// Avatar R2 torso golden (D-092) — the visual baseline for the accepted Ridderdragt (D-091).
// SELF-SERVED + FIXTURE-INTERCEPTED (0 real backend from this spec, fictitious local fixtures).
//
// WHAT THIS MATRIX IS FOR, and why its columns are what they are:
// D-091 accepted the armour with one recorded observation — at the smallest render sizes its
// silhouette is close to the base tee's, so it reads as a grey shirt with a belt. The
// `legible-at-render-sizes` gate could never see that: it measures COVERAGE of the mandatory
// region, not DISTINGUISHABILITY from wearing nothing. This baseline puts "no item" beside
// "armour" at every D-071 size precisely so that difference is the thing under review, and so a
// future regression in it fails loudly instead of passing a coverage check.
//
// The third column (armour + headwear + eyes) guards the z-order: the garment sits at z1, under
// every face layer and far under hair 40 / headwear 45.
//
// Chromium only, per the established golden convention; baselines are per platform
// (-chromium-linux / -chromium-win32) and the Linux ones are regenerated by
// .github/workflows/update-avatar-goldens.yml, never by hand.
import { test, expect, Route } from "@playwright/test";
import * as http from "http";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const MIME: Record<string, string> = { ".html": "text/html", ".js": "text/javascript", ".mjs": "text/javascript", ".svg": "image/svg+xml", ".css": "text/css", ".webp": "image/webp", ".png": "image/png", ".json": "application/json" };
const MATRIX = '<!doctype html><meta charset=utf-8><style>.mx-layer{position:absolute;inset:0;width:100%;height:100%}body{margin:0;background:#1a1c24}</style><body></body>';

let server: http.Server; let baseUrl: string;
test.beforeAll(async () => {
  server = http.createServer((req, res) => {
    const p = decodeURIComponent((req.url || "/").split("?")[0]);
    if (p === "/_matrix.html") { res.writeHead(200, { "content-type": "text/html" }); res.end(MATRIX); return; }
    try {
      const fp = path.normalize(path.join(ROOT, p === "/" ? "/index.html" : p));
      if (!fp.startsWith(ROOT)) { res.writeHead(403); res.end(); return; }
      const data = fs.readFileSync(fp);
      res.writeHead(200, { "content-type": MIME[path.extname(fp).toLowerCase()] || "application/octet-stream" });
      res.end(data);
    } catch { res.writeHead(404); res.end("nf"); }
  });
  await new Promise<void>((r) => server.listen(0, r));
  baseUrl = `http://localhost:${(server.address() as any).port}`;
});
test.afterAll(async () => { await new Promise<void>((r) => server.close(() => r())); });

const CORS = { "access-control-allow-origin": "*", "access-control-allow-headers": "*", "access-control-allow-methods": "GET,POST,PATCH,PUT,DELETE,OPTIONS" };
// The matrix composes layers directly through the render module, so the only backend the page can
// reach is stubbed to empty — nothing here reads a profile.
const stubRoute = async (route: Route) => {
  if (route.request().method() === "OPTIONS") return route.fulfill({ status: 204, headers: CORS });
  return route.fulfill({ status: 200, headers: { ...CORS, "content-type": "application/json" }, body: "[]" });
};

const ARMOR = "/assets/avatar/shirt/armor-knight.svg";
const ARMOR_R2 = "/assets/avatar-r2/torso/armor-knight-r2-v1.webp";
const HAT = "/assets/avatar/hat/crown-golden.svg";
const GLASSES = "/assets/avatar/glasses/glasses-round-basic-v1.svg";

test("golden: R2 torso matrix (no item · Ridderdragt · Ridderdragt + headwear + eyes)", async ({ browser, browserName }) => {
  const ctx = await browser.newContext({ viewport: { width: 760, height: 720 }, reducedMotion: "reduce" });
  await ctx.route("**://*.supabase.co/**", stubRoute);
  await ctx.addInitScript(() => localStorage.setItem("avatar_r2", "1"));
  const page = await ctx.newPage();
  await page.goto(`${baseUrl}/_matrix.html`, { waitUntil: "networkidle" });

  const info = await page.evaluate(async ([armor, hat, glasses]: string[]) => {
    const mod: any = await import("/js/avatar-render-c2.js");
    const id = { v: 1, body_type: "neutral", skin_tone: "medium", hairstyle: "tousled", hair_color: "brown" };
    // The four D-071 render sizes the garment has to survive (2:3 avatar-canvas aspect).
    const SIZES = [
      { name: "avatar 180", w: 180, h: 270 },
      { name: "hub 112", w: 112, h: 168 },
      { name: "quiz 72", w: 72, h: 108 },
      { name: "min 52", w: 52, h: 78 },
    ];
    const COLS = [
      { name: "no item", cos: [] as any[] },
      { name: "Ridderdragt", cos: [{ slot: "torso", src: armor, z: 20 }] },
      { name: "+ headwear/eyes", cos: [{ slot: "torso", src: armor, z: 20 }, { slot: "headwear", src: hat, z: 30 }, { slot: "eyes", src: glasses, z: 25 }] },
    ];
    document.body.style.cssText = "margin:0;background:#1a1c24;color:#c9cfdd;font:12px/1.3 system-ui,sans-serif;padding:16px";
    const label = (text: string) => { const el = document.createElement("div"); el.style.cssText = "white-space:pre-line;text-align:center;align-self:center;justify-self:center"; el.textContent = text; return el; };
    const grid = document.createElement("div");
    grid.style.cssText = "display:inline-grid;grid-template-columns:auto repeat(3,max-content);gap:12px 14px;align-items:end;justify-items:center";
    grid.appendChild(label(""));
    for (const c of COLS) grid.appendChild(label(c.name));
    const out: any[] = [];
    for (const size of SIZES) {
      grid.appendChild(label(size.name));
      for (const col of COLS) {
        const cell = document.createElement("div");
        cell.style.cssText = `position:relative;width:${size.w}px;height:${size.h}px`;
        grid.appendChild(cell);
        const rp = await mod.mountC2Avatar(cell, id, { layerClass: "mx-layer", cosmetics: col.cos, surface: "avatar" });
        const srcs = Array.from(cell.querySelectorAll("img")).map((i: any) => i.getAttribute("src") || "");
        const torso = cell.querySelector('[data-c2-layer="torso-cosmetic"]') as HTMLElement | null;
        out.push({
          tag: `${size.name} / ${col.name}`,
          rp,
          hasTorsoR2: srcs.some((s) => s.includes("armor-knight-r2-v1.webp")),
          hasArmorC2: srcs.some((s) => s.includes("armor-knight.svg")),
          // Inline style, as the render sets it and as the headwear golden reads it — the computed
          // value depends on the surrounding stacking context and would not be the layer's own z.
          torsoZ: torso ? Number(torso.style.zIndex) : null,
          broken: Array.from(cell.querySelectorAll("img")).filter((i: any) => i.complete && i.naturalWidth === 0).length,
        });
      }
    }
    document.body.appendChild(grid);
    return out;
  }, [ARMOR, HAT, GLASSES]);

  for (const it of info) {
    expect(it.rp, `${it.tag}: R2`).toBe("r2");
    expect(it.broken, `${it.tag}: no broken images`).toBe(0);
    expect(it.hasArmorC2, `${it.tag}: no C2 armour leak`).toBeFalsy();
    if (it.tag.includes("no item")) {
      expect(it.hasTorsoR2, `${it.tag}: nothing equipped → no garment`).toBeFalsy();
    } else {
      expect(it.hasTorsoR2, `${it.tag}: the R2 garment renders`).toBeTruthy();
      expect(it.torsoZ, `${it.tag}: garment z above base, below the face stack`).toBe(1);
    }
  }

  // Wait for the garment bitmaps to finish decoding before the baseline is taken; mountC2Avatar
  // resolves on the atomic preload, but the browser still has to paint them.
  await page.waitForFunction(() => Array.from(document.images).every((i) => i.complete));
  if (browserName === "chromium") {
    await expect(page.locator("body")).toHaveScreenshot("r2-torso-matrix.png", { maxDiffPixels: 400, animations: "disabled" });
  }
  await ctx.close();
});
