// Avatar R2 render goldens (activation-audit F4). Permanent pixel baselines for
// the DECOMPOSED R2 raster stack (neutral × medium — the only R2-supported identity)
// on the avatar page, hub and quiz. Until now every avatar golden captured the C2
// path (AVATAR_R2=false); these are the first R2 baselines, so a future change to an
// R2 layer or the render path is caught by pixel regression.
//
// R2 is opted-in PER TEST BROWSER via localStorage (avatar_v2=1 + avatar_r2=1); the
// global AVATAR_R2 flag stays false. Reduced motion suppresses blink/presence/
// expression (js/avatar-blink-engine.js §"Suppressed under prefers-reduced-motion"),
// so the eyes/face are static → deterministic. chromium-only; baselines committed
// for chromium-win32 + chromium-linux (the latter regenerated by the manual
// Update-Avatar-Goldens workflow). Goldens live in
// tests/avatar-r2-render.spec.ts-snapshots/.

import { test, expect } from "@playwright/test";
import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
import { fileURLToPath } from "url";
import * as path from "path";
import { PROD } from "./helpers.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.resolve(__dirname, "../.env") });

const STUDENT_EMAIL = process.env.TEST_STUDENT_EMAIL!;
const STUDENT_PASS  = process.env.TEST_STUDENT_PASSWORD!;
const SUPABASE_URL  = process.env.SUPABASE_URL!;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;
const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqemJlaHdmYWdpd3B3b2RzZ3dnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE2ODc5OTQsImV4cCI6MjA4NzI2Mzk5NH0.BzepnYLe6Khzqx9vTL3Ifa_zMRgjoGQ9Lw5seaoKMMc";

let adminClient: ReturnType<typeof createClient>;
let studentId: string;

const NEUTRAL_MEDIUM = () => ({ v: 1, body_type: "neutral", hairstyle: "tousled", skin_tone: "medium", hair_color: "brown", chosen_at: new Date().toISOString() });
const BASE_IDENTITY  = () => ({ v: 1, body_type: "neutral", hairstyle: "default", skin_tone: "medium", chosen_at: new Date().toISOString() });

test.beforeAll(async () => {
  adminClient = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, { auth: { autoRefreshToken: false, persistSession: false } });
  const loginClient = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, { auth: { autoRefreshToken: false, persistSession: false } });
  const { data: session, error } = await loginClient.auth.signInWithPassword({ email: STUDENT_EMAIL, password: STUDENT_PASS });
  if (error || !session.session) throw new Error(`Student sign-in failed: ${error?.message}`);
  studentId = session.user!.id;
});

// Per-browser R2 opt-in (+ C2 pipeline enable). Runs before every page script.
test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => {
    try { localStorage.setItem("avatar_v2", "1"); localStorage.setItem("avatar_r2", "1"); } catch (e) {}
  });
});

test.afterAll(async () => {
  // Restore the shared student to the default identity + empty cosmetics.
  await adminClient.from("profiles").update({ equipped_slots: {}, avatar_identity: BASE_IDENTITY() }).eq("id", studentId);
});

async function setIdentity(identity: object) {
  const { error } = await adminClient.from("profiles").update({ avatar_identity: identity }).eq("id", studentId);
  if (error) throw new Error(`identity fixture failed: ${error.message}`);
}

async function loginReduced(page: any) {
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto(`${PROD}/login.html`, { waitUntil: "domcontentloaded" });
  await page.fill("#email", STUDENT_EMAIL);
  await page.fill("#password", STUDENT_PASS);
  await page.locator("#loginBtn").click();
  await page.waitForURL(`${PROD}/index.html`, { timeout: 20000 });
}

// Wait for the app render-complete signal + assert the R2 stack (not C2) is active,
// so the golden can never silently bake in a C2 fallback.
async function waitForR2(page: any, selector: string) {
  await page.waitForSelector(`${selector}[data-avatar-rendered="1"]`, { timeout: 15000 });
  await expect(page.locator(`${selector} img[data-c2-layer="base"][src*="avatar-r2/base/body-neutral-medium-v2.webp"]`),
    "R2 base must be the active render (opt-in resolved)").toBeAttached({ timeout: 10000 });
  await page.waitForFunction(
    (sel: string) => {
      const imgs = Array.from(document.querySelectorAll(sel + " img"));
      return imgs.length > 0 && imgs.every((i: any) => i.complete && i.naturalWidth > 0);
    },
    selector,
    { timeout: 15000 }
  );
}

test("golden: R2 avatar page (neutral-medium) matches baseline", async ({ page, browserName }) => {
  test.skip(browserName !== "chromium", "golden baselines are chromium-only");
  await setIdentity(NEUTRAL_MEDIUM());
  await loginReduced(page);
  await page.goto(`${PROD}/avatar.html`, { waitUntil: "domcontentloaded" });
  await page.waitForSelector("#skinToneButtons .identity-btn", { timeout: 15000 });
  await waitForR2(page, "#avatar-preview");
  await expect(page.locator("#avatar-preview")).toHaveScreenshot("r2-avatar-page-neutral-medium.png", { maxDiffPixels: 250, animations: "disabled" });
});

test("golden: R2 hub avatar (neutral-medium) matches baseline", async ({ page, browserName }) => {
  test.skip(browserName !== "chromium", "golden baselines are chromium-only");
  await setIdentity(NEUTRAL_MEDIUM());
  await loginReduced(page);
  await page.goto(`${PROD}/hub.html`, { waitUntil: "domcontentloaded" });
  await page.waitForSelector("#profileAvatar img", { timeout: 15000 });
  await waitForR2(page, "#profileAvatar");
  await expect(page.locator("#profileAvatar")).toHaveScreenshot("r2-hub-avatar-neutral-medium.png", { maxDiffPixels: 150, animations: "disabled" });
});

test("golden: R2 quiz avatar (neutral-medium) matches baseline", async ({ page, browserName }) => {
  test.skip(browserName !== "chromium", "golden baselines are chromium-only");
  await setIdentity(NEUTRAL_MEDIUM());
  await loginReduced(page);
  // Already on index.html (quiz) after login; the quiz avatar mounts on #avatar-display.
  await waitForR2(page, "#avatar-display");
  await expect(page.locator("#avatar-display")).toHaveScreenshot("r2-quiz-avatar-neutral-medium.png", { maxDiffPixels: 120, animations: "disabled" });
});
