-- Section 149 — revolutions_democracy Grade 7 Band Coverage Fix
-- Fixes grade-7 B5 starvation and thin pool for revolutions_democracy.
-- NOTE: This does NOT reach the 60-question capacity target.
--       Partial improvement only: 25 → 45 grade-7 questions.
--
-- Adds 20 questions: learning_objective=revolutions_democracy,
--   target_grade=7, is_active=true
-- Distribution: B1×2 B2×4 B3×5 B4×5 B5×4
--
-- Before: G7 total=25 (B1:6 B2:7 B3:7 B4:5 B5:0)
-- After:  G7 total=45 (B1:8 B2:11 B3:12 B4:10 B5:4)
--
-- Topics: French Revolution definition, three estates, liberty/equality/fraternity,
--   causes of 1789, execution of Louis XVI, American Declaration of Independence,
--   Skrækveldet/the Terror, American→French inspiration, revolution vs reform,
--   Napoleon's rise, women excluded from revolutionary rights,
--   revolution devouring its leaders, American Revolution and slavery,
--   French revolutionary ideas spreading, 1848 revolutions failing,
--   long-term democratic legacy, historiographic social vs political debate,
--   Napoleon as heir or betrayal, Terror—necessary or avoidable,
--   revolution and democracy comparative outcomes

-- ─── BAND 1 (2 questions) ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad var Den Franske Revolution?","options":["En folkeopstand i Frankrig fra 1789 hvor borgere og bønder væltede kongedømmets enevælde og krævede frihed, lighed og folkets ret til at bestemme","En krig mellem Frankrig og England om hvem der skulle styre Europa","En religiøs bevægelse hvor franskmændene skiftede fra katolsk til protestantisk tro","Et fredeligt valg i Frankrig hvor kongen frivilligt gav magten til folket"],"correct":"En folkeopstand i Frankrig fra 1789 hvor borgere og bønder væltede kongedømmets enevælde og krævede frihed, lighed og folkets ret til at bestemme","accepted_answers":["En folkeopstand i Frankrig fra 1789 hvor borgere og bønder væltede kongedømmets enevælde og krævede frihed, lighed og folkets ret til at bestemme"],"review_text":"Den Franske Revolution begyndte i 1789 da det franske folk rejste sig mod kong Ludvig XVI og det gamle system, hvor adelen og kirken havde al magten, mens bønderne og borgerne betalte alle skatterne. Revolutionen ændrede Frankrig og hele verden — for første gang krævede et folk i stor skala frihed og lighed som rettigheder for alle borgere."}$$::jsonb,
  'mc','short',$${"concepts":["Fransk Revolution","folkeopstand","enevælde","frihed","lighed"],"misconception_type":"surface_association","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',1,'auto',true,'revolutions_democracy',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Frankrig før 1789 var delt i tre stænder. Hvad var tredjestanden?","options":["Alle borgere og bønder — langt de fleste franskmænd — som betalte skat men ikke havde politisk magt","Adelen som ikke betalte skat og boede ved hoffet hos kongen","Præster og biskopper fra den katolske kirke","Soldaterne i den franske hær"],"correct":"Alle borgere og bønder — langt de fleste franskmænd — som betalte skat men ikke havde politisk magt","accepted_answers":["Alle borgere og bønder — langt de fleste franskmænd — som betalte skat men ikke havde politisk magt"],"review_text":"Den franske befolkning var delt i tre stænder: præsterne (første stand), adelen (anden stand) og alle andre (tredjestanden) — bønder, håndværkere, købmænd og simple borgere. Tredjestanden udgjorde over 97 procent af befolkningen men betalte næsten al skatten og havde ingen reel indflydelse. Det var denne ulighed der var brændstof under revolutionen."}$$::jsonb,
  'mc','short',$${"concepts":["tredjestand","stænder","ulighed","skat","feudalsystem"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',1,'auto',true,'revolutions_democracy',7,1
);

-- ─── BAND 2 (4 questions) ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad betyder de tre revolutionære idealer 'frihed, lighed og broderskab'?","options":["At alle borgere har de samme rettigheder, ingen er hævet over loven, og samfundet tager ansvar for hinanden som borgere — ikke som undersåtter under en enevældig konge","At kongen deler sin magt ligeligt med adelen og kirken","At Frankrig skulle erobre andre lande og sprede sin kultur","At alle franskmænd skulle have ens løn og ens ejendom"],"correct":"At alle borgere har de samme rettigheder, ingen er hævet over loven, og samfundet tager ansvar for hinanden som borgere — ikke som undersåtter under en enevældig konge","accepted_answers":["At alle borgere har de samme rettigheder, ingen er hævet over loven, og samfundet tager ansvar for hinanden som borgere — ikke som undersåtter under en enevældig konge"],"review_text":"Frihed, lighed og broderskab er Den Franske Revolutions tre grundidealer. Frihed: borgerne har rettigheder staten ikke må krænke. Lighed: alle er lige for loven — ingen adel hævet over reglerne. Broderskab: vi er alle borgere i det samme samfund og støtter hinanden. Disse tre idealer er stadig grundlaget for moderne demokrati."}$$::jsonb,
  'mc','short',$${"concepts":["frihed","lighed","broderskab","borgerrettigheder","demokrati"],"misconception_type":"overgeneralization","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"concept_clarification","challenge_role":"reinforcement","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',2,'auto',true,'revolutions_democracy',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad var den vigtigste årsag til at franskmændene rejste sig i revolution i 1789?","options":["Den store ulighed — tredjestanden sultede under en dårlig høst og betalte alle skatter, mens adelen og kongehuset levede i luksus uden at bidrage","Frankrig tabte en krig og folket var vred på kongen for at have mistet territorier","En religiøs konflikt mellem katolikker og protestanter eskalerede til åbent oprør","Kongen forsøgte at afskaffe adelen og adelen rejste sig i protest"],"correct":"Den store ulighed — tredjestanden sultede under en dårlig høst og betalte alle skatter, mens adelen og kongehuset levede i luksus uden at bidrage","accepted_answers":["Den store ulighed — tredjestanden sultede under en dårlig høst og betalte alle skatter, mens adelen og kongehuset levede i luksus uden at bidrage"],"review_text":"I 1788-89 var der misvækst i Frankrig og millioner sultede. Statskassen var tom og kongen krævede nye skatter af tredjestanden, som i forvejen betalte alt. Oplysningstidens ideer om lighed og rettigheder gav folk et sprog for deres vrede. Kombinationen af sult, ulighed og nye ideer udløste revolutionen."}$$::jsonb,
  'mc','short',$${"concepts":["ulighed","skat","misvækst","oplysningstidens ideer","revolution"],"misconception_type":"causal_confusion","cognitive_skill":"comprehension","difficulty_type":"causal","insight_type":"concept_clarification","challenge_role":"reinforcement","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',2,'auto',true,'revolutions_democracy',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad skete der med den franske kong Ludvig XVI under revolutionen?","options":["Han blev anklaget for forræderi og henrettet ved guillotinen i januar 1793 — et dramatisk brud med forestillingen om kongens guddommelige ret til at regere","Han abdicerede frivilligt og levede resten af livet som almindelig borger i Frankrig","Han flygtede til England og organiserede derfra en invasion for at genvinde tronen","Han blev fængslet men aldrig henrettet — revolutionære valgte at holde ham som gidsel"],"correct":"Han blev anklaget for forræderi og henrettet ved guillotinen i januar 1793 — et dramatisk brud med forestillingen om kongens guddommelige ret til at regere","accepted_answers":["Han blev anklaget for forræderi og henrettet ved guillotinen i januar 1793 — et dramatisk brud med forestillingen om kongens guddommelige ret til at regere"],"review_text":"Kong Ludvig XVI blev henrettet den 21. januar 1793. Det var et af de mest symbolsk kraftfulde øjeblikke i verdenshistorien — kongen var ikke længere hellig og uantastelig. At guillotinere en monark sendte et chokerende signal til alle Europas konger: folket kunne fjerne dem. Det gav revolutionen en ny og mere radikal karakter."}$$::jsonb,
  'mc','short',$${"concepts":["Ludvig XVI","guillotine","monarkiets afskaffelse","symbolik","henrettelse"],"misconception_type":"false_memory","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"perspective_shift","challenge_role":"reinforcement","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',2,'auto',true,'revolutions_democracy',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad fastslår den amerikanske Uafhængighedserklæring fra 1776?","options":["At alle mennesker er skabt lige og har umistelige rettigheder — til liv, frihed og stræben efter lykke — og at en retfærdig regering kun har magt med borgernes samtykke","At USA skulle regeres af en valgt kongemagt med stærk centralmagt","At kun hvide mænd med ejendom har politiske rettigheder og kan deltage i demokratiet","At Storbritannien og USA skulle deles ligeligt om Nordamerika"],"correct":"At alle mennesker er skabt lige og har umistelige rettigheder — til liv, frihed og stræben efter lykke — og at en retfærdig regering kun har magt med borgernes samtykke","accepted_answers":["At alle mennesker er skabt lige og har umistelige rettigheder — til liv, frihed og stræben efter lykke — og at en retfærdig regering kun har magt med borgernes samtykke"],"review_text":"Den amerikanske Uafhængighedserklæring fra 1776 er et af historiens mest indflydelsesrige dokumenter. Den proklamerer at rettigheder ikke gives af en konge — de er naturlige og umistelige. At regeringen kun er legitim når borgerne accepterer den. Disse ideer inspirerede direkte Den Franske Revolution 13 år senere."}$$::jsonb,
  'mc','short',$${"concepts":["Uafhængighedserklæringen","rettigheder","lighed","samtykke","USA"],"misconception_type":"scope_confusion","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',2,'auto',true,'revolutions_democracy',7,2
);

-- ─── BAND 3 (5 questions) ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad var 'Skrækveldet' under Den Franske Revolution, og hvorfor opstod det?","options":["En periode i 1793-94 hvor den radikale regering henrettede tusindvis af påståede fjender af revolutionen — skabt af frygt for invasion udefra og kontrarevolution indefra","En invasionskrig fra Østrig og Preussen der midlertidigt besatte Paris og henrettede revolutionære ledere","En hungersnød der dræbte tusindvis af parisiske borgere i revolutionens første år","En planlagt terroraktion fra kongens tilhængere for at destabilisere den nye regering"],"correct":"En periode i 1793-94 hvor den radikale regering henrettede tusindvis af påståede fjender af revolutionen — skabt af frygt for invasion udefra og kontrarevolution indefra","accepted_answers":["En periode i 1793-94 hvor den radikale regering henrettede tusindvis af påståede fjender af revolutionen — skabt af frygt for invasion udefra og kontrarevolution indefra"],"review_text":"Skrækveldet var en periode under Robespierre (1793-94) hvor frihedens fjender — reelle og påståede — blev guillotineret. Over 17.000 blev henrettet. Det opstod i en situation med krig mod det meste af Europa, royalistisk oprør i Vendée og paranoia om forrædere inden for revolutionen. Skrækveldet viser hvordan revolutioner under pres kan vende sig mod egne borgere."}$$::jsonb,
  'mc','short',$${"concepts":["Skrækveldet","Robespierre","guillotine","frygt","kontrarevolution"],"misconception_type":"causal_inversion","cognitive_skill":"application","difficulty_type":"causal","insight_type":"concept_clarification","challenge_role":"reasoning_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',3,'auto',true,'revolutions_democracy',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvordan inspirerede den amerikanske revolution Den Franske Revolution?","options":["Amerikanerne beviste at det var muligt at vælte en monark og danne en regering baseret på borgernes rettigheder og samtykke — det viste franskmændene at grundlæggende forandring var opnåelig","Amerika sendte soldater og våben til Frankrig for at hjælpe revolutionærerne i kampen mod kongen","Den franske revolution begyndte som en direkte reaktion på Englands forsøg på at inddrage Frankrig i den amerikanske konflikt","Amerika og Frankrig planlagde revolutionerne i fællesskab gennem hemmelige diplomatiske forbindelser"],"correct":"Amerikanerne beviste at det var muligt at vælte en monark og danne en regering baseret på borgernes rettigheder og samtykke — det viste franskmændene at grundlæggende forandring var opnåelig","accepted_answers":["Amerikanerne beviste at det var muligt at vælte en monark og danne en regering baseret på borgernes rettigheder og samtykke — det viste franskmændene at grundlæggende forandring var opnåelig"],"review_text":"Den amerikanske revolution (1776) viste verden at enevælde ikke var uundgåeligt. Lafayette og andre franskmænd kæmpede i Amerika og vendte hjem med nye ideer. Erklæringen om umistelige rettigheder og folkestyre inspirerede direkte de franske revolutionære. Mange af deres formuleringer minder meget om den amerikanske Uafhængighedserklæring."}$$::jsonb,
  'mc','short',$${"concepts":["inspiration","rettigheder","Lafayette","folkestyre","eksempel"],"misconception_type":"false_mechanism","cognitive_skill":"application","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"reasoning_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',3,'auto',true,'revolutions_democracy',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er den afgørende forskel på en revolution og en reform?","options":["En revolution bryder grundlæggende med det eksisterende system og sker typisk hurtigt og med vold, mens en reform ændrer dele af systemet indefra gennem lovlig proces og gradvis forandring","En revolution foregår altid med våbenmagt mens en reform er en fredelig folkeafstemning","Reformer ændrer mere end revolutioner — de omstrukturerer hele samfund over tid","Der er ingen reel forskel — begge ord beskriver hurtige politiske forandringer"],"correct":"En revolution bryder grundlæggende med det eksisterende system og sker typisk hurtigt og med vold, mens en reform ændrer dele af systemet indefra gennem lovlig proces og gradvis forandring","accepted_answers":["En revolution bryder grundlæggende med det eksisterende system og sker typisk hurtigt og med vold, mens en reform ændrer dele af systemet indefra gennem lovlig proces og gradvis forandring"],"review_text":"En revolution er et grundlæggende brud — den gamle orden væltes og nye magtstrukturer skabes. En reform ændrer dele af systemet men bevarer det grundlæggende. Revolutioner er typisk hurtigere, mere voldsomme og mere usikre i deres konsekvenser. Reformer er langsommere men mere forudsigelige. I politisk debat er spørgsmålet om reform eller revolution stadig centralt."}$$::jsonb,
  'mc','short',$${"concepts":["revolution","reform","brud","gradvis forandring","vold"],"misconception_type":"false_equivalence","cognitive_skill":"application","difficulty_type":"conceptual","insight_type":"concept_clarification","challenge_role":"reasoning_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',3,'auto',true,'revolutions_democracy',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvorfor lykkedes det Napoleon Bonaparte at overtage magten i Frankrig efter revolutionen?","options":["Frankrig var præget af politisk kaos og intern splittelse efter Skrækveldet — Napoleon tilbød stabilitet, orden og militær styrke på et tidspunkt, hvor franskmændene var trætte af usikkerhed","Napoleon var en direkte arving til den franske trone og overtog magten lovmæssigt","Napoleon vandt en folkeafstemning fordi han lovede at genindføre kongedømmet og give adelen magten tilbage","Napoleon blev inviteret af revolutionens ledere til at overtage fordi de ikke selv ønskede den politiske magt"],"correct":"Frankrig var præget af politisk kaos og intern splittelse efter Skrækveldet — Napoleon tilbød stabilitet, orden og militær styrke på et tidspunkt, hvor franskmændene var trætte af usikkerhed","accepted_answers":["Frankrig var præget af politisk kaos og intern splittelse efter Skrækveldet — Napoleon tilbød stabilitet, orden og militær styrke på et tidspunkt, hvor franskmændene var trætte af usikkerhed"],"review_text":"Efter Skrækveldet var Frankrig ustabilt. Mange franskmænd var trætte af politisk kaos og ønskede orden. Napoleon var en genial militærleder der vandt store sejre. I 1799 gennemførte han et statskup med hærens støtte. Han tilbød det franskmændene savnede: stærk ledelse og stabilitet. Det er et klassisk mønster — kaotiske revolutioner baner ofte vejen for stærke ledere."}$$::jsonb,
  'mc','short',$${"concepts":["Napoleon","kaos","stabilitet","statskup","militær ledelse"],"misconception_type":"false_authority","cognitive_skill":"application","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"reasoning_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',3,'auto',true,'revolutions_democracy',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Kvinder deltog aktivt i Den Franske Revolution. Hvorfor fik de alligevel ikke de rettigheder revolutionen proklamerede?","options":["Revolutionens ledere mente at rettigheder som frihed og lighed primært gjaldt mænd som borgere — kvinder blev set som hustruer og mødre, ikke som politiske aktører med selvstændige rettigheder","Kvinder var ikke interesserede i politiske rettigheder og valgte selv at holde sig uden for den politiske sfære","Den franske forfatning fra 1791 gav faktisk kvinder stemmeret, men den blev aldrig implementeret i praksis","Kvinder fik alle civile rettigheder men ikke politiske rettigheder — det var en bevidst og logisk opdeling"],"correct":"Revolutionens ledere mente at rettigheder som frihed og lighed primært gjaldt mænd som borgere — kvinder blev set som hustruer og mødre, ikke som politiske aktører med selvstændige rettigheder","accepted_answers":["Revolutionens ledere mente at rettigheder som frihed og lighed primært gjaldt mænd som borgere — kvinder blev set som hustruer og mødre, ikke som politiske aktører med selvstændige rettigheder"],"review_text":"Olympe de Gouges skrev i 1791 sit svar på den officielle erklæring som udelukkede kvinder. Hun blev guillotineret i 1793. Revolutionen proklamerede universelle rettigheder men definerede universelt som mænd. Det viser at selv radikale forandringer kan reproducere eksisterende fordomme — revolutionens idealer om lighed var ikke fuldt konsekvente."}$$::jsonb,
  'mc','short',$${"concepts":["kvinders rettigheder","Olympe de Gouges","køn","ekskludering","universel lighed"],"misconception_type":"victim_blaming","cognitive_skill":"application","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"reasoning_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',3,'auto',true,'revolutions_democracy',7,3
);

-- ─── BAND 4 (5 questions) ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Skrækveldet fik mange af de originale revolutionære ledere guillotineret — til sidst også Robespierre selv. Hvad forklarer bedst dette mønster?","options":["I ekstreme revolutionære situationer skaber frygten for forræderi et system der hele tiden søger nye indre fjender — ingen er sikre og selv loyale revolutionære kan anklages og dø","Robespierre og de andre ledere var faktisk royalister der arbejdede imod revolutionen og retfærdigt blev straffet","Revolutionsdomstolene var korrumperede og dømte folk for penge — det var ikke politisk men kriminelt","Det var tilfældig ulykke at netop disse ledere blev ofre — det kunne have ramt andre ligeså let"],"correct":"I ekstreme revolutionære situationer skaber frygten for forræderi et system der hele tiden søger nye indre fjender — ingen er sikre og selv loyale revolutionære kan anklages og dø","accepted_answers":["I ekstreme revolutionære situationer skaber frygten for forræderi et system der hele tiden søger nye indre fjender — ingen er sikre og selv loyale revolutionære kan anklages og dø"],"review_text":"Mønsteret 'revolutionen æder sine egne børn' er historisk genkommende. Under Skrækveldet lod Robespierre sine egne allierede henrette (Danton m.fl.) — og endte selv guillotineret i 1794. Mekanismen er paranoia kombineret med magtkonkurrence: en anklage om forræderi er dødelig, og politiske rivaler bruger systemet til at eliminere hinanden. Det er et systemisk problem, ikke individuel ondskab."}$$::jsonb,
  'mc','short',$${"concepts":["Skrækveldet","paranoia","Robespierre","magtkonkurrence","systemisk vold"],"misconception_type":"character_flaw","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"concept_clarification","challenge_role":"reasoning_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',4,'auto',true,'revolutions_democracy',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Den amerikanske Uafhængighedserklæring proklamerede at alle mennesker er skabt lige. Alligevel afskaffede den amerikanske revolution ikke slaveriet. Hvad er den bedste forklaring?","options":["De fleste af revolutionens ledere — herunder Jefferson og Washington — var selv slaveejere og tog slaveriet for givet; 'alle mennesker' betød i praksis hvide mænd med ejendom","Slaveriet var så dybt forankret i den amerikanske økonomi at selv modstandere indrømmede at det ikke kunne afskaffes med ét slag","Det var en bevidst logisk undtagelse: grundlæggerne anerkendte eksplicit at afrikanere ikke var dækket af erklæringens rettigheder","Grundlæggerne planlagde en gradvis afskaffelse, men borgerkrigen brød ud inden den kunne gennemføres"],"correct":"De fleste af revolutionens ledere — herunder Jefferson og Washington — var selv slaveejere og tog slaveriet for givet; 'alle mennesker' betød i praksis hvide mænd med ejendom","accepted_answers":["De fleste af revolutionens ledere — herunder Jefferson og Washington — var selv slaveejere og tog slaveriet for givet; 'alle mennesker' betød i praksis hvide mænd med ejendom"],"review_text":"Thomas Jefferson der skrev 'alle mennesker er skabt lige' ejede selv hundredvis af slaver. 'Alle mennesker' betød i praksis hvide mænd med ejendom. Slaveriet var grundlæggernes blinde plet eller bevidste kompromis. Det viser at selv revolutioner der proklamerer universelle idealer kan have massive undtagelser styret af de revolutionæres egne interesser og fordomme."}$$::jsonb,
  'mc','short',$${"concepts":["slaveri","Jefferson","Washington","universelle rettigheder","blinde pletter"],"misconception_type":"economic_determinism","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"reasoning_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',4,'auto',true,'revolutions_democracy',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvordan spredte Den Franske Revolutions ideer sig til resten af Europa efter 1789?","options":["Både gennem Napoleons erobringer der nedbrød den feudale orden i store dele af Europa, og gennem skrifter og intellektuelle der inspirerede liberale og nationale bevægelser overalt","Den franske revolution spredte sig kun til lande der grænser op til Frankrig og havde ingen effekt andetsteds","Ideerne spredte sig udelukkende gennem hemmelige revolutionære organisationer der planlagde oprør i hvert land","Frankrig tvang besejrede lande til at vedtage den franske forfatning som betingelse for fredsaftaler"],"correct":"Både gennem Napoleons erobringer der nedbrød den feudale orden i store dele af Europa, og gennem skrifter og intellektuelle der inspirerede liberale og nationale bevægelser overalt","accepted_answers":["Både gennem Napoleons erobringer der nedbrød den feudale orden i store dele af Europa, og gennem skrifter og intellektuelle der inspirerede liberale og nationale bevægelser overalt"],"review_text":"Napoleons felttog rev feudalsystemet ned i Polen, Spanien, Italien og de tyske stater. Code Napoléon afskaffede adelsprivilegier og indførte juridisk lighed. Samtidig spredte pamfletter og intellektuelle revolutionens ideer til liberale i hele Europa. Det 19. århundrede fyldes af revolutioner og nationale opstande direkte inspireret af 1789."}$$::jsonb,
  'mc','short',$${"concepts":["Napoleon","Code Napoléon","spredning","liberalisme","nationalisme"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"concept_clarification","challenge_role":"reasoning_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',4,'auto',true,'revolutions_democracy',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"I 1848 brød revolutioner ud i næsten hele Europa. De fleste slog fejl inden for et år. Hvad er den vigtigste forklaring?","options":["De revolutionære var en løs koalition af liberale, nationalister og arbejdere med modsatrettede mål — da den første fare var ovre splittedes de og de etablerede magter genvandt kontrollen","1848-revolutionerne slog fejl fordi de manglede militær støtte fra andre lande og hvert land kæmpede alene","Den katolske kirke mobiliserede massivt imod revolutionerne og overbeviste bondestanden om at modsætte sig forandring","Revolutionerne slog fejl fordi de primært var ledet af uerfarne studenter uden politisk erfaring"],"correct":"De revolutionære var en løs koalition af liberale, nationalister og arbejdere med modsatrettede mål — da den første fare var ovre splittedes de og de etablerede magter genvandt kontrollen","accepted_answers":["De revolutionære var en løs koalition af liberale, nationalister og arbejdere med modsatrettede mål — da den første fare var ovre splittedes de og de etablerede magter genvandt kontrollen"],"review_text":"1848-revolutionerne havde mange mål: liberale ville have forfatninger, nationalister ville have nationale stater, arbejdere ville have sociale reformer. Da de konservative styrer gav minimale indrømmelser splittedes koalitionen. Liberale frygtede arbejderrevolution mere end konservatisme. Magthaverne genvandt kontrollen. Fragmenterede koalitioner med modstridende mål er svage."}$$::jsonb,
  'mc','short',$${"concepts":["1848","koalition","splittelse","liberalisme","nationalisme"],"misconception_type":"single_cause","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"concept_clarification","challenge_role":"reasoning_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',4,'auto',true,'revolutions_democracy',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er den vigtigste langsigtede arv fra Den Franske Revolution for moderne demokrati?","options":["Ideen om at regeringsmagten kun er legitim når den er baseret på borgernes rettigheder og samtykke — og at folket kan afsætte regeringer der krænker disse rettigheder","At Frankrig fik en stabil demokratisk forfatning der har holdt uændret siden 1789","At guillotinen som henrettelsesmetode erstattede de brutale offentlige henrettelser der ellers var normen","At konger og adel verden over frivilligt opgav deres privilegier som reaktion på revolutionens budskab"],"correct":"Ideen om at regeringsmagten kun er legitim når den er baseret på borgernes rettigheder og samtykke — og at folket kan afsætte regeringer der krænker disse rettigheder","accepted_answers":["Ideen om at regeringsmagten kun er legitim når den er baseret på borgernes rettigheder og samtykke — og at folket kan afsætte regeringer der krænker disse rettigheder"],"review_text":"Revolutionens dybeste arv er forestillingen om folkesuverænitet: magten tilhører folket, ikke kongen. Borgerrettigheder som frihed, lighed og ytringsfrihed er i dag grundlæggende i alle demokratier. Menneskerettighedserklæringen fra 1789 er forfader til FN's Menneskerettighedserklæring fra 1948. Selv lande der aldrig selv har haft revolution er formet af disse ideer."}$$::jsonb,
  'mc','short',$${"concepts":["folkesuverænitet","borgerrettigheder","legitimitet","politisk arv","moderne demokrati"],"misconception_type":"outcome_confusion","cognitive_skill":"analysis","difficulty_type":"evaluative","insight_type":"perspective_shift","challenge_role":"reasoning_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',4,'auto',true,'revolutions_democracy',7,4
);

-- ─── BAND 5 (4 questions) ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Historikere er uenige om Den Franske Revolution primært var en social revolution (en klassekamp) eller en politisk revolution (en statslig magtovertagelse). Hvad karakteriserer bedst denne historiografiske strid?","options":["Marxistiske historikere som Soboul argumenterer for at revolutionen var borgerskabets sejr over feudaladelen, mens revisionistiske historikere som Cobban peger på at politiske ideer og statskrise drev forandringen — ikke automatisk klassemodsætninger","Striden handler udelukkende om hvorvidt revolutionen var planlagt eller spontan — ikke om dens sociale versus politiske karakter","Historikere er faktisk enige om at revolutionen var rent politisk — den ændrede staten men ikke det sociale hierarki","Striden er primært mellem franske og engelske historikere og afspejler nationale fordomme snarere end reelle historiske spørgsmål"],"correct":"Marxistiske historikere som Soboul argumenterer for at revolutionen var borgerskabets sejr over feudaladelen, mens revisionistiske historikere som Cobban peger på at politiske ideer og statskrise drev forandringen — ikke automatisk klassemodsætninger","accepted_answers":["Marxistiske historikere som Soboul argumenterer for at revolutionen var borgerskabets sejr over feudaladelen, mens revisionistiske historikere som Cobban peger på at politiske ideer og statskrise drev forandringen — ikke automatisk klassemodsætninger"],"review_text":"Albert Soboul og Georges Lefebvre argumenterede for den marxistiske tolkning: borgerskabet vælter feudaladelen i en klassekamp. Alfred Cobban og den revisionistiske skole svarede: borgerskabet var ikke en samlet klasse med fælles interesser. Denne debat viser at historiske fortolkninger altid afspejler de teoretiske rammer historikeren anvender — der er ingen neutral tilgang til revolution."}$$::jsonb,
  'mc','short',$${"concepts":["historiografi","marxistisk tolkning","revisionisme","borgerskab","feudalisme"],"misconception_type":"oversimplification","cognitive_skill":"evaluation","difficulty_type":"historiographic","insight_type":"concept_clarification","challenge_role":"reasoning_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',7,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Var Napoleon Bonaparte revolutionens fuldbyrdelse eller dens forræderi?","options":["Begge dele på én gang: Napoleon bevarede og spredte revolutionære reformer (Code Napoléon, lighed for loven, meritokrati) men afskaffede politisk frihed, genindførte adelstitler og kårede sig selv til kejser","Napoleon var udelukkende revolutionens forræderi — han genindførte alt det revolutionen havde afskaffet og efterlod Frankrig dårligere stillet end i 1789","Napoleon var revolutionens fuldbyrdelse — han realiserede alle dens idealer fuldt ud ved at sprede dem militært til hele Europa","Napoleon var hverken fuldbyrdelse eller forræderi — han var et nyt fænomen uden sammenhæng med revolutionens ideer"],"correct":"Begge dele på én gang: Napoleon bevarede og spredte revolutionære reformer (Code Napoléon, lighed for loven, meritokrati) men afskaffede politisk frihed, genindførte adelstitler og kårede sig selv til kejser","accepted_answers":["Begge dele på én gang: Napoleon bevarede og spredte revolutionære reformer (Code Napoléon, lighed for loven, meritokrati) men afskaffede politisk frihed, genindførte adelstitler og kårede sig selv til kejser"],"review_text":"Napoleon inkarnerer revolutionens ambivalens. Han bevarede Code Napoléon og meritokrati frem for arv. Men han lod sig kalde kejser i 1804, genindførte adelstitler og undertrykte pressefriheden. Historikere debatterer stadig: var Napoleon revolutionens logiske konklusion eller dens negation? Svaret er formentlig begge dele — han er selve indbegrebet af revolutionens indre modsætning mellem orden og frihed."}$$::jsonb,
  'mc','short',$${"concepts":["Napoleon","Code Napoléon","ambivalens","frihed vs orden","historiografi"],"misconception_type":"binary_thinking","cognitive_skill":"evaluation","difficulty_type":"evaluative","insight_type":"perspective_shift","challenge_role":"reasoning_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',7,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Var Skrækveldet en uundgåelig konsekvens af Den Franske Revolution, eller kunne det have været undgået?","options":["Det er et åbent historikerspørgsmål: strukturelle faktorer som krig og kontrarevolution skabte pres for radikalisering, men Robespierre og hans komité traf bevidste valg der eskalerede volden ud over hvad situationen krævede","Skrækveldet var fuldstændig uundgåeligt — enhver revolution under så stærkt udefrakommende pres ville nødvendigvis have skabt det samme resultat","Skrækveldet var helt undgåeligt — det skyldtes udelukkende Robespierres personlige psykologi og ville ikke være sket under en anden leder","Historikere er enige om at Skrækveldet var en fejltagelse der afspejlede revolutionens fundamentale svaghed fra starten"],"correct":"Det er et åbent historikerspørgsmål: strukturelle faktorer som krig og kontrarevolution skabte pres for radikalisering, men Robespierre og hans komité traf bevidste valg der eskalerede volden ud over hvad situationen krævede","accepted_answers":["Det er et åbent historikerspørgsmål: strukturelle faktorer som krig og kontrarevolution skabte pres for radikalisering, men Robespierre og hans komité traf bevidste valg der eskalerede volden ud over hvad situationen krævede"],"review_text":"Hannah Arendt argumenterede for at revolutioner der prioriterer sociale mål frem for politisk orden tenderer mod terror. Charles Tilly pegede på statsopbygning under krigsforhold som strukturel forklaring. Men selv under stærkt pres traf Robespierre valg: hvem der skulle dø og af hvilke anklager. Historiske konsekvenser er sjældent enten fuldt nødvendige eller fuldt tilfældige — de er begge dele."}$$::jsonb,
  'mc','short',$${"concepts":["Skrækveldet","nødvendighed","Robespierre","Arendt","strukturelt vs individuelt ansvar"],"misconception_type":"false_binary","cognitive_skill":"evaluation","difficulty_type":"historiographic","insight_type":"concept_clarification","challenge_role":"reasoning_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',7,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Fører revolutioner til demokrati, eller skaber de oftest nye former for autoritært styre?","options":["Historisk set er billedet blandet: den amerikanske revolution skabte et stabilt demokrati, den franske endte med Napoleon, den russiske med Stalin og den iranske med teokrati — revolution er ingen garanti for demokrati","Revolutioner fører altid til demokrati på langt sigt — selv om det tager tid er folkemagt det uundgåelige resultat","Revolutioner er altid ødelæggende for demokrati — alle historiske revolutioner har enten skabt diktatur eller anarkistisk kaos","Spørgsmålet er meningsløst — demokrati kan kun etableres gennem gradvise reformer, aldrig revolution"],"correct":"Historisk set er billedet blandet: den amerikanske revolution skabte et stabilt demokrati, den franske endte med Napoleon, den russiske med Stalin og den iranske med teokrati — revolution er ingen garanti for demokrati","accepted_answers":["Historisk set er billedet blandet: den amerikanske revolution skabte et stabilt demokrati, den franske endte med Napoleon, den russiske med Stalin og den iranske med teokrati — revolution er ingen garanti for demokrati"],"review_text":"Komparativ revolutionsforskning viser at revolutioners udfald afhænger af mange faktorer: eksisterende institutioner, internationale relationer og koalitionernes sammensætning. Frankrig 1789 gav demokrati til sidst — men via Napoleon, tre kongedømmer og to kejserdømmer. Amerika havde institutionelle forudsætninger der hjalp demokratiet. Der er ingen automatisk sammenhæng mellem revolution og demokrati."}$$::jsonb,
  'mc','short',$${"concepts":["komparativ revolution","demokrati","autoritarisme","strukturelle faktorer","historisk resultat"],"misconception_type":"determinism","cognitive_skill":"evaluation","difficulty_type":"evaluative","insight_type":"perspective_shift","challenge_role":"reasoning_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',7,5
);
