-- Section 53 — Youth-Near Language & Cognitive Energy Rewrite Pass
-- Democracy & Power domain: 20 selective content UPDATEs
-- Metadata unchanged. Conceptual depth unchanged.
-- Changes: youth-near stems, shorter options, warmer review_text openings.
-- Rollback: re-run 20260526000200 INSERT statements (content only fields).

-- dp_001: fix inconsistent "autonom leder" → "autokrat" (matches options)
UPDATE public.questions
SET content = $${"question":"Hvad er den vigtigste forskel på en demokratisk leder og en autokrat?","options":["En demokratisk leder vælges — en autokrat udnævnes","En demokratisk leder kan afsættes af dem de leder — en autokrat kan ikke","En demokratisk leder regerer med flertallets støtte","En demokratisk leder har færre beføjelser"],"correct":"En demokratisk leder kan afsættes af dem de leder — en autokrat kan ikke","review_text":"Valg skaber ikke demokrati — ansvarlighed gør. En leder kan blive valgt, holde fair valg én gang, og derefter afmontere mekanismerne der ville fjerne dem. Det der adskiller demokrati er ikke processen til at komme til magten, men muligheden for at blive afsat. Spørg altid: hvem holder denne leder ansvarlig — og hvordan?"}$$::jsonb
WHERE metadata->>'domain' = 'democracy_power'
  AND content->>'question' = 'Hvad er den vigtigste forskel på en demokratisk leder og en autonom leder?';

-- dp_004: abstract collective-action stem → concrete consequence framing; punchline moved first
UPDATE public.questions
SET content = $${"question":"Hvad sker der med demokratiet, når mange vælger ikke at stemme?","options":["Staten kan tvinge borgere til at stemme — det er den eneste løsning","Det er et rent personligt valg uden politiske konsekvenser for andre","De der ikke stemmer, mister retten til at klage over politikernes beslutninger","Fravalget er ikke neutralt — det giver bestemte grupper mere indflydelse og skæver demokratiets resultat"],"correct":"Fravalget er ikke neutralt — det giver bestemte grupper mere indflydelse og skæver demokratiets resultat","review_text":"Lav valgdeltagelse er ikke neutral. Den favoriserer systematisk de grupper der stemmer — typisk ældre, velhavende og allerede tilfredse borgere. Politikere tilpasser sig: de designer politik for dem der stemmer. Din stemme er ikke blot din. Dens fravær omformer hvad alle andres stemmer betyder."}$$::jsonb
WHERE metadata->>'domain' = 'democracy_power'
  AND content->>'question' = 'Hvorfor er stemmedeltagelse et kollektivt anliggende snarere end et rent personligt valg?';

-- dp_008: fix long embedded-clause sentence in review_text (Section 52 audit finding)
UPDATE public.questions
SET content = $${"question":"Hvorfor reproducerer revolutioner ofte de magtstrukturer de omvæltede?","options":["Fordi revolutionære ledere er hyklere","Fordi magtstrukturerne der overtages former dem der overtager dem","Fordi idealer kompromitteres af praktiske nødvendigheder","Fordi befolkninger ønsker stabilitet frem for forandring"],"correct":"Fordi magtstrukturerne der overtages former dem der overtager dem","review_text":"En revolution erstatter personerne — men arver infrastrukturen: bureaukratiet, politiet, skatteapparatet, informationsnetværkerne. Disse strukturer har en indre logik der påvirker enhver der bruger dem. En revolutionær der overtager imperiet, opdager hurtigt: det kan kun administreres som det altid er blevet. Strukturer former aktører mindst ligeså meget som aktører former strukturer. Det er grunden til at Frankrigs revolution producerede Napoleon og Ruslands producerede Stalin."}$$::jsonb
WHERE metadata->>'domain' = 'democracy_power'
  AND content->>'question' = 'Hvorfor reproducerer revolutioner ofte de magtstrukturer de omvæltede?';

-- dp_012: replace cold hypothesis opener with direct human-situation framing
UPDATE public.questions
SET content = $${"question":"Hvad er den vigtigste svaghed ved repræsentativt demokrati?","options":["Vælgere har ikke nok viden til at træffe gode valg","Repræsentanter kan handle i egne interesser frem for vælgernes","Systemet er for langsomt til at håndtere moderne udfordringer","Flertalsbeslutninger afspejler ikke mindretallenes behov"],"correct":"Repræsentanter kan handle i egne interesser frem for vælgernes","review_text":"Du vælger nogen til at handle på dine vegne. Men der er ingen garanti for at de faktisk gør det. Repræsentanter har egne karriereinteresser, partiloyaliteter og påvirkninger fra lobbyister. Principal-agent-problemet er ikke en fejl der kan rettes — det er en strukturel spænding der kræver løbende institutionel håndtering. Transparens, karantæneregler og pressefrihed er ikke dekorationer; de er de mekanismer der reducerer agenturproblemet."}$$::jsonb
WHERE metadata->>'domain' = 'democracy_power'
  AND content->>'question' = 'Hvad er den vigtigste svaghed ved repræsentativt demokrati?';

-- dp_015: abstract oligarki-definition stem → concrete power question; warmer opener
UPDATE public.questions
SET content = $${"question":"Kan en lille gruppe rige mennesker reelt bestemme i et demokrati — selvom alle har en stemme?","options":["Nej — oligarki og demokrati er gensidigt udelukkende styreformer","Ja — en lille gruppe kan have uforholdsmæssig reel magt selv i et formelt demokrati","Ja — men kun i korrupte demokratier, ikke i velfungerende","Oligarki refererer kun til styreformer uden valg"],"correct":"Ja — en lille gruppe kan have uforholdsmæssig reel magt selv i et formelt demokrati","review_text":"Du stemmer. Virksomhederne lobbyerer. Begge former lovgivningen — men ikke i samme omfang. En lille velhavende elite kan finansiere valgkampagner, eje medier og lobbye effektivt, mens valgurnen formelt fungerer. Videnskabelige analyser af amerikanske politiske beslutninger viser at eliteinteresser statistisk forudsiger politiske resultater langt bedre end folkelig opinion. Demokrati og oligarki er et spektrum, ikke en binær. Spørgsmålet er ikke 'har vi et demokrati?' men 'hvem har den reelle indflydelse — og hvorfra?'"}$$::jsonb
WHERE metadata->>'domain' = 'democracy_power'
  AND content->>'question' = 'Hvad er oligarki — og kan det eksistere side om side med demokrati?';

-- dp_016: "primære kilde til politisk legitimitet" → direct human question; Weber-free opener
UPDATE public.questions
SET content = $${"question":"Hvad giver egentlig en politisk leder retten til at bestemme?","options":["Tradition — det har altid været sådan","Karisma — folk beundrer og følger dem","Resultater — de leverer hvad borgerne ønsker","Folkelig accept — de regerede anerkender retten til at regere"],"correct":"Folkelig accept — de regerede anerkender retten til at regere","review_text":"En leder kan have magt af tre grunde: tradition (det har altid været sådan), karisma (folk ser op til dem) eller rationelle regler (systemet udpegede dem). Moderne demokratier hviler på det tredje — men kun hvis borgerne faktisk accepterer reglerne som legitime. Det er grunden til at valgnederlæg der afvises truer demokratiet fundamentalt: de underminerer den folkelige accept der er systemets egentlige fundament."}$$::jsonb
WHERE metadata->>'domain' = 'democracy_power'
  AND content->>'question' = 'Hvad er den primære kilde til politisk legitimitet i et moderne demokrati?';

-- dp_019: shorten bloated correct option (was 28 words → 11 words)
UPDATE public.questions
SET content = $${"question":"Hvad er forskellen på borgerrettigheder og menneskerettigheder?","options":["De er synonyme begreber — begge beskytter individers frihed","Menneskerettigheder følger dig som menneske — borgerrettigheder giver din stat dig","Borgerrettigheder er lovfæstede — menneskerettigheder er blot moralske principper uden juridisk kraft","Menneskerettigheder gælder kun i krigssituationer — borgerrettigheder i fredstid"],"correct":"Menneskerettigheder følger dig som menneske — borgerrettigheder giver din stat dig","review_text":"Skellet er ikke kun semantisk — det er et spørgsmål om hvem der garanterer dig hvad. Borgerrettigheder afhænger af din relation til en stat: de kan i princippet fratages ved at fratage statsborgerskab. Menneskerettigheder hviler på en anden antagelse: at visse rettigheder følger med menneskelig eksistens, ikke med pas. FN's erklæring af 1948 var et direkte svar på Holocaust — en anerkendelse af at statssuverænitet ikke kan beskytte rettighederne, fordi staten selv var bødlen. Det er grunden til at menneskerettigheder eksplicit er formuleret som noget der binder stater udefra."}$$::jsonb
WHERE metadata->>'domain' = 'democracy_power'
  AND content->>'question' = 'Hvad er forskellen på borgerrettigheder og menneskerettigheder?';

-- dp_021: shorten bloated correct option; apply Section 52 review_text sentence split
UPDATE public.questions
SET content = $${"question":"Hvad er et ekkokammer — og hvad er den primære mekanisme der skaber det?","options":["En gruppe ligesindede der bevidst undgår at høre modargumenter","Et informationsmiljø der bekræfter dine overbevisninger — drevet primært af algoritmer der optimerer for engagement","Et medie der kun formidler ét politisk synspunkt","En politisk kultur der ikke tolererer offentlig uenighed"],"correct":"Et informationsmiljø der bekræfter dine overbevisninger — drevet primært af algoritmer der optimerer for engagement","review_text":"Ekkokamre opstår ikke primært fordi folk er snæversynede. De opstår fordi platforme er designet til engagement — og bekræftelse genererer mere engagement end modsigelse. En bruger der klikker på ét politisk perspektiv ser gradvist mere af det — ikke som valg, men som algoritmisk konsekvens. Det farlige er ikke at ekkokamre gør folk mere ekstreme (evidensen er blandet). Det er at de gør det muligt at leve i en faktuel virkelighed der er strukturelt adskilt fra modpartens. Politisk dialog kræver delt faktuel bund. Ekkokamre eroderer den bund — stille, personaliseret, en feed ad gangen."}$$::jsonb
WHERE metadata->>'domain' = 'democracy_power'
  AND content->>'question' = 'Hvad er et ekkokammer — og hvad er den primære mekanisme der skaber det?';

-- dp_022: replace "Max Weber adskillede..." opener with Napoleon concrete example
UPDATE public.questions
SET content = $${"question":"Kan en leder der kom til magten ulovligt alligevel regere legitimt?","options":["Nej — uden lovlig magtovertagelse er ethvert styre pr. definition illegitimt","Nej — demokratisk legitimitet kræver altid procedurelt korrekte valg","Ja — legitimitet er uafhængig af legalitet; en leder kan have reel folkelig accept uden at have fulgt juridiske procedurer","Ja — men kun midlertidigt, indtil et nyt lovligt valg kan afholdes"],"correct":"Ja — legitimitet er uafhængig af legalitet; en leder kan have reel folkelig accept uden at have fulgt juridiske procedurer","review_text":"Napoleon brød reglerne for, hvordan man kom til magten. Alligevel fulgte millioner ham frivilligt. Hvad siger det om hvad der egentlig giver en leder ret til at regere? Legitimitet — den sociale accept af autoritetens ret — er noget andet end legalitet. Omvendt kan en leder vinde et lovligt valg og gradvist miste al legitimitet — som Mugabe i Zimbabwe, der i årtier vandt valg mens den reelle accept smuldrede. Begge tæller — men de er ikke det samme."}$$::jsonb
WHERE metadata->>'domain' = 'democracy_power'
  AND content->>'question' = 'Kan en leder der kom til magten ulovligt alligevel regere legitimt?';

-- dp_023: "skalere dårligt til moderne nationalstater" → Denmark-grounded concrete question
UPDATE public.questions
SET content = $${"question":"Hvorfor kan man ikke bare lade alle borgere stemme om alle beslutninger i et land som Danmark?","options":["Borgere har ikke nok viden til at træffe gode beslutninger om komplekse emner","Folk er for uenige til at nå konsensus i store grupper","Det er logistisk og kognitivt umuligt — en moderne stat har tusindvis af tekniske beslutninger","Direkte demokrati er for sårbart over for flertalstyranni"],"correct":"Det er logistisk og kognitivt umuligt — en moderne stat har tusindvis af tekniske beslutninger","review_text":"Athen praktiserede direkte demokrati med måske 30.000–50.000 deltagelsesberettigede — og selv dér var det logistisk krævende. En moderne nation med 6 millioner borgere kan ikke afholde daglige folkeafstemninger om hvert lovforslag. Men problemet er ikke kun logistisk. Det er kognitivt: en enkelt lov kan indeholde hundredvis af tekniske, juridiske og sociale afvejninger. Borgere kan have stærke og legitime meninger om formål uden kapacitet til at evaluere implementeringsvalg. Det er ikke et argument mod folkelig deltagelse — det er argumentet for repræsentation som specialisering af én demokratisk funktion: beslutningstagning i kompleksitet."}$$::jsonb
WHERE metadata->>'domain' = 'democracy_power'
  AND content->>'question' = 'Hvorfor kan direkte demokrati skalere dårligt til moderne nationalstater?';

-- dp_024: remove Tocqueville-named stem; concrete yes/no framing; punchline-first opener
UPDATE public.questions
SET content = $${"question":"Kan et flertal undertrykke en minoritet — uden at en eneste lov forbyder noget?","options":["Nej — undertrykkelse kræver juridiske redskaber for at være reel","Ja — men kun hvis mindretallet allerede er svagt politisk repræsenteret","Ja — men kun via skjult diskrimination, ikke åbenlys social kontrol","Ja — majoritetens sociale forventninger kan kvæle afvigende meninger uden en eneste lov"],"correct":"Ja — majoritetens sociale forventninger kan kvæle afvigende meninger uden en eneste lov","review_text":"Det mest effektive tyranni efterlader ingen spor. Ingen love. Ingen betjente. Bare social usynlighed for den der tænker forkert. Tocqueville kaldte det tyranni over sindet — og observerede det i 1830'ernes USA. Ingen piskede ikke-konformister. Men social udelukkelse og kulturel isolation var reelle konsekvenser. Er det stadig relevant? Sociale mediers mobkultur og platformkonformitetspres er 21. århundredes version af præcis det fænomen Tocqueville beskrev 190 år siden."}$$::jsonb
WHERE metadata->>'domain' = 'democracy_power'
  AND content->>'question' = 'Hvad er Tocquevilles "flertallets tyranni" — og er det primært et juridisk eller socialt fænomen?';

-- dp_026: "legitim demokratisk protest" → "kritisere de der har magten"; shorten correct option
UPDATE public.questions
SET content = $${"question":"Hvornår er det populisme — og hvornår er det bare at kritisere de der har magten?","options":["Populisme er ulovlig politisk mobilisering — demokratisk kritik er lovlig","Populisme opdeler samfundet i 'det ægte folk' mod 'eliten' — kritik udfordrer konkrete beslutninger inden for et fælles system","Populisme har altid ekstremistiske politiske mål","Populisme er altid antidemokratisk"],"correct":"Populisme opdeler samfundet i 'det ægte folk' mod 'eliten' — kritik udfordrer konkrete beslutninger inden for et fælles system","review_text":"Populisme er ikke en politik — det er en narrativ struktur. Den opdeler samfundet i to rene og homogene grupper: 'det ægte folk' og 'den korrupte elite'. Problemet er homogeniteten. Demokratiet bygger på antagelsen om at 'folket' er pluralt og har modstridende legitime interesser. Populisme kræver at 'folket' er ét, med én vilje — og at enhver der er uenig enten er del af eliten eller forråder folket. Det gør kompromis til forræderi. Det gør opposition til fjendtlighed. Og det underminerer den institutionelle respekt som demokratiet kræver at alle parter — inkl. taberne — opretholder."}$$::jsonb
WHERE metadata->>'domain' = 'democracy_power'
  AND content->>'question' = 'Hvad adskiller populisme fra legitim demokratisk protest?';

-- dp_029: "demokratisk deliberation" → concrete "udover falske nyheder" framing; applies Section 52 improvement
UPDATE public.questions
SET content = $${"question":"Hvad er det egentlige demokratiske problem med sociale medier — udover at de spreder falske nyheder?","options":["Sociale medier spreder misinformation der erstatter faktuel viden","Folk bruger for meget tid på underholdning og for lidt på politik","Sociale medier er for nemme at manipulere af udenlandske aktører","Platforme belønner emotionel og polariserende kommunikation frem for nuanceret argumentation, fordi det genererer mere engagement"],"correct":"Platforme belønner emotionel og polariserende kommunikation frem for nuanceret argumentation, fordi det genererer mere engagement","review_text":"Problemet er ikke de falske nyheder. Det er selve arkitekturen. Platforme er bygget til at maksimere engagement — og det der engagerer mest er outrage, identitetsmarkering og bekræftelse. En præcis, nuanceret analyse genererer færre reaktioner end et skarpt partisanopslag. Resultatet er ikke et informationsproblem — det er et problem med samtalen selv. De institutionelle incitamenter diskriminerer mod demokratiets kommunikationsform: den langsomme, nuancerede, faktabaserede, kompromisvillige."}$$::jsonb
WHERE metadata->>'domain' = 'democracy_power'
  AND content->>'question' = 'Hvad er den mest præcise måde sociale medier strukturelt svækker demokratisk deliberation?';

-- dp_030: "civilsamfundets vigtigste demokratiske funktion" → concrete club/union framing; warm opener
UPDATE public.questions
SET content = $${"question":"Hvad er det egentlige demokratiske formål med fagforeninger, sportsklubber og frivillige organisationer?","options":["At supplere statens velfærdsopgaver med frivillige tjenester","At mobilisere borgere til at stemme ved valg","At give borgere mulighed for at mødes og dyrke fælles interesser","At skabe netværk uafhængige af staten — som modvægt til magtkoncentration og øveplads for kollektiv handling"],"correct":"At skabe netværk uafhængige af staten — som modvægt til magtkoncentration og øveplads for kollektiv handling","review_text":"En sportsklub, en fagforening, en borgerforening. Hvad har de med demokrati at gøre? Mere end man tror. Tocqueville beundrede disse foreninger mere end nogen anden demokratisk institution — fordi de lærte borgere at koordinere og handle kollektivt uden statens initiativ. Disse institutioner skaber kapacitet til kollektiv handling og udgør en strukturel modkraft mod statens ekspansion. Når de svækkes, svækkes demokratiets muskler. Et folk der ikke kan organisere sig uafhængigt, kan ikke holde staten ansvarlig."}$$::jsonb
WHERE metadata->>'domain' = 'democracy_power'
  AND content->>'question' = 'Hvad er civilsamfundets vigtigste demokratiske funktion?';

-- dp_032: "domstolsprøvelse af lovgivning" → direct yes/no framing; shorter correct option; warmer opener
UPDATE public.questions
SET content = $${"question":"Uvalgte dommere kan ophæve love vedtaget af den folkevalgte regering. Er det demokratisk?","options":["Nej — det er udemokratisk at uvalgte ophæver folkevalgtes beslutninger","Ja — domstolsprøvelse er et neutralt juridisk redskab uden politisk dimension","Det er et ægte dilemma: uvalgte dommere beskytter demokratiets grænser — men hvem valgte dem til at fastlægge dem?","Det er kun nødvendigt i lande med upålidelige parlamenter"],"correct":"Det er et ægte dilemma: uvalgte dommere beskytter demokratiets grænser — men hvem valgte dem til at fastlægge dem?","review_text":"Det lyder selvmodsigende: uvalgte dommere kan nedlægge veto mod folkevalgtes beslutninger. Men det er præcis meningen. Demokratiet beskytter sig selv ved at begrænse sit eget flertal. Majoriteten kan ikke stemme sig til at fratage mindretal grundlæggende rettigheder — og domstolene håndhæver grænsen. Men dilemmaet er ægte: USA's højesteretsdommere sidder livslangt og former politisk virkelighed for generationer. Der er ingen perfekt løsning — kun erkendelsen at demokratiet kræver begrænsning af sit eget flertal for at beskytte de grundlæg det hviler på."}$$::jsonb
WHERE metadata->>'domain' = 'democracy_power'
  AND content->>'question' = 'Hvad er demokratiets dilemma med domstolsprøvelse af lovgivning?';

-- dp_033: replace cold definitional opener with punchy paradox statement
UPDATE public.questions
SET content = $${"question":"Hvornår er politiske partier afgørende for demokratiet — og hvornår truer de det?","options":["Partier er altid gavnlige fordi de organiserer politisk deltagelse i skala","Partier truer altid demokratiet fordi de skaber partisan loyalitet frem for saglig vurdering","Partier er afgørende når de aggregerer interesser og koordinerer — de truer demokratiet når de danner karteller der fastsætter regler der beskytter dem mod ny konkurrence","Partier er primært truende i flerpartisystemer der producerer politisk instabilitet"],"correct":"Partier er afgørende når de aggregerer interesser og koordinerer — de truer demokratiet når de danner karteller der fastsætter regler der beskytter dem mod ny konkurrence","review_text":"Partier er uundværlige. Og de er farlige. Begge dele på én gang — det er paradokset. Et politisk parti samler borgere med sammenfaldende interesser og muliggør politisk handling i skala. Uden partier er demokratisk koordination umulig. Men modne partisystemer kan degenerere til karteller: etablerede partier aftaler institutionelle regler der gør det svært for udfordrere at komme ind — valgbarhedstærskler, medieregler, offentlig partifinansiering der favoriserer eksisterende aktører. Et sundt demokrati kræver partier — og mekanismer der holder dem konkurrenceudsatte."}$$::jsonb
WHERE metadata->>'domain' = 'democracy_power'
  AND content->>'question' = 'Hvornår er politiske partier afgørende for demokratiet — og hvornår truer de det?';

-- dp_037: replace abstract opener with concrete patientforening/tobak contrast
UPDATE public.questions
SET content = $${"question":"Er lobbyisme nødvendigvis skadelig for demokratiet?","options":["Ja — lobbyisme giver organiserede interesser uforholdsmæssig indflydelse","Ja — kun vælgernes stemme bør forme politiske beslutninger","Nej — lobbyisme er blot erhvervslivets ytringsfrihed","Nej — lobbyisme er en form for politisk deltagelse der kan informere beslutningstagere, men asymmetrien kræver regulering og transparens"],"correct":"Nej — lobbyisme er en form for politisk deltagelse der kan informere beslutningstagere, men asymmetrien kræver regulering og transparens","review_text":"En patientforening der informerer parlamentarikere om konsekvenserne af et sundhedslovforslag. En tobaksindustri der ansætter konsulenter til at forsinke videnskabeligt begrundet regulering. Begge er lobbyisme. Problemet er asymmetrien: velfinansierede interesser kan lobbye kontinuerligt og professionelt; diffuse offentlige interesser kan det ikke. Løsningen er regulering, gennemsigtighed og institutionel modvægt — ikke forbud. Et forbud mod lobbyisme ville flytte indflydelse til uofficielle kanaler. Det ville ikke eliminere den. Det ville blot gøre den usynlig."}$$::jsonb
WHERE metadata->>'domain' = 'democracy_power'
  AND content->>'question' = 'Er lobbyisme nødvendigvis skadelig for demokratiet?';

-- dp_038: "stærkeste strukturelle argument for tidsbegrænsning" → concrete why-question
UPDATE public.questions
SET content = $${"question":"Hvorfor er der i mange demokratier en grænse for, hvor mange år en leder kan sidde?","options":["For at sikre at nye perspektiver kontinuerligt introduceres i politikken","Det er et demokratisk princip om at magt regelmæssigt bør cirkulere","For at forhindre populære ledere i at akkumulere for stor folkelig støtte","Det reducerer incitamentet til at kapre institutioner — gevinsten begrænses af tidsrammen"],"correct":"Det reducerer incitamentet til at kapre institutioner — gevinsten begrænses af tidsrammen","review_text":"Tidsbegrænsning er ikke designet til at bringe variation — det er designet til at reducere institutionel kapring. En leder der ved de sidder i otte år og ikke kan sidde i tolv, har reducerede incitamenter til at cementere personlig magt permanent. En leder uden tidsbegrænsning har alle incitamenter til at investere i at kontrollere de institutioner der skulle kontrollere dem. Franklins fire præsidentvalg — dog under ekstraordinære omstændigheder — førte direkte til det tillæg der begrænsede fremtidige præsidenter. Argumentet er ikke at magt korrumperer mennesker. Det er at magt skaber strukturelle incitamenter der korrumperer systemer."}$$::jsonb
WHERE metadata->>'domain' = 'democracy_power'
  AND content->>'question' = 'Hvad er det stærkeste strukturelle argument for tidsbegrænsning af politiske embeder?';

-- dp_039: "den mest strukturelt præcise forklaring på udbredt politisk apati" → youth-near blame-reframe
UPDATE public.questions
SET content = $${"question":"Hvorfor gider mange unge ikke engagere sig politisk — er det egentlig deres skyld?","options":["Folk er for selvoptaget og materialistiske til at bry sig om fællesskabet","Uddannelsesniveauet er for lavt til at borgere kan engagere sig meningsfuldt","Sociale medier har erstattet politisk engagement med underholdning","Systemet leverer ikke mærkbare resultater og tilbyder ikke reelle valg — så fravalget er rationelt, ikke ligegyldighed"],"correct":"Systemet leverer ikke mærkbare resultater og tilbyder ikke reelle valg — så fravalget er rationelt, ikke ligegyldighed","review_text":"Apati er ikke personlighedstræk — det er rationelt respons på institutionelle vilkår. Når alle partier konvergerer til centrum, er marginaldifferencen lav. Når politiske processer er uigennemsigtige og ekspertdominerede, virker deltagelse meningsløs. Når sociale problemer er uløste trods årtiers opmærksomhed, er scepticisme rationel. Politisk apati er ikke demokratiets kerne-problem. Det er demokratiets symptom. At løse apati kræver at løse det den er et rationelt svar på: reelt valg, reelt responsivt styre, reelt meningsfulde konsekvenser af at deltage frem for at forblive passiv."}$$::jsonb
WHERE metadata->>'domain' = 'democracy_power'
  AND content->>'question' = 'Hvad er den mest strukturelt præcise forklaring på udbredt politisk apati?';

-- dp_040: cold institutional opener → Denmark-grounded concrete framing
UPDATE public.questions
SET content = $${"question":"Kan internationale institutioner som EU underminere nationalt demokrati?","options":["Ja — internationale institutioner er pr. definition udemokratiske fordi de ikke er direkte folkevalgte","Nej — Danmark valgte selv at deltage og kan forlade EU","Nej — internationale institutioner beskytter demokratiet mod nationalstaternes excesses","Ja — men det afhænger af om beslutningerne er demokratisk forankret, transparente og underlagt reel politisk kontrol"],"correct":"Ja — men det afhænger af om beslutningerne er demokratisk forankret, transparente og underlagt reel politisk kontrol","review_text":"Danmark har overdraget noget af sin lovgivningsmagt til EU. Det er et bevidst valg — men hvad sker der med det demokratiske ansvar der fulgte med? Argumentet for bekymring: borgere kan ikke stemme direkte om EU-lovgivning der regulerer store dele af hverdagslivet. Argumentet imod: Europaparlamentet er valgt direkte, nationale regeringer er repræsenteret i Rådet, og stater valgte frivilligt at overføre suverænitet. Det er ikke et spørgsmål med ét rigtigt svar — men det er et spørgsmål alle demokratier i et globalt integreret system skal stille sig løbende. Demokratisk kontrol skal følge magt — og magt bevæger sig opad."}$$::jsonb
WHERE metadata->>'domain' = 'democracy_power'
  AND content->>'question' = 'Kan internationale institutioner som EU underminere nationalt demokrati?';
