-- Engelsk batch 2, 4. klasse bånd 1-2: 167 nye MC-spørgsmål (learning_objective='english', bånd 1-4).
-- Del af 1000 nye engelskspørgsmål til 3.-5. klasse. Samme indholds- og metadata-mønster som
-- 20261001000000_english_grade3_5; metadata afledes her af kategorinøglen k:
-- o=ordforråd, h=hverdagsudtryk, g=grammatik, l=læseforståelse. difficulty = bånd.
-- Bånd 1-2: reinforcement/conceptual_bridge. Bånd 3-4: challenge/reframing. All is_active=true.
-- Må KUN anvendes via apply_migration med særskilt ejer-autorisation (D-110).

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band)
SELECT
  jsonb_build_object('question', e->>'q', 'options', e->'o', 'correct', e->>'a',
                     'accepted_answers', jsonb_build_array(e->>'a'), 'review_text', e->>'r'),
  'mc', 'short',
  jsonb_build_object('concepts', jsonb_build_array(m.concept), 'cognitive_skill', m.skill,
                     'difficulty_type', m.dtype, 'misconception_type', m.mis,
                     'challenge_role', CASE WHEN (e->>'b')::int >= 3 THEN 'challenge' ELSE 'reinforcement' END,
                     'insight_type', CASE WHEN (e->>'b')::int >= 3 THEN 'reframing' ELSE 'conceptual_bridge' END,
                     'domain', 'english'),
  'mc_single', (e->>'b')::int, 'auto', true, 'english', (e->>'g')::int, (e->>'b')::int
FROM jsonb_array_elements($$[
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'city'?","o":["sø","by","cykel","kirke"],"a":"by","r":"'City' betyder by — især en stor by. En landsby hedder 'village'."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'village'?","o":["landsby","villa","have","vej"],"a":"landsby","r":"'Village' er en landsby. 'Villa' er et stort hus."},
{"g":4,"b":1,"k":"o","q":"Hvad hedder 'gade' på engelsk?","o":["stream","stair","strange","street"],"a":"street","r":"Gade = street. 'Stairs' er trapper."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'bridge'?","o":["brød","briller","bro","bryst"],"a":"bro","r":"'Bridge' betyder bro. Briller hedder 'glasses'."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'church'?","o":["kirsebær","kirke","ost","kylling"],"a":"kirke","r":"'Church' betyder kirke."},
{"g":4,"b":1,"k":"o","q":"Hvad hedder 'banegård' på engelsk?","o":["station","stadium","shop","street"],"a":"station","r":"Banegård = (train) station. 'Stadium' er et stadion."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'hospital'?","o":["hotel","hus","have","hospital"],"a":"hospital","r":"'Hospital' er det samme ord på engelsk og dansk."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'park'?","o":["parkering","plads","park","pakke"],"a":"park","r":"'Park' betyder park. Parkeringsplads hedder 'car park' eller 'parking lot'."},
{"g":4,"b":1,"k":"o","q":"Hvad hedder 'svømmehal' på engelsk?","o":["swimming school","swimming pool","swim house","water hall"],"a":"swimming pool","r":"Svømmehal = swimming pool (eller swimming baths)."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'supermarket'?","o":["supermarked","superhelt","sportshal","skole"],"a":"supermarked","r":"'Supermarket' er et supermarked, hvor man køber mad."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'football'?","o":["basketball","håndbold","tennis","fodbold"],"a":"fodbold","r":"'Football' er fodbold. I USA kalder man det 'soccer'."},
{"g":4,"b":1,"k":"o","q":"Hvad hedder 'håndbold' på engelsk?","o":["football","baseball","handball","volleyball"],"a":"handball","r":"Håndbold = handball — hand (hånd) + ball (bold)."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'ride a horse'?","o":["købe en hest","ride på en hest","tegne en hest","fodre en hest"],"a":"ride på en hest","r":"'Ride' betyder ride, og 'horse' er hest."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'dance'?","o":["danse","dase","tænke","drømme"],"a":"danse","r":"'Dance' betyder danse. 'I like to dance' = jeg kan lide at danse."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'draw'?","o":["trække","drømme","drikke","tegne"],"a":"tegne","r":"'Draw' betyder tegne. 'Drawing' er en tegning."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'paint'?","o":["pande","pakke","male","pege"],"a":"male","r":"'Paint' betyder male (med maling)."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'cook'?","o":["kigge","lave mad","kaste","købe"],"a":"lave mad","r":"'Cook' betyder lave mad. En kok hedder også 'cook'."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'write'?","o":["skrive","ride","hvid","rette"],"a":"skrive","r":"'Write' betyder skrive. 'White' (hvid) lyder lidt ens."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'listen'?","o":["liste","leve","ligge","lytte"],"a":"lytte","r":"'Listen' betyder lytte. 'Listen to music' = lyt til musik."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'watch TV'?","o":["vaske tv","købe tv","se fjernsyn","lytte til radio"],"a":"se fjernsyn","r":"'Watch' betyder se på. Det betyder også et armbåndsur!"},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'January'?","o":["juni","januar","juli","februar"],"a":"januar","r":"'January' er januar — årets første måned."},
{"g":4,"b":1,"k":"o","q":"Hvad hedder 'august' på engelsk?","o":["August","April","autumn","October"],"a":"August","r":"August hedder også 'August' — men med stort A på engelsk."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'April'?","o":["august","maj","juli","april"],"a":"april","r":"'April' er april. Måneder skrives med stort på engelsk."},
{"g":4,"b":1,"k":"o","q":"Hvad hedder 'oktober' på engelsk?","o":["November","August","October","Octopus"],"a":"October","r":"Oktober = October. Måneder skrives med stort."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'fourteen'?","o":["40","14","4","41"],"a":"14","r":"'Fourteen' er 14. 40 hedder 'forty' — uden u!"},
{"g":4,"b":1,"k":"o","q":"Hvad hedder tallet 30 på engelsk?","o":["thirty","thirteen","three","third"],"a":"thirty","r":"30 = thirty. 13 = thirteen."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'fifty'?","o":["15","5","500","50"],"a":"50","r":"'Fifty' er 50. 15 hedder 'fifteen'."},
{"g":4,"b":1,"k":"o","q":"Hvad hedder tallet 100 på engelsk?","o":["one thousand","ten ten","one hundred","one million"],"a":"one hundred","r":"100 = one hundred. 1000 = one thousand."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'aunt'?","o":["onkel","tante","kusine","mormor"],"a":"tante","r":"'Aunt' betyder tante. Onkel hedder 'uncle'."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'cousin'?","o":["fætter eller kusine","onkel","nevø","bedstefar"],"a":"fætter eller kusine","r":"'Cousin' bruges både om fætter og kusine."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'parents'?","o":["søskende","bedsteforældre","venner","forældre"],"a":"forældre","r":"'Parents' betyder forældre — mor og far."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'neck'?","o":["næse","nøgle","hals","knæ"],"a":"hals","r":"'Neck' betyder hals. Knæ hedder 'knee'."},
{"g":4,"b":1,"k":"o","q":"Hvad hedder 'mave' på engelsk?","o":["mouth","stomach","back","chest"],"a":"stomach","r":"Mave = stomach (eller tummy). Ryg = back."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'finger'?","o":["finger","fod","tå","negl"],"a":"finger","r":"'Finger' er det samme på engelsk. Tå hedder 'toe'."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'shoulder'?","o":["skuffe","skulle","sko","skulder"],"a":"skulder","r":"'Shoulder' betyder skulder."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'computer'?","o":["lommeregner","telefon","computer","skærm"],"a":"computer","r":"'Computer' er det samme ord på engelsk og dansk."},
{"g":4,"b":1,"k":"o","q":"Hvad hedder 'mobiltelefon' på engelsk?","o":["mobile home","mobile phone","moving phone","phone box"],"a":"mobile phone","r":"Mobiltelefon = mobile phone. Amerikanere siger 'cell phone'."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'clock'?","o":["ur","klokke","klods","kok"],"a":"ur","r":"'Clock' er et ur på væggen. Armbåndsur hedder 'watch'."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'cupboard'?","o":["kop","bord","kasse","skab"],"a":"skab","r":"'Cupboard' er et skab. Ordet kommer af 'cup' (kop) og 'board' (hylde)."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'lamp'?","o":["lam","lamel","lampe","lommelygte"],"a":"lampe","r":"'Lamp' betyder lampe."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'giraffe'?","o":["gorilla","giraf","zebra","kamel"],"a":"giraf","r":"'Giraffe' er en giraf — med to f'er og e på engelsk."},
{"g":4,"b":1,"k":"o","q":"Hvad hedder 'skildpadde' på engelsk?","o":["turtle","tiger","turkey","toad"],"a":"turtle","r":"Skildpadde = turtle (eller tortoise på land). 'Turkey' er en kalkun."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'spider'?","o":["spejder","spade","spand","edderkop"],"a":"edderkop","r":"'Spider' betyder edderkop."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'bee'?","o":["bær","bøg","bi","bjørn"],"a":"bi","r":"'Bee' betyder bi. Bier laver honning (honey)."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'nice'?","o":["nysgerrig","sød eller rar","ny","næste"],"a":"sød eller rar","r":"'Nice' betyder sød, rar eller dejlig."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'kind'?","o":["venlig","kind","barn","klog"],"a":"venlig","r":"'Kind' betyder venlig — ikke kind! Kind hedder 'cheek'."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'easy'?","o":["svær","hurtig","tom","nem"],"a":"nem","r":"'Easy' betyder nem. Det modsatte er 'difficult' — svær."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'long'?","o":["lav","længe","lang","lunken"],"a":"lang","r":"'Long' betyder lang. Det modsatte er 'short'."},
{"g":4,"b":1,"k":"h","q":"Hvad betyder 'What's your favourite food?'","o":["Hvad spiser du i dag?","Hvad er din yndlingsmad?","Er du sulten?","Hvem laver maden?"],"a":"Hvad er din yndlingsmad?","r":"'Favourite' betyder yndlings-, og 'food' betyder mad."},
{"g":4,"b":1,"k":"h","q":"Hvad betyder 'Have a nice day!'?","o":["Hav en god dag!","Det er en dejlig dag!","Hvilken dag er det?","God nat!"],"a":"Hav en god dag!","r":"Man siger 'Have a nice day', når man siger farvel."},
{"g":4,"b":1,"k":"h","q":"Hvad betyder 'I'm fine, thanks'?","o":["Jeg er færdig, tak","Jeg finder den, tak","Jeg er sulten, tak","Jeg har det fint, tak"],"a":"Jeg har det fint, tak","r":"'Fine' betyder fin/godt. Man svarer det på 'How are you?'."},
{"g":4,"b":1,"k":"h","q":"Hvad betyder 'Me too!'?","o":["Til mig!","Ikke mig!","Også mig!","Mig først!"],"a":"Også mig!","r":"'Me too' betyder 'også mig' eller 'det gør jeg også'."},
{"g":4,"b":1,"k":"h","q":"Hvad betyder 'Wait a minute!'?","o":["Om et minut!","Vent et øjeblik!","Vent ikke!","Hvad er klokken?"],"a":"Vent et øjeblik!","r":"'Wait' betyder vente. 'A minute' er et minut — eller bare et øjeblik."},
{"g":4,"b":1,"k":"h","q":"Hvad betyder 'Here you are' (når man giver noget)?","o":["Værsgo","Her er du","Kom her","Hvor er du?"],"a":"Værsgo","r":"'Here you are' siger man, når man rækker nogen noget — ligesom 'værsgo'."},
{"g":4,"b":1,"k":"h","q":"Hvad betyder 'Happy New Year!'?","o":["Glædelig jul!","Tillykke!","God sommer!","Godt nytår!"],"a":"Godt nytår!","r":"'New Year' er nytår. 'Happy New Year!' = godt nytår!"},
{"g":4,"b":1,"k":"h","q":"Hvad betyder 'Watch out!'?","o":["Se her!","Gå ud!","Pas på!","Se fjernsyn!"],"a":"Pas på!","r":"'Watch out!' råber man, når der er fare — pas på!"},
{"g":4,"b":1,"k":"h","q":"Hvad betyder 'Of course!'?","o":["Måske!","Selvfølgelig!","Aldrig!","Med vilje!"],"a":"Selvfølgelig!","r":"'Of course' betyder selvfølgelig."},
{"g":4,"b":1,"k":"h","q":"Hvad betyder 'Shh, be quiet!'?","o":["Shh, vær stille!","Shh, kom her!","Shh, sov godt!","Shh, skynd dig!"],"a":"Shh, vær stille!","r":"'Quiet' betyder stille."},
{"g":4,"b":1,"k":"g","q":"Hvilket ord mangler? 'He ___ my brother.'","o":["are","am","be","is"],"a":"is","r":"Med 'he' bruger man 'is': He is my brother = han er min bror."},
{"g":4,"b":1,"k":"g","q":"Hvilket ord mangler? 'They ___ a big house.'","o":["has","is","have","am"],"a":"have","r":"Med 'they' bruger man 'have': They have a big house."},
{"g":4,"b":1,"k":"g","q":"Hvad er flertal af 'apple'?","o":["appless","apples","applees","apple"],"a":"apples","r":"Man sætter -s på: one apple, five apples."},
{"g":4,"b":1,"k":"g","q":"Hvad er flertal af 'bird'?","o":["birds","birdes","bird","birdies"],"a":"birds","r":"Man sætter -s på: one bird, many birds."},
{"g":4,"b":1,"k":"g","q":"Hvilket ord betyder 'hun'?","o":["he","her","it","she"],"a":"she","r":"'She' betyder hun. 'He' betyder han, og 'her' betyder hende/hendes."},
{"g":4,"b":1,"k":"g","q":"Hvilket ord betyder 'din'?","o":["you","my","your","our"],"a":"your","r":"'Your' betyder din, dit eller jeres: your book = din bog."},
{"g":4,"b":1,"k":"g","q":"Hvilket ord mangler? 'I ___ ride a bike.' (jeg kan cykle)","o":["is","can","has","am"],"a":"can","r":"'Can' betyder kan: I can ride a bike = jeg kan cykle."},
{"g":4,"b":1,"k":"g","q":"Hvilket ord mangler? 'It ___ cold today.'","o":["is","are","am","has"],"a":"is","r":"Om vejret siger man 'it is': It is cold = det er koldt."},
{"g":4,"b":1,"k":"l","q":"Læs: 'Hannah has a green bag.' Hvilken farve har tasken?","o":["gul","blå","rød","grøn"],"a":"grøn","r":"'Green' betyder grøn."},
{"g":4,"b":1,"k":"l","q":"Læs: 'I am ten years old.' Hvor gammel er personen?","o":["12 år","20 år","10 år","2 år"],"a":"10 år","r":"'Ten' betyder ti."},
{"g":4,"b":1,"k":"l","q":"Læs: 'My dog is called Rex.' Hvad hedder hunden?","o":["Dog","Rex","My","Max"],"a":"Rex","r":"'Is called' betyder hedder. Hunden hedder Rex."},
{"g":4,"b":1,"k":"l","q":"Læs: 'Leo likes football and swimming.' Hvad kan Leo lide?","o":["fodbold og svømning","fodbold og dans","tennis og svømning","tegning og fodbold"],"a":"fodbold og svømning","r":"'Football' er fodbold, og 'swimming' er svømning."},
{"g":4,"b":1,"k":"l","q":"Læs: 'It is Friday. I go to the cinema.' Hvor går personen hen?","o":["i skole","i svømmehallen","i kirke","i biografen"],"a":"i biografen","r":"'Cinema' betyder biograf. 'Friday' er fredag."},
{"g":4,"b":1,"k":"l","q":"Læs: 'My mum has long hair.' Hvad har mor?","o":["kort hår","en lang kjole","langt hår","en hat"],"a":"langt hår","r":"'Long hair' betyder langt hår."},
{"g":4,"b":1,"k":"l","q":"Læs: 'The apple is red and the banana is yellow.' Hvilken farve har bananen?","o":["rød","gul","grøn","brun"],"a":"gul","r":"'Yellow' betyder gul."},
{"g":4,"b":1,"k":"l","q":"Læs: 'Liam is at home. He is sick.' Hvorfor er Liam hjemme?","o":["Han er syg","Han er glad","Han er træt","Han har fri"],"a":"Han er syg","r":"'Sick' betyder syg."},
{"g":4,"b":1,"k":"l","q":"Læs: 'There are three cats on the sofa.' Hvor mange katte er der?","o":["to","fire","en","tre"],"a":"tre","r":"'Three cats' betyder tre katte."},
{"g":4,"b":1,"k":"l","q":"Læs: 'I play the piano.' Hvad spiller personen på?","o":["guitar","tromme","klaver","fløjte"],"a":"klaver","r":"'Piano' betyder klaver."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'guitar'?","o":["gulerod","guitar","giraf","gardin"],"a":"guitar","r":"'Guitar' er det samme på engelsk og dansk."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'drum'?","o":["tromme","drøm","dram","drage"],"a":"tromme","r":"'Drum' betyder tromme. Drøm hedder 'dream'."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'game'?","o":["gammel","gemme","gave","spil"],"a":"spil","r":"'Game' betyder spil. 'Computer game' = computerspil."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'present' i 'a birthday present'?","o":["præsident","pære","gave","pris"],"a":"gave","r":"'Present' kan betyde gave: a birthday present = en fødselsdagsgave."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'party'?","o":["parti","fest","park","par"],"a":"fest","r":"'Party' betyder fest. 'Birthday party' = fødselsdagsfest."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'holiday'?","o":["ferie","hotel","hoved","lektie"],"a":"ferie","r":"'Holiday' betyder ferie (britisk). Amerikanere siger 'vacation'."},
{"g":4,"b":1,"k":"o","q":"Hvad betyder 'tomorrow'?","o":["i går","i dag","i morges","i morgen"],"a":"i morgen","r":"'Tomorrow' betyder i morgen. I går hedder 'yesterday'."},
{"g":4,"b":1,"k":"o","q":"Hvad hedder 'ræv' på engelsk?","o":["fish","frog","fox","wolf"],"a":"fox","r":"Ræv = fox. 'Wolf' er en ulv."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'nurse'?","o":["nabo","næse","sygeplejerske","nisse"],"a":"sygeplejerske","r":"'Nurse' betyder sygeplejerske. De arbejder ofte på et hospital."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'baker'?","o":["bage","bager","bjerg","bærer"],"a":"bager","r":"'Baker' er en bager. 'Bake' betyder at bage."},
{"g":4,"b":2,"k":"o","q":"Hvad hedder 'tandlæge' på engelsk?","o":["dentist","doctor","teacher","tourist"],"a":"dentist","r":"Tandlæge = dentist. Læge = doctor."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'pilot'?","o":["politimand","postbud","pirat","pilot"],"a":"pilot","r":"'Pilot' er en pilot, der flyver fly."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'shop assistant'?","o":["butiksejer","kunde","ekspedient","kasse"],"a":"ekspedient","r":"En 'shop assistant' er en ekspedient, der hjælper i butikken."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'artist'?","o":["skuespiller","kunstner","artig","arkitekt"],"a":"kunstner","r":"'Artist' betyder kunstner. Skuespiller hedder 'actor'."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'singer'?","o":["sanger","svinger","finger","sikker"],"a":"sanger","r":"'Singer' er en sanger — én der synger (sings)."},
{"g":4,"b":2,"k":"o","q":"Hvad hedder 'trøje' på engelsk?","o":["jacket","jeans","jam","jumper"],"a":"jumper","r":"Trøje = jumper (britisk) eller sweater. 'Jacket' er en jakke."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'gloves'?","o":["glas","gløder","handsker","strømper"],"a":"handsker","r":"'Gloves' betyder handsker eller vanter."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'scarf'?","o":["skærf","halstørklæde","skraber","skjorte"],"a":"halstørklæde","r":"'Scarf' betyder halstørklæde."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'boots'?","o":["støvler","både","bøger","bukser"],"a":"støvler","r":"'Boots' betyder støvler. 'Rain boots' = gummistøvler."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'skirt'?","o":["skjorte","skærf","skjold","nederdel"],"a":"nederdel","r":"'Skirt' betyder nederdel. Skjorte hedder 'shirt'."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'pyjamas'?","o":["badetøj","regntøj","nattøj","sportstøj"],"a":"nattøj","r":"'Pyjamas' er nattøj, man sover i."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'living room'?","o":["soveværelse","stue","levende rum","kælder"],"a":"stue","r":"'Living room' er stuen. Man 'lever' der i løbet af dagen."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'stairs'?","o":["trapper","stjerner","stole","stalde"],"a":"trapper","r":"'Stairs' betyder trapper. 'Go upstairs' = gå ovenpå."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'roof'?","o":["rum","rude","rod","tag"],"a":"tag","r":"'Roof' betyder tag (på et hus)."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'wall'?","o":["vold","hval","væg","vej"],"a":"væg","r":"'Wall' betyder væg eller mur."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'floor'?","o":["flod","gulv","blomst","fløde"],"a":"gulv","r":"'Floor' betyder gulv. Blomst hedder 'flower'."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'sofa'?","o":["sofa","seng","stol","skab"],"a":"sofa","r":"'Sofa' er det samme på engelsk og dansk. Man siger også 'couch'."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'grapes'?","o":["grapefrugt","græs","gryder","vindruer"],"a":"vindruer","r":"'Grapes' er vindruer."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'pear'?","o":["perle","par","pære","peber"],"a":"pære","r":"'Pear' betyder pære. Pas på: 'pair' betyder et par."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'meat'?","o":["møde","kød","mad","mælk"],"a":"kød","r":"'Meat' betyder kød. 'Meet' (møde) udtales på samme måde."},
{"g":4,"b":2,"k":"o","q":"Hvad hedder 'smør' på engelsk?","o":["butter","bread","better","bitter"],"a":"butter","r":"Smør = butter. 'Better' betyder bedre."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'sugar'?","o":["suppe","salt","sukkerrør","sukker"],"a":"sukker","r":"'Sugar' betyder sukker."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'dinner'?","o":["morgenmad","frokost","aftensmad","dessert"],"a":"aftensmad","r":"'Dinner' er aftensmad, dagens store måltid."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'tennis'?","o":["bordtennis","tennis","badminton","golf"],"a":"tennis","r":"'Tennis' er det samme på engelsk. Bordtennis hedder 'table tennis'."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'skate'?","o":["løbe på skøjter eller skateboard","skatte","skære","skrive"],"a":"løbe på skøjter eller skateboard","r":"'Skate' betyder at løbe på skøjter eller køre på skateboard."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'climb'?","o":["kalde","kaste","klippe","klatre"],"a":"klatre","r":"'Climb' betyder klatre. 'Climb a tree' = klatre i et træ."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'throw'?","o":["trække","tro","kaste","tørre"],"a":"kaste","r":"'Throw' betyder kaste. 'Throw the ball!' = kast bolden!"},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'catch'?","o":["kaste","gribe","klappe","kæmpe"],"a":"gribe","r":"'Catch' betyder gribe. 'Catch the ball!' = grib bolden!"},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'kick'?","o":["sparke","kigge","kysse","kilde"],"a":"sparke","r":"'Kick' betyder sparke. 'Kick the ball' = spark til bolden."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'win'?","o":["vinke","vente","vise","vinde"],"a":"vinde","r":"'Win' betyder vinde. Det modsatte er 'lose' — tabe."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'tall'?","o":["tal","tyk","høj","tung"],"a":"høj","r":"'Tall' betyder høj (om mennesker og bygninger)."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'strong'?","o":["streng","stærk","strand","stram"],"a":"stærk","r":"'Strong' betyder stærk. Det modsatte er 'weak' — svag."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'lazy'?","o":["doven","let","lys","lidt"],"a":"doven","r":"'Lazy' betyder doven."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'wet'?","o":["varm","vild","hvid","våd"],"a":"våd","r":"'Wet' betyder våd. Det modsatte er 'dry' — tør."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'dark'?","o":["dansk","dårlig","mørk","tyk"],"a":"mørk","r":"'Dark' betyder mørk. Det modsatte er 'light' — lys."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'cheap'?","o":["dyr","billig","skib","chip"],"a":"billig","r":"'Cheap' betyder billig. Det modsatte er 'expensive' — dyr."},
{"g":4,"b":2,"k":"h","q":"Hvad betyder 'How much is it?'","o":["Hvad koster det?","Hvor mange er der?","Hvor stort er det?","Hvor er det?"],"a":"Hvad koster det?","r":"'How much' bruges om pris: How much is it? = hvad koster det?"},
{"g":4,"b":2,"k":"h","q":"Hvad betyder 'What do you do in your free time?'","o":["Hvornår har du fri?","Hvad laver du i skolen?","Har du tid i dag?","Hvad laver du i din fritid?"],"a":"Hvad laver du i din fritid?","r":"'Free time' betyder fritid."},
{"g":4,"b":2,"k":"h","q":"Hvad betyder 'I'm bored'?","o":["Jeg er bange","Jeg er træt","Jeg keder mig","Jeg er født"],"a":"Jeg keder mig","r":"'Bored' betyder at kede sig. 'Boring' betyder kedelig."},
{"g":4,"b":2,"k":"h","q":"Hvad betyder 'Can I help you?' i en butik?","o":["Kan du hjælpe mig?","Kan jeg hjælpe dig?","Må jeg købe den?","Hvad koster den?"],"a":"Kan jeg hjælpe dig?","r":"Ekspedienten siger 'Can I help you?' = kan jeg hjælpe dig?"},
{"g":4,"b":2,"k":"h","q":"Hvad betyder 'Let's go!'?","o":["Lad os gå/komme af sted!","Lad være!","Lad mig gå!","Lad os blive!"],"a":"Lad os gå/komme af sted!","r":"'Let's go!' betyder 'lad os komme af sted!'"},
{"g":4,"b":2,"k":"h","q":"Hvad betyder 'What's wrong?'","o":["Hvad er rigtigt?","Hvem har ret?","Hvad skriver du?","Hvad er der galt?"],"a":"Hvad er der galt?","r":"'Wrong' betyder forkert. 'What's wrong?' = hvad er der galt?"},
{"g":4,"b":2,"k":"h","q":"Hvad betyder 'Good idea!'?","o":["Godt gået!","Godt nytår!","God idé!","Godt spørgsmål!"],"a":"God idé!","r":"'Idea' betyder idé."},
{"g":4,"b":2,"k":"h","q":"Hvad betyder 'I agree'?","o":["Jeg er vred","Jeg er enig","Jeg er klar","Jeg er ked af det"],"a":"Jeg er enig","r":"'Agree' betyder være enig. 'I don't agree' = jeg er uenig."},
{"g":4,"b":2,"k":"h","q":"Hvad betyder 'Have fun!'?","o":["Hav det sjovt!","Hav en god dag!","Hav det godt!","Hav tålmodighed!"],"a":"Hav det sjovt!","r":"'Fun' betyder sjov. 'Have fun!' = hav det sjovt!"},
{"g":4,"b":2,"k":"h","q":"Hvordan spørger man om vej til stationen?","o":["Where do you go station?","What is the station?","When is the station?","How do I get to the station?"],"a":"How do I get to the station?","r":"'How do I get to …?' betyder 'hvordan kommer jeg til …?'"},
{"g":4,"b":2,"k":"h","q":"Hvad betyder 'Go straight on'?","o":["Gå tilbage","Drej til højre","Gå ligeud","Stop her"],"a":"Gå ligeud","r":"'Straight on' betyder ligeud. Højre = right, venstre = left."},
{"g":4,"b":2,"k":"h","q":"Hvad betyder 'Turn right'?","o":["Drej til venstre","Drej til højre","Gå ligeud","Vend om"],"a":"Drej til højre","r":"'Right' betyder højre. 'Turn right' = drej til højre."},
{"g":4,"b":2,"k":"g","q":"Hvilket ord mangler? 'She ___ TV every evening.'","o":["watches","watch","watching","watchs"],"a":"watches","r":"Med 'she' får verbet -s. Efter -ch tilføjer man -es: watches."},
{"g":4,"b":2,"k":"g","q":"Hvilket ord mangler? 'My brother ___ in Aarhus.'","o":["live","living","are live","lives"],"a":"lives","r":"'My brother' = 'he', så verbet får -s: he lives."},
{"g":4,"b":2,"k":"g","q":"Hvilket ord mangler? 'I usually ___ to school by bike.'","o":["goes","going","go","went"],"a":"go","r":"Med 'I' får verbet ikke -s: I go. 'Usually' betyder normalt."},
{"g":4,"b":2,"k":"g","q":"Hvilket ord mangler? 'We ___ English on Mondays.'","o":["has","have","haves","having"],"a":"have","r":"Med 'we' bruger man 'have': We have English on Mondays."},
{"g":4,"b":2,"k":"g","q":"Hvilket ord mangler? 'The picture is ___ the wall.'","o":["on","in","at","under"],"a":"on","r":"Billeder hænger 'on the wall' — på væggen."},
{"g":4,"b":2,"k":"g","q":"Hvilket ord mangler? 'I was born ___ May.'","o":["on","at","of","in"],"a":"in","r":"Man bruger 'in' ved måneder: in May = i maj."},
{"g":4,"b":2,"k":"g","q":"Hvilket ord mangler? 'School starts ___ eight o'clock.'","o":["in","on","at","by"],"a":"at","r":"Ved klokkeslæt bruger man 'at': at eight o'clock."},
{"g":4,"b":2,"k":"g","q":"Hvilket ord mangler? 'We have no school ___ Saturday.'","o":["in","on","at","of"],"a":"on","r":"Ved ugedage bruger man 'on': on Saturday."},
{"g":4,"b":2,"k":"g","q":"Hvad er flertal af 'woman'?","o":["women","womans","womens","woman"],"a":"women","r":"'Woman' er uregelmæssig: one woman, two women."},
{"g":4,"b":2,"k":"g","q":"Hvad er flertal af 'person'?","o":["persons","peoples","personnes","people"],"a":"people","r":"Flertal af 'person' er normalt 'people': one person, many people."},
{"g":4,"b":2,"k":"g","q":"Hvad er flertal af 'lady'?","o":["ladys","ladyes","ladies","ladis"],"a":"ladies","r":"Konsonant + y bliver til -ies: lady → ladies."},
{"g":4,"b":2,"k":"g","q":"Hvilket ord mangler? 'Look at ___ dog!' (den hund derovre)","o":["this","that","these","those"],"a":"that","r":"'That' bruges om én ting langt væk. 'This' er om noget tæt på."},
{"g":4,"b":2,"k":"g","q":"Hvilket ord mangler? '___ are my shoes.' (de her sko)","o":["These","This","That","There"],"a":"These","r":"'These' bruges om flere ting tæt på: These are my shoes."},
{"g":4,"b":2,"k":"g","q":"Hvilket ord mangler? 'Is this ___ pencil, Tom?' (din)","o":["you","yours","you're","your"],"a":"your","r":"'Your' betyder din. 'You're' er en forkortelse af 'you are'."},
{"g":4,"b":2,"k":"l","q":"Læs: 'Every Saturday Sophie goes to the stable to ride her horse.' Hvad gør Sophie om lørdagen?","o":["Hun svømmer","Hun spiller fodbold","Hun rider","Hun maler"],"a":"Hun rider","r":"'Ride her horse' betyder ride på sin hest. En 'stable' er en stald."},
{"g":4,"b":2,"k":"l","q":"Læs: 'The jacket costs 30 pounds. Ben only has 20 pounds.' Kan Ben købe jakken?","o":["Ja, han har penge nok","Nej, han har for få penge","Ja, han får penge tilbage","Det står der ikke noget om"],"a":"Nej, han har for få penge","r":"Jakken koster 30 pund, men Ben har kun 20 pund (only has 20)."},
{"g":4,"b":2,"k":"l","q":"Læs: 'My grandma lives in a small house by the sea.' Hvor bor bedstemor?","o":["i et lille hus ved havet","i et stort hus ved søen","i en lejlighed i byen","på en gård"],"a":"i et lille hus ved havet","r":"'Small house' = lille hus, 'by the sea' = ved havet."},
{"g":4,"b":2,"k":"l","q":"Læs: 'Adam is wearing shorts and a T-shirt.' Hvordan er vejret sikkert?","o":["koldt","snevejr","meget blæsende","varmt"],"a":"varmt","r":"Shorts og T-shirt har man på, når det er varmt."},
{"g":4,"b":2,"k":"l","q":"Læs: 'The film starts at 7. We must leave at 6:30.' Hvornår skal de tage af sted?","o":["syv","seks","halv syv","otte"],"a":"halv syv","r":"'Leave at 6:30' betyder tage af sted kl. halv syv."},
{"g":4,"b":2,"k":"l","q":"Læs: 'Olivia's favourite subject is maths, but she doesn't like art.' Hvilket fag kan Olivia ikke lide?","o":["matematik","billedkunst","engelsk","idræt"],"a":"billedkunst","r":"'Art' betyder billedkunst. 'Maths' er hendes yndlingsfag."},
{"g":4,"b":2,"k":"l","q":"Læs: 'Oliver brushes his teeth, puts on his pyjamas and goes to bed.' Hvornår på dagen er det?","o":["om aftenen","om morgenen","ved frokost","om eftermiddagen"],"a":"om aftenen","r":"Han tager nattøj på (pyjamas) og går i seng — det er aften."},
{"g":4,"b":2,"k":"l","q":"Læs: 'The baker opens his shop at 6 in the morning.' Hvem åbner butikken?","o":["slagteren","læreren","lægen","bageren"],"a":"bageren","r":"'Baker' betyder bager."},
{"g":4,"b":2,"k":"l","q":"Læs: 'Ella can't find her cat. She looks under the bed and in the garden.' Hvad leder Ella efter?","o":["sin seng","sin have","sin kat","sin taske"],"a":"sin kat","r":"'Can't find her cat' = kan ikke finde sin kat."},
{"g":4,"b":2,"k":"l","q":"Læs: 'It's 3 o'clock. School finishes at 2.' Er skolen slut?","o":["Nej, om en time","Ja, for en time siden","Nej, den begynder nu","Ja, lige nu"],"a":"Ja, for en time siden","r":"Skolen slutter (finishes) kl. 2, og nu er klokken 3. Den sluttede for en time siden."},
{"g":4,"b":2,"k":"l","q":"Læs: 'Noah has a cat called Tiger. Tiger is black and white.' Hvad er Tiger?","o":["en kat","en tiger","en hund","en hest"],"a":"en kat","r":"Tiger er navnet på Noahs kat (a cat called Tiger)."},
{"g":4,"b":2,"k":"l","q":"Læs: 'Freddie drinks a glass of milk every morning.' Hvor tit drikker Freddie mælk?","o":["hver aften","om søndagen","aldrig","hver morgen"],"a":"hver morgen","r":"'Every morning' betyder hver morgen."},
{"g":4,"b":2,"k":"l","q":"Læs: 'Lucy is the tallest girl in her class.' Hvad betyder det?","o":["Lucy er den mindste","Lucy er den yngste","Ingen piger i klassen er højere end Lucy","Lucy er klassens lærer"],"a":"Ingen piger i klassen er højere end Lucy","r":"'Tallest' betyder højest."},
{"g":4,"b":2,"k":"l","q":"Læs: 'Please take off your shoes before you come in.' Hvad skal man gøre?","o":["tage skoene på","tage skoene af","købe nye sko","vaske skoene"],"a":"tage skoene af","r":"'Take off' betyder tage af. 'Put on' betyder tage på."},
{"g":4,"b":2,"k":"l","q":"Læs: 'Jack goes to bed at 9, but on Fridays he can stay up until 10.' Hvornår går Jack i seng om fredagen?","o":["kl. 10","kl. 9","kl. 8","kl. 11"],"a":"kl. 10","r":"'Stay up until 10' = blive oppe til kl. 10."},
{"g":4,"b":2,"k":"l","q":"Læs: 'There is a big tree in our garden. Birds live in it.' Hvor bor fuglene?","o":["i huset","i haven ved søen","på taget","i træet"],"a":"i træet","r":"'Birds live in it' = fugle bor i det (træet)."},
{"g":4,"b":2,"k":"o","q":"Hvad betyder 'busy'?","o":["bus","buskads","travl","ked af det"],"a":"travl","r":"'Busy' betyder travl eller optaget: 'I'm busy' = jeg har travlt."},
{"g":4,"b":2,"k":"h","q":"Hvad betyder 'Turn left at the church'?","o":["Drej til højre ved kirken","Drej til venstre ved kirken","Gå ligeud forbi kirken","Stop foran kirken"],"a":"Drej til venstre ved kirken","r":"'Left' betyder venstre, og 'church' betyder kirke."},
{"g":4,"b":2,"k":"g","q":"Hvilket ord mangler? 'My birthday is ___ the 5th of June.'","o":["on","in","at","by"],"a":"on","r":"Ved datoer bruger man 'on': on the 5th of June."}
]$$::jsonb) AS e
JOIN (VALUES
  ('o', 'ordforråd', 'recall', 'factual', 'surface_association'),
  ('h', 'hverdagsudtryk', 'comprehension', 'conceptual', 'surface_association'),
  ('g', 'grammatik', 'application', 'applied', 'overgeneralization'),
  ('l', 'læseforståelse', 'analysis', 'inferential', 'surface_association')
) AS m(k, concept, skill, dtype, mis) ON m.k = e->>'k';
