-- Section 82 — World War 1 Content Sprint
-- 50 questions: Grade 7 (25) + Grade 8 (25).
-- Bands: B1x12, B2x14, B3x14, B4x10
-- Grade 7: B1x6, B2x7, B3x7, B4x5
-- Grade 8: B1x6, B2x7, B3x7, B4x5
-- Domain: world_war_1. Focus: causes, consequences, everyday life, connections to WWII.

-- ─── GRADE 7 · BAND 1 (6 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var alliancesystemet foer Forste Verdenskrig?","options":["En raekke aftaler der betod at hvis et land blev angrebet maatte dets allierede hjaelpe det","En handelsaftale der hjalp lande med at saelge varer til hinanden","En fredsaftale der garanterede at Europa aldrig ville have krig igen","Et system hvor lande maatte spoerge en domstol foer de aabnede krig"],"correct":"En raekke aftaler der betod at hvis et land blev angrebet maatte dets allierede hjaelpe det","accepted_answers":["En raekke aftaler der betod at hvis et land blev angrebet maatte dets allierede hjaelpe det"],"review_text":"Europa var delt i to store alliancer. Triple Entente: Frankrig, Rusland og England. Triple Alliance: Germany, Oestrig-Ungarn og Italien. Hvis et land gik i krig ville alle dets allierede automatisk goere det samme."}'::jsonb,
  'mc','short','{"concepts":["alliancer","Triple Entente","Triple Alliance","automatisk krig"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_1',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvem blev myrdet i Sarajevo i 1914 og udloeste dermed Forste Verdenskrig?","options":["Den ostrigsk-ungarnske aartehertug Franz Ferdinand","Kejser Wilhelm II af Germany","Tsar Nikolaj II af Rusland","Kong George V af England"],"correct":"Den ostrigsk-ungarnske aartehertug Franz Ferdinand","accepted_answers":["Den ostrigsk-ungarnske aartehertug Franz Ferdinand"],"review_text":"Den 28. juni 1914 blev den ostrigsk-ungarnske aartehertug Franz Ferdinand skudt i Sarajevo. Gerningsmanden var den serbiske nationalist Gavrilo Princip. Mordet udloeste en kaedereaktion der endte i verdenskrig."}'::jsonb,
  'mc','short','{"concepts":["Franz Ferdinand","Sarajevo","mordet","udbrud"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_1',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var skyttegravskrig?","options":["En type krig hvor soldaterne boede og kaempede i lange udgravede groefte","En type krig der foregik paa havet","En krig hvor kavaleri var den vigtigste styrke","En krig der foregik i bjerge og skove"],"correct":"En type krig hvor soldaterne boede og kaempede i lange udgravede groefte","accepted_answers":["En type krig hvor soldaterne boede og kaempede i lange udgravede groefte"],"review_text":"Paa Vestfronten gravede begge sider lange groefte. Soldaterne boede i disse groefte og forsoegte at erobre fjendens stillinger. Imellem de to sider laag ingenmandsland som var ekstremt farligt at krydse."}'::jsonb,
  'mc','short','{"concepts":["skyttegrave","Vestfronten","ingenmandsland","doedvande"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_1',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var ny militaer teknologi i Forste Verdenskrig?","options":["Giftgas, maskingevaerer og fly","Nukleare bomber og missiler","Lasservaaben og droner","Svaerd og hestevogne"],"correct":"Giftgas, maskingevaerer og fly","accepted_answers":["Giftgas, maskingevaerer og fly"],"review_text":"Forste Verdenskrig indfoerte ny og frygtelig teknologi. Giftgas drab og skaadede tusindvis. Maskingevaerer kunne skyde hundredvis af kugler i minuttet. Fly blev brugt til rekognoscering og bomninger. Det goerede krigen endnu mere dodelig."}'::jsonb,
  'mc','short','{"concepts":["giftgas","maskingevaer","fly","ny teknologi","dodelig"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_1',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var nationalisme i Europas sammenaenhaeng foer Forste Verdenskrig?","options":["En stærk tro paa at ens eget folk og nation fortjente magt og selvraadighed","En politisk bevaegelse der oenskede at afskaffe alle graenser i Europa","En religioes bevaegelse der ville forene alle kristne lande","Et okonomisk system baseret paa international handel"],"correct":"En stærk tro paa at ens eget folk og nation fortjente magt og selvraadighed","accepted_answers":["En stærk tro paa at ens eget folk og nation fortjente magt og selvraadighed"],"review_text":"Nationalisme betod at folk folte stærk tilknytning til deres nation. Det styrkede sammenholdet i mange lande. Men det skabte ogsaa fjendskab og konkurrence mellem nationer og bidrog til krigen."}'::jsonb,
  'mc','short','{"concepts":["nationalisme","nation","identitet","rivalisering"],"misconception_type":"scope_confusion","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_1',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad skete der med kvinders rolle under Forste Verdenskrig?","options":["Kvinder overtog mange mandsdomineerede jobs da maend var ved fronten","Kvinders rolle aendrede sig slet ikke under krigen","Kvinder fik forbud mod at arbejde for at beskytte dem","Kvinder kaeempede som soldater paa alle fronter"],"correct":"Kvinder overtog mange mandsdomineerede jobs da maend var ved fronten","accepted_answers":["Kvinder overtog mange mandsdomineerede jobs da maend var ved fronten"],"review_text":"Da maendene blev sendt til fronten manglede fabrikker og gaarde arbejdskraft. Kvinder overtog jobs i vaabenfabrikker, transport og sundhedsvaesen. Det aendrede synet paa hvad kvinder kunne og maatte goere."}'::jsonb,
  'mc','short','{"concepts":["kvinder","roller","arbejde","fabrikker","forandring"],"misconception_type":"overgeneralization","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_1',7,1
);

-- ─── GRADE 7 · BAND 2 (7 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvorfor betod alliancesystemet at en lokal konflikt hurtigt blev en verdenskrig?","options":["Fordi hvert land der gik i krig automatisk trak sine allierede med ind","Fordi alliancerne forbod lande at foere krig mod hinanden","Fordi alle lande i verden var med i den samme alliance","Fordi ingen lande ville hjaelpe hinanden og det skabte kaos"],"correct":"Fordi hvert land der gik i krig automatisk trak sine allierede med ind","accepted_answers":["Fordi hvert land der gik i krig automatisk trak sine allierede med ind"],"review_text":"Oestrig-Ungarn erklaerede krig mod Serbien. Rusland mobiliserede for at hjaelpe Serbien. Germany erklaerede krig mod Rusland. Frankrig og England kom ind. Paa faa uger var en lokal konflikt blevet en europaeisk krig."}'::jsonb,
  'mc','short','{"concepts":["alliancer","kaedereaktion","eskalering","verdenskrig"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_1',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var forholdet mellem mordet paa Franz Ferdinand og Forste Verdenskrigs udbrud?","options":["Mordet var den gnist der udloeste krigen men de egentlige aarsager var dybe spaendinger der havde bygget op i aartier","Mordet var den eneste og direkte aarsag til krigen","Mordet var uvaesentligt og krigen ville have brudt ud uanset hvad","Mordet foraarsakede kun en kortvarig konflikt mellem Oestrig og Serbien"],"correct":"Mordet var den gnist der udloeste krigen men de egentlige aarsager var dybe spaendinger der havde bygget op i aartier","accepted_answers":["Mordet var den gnist der udloeste krigen men de egentlige aarsager var dybe spaendinger der havde bygget op i aartier"],"review_text":"Franz Ferdinand var gnisten ikke aarsagen. Nationalisme, rustningskaapplobet, imperialisme og alliancesystemet havde bygget op i aaratier. Mordet var blot den begivenhed der satte det hele i gang."}'::jsonb,
  'mc','short','{"concepts":["Franz Ferdinand","gnist","strukturelle aarsager","MAIN","misconception-en-aarsag"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_1',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvorfor var skyttegravskrigen saa dodelig?","options":["Maskingevaerer dræbte alle der angreb over aabent terrae og skaabte en blodig doedvande","Soldaterne var traeante til at doe og betragtede det ikke som et problem","Skyttegravene var kun til pynt og kampen foregik egentlig andre steder","Teknologien var saa ny at soldaterne ikke vidste hvad de foretog sig"],"correct":"Maskingevaerer dræbte alle der angreb over aabent terrae og skaabte en blodig doedvande","accepted_answers":["Maskingevaerer dræbte alle der angreb over aabent terrae og skaabte en blodig doedvande"],"review_text":"Et enkelt maskingevaer kunne dræbe hundredvis af angribende soldater paa minutter. Forsvar var nu langt stærkere end angreb. Det betod at krigen gik i staa i aaarevis mens begge sider led enorme tab."}'::jsonb,
  'mc','short','{"concepts":["maskingevaer","defensiv teknologi","doedvande","tab","skyttegrave"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_1',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var formaaalet med propaganda under Forste Verdenskrig?","options":["At holde befolkningens moral oppe, rekruttere soldater og fremstille fjenden som ond","At formidle objektiv information om krigens foerlob til borgerne","At koordinere militaere operationer mellem allierede","At kommunikere med soldaterne ved fronten"],"correct":"At holde befolkningens moral oppe, rekruttere soldater og fremstille fjenden som ond","accepted_answers":["At holde befolkningens moral oppe, rekruttere soldater og fremstille fjenden som ond"],"review_text":"Alle krigsfoerende lande brugte propaganda aktivt. Plakater og film fremstillede fjenden som barbarisk. Det var vigtigt for at faa maeand til at melde sig og faa befolkningen til at stoette krigen."}'::jsonb,
  'mc','short','{"concepts":["propaganda","moral","rekruttering","fjendebillede","manipulation"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_1',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvordan ramte Forste Verdenskrig civile bag fronten?","options":["Via rationering af mad, bomninger af byer og sorgen over at miste familiemedlemmer","Civile var fuldt beskyttede og maerkede naesten ikke krigen","Kun civile nær fronten maerkede krigen","Civile tjente penge fordi fabrikker arbejdede haardere"],"correct":"Via rationering af mad, bomninger af byer og sorgen over at miste familiemedlemmer","accepted_answers":["Via rationering af mad, bomninger af byer og sorgen over at miste familiemedlemmer"],"review_text":"Krigen var ikke kun for soldater. Civile maerkede den via madmangel, bombeangreb og den konstante frygt for at miste en far, bror eller son. For mange familier varede sorgen i aartier."}'::jsonb,
  'mc','short','{"concepts":["civile","hjemmefront","rationering","bomninger","misconception-kun-soldater"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_1',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvorfor fortsatte soldaterne med at kaempe i de frygtelige skyttegraver aar efter aar?","options":["Kombination af pligtsfolelse, kammeratskab, frygt for straf og propaganda om aere og heroisme","Fordi de syntes det var spaeaendende","Fordi de ikke vidste hvad der foregik","Fordi de alle troede krigen ville slutte inden for faa uger"],"correct":"Kombination af pligtsfolelse, kammeratskab, frygt for straf og propaganda om aere og heroisme","accepted_answers":["Kombination af pligtsfolelse, kammeratskab, frygt for straf og propaganda om aere og heroisme"],"review_text":"Soldaterne fortsatte ikke kun af mod. Kammeratskab, pligtsfolelse og frygt for militaer straf holdt dem i graevterne. Desertore risikerede doedsstraffen. Propaganda overbeviste mange om at de kaeempede for et hoejere formaal."}'::jsonb,
  'mc','short','{"concepts":["soldater","kammeratskab","pligtsfolelse","straf","propaganda"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"perspective_shift","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_1',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var rustningskaapplobet foer Forste Verdenskrig?","options":["En konkurrence mellem de store magter om at opbygge storre og stærkere haer og flaader end sine rivaler","En konkurrence om at bygge de bedste jernbaner i Europa","En konkurrence om at erobre flest kolonier i Afrika","En aftale om at dele militaere teknologier med hinanden"],"correct":"En konkurrence mellem de store magter om at opbygge storre og stærkere haer og flaader end sine rivaler","accepted_answers":["En konkurrence mellem de store magter om at opbygge storre og stærkere haer og flaader end sine rivaler"],"review_text":"Isaer England og Germany havde et intenst kaapplob om floestyrke. Begge lande byggede krigssskibe i et rasende tempo. Det skabte frygt og mistillid og goerede krig mere sandsynlig."}'::jsonb,
  'mc','short','{"concepts":["rustningskaapplob","militarisme","flaaade","Germany","England","spaending"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_1',7,2
);

-- ─── GRADE 7 · BAND 3 (7 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved forestillingen om at nationalisme altid var positiv foer Forste Verdenskrig?","options":["Nationalisme skabte ogsaa had til andre folkegrupper og rivalisering der goerede krig mere sandsynlig","Forestillingen er korrekt nationalisme var altid en positiv kraft","Nationalisme forhindrede faktisk krig ved at gore hvert land selvtilstraekkeligt","Nationalisme eksisterede ikke foer Forste Verdenskrig"],"correct":"Nationalisme skabte ogsaa had til andre folkegrupper og rivalisering der goerede krig mere sandsynlig","accepted_answers":["Nationalisme skabte ogsaa had til andre folkegrupper og rivalisering der goerede krig mere sandsynlig"],"review_text":"Nationalisme kan vaere positiv som stolthed over sin kultur. Men den kan ogsaa vaere farlig naar den betyder at man ser andre nationer som fjender. I perioden foer 1914 skabte nationalisme rivalisering der bidrog til krigen."}'::jsonb,
  'mc','short','{"concepts":["nationalisme","had","rivalisering","misconception-nationalisme-positiv","dobbelttydig"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_1',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved forestillingen om at mordet paa Franz Ferdinand alene foraarsagede Forste Verdenskrig?","options":["Krigen havde fire dybe strukturelle aarsager bygget op i aartier: nationalisme, alliancer, imperialisme og militarisme","Forestillingen er korrekt mordet var den eneste reelle aarsag","Det er forkert fordi krigen ikke havde noget med mordet at goere","Det er forkert fordi det var Rusland der startede krigen"],"correct":"Krigen havde fire dybe strukturelle aarsager bygget op i aartier: nationalisme, alliancer, imperialisme og militarisme","accepted_answers":["Krigen havde fire dybe strukturelle aarsager bygget op i aartier: nationalisme, alliancer, imperialisme og militarisme"],"review_text":"Historikere bruger forkortelsen MAIN: Militarisme, Alliancer, Imperialisme, Nationalisme. Mordet var gnisten der taeaendte en situation der allerede var ekstremt spraeangfarlig. Fjern mordet og krigen ville sandsynligvis stadig have brudt ud."}'::jsonb,
  'mc','short','{"concepts":["MAIN","enkelt-aarsag","strukturelle aarsager","misconception-en-aarsag","Franz Ferdinand"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_1',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved forestillingen om at ny teknologi goerede krigen lettere for soldaterne?","options":["Ny teknologi skaabte de vaerst taenkelige vilkaar og goerede krigen endnu mere dodelig og langvarig","Forestillingen er korrekt teknologien hjalp soldaterne med at vinde hurtigt","Teknologien aendrede intet i praksis","Teknologien skadede primaert civile ikke soldaterne"],"correct":"Ny teknologi skaabte de vaerst taenkelige vilkaar og goerede krigen endnu mere dodelig og langvarig","accepted_answers":["Ny teknologi skaabte de vaerst taenkelige vilkaar og goerede krigen endnu mere dodelig og langvarig"],"review_text":"Giftgas, maskingevaerer og artilleri skabte et af historiens blodigste slagmarker. Teknologien styrkede forsvaret men svaekkede angrebet. Det skaabte en doedvande der kostede millioner af liv og varede fire aar."}'::jsonb,
  'mc','short','{"concepts":["teknologi","doedvande","dodelig","misconception-teknologi-lettere","artilleri"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_1',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var den langsigtede konsekvens af kvinders indsats under Forste Verdenskrig?","options":["Det hjalp med at aendre synet paa kvinder som kompetente deltagere i samfundet og styrkede stemmeretsbevaeegelsen","Kvinder vendte straks tilbage til de gamle roller da krigen sluttede og intet aendrede sig","Krigen svaekkede kvinders position i samfundet","Kvindernes roller aendrede sig kun i England"],"correct":"Det hjalp med at aendre synet paa kvinder som kompetente deltagere i samfundet og styrkede stemmeretsbevaeegelsen","accepted_answers":["Det hjalp med at aendre synet paa kvinder som kompetente deltagere i samfundet og styrkede stemmeretsbevaeegelsen"],"review_text":"I mange lande fik kvinder stemmeret kort efter krigen: England i 1918, USA i 1920. Krigen havde bevist at kvinder var fuldt kompetente til at drive samfundet. Det var svaert at tage den erkendelse tilbage."}'::jsonb,
  'mc','short','{"concepts":["kvinder","stemmeret","kompetence","langsigtede konsekvenser","forandring"],"misconception_type":"temporal_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_1',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved forestillingen om at Versailles-traktaten loeste Europas problemer?","options":["Traktaten ydmygede Germany saa haardt at den skabte de betingelser Hitler senere udnyttede","Forestillingen er korrekt traktaten skabte varig fred","Traktaten var for mild mod Germany og det var problemet","Traktaten loeste problemerne men kun til 1920"],"correct":"Traktaten ydmygede Germany saa haardt at den skabte de betingelser Hitler senere udnyttede","accepted_answers":["Traktaten ydmygede Germany saa haardt at den skabte de betingelser Hitler senere udnyttede"],"review_text":"Versailles paaloede Germany skylden for hele krigen og kraevede gigantiske erstatninger. Den tyske befolkning oplevede det som en dyb ydmygelse. Det skabte bitter vrede der gav Hitler og nationalsocialismen gunstige betingelser."}'::jsonb,
  'mc','short','{"concepts":["Versailles","ydmygelse","Hitler","konsekvenser","misconception-Versailles-loeste"],"misconception_type":"temporal_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_1',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forbindelsen mellem Forste og Anden Verdenskrig?","options":["Versailles-traktatens haarde betingelser skabte okonomisk nod og national ydmygelse i Germany der banede vejen for Hitler","Der er ingen forbindels de to krige var fuldstaendig uafhaengige","Forbindelsen er at de samme lande kaeampede mod hinanden","Forbindelsen er kun geografisk begge fandt sted i Europa"],"correct":"Versailles-traktatens haarde betingelser skabte okonomisk nod og national ydmygelse i Germany der banede vejen for Hitler","accepted_answers":["Versailles-traktatens haarde betingelser skabte okonomisk nod og national ydmygelse i Germany der banede vejen for Hitler"],"review_text":"Anden Verdenskrig voksede direkte ud af Forste. Versailles ydmygede Germany. Den Store Depression forvaerrerede krisen. Hitler lovede at gaengaelde ydmygelsen. Uden Versailles er det svaert at forestille sig Hitlers opkomst."}'::jsonb,
  'mc','short','{"concepts":["Versailles","Hitler","forbindels","WWI-WWII","misconception-uafhaengige"],"misconception_type":"temporal_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_1',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvordan bidrog imperialisme til Forste Verdenskrigs udbrud?","options":["Konkurrence om kolonier i Afrika og Asien skabte spaendinger og fjendskab mellem de europaeiske stormagter","Imperialisme forhindrede krigen fordi kolonier gav lande rigdom nok til at vaere tilfredse","Imperialisme var ikke relateret til krigen som foregik kun i Europa","Kun Frankrig og England rivaliserede om kolonier alle andre lande var tilfredse"],"correct":"Konkurrence om kolonier i Afrika og Asien skabte spaendinger og fjendskab mellem de europaeiske stormagter","accepted_answers":["Konkurrence om kolonier i Afrika og Asien skabte spaendinger og fjendskab mellem de europaeiske stormagter"],"review_text":"I 1914 kontrollerede de europaeiske magter store dele af verden. Konkurrencen om nye kolonier og ressourcer skabte bitter rivalisering. Det styrkede militarismen og skabte en atmosfaere af gensidig mistillid."}'::jsonb,
  'mc','short','{"concepts":["imperialisme","kolonier","rivalisering","spaendinger","MAIN"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_1',7,3
);

-- ─── GRADE 7 · BAND 4 (5 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betod skyttegravskrigen for den enkelte soldat i hverdagen?","options":["Konstant frygt, livsvilkaar med rotter og mudder og lange perioder af kedsomhed afbrudt af ekstrem vold","Spaeaendende og heroisk krig med mange muligheder for at vise mod","Komfortabel og rolig tjeneste med god mad","Soldaterne kaeampede kun i korte slag og hvilede resten af tiden"],"correct":"Konstant frygt, livsvilkaar med rotter og mudder og lange perioder af kedsomhed afbrudt af ekstrem vold","accepted_answers":["Konstant frygt, livsvilkaar med rotter og mudder og lange perioder af kedsomhed afbrudt af ekstrem vold"],"review_text":"Skyttegravene var fyldt med mudder, rotter og lig. Soldaterne levede i konstant frygt for artilleri og gasangreb. Perioder af kedsomhed blev brudt af frygtelige angrebsbolger. Mange fik psykologiske skader vi i dag kalder PTSD."}'::jsonb,
  'mc','short','{"concepts":["soldaters hverdagsliv","skyttegraven","PTSD","realitet vs heroisme","misconception-krigen-spaeandende"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_1',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved forestillingen om at Germany alene bar ansvaret for Forste Verdenskrig?","options":["Alle de store magter bidrog til optrapningen via militarisme, imperialisme og nationalisme","Forestillingen er korrekt Germany bar fuldt ansvar for krigen","Det er forkert fordi kun Oestrig-Ungarn bar ansvaret","Det er forkert fordi ingen lande bar ansvar krigen startede tilfaeldigt"],"correct":"Alle de store magter bidrog til optrapningen via militarisme, imperialisme og nationalisme","accepted_answers":["Alle de store magter bidrog til optrapningen via militarisme, imperialisme og nationalisme"],"review_text":"Versailles-traktatens krigsscyldsklausul var politisk ikke historisk. England og Frankrig konkurrerede aggressivt om kolonier. Rusland mobiliserede hurtigt. Oestrig-Ungarn udnyttede mordet. Alle store magter bidrog til eskalationen."}'::jsonb,
  'mc','short','{"concepts":["krigsansvar","Germany","delt ansvar","Versailles-klausul","misconception-kun-Germany"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_1',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Var Versailles-traktaten for haerd mod Germany?","options":["Mange historikere mener den var for haerd fordi den skabte ydmygelse og ekonomisk nod der hjalp Hitler til magten","Traktaten var for mild og det var grunden til at Hitler kom til magten","Traktaten var fuldt retfaerdig og havde ingen negative konsekvenser","Traktaten var irrelevant da Germany ignorerede den fuldstaendigt"],"correct":"Mange historikere mener den var for haerd fordi den skabte ydmygelse og ekonomisk nod der hjalp Hitler til magten","accepted_answers":["Mange historikere mener den var for haerd fordi den skabte ydmygelse og ekonomisk nod der hjalp Hitler til magten"],"review_text":"Fra fransk perspektiv var haardhed forstaaeelig: Frankrig var haerget. Men okenomisten Keynes advarede allerede i 1919 om at betingelserne ville skabe en ny krig. Han fik ret i 1939."}'::jsonb,
  'mc','short','{"concepts":["Versailles","retfaerdig fred","opskrift paa krig","Keynes","Hitler"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_1',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad viser det at England, Frankrig og USA alle brugte propaganda under Forste Verdenskrig?","options":["At demokratier er villige til at manipulere borgerne naar de foeler krigen er eksistentiel og at propaganda ikke er forbeholdt diktaturer","At demokratier var ligesaa slemme som diktaturer","At propaganda altid er etisk i krigstid","At propaganda kun eksisterede i Centraleuropa"],"correct":"At demokratier er villige til at manipulere borgerne naar de foeler krigen er eksistentiel og at propaganda ikke er forbeholdt diktaturer","accepted_answers":["At demokratier er villige til at manipulere borgerne naar de foeler krigen er eksistentiel og at propaganda ikke er forbeholdt diktaturer"],"review_text":"England, Frankrig og USA oprettede dedikerede propagandaministerier. Plakater, film og aviser manipulerede den offentlige mening. Det viser at propaganda er et redskab alle stater griber til i krig uanset styreform."}'::jsonb,
  'mc','short','{"concepts":["propaganda","demokrati","diktatur","misconception-propaganda-kun-diktaturer","manipulation"],"misconception_type":"scope_confusion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_1',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad viser soldaters breve og dagboeger om kloeften mellem officiel propaganda og krigens virkelighed?","options":["At soldaterne oplevede en krig meget forskellig fra den heroiske fremstilling mens censuren forhindrede dem i at fortaelle sandheden hjem","At soldaterne var enige i propagandaens fremstilling","At soldaterne ikke vidste hvad krigen var om","At soldaterne levede komfortabelt og var glade for oplevelsen"],"correct":"At soldaterne oplevede en krig meget forskellig fra den heroiske fremstilling mens censuren forhindrede dem i at fortaelle sandheden hjem","accepted_answers":["At soldaterne oplevede en krig meget forskellig fra den heroiske fremstilling mens censuren forhindrede dem i at fortaelle sandheden hjem"],"review_text":"Soldaternes breve hjem var censurerede. De maatte ikke skrive sandheden. Men dagboeger afslorer den raaende virkelighed: kameraterne der doede, den konstante frygt, meningsloesheden. Der var en enorm kloeft mellem officiel fremstilling og oplevd virkelighed."}'::jsonb,
  'mc','short','{"concepts":["censur","breve","dagboeger","virkelighed vs propaganda","kloeft"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_1',7,4
);

-- ─── GRADE 8 · BAND 1 (6 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betoekner forkortelsen MAIN som beskriver aarsagerne til Forste Verdenskrig?","options":["Militarisme, Alliancer, Imperialisme og Nationalisme","Moerke, Angreb, Invasion og Neutralitet","Magt, Agression, Interesser og Naboer","Mobilisering, Anneksion, Information og Normer"],"correct":"Militarisme, Alliancer, Imperialisme og Nationalisme","accepted_answers":["Militarisme, Alliancer, Imperialisme og Nationalisme"],"review_text":"Historikere bruger MAIN som huskeregel. Militarisme: rustningskaapplobet. Alliancer: automatiske forpligtelser. Imperialisme: kolonirivalisering. Nationalisme: stolthed og fjendskab. Ingen enkelt aarsag men alle fire samlet."}'::jsonb,
  'mc','short','{"concepts":["MAIN","militarisme","alliancer","imperialisme","nationalisme"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_1',8,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvilke lande udgoerde Triple Entente og Triple Alliance foer Forste Verdenskrig?","options":["Triple Entente: Frankrig, Rusland og England. Triple Alliance: Germany, Oestrig-Ungarn og Italien","Triple Entente: Germany, Oestrig-Ungarn og Tyrkiet. Triple Alliance: Frankrig, Rusland og England","Begge alliancer bestod af de samme fem lande","Triple Entente: USA, England og Frankrig. Triple Alliance: Germany og Oestrig"],"correct":"Triple Entente: Frankrig, Rusland og England. Triple Alliance: Germany, Oestrig-Ungarn og Italien","accepted_answers":["Triple Entente: Frankrig, Rusland og England. Triple Alliance: Germany, Oestrig-Ungarn og Italien"],"review_text":"Europa var delt i to lejer. Triple Entente vandt. Men ved krigens start skiftede Italien side og England og Frankrig fik USA med i 1917. Alliancerne var ikke faste men de skabte automatiske forpligtelser."}'::jsonb,
  'mc','short','{"concepts":["Triple Entente","Triple Alliance","alliancer","krigsdeltagere"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_1',8,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvornaar og hvor udkaempedes Forste Verdenskrig?","options":["1914-1918 primaert i Europa men ogsaa i Mellemøesten, Afrika og Asien","1910-1918 kun i Europa","1914-1920 kun paa Vestfronten","1916-1918 primaert i Rusland og Tyrkiet"],"correct":"1914-1918 primaert i Europa men ogsaa i Mellemøesten, Afrika og Asien","accepted_answers":["1914-1918 primaert i Europa men ogsaa i Mellemøesten, Afrika og Asien"],"review_text":"Krigen varede fra august 1914 til november 1918. Vestfronten i Frankrig og Belgien var den mest beromte. Men der var ogsaa Oestfronten mod Rusland, krig i Mellemoeesten, soeslag i Atlanterhavet og kampe om kolonier i Afrika."}'::jsonb,
  'mc','short','{"concepts":["krig 1914-1918","fronter","Vestfronten","global konflikt"],"misconception_type":"scope_confusion","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_1',8,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad indeholdt Versailles-traktaten fra 1919?","options":["Germany fik skylden for krigen, maatte betale store erstatninger og afgive territorier","Alle lande fik ens betingelser og delte krigsomkostningerne ligeligt","Traktaten garanterede Germany beskyttelse mod fremtidige angreb","Traktaten skabte et forenet Europa med faelles graenser"],"correct":"Germany fik skylden for krigen, maatte betale store erstatninger og afgive territorier","accepted_answers":["Germany fik skylden for krigen, maatte betale store erstatninger og afgive territorier"],"review_text":"Paragraf 231 var krigsscyldsklausulen. Germany fik skylden for hele krigen. Det skulle betale massive erstatninger og afstaa territorier herunder Alsace-Lorraine til Frankrig. Germany mistede ogsaa sine kolonier og store dele af sin haer."}'::jsonb,
  'mc','short','{"concepts":["Versailles","krigsscyldsklausul","erstatninger","territorier","1919"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_1',8,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvilke nye vaabentyper blev indfoert i Forste Verdenskrig?","options":["Tanks, fly, undervandsbaade og kemiske vaaaben som giftgas","Nukleare bomber og ballistiske missiler","Lasservaaben og droner","Maskingevaeret var den eneste nye teknologi"],"correct":"Tanks, fly, undervandsbaade og kemiske vaaaben som giftgas","accepted_answers":["Tanks, fly, undervandsbaade og kemiske vaaaben som giftgas"],"review_text":"Tanks broede igennem skyttegravslinjer. Fly patruljerede og bombede. Undervandsbaade angreb forsyningsskibe. Giftgas var den mest frygtede nyhed. Alle disse teknologier var nye og aendrede krigsforlobet."}'::jsonb,
  'mc','short','{"concepts":["tanks","fly","undervandsbaade","giftgas","ny teknologi"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_1',8,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betod begrebet total krig under Forste Verdenskrig?","options":["At hele samfundet var mobiliseret til krig herunder fabrikker, kvinder, okonomi og propaganda","At krigen foregik 24 timer i dognet uden pauser","At alle militaere ressourcer blev brugt paa een gang","At krigen spredte sig til alle verdensdele"],"correct":"At hele samfundet var mobiliseret til krig herunder fabrikker, kvinder, okonomi og propaganda","accepted_answers":["At hele samfundet var mobiliseret til krig herunder fabrikker, kvinder, okonomi og propaganda"],"review_text":"Total krig betod at skellet mellem civil og militaer sloev. Fabrikker producerede vaaaben. Kvinder arbejdede i industrien. Okonomier blev omstillet til krigsproduktion. Staten kontrollerede madvarer og information. Alle var en del af krigsindsatsen."}'::jsonb,
  'mc','short','{"concepts":["total krig","mobilisering","hjemmefront","stat","civil-militaer"],"misconception_type":"scope_confusion","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_1',8,1
);

-- ─── GRADE 8 · BAND 2 (7 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvordan skabte europaeisk imperialisme konkrete spaendinger foer Forste Verdenskrig?","options":["Rivalisering om kolonier i Afrika og Asien skabte gensidig frygt og konkurrence der goerede krig mere sandsynlig","Imperialisme skabte fred fordi lande var for optagede af kolonier til at kaempe mod hinanden","Kun Frankrig og England rivaliserede om kolonier resten var neutrale","Imperialisme var ikke relateret til krigen"],"correct":"Rivalisering om kolonier i Afrika og Asien skabte gensidig frygt og konkurrence der goerede krig mere sandsynlig","accepted_answers":["Rivalisering om kolonier i Afrika og Asien skabte gensidig frygt og konkurrence der goerede krig mere sandsynlig"],"review_text":"Marokko-kriserne i 1905 og 1911 bragte Frankrig og Germany naer ved krig. Konkurrence om Afrika og Asien forstaerkede militarismen. Imperialisme var ikke den eneste aarsag men den bidrog til atmosfaeren af rivalisering."}'::jsonb,
  'mc','short','{"concepts":["imperialisme","kolonier","rivalisering","Marokko-kriserne","spaendinger"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_1',8,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvorfor gik Vestfronten i staa i en blodig doedvande?","options":["Defensiv teknologi som maskingevaerer og artilleri var langt stærkere end angrebsteknologi saa ingen side kunne bryde igennem","Soldaterne paa begge sider naegtede at angribe","Vejrliget umuliggjorde fremrykning","Alliancerne naegtede at sende nok soldater til fronten"],"correct":"Defensiv teknologi som maskingevaerer og artilleri var langt stærkere end angrebsteknologi saa ingen side kunne bryde igennem","accepted_answers":["Defensiv teknologi som maskingevaerer og artilleri var langt stærkere end angrebsteknologi saa ingen side kunne bryde igennem"],"review_text":"Et enkelt maskingevaer kunne holde et helt kompagni tilbage. Artilleri forvandlede slagmarken til mudder. Angreb paa befoestede stillinger kostede enormt mange liv for minimale gevinster. Krigen gik i staa i naesten fire aar."}'::jsonb,
  'mc','short','{"concepts":["Vestfronten","doedvande","defensiv teknologi","angreb","maskingevaer"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_1',8,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvilke konkrete teknikker brugte krigstidens propaganda?","options":["Plakater der fremstillede fjenden som monster, censurerede aviser og film der heroiserede egne soldater","Propaganda var baseret paa faktuelle nyheder","Propaganda brugte kun radio der ikke fandtes foer 1920","Propaganda var frivillig og ingen lande tvang borgere til at se den"],"correct":"Plakater der fremstillede fjenden som monster, censurerede aviser og film der heroiserede egne soldater","accepted_answers":["Plakater der fremstillede fjenden som monster, censurerede aviser og film der heroiserede egne soldater"],"review_text":"Propagandaplakater fremstillede tyske soldater som barbariske mordere. Aviser var censurerede. Film viste heroiske soldater. Maal: faa maeand til at melde sig, faa kvinder til at stoette krigen og fastholde civil moral."}'::jsonb,
  'mc','short','{"concepts":["plakater","censur","film","fjendebillede","propaganda-teknikker"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_1',8,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betod det at Forste Verdenskrig var en total krig for hjemmefronten?","options":["Staten kontrollerede okonomien, rationerede mad og mobiliserede kvinder til industriarbejde","Civile bag fronten var fuldt beskyttede","Kun civile nær fronten var paavirket","Den civile okonomi voksede og alle levede bedre under krigen"],"correct":"Staten kontrollerede okonomien, rationerede mad og mobiliserede kvinder til industriarbejde","accepted_answers":["Staten kontrollerede okonomien, rationerede mad og mobiliserede kvinder til industriarbejde"],"review_text":"Hjemmefronten var en del af krigen. Mad blev rationeret. Fabrikkerne producerede vaaaben. Kvinder overtog jobs. Staten censurerede pressen. Hjemmefronten var ikke bagland men en aktiv del af krigsindsatsen."}'::jsonb,
  'mc','short','{"concepts":["hjemmefront","total krig","rationering","kvinder","statskontrol"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_1',8,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad fik USA til at gaa ind i Forste Verdenskrig i 1917?","options":["Tysk ubadskrig mod neutrale skibe og Zimmermann-telegrammet der tilbod Mexico amerikansk territorium","USA var allierede med England fra starten","Germany angreb amerikansk territorium direkte","Frankrig var ved at tabe og USA ville redde sine allierede"],"correct":"Tysk ubadskrig mod neutrale skibe og Zimmermann-telegrammet der tilbod Mexico amerikansk territorium","accepted_answers":["Tysk ubadskrig mod neutrale skibe og Zimmermann-telegrammet der tilbod Mexico amerikansk territorium"],"review_text":"USA var neutral fra start. Men Germanys ubadskrig sank civile skibe herunder amerikanske. Zimmermann-telegrammet var et hemmeligt forsoeg paa at overtale Mexico til at angribe USA. Begge dele fik USA med i krigen."}'::jsonb,
  'mc','short','{"concepts":["USA","ubadskrig","Zimmermann-telegram","neutralitet","1917"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_1',8,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad skete der med de store europaeiske imperier som foelge af Forste Verdenskrig?","options":["Det Osmanniske, Oestrig-Ungarnske, Russiske og Tyske kejserrige broede alle samman","Alle imperier overlevede krigen og fortsatte til 1945","Kun Germany mistede sit imperium de andre overlevede","Imperierene forstærkedes fordi de vandt nye kolonier"],"correct":"Det Osmanniske, Oestrig-Ungarnske, Russiske og Tyske kejserrige broede alle samman","accepted_answers":["Det Osmanniske, Oestrig-Ungarnske, Russiske og Tyske kejserrige broede alle samman"],"review_text":"Krigen udraderede fire store imperier. Det Russiske Kejserrige faldt i revolutionen 1917. Oestrig-Ungarn oplostes i mange nye stater. Det Tyske Kejserrige endte. Det Osmanniske Rige oplostes. Europas kort var radikalt forandret."}'::jsonb,
  'mc','short','{"concepts":["imperierenes fald","Rusland","Oestrig-Ungarn","Germany","Osmannerriget","konsekvenser"],"misconception_type":"temporal_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_1',8,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad forklarer at soldaterne fortsatte med at adlyde ordrer selvom de vidste et angreb ville koste mange liv?","options":["Kombination af disciplin, kammeratskab, frygt for doedsstraffen og tro paa at kampen tjente et hoejere formaal","Soldaterne vidste ikke at de ville doe","Soldaterne naegtede faktisk tit og der var konstante mytinier","Soldaterne var paavirket af stoffer og vidste ikke hvad de goerde"],"correct":"Kombination af disciplin, kammeratskab, frygt for doedsstraffen og tro paa at kampen tjente et hoejere formaal","accepted_answers":["Kombination af disciplin, kammeratskab, frygt for doedsstraffen og tro paa at kampen tjente et hoejere formaal"],"review_text":"At naegte en ordre i krig betod doedsstraffen. Kammeratskab betod at man ikke ville svigte dem ved siden af sig. Propaganda overbeviste mange om at de kaeempede for noget vigtigt. Alt dette holdt massedesertioner i skak."}'::jsonb,
  'mc','short','{"concepts":["lydighed","kammeratskab","doedsstraffen","propaganda","disciplin"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"perspective_shift","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_1',8,2
);

-- ─── GRADE 8 · BAND 3 (7 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er problemet med Versailles-traktatens konklusion om at Germany var eneansvarlig for krigen?","options":["Det var en politisk ydmygelse der ignorerede at alle store magter bidrog til de spaendinger der eksploderede i 1914","Der er intet problem Germany var faktisk eneansvarlig","Problemet er at Rusland og Frankrig burde have delt ansvaret med Germany","Problemet er kun at formuleringen var for mild"],"correct":"Det var en politisk ydmygelse der ignorerede at alle store magter bidrog til de spaendinger der eksploderede i 1914","accepted_answers":["Det var en politisk ydmygelse der ignorerede at alle store magter bidrog til de spaendinger der eksploderede i 1914"],"review_text":"Krigsscyldsklausulen var politisk ikke historisk. Sejrherrerne ville have Germany til at betale. Men England, Frankrig, Rusland og Oestrig-Ungarn bidrog alle til optrapningen. Det er konsensus blandt historikere i dag."}'::jsonb,
  'mc','short','{"concepts":["krigsansvar","Versailles","politisk beslutning","delt ansvar","historisk konsensus"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_1',8,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad forklarer at Forste Verdenskrig varede fire aar naer alle forventede den sluttede foer julen 1914?","options":["Defensiv teknologi skaabte en blodig doedvande og ingen side kunne opnaa det afgoorende gennembrud","Lederne paa begge sider onskede bevidst at forlange krigen","Ingen af parterne oenskede fred og forhandling","Vaabenstillstand var ulovlig under international ret"],"correct":"Defensiv teknologi skaabte en blodig doedvande og ingen side kunne opnaa det afgoorende gennembrud","accepted_answers":["Defensiv teknologi skaabte en blodig doedvande og ingen side kunne opnaa det afgoorende gennembrud"],"review_text":"Alle troede krigen ville vaere kort. Schlieffen-planen haabede paa seks uger. Men maskingevaerer og artilleri fastlaaeste fronterne. Ingen teknologi var god nok til at bryde igennem. Fire aars gensidigt blodbad folgede."}'::jsonb,
  'mc','short','{"concepts":["varighed","doedvande","Schlieffen","teknologi","forventninger"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_1',8,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er den direkte forbindels mellem Versailles-traktaten og Anden Verdenskrigs udbrud?","options":["Traktatens haardhed skabte okonomisk nod og national ydmygelse i Germany der gav Hitler og NSDAP den opbakning de behoevede","Der er ingen forbindels de to traktater var fuldstaendig separate","Traktaten forhindrede faktisk Anden Verdenskrig i 20 aar","Forbindelsen er kun at begge krige begyndte i Europa"],"correct":"Traktatens haardhed skabte okonomisk nod og national ydmygelse i Germany der gav Hitler og NSDAP den opbakning de behoevede","accepted_answers":["Traktatens haardhed skabte okonomisk nod og national ydmygelse i Germany der gav Hitler og NSDAP den opbakning de behoevede"],"review_text":"Den tyske okonomis kollaps under kravet om krigsudgifter og den nationale ydmygelse ved at acceptere eneansvar var giftige betingelser. Da Den Store Depression ramte i 1929 udnyttede Hitler bevidst hadet mod Versailles."}'::jsonb,
  'mc','short','{"concepts":["Versailles","Hitler","NSDAP","Den Store Depression","WWI-WWII forbindels"],"misconception_type":"temporal_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_1',8,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betod Forste Verdenskrig for de koloniserede folk i Afrika og Asien?","options":["De blev tvunget til at kaempe og doe i andres krig og fik ikke de friheder de var lovet som beloening bagefter","Koloniserede folk var fuldt frivillige og begejstrede deltagere","Koloniserede folk kaeampede ikke i krigen","Koloniserede folk fik fuld selvstaendighed straks efter krigen"],"correct":"De blev tvunget til at kaempe og doe i andres krig og fik ikke de friheder de var lovet som beloening bagefter","accepted_answers":["De blev tvunget til at kaempe og doe i andres krig og fik ikke de friheder de var lovet som beloening bagefter"],"review_text":"Over en million soldater fra franske og britiske kolonier kaeampede i krigen. Mange var tvangsindrullerede. De fik loefter om politiske reformer. Men efter krigen geninfoerte kolonimagterne det gamle system. Det saaede froe til de nationale befrielsesbevaegelser der folgete."}'::jsonb,
  'mc','short','{"concepts":["kolonier","kolonifolk","tvang","loefter","befrielsesbevaegelser"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_1',8,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad skete der med statens magt over borgerne under Forste Verdenskrig?","options":["Staten fik enorm magt over borgerne via censur, rationering, tvangsindkaldelse og kontrol med okonomien","Statens magt mindsksdes fordi krigen var for kaotisk til at kontrollere","Staten mistede kontrol og borgerne styrede sig selv under krigen","Statens magt aendrede sig ikke under krigen"],"correct":"Staten fik enorm magt over borgerne via censur, rationering, tvangsindkaldelse og kontrol med okonomien","accepted_answers":["Staten fik enorm magt over borgerne via censur, rationering, tvangsindkaldelse og kontrol med okonomien"],"review_text":"Total krig kraevede total kontrol. Staten bestemte hvad aviser maatte skrive. Den rationerede mad. Fabrikker omstillede sig til krigsproduktion. Tvangsindrullering sendte maeand til fronten mod deres vilje. Staten voksede dramatisk under krigen."}'::jsonb,
  'mc','short','{"concepts":["statsmagt","censur","tvangsindkaldelse","rationering","total krig"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_1',8,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Paa hvilken maade var nationalisme en dobbeltaegget klinge i perioden foer Forste Verdenskrig?","options":["Den styrkede indenrigsk sammenhold men skabte fjendskab og rivalisering mellem nationer der goerede kompromis svaerere","Nationalisme var rent positiv og bidrog ikke til krigen","Nationalisme var rent negativ og ingen saa noget godt i den","Nationalisme opstod som konsekvens af krigen ikke foer den"],"correct":"Den styrkede indenrigsk sammenhold men skabte fjendskab og rivalisering mellem nationer der goerede kompromis svaerere","accepted_answers":["Den styrkede indenrigsk sammenhold men skabte fjendskab og rivalisering mellem nationer der goerede kompromis svaerere"],"review_text":"Nationalisme sammensvejsede franskmæend, tysker og englndsmæend som aldrig foer. Det goerede dem villige til at kaempe. Men det betod ogsaa at man saa fjenden som grundlaeggende anderledes og mindrevaerdig. Det goerede fredelige loesninger svaerere."}'::jsonb,
  'mc','short','{"concepts":["nationalisme","sammenhold","fjendskab","dobbelttydig","kompromis"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_1',8,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betod Forste Verdenskrig for den europaeiske verdensorden der had eksisteret siden 1815?","options":["Den udraderede den gamle orden: fire kejserriger faldt, nye nationer opstod og USA og Sovjet begyndte at erstatte Europa som verdens center","Den bevarede den gamle orden men med Germany som ny dominerende magt","Den styrkede den gamle orden fordi England og Frankrig sejrede","Den europaeiske orden aendrede sig ikke foerend Anden Verdenskrig"],"correct":"Den udraderede den gamle orden: fire kejserriger faldt, nye nationer opstod og USA og Sovjet begyndte at erstatte Europa som verdens center","accepted_answers":["Den udraderede den gamle orden: fire kejserriger faldt, nye nationer opstod og USA og Sovjet begyndte at erstatte Europa som verdens center"],"review_text":"Den europaeiske orden fra 1815 rasede i suel. Kejserriger forsvandt. Graenser blev omtegnet. Wilson introducerede folkenes selvbestemmelsesprincip. Europa var ikke laengere alene om at bestemme verdens skaebne."}'::jsonb,
  'mc','short','{"concepts":["verdensorden","kejserriger","nye nationer","USA","Sovjet","Europa"],"misconception_type":"temporal_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_1',8,3
);

-- ─── GRADE 8 · BAND 4 (5 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Var Forste Verdenskrig uundgaaelig?","options":["Det debatteres stadig. Strukturelle spaendinger var enorme men konkrete politiske beslutninger i juli 1914 kunne have stoppet krigen","Ja krigen var fuldstaendig uundgaaelig givet de strukturelle betingelser","Nej krigen var et tilfaeldigt uheld som nemt kunne vaere undgaaet","Krigen var uundgaaelig fordi Germany planlagde den systematisk i aartier"],"correct":"Det debatteres stadig. Strukturelle spaendinger var enorme men konkrete politiske beslutninger i juli 1914 kunne have stoppet krigen","accepted_answers":["Det debatteres stadig. Strukturelle spaendinger var enorme men konkrete politiske beslutninger i juli 1914 kunne have stoppet krigen"],"review_text":"Strukturalisterne siger spaendingerne var saa store at noget maatte eksplodere. Andre peeger paa at lederne i de afgoorende julidage 1914 aktivt valgte eskalering frem for kompromis. Sandsynligvis bidrog begge: strukturerne skaabte betingelserne men mennesker traf beslutningerne."}'::jsonb,
  'mc','short','{"concepts":["uundgaaelighed","strukturer","beslutninger","julidagene","historisk debat"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_1',8,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Var Versailles-traktaten en retfaerdig fred eller en opskrift paa ny krig?","options":["Begge dele paa en gang: forstaaeelig fra sejrherrernes perspektiv men saa haard at den saaede froe til den naeste krig","Den var fuldt retfaerdig og ingen ansvarlig historiker kritiserer den","Den var katastrofalt uretfaerdig og ingen vidste bedre","Den var saa mild at det var grunden til at Hitler kom til magten"],"correct":"Begge dele paa en gang: forstaaeelig fra sejrherrernes perspektiv men saa haard at den saaede froe til den naeste krig","accepted_answers":["Begge dele paa en gang: forstaaeelig fra sejrherrernes perspektiv men saa haard at den saaede froe til den naeste krig"],"review_text":"Fra fransk perspektiv var haardhed forstaaeelig: Frankrig var haerget. Men okonomisten Keynes forudsagde i 1919 at traktatens betingelser ville skabe en ny krig inden 20 aar. Han fik desvaerre ret i 1939."}'::jsonb,
  'mc','short','{"concepts":["Versailles","retfaerdig fred","Keynes","perspektiver","konsekvenser"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_1',8,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad viser brugen af propaganda i England, Frankrig og USA om forholdet mellem demokrati og statsstyret manipulation?","options":["At demokratier er villige til at manipulere borgerne i eksistentielle kriser og at medierne aktivt samarbejdede med staten","At demokratier aldrig bruger propaganda det goer kun diktaturer","At demokratiernes propaganda var fuldt etisk og aaben modsat diktaturers","At borgerne gennemskuede al propaganda og den var ineffektiv"],"correct":"At demokratier er villige til at manipulere borgerne i eksistentielle kriser og at medierne aktivt samarbejdede med staten","accepted_answers":["At demokratier er villige til at manipulere borgerne i eksistentielle kriser og at medierne aktivt samarbejdede med staten"],"review_text":"England oprettede et dedikeret Propagandaministerium. USA brugte Committee on Public Information. Aviser og film formidlede krigens noedvendighed. Borgerne i disse demokratier var udsat for statsstyret informationskrig der var meget effektiv."}'::jsonb,
  'mc','short','{"concepts":["propaganda","demokrati","statsstyret","manipulation","misconception-propaganda-kun-diktaturer"],"misconception_type":"scope_confusion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_1',8,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad fortaeller kloeften mellem krigstidens propaganda og soldaternes egne dagboeger om information og magt?","options":["At dem der styrer informationen kan forme virkelighed for store befolkningsgrupper og at censur aktivt holdt sandheden fra offentligheden","At soldaterne faktisk var enige med propagandaen","At propaganda aldrig virker fordi folk gennemskuer det","At informationskontrol kun var mulig foer aviser eksisterede"],"correct":"At dem der styrer informationen kan forme virkelighed for store befolkningsgrupper og at censur aktivt holdt sandheden fra offentligheden","accepted_answers":["At dem der styrer informationen kan forme virkelighed for store befolkningsgrupper og at censur aktivt holdt sandheden fra offentligheden"],"review_text":"Mens propaganda fremstillede heroisk krig levede soldaterne i mudder og gas. Breve hjem var censurerede. Det er et tidligt og magtfuldt eksempel paa at kontrol over information er kontrol over virkelighed."}'::jsonb,
  'mc','short','{"concepts":["informationskontrol","censur","magt","virkelighed","dagboeger"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_1',8,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er Forste Verdenskrigs vigtigste arv til verden i dag?","options":["At verdenskrig er mulig og at nationalisme, rivalisering og svage internationale institutioner kan bringe civilisationer til ruinens rand","At teknologisk overlegenhed altid afgoer en krig","At demokratier aldrig goer krig mod hinanden","At Europas dominans over verden er permanent og urokkeaelig"],"correct":"At verdenskrig er mulig og at nationalisme, rivalisering og svage internationale institutioner kan bringe civilisationer til ruinens rand","accepted_answers":["At verdenskrig er mulig og at nationalisme, rivalisering og svage internationale institutioner kan bringe civilisationer til ruinens rand"],"review_text":"Forste Verdenskrig dræabte 20 millioner. Den udraderede fire imperier. Den saaede froe til den naeste krig. Dens lektie var smertefuld: den internationale orden er skroebelig og krig er aldrig det korte sejrstogt man lover. Det var baggrunden for FN og det europaeiske integrationsprojekt."}'::jsonb,
  'mc','short','{"concepts":["arv","FN","europaeisk integration","lektie","international orden"],"misconception_type":"temporal_confusion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_1',8,4
);
