INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad viser det at stenalderbønder byggede store stengrave der krævede hundredvis af menneskers fælles arbejde?","options":["At de troede på et liv efter døden og at de var i stand til at organisere store fællesskaber der kunne samarbejde om et langsigtet projekt","At stenalderbønder ikke havde andet at lave og valgte at bruge al deres fritid på at flytte tunge sten rundt","At kun de aller rigeste bønder nogensinde bidrog til byggeriet og resten af befolkningen ikke måtte deltage","At de byggede gravene af frygt for at de afdøde ville vende tilbage og hjemsøge landsbyen hvis de ikke fik en stor grav"],"correct":"At de troede på et liv efter døden og at de var i stand til at organisere store fællesskaber der kunne samarbejde om et langsigtet projekt","accepted_answers":["At de troede på et liv efter døden og at de var i stand til at organisere store fællesskaber der kunne samarbejde om et langsigtet projekt"],"review_text":"Stengrave som dysser og jættestuer fra Stenalderen (ca. 3.500 f.Kr.) vejer mange tons og krævede hundredvis af mennesker at flytte og rejse. Det viser to vigtige ting: stenalderbønder levede i organiserede fællesskaber der kunne planlægge og gennemføre store projekter over lang tid — og de troede på et efterliv og ærede deres afdøde forfædre. Gravene bruges som fællesgrave for mange mennesker over generationer. Danmark har over 7.000 fredede gravhøje og stengrave. De er ikke bygget af slaver eller tvang — de var et udtryk for fællesskabets tro og sammenhold."}$$::jsonb,
  'mc','short',$${"concepts":["megalitgrave","stengrave","fællesskab","efterliv","organisering"],"misconception_type":"false_equivalence","cognitive_skill":"application","difficulty_type":"inferential","insight_type":"concept_clarification","challenge_role":"reasoning_challenge","domain":"prehistoric_denmark"}$$::jsonb,
  'mc_single',3,'auto',true,'prehistoric_denmark',3,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Tollandmanden der levede for ca. 2.400 år siden havde et reb om halsen og var lagt forsigtigt ned i en jysk mose. Hvad kan vi sandsynligvis slutte?","options":["At hans død sandsynligvis ikke var et uheld — rebet og den omhyggelige placering i mosen tyder på at døden var tilsigtet og måske forbundet med en religiøs handling","At han faldt ved et uheld ud i mosen mens han hentede vand og rebet sad tilfældigvis fast om halsen","At alle mennesker der dør nær en mose automatisk synker ned og bevares og rebet er et tilfældigt fund","At rebet beviser at han var en slave der blev straffet af sin herre og smidt i mosen som straf"],"correct":"At hans død sandsynligvis ikke var et uheld — rebet og den omhyggelige placering i mosen tyder på at døden var tilsigtet og måske forbundet med en religiøs handling","accepted_answers":["At hans død sandsynligvis ikke var et uheld — rebet og den omhyggelige placering i mosen tyder på at døden var tilsigtet og måske forbundet med en religiøs handling"],"review_text":"Tollandmanden er verdens bedst bevarede jernaldermenneske fundet i Bjældskovdal ved Silkeborg i 1950. Mosetørv konserverer organisk materiale — hud, hår og indre organer bevarede i ca. 2.400 år. Han havde et flettet læderreb tæt om halsen og var lagt forsigtigt ned i tørven med lukkede øjne. Hans ansigt ser fredfyldt ud. Historikere mener at han sandsynligvis enten blev ofret til guderne eller henrettet — men vi kan ikke vide det med sikkerhed. Det er et godt eksempel på at vi kan lære meget af forhistoriske fund men ikke altid kan forklare dem fuldt ud fordi vi mangler skriftlige kilder."}$$::jsonb,
  'mc','short',$${"concepts":["Tollandmanden","moseleg","jernalderen","ritualoffer","kildekritik"],"misconception_type":"causal_inversion","cognitive_skill":"application","difficulty_type":"inferential","insight_type":"perspective_shift","challenge_role":"reasoning_challenge","domain":"prehistoric_denmark"}$$::jsonb,
  'mc_single',3,'auto',true,'prehistoric_denmark',3,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvorfor var bronzealderens bønder i Danmark nødt til at handle med folk langt væk for at skaffe bronze?","options":["Fordi bronze fremstilles af kobber og tin der ikke fandtes naturligt i Danmark — begge metaller måtte importeres fra Centraleuropa og England mod eksport af rav og andre danske varer","Fordi danskerne ikke kendte til bronzestøbning og måtte købe færdige bronseredskaber direkte fra sydeuropæiske specialister","Fordi bronze udelukkende bestod af jern og sand der heller ikke fandtes tilstrækkeligt i Danmark","Fordi rav kun kunne bruges til at betale for bronze og slet ikke til andre varer eller formål"],"correct":"Fordi bronze fremstilles af kobber og tin der ikke fandtes naturligt i Danmark — begge metaller måtte importeres fra Centraleuropa og England mod eksport af rav og andre danske varer","accepted_answers":["Fordi bronze fremstilles af kobber og tin der ikke fandtes naturligt i Danmark — begge metaller måtte importeres fra Centraleuropa og England mod eksport af rav og andre danske varer"],"review_text":"Bronze er en legering af kobber og tin. I Bronzealderen (1700-500 f.Kr.) fandtes ingen af disse metaller naturligt i Danmark. Kobber kom fra Alperne og den Iberiske Halvø, tin fra Cornwall i England og Centraleuropa. Danmarks vigtigste eksportvare var rav — forstenet harpiks fra Jyllands vestkyst og Østersøen der var meget efterspurgt i hele Europa til smykker og religiøse genstande. Fund af jysk rav i grave i Mykene i Grækenland og i Egypten bekræfter at ravvejen strakte sig tusindvis af kilometer sydpå. Bronzealderens danskere var altså en del af et stort europæisk handelsnetværk."}$$::jsonb,
  'mc','short',$${"concepts":["bronze","kobber","tin","ravhandel","handelsnetværk","Bronzealder"],"misconception_type":"factual_error","cognitive_skill":"application","difficulty_type":"causal","insight_type":"concept_clarification","challenge_role":"reasoning_challenge","domain":"prehistoric_denmark"}$$::jsonb,
  'mc_single',3,'auto',true,'prehistoric_denmark',4,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Solvognen fra Trundholm er en bronzefigur af en hest der trækker en vogn med en forgyldt solskive. Hvad kan vi lære af dette fund?","options":["At solen var et vigtigt religiøst symbol for bronzealderens folk og at de beherskede avanceret bronzehåndværk og guldarbejde til at udtrykke religiøse forestillinger","At bronzealderens folk brugte solvogne som legetøj til børn og ikke tillagde dem nogen religiøs eller symbolsk betydning","At Solvognen var et nøjagtigt astronomisk instrument der viste præcis hvilken dag på året det var ud fra solens position","At heste i bronzealderen udelukkende blev brugt til at trække vogne og aldrig til ridning arbejde eller handel"],"correct":"At solen var et vigtigt religiøst symbol for bronzealderens folk og at de beherskede avanceret bronzehåndværk og guldarbejde til at udtrykke religiøse forestillinger","accepted_answers":["At solen var et vigtigt religiøst symbol for bronzealderens folk og at de beherskede avanceret bronzehåndværk og guldarbejde til at udtrykke religiøse forestillinger"],"review_text":"Solvognen fra Trundholm (ca. 1400 f.Kr.) er et af Nordeuropas mest berømte bronzealder-fund. Den er støbt af bronze og delvist forgyldt og forestiller en hest der trækker en vogn med en solskive — den ene side er forgyldt (dag) og den anden mørkere (nat). Sol-symbolik optræder mange steder i nordisk bronzealder: på rageknive, dolke og gravsteler. Det fortæller os at solen spillede en central rolle i bronzealderfolkets religion og verdensopfattelse. Solvognen er i dag udstillet på Nationalmuseet i København og er et af de mest genkendelige symboler på dansk forhistorie."}$$::jsonb,
  'mc','short',$${"concepts":["Solvognen","Trundholm","solreligion","bronzehåndværk","bronzealder","symbolik"],"misconception_type":"scope_confusion","cognitive_skill":"application","difficulty_type":"inferential","insight_type":"concept_clarification","challenge_role":"reasoning_challenge","domain":"prehistoric_denmark"}$$::jsonb,
  'mc_single',3,'auto',true,'prehistoric_denmark',4,3
);;
