INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvorfor begyndte nogle mennesker i forhistorien at have mere end andre?","options":["Da folk begyndte at dyrke marker, kunne nogle gemme mere mad og bytte det mod andre ting — dem der var dygtige til landbrug eller handel fik efterhånden mere end dem der ikke var det","Folk besluttede at det var fair at dele alt ligeligt og alle forhistoriske danskere havde præcis det samme","Guder valgte hvem der måtte have meget og hvem der måtte have lidt og folk accepterede det uden at stille spørgsmål","Kun vikingerne kendte til at have rige og fattige folk — i Stenalderen var alle helt ens"],"correct":"Da folk begyndte at dyrke marker, kunne nogle gemme mere mad og bytte det mod andre ting — dem der var dygtige til landbrug eller handel fik efterhånden mere end dem der ikke var det","accepted_answers":["Da folk begyndte at dyrke marker, kunne nogle gemme mere mad og bytte det mod andre ting — dem der var dygtige til landbrug eller handel fik efterhånden mere end dem der ikke var det"],"review_text":"Da folk var jæger-samlere, var der ikke meget at gemme. Men da landbruget kom, kunne man opbevare korn og have egne dyr. Dem der var bedst til at dyrke jord eller lave gode redskaber fik efterhånden mere end andre. Det var begyndelsen på at samfund får rige og fattige — ikke fordi nogen planlagde det, men fordi det skete naturligt."}$$::jsonb,
  'mc','short',$${"concepts":["ulighed","landbrug","oplagring","handel","social differentiering"],"misconception_type":"false_equivalence","cognitive_skill":"application","difficulty_type":"causal","insight_type":"concept_clarification","challenge_role":"reasoning_challenge","domain":"prehistoric_denmark"}$$::jsonb,
  'mc_single',4,'auto',true,'prehistoric_denmark',3,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Bronzealdernes folk lavede smukt udformede musikinstrumenter kaldet bronzelurer. Hvad viser det?","options":["At de ikke brugte al deres tid på at overleve — de havde overskud til at lave noget smukt og nyde musik, ligesom vi gør i dag","At bronzealderens folk ikke arbejdede hårdt og mest legede og lavede musik hele dagen","At musikken kun var for lederne og almindelige folk ikke måtte lytte til bronzelurerne","At bronzelurerne var redskaber til at skræmme dyr væk og ikke rigtige musikinstrumenter"],"correct":"At de ikke brugte al deres tid på at overleve — de havde overskud til at lave noget smukt og nyde musik, ligesom vi gør i dag","accepted_answers":["At de ikke brugte al deres tid på at overleve — de havde overskud til at lave noget smukt og nyde musik, ligesom vi gør i dag"],"review_text":"En bronzelur er smukt støbt og lyder godt. Det kræver tid og dygtighed at lave den — og det kræver at man har mad nok til ikke kun at tænke på at overleve. Bronzealderens folk havde overskud til kunst og musik. Det viser at de ikke var så meget anderledes end os."}$$::jsonb,
  'mc','short',$${"concepts":["bronzelur","overskud","kultur","musik","bronzealder"],"misconception_type":"scope_confusion","cognitive_skill":"application","difficulty_type":"inferential","insight_type":"perspective_shift","challenge_role":"reasoning_challenge","domain":"prehistoric_denmark"}$$::jsonb,
  'mc_single',4,'auto',true,'prehistoric_denmark',3,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Vi finder mange grave fra Stenalderen men næsten ingen huse. Hvad er den bedste forklaring?","options":["Husene var lavet af træ som rådner væk efter tusinder af år mens gravene var lavet af tunge sten der holder meget længere","Folk i Stenalderen boede ikke i huse men levede udelukkende under åben himmel hele året rundt","Arkæologer er ikke interesserede i at finde huse og leder kun efter grave og smykker","Husene var bygget dybt under jorden og er endnu ikke fundet af nogen arkæologer"],"correct":"Husene var lavet af træ som rådner væk efter tusinder af år mens gravene var lavet af tunge sten der holder meget længere","accepted_answers":["Husene var lavet af træ som rådner væk efter tusinder af år mens gravene var lavet af tunge sten der holder meget længere"],"review_text":"Træ rådner. Sten holder. Et stenalderhus af træ og strå er borte efter 100-200 år i dansk jord. En jættestue af store sten holder i 6.000 år. Det er ikke fordi husene ikke var der — de var der. Vi finder dem bare ikke fordi materialerne er væk."}$$::jsonb,
  'mc','short',$${"concepts":["bevaringsbias","materialer","grave","huse","arkæologi"],"misconception_type":"causal_inversion","cognitive_skill":"application","difficulty_type":"inferential","insight_type":"concept_clarification","challenge_role":"reasoning_challenge","domain":"prehistoric_denmark"}$$::jsonb,
  'mc_single',4,'auto',true,'prehistoric_denmark',3,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvorfor var det så vigtigt at de første folk i Danmark hjalp hinanden?","options":["Fordi ingen kan klare alt alene — at jage store dyr, bygge store grave og overleve vinteren krævede at mange mennesker arbejdede sammen om de samme mål","Fordi kongen bestemte at alle skulle hjælpe hinanden under trussel om hård straf","Fordi folk i forhistorien var venligere end mennesker i dag og altid hjalp hinanden frivilligt","Fordi der ikke var nok mad til at nogen kunne klare sig alene og alle måtte dele alt de havde med alle andre"],"correct":"Fordi ingen kan klare alt alene — at jage store dyr, bygge store grave og overleve vinteren krævede at mange mennesker arbejdede sammen om de samme mål","accepted_answers":["Fordi ingen kan klare alt alene — at jage store dyr, bygge store grave og overleve vinteren krævede at mange mennesker arbejdede sammen om de samme mål"],"review_text":"En gruppe på tyve jægere der arbejder sammen kan nedlægge et stort dyr. Alene er det umuligt. De store grave i Stenalderen krævede hundredvis af hænder. At overleve en hård vinter kræver at man hjælper naboen og naboen hjælper dig. Fællesskab er et af menneskets vigtigste redskaber — og det har altid været det."}$$::jsonb,
  'mc','short',$${"concepts":["samarbejde","fællesskab","jagt","overlevelse","forhistorisk samfund"],"misconception_type":"false_equivalence","cognitive_skill":"application","difficulty_type":"causal","insight_type":"concept_clarification","challenge_role":"reasoning_challenge","domain":"prehistoric_denmark"}$$::jsonb,
  'mc_single',4,'auto',true,'prehistoric_denmark',3,4
);;
