-- Section 79 — Industrialisation Content Sprint
-- 50 questions: Grade 7 (25) + Grade 8 (25)
-- Bands: B1×12, B2×14, B3×14, B4×10
-- Concepts: factories, steam, urbanisation, working conditions, child labour,
--           housing, social classes, trade unions, democracy, tech change, Danish ind.
-- Misconceptions targeted throughout. 100% review_text. is_active=true.

-- ─── GRADE 7 · BAND 1 (6 questions) ─────────────────────────────────────────

-- ind_g7b1_01 — Factory definition
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er en fabrik?","options":["Et sted hvor mange arbejdere bruger maskiner til at producere varer i store mængder","En butik der sælger håndlavede varer direkte til kunden","Et landbrug med mange ansatte til at høste og forarbejde korn","Et marked hvor råvarer byttes mod færdigvarer"],"correct":"Et sted hvor mange arbejdere bruger maskiner til at producere varer i store mængder","accepted_answers":["Et sted hvor mange arbejdere bruger maskiner til at producere varer i store mængder"],"review_text":"En fabrik samler mange arbejdere ét sted med maskiner til at producere varer hurtigt og billigt. Det var en ny måde at arbejde på — meget anderledes end det gamle håndværk, hvor én mand lavede én ting fra start til slut."}'::jsonb,
  'mc','short','{"concepts":["fabrik","masseproduktion","industrialisering"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"industrialisation"}'::jsonb,
  'mc_single',1,'auto',true,'industrialisation',7,1
);

-- ind_g7b1_02 — Steam power
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var dampmaskinen god til i industrialiseringen?","options":["Den drev maskiner og erstattede heste og menneskekraft med mekanisk kraft","Den producerede mad til fabriksarbejderne","Den pumpede vand ind i byerne som drikkevand","Den holder temperaturen stabil i fabrikslokalerne"],"correct":"Den drev maskiner og erstattede heste og menneskekraft med mekanisk kraft","accepted_answers":["Den drev maskiner og erstattede heste og menneskekraft med mekanisk kraft"],"review_text":"Dampmaskinen brændte kul og omdannede varmen til bevægelse. Den kunne drive maskiner i fabrikker og jernbaner. Det betød at man ikke længere var afhængig af vind, vand eller heste. Produktionen eksploderede."}'::jsonb,
  'mc','short','{"concepts":["dampmaskine","mekanisk kraft","teknologi"],"misconception_type":"scope_confusion","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"industrialisation"}'::jsonb,
  'mc_single',1,'auto',true,'industrialisation',7,1
);

-- ind_g7b1_03 — Child labour
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad brugte fabriksejere børn til under industrialiseringen?","options":["Børn arbejdede i miner og fabrikker fordi de var billigere end voksne og kunne krybe ind i smalle tunneler","Børn passede maskiner om natten mens voksne sov","Børn solgte fabriksvarerne på markedet","Børn underviste andre børn i fabriksskolerne"],"correct":"Børn arbejdede i miner og fabrikker fordi de var billigere end voksne og kunne krybe ind i smalle tunneler","accepted_answers":["Børn arbejdede i miner og fabrikker fordi de var billigere end voksne og kunne krybe ind i smalle tunneler"],"review_text":"Børnearbejde var udbredt og ikke sjældent. I kulminerne trak børn kulvogne i smalle tunneler. I tekstilfabrikker var de hurtige fingre der knyttede løse tråde. Lønnen var lav — og det var præcis grunden til at fabriksejerne foretrak dem."}'::jsonb,
  'mc','short','{"concepts":["børnearbejde","miner","fabrikker","misconception-boernearbejde-sjaeldent"],"misconception_type":"overgeneralization","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"industrialisation"}'::jsonb,
  'mc_single',1,'auto',true,'industrialisation',7,1
);

-- ind_g7b1_04 — Urbanisation
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad skete med befolkningerne under industrialiseringen?","options":["Millioner af mennesker flyttede fra landet til byerne for at finde arbejde i fabrikkerne","Folk flyttede fra byerne til landet fordi maskiner krævede plads","Befolkningerne forblev stort set på de samme steder som før","Folk emigrerede primært til andre lande fremfor at flytte til industribyer"],"correct":"Millioner af mennesker flyttede fra landet til byerne for at finde arbejde i fabrikkerne","accepted_answers":["Millioner af mennesker flyttede fra landet til byerne for at finde arbejde i fabrikkerne"],"review_text":"Industrialiseringen skabte en massiv vandring fra land til by. Maskiner overtog mange landbrugsopgaver, og nye fabrikker tilbød lønarbejde i byerne. Byer voksede eksplosivt — London gik fra 1 million til 6 millioner på 100 år."}'::jsonb,
  'mc','short','{"concepts":["urbanisering","migration","befolkning","fabriksarbejde"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"industrialisation"}'::jsonb,
  'mc_single',1,'auto',true,'industrialisation',7,1
);

-- ind_g7b1_05 — Working conditions
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad karakteriserede arbejdsforholdene i de tidligste fabrikker?","options":["12-16 timers arbejdsdage, farlige maskiner og ingen lovbeskyttelse mod ulykker","8-timers arbejdsdag og statsstøttet sikkerhedsudstyr","Korte arbejdsdage med mange pauser og høje lønninger","Fleksibelt arbejde hvor den ansatte bestemte sin egen arbejdstid"],"correct":"12-16 timers arbejdsdage, farlige maskiner og ingen lovbeskyttelse mod ulykker","accepted_answers":["12-16 timers arbejdsdage, farlige maskiner og ingen lovbeskyttelse mod ulykker"],"review_text":"De første fabrikker havde ingen arbejdsmiljøregler. 12-16 timers arbejdsdage var normalt. Maskiner uden sikkerhedsafskærmning tog fingre og hænder. En ulykke betød ofte tab af arbejde og indkomst — ingen erstatning, ingen sygedagpenge."}'::jsonb,
  'mc','short','{"concepts":["arbejdsforhold","arbejdsdag","fabriksulykker","arbejdsmiljø"],"misconception_type":"anachronism","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"industrialisation"}'::jsonb,
  'mc_single',1,'auto',true,'industrialisation',7,1
);

-- ind_g7b1_06 — Social classes
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvem var fabriksejerne i den tidlige industrialisering?","options":["En ny klasse af rige kapitalister — borgerskabet — der tjente penge på andres arbejde","Konger og adel der ejede alt land og industri","Faglærte håndværkere der efterhånden åbnede egne fabrikker","Kirkens repræsentanter der styrede produktionen"],"correct":"En ny klasse af rige kapitalister — borgerskabet — der tjente penge på andres arbejde","accepted_answers":["En ny klasse af rige kapitalister — borgerskabet — der tjente penge på andres arbejde"],"review_text":"Industrialiseringen skabte et nyt borgerskab — fabrikanterne. De ejede maskinerne og fabrikkerne og tjente penge på at leje andres arbejdskraft ud. Det var en ny type rigdom: ikke jord som adelens, men kapital og produktionsmidler."}'::jsonb,
  'mc','short','{"concepts":["borgerskab","kapitalister","sociale klasser","fabriksejere"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"industrialisation"}'::jsonb,
  'mc_single',1,'auto',true,'industrialisation',7,1
);

-- ─── GRADE 7 · BAND 2 (7 questions) ─────────────────────────────────────────

-- ind_g7b2_01 — Why factories emerged
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvorfor opstod fabrikkerne som ny produktionsform?","options":["Dampmaskiner og store maskiner krævede en central strømkilde — det var praktisk at samle alle arbejdere ét sted","Fabriksejerne ville overvåge arbejderne bedre og kontrollere produktionshastigheden","Staten beordrede at al produktion skulle ske i kontrollerede miljøer","Håndværkerne selv ønskede at arbejde sammen i store grupper"],"correct":"Dampmaskiner og store maskiner krævede en central strømkilde — det var praktisk at samle alle arbejdere ét sted","accepted_answers":["Dampmaskiner og store maskiner krævede en central strømkilde — det var praktisk at samle alle arbejdere ét sted"],"review_text":"Tidlige maskiner var store og krævede dampen fra ét centralt anlæg. Det gav ikke mening at sprede dem. Så fabrikken opstod: ét sted, mange arbejdere, ét maskineri. Kontrollen fulgte naturligt med — men var ikke den egentlige årsag."}'::jsonb,
  'mc','short','{"concepts":["fabrik","dampmaskine","centralisering","årsag"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"industrialisation"}'::jsonb,
  'mc_single',2,'auto',true,'industrialisation',7,2
);

-- ind_g7b2_02 — Why urbanisation
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvorfor flygtede bønder fra landet til byerne under industrialiseringen?","options":["Maskiner overtog landbrugsarbejdet og færre hænder var behøvet — fabrikkerne i byerne tilbød lønarbejde","Byerne tilbød bedre uddannelse og et sundere miljø end landet","Staten forbød folk at blive på landet uden eget jord","Klimaet i byerne var varmere og mere behageligt end på landet"],"correct":"Maskiner overtog landbrugsarbejdet og færre hænder var behøvet — fabrikkerne i byerne tilbød lønarbejde","accepted_answers":["Maskiner overtog landbrugsarbejdet og færre hænder var behøvet — fabrikkerne i byerne tilbød lønarbejde"],"review_text":"Mekaniseringen af landbruget betød at bønder mistede arbejde på landet. Fabrikkerne i byerne tilbød lønarbejde — selv om lønningerne var lave. Folk havde ikke mange valg. Urbaniseringen var for mange en nødvendighed, ikke et frit valg."}'::jsonb,
  'mc','short','{"concepts":["urbanisering","landbrug","mekanisering","fattigdom"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"industrialisation"}'::jsonb,
  'mc_single',2,'auto',true,'industrialisation',7,2
);

-- ind_g7b2_03 — Trade unions purpose
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var fagforeningers formål?","options":["At organisere arbejdere kollektivt så de stod stærkere i forhandlinger med arbejdsgiverne","At sikre at fabrikanterne fulgte statens produktionskvoter","At kontrollere priserne på fabriksvarerne i butikkerne","At uddanne nye arbejdere i maskinernes brug"],"correct":"At organisere arbejdere kollektivt så de stod stærkere i forhandlinger med arbejdsgiverne","accepted_answers":["At organisere arbejdere kollektivt så de stod stærkere i forhandlinger med arbejdsgiverne"],"review_text":"En enkelt arbejder der bad om bedre løn kunne afskediges øjeblikkeligt. Men hvis alle arbejdere strejkede sammen, mistede fabrikanten produktion og penge. Fagforeningen gav kollektiv styrke — det er ideen bag organisering."}'::jsonb,
  'mc','short','{"concepts":["fagforening","kollektiv forhandling","arbejdere","organisering"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"industrialisation"}'::jsonb,
  'mc_single',2,'auto',true,'industrialisation',7,2
);

-- ind_g7b2_04 — Housing conditions
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad karakteriserede boligforholdene for fabriksarbejdere i industribyen?","options":["Tæt sammenpakkede slumkvarterer med mange familier i ét rum og ringe adgang til rent vand","Nye og rummelige boliger bygget af fabrikanterne til deres arbejdere","Arbejderne boede stadig på landet og pendlede til fabrikken","Staten byggede ordentlige boliger til alle industriarbejdere"],"correct":"Tæt sammenpakkede slumkvarterer med mange familier i ét rum og ringe adgang til rent vand","accepted_answers":["Tæt sammenpakkede slumkvarterer med mange familier i ét rum og ringe adgang til rent vand"],"review_text":"Byerne voksede hurtigere end infrastrukturen. Arbejderfamilier levede ofte 8-10 personer i ét rum. Der var ingen kloakker — afføring havnede i gårde og vandforsyningen. Epidemier rasede. Bylivet var ingenlunde et paradis."}'::jsonb,
  'mc','short','{"concepts":["boliger","slum","urbanisering","boligforhold","misconception-byer-forbedrer"],"misconception_type":"overgeneralization","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"industrialisation"}'::jsonb,
  'mc_single',2,'auto',true,'industrialisation',7,2
);

-- ind_g7b2_05 — Child labour cause
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvorfor sendte forældre børn ud at arbejde i fabrikkerne?","options":["Familier var så fattige at alle måtte bidrage til indkomsten — børn fik lavere løn end voksne og var derfor attraktive for fabrikanter","Det var en kulturel tradition at børn lærte et håndværk tidligt","Børnene bad selv om at arbejde fordi de kedede sig derhjemme","Staten beordrede at alle børn over 6 år skulle have erhvervserfaring"],"correct":"Familier var så fattige at alle måtte bidrage til indkomsten — børn fik lavere løn end voksne og var derfor attraktive for fabrikanter","accepted_answers":["Familier var så fattige at alle måtte bidrage til indkomsten — børn fik lavere løn end voksne og var derfor attraktive for fabrikanter"],"review_text":"En fabriksarbejders løn var ofte ikke nok til at brødføde en familie. Børns løn — om end lavere — hjalp familien overleve. Fabriksejerne foretrak børn: billig arbejdskraft og nem at disciplinere. Fattigdommens struktur tvang familierne ind i det."}'::jsonb,
  'mc','short','{"concepts":["børnearbejde","fattigdom","arbejdsmarked","familieøkonomi"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"industrialisation"}'::jsonb,
  'mc_single',2,'auto',true,'industrialisation',7,2
);

-- ind_g7b2_06 — Technology and inequality
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad skete med den sociale ulighed under industrialiseringen?","options":["Fabriksejerne blev rige mens mange arbejdere forblev fattige trods enorm produktionsvækst","Rigdommen blev mere jævnt fordelt fordi maskiner producerede mere til alle","Alle samfundsgrupper tjente mere og uligheden faldt markant","Kun adelen tjente på industrialiseringen mens borgerskabet forblev middelmådigt"],"correct":"Fabriksejerne blev rige mens mange arbejdere forblev fattige trods enorm produktionsvækst","accepted_answers":["Fabriksejerne blev rige mens mange arbejdere forblev fattige trods enorm produktionsvækst"],"review_text":"Industrialiseringen skabte enorm rigdom — men fordelte den skævt. Ejerne af maskinerne tog overskuddet. Arbejderne fik løn nok til at overleve, sjældent mere. Ulighed steg markant i de første 100 år af industrialiseringen."}'::jsonb,
  'mc','short','{"concepts":["ulighed","kapitalister","arbejdere","rigdom","misconception-teknologi-gavner-alle"],"misconception_type":"overgeneralization","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"industrialisation"}'::jsonb,
  'mc_single',2,'auto',true,'industrialisation',7,2
);

-- ind_g7b2_07 — Steam power impact
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betød dampmaskinen for produktionsmængden?","options":["Produktionen steg dramatisk — man producerede nu på timer hvad der tidligere tog uger","Produktionen steg lidt men kvaliteten faldt markant","Produktionen forblev den samme men omkostningerne faldt","Dampmaskinen var mest nyttig til transport, ikke til selve produktionen"],"correct":"Produktionen steg dramatisk — man producerede nu på timer hvad der tidligere tog uger","accepted_answers":["Produktionen steg dramatisk — man producerede nu på timer hvad der tidligere tog uger"],"review_text":"En dampdrevet tekstilmaskine kunne producere mere garn på én dag end en håndspinder på en måned. Priserne faldt. Varer der kun rigmænd havde råd til, blev tilgængelige for flere. Men gevinsterne gik primært til ejerne — ikke arbejderne."}'::jsonb,
  'mc','short','{"concepts":["dampmaskine","produktionsvækst","teknologi","effekt"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"industrialisation"}'::jsonb,
  'mc_single',2,'auto',true,'industrialisation',7,2
);

-- ─── GRADE 7 · BAND 3 (7 questions) ─────────────────────────────────────────

-- ind_g7b3_01 — Misconception: not only factories
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved påstanden at industrialisering kun påvirkede fabriksarbejdere?","options":["Industrialiseringen ændrede landbrug, transport, familiestrukturer, boligforhold og politiske systemer — den omformede hele samfundet","Påstanden er korrekt — kun de der arbejdede i fabrikker mærkede forandringen","Kun mænd var påvirkede — kvinder og børn forblev i de traditionelle roller","Kun rige lande som England og Frankrig mærkede industrialiseringens effekter"],"correct":"Industrialiseringen ændrede landbrug, transport, familiestrukturer, boligforhold og politiske systemer — den omformede hele samfundet","accepted_answers":["Industrialiseringen ændrede landbrug, transport, familiestrukturer, boligforhold og politiske systemer — den omformede hele samfundet"],"review_text":"Jernbanen forandrede transporten. Maskiner ændrede landbruget. Urbanisering transformerede familiernes hverdag. Nye klasser opstod. Politiske bevægelser kæmpede for stemmeret. Industrialisering var ikke blot en fabrikshistorie — det var hele samfundets transformation."}'::jsonb,
  'mc','short','{"concepts":["samfundstransformation","misconception-kun-fabrikker","landbrug","transport","familie"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"industrialisation"}'::jsonb,
  'mc_single',3,'auto',true,'industrialisation',7,3
);

-- ind_g7b3_02 — Factory vs craft work
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var den vigtigste forskel på at arbejde som håndværker og som fabriksarbejder?","options":["Håndværkeren ejede sine egne redskaber og bestemte eget tempo; fabriksarbejderen var bundet til maskinens rytme og ejede intet","Der var ingen reel forskel — begge lavede de samme produkter på samme tid","Fabriksarbejderen tjente mere og havde bedre arbejdsforhold end håndværkeren","Håndværkeren arbejdede for staten; fabriksarbejderen for private ejere"],"correct":"Håndværkeren ejede sine egne redskaber og bestemte eget tempo; fabriksarbejderen var bundet til maskinens rytme og ejede intet","accepted_answers":["Håndværkeren ejede sine egne redskaber og bestemte eget tempo; fabriksarbejderen var bundet til maskinens rytme og ejede intet"],"review_text":"Håndværkeren kontrollerede sit arbejde: egne redskaber, eget tempo, stolthed over et færdigt produkt. Fabriksarbejderen udførte én gentagen handling i takt med maskinen, ejede intet, og var let at erstatte. Det var tabet af autonomi — ikke kun lavere løn — der frustrerede mange."}'::jsonb,
  'mc','short','{"concepts":["håndværk","fabriksarbejde","autonomi","proletarisering"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"industrialisation"}'::jsonb,
  'mc_single',3,'auto',true,'industrialisation',7,3
);

-- ind_g7b3_03 — Working conditions and safety
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad viser de mange arbejdsulykker i tidlige fabrikker om samfundets prioriteter?","options":["At sikkerhed var en udgift ingen tvang fabriksejerne til at betale — profitmotivet gik forud for arbejdernes liv","At maskinerne var dårligt konstruerede og ingeniørerne uduelige","At arbejderne var uforsigtige og ikke fulgte sikkerhedsreglerne","At staten aktivt forhindrede fabriksejerne i at investere i sikkerhed"],"correct":"At sikkerhed var en udgift ingen tvang fabriksejerne til at betale — profitmotivet gik forud for arbejdernes liv","accepted_answers":["At sikkerhed var en udgift ingen tvang fabriksejerne til at betale — profitmotivet gik forud for arbejdernes liv"],"review_text":"Der fandtes ingen arbejdsmiljølov, ingen sikkerhedsinspektioner og ingen erstatningspligt. En fabrikant der investerede i sikkerhedsafskærmning havde højere udgifter end konkurrenten der ikke gjorde det. Markedet straffede ikke usikkerhed — det tilskyndede til det."}'::jsonb,
  'mc','short','{"concepts":["arbejdsulykker","fabriksikkerhed","profit","regulering"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"industrialisation"}'::jsonb,
  'mc_single',3,'auto',true,'industrialisation',7,3
);

-- ind_g7b3_04 — Trade unions and danger
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvorfor var det farligt at organisere sig i fagforening i 1800-tallets begyndelse?","options":["Strejker og fagforeninger var ulovlige i mange lande — man risikerede fængsel eller fyring","Fagforeninger var kun ulovlige i diktaturer, ikke i demokratier som England","Fabriksejerne betalte politikerne for at beskytte fagforeningerne","Der var ingen regler — fagforeninger var bare upopulære"],"correct":"Strejker og fagforeninger var ulovlige i mange lande — man risikerede fængsel eller fyring","accepted_answers":["Strejker og fagforeninger var ulovlige i mange lande — man risikerede fængsel eller fyring"],"review_text":"I England var fagforeninger forbudt under Combination Acts frem til 1824. Strejkede man risikerede man fængsel. Alligevel organiserede arbejdere sig hemmeligt. At kæmpe for bedre vilkår krævede mod — og kostede mange karrierer og frihed."}'::jsonb,
  'mc','short','{"concepts":["fagforening","lovgivning","strejke","mod"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"industrialisation"}'::jsonb,
  'mc_single',3,'auto',true,'industrialisation',7,3
);

-- ind_g7b3_05 — Urbanisation and health
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var konsekvensen af den hurtige urbanisering for folkesundheden?","options":["Kolera, tyfus og tuberkulose spredte sig hurtigt i overbefolkede byer uden rent vand og kloaker","Sundheden forbedrede sig fordi lægerne nu arbejdede i byerne","Epidemierne forsvandt fordi folk spiste bedre i byerne end på landet","Luften i industribyerne var ren fordi fabrikkerne lå uden for byen"],"correct":"Kolera, tyfus og tuberkulose spredte sig hurtigt i overbefolkede byer uden rent vand og kloaker","accepted_answers":["Kolera, tyfus og tuberkulose spredte sig hurtigt i overbefolkede byer uden rent vand og kloaker"],"review_text":"Byerne voksede hurtigere end kloakker og vandforsyning. Affaldet fra latrinerne sivede ned i grundvandet. Koleraepidemier hærgede London, Hamburg og København i 1800-tallet. En fabriksarbeider levede statistisk kortere end en bonde på landet."}'::jsonb,
  'mc','short','{"concepts":["folkesundhed","epidemier","kolera","kloakering","misconception-byer-forbedrer"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"industrialisation"}'::jsonb,
  'mc_single',3,'auto',true,'industrialisation',7,3
);

-- ind_g7b3_06 — Misconception: not equally poor
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved forestillingen om at alle fabriksarbejdere var lige fattige?","options":["Faglærte arbejdere tjente langt mere end ufaglærte — arbejderklassen var internt differentieret","Forestillingen er korrekt — alle fabriksarbejdere levede under identiske forhold","Kvinderne tjente mere end mænd i de fleste fabrikker","Fabriksarbejdere var generelt rigere end landbefolkningen"],"correct":"Faglærte arbejdere tjente langt mere end ufaglærte — arbejderklassen var internt differentieret","accepted_answers":["Faglærte arbejdere tjente langt mere end ufaglærte — arbejderklassen var internt differentieret"],"review_text":"Arbejderklassen var ikke én homogen masse. En faglært smed eller maskinmester tjente fire gange mere end en ufaglært daglejarbejder. Faglærte arbejdere dannede egne foreninger og havde en vis stolthed og stabilitet. Klasse er ikke ét lag — det er mange."}'::jsonb,
  'mc','short','{"concepts":["arbejderklasse","faglærte","ufaglærte","klassedifferentiering","misconception-alle-lige-fattige"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"industrialisation"}'::jsonb,
  'mc_single',3,'auto',true,'industrialisation',7,3
);

-- ind_g7b3_07 — Technology displacing workers
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvorfor forbedrede ny teknologi ikke altid livet for de arbejdere der allerede var ansat?","options":["Maskiner erstattede håndværkere og pressede lønningerne ned — mange mistede levebrødet da maskinerne overtog","Teknologien var altid for dyr til at erstatte erfarne arbejdere","Fabriksejerne valgte altid arbejderne frem for maskinerne af moralske grunde","Ny teknologi gav altid arbejderne bedre job med højere løn"],"correct":"Maskiner erstattede håndværkere og pressede lønningerne ned — mange mistede levebrødet da maskinerne overtog","accepted_answers":["Maskiner erstattede håndværkere og pressede lønningerne ned — mange mistede levebrødet da maskinerne overtog"],"review_text":"En vævemaskine kunne gøre arbejdet for 20 vævere. De 20 mistede deres levevej. Dem der stadig arbejdede fik lavere løn fordi maskinen pressede konkurrencen. Teknologisk fremgang skaber vindere og tabere — taberne mærkes sjældest i historiedokumenterne."}'::jsonb,
  'mc','short','{"concepts":["teknologi","arbejdsløshed","lønpres","misconception-teknologi-gavner-alle"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"industrialisation"}'::jsonb,
  'mc_single',3,'auto',true,'industrialisation',7,3
);

-- ─── GRADE 7 · BAND 4 (5 questions) ─────────────────────────────────────────

-- ind_g7b4_01 — Two perspectives: owners vs workers
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Fabriksejeren og fabriksarbejderen oplevede industrialiseringen vidt forskelligt. Hvad var de to perspektiver?","options":["Ejeren: fremgang, rigdom og ny samfundsorden. Arbejderen: tab af kontrol, farlige forhold, lange dage og usikker fremtid","Begge var tilfredse — ejerne tjente mere og arbejderne slap for hårdt landbrugsarbejde","Arbejderne var tilfredse; ejerne frustrerede over lav produktivitet","Begge var misfornøjede — ejerne over høj skat, arbejderne over lave lønninger"],"correct":"Ejeren: fremgang, rigdom og ny samfundsorden. Arbejderen: tab af kontrol, farlige forhold, lange dage og usikker fremtid","accepted_answers":["Ejeren: fremgang, rigdom og ny samfundsorden. Arbejderen: tab af kontrol, farlige forhold, lange dage og usikker fremtid"],"review_text":"Industrialiseringen var ét fænomen med to radikalt forskellige virkeligheder. Fabrikanterne oplevede velstand og magt. Arbejderne oplevede udmattelse, fare og afmagt. Begge perspektiver er historisk sande. At forstå begge er at forstå industrialiseringens kompleksitet."}'::jsonb,
  'mc','short','{"concepts":["perspektiv","fabrikant","arbejder","klassekonflik","industrialisering"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"industrialisation"}'::jsonb,
  'mc_single',4,'auto',true,'industrialisation',7,4
);

-- ind_g7b4_02 — Machine: liberation or oppression?
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Var dampmaskinen en befrier eller en tyran for de første industrielle arbejdere?","options":["For ejerne: en befrier fra naturens begrænsninger. For arbejderne: et tyrannisk tempo de var bundet til 14 timer om dagen","Den var rent en befrier — alle arbejdere elskede maskinernes effektivitet","Den var rent en tyran — ingen så noget positivt i teknologien","Spørgsmålet er meningsløst — maskiner er neutrale og hverken gode eller dårlige"],"correct":"For ejerne: en befrier fra naturens begrænsninger. For arbejderne: et tyrannisk tempo de var bundet til 14 timer om dagen","accepted_answers":["For ejerne: en befrier fra naturens begrænsninger. For arbejderne: et tyrannisk tempo de var bundet til 14 timer om dagen"],"review_text":"Dampmaskinen brød med naturens rytme — nu arbejdede man i samme tempo hele året, ikke med årstidernes cyklusser. For ejeren var det frihed fra vejrafhængighed. For arbejderen var det den evindelige maskines takt 14 timer om dagen, 6 dage om ugen. Teknologi er aldrig neutral."}'::jsonb,
  'mc','short','{"concepts":["teknologi","befrier","tyran","perspektiv","dampmaskine"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"industrialisation"}'::jsonb,
  'mc_single',4,'auto',true,'industrialisation',7,4
);

-- ind_g7b4_03 — Why reforms were difficult
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var grunden til at reformer der beskyttede arbejdere var svære at gennemføre?","options":["Fabriksejerne havde politisk magt og lobbykraft; arbejderne manglede stemmeret og organisering","Politikerne vidste simpelthen ikke om de dårlige forhold i fabrikkerne","Arbejderne selv modsatte sig reformerne fordi de frygtede at miste arbejdet","Det var teknisk umuligt at forbedre maskinernes sikkerhed uden at stoppe produktionen"],"correct":"Fabriksejerne havde politisk magt og lobbykraft; arbejderne manglede stemmeret og organisering","accepted_answers":["Fabriksejerne havde politisk magt og lobbykraft; arbejderne manglede stemmeret og organisering"],"review_text":"I 1800-tallets begyndelse var det typisk kun rige mænd der stemte. Fabrikanterne var rige mænd. Arbejderne hverken stemte eller var organiserede. Politisk magt og organisering manglede — og magt ændrer sjældent sig selv frivilligt."}'::jsonb,
  'mc','short','{"concepts":["reform","politisk magt","stemmeret","lobbyisme","magtbalance"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"industrialisation"}'::jsonb,
  'mc_single',4,'auto',true,'industrialisation',7,4
);

-- ind_g7b4_04 — Child labour complexity
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Var forældrene der sendte børn ud at arbejde i fabrikkerne onde eller ligeglade med deres børn?","options":["Nej — de var fanget i ekstrem fattigdom. Det var strukturen der var ond, ikke de individuelle forældre","Ja — det var bevidst forsømmelse der let kunne have været undgået","Ja — forældre havde ikke adgang til information om børnearbejdets farer","Nej — børnene nød fabriksarbejdet og valgte det selv"],"correct":"Nej — de var fanget i ekstrem fattigdom. Det var strukturen der var ond, ikke de individuelle forældre","accepted_answers":["Nej — de var fanget i ekstrem fattigdom. Det var strukturen der var ond, ikke de individuelle forældre"],"review_text":"At dømme fattige forældre er at misforstå historien. Valget stod mellem at sende barnet på arbejde eller at sulte. Det er ikke et reelt valg. Problemet var systemets manglende støtte — ikke forældrenes moralske karakter. Historikeren analyserer strukturen, ikke den enkeltes skyldbyrde."}'::jsonb,
  'mc','short','{"concepts":["børnearbejde","strukturel analyse","fattigdom","moralsk dom","individ vs system"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"industrialisation"}'::jsonb,
  'mc_single',4,'auto',true,'industrialisation',7,4
);

-- ind_g7b4_05 — Long-term consequence for democracy
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var industrialiseringens vigtigste langsigtede konsekvens for demokratiet?","options":["Industrialiseringen skabte en stor arbejderklasse der over tid krævede og opnåede politisk deltagelse — og dermed udvidede demokratiet","Industrialiseringen svækkede demokratiet fordi det styrkede de rige fabriksejeres magt permanent","Demokratiet og industrialiseringen var uafhængige — den ene påvirkede ikke den anden","Industrialiseringen afskaffede demokratiet midlertidigt men det vendte tilbage af sig selv"],"correct":"Industrialiseringen skabte en stor arbejderklasse der over tid krævede og opnåede politisk deltagelse — og dermed udvidede demokratiet","accepted_answers":["Industrialiseringen skabte en stor arbejderklasse der over tid krævede og opnåede politisk deltagelse — og dermed udvidede demokratiet"],"review_text":"Industrialiseringen skabte millioner af byboere og fabriksarbejdere. De organiserede sig i fagforeninger og politiske bevægelser. De krævede stemmeret, bedre vilkår og social lovgivning. Arbejderbevægelsen var en direkte konsekvens af industrialiseringen — og fundamentet for det moderne demokrati."}'::jsonb,
  'mc','short','{"concepts":["demokrati","arbejderbevægelse","stemmeret","politisk deltagelse","langsigtet konsekvens"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"industrialisation"}'::jsonb,
  'mc_single',4,'auto',true,'industrialisation',7,4
);

-- ─── GRADE 8 · BAND 1 (6 questions) ─────────────────────────────────────────

-- ind_g8b1_01 — Where it started
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"I hvilket land startede industrialiseringen og hvornår?","options":["England i slutningen af 1700-tallet — takket være kul, jern og kolonier","Frankrig ca. 1750 — drevet af den franske revolutions frihedsidealer","USA ca. 1800 — med bomuldsplantager som grundlag","Danmark ca. 1800 — med andelsbevægelsen som drivkraft"],"correct":"England i slutningen af 1700-tallet — takket være kul, jern og kolonier","accepted_answers":["England i slutningen af 1700-tallet — takket være kul, jern og kolonier"],"review_text":"England var første land til at industrialisere — ca. 1760-1840. Årsagerne: store kulreserver, jernmalerier, kolonier som markeder og råstofkilder, og kapitalrige handelsmænd. Ingen enkelt faktor er svaret — det var kombinationen."}'::jsonb,
  'mc','short','{"concepts":["industrialiseringens oprindelse","England","årsager","historisk kontekst"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"industrialisation"}'::jsonb,
  'mc_single',1,'auto',true,'industrialisation',8,1
);

-- ind_g8b1_02 — Danish timing
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvornår startede den egentlige industrialisering i Danmark?","options":["Ca. 1870-1880 — næsten 100 år efter England","Ca. 1800 — samtidig med England","Ca. 1950 — efter 2. Verdenskrig","Ca. 1750 — Danmark var faktisk foran England"],"correct":"Ca. 1870-1880 — næsten 100 år efter England","accepted_answers":["Ca. 1870-1880 — næsten 100 år efter England"],"review_text":"Danmark industrialiserede sent — ca. 1870-1880. England var allerede 100 år foran. Det skyldes dels mangel på kul og jern i Danmark, dels at dansk økonomi var landbrugsdomineret. Da industrialiseringen kom, fik den en dansk form der adskilte sig fra den britiske."}'::jsonb,
  'mc','short','{"concepts":["dansk industrialisering","timing","forsinkelse","England-sammenligning"],"misconception_type":"temporal_confusion","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"industrialisation"}'::jsonb,
  'mc_single',1,'auto',true,'industrialisation',8,1
);

-- ind_g8b1_03 — Proletariat
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betød begrebet \"proletariatet\"?","options":["Den nye klasse af lønmodtagere der ejede intet andet end deres arbejdskraft","Fabriksejerne der ejede produktionsmidlerne","Den politiske bevægelse der kæmpede for arbejdernes rettigheder","Adelen der mistede indflydelse under industrialiseringen"],"correct":"Den nye klasse af lønmodtagere der ejede intet andet end deres arbejdskraft","accepted_answers":["Den nye klasse af lønmodtagere der ejede intet andet end deres arbejdskraft"],"review_text":"Marx brugte begrebet proletariatet om dem der ikke ejede jord, maskiner eller kapital — kun deres egne hænder og tid. At sælge sin arbejdskraft for løn var den nye norm. Proletariatet var industrialiseringens helt nye klasse."}'::jsonb,
  'mc','short','{"concepts":["proletariat","arbejderklasse","lønmodtager","Marx"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"industrialisation"}'::jsonb,
  'mc_single',1,'auto',true,'industrialisation',8,1
);

-- ind_g8b1_04 — Railway importance
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var jernbanens vigtigste funktion for industrialiseringen?","options":["Den muliggjorde hurtig transport af råvarer til fabrikkerne og færdigvarer til markederne over lange afstande","Den transporterede primært arbejdere fra byerne til fabrikker på landet","Jernbanen var mest vigtig for militæret og havde ringe civil betydning","Den var et luksusgode kun rige forretningsfolk brugte"],"correct":"Den muliggjorde hurtig transport af råvarer til fabrikkerne og færdigvarer til markederne over lange afstande","accepted_answers":["Den muliggjorde hurtig transport af råvarer til fabrikkerne og færdigvarer til markederne over lange afstande"],"review_text":"Jernbanen forbandt kulminerne med fabrikkerne og fabrikkerne med byerne. Den skabte nationale markeder. Varer der kun solgtes lokalt kunne nu sælges over hele landet. Transport var industrialiseringens pulsåre — jernbanen var dens vigtigste åre."}'::jsonb,
  'mc','short','{"concepts":["jernbane","transport","marked","råvarer","industrialisering"],"misconception_type":"scope_confusion","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"industrialisation"}'::jsonb,
  'mc_single',1,'auto',true,'industrialisation',8,1
);

-- ind_g8b1_05 — Danish andelsbevaegelse
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var andelsbevægelsen i Danmark?","options":["Bønder der organiserede sig kollektivt i andelsmejerier og andelsslagterier for at konkurrere på eksportmarkederne","En dansk politisk bevægelse der kæmpede mod industrialiseringen","Et system hvor staten ejede alle landbrugsbedrifter fælles","En religiøs bevægelse der organiserede bøndernes arbejde"],"correct":"Bønder der organiserede sig kollektivt i andelsmejerier og andelsslagterier for at konkurrere på eksportmarkederne","accepted_answers":["Bønder der organiserede sig kollektivt i andelsmejerier og andelsslagterier for at konkurrere på eksportmarkederne"],"review_text":"Andelsbevægelsen var Danmarks svar på industrialiseringen. Bønder gik sammen om at eje og drive mejerier og slagterier kollektivt. Det gav dem forhandlingsstyrke og adgang til eksportmarkeder. Dansk smør og bacon dominerede det engelske marked i 1800-tallets slutning."}'::jsonb,
  'mc','short','{"concepts":["andelsbevægelse","Danmark","kollektiv organisering","eksport","landbrug"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"industrialisation"}'::jsonb,
  'mc_single',1,'auto',true,'industrialisation',8,1
);

-- ind_g8b1_06 — Reform movement: what is a trade union
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er den korteste præcise definition af en fagforening?","options":["En organisation der samler arbejdere til kollektiv forhandling om løn og arbejdsforhold","En privat klub for faglærte håndværkere med faglige standarder","En statslig institution der fastsætter minimumsløn","En organisation der uddanner nye arbejdere til fabriksarbejde"],"correct":"En organisation der samler arbejdere til kollektiv forhandling om løn og arbejdsforhold","accepted_answers":["En organisation der samler arbejdere til kollektiv forhandling om løn og arbejdsforhold"],"review_text":"Fagforeningens kraft er kollektiv: én arbejder kan let erstattes, men alle arbejdere tilsammen er uerstattelige på kort sigt. Kollektiv forhandling er kernen — ikke solidaritet alene, men organiseret pres der giver resultater."}'::jsonb,
  'mc','short','{"concepts":["fagforening","kollektiv forhandling","arbejderrettigheder"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"industrialisation"}'::jsonb,
  'mc_single',1,'auto',true,'industrialisation',8,1
);

-- ─── GRADE 8 · BAND 2 (7 questions) ─────────────────────────────────────────

-- ind_g8b2_01 — Why Britain first (causes)
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var årsagerne til at industrialiseringen startede i England?","options":["Kombination af kulreserver, jernforekomster, kolonier som markeder, handelsorienterede kapitalister og relativ politisk stabilitet","Ene og alene dampmaskinens opfindelse som kun englænderne kendte til","England tvang sine kolonier til at levere det nødvendige — industrialiseringen hvilede på slaveri alene","Engelske arbejdere var hårdere arbejdende end andre europæere"],"correct":"Kombination af kulreserver, jernforekomster, kolonier som markeder, handelsorienterede kapitalister og relativ politisk stabilitet","accepted_answers":["Kombination af kulreserver, jernforekomster, kolonier som markeder, handelsorienterede kapitalister og relativ politisk stabilitet"],"review_text":"Ingen enkelt faktor forklarer Englands tidlige industrialisering. Kul og jern gav energi og materialer. Kolonier gav råstoffer og afsætningsmarkeder. Kapitalister med risikovillighed investerede i maskiner. Den politiske stabilitet efter 1688 tillod langsigtet investering. Det var en unik kombination."}'::jsonb,
  'mc','short','{"concepts":["England","industrialiseringens årsager","kul","kolonier","kapital"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"industrialisation"}'::jsonb,
  'mc_single',2,'auto',true,'industrialisation',8,2
);

-- ind_g8b2_02 — Danish andelsbevaegelse significance
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betød andelsbevægelsen for den danske bondes stilling?","options":["Bønder der før solgte til lokale opkøbere til lave priser fik nu kollektiv forhandlingsstyrke og adgang til eksportmarkeder","Andelsbevægelsen forvandlede bønder til industriarbejdere","Staten overtog ansvaret for landbruget og bønderne mistede ejerskab","Andelsbevægelsen var primært en religiøs og kulturel bevægelse uden økonomisk effekt"],"correct":"Bønder der før solgte til lokale opkøbere til lave priser fik nu kollektiv forhandlingsstyrke og adgang til eksportmarkeder","accepted_answers":["Bønder der før solgte til lokale opkøbere til lave priser fik nu kollektiv forhandlingsstyrke og adgang til eksportmarkeder"],"review_text":"Én bonde med 5 køer kunne ikke sælge mælk direkte til England. 200 bønder der delte et mejeri kunne. Andelsbevægelsen ændrede magtbalancen: fra at være pristagere over for opkøbere til at være prissættere på det internationale marked."}'::jsonb,
  'mc','short','{"concepts":["andelsbevægelse","bønder","kollektiv magt","eksport","Danmark"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"industrialisation"}'::jsonb,
  'mc_single',2,'auto',true,'industrialisation',8,2
);

-- ind_g8b2_03 — Urbanisation and epidemics connection
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var den direkte årsag til at epidemier rasede i industribyer?","options":["Tæt befolkning delte vand fra brønde forurenet af latrinernes indhold — kolera og tyfus spredte sig via drikkevand","Industribyernes luft var forgiftet af fabriksdamp der direkte smittede lungerne","Arbejderne var underernærede og immunsystemet svigtede af sig selv","Epidemierne var forårssaget af byttedyr fra landet der fulgte med de migrerende bønder"],"correct":"Tæt befolkning delte vand fra brønde forurenet af latrinernes indhold — kolera og tyfus spredte sig via drikkevand","accepted_answers":["Tæt befolkning delte vand fra brønde forurenet af latrinernes indhold — kolera og tyfus spredte sig via drikkevand"],"review_text":"Koleraepidemier hærgede alle store industribyer i 1800-tallet. John Snow kortlagde i 1854 at London-epidemien kom fra én forurenet vandpumpe. Løsningen var ikke medicin men kloakering og rent vand. Det var en ingenørmæssig og politisk udfordring — ikke en medicinsk."}'::jsonb,
  'mc','short','{"concepts":["kolera","forurenet vand","kloakering","epidemi","folkesundhed"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"industrialisation"}'::jsonb,
  'mc_single',2,'auto',true,'industrialisation',8,2
);

-- ind_g8b2_04 — Working day reform consequences
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad skete med produktiviteten da reformer begrænsede arbejdsdagen fra 14 til 10 timer?","options":["Produktiviteten faldt ikke mærkbart — hvile og motivation opvejede den kortere tid. Det satte standard for videre reform","Produktiviteten halverede sig og mange fabrikker lukkede","Produktiviteten steg voldsomt fordi arbejderne nu var mere motiverede end nogensinde","Fabriksejerne havde ret — kortere arbejdsdag ødelagde den engelske økonomi"],"correct":"Produktiviteten faldt ikke mærkbart — hvile og motivation opvejede den kortere tid. Det satte standard for videre reform","accepted_answers":["Produktiviteten faldt ikke mærkbart — hvile og motivation opvejede den kortere tid. Det satte standard for videre reform"],"review_text":"Fabrikanterne advarede imod kortere arbejdsdag — produktionen ville kollapse. Det skete ikke. Udhvilede arbejdere lavede færre fejl og maskiner slidtes ikke så hurtigt. Reformen viste at humanitet og økonomi ikke altid er modsætninger."}'::jsonb,
  'mc','short','{"concepts":["arbejdsdagsreform","produktivitet","10-timersdagen","reform"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"industrialisation"}'::jsonb,
  'mc_single',2,'auto',true,'industrialisation',8,2
);

-- ind_g8b2_05 — Mechanisation of agriculture pushing people to cities
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var sammenhængen mellem mekanisering af landbruget og byernes vækst?","options":["Tærskemaskiner og plov-maskiner reducerede behovet for menneskehænder på landet og pressede folk mod fabrikjobs i byerne","Landbrugsmaskiner øgede produktionen så meget at bønderne blev rige og valgte at flytte til byerne","Byerne voksede uafhængigt af landbruget — industrialiseringen skabte selv befolkningsvækst","Statslig lovgivning forbød folk at bo på landet og tvang dem til byerne"],"correct":"Tærskemaskiner og plov-maskiner reducerede behovet for menneskehænder på landet og pressede folk mod fabrikjobs i byerne","accepted_answers":["Tærskemaskiner og plov-maskiner reducerede behovet for menneskehænder på landet og pressede folk mod fabrikjobs i byerne"],"review_text":"Maskinerne overtog landbrugsopgaver som høst og tærskning. Bønder der ikke ejede land mistede arbejdet. Fabrikkerne i byerne tilbød lønarbejde. Det var en push-pull bevægelse: presset fra landet og trukket mod byerne. Mange vandrede ikke af fri vilje."}'::jsonb,
  'mc','short','{"concepts":["mekanisering","landbrug","urbanisering","push-pull"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"industrialisation"}'::jsonb,
  'mc_single',2,'auto',true,'industrialisation',8,2
);

-- ind_g8b2_06 — Trade unions and democracy connection
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var sammenhængen mellem fagforeningsbevægelsen og udvidelsen af demokratiet?","options":["Fagforeninger organiserede arbejderklassen og kanaliserede krav om stemmeret og social lovgivning til politisk forandring","Fagforeninger og demokrati var uafhængige fænomener med forskellige rødder","Fagforeninger modvirkede demokratiet fordi de ønskede revolution frem for reformer","Demokratiet gav automatisk stemmeret til alle — fagforeningerne var unødvendige"],"correct":"Fagforeninger organiserede arbejderklassen og kanaliserede krav om stemmeret og social lovgivning til politisk forandring","accepted_answers":["Fagforeninger organiserede arbejderklassen og kanaliserede krav om stemmeret og social lovgivning til politisk forandring"],"review_text":"Fagforeningerne lærte arbejdere at organisere sig kollektivt. De samme organisationsformer blev brugt til at kræve stemmeret, sociallovgivning og arbejdsmarkedsreformer. I Danmark fik mænd og kvinder stemmeret i 1915 — en direkte konsekvens af årtiers politisk pres fra arbejderbevægelsen."}'::jsonb,
  'mc','short','{"concepts":["fagforening","demokrati","stemmeret","arbejderbevægelse"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"industrialisation"}'::jsonb,
  'mc_single',2,'auto',true,'industrialisation',8,2
);

-- ind_g8b2_07 — Child labour reform
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var årsagen til at børnearbejde gradvis blev forbudt i løbet af 1800-tallet?","options":["Kombination af reformistiske politikere, voksende folkelig opinion og erkendelsen af at børn behøvede uddannelse for samfundets skyld","Fabriksejerne afskaffede frivilligt børnearbejdet da maskiner klarede opgaverne bedre","Børnearbejdet forsvandt af sig selv da arbejderfamilier efterhånden fik råd til ikke at sende børn på arbejde","FN vedtog et globalt forbud mod børnearbejde i 1850"],"correct":"Kombination af reformistiske politikere, voksende folkelig opinion og erkendelsen af at børn behøvede uddannelse for samfundets skyld","accepted_answers":["Kombination af reformistiske politikere, voksende folkelig opinion og erkendelsen af at børn behøvede uddannelse for samfundets skyld"],"review_text":"Børnearbejdets afskaffelse kom ikke af sig selv. Det krævede reformpolitikere som Lord Shaftesbury i England, journalister der afslørede forholdene, og en voksende folkelig overbevisning om at børn tilhørte skolen, ikke fabrikken. Politisk vilje + folkelig opinion = forandring."}'::jsonb,
  'mc','short','{"concepts":["børnearbejde","reform","folkelig opinion","uddannelse","politisk forandring"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"industrialisation"}'::jsonb,
  'mc_single',2,'auto',true,'industrialisation',8,2
);

-- ─── GRADE 8 · BAND 3 (7 questions) ─────────────────────────────────────────

-- ind_g8b3_01 — Misconception: Denmark ≠ Britain
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved forestillingen om at Danmark industrialiserede præcis som England?","options":["England: kulgruber, tekstilmøller og tung industri. Danmark: andelsbevægelse, landbrugsforædling og senest byerhverv. Konteksten formede processen","Forestillingen er korrekt — alle lande industrialiserede efter den samme britiske model","Danmark industrialiserede faktisk hurtigere end England pga. bedre politisk organisering","Forskellen var kun i timing — ellers var processen identisk"],"correct":"England: kulgruber, tekstilmøller og tung industri. Danmark: andelsbevægelse, landbrugsforædling og senest byerhverv. Konteksten formede processen","accepted_answers":["England: kulgruber, tekstilmøller og tung industri. Danmark: andelsbevægelse, landbrugsforædling og senest byerhverv. Konteksten formede processen"],"review_text":"Danmark manglede kul og jern. Landbruget dominerede. Andelsbevægelsen var det danske svar: kollektiv organisering frem for store fabrikker. Industrialisering er ikke én universal sti — hvert lands geografi, råmaterialer og kultur former dens unikke form."}'::jsonb,
  'mc','short','{"concepts":["dansk industrialisering","England-sammenligning","andelsbevægelse","misconception-Danmark=England"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"industrialisation"}'::jsonb,
  'mc_single',3,'auto',true,'industrialisation',8,3
);

-- ind_g8b3_02 — Misconception: cities improved life
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er problematisk ved forestillingen om at byer automatisk forbedrede levevilkårene?","options":["Tidlige industribyer var livsfarlige — overbefolkning, smitsomme sygdomme og slumforhold betød at fabriksarbejdere statistisk levede kortere end bønder","Forestillingen er korrekt — byerne tilbød bedre sundhedspleje og boliger straks fra starten","Byerne var farlige men kun for fattige — middelklassen levede godt","Landlivet var faktisk endnu farligere — bønder levede kortere end fabriksarbejdere"],"correct":"Tidlige industribyer var livsfarlige — overbefolkning, smitsomme sygdomme og slumforhold betød at fabriksarbejdere statistisk levede kortere end bønder","accepted_answers":["Tidlige industribyer var livsfarlige — overbefolkning, smitsomme sygdomme og slumforhold betød at fabriksarbejdere statistisk levede kortere end bønder"],"review_text":"Statistikkerne er klare: middellevetiden for en manchesterfabriksarbejer i 1840 var ca. 28 år. En landarbejder samme sted levede til ca. 38. Byer forbedrede livet på sigt — men de første generationer betalte med liv og helbred for den fremtid der kom."}'::jsonb,
  'mc','short','{"concepts":["byers levevilkår","levetid","misconception-byer-forbedrer","statistik"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"industrialisation"}'::jsonb,
  'mc_single',3,'auto',true,'industrialisation',8,3
);

-- ind_g8b3_03 — Trade unions actually changed conditions
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad viser det at fagforeninger faktisk ændrede arbejdernes vilkår over tid?","options":["At kollektiv organisering virker — kortere arbejdsdag, minimumslønninger og arbejdsmiljølovgivning kom alle via faglig pres","At reformerne kom af sig selv som del af den naturlige samfundsudvikling","At fabriksejerne frivilligt forbedrede forholdene da de erkendte at det var profitabelt","At statens intervention alene var tilstrækkelig — fagforeningerne var unødvendige"],"correct":"At kollektiv organisering virker — kortere arbejdsdag, minimumslønninger og arbejdsmiljølovgivning kom alle via faglig pres","accepted_answers":["At kollektiv organisering virker — kortere arbejdsdag, minimumslønninger og arbejdsmiljølovgivning kom alle via faglig pres",""],"review_text":"Fagforeningerne er den vigtigste årsag til de arbejdsrettigheder vi tager for givet i dag. 8-timers arbejdsdag, weekend, betalt ferie og sikre arbejdspladser — alt vundet via årtiers organisering, strejker og politisk pres. Det kom ikke gratis."}'::jsonb,
  'mc','short','{"concepts":["fagforening","reformer","kollektiv organisering","arbejdsrettigheder"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"industrialisation"}'::jsonb,
  'mc_single',3,'auto',true,'industrialisation',8,3
);

-- ind_g8b3_04 — Technology and ownership (who benefits)
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er den dybeste forklaring på at teknologisk fremgang ikke gavner alle lige meget?","options":["Hvem der ejer teknologien bestemmer hvem der tjener på den — maskinen tilhørte kapitalisten, ikke arbejderen","Teknologi fordeler altid sine fordele jævnt — det er kun politikerne der griber forstyrrende ind","Arbejderne valgte ikke at drage fordel af teknologien og er selv skyld i uligheden","Teknologiens fordele er tidsforsinkede — alle nyder godt af den til sidst"],"correct":"Hvem der ejer teknologien bestemmer hvem der tjener på den — maskinen tilhørte kapitalisten, ikke arbejderen","accepted_answers":["Hvem der ejer teknologien bestemmer hvem der tjener på den — maskinen tilhørte kapitalisten, ikke arbejderen"],"review_text":"En arbejder ved en dampdrevet maskine skabte enorm merværdi. Men maskinen ejedes af fabrikanten. Overskuddet gik til ejeren — ikke til dem der betjente maskinen. Ejerskab af produktionsmidlerne afgør hvem der tjener på teknologien. Det er ikke teknologiens egenart men ejendomsretten der skaber ulighed."}'::jsonb,
  'mc','short','{"concepts":["ejerskab","teknologi","ulighed","kapital","misconception-teknologi-gavner-alle"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"industrialisation"}'::jsonb,
  'mc_single',3,'auto',true,'industrialisation',8,3
);

-- ind_g8b3_05 — Agriculture vs industry comparison
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var den vigtigste forskel på bonden og fabriksarbejerens hverdag?","options":["Bonden fulgte årstidernes rytme og ejede noget (jord eller dyr). Fabriksarbejderen var bundet til maskinens takt og ejede intet","Fabriksarbejderen havde det generelt bedre fordi lønnen var mere forudsigelig","Begge levede under identiske kår — arbejde var hårdt uanset om det var land eller by","Bonden var rigere men arbejdede mere; fabriksarbejderen var fattigere men arbejdede mindre"],"correct":"Bonden fulgte årstidernes rytme og ejede noget (jord eller dyr). Fabriksarbejderen var bundet til maskinens takt og ejede intet","accepted_answers":["Bonden fulgte årstidernes rytme og ejede noget (jord eller dyr). Fabriksarbejderen var bundet til maskinens takt og ejede intet"],"review_text":"Bonden der ejede en lille gård fulgte naturens rytme — travlt om sommeren, roligt om vinteren. Fabriksarbejderen arbejdede identisk alle årets dage, altid i maskinens tempo. Tabet af ejerskab og rytme var for mange ligeså traumatisk som de lave lønninger."}'::jsonb,
  'mc','short','{"concepts":["bonde","fabriksarbejder","ejerskab","rytme","sammenligning"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"industrialisation"}'::jsonb,
  'mc_single',3,'auto',true,'industrialisation',8,3
);

-- ind_g8b3_06 — Danish welfare state origins
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad har industrialiseringens uligheder at gøre med den danske velfærstats opståen?","options":["Industrialiseringens uligheder skabte politisk pres fra arbejderbevægelsen der lagde grunden til social lovgivning og den fremtidige velfærdsstat","Velfærdsstaten opstod uafhængigt af industrialiseringen som et religiøst filantropiprojekt","Industrialiseringen skabte så stor rigdom at velfærdsstaten blot var en naturlig fordeling","Den danske velfærdsstat er importeret fra Sverige og har ingen rødder i dansk industri"],"correct":"Industrialiseringens uligheder skabte politisk pres fra arbejderbevægelsen der lagde grunden til social lovgivning og den fremtidige velfærdstat","accepted_answers":["Industrialiseringens uligheder skabte politisk pres fra arbejderbevægelsen der lagde grunden til social lovgivning og den fremtidige velfærdstat"],"review_text":"Velfærdsstaten kom ikke tilfældigt. Industrialiseringens uligheder skabte en organiseret arbejderbevægelse der kæmpede for sygedagpenge, folkepension og børneomsorg. Social lovgivning i begyndelsen af 1900-tallet var direkte svar på industrialiseringens menneskelige omkostninger."}'::jsonb,
  'mc','short','{"concepts":["velfærdsstat","arbejderbevægelse","social lovgivning","dansk historie","industrialisering"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"industrialisation"}'::jsonb,
  'mc_single',3,'auto',true,'industrialisation',8,3
);

-- ind_g8b3_07 — Social mobility
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Var der mulighed for social opstigning for fabriksarbejdere under industrialiseringen?","options":["For de færreste — men faglærte arbejdere og dem med særlige evner eller held kunne stige. Det var muligt men ikke typisk","Alle arbejdere steg hurtigt til middelklassen indenfor én generation","Social opstigning var fuldstændig umulig — klasse var arvelig og uforanderlig","Alle der ville arbejde hårdt nok nåede toppen — det var et meritokrati"],"correct":"For de færreste — men faglærte arbejdere og dem med særlige evner eller held kunne stige. Det var muligt men ikke typisk","accepted_answers":["For de færreste — men faglærte arbejdere og dem med særlige evner eller held kunne stige. Det var muligt men ikke typisk"],"review_text":"Social opstigning eksisterede — men var sjælden. En faglært maskinmester kunne blive forman, en energisk handelsrejsende kunne åbne eget firma. Men de fleste fabriksarbejdere forblev fabriksarbejdere. Undtagelserne bekræftede myten om den universelle mulighed men dækkede over strukturens modstand."}'::jsonb,
  'mc','short','{"concepts":["social mobilitet","opstigning","klasse","meritokrati"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"industrialisation"}'::jsonb,
  'mc_single',3,'auto',true,'industrialisation',8,3
);

-- ─── GRADE 8 · BAND 4 (5 questions) ─────────────────────────────────────────

-- ind_g8b4_01 — Luddites: machine sabotage perspective
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad siger det om industrialiseringen at mange engelske arbejdere (luddisterne) i 1811-13 saboterede og smadrede fabriksmaskiner?","options":["At teknologisk fremgang kan opleves som en eksistentiel trussel af dem der mister deres levevej — modstand mod teknologi er ikke irrationel men rationel selvforsvar","At luddisterne var ignorante og ikke forstod at maskinerne ville forbedre alles liv","At luddisterne var et marginalt og uvæsentligt fænomen uden historisk betydning","At det beviser at arbejdere foretrak fattigdom frem for fremgang"],"correct":"At teknologisk fremgang kan opleves som en eksistentiel trussel af dem der mister deres levevej — modstand mod teknologi er ikke irrationel men rationel selvforsvar","accepted_answers":["At teknologisk fremgang kan opleves som en eksistentiel trussel af dem der mister deres levevej — modstand mod teknologi er ikke irrationel men rationel selvforsvar"],"review_text":"Luddisterne var erfarne vævere der mistede levebrødet til maskiner. At smadre maskinen der erstatter dig er rationel handling — ikke mangel på intelligens. Historikere analyserer luddisterne som tidlig modstand mod ukontrolleret kapitalisme, ikke som vandalisme. Perspektivet afgør vurderingen."}'::jsonb,
  'mc','short','{"concepts":["luddister","maskin-sabotage","teknologimodstand","perspektiv","rationel handling"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"industrialisation"}'::jsonb,
  'mc_single',4,'auto',true,'industrialisation',8,4
);

-- ind_g8b4_02 — Structural vs individual analysis
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Var industrialiseringens sociale problemer enkeltpersoners fejl eller strukturelle problemer?","options":["Strukturelle: børnearbejde, fattigdom og ulykker var systematiske resultater af et system uden regulering — ikke ondskabsfulde individers valg","Individuelle: fabriksejerne valgte bevidst at skade arbejderne af grådighed","Tilfældige: problemerne opstod uventet og ingen forudså dem","Naturlige: dårlige arbejdsforhold er uundgåelige i enhver industriproces"],"correct":"Strukturelle: børnearbejde, fattigdom og ulykker var systematiske resultater af et system uden regulering — ikke ondskabsfulde individers valg","accepted_answers":["Strukturelle: børnearbejde, fattigdom og ulykker var systematiske resultater af et system uden regulering — ikke ondskabsfulde individers valg"],"review_text":"Mange fabrikanter var ikke onde mennesker — de fulgte markedets logik. Når konkurrenten ikke brugte sikkerhedsafskærmning og tjente mere, gjorde du det samme eller tabte. Strukturen belønner dårlig adfærd. At ændre strukturen — via lovgivning — er den eneste effektive løsning. Det er den historiske lektie."}'::jsonb,
  'mc','short','{"concepts":["strukturel analyse","individuel ansvar","regulering","system","kapitalisme"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"industrialisation"}'::jsonb,
  'mc_single',4,'auto',true,'industrialisation',8,4
);

-- ind_g8b4_03 — Capitalism and democracy tension
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var det paradoksale i forholdet mellem kapitalisme og demokrati under industrialiseringen?","options":["Kapitalisterne kæmpede for borgerrettigheder og demokrati mod adelen — men frygtede et arbejderdemokrati der ville beskatte og regulere dem","Kapitalisme og demokrati var altid naturlige allierede uden nogen spænding","Kapitalisterne modsatte sig demokrati konsekvent fordi det truede deres ejendom","Demokratiet opstod uafhængigt af kapitalisme og industri"],"correct":"Kapitalisterne kæmpede for borgerrettigheder og demokrati mod adelen — men frygtede et arbejderdemokrati der ville beskatte og regulere dem","accepted_answers":["Kapitalisterne kæmpede for borgerrettigheder og demokrati mod adelen — men frygtede et arbejderdemokrati der ville beskatte og regulere dem"],"review_text":"Det store borgerskab kæmpede for parlamentarisme og borgerrettigheder mod det gamle aristokrati. Men da arbejderbevægelsen rejste sig og krævede stemmeret, var borgerskabet pludselig det konservative element. Man ønskede demokrati for sig selv — ikke nødvendigvis for alle."}'::jsonb,
  'mc','short','{"concepts":["kapitalisme","demokrati","borgerskab","arbejderbevægelse","paradoks"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"industrialisation"}'::jsonb,
  'mc_single',4,'auto',true,'industrialisation',8,4
);

-- ind_g8b4_04 — Denmark and Britain comparison (synthesis)
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad kan sammenligningen af dansk og britisk industrialisering fortælle os om historisk forandring generelt?","options":["At historiske processer ikke følger én universel vej — geografi, råmaterialer, kultur og politisk kontekst former unikke nationale varianter","At alle lande der industrialiserede måtte gennemgå de samme faser i den rigtige rækkefølge","At England var overlegent og resten af Europa blot kopierede den britiske model","At industrialisering kun lycedes i lande med store kolonier som råstofkilder"],"correct":"At historiske processer ikke følger én universel vej — geografi, råmaterialer, kultur og politisk kontekst former unikke nationale varianter","accepted_answers":["At historiske processer ikke følger én universel vej — geografi, råmaterialer, kultur og politisk kontekst former unikke nationale varianter"],"review_text":"England: kul, jern, tekstil, empire. Danmark: landbrugslandet med andelsbevægelse og mejerier. Begge industrialiserede — men på fundamentalt forskellige måder. Historien har ikke én vej. Konteksten former resultatet. Det er den dybeste lektie sammenlignende historiestudie kan lære os."}'::jsonb,
  'mc','short','{"concepts":["sammenligning","Danmark","England","historiske processer","kontekst"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"industrialisation"}'::jsonb,
  'mc_single',4,'auto',true,'industrialisation',8,4
);

-- ind_g8b4_05 — Industrial revolution legacy today
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er industrialiseringens vigtigste arv for det moderne samfund vi lever i?","options":["Lønarbejdets logik, velfærdsstatens rødder, fagforeningsbevægelsen og den fossile energiøkonomi vi nu kæmper med at transformere","Industrialiseringen er fortidig — den har ingen relevans for nutidens digitale økonomi","Den vigtigste arv er teknologien — alt andet er glemt","Industrialiseringen efterlod primært negative spor og bør glemmes"],"correct":"Lønarbejdets logik, velfærdsstatens rødder, fagforeningsbevægelsen og den fossile energiøkonomi vi nu kæmper med at transformere","accepted_answers":["Lønarbejdets logik, velfærdsstatens rødder, fagforeningsbevægelsen og den fossile energiøkonomi vi nu kæmper med at transformere"],"review_text":"Vi lever stadig i industrialiseringens arv. Lønarbejde er normen. Velfærdsstaten udsprang af arbejderbevægelsen. Fossile brændstoffer der drev industrialiseringen driver nu klimakrisen. Fagforeningerne eksisterer. Industrialiseringen er ikke fortid — dens strukturer og problemer er nutid."}'::jsonb,
  'mc','short','{"concepts":["arv","velfærdsstat","fossile brændstoffer","lønarbejde","nutidig relevans"],"misconception_type":"temporal_confusion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"industrialisation"}'::jsonb,
  'mc_single',4,'auto',true,'industrialisation',8,4
);
