-- Section 83 — Reformation & Monarchy — Grade 7 (25 questions) v2

-- ─── GRADE 7 · BAND 1 (6 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var Luthers 95 teser?","options":["Et dokument med 95 argumenter imod den katolske kirkes salg af afladsbreve offentliggjort i 1517","En liste over 95 ting Luther ville aendre i den protestantiske kirke","En religioes lovbog med 95 paragrafer","Et brev til paven med 95 spoergsmaal om kristendom"],"correct":"Et dokument med 95 argumenter imod den katolske kirkes salg af afladsbreve offentliggjort i 1517","accepted_answers":["Et dokument med 95 argumenter imod den katolske kirkes salg af afladsbreve offentliggjort i 1517"],"review_text":"I 1517 offentliggjorde Luther 95 argumenter mod kirkens salg af afladsbreve. Han naglede dem efter sigende op paa kirkedoren i Wittenberg. Teserne spredte sig hurtigt via bogtrykkerkunsten og startede en europaisk religioes revolution."}'::jsonb,
  'mc','short','{"concepts":["95 teser","Wittenberg","afladsbreve","1517"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',1,'auto',true,'reformation_monarchy',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad gjoerde Frederik III i 1660?","options":["Han indfoerte enevaeldet i Danmark og fjernede adelens politiske magt","Han grundlagde den lutherske kirke i Danmark","Han underskrev grundloven og indfoerte demokrati","Han afskaffede Reformationen og genindfoerte katolicisme"],"correct":"Han indfoerte enevaeldet i Danmark og fjernede adelens politiske magt","accepted_answers":["Han indfoerte enevaeldet i Danmark og fjernede adelens politiske magt"],"review_text":"I 1660 sammenkaldte Frederik III Staenderforsamlingen. I en historisk vending stemte adel, borger og praester for at give kongen enevaeldig magt. Adelens politiske privilegier forsvandt. Kongen styrerede nu uden rival."}'::jsonb,
  'mc','short','{"concepts":["Frederik III","enevaelde","1660","Staenderforsamling","adelen"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',1,'auto',true,'reformation_monarchy',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var adelens rolle i det danske samfund foer enevaeldet?","options":["Adelen var store jordejere med arvelige privilegier og politisk magt som kongen maatte forhandle med","Adelen var praester og kirkeledere der kontrollerede religionen","Adelen var koebmaend og haandvaerkere der styrede okonomien","Adelen var en militaer enhed der kun kaempede for kongen"],"correct":"Adelen var store jordejere med arvelige privilegier og politisk magt som kongen maatte forhandle med","accepted_answers":["Adelen var store jordejere med arvelige privilegier og politisk magt som kongen maatte forhandle med"],"review_text":"Adelen arvede privilegier som skattefrihed og ret til at sidde i Rigsraadet der raadgav kongen. De ejede store godser og kontrollerede boenderne. Foer enevaeldet var adelen kongens vigtigste rivalmagt."}'::jsonb,
  'mc','short','{"concepts":["adelen","privilegier","Rigsraadet","godser","rivalmagt"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',1,'auto',true,'reformation_monarchy',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betod det lutherske princip om frelse ved tro alene?","options":["At mennesket frelstes af sin tro paa Gud og ikke ved at kobe afladsbreve eller goere gode gerninger","At kun praester kunne opnaa frelse","At frelse kraevede pilgrimsrejse til Rom","At frelse kraevede at man betalte en aarslig afgift til kirken"],"correct":"At mennesket frelstes af sin tro paa Gud og ikke ved at kobe afladsbreve eller goere gode gerninger","accepted_answers":["At mennesket frelstes af sin tro paa Gud og ikke ved at kobe afladsbreve eller goere gode gerninger"],"review_text":"Luther laeste Paulus og forstod det saadan: Gud giver naade til den der tror ikke til den der betaler. Afladsbreve var meningsloese. Tro alene var nok. Det var en fundamental omvaeltning af kirkens system."}'::jsonb,
  'mc','short','{"concepts":["frelse","tro alene","afladsbreve","naade","Luther"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',1,'auto',true,'reformation_monarchy',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var en livegen bonde i Danmark?","options":["En bonde der var bundet til et bestemt gods og ikke maatte flytte uden herremandens tilladelse","En bonde der ejede sin jord og betalte skat til kongen","En fri bonde der arbejdede for loen paa andres gaarde","En byboer der dyrkede en lille have"],"correct":"En bonde der var bundet til et bestemt gods og ikke maatte flytte uden herremandens tilladelse","accepted_answers":["En bonde der var bundet til et bestemt gods og ikke maatte flytte uden herremandens tilladelse"],"review_text":"Livegne boender var bundne til godset. De maatte ikke flytte. De maatte ikke gifte sig uden herremandens tilladelse. De betalte afgifter i korn og arbejde. De var juridisk bundet til den jord de dyrkede."}'::jsonb,
  'mc','short','{"concepts":["livegen","bonde","gods","afgifter","binding"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',1,'auto',true,'reformation_monarchy',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er en statskirke?","options":["En kirke der er officielt forbundet med staten og kongen er dens overhoved","En kirke der finansierer staten via skatter","En kirke der er placeret i landets hovedstad","En kirke der er grundlagt af en konges beslutning men ellers er selvstaendig"],"correct":"En kirke der er officielt forbundet med staten og kongen er dens overhoved","accepted_answers":["En kirke der er officielt forbundet med staten og kongen er dens overhoved"],"review_text":"I Danmark efter Reformationen var kirken statskirke. Kongen var kirkens overhoved. Praesterne var statsansatte. Gudstjenestens indhold var bestemt af staten. Kirke og stat var smeltet samman i eet system."}'::jsonb,
  'mc','short','{"concepts":["statskirke","stat og kirke","kongens overhoved","sammensmeltet"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',1,'auto',true,'reformation_monarchy',7,1
);

-- ─── GRADE 7 · BAND 2 (7 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var bogtrykkerkunstens konkrete rolle i Reformationens spredning?","options":["Luthers skrifter og bibelen paa folkesprog kunne masseproduceres og naae laesere over hele Europa paa kort tid","Bogtrykkerkunsten hjalp paven med at udsende modargumenter hurtigere","Bogtrykkerkunsten var irrelevant fordi de fleste ikke kunne laese","Bogtrykkerkunsten bredte kun Reformationen til Sydtyskland"],"correct":"Luthers skrifter og bibelen paa folkesprog kunne masseproduceres og naae laesere over hele Europa paa kort tid","accepted_answers":["Luthers skrifter og bibelen paa folkesprog kunne masseproduceres og naae laesere over hele Europa paa kort tid"],"review_text":"Gutenbergs trykkepresse fra 1450 var afgoorende. Luthers tekster kunne massereproduceres. Bibeloversaettelse til folkesprog betod at laesere selv kunne studere Guds ord. Reformationen var den forste store massemediebegivenhed i historien."}'::jsonb,
  'mc','short','{"concepts":["bogtrykkeri","masseproduktion","folkesprog","Luther","spredning"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',2,'auto',true,'reformation_monarchy',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvorfor var det muligt for Frederik III at indfoere enevaeldet i 1660?","options":["Adelen var svaeekket af krige og gaeld og borgerskabet og praestestanden allierede sig med kongen mod adelen","Frederik III truede adelen militaert og tvang dem til at underskrive","Folket kraevede enevaelde ved en folkeafstemning","Paven beordrede enevaeldet som betingelse for fred"],"correct":"Adelen var svaeekket af krige og gaeld og borgerskabet og praestestanden allierede sig med kongen mod adelen","accepted_answers":["Adelen var svaeekket af krige og gaeld og borgerskabet og praestestanden allierede sig med kongen mod adelen"],"review_text":"Danmark havde tabt krige mod Sverige og adelen var baade svaeekket og hadet for ikke at betale skat. Frederik III spillede borgerskabet og praestestanden ud mod adelen. Da Staenderforsamlingen moodtes i 1660 var stemningen gunstig for kongen."}'::jsonb,
  'mc','short','{"concepts":["Frederik III","enevaelde","adelen svaeekket","borgerskab","alliancer"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',2,'auto',true,'reformation_monarchy',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad skete der med adelens privilegier da enevaeldet blev indfoert i 1660?","options":["Adelen mistede sin arvelige ret til politisk indflydelse og blev nu ligesom alle andre underlagt kongens vilje","Adelen bevarede al politisk magt men maattes dele det med borgerskabet","Adelen fik mere magt da kongen beloennede dem for at acceptere enevaeldet","Adelen forsvandt fuldstaendigt som klasse"],"correct":"Adelen mistede sin arvelige ret til politisk indflydelse og blev nu ligesom alle andre underlagt kongens vilje","accepted_answers":["Adelen mistede sin arvelige ret til politisk indflydelse og blev nu ligesom alle andre underlagt kongens vilje"],"review_text":"Foer 1660 sad adelen i Rigsraadet og kunne bremse kongen. Efter 1660 eksisterede Rigsraadet ikke laengere. Adelen beholdt sine godser og sociale privilegier men den politiske magt var vaek. Kongen regerede nu alene."}'::jsonb,
  'mc','short','{"concepts":["adelen","Rigsraadet","privilegier","enevaelde","magtfald"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',2,'auto',true,'reformation_monarchy',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var Reformationens konsekvens for uddannelse i Danmark?","options":["Det lutherske krav om at folk selv kunne laese bibelen skabte gradvist bredere adgang til skoleundervisning","Reformationen lukkede alle skoler fordi kirken ikke laengere maatte drive dem","Uddannelse forblev eksklusivt for adelen og hoejere borgerskab","Alle born fik skolegang straks efter Reformationen i 1536"],"correct":"Det lutherske krav om at folk selv kunne laese bibelen skabte gradvist bredere adgang til skoleundervisning","accepted_answers":["Det lutherske krav om at folk selv kunne laese bibelen skabte gradvist bredere adgang til skoleundervisning"],"review_text":"Det tok tid. Men Luthers ide om at alle kristne selv skulle kunne laese bibelen var motor for skoleundervisning. I 1739 indfoerte Danmark lovpligtig skoleundervisning. Reformationens ide om laasekompetence var en vigtig baggrund."}'::jsonb,
  'mc','short','{"concepts":["uddannelse","laesning","bibelen","skoleundervisning","1739"],"misconception_type":"temporal_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',2,'auto',true,'reformation_monarchy',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betod det at kirken og staten smeltede samman under enevaeldet?","options":["Kongen bestemte baaede over love og gudstjenester og praesterne var statsansatte der forkyndte lydighed","Kirken og staten var adskilt og paavirket ikke hinanden","Kirken styrede staten og praesterne var den reelle regering","Staten finansierede kirken men ellers var de uafhaengige"],"correct":"Kongen bestemte baaede over love og gudstjenester og praesterne var statsansatte der forkyndte lydighed","accepted_answers":["Kongen bestemte baaede over love og gudstjenester og praesterne var statsansatte der forkyndte lydighed"],"review_text":"Under enevaeldet var kongen Guds stedfortræder paa jord. Kongens love var Guds vilje. Praesterne forkyndte kongens budskaber. Kirken var statens ideologiske apparat. Det var en fundamental sammensmeltning af religioes og politisk magt."}'::jsonb,
  'mc','short','{"concepts":["stat og kirke","sammensmeltet","kongens magt","religioes legitimitet","enevaelde"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',2,'auto',true,'reformation_monarchy',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvorfor profiterede boenderne ikke paa Reformationen?","options":["Fordi den religiose og politiske revolution i toppen ikke aendrede de okonomiske og juridiske betingelser for boendernes liv","Fordi boender var mod Reformationen og derfor straffedes de","Fordi boender allerede levede saa godt at der intet var at forbedre","Fordi boender ikke var paavirket af religion overhovedet"],"correct":"Fordi den religiose og politiske revolution i toppen ikke aendrede de okonomiske og juridiske betingelser for boendernes liv","accepted_answers":["Fordi den religiose og politiske revolution i toppen ikke aendrede de okonomiske og juridiske betingelser for boendernes liv"],"review_text":"Reformationen aendrede hvem der kontrollerede kirken. Enevaeldet aendrede hvem der havde politisk magt. Men bondens afgifter, pligter og bundhed til godset forblev. De store magtpolitiske omvaeltninger passerede over boendernes hoveder."}'::jsonb,
  'mc','short','{"concepts":["boender","Reformation","okonomisk uforandret","pligter","godset"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',2,'auto',true,'reformation_monarchy',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var den protestantiske kirkes revolutionaere ide om den troende og Gud?","options":["At hvert enkelt menneske havde en direkte linje til Gud uden behov for kirkens praester og sakramenter som mellemled","At kun kongen kunne tale direkte med Gud","At Gud var utilgaengelig for alle undtagen biskopper","At den troende maatte betale for adgang til Guds naade"],"correct":"At hvert enkelt menneske havde en direkte linje til Gud uden behov for kirkens praester og sakramenter som mellemled","accepted_answers":["At hvert enkelt menneske havde en direkte linje til Gud uden behov for kirkens praester og sakramenter som mellemled"],"review_text":"Katolsk teologi placerede praesten som noedvendig mellemled til Gud. Luther sagde dette var forkert. Tro alene var nok. Det frigjoerde den troende fra kirkens monopol paa det hellige og var revolutionaert."}'::jsonb,
  'mc','short','{"concepts":["direkte linje","Gud","tro","praestens monopol","revolution"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',2,'auto',true,'reformation_monarchy',7,2
);

-- ─── GRADE 7 · BAND 3 (7 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved forestillingen om at enevaeldet betod at kongen kunne goere praecis hvad han ville?","options":["Kongen var stadig bundet af loven og Guds lov og tradition selvom ingen menneskelig institution officielt kunne stoppe ham","Forestillingen er korrekt enevaeldige konger kunne goere praecis hvad de ville","Det er forkert fordi adelen stadig begraensede kongen under enevaeldet","Det er forkert fordi paven stadig had magt over den danske kongen"],"correct":"Kongen var stadig bundet af loven og Guds lov og tradition selvom ingen menneskelig institution officielt kunne stoppe ham","accepted_answers":["Kongen var stadig bundet af loven og Guds lov og tradition selvom ingen menneskelig institution officielt kunne stoppe ham"],"review_text":"Enevaeldet var juridisk absolutt. Men konger var i teorien bundet af naturretten og Guds lov. Praktisk set ville en tyrannisk kongen risikere revolution eller mord. Konger der regerede stabilt og forstandigt overlevede laengere."}'::jsonb,
  'mc','short','{"concepts":["enevaelde","begraensninger","Guds lov","naturret","misconception-ubegreanset-magt"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',3,'auto',true,'reformation_monarchy',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad viser Reformationens politiske og okonomiske dimension om dens egentlige karakter?","options":["At Reformationen var baaede en religioes revolution og en magtpolitisk omfordeling der styrkede natinoalstater paa bekostning af paven","At Reformationen var en rent religioes begivenhed uden politiske konsekvenser","At Reformationens politiske dimension var langt vigtigere end den religiose","At Reformationen kun had okonomiske aarsager og ingen religiose"],"correct":"At Reformationen var baaede en religioes revolution og en magtpolitisk omfordeling der styrkede natinoalstater paa bekostning af paven","accepted_answers":["At Reformationen var baaede en religioes revolution og en magtpolitisk omfordeling der styrkede natinoalstater paa bekostning af paven"],"review_text":"Den politiske dimension var mindst ligesaa vigtig som den religiose. Konger broed med paven og overtog kirkens jord. Nationalstater voksede frem uafhaengige af Roms autoritet. Reformationen remappede Europas magtgeografi."}'::jsonb,
  'mc','short','{"concepts":["Reformation","politisk dimension","ejendom","nationalstater","dobbeltkarakter"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',3,'auto',true,'reformation_monarchy',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved forestillingen om at Luther alene skabte Reformationen?","options":["Luther var en udslagsgivende person men Reformationen lykkedes fordi mange var utilfredse med kirken og fyrster had okonomisk interesse i at stoette den","Forestillingen er korrekt Luther alene skabte Reformationen","Det er forkert fordi Luther faktisk ikke spillede nogen rolle","Det er forkert fordi Reformationen startede i Danmark ikke i Tyskland"],"correct":"Luther var en udslagsgivende person men Reformationen lykkedes fordi mange var utilfredse med kirken og fyrster had okonomisk interesse i at stoette den","accepted_answers":["Luther var en udslagsgivende person men Reformationen lykkedes fordi mange var utilfredse med kirken og fyrster had okonomisk interesse i at stoette den"],"review_text":"Luther var vigtig men Reformationen ville ikke have lykkedes uden bogtrykkerkunsten, uden beskyttelse fra tyske fyrstere og uden den brede folkelige utilfredshed med kirkens korruption. Historiske forandringer kraever strukturelle betingelser ikke blot enkeltpersoner."}'::jsonb,
  'mc','short','{"concepts":["Luther","enkeltperson","strukturelle betingelser","fyrstere","misconception-Luther-alene"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',3,'auto',true,'reformation_monarchy',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var konsekvenserne af enevaeldet for hverdagslivet for en dansk borger i 1700-tallet?","options":["Lov og orden forbedrede handel og sikkerhed men borgeren havde ingen politisk stemme og var underlagt statens kontrol via kirke og lov","Borgerne levede i frihed og velstand under enevaeldet","Enevaeldet betod konstant terror og borgerne levede i frygt","Borgerne maerkede slet ikke at der var enevaelde"],"correct":"Lov og orden forbedrede handel og sikkerhed men borgeren havde ingen politisk stemme og var underlagt statens kontrol via kirke og lov","accepted_answers":["Lov og orden forbedrede handel og sikkerhed men borgeren havde ingen politisk stemme og var underlagt statens kontrol via kirke og lov"],"review_text":"Enevaeldet bragte ensartede love og reducerede adelens lokale vilkaarlighed. Handel og haandvaerk blomstrede. Men borgeren stemte ikke. Han adlod kongens love. Kirken forkyndte lydighed. Friheden var okonomisk ikke politisk."}'::jsonb,
  'mc','short','{"concepts":["borger","enevaelde","hverdagsliv","handel","politisk frihed"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',3,'auto',true,'reformation_monarchy',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forbindelsen mellem Reformationen og den gradvise forbedring af laesekompetencer i Europa?","options":["Luthersk kristendom kraevede at den troende selv kunne laese bibelen og det skabte grundlag for skoleundervisning der gradvist naaede bredere befolkningsgrupper","Reformationen forringede laesekompetencer fordi kirken lukkede skolerne","Der er ingen forbindels laesekompetence og Reformationen er uafhaengige","Kun adelen opnaaede laesekompetence som resultat af Reformationen"],"correct":"Luthersk kristendom kraevede at den troende selv kunne laese bibelen og det skabte grundlag for skoleundervisning der gradvist naaede bredere befolkningsgrupper","accepted_answers":["Luthersk kristendom kraevede at den troende selv kunne laese bibelen og det skabte grundlag for skoleundervisning der gradvist naaede bredere befolkningsgrupper"],"review_text":"Den lutherske ide om det almene praestedoemme betod at hvert menneske ideelt set burde kunne laese Guds ord selv. Det skaabte en ideologisk motor for skoleundervisning. Gradvist over generationer naaede dette bredt ud."}'::jsonb,
  'mc','short','{"concepts":["laesekompetence","bibelen","skoleundervisning","almene praestedoemme","Reformation"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',3,'auto',true,'reformation_monarchy',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved forestillingen om at demokrati kom hurtigt efter enevaeldet?","options":["Enevaeldet varede i Danmark fra 1660 til 1849 og vejen dertil gik via Oplysning, revolutioner og gradvist pres for forfatning","Forestillingen er korrekt demokrati kom straks efter enevaeldet","Det er forkert fordi Danmark aldrig haft enevaelde","Det er forkert fordi demokratiet kom foer enevaeldet"],"correct":"Enevaeldet varede i Danmark fra 1660 til 1849 og vejen dertil gik via Oplysning, revolutioner og gradvist pres for forfatning","accepted_answers":["Enevaeldet varede i Danmark fra 1660 til 1849 og vejen dertil gik via Oplysning, revolutioner og gradvist pres for forfatning"],"review_text":"Fra 1660 til 1849 var Danmark enevaeldigt monarki. 189 aar. Oplysningstidens ideer om borgerrettigheder, den franske revolution og voksende borgerlig presse skabte langsomt betingelserne. Grundloven i 1849 var resultatet af et laangt historisk forloob."}'::jsonb,
  'mc','short','{"concepts":["demokrati","enevaelde","1849","Grundloven","langsom forandring"],"misconception_type":"temporal_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',3,'auto',true,'reformation_monarchy',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad viser adelens reaktion paa enevaeldet om forholdet mellem magt og klasse?","options":["Adelen forsoegte at modstaa enevaeldet fordi det truede de arvelige privilegier der had givet dem magt og rigdom i generationer","Adelen bejede enevaeldet enthusiastisk fordi det gav dem mere magt","Adelen var indifferent og lod kongen tage magten uden modstand","Adelen eksisterede ikke som klasse i 1660"],"correct":"Adelen forsoegte at modstaa enevaeldet fordi det truede de arvelige privilegier der had givet dem magt og rigdom i generationer","accepted_answers":["Adelen forsoegte at modstaa enevaeldet fordi det truede de arvelige privilegier der had givet dem magt og rigdom i generationer"],"review_text":"Adelen vidste hvad enevaeldet ville koste dem: Rigsraadet, skattefriheden og den formelle ret til at raadgive kongen. Mange forsoegte at forhandle. Men i 1660 var de for svaekkede af krige og gaeld til at modstaa."}'::jsonb,
  'mc','short','{"concepts":["adelen","enevaelde","privilegier","modstand","klasse"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',3,'auto',true,'reformation_monarchy',7,3
);

-- ─── GRADE 7 · BAND 4 (5 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Var Reformationen en befrielse for det menige folk?","options":["Delvist: religioes befrielse ved at fjerne kirkens monopol paa Guds ord men ingen social eller politisk befrielse for boender og fattige","Ja Reformationen befriede alle sociale klasser fra undertrykkelse","Nej Reformationen forvaerrede livet for alle undtagen kongen","Reformationen var irrelevant for det menige folk"],"correct":"Delvist: religioes befrielse ved at fjerne kirkens monopol paa Guds ord men ingen social eller politisk befrielse for boender og fattige","accepted_answers":["Delvist: religioes befrielse ved at fjerne kirkens monopol paa Guds ord men ingen social eller politisk befrielse for boender og fattige"],"review_text":"Reformationen gav folk et gudstjenesteliv de forstod. Men den gav dem ikke jord, frihed eller stemmeret. Den religiose frigoerelse var reel men den okonomiske og politiske frigoerelse kom ikke. Det er Reformationens paradoks."}'::jsonb,
  'mc','short','{"concepts":["befrielse","religioes frigoerelse","social uforandret","Reformationens paradoks"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',4,'auto',true,'reformation_monarchy',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var Reformationen og enevaeldet set fra kongens, adelens og bondens perspektiv?","options":["Kongen: magt og rigdom. Adelen: tab af politiske privilegier. Bonden: religioes forandring men okonomisk uforandret.","Alle tre grupper oplevede det som en ren forbedring","Alle tre grupper oplevede det som ren undertrykkelse","Kun kongen og adelen var paavirket boenderne var fuldstaendigt uberort"],"correct":"Kongen: magt og rigdom. Adelen: tab af politiske privilegier. Bonden: religioes forandring men okonomisk uforandret.","accepted_answers":["Kongen: magt og rigdom. Adelen: tab af politiske privilegier. Bonden: religioes forandring men okonomisk uforandret."],"review_text":"Reformationen og enevaeldet rammer alle tre grupper vidt forskelligt. Kongen vinder enormt paa begge. Adelen vinder paa Reformationen men taber paa enevaeldet. Bonden faar et gudstjenesteliv han forstaar men beholder sine afgifter og pligter."}'::jsonb,
  'mc','short','{"concepts":["tre perspektiver","kongen","adelen","bonden","Reformation og enevaelde"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',4,'auto',true,'reformation_monarchy',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var forbindelsen mellem Reformationens ide om individets samvittighed og Oplysningstiden 200 aar senere?","options":["Reformationens ide om at den troende selv kan fortolke Guds ord lagde grundlaget for Oplysningstiden ide om at individet ogsaa kan bruge sin fornuft til at kritisere monarker og traditioner","Der er ingen forbindels de to perioder er fuldstaendigt uafhaengige","Reformationen forhindrede Oplysning ved at saette Bibelen over fornuften","Oplysningstiden afviste Reformationens ideer fuldstaendigt"],"correct":"Reformationens ide om at den troende selv kan fortolke Guds ord lagde grundlaget for Oplysningstiden ide om at individet ogsaa kan bruge sin fornuft til at kritisere monarker og traditioner","accepted_answers":["Reformationens ide om at den troende selv kan fortolke Guds ord lagde grundlaget for Oplysningstiden ide om at individet ogsaa kan bruge sin fornuft til at kritisere monarker og traditioner"],"review_text":"Luther sagde: individets samvittighed over kirkens autoritet. Oplysningsfilosofferne sagde: individets fornuft over kongens autoritet. Begge satte individet over den etablerede institution. Det er ikke tilfaeldigt at Oplysning blomstrede i protestantiske lande."}'::jsonb,
  'mc','short','{"concepts":["individuel samvittighed","Oplysning","fornuft","autoritet","kontinuitet"],"misconception_type":"temporal_confusion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',4,'auto',true,'reformation_monarchy',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betod laeren om at kongens magt kom fra Gud?","options":["At modsaette sig kongen var det samme som at modsaette sig Guds vilje og det legitimerede enevaeldet som religioes pligt","At paven udpegede kongen og dermed beholdt paven al politisk magt","At kongen var Gud og maatte tilbedes som en religioes skikkelse","At kongen ikke behoevede at folge nogen love fordi Gud bestemte alt"],"correct":"At modsaette sig kongen var det samme som at modsaette sig Guds vilje og det legitimerede enevaeldet som religioes pligt","accepted_answers":["At modsaette sig kongen var det samme som at modsaette sig Guds vilje og det legitimerede enevaeldet som religioes pligt"],"review_text":"Laeren om kongens guddomsgivne magt var enevaeldets ideologiske fundament. At nagte at adlyde kongen var at nagte at adlyde Gud. Praesterne forkyndte lydighed til kongen fra praeekestolen. Kirken og staten forstaearkede hinanden gensidigt."}'::jsonb,
  'mc','short','{"concepts":["guddomsret","kongens magt","religioes legitimitet","enevaelde","lydighed"],"misconception_type":"scope_confusion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',4,'auto',true,'reformation_monarchy',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var saerligt ved den danske vej gennem Reformation og enevaelde?","options":["I Danmark skete begge via kongens beslutning ovenfra ikke via folkelig revolution nedefra og det formede en stærk stat-kirke-alliance der varte ved i aarhundreder","Danmark var det eneste land der nagtede Reformationen og forblev katolsk laengst","Danmark fik enevaelde via folkelig revolution som i Frankrig","Den danske Reformation og enevaelde var identiske med alle andre europaeiske laandes"],"correct":"I Danmark skete begge via kongens beslutning ovenfra ikke via folkelig revolution nedefra og det formede en stærk stat-kirke-alliance der varte ved i aarhundreder","accepted_answers":["I Danmark skete begge via kongens beslutning ovenfra ikke via folkelig revolution nedefra og det formede en stærk stat-kirke-alliance der varte ved i aarhundreder"],"review_text":"I lande som England og Frankrig var Reformationen og magtskiftet mere konfliktfyldt og blodigt. I Danmark kom begge igennem kongens beslutning ovenfra. Det formede en tradition for stærk statslig styring og konsensus der kan spordes frem til i dag."}'::jsonb,
  'mc','short','{"concepts":["dansk vej","ovenfra","stat-kirke-alliance","konsensus","tradition"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',4,'auto',true,'reformation_monarchy',7,4
);;
