-- Section 78 — Cold War Content Sprint
-- 50 questions: Grade 8 (25) + Grade 9 (25)
-- Bands: B1×12, B2×14, B3×14, B4×10
-- Concepts: superpower rivalry, ideology, arms race, Berlin Wall, Cuba,
--           propaganda, espionage, everyday life, Iron Curtain, end of Cold War
-- Misconceptions targeted throughout. All review_text. is_active=true.

-- ─── GRADE 8 · BAND 1 (6 questions) ─────────────────────────────────────────

-- cw_g8b1_01 — Cold War definition (misconception: not a shooting war)
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er \"Den Kolde Krig\"?","options":["En spænding og magtkamp mellem USA og Sovjet uden direkte militær kamp mellem dem","En krig der foregik i kolde klimaer i Sibirien og Arktis","Et navn for 1. Verdenskrig fordi den foregik om vinteren","En krig der aldrig skete — det var kun trusler"],"correct":"En spænding og magtkamp mellem USA og Sovjet uden direkte militær kamp mellem dem","accepted_answers":["En spænding og magtkamp mellem USA og Sovjet uden direkte militær kamp mellem dem"],"review_text":"Den Kolde Krig (1947-1991) var IKKE en krig med skyderi mellem USA og Sovjet. Det var en spænding og magtkamp med atomvåben, propaganda og kapløb om indflydelse. Kold fordi de to supermagter aldrig skød direkte på hinanden."}'::jsonb,
  'mc','short','{"concepts":["kolde krig definition","misconception-skydekrig","supermagter"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',1,'auto',true,'cold_war',8,1
);

-- cw_g8b1_02 — NATO
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var NATO under Den Kolde Krig?","options":["En militær alliance ledet af USA til kollektivt forsvar mod Sovjet","Et FN-organ til konfliktmægling mellem supermangterne","Et europæisk handelsforbund uden militær funktion","En videnskabelig organisation til rumforskning"],"correct":"En militær alliance ledet af USA til kollektivt forsvar mod Sovjet","accepted_answers":["En militær alliance ledet af USA til kollektivt forsvar mod Sovjet"],"review_text":"NATO (North Atlantic Treaty Organization) blev oprettet i 1949. Kernen: hvis ét NATO-land angribes, hjælper alle andre. Det var Vestens kollektive militære svar på frygten for Sovjet-invasion af Vesteuropa."}'::jsonb,
  'mc','short','{"concepts":["NATO","militæralliance","kollektivt forsvar"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',1,'auto',true,'cold_war',8,1
);

-- cw_g8b1_03 — Iron Curtain
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betød \"Jerntæppet\" i Europa under Den Kolde Krig?","options":["En politisk grænse der delte Europa i en fri vestlig del og en kommunistisk kontrolleret østlig del","En faktisk jernmur der fysisk dækkede hele Europas grænse","Et andet navn for Berlinmuren","En handelsspærring der forhindrede import og eksport"],"correct":"En politisk grænse der delte Europa i en fri vestlig del og en kommunistisk kontrolleret østlig del","accepted_answers":["En politisk grænse der delte Europa i en fri vestlig del og en kommunistisk kontrolleret østlig del"],"review_text":"Jerntæppet var ikke en fysisk mur — det var en politisk og ideologisk grænse. Vest for tæppet: demokrati og kapitalisme. Øst for tæppet: kommunisme under Sovjet-kontrol. Churchill brugte udtrykket i en berømt tale i 1946."}'::jsonb,
  'mc','short','{"concepts":["Jerntæppet","Europa-deling","ideologisk grænse"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',1,'auto',true,'cold_war',8,1
);

-- cw_g8b1_04 — Berlin Wall why built
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvorfor byggede Østtyskland Berlinmuren i 1961?","options":["For at stoppe de millioner der flygtede fra Øst til Vest","For at beskytte Østberlin mod vestlige militæranlæg","Som symbol på kommunismens styrke og stolthed","Fordi FN krævede at Berlin formelt blev delt i to byer"],"correct":"For at stoppe de millioner der flygtede fra Øst til Vest","accepted_answers":["For at stoppe de millioner der flygtede fra Øst til Vest"],"review_text":"Inden muren blev bygget, flygtede millioner af østtyskere til Vesttyskland — heriblandt mange unge og veluddannede. Muren stoppede flugten. Men den lukkede også borgerne inde. Det viser at Øst holdt sine borgere fanget, ikke fri."}'::jsonb,
  'mc','short','{"concepts":["Berlinmuren","flugt","DDR","Vesttyskland"],"misconception_type":"surface_association","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',1,'auto',true,'cold_war',8,1
);

-- cw_g8b1_05 — Sputnik
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var Sputnik, og hvorfor chokerede det USA?","options":["Den første menneskeskabte satellit — den viste at Sovjet var foran i raketteknologi og potentielt kunne nå USA med atomvåben","Den første atombombe testet af Sovjet i 1957","Et sovjet-spionfly der overvågede amerikanske militærbaser","Den første rumraket der nåede Månen"],"correct":"Den første menneskeskabte satellit — den viste at Sovjet var foran i raketteknologi og potentielt kunne nå USA med atomvåben","accepted_answers":["Den første menneskeskabte satellit — den viste at Sovjet var foran i raketteknologi og potentielt kunne nå USA med atomvåben"],"review_text":"I 1957 sendte Sovjet Sputnik i kredsløb — verdens første satellit. Chokket: hvis Sovjet kan sende en satellit op, kan de sende en atombombe. Det startede rumkapløbet og satte fuld gang i det amerikanske NASA-program."}'::jsonb,
  'mc','short','{"concepts":["Sputnik","rumkapløb","atombombe-trussel","teknologisk chok"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',1,'auto',true,'cold_war',8,1
);

-- cw_g8b1_06 — Arms race basics
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var atomkapløbet under Den Kolde Krig?","options":["USA og Sovjet byggede stadig flere atomvåben for at afskrækkeadden anden side fra at angribe","En konkurrence om hvem der testede atomvåben hurtigst","Et kapløb om at sælge atomvåben til allierede lande","En konkurrence om at bygge de største atomkraftværker"],"correct":"USA og Sovjet byggede stadig flere atomvåben for at afskrækkeadden anden side fra at angribe","accepted_answers":["USA og Sovjet byggede stadig flere atomvåben for at afskrækkeadden anden side fra at angribe"],"review_text":"Atomkapløbet betød tusindvis af atomvåben på begge sider — ikke for at bruge dem, men for at skræmme den anden fra at angribe. Jo mere destruktiv du var, desto sikrere var du. En farlig og dyr logik."}'::jsonb,
  'mc','short','{"concepts":["atomkapløb","afskrækkelse","supermagter","våbenopbygning"],"misconception_type":"scope_confusion","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',1,'auto',true,'cold_war',8,1
);

-- ─── GRADE 8 · BAND 2 (7 questions) ─────────────────────────────────────────

-- cw_g8b2_01 — Why Cold War started
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var den vigtigste årsag til at Den Kolde Krig startede efter 2. Verdenskrig?","options":["USA og Sovjet vandt krigen sammen men delte fundamentalt modsatrettede ideologier — og da fjenden var besejret, forsvandt grundlaget for samarbejdet","USA angreb Sovjet med atomvåben lige efter krigens afslutning","Sovjet invaderede Vesteuropa i 1946 og tvang USA til at reagere militært","FN erklærede krig mellem de to supermagter som en sikkerhedsforanstaltning"],"correct":"USA og Sovjet vandt krigen sammen men delte fundamentalt modsatrettede ideologier — og da fjenden var besejret, forsvandt grundlaget for samarbejdet","accepted_answers":["USA og Sovjet vandt krigen sammen men delte fundamentalt modsatrettede ideologier — og da fjenden var besejret, forsvandt grundlaget for samarbejdet"],"review_text":"USA ville have frie markeder og demokrati. Sovjet ville sprede kommunisme. Da Hitler var besejret, var samarbejdsgrundlaget væk. Mistillid og modsatrettede interesser i Europa eskalerede hurtigt til Den Kolde Krig."}'::jsonb,
  'mc','short','{"concepts":["koldkrig-oprindelse","ideologisk konflikt","efterkrigstid"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',2,'auto',true,'cold_war',8,2
);

-- cw_g8b2_02 — Capitalism vs Communism
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var den grundlæggende forskel på kapitalisme og kommunisme under Den Kolde Krig?","options":["I kapitalisme ejede private virksomheder produktionen og markedet satte priser; i kommunisme ejede staten alt på fællesskabets vegne","Kapitalisme var kun for rige lande; kommunisme var et system for fattige lande","Kommunisme tillod private virksomheder men med statsregulerede priser","Det var i praksis to navne for det samme system — bare med forskellige politiske symboler"],"correct":"I kapitalisme ejede private virksomheder produktionen og markedet satte priser; i kommunisme ejede staten alt på fællesskabets vegne","accepted_answers":["I kapitalisme ejede private virksomheder produktionen og markedet satte priser; i kommunisme ejede staten alt på fællesskabets vegne"],"review_text":"I kapitalisme (USA): private virksomheder og markedet bestemmer hvad der produceres. I kommunisme (Sovjet): staten ejer og styrer produktionen. To fundamentalt modsatte ideer om økonomi og frihed — det var kernen i Den Kolde Krig."}'::jsonb,
  'mc','short','{"concepts":["kapitalisme","kommunisme","ideologi","økonomi"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',2,'auto',true,'cold_war',8,2
);

-- cw_g8b2_03 — Why arms race escalated (MAD logic)
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvorfor blev begge sider ved med at bygge FLERE atomvåben — selv da de allerede havde nok til at ødelægge verden mange gange?","options":["Begge sider frygtede at den anden var teknologisk foran — og ingen turde risikere at stå svagere","Fordi det skabte arbejdspladser og var godt for begge landes økonomi","Fordi FN krævede at begge lande bevarede en minimumsarsenal","Fordi forskere på begge sider konkurrerede om internationale priser"],"correct":"Begge sider frygtede at den anden var teknologisk foran — og ingen turde risikere at stå svagere","accepted_answers":["Begge sider frygtede at den anden var teknologisk foran — og ingen turde risikere at stå svagere"],"review_text":"Logikken hed MAD — Mutually Assured Destruction. Begge parter vidste at et angreb ville betyde selvdestruktion. Men begge frygtede at den anden måske havde en skjult fordel. Det var et kapløb drevet af frygt — ikke faktisk behov."}'::jsonb,
  'mc','short','{"concepts":["MAD","atomkapløb","frygt","eskalation"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',2,'auto',true,'cold_war',8,2
);

-- cw_g8b2_04 — Propaganda purpose
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var formålet med propaganda under Den Kolde Krig?","options":["At overbevise den egne befolkning om at den anden side var ond og farlig — og at ens eget system var det bedste","At sprede falske militære oplysninger direkte til den fjendtlige hær","At rekruttere spioner i det andet lands ambassader","At informere neutrale lande neutralt om konflikten"],"correct":"At overbevise den egne befolkning om at den anden side var ond og farlig — og at ens eget system var det bedste","accepted_answers":["At overbevise den egne befolkning om at den anden side var ond og farlig — og at ens eget system var det bedste"],"review_text":"Begge sider brugte propaganda. Amerikanske skolebørn øvede atombombe-drills. Sovjet-borgere lærte at USA var et land styret af grådige kapitalister. Propaganda handlede om at kontrollere hvad din EGEN befolkning troede — ikke hvad fjenden troede."}'::jsonb,
  'mc','short','{"concepts":["propaganda","befolkningskontrol","ideologi"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',2,'auto',true,'cold_war',8,2
);

-- cw_g8b2_05 — Space Race significance
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betød rumkapløbet for Den Kolde Krig udover selve rumforskningen?","options":["Det var en ideologisk prestigekamp: den side der vandt i rummet beviste at dens system — kapitalisme eller kommunisme — var overlegen","Det var en aftale om at konkurrere fredeligt i rummet i stedet for med atomvåben","Det handlede primært om at finde naturressourcer på Månen og Mars","Rumkapløbet var adskilt fra Den Kolde Krig og fulgte sine egne regler"],"correct":"Det var en ideologisk prestigekamp: den side der vandt i rummet beviste at dens system — kapitalisme eller kommunisme — var overlegen","accepted_answers":["Det var en ideologisk prestigekamp: den side der vandt i rummet beviste at dens system — kapitalisme eller kommunisme — var overlegen"],"review_text":"Rummet var ikke blot videnskab — det var ideologisk scenen. Sovjet i rummet: kommunisme virker. USA på Månen: kapitalisme og frihed kan opnå det umulige. Hvert nyt rumrekord var gevinst i en global PR-kamp om hvem der havde det bedste system."}'::jsonb,
  'mc','short','{"concepts":["rumkapløb","ideologisk prestige","Sputnik","Månen"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',2,'auto',true,'cold_war',8,2
);

-- cw_g8b2_06 — Iron Curtain everyday people
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betød Jerntæppet konkret for almindelige borgere i Østeuropa?","options":["De kunne ikke frit rejse til Vesteuropa og adgang til vestlig information og medier var kraftigt begrænset","Det betød kun en politisk grænse — folk på begge sider rejste frit og kommunikerede uhindret","Vesteuropæere måtte ikke besøge Østeuropa men østeuropæere rejste frit vestpå","Det påvirkede primært politikere og militær — ikke normalbefolkningens hverdagsliv"],"correct":"De kunne ikke frit rejse til Vesteuropa og adgang til vestlig information og medier var kraftigt begrænset","accepted_answers":["De kunne ikke frit rejse til Vesteuropa og adgang til vestlig information og medier var kraftigt begrænset"],"review_text":"Jerntæppet var meget konkret i folks liv. Østeuropæere måtte ikke rejse frit til vest. Vestlige aviser og radio var forbudte eller jammede. Breve og telefonopkald til vestlige lande var overvågede. Frihed var en politisk beslutning — ikke en menneskeret."}'::jsonb,
  'mc','short','{"concepts":["Jerntæppet","hverdagsliv","rejsefrihed","censur","misconception-folk-upåvirkede"],"misconception_type":"overgeneralization","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',2,'auto',true,'cold_war',8,2
);

-- cw_g8b2_07 — Berlin Wall impact on families
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var den umiddelbare menneskelige konsekvens af Berlinmurens opførelse natten den 13. august 1961?","options":["Familier der boede på hver sin side af muren var pludselig afskåret fra hinanden","Muren skabte ti tusinder af nye arbejdspladser i byggeri og vagt","Muren gjorde Berlin til en sikrere by for alle borgere på begge sider","Borgerne på begge sider modtog kompensation fra regeringerne"],"correct":"Familier der boede på hver sin side af muren var pludselig afskåret fra hinanden","accepted_answers":["Familier der boede på hver sin side af muren var pludselig afskåret fra hinanden"],"review_text":"Berlinmuren tog ingen hensyn til familier. Natten den blev bygget var folk pludselig adskilt. Søskende, forældre og børn på hver sin side. Mange så ikke hinanden igen i årtier. Muren var politisk logik der ødelagde virkelige menneskers liv."}'::jsonb,
  'mc','short','{"concepts":["Berlinmuren","familiepåvirkning","menneskelig konsekvens"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',2,'auto',true,'cold_war',8,2
);

-- ─── GRADE 8 · BAND 3 (7 questions) ─────────────────────────────────────────

-- cw_g8b3_01 — Communism ≠ dictatorship (misconception)
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Er kommunisme og diktatur det samme?","options":["Nej — kommunisme er en ideologi om fælles ejerskab; diktatur er en styreform. Sovjet kombinerede dem i praksis — men de er ikke det samme per definition","Ja — alle kommunistiske lande var altid og nødvendigvis diktaturer","Ja — Marx og Lenin designede fra starten kommunisme som et enpartidiktatur","Nej — Sovjet var ikke et diktatur men blot et autoritært demokrati med ét parti"],"correct":"Nej — kommunisme er en ideologi om fælles ejerskab; diktatur er en styreform. Sovjet kombinerede dem i praksis — men de er ikke det samme per definition","accepted_answers":["Nej — kommunisme er en ideologi om fælles ejerskab; diktatur er en styreform. Sovjet kombinerede dem i praksis — men de er ikke det samme per definition"],"review_text":"Marx forestillede sig kommunisme som befrielse af arbejderne fra kapitalistisk udbytning — ikke diktatur. Lenin og Stalin formede det til enpartistyre med hemmelig politi. Teorien og praksis kan divergere dramatisk. Det er en af historiens vigtigste lektioner."}'::jsonb,
  'mc','short','{"concepts":["kommunisme","diktatur","ideologi","misconception-kommunisme=diktatur"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"cold_war"}'::jsonb,
  'mc_single',3,'auto',true,'cold_war',8,3
);

-- cw_g8b3_02 — Cuban Missile Crisis global threat (misconception: not just Cuba)
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var grunden til at Cuba-krisen i 1962 truede HELE verden — og ikke kun Cuba?","options":["Sovjet-raketterne i Cuba kunne ramme de fleste store amerikanske byer på 14 minutter — og et angreb på Cuba kunne udløse atomkrig","Krisens geografiske centrum var i Atlanterhavet og truede al international skibstrafik","Cuba selv truede med at erklære krig mod alle NATO-lande","FN var på nippet til at kollapse under presset fra begge supermagter"],"correct":"Sovjet-raketterne i Cuba kunne ramme de fleste store amerikanske byer på 14 minutter — og et angreb på Cuba kunne udløse atomkrig","accepted_answers":["Sovjet-raketterne i Cuba kunne ramme de fleste store amerikanske byer på 14 minutter — og et angreb på Cuba kunne udløse atomkrig"],"review_text":"Fra Cuba til Washington D.C. er der kun 14 minutters flyvtid for en raket. Sovjet-raketter i Cuba var ikke en trussel mod Cuba — de var rettet mod USA. Et angreb på Cuba ville sandsynligvis have udløst atomkrig. Hele verden var 13 dage fra mulig atomkrig."}'::jsonb,
  'mc','short','{"concepts":["Cuba-krisen","global trussel","misconception-kun-Cuba","atomkrig"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"cold_war"}'::jsonb,
  'mc_single',3,'auto',true,'cold_war',8,3
);

-- cw_g8b3_03 — Proxy wars
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var en \"proxy-krig\", og hvordan afspejler Koreakrigen og Vietnamkrigen dette?","options":["Krige hvor USA og Sovjet støttede modsatte sider uden selv at kæmpe mod hinanden direkte — og derved dræbte millioner uden formel krig","Krige styret med fjernkontrollerede våben og tidlige droner","Hemmelige krige som befolkningerne i USA og Sovjet aldrig kendte til","Krige der foregik i neutrale lande for at undgå at inddrage supermagternes egne territorier"],"correct":"Krige hvor USA og Sovjet støttede modsatte sider uden selv at kæmpe mod hinanden direkte — og derved dræbte millioner uden formel krig","accepted_answers":["Krige hvor USA og Sovjet støttede modsatte sider uden selv at kæmpe mod hinanden direkte — og derved dræbte millioner uden formel krig"],"review_text":"USA støttede Sydkorea og Sydvietnam. Sovjet støttede Nordkorea og Nordvietnam. Supermangterne kæmpede via allierede — ikke direkte. Den Kolde Krig var kold for supermagterne; varm og dødelig for koreanere og vietnamesere. Millioner døde i disse proxy-konflikter."}'::jsonb,
  'mc','short','{"concepts":["proxy-krig","Koreakrig","Vietnamkrig","indirekte konflikt"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"cold_war"}'::jsonb,
  'mc_single',3,'auto',true,'cold_war',8,3
);

-- cw_g8b3_04 — Everyday life misconception
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved påstanden at Den Kolde Krig kun påvirkede politikere og militæret?","options":["Ordinære borgere levede med atombombe-drills, propaganda, rejseforbud og frygt for atomkrig som reelle hverdagselementer","Påstanden er korrekt — al beslutningstagning skete bag lukkede politiske døre","Kun borgere tæt på militærbaser var reelt påvirkede","Kun borgere i Sovjet var påvirkede — vestlige borgere levede normalt"],"correct":"Ordinære borgere levede med atombombe-drills, propaganda, rejseforbud og frygt for atomkrig som reelle hverdagselementer","accepted_answers":["Ordinære borgere levede med atombombe-drills, propaganda, rejseforbud og frygt for atomkrig som reelle hverdagselementer"],"review_text":"Amerikanske skolebørn øvede duck-and-cover mod atombombe. Østeuropæere levede med overvågning og rejseforbud. Den Kolde Krig formede film, musik, sport og skolelæreplaner. Ingen blev skånet fra dens påvirkning — hverken i øst eller vest."}'::jsonb,
  'mc','short','{"concepts":["hverdagsliv","misconception-folk-upåvirkede","propaganda","frygt","duck-and-cover"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"cold_war"}'::jsonb,
  'mc_single',3,'auto',true,'cold_war',8,3
);

-- cw_g8b3_05 — MAD paradox
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var det paradoksale ved strategien om Gensidig Sikret Ødelæggelse (MAD)?","options":["Jo flere destruktive atomvåben du ejede, desto mere stabil var situationen — fordi ingen turde bruge dem","Jo færre atomvåben du havde, desto sikrere var du — og dermed var kapløbet irrationelt","MAD betød at begge sider var enige om at dele deres atomvåben ligeligt som afskrækkelse","Logikken betød at atomvåben kun ville rettes mod militære mål — aldrig mod civile"],"correct":"Jo flere destruktive atomvåben du ejede, desto mere stabil var situationen — fordi ingen turde bruge dem","accepted_answers":["Jo flere destruktive atomvåben du ejede, desto mere stabil var situationen — fordi ingen turde bruge dem"],"review_text":"MAD er et paradoks: mere destruktive våben skabte paradoksal stabilitet. Begge parter vidste at et angreb ville betyde total ødelæggelse af begge. Ingen turde angribe. Men denne stabilitet krævede konstant frygt og enorme udgifter til våben der aldrig måtte bruges."}'::jsonb,
  'mc','short','{"concepts":["MAD","afskrækkelse","paradoks","nuklear stabilitet"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"cold_war"}'::jsonb,
  'mc_single',3,'auto',true,'cold_war',8,3
);

-- cw_g8b3_06 — Espionage not just weapons
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad viser den massive brug af spionage under Den Kolde Krig om konfliktens natur?","options":["At konflikten ikke kun handlede om våben — information, teknologiske hemmeligheder og politiske planer var ligeså vigtige magtfaktorer","At begge sider primært spionerede mod neutrale lande for at rekruttere allierede","At spionage erstattede al militær aktivitet under Den Kolde Krig","At CIA og KGB i virkeligheden samarbejdede hemmelig om at fordele spionopgaverne"],"correct":"At konflikten ikke kun handlede om våben — information, teknologiske hemmeligheder og politiske planer var ligeså vigtige magtfaktorer","accepted_answers":["At konflikten ikke kun handlede om våben — information, teknologiske hemmeligheder og politiske planer var ligeså vigtige magtfaktorer"],"review_text":"CIA og KGB brugte enorme ressourcer på spioner, dobbelt-agenter og aflytning. De jagede atomhemmeligheder, militære planer og politisk information om hinandens lederskab. Den Kolde Krig var en informationskrig i ligeså høj grad som en våbenkrig."}'::jsonb,
  'mc','short','{"concepts":["spionage","CIA","KGB","informationskrig","misconception-kun-våben"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"cold_war"}'::jsonb,
  'mc_single',3,'auto',true,'cold_war',8,3
);

-- cw_g8b3_07 — Germany division consequences
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betød delingen af Tyskland i Øst og Vest for det tyske folk?","options":["En nation med fælles sprog og kultur i et årtusind blev politisk splittet — to generationer voksede op med radikalt forskellige politiske virkeligheder","Befolkningerne i Øst og Vest udviklede sig til to helt adskilte folk med egne sprog og identiteter","Delingen betød primært militære konsekvenser — civile liv var i store træk uforandrede","Østtyskerne fik dårligere kår men var grundlæggende tilfredse med det kommunistiske system"],"correct":"En nation med fælles sprog og kultur i et årtusind blev politisk splittet — to generationer voksede op med radikalt forskellige politiske virkeligheder","accepted_answers":["En nation med fælles sprog og kultur i et årtusind blev politisk splittet — to generationer voksede op med radikalt forskellige politiske virkeligheder"],"review_text":"I vest: demokrati, velstand og rejsefrihed. I øst: enpartidiktatur, planøkonomi og Stasi-overvågning. To generationer af tyskere voksede op i vidt forskellige verdener. Da genforeningen kom i 1990, mødte to fundamentalt different befolkninger hinanden."}'::jsonb,
  'mc','short','{"concepts":["Tysklands deling","DDR","Vesttyskland","national identitet","genforening"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"cold_war"}'::jsonb,
  'mc_single',3,'auto',true,'cold_war',8,3
);

-- ─── GRADE 8 · BAND 4 (5 questions) ─────────────────────────────────────────

-- cw_g8b4_01 — USA perspective on communism as threat
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvorfor opfattede mange amerikanere kommunisme som en eksistentiel trussel under Den Kolde Krig?","options":["Kommunisme truede privat ejendomsret og demokratiet som USA byggede sin identitet på — og Sovjet forsøgte aktivt at sprede det globalt","Fordi kommunistiske lande altid angreb NATO-lande militært","Fordi USA-borgere personligt mistede ejendom på grund af Sovjet-aktiviteter","Fordi FN erklærede kommunisme som en ulovlig international ideologi"],"correct":"Kommunisme truede privat ejendomsret og demokratiet som USA byggede sin identitet på — og Sovjet forsøgte aktivt at sprede det globalt","accepted_answers":["Kommunisme truede privat ejendomsret og demokratiet som USA byggede sin identitet på — og Sovjet forsøgte aktivt at sprede det globalt"],"review_text":"For mange amerikanere truede kommunisme selve fundamentet: privat ejendom, frie markeder og demokrati. Sovjet spredte aktivt kommunisme i Afrika, Asien og Latinamerika. USA så det som en trussel mod hele den verden-orden der gav USA sin magt og identitet."}'::jsonb,
  'mc','short','{"concepts":["USA-perspektiv","kommunismefrygt","ideologi","perspektiv"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',4,'auto',true,'cold_war',8,4
);

-- cw_g8b4_02 — Soviet perspective on USA
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvordan kunne Sovjet retfærdiggøre sin politik under Den Kolde Krig fra eget perspektiv?","options":["Sovjet var omringet af USA-militærbaser og NATO-alliancer og så sig som en nation der forsvarede sig mod vestlig omringning og kapitalistisk aggression","Sovjet ønskede aktivt at starte atomkrig og ventede bare på det rette tidspunkt","Sovjet-lederskabet var rent paranoid og handlede uden faktuelle grunde til bekymring","Sovjet opfattede USA som en samarbejdspartner der trak for hurtigt ud af Europa"],"correct":"Sovjet var omringet af USA-militærbaser og NATO-alliancer og så sig som en nation der forsvarede sig mod vestlig omringning og kapitalistisk aggression","accepted_answers":["Sovjet var omringet af USA-militærbaser og NATO-alliancer og så sig som en nation der forsvarede sig mod vestlig omringning og kapitalistisk aggression"],"review_text":"Fra Sovjet-perspektiv: USA havde atomvåben og militærbaser i alle nabolande. NATO omringede dem strategisk. USA propaganderede aktivt for at underminere kommunistiske regimer. At forstå modpartens perspektiv er ikke at godkende det — det er at forstå historien fuldt ud."}'::jsonb,
  'mc','short','{"concepts":["Sovjet-perspektiv","omringning","USA-aggression","misconception-Sovjet-altid-forkert"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',4,'auto',true,'cold_war',8,4
);

-- cw_g8b4_03 — Leaders vs ordinary people experience
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var den afgørende forskel på hvordan politiske ledere og ordinære borgere oplevede Den Kolde Krig?","options":["Ledere tog beslutningerne bag lukkede fortrolige døre; borgere bar konsekvenserne i hverdagen — atombombe-angst, propaganda og begrænsede friheder","Borgerne var bedre informerede end lederne om den faktiske militære situation","Borgerne i øst og vest oplevede situationen identisk — kun regeringerne var uenige","Politikerne bar den tungeste psykologiske byrde; borgerne var stort set upåvirkede"],"correct":"Ledere tog beslutningerne bag lukkede fortrolige døre; borgere bar konsekvenserne i hverdagen — atombombe-angst, propaganda og begrænsede friheder","accepted_answers":["Ledere tog beslutningerne bag lukkede fortrolige døre; borgere bar konsekvenserne i hverdagen — atombombe-angst, propaganda og begrænsede friheder"],"review_text":"Kennedy og Khrushchev forhandlede bag lukkede døre med fortrolige rapporter. Borgere levede med drills, propagandafilm og rejseforbud som hverdagsrealiteter. Beslutningerne lå hos lederne — konsekvenserne ramte alle."}'::jsonb,
  'mc','short','{"concepts":["ledere","borgere","hverdagsliv","magtasymmetri","perspektiv"],"misconception_type":"scope_confusion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',4,'auto',true,'cold_war',8,4
);

-- cw_g8b4_04 — Both sides used propaganda (symmetry)
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var den dybere årsag til at BEGGE sider — USA og Sovjet — brugte massiv propaganda mod deres egne borgere?","options":["Begge magter havde brug for befolkningens støtte til ofringer — enorme militærudgifter og frihedsbegrænsninger — og propaganda sikrede denne opbakning","Kun Sovjet brugte propaganda; USA informerede sine borgere faktabaseret og objektivt","Propaganda var et FN-krav til begge supermagter som betingelse for at sidde i Sikkerhedsrådet","Begge sider brugte propaganda fordi det var billigere end faktisk militæropbygning"],"correct":"Begge magter havde brug for befolkningens støtte til ofringer — enorme militærudgifter og frihedsbegrænsninger — og propaganda sikrede denne opbakning","accepted_answers":["Begge magter havde brug for befolkningens støtte til ofringer — enorme militærudgifter og frihedsbegrænsninger — og propaganda sikrede denne opbakning"],"review_text":"Propaganda er ikke kun et diktatur-fænomen. USA skabte Hollywood-film og skolekampagner der fremstillede Sovjet som ondsindede tyranner. Begge sider havde brug for at befolkningerne accepterede enorme militærudgifter og frihedsbegrænsninger. Propaganda var et styringsværktøj for begge."}'::jsonb,
  'mc','short','{"concepts":["propaganda","begge sider","befolkningskontrol","misconception-USA-altid-rigtig"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',4,'auto',true,'cold_war',8,4
);

-- cw_g8b4_05 — Berlin Wall: state vs citizens perspectives
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad afslører forskellene i statens og borgernes oplevelse af Berlinmuren?","options":["Staten kaldte den officielt en antifascistisk beskyttelsesvold; borgerne oplevede den som et fængselshegn — over 140 døde i forsøg på at krydse den","Begge — stat og borgere — var enige om at muren var en nødvendig sikkerhedsforanstaltning","Borgerne var stolte af muren som et symbol på østtysk styrke og selvstændighed","Staten sagde den var midlertidig; borgerne vidste det ikke ville vare"],"correct":"Staten kaldte den officielt en antifascistisk beskyttelsesvold; borgerne oplevede den som et fængselshegn — over 140 døde i forsøg på at krydse den","accepted_answers":["Staten kaldte den officielt en antifascistisk beskyttelsesvold; borgerne oplevede den som et fængselshegn — over 140 døde i forsøg på at krydse den"],"review_text":"Den østtyske stat kaldte muren officielt Antifaschistischer Schutzwall — beskyttelse mod vestlig fascisme. Borgerne der risikerede livet for at krydse den, oplevede et fængsel. Over 140 mennesker døde i flugtforsøg. Ord og virkelighed var vidt forskellig."}'::jsonb,
  'mc','short','{"concepts":["Berlinmuren","statspropaganda","borgerlige konsekvenser","perspektiv"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',4,'auto',true,'cold_war',8,4
);

-- ─── GRADE 9 · BAND 1 (6 questions) ─────────────────────────────────────────

-- cw_g9b1_01 — Cuban Missile Crisis basics
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad skete under Cuba-krisen i oktober 1962?","options":["USA opdagede Sovjet-atomraketter i Cuba — 13 dage på kanten af atomkrig endte da Khrushchev trak raketterne tilbage","Cuba forsøgte med Sovjet-støtte at invadere Florida","USA satte egne atomraketter på Cuba som svar på en Sovjet-provokation","FN afholdt en nødkonference på Cuba der løste krisen hurtigt"],"correct":"USA opdagede Sovjet-atomraketter i Cuba — 13 dage på kanten af atomkrig endte da Khrushchev trak raketterne tilbage","accepted_answers":["USA opdagede Sovjet-atomraketter i Cuba — 13 dage på kanten af atomkrig endte da Khrushchev trak raketterne tilbage"],"review_text":"Et amerikansk spionfly opdagede i oktober 1962 Sovjet-raketter i Cuba. USA blokerede Cuba. 13 dage stod verden på kanten af atomkrig. Til sidst trak Khrushchev raketterne tilbage, Kennedy lovede ikke at invadere Cuba. Det tætteste verden kom på atomkrig under Den Kolde Krig."}'::jsonb,
  'mc','short','{"concepts":["Cuba-krisen","1962","Khrushchev","Kennedy","atomkrig"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',1,'auto',true,'cold_war',9,1
);

-- cw_g9b1_02 — Warsaw Pact
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var Warszawapagten?","options":["Sovjet-ledede militæralliance for Østeuropas kommunistiske lande — modstykket til NATO","En fredsaftale underskrevet af alle europæiske lande i 1955","En handelsaftale der bandt Østeuropa til Sovjet-markedet","Et FN-organ til overvågning af den europæiske grænse"],"correct":"Sovjet-ledede militæralliance for Østeuropas kommunistiske lande — modstykket til NATO","accepted_answers":["Sovjet-ledede militæralliance for Østeuropas kommunistiske lande — modstykket til NATO"],"review_text":"Warszawapagten (1955) var Sovjet-blokens svar på NATO. Lande som Polen, Tjekkoslovakiet og Østtyskland var militært forpligtet til Sovjet. Ligesom NATO sikrede kollektivt forsvar — men denne gang rettet mod Vesten."}'::jsonb,
  'mc','short','{"concepts":["Warszawapagten","Sovjet-blok","militæralliance","NATO"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',1,'auto',true,'cold_war',9,1
);

-- cw_g9b1_03 — Gorbachev reforms
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betød Gorbatjovs reformer glasnost og perestrojka?","options":["Glasnost = åbenhed i information; perestrojka = omstrukturering af økonomien — reformer der utilsigtet accelererede Sovjet-systemets sammenbrud","Glasnost = mere censur; perestrojka = nationalisering af private virksomheder","Militær opbygning og lukning af grænser for at beskytte Sovjet mod vestlig indflydelse","Det var propaganda-begreber uden reel politisk indhold bag sig"],"correct":"Glasnost = åbenhed i information; perestrojka = omstrukturering af økonomien — reformer der utilsigtet accelererede Sovjet-systemets sammenbrud","accepted_answers":["Glasnost = åbenhed i information; perestrojka = omstrukturering af økonomien — reformer der utilsigtet accelererede Sovjet-systemets sammenbrud"],"review_text":"Gorbatjov ville reformere Sovjet — ikke ødelægge det. Glasnost tillod offentlig kritik. Perestrojka forsøgte at effektivisere den stagnerede økonomi. Men reformerne løsnede kontrollen og åbnede for folkeopstande. Resultatet: Sovjet kollapsede i 1991."}'::jsonb,
  'mc','short','{"concepts":["Gorbatjov","glasnost","perestrojka","Sovjet-sammenbrud"],"misconception_type":"causal_inversion","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',1,'auto',true,'cold_war',9,1
);

-- cw_g9b1_04 — End of Cold War when
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvornår sluttede Den Kolde Krig og hvad var de to vigtigste tegn?","options":["1989-1991 — Berlinmurens fald i november 1989 og Sovjet-Unionens opløsning i december 1991","1963 da begge sider underskrev en fredsaftale efter Cuba-krisen","1975 da USA trak sig ud af Vietnam og opgav sin militære overlegenhed","1980 da Reagan vandt præsidentvalget med anti-Sovjet program"],"correct":"1989-1991 — Berlinmurens fald i november 1989 og Sovjet-Unionens opløsning i december 1991","accepted_answers":["1989-1991 — Berlinmurens fald i november 1989 og Sovjet-Unionens opløsning i december 1991"],"review_text":"Den Kolde Krig sluttede gradvist 1989-1991. Berlinmurens fald 9. november 1989 var det mest dramatiske tegn. To år senere opløstes Sovjet-Unionen i 15 selvstændige stater. Det var ikke et punktum — det var en langsom opløsning."}'::jsonb,
  'mc','short','{"concepts":["Kolde Krig afslutning","Berlinmur","Sovjet-opløsning","misconception-øjeblikkelig slutning"],"misconception_type":"temporal_confusion","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',1,'auto',true,'cold_war',9,1
);

-- cw_g9b1_05 — MAD concept
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad stod MAD for under Den Kolde Krig?","options":["Mutually Assured Destruction — gensidig sikret ødelæggelse: hvis én side angriber, ødelægges begge","Military Advancement Division — den afdeling i Pentagon der styrede atomvåbnene","Multilateral Arms Disarmament — en FN-aftale om gradvis atomnedrustning","Moscow-America Dialogue — den direkte telefonlinje mellem de to supermagter"],"correct":"Mutually Assured Destruction — gensidig sikret ødelæggelse: hvis én side angriber, ødelægges begge","accepted_answers":["Mutually Assured Destruction — gensidig sikret ødelæggelse: hvis én side angriber, ødelægges begge"],"review_text":"MAD var den strategiske logik der afskrækkede begge sider fra at angribe. Hvis USA angreb med atomvåben, ville Sovjet svare. Begge ødelægges. Ingen turde starte. En form for stabilitet baseret på frygt for fuldstændig gensidig udslettelse."}'::jsonb,
  'mc','short','{"concepts":["MAD","atomafskrækkelse","nuklear strategi"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',1,'auto',true,'cold_war',9,1
);

-- cw_g9b1_06 — Checkpoint Charlie
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var Checkpoint Charlie?","options":["Den mest kendte grænseovergang i Berlinmuren — det eneste officielle sted vestlige allierede og diplomater måtte passere til Østberlin","En berømt dobbelt-agent der arbejdede for begge sider under Den Kolde Krig","En NATO-kommandopost på grænsen til Sovjet-kontrolleret territorium","Et kodenavn for USA-spionfly der overvågede Østeuropa"],"correct":"Den mest kendte grænseovergang i Berlinmuren — det eneste officielle sted vestlige allierede og diplomater måtte passere til Østberlin","accepted_answers":["Den mest kendte grænseovergang i Berlinmuren — det eneste officielle sted vestlige allierede og diplomater måtte passere til Østberlin"],"review_text":"Checkpoint Charlie var et symbol på det delte Berlin. Her mødte øst og vest hinanden ansigt til ansigt — soldater fra supermagterne foran hinanden. Det eneste officielle krydsningspunkt for vestlige diplomater og allierede. I dag er det et museum i Berlin."}'::jsonb,
  'mc','short','{"concepts":["Checkpoint Charlie","Berlinmuren","Berlin","grænseovergang"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',1,'auto',true,'cold_war',9,1
);

-- ─── GRADE 9 · BAND 2 (7 questions) ─────────────────────────────────────────

-- cw_g9b2_01 — Why Soviet Union collapsed
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var den vigtigste årsag til Sovjet-Unionens sammenbrud i 1991?","options":["Kombination af stagneret planøkonomi, tabte proxy-krige (Afghanistan), og folkeoprør i Østeuropa der udtømte systemet","Et militært nederlag til USA i en direkte krig","En naturkatastrofe der ødelagde Sovjet-Unionens infrastruktur","FN-sanktioner der afskærede Sovjet fra verdenshandelen"],"correct":"Kombination af stagneret planøkonomi, tabte proxy-krige (Afghanistan), og folkeoprør i Østeuropa der udtømte systemet","accepted_answers":["Kombination af stagneret planøkonomi, tabte proxy-krige (Afghanistan), og folkeoprør i Østeuropa der udtømte systemet"],"review_text":"Sovjet kollapsede ikke fordi USA vandt en krig — det kollapsede indefra. En ineffektiv planøkonomi, den katastrofale Afghanistandkrig og folkeopstande i Østeuropa udtømte systemet. Gorbatjovs reformer forsøgte at redde det — men løsnede kontrollen i stedet."}'::jsonb,
  'mc','short','{"concepts":["Sovjet-sammenbrud","planøkonomi","Afghanistan","folkeopstande"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',2,'auto',true,'cold_war',9,2
);

-- cw_g9b2_02 — Why Cuba became flashpoint
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var den strategiske grund til at Cuba var så central i Den Kolde Krig?","options":["Cuba ligger 145 km fra Florida — Sovjet-kontrol over Cuba betød at atomraketter kunne placeres direkte på USA''s dørtærskel","Cuba var den eneste kommunistiske stat i hele verden uden for Østeuropa og Kina","Cuba havde de største oliereserver i Vestindien som begge supermagter ønskede at kontrollere","Cuba var symbolsk vigtig for FN som det eneste kommunistiske land i Amerika"],"correct":"Cuba ligger 145 km fra Florida — Sovjet-kontrol over Cuba betød at atomraketter kunne placeres direkte på USA''s dørtærskel","accepted_answers":["Cuba ligger 145 km fra Florida — Sovjet-kontrol over Cuba betød at atomraketter kunne placeres direkte på USA''s dørtærskel"],"review_text":"Geografien var afgørende. Cuba er 145 km fra USA-kysten. Sovjet-raketter der kunne nå Washington D.C. på 14 minutter. For USA var det som en pistol rettet mod tindingen. Cuba-krisen handlede ikke om Cuba — det handlede om magtbalancen på USAs eget baghave."}'::jsonb,
  'mc','short','{"concepts":["Cuba","geografi","strategisk placering","magtbalance"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',2,'auto',true,'cold_war',9,2
);

-- cw_g9b2_03 — CIA vs KGB espionage
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var CIA og KGBs primære funktion under Den Kolde Krig?","options":["Indsamle information om den anden side — rekruttere spioner, stjæle militære hemmeligheder og manipulere fremmede regeringer","Rekruttere soldater til proxy-krige i Asien og Afrika","Overvåge atomvåbnenes tilstand og forhindre utilsigtet detonation","CIA og KGB samarbejdede hemmelig om at fordele spionopgaverne globalt"],"correct":"Indsamle information om den anden side — rekruttere spioner, stjæle militære hemmeligheder og manipulere fremmede regeringer","accepted_answers":["Indsamle information om den anden side — rekruttere spioner, stjæle militære hemmeligheder og manipulere fremmede regeringer"],"review_text":"CIA og KGB var hinandens modstykker i en skyggeverdenen. De rekrutterede dobbelt-agenter, stjal atomhemmeligheder og forsøgte at destabilisere hinandens allierede. Spionage var en central del af Den Kolde Krig — information var ligeså vigtig som atomvåben."}'::jsonb,
  'mc','short','{"concepts":["CIA","KGB","spionage","informationskrig"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',2,'auto',true,'cold_war',9,2
);

-- cw_g9b2_04 — Korean War as proxy
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad viser Koreakrigen (1950-53) om Den Kolde Krigs natur?","options":["At Den Kolde Krig ikke var kold for dem der faktisk kæmpede — proxy-krige kostede millioner af liv uden at supermangterne formelt kæmpede mod hinanden","At USA og Sovjet samarbejdede om at mægle freden i Korea via FN","At Kina var den egentlige supermagt der styrede den asiatiske del af koldkrigs-konflikterne","At Den Kolde Krig forblev fredelig fordi FN greb hurtigt ind og forhindrede eskalation"],"correct":"At Den Kolde Krig ikke var kold for dem der faktisk kæmpede — proxy-krige kostede millioner af liv uden at supermangterne formelt kæmpede mod hinanden","accepted_answers":["At Den Kolde Krig ikke var kold for dem der faktisk kæmpede — proxy-krige kostede millioner af liv uden at supermangterne formelt kæmpede mod hinanden"],"review_text":"I Koreakrigen døde over 3 millioner — soldater og civile. USA støttede syd, Kina og Sovjet støttede nord. Krigen var kold for supermangterne. Varm og dødelig for koreanerne. Kold Krig er et vestcentreret udtryk der skjuler de mange proxy-krigers realitet."}'::jsonb,
  'mc','short','{"concepts":["Koreakrig","proxy-krig","tab","misconception-fredelig-koldkrig"],"misconception_type":"overgeneralization","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"perspective_shift","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',2,'auto',true,'cold_war',9,2
);

-- cw_g9b2_05 — Vietnam lessons
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er den vigtigste lektie fra USA-engagementet i Vietnamkrigen?","options":["Militær overlegenhed garanterer ikke succes mod en modstandsbevægelse med stærk folkelig opbakning og ideologisk motivation","At Sovjet-støtten til Nordvietnam var den direkte årsag til USAs nederlag","At USA tabte fordi det aldrig brugte sin fulde militære kapacitet inklusive atomvåben","At atomvåben var den eneste effektive løsning men politikerne undlod at bruge dem"],"correct":"Militær overlegenhed garanterer ikke succes mod en modstandsbevægelse med stærk folkelig opbakning og ideologisk motivation","accepted_answers":["Militær overlegenhed garanterer ikke succes mod en modstandsbevægelse med stærk folkelig opbakning og ideologisk motivation"],"review_text":"USA var militært langt stærkere end Nordvietnam og tabte alligevel. Nordvietnameserne kæmpede for national befrielse — det var svært at bekæmpe med fly og bombefly. Vietnamkrigen viser at teknologisk og militær overlegenhed ikke erstatter folkelig sammenhæng."}'::jsonb,
  'mc','short','{"concepts":["Vietnamkrig","militær overlegenhed","folkelig opbakning","proxy-krig"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',2,'auto',true,'cold_war',9,2
);

-- cw_g9b2_06 — Moon landing significance
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betød USA''s månelanding i 1969 for Den Kolde Krigs ideologiske kamp?","options":["Det var en symbolsk sejr der demonstrerede at det demokratiske kapitalistiske system kunne mobilisere ressourcer og innovation og dermed vinde den ideologiske kamp","Det betød at USA nu teknisk set kunne placere atomvåben på Månen til trussel mod Sovjet","Det afsluttede rumkapløbet — begge sider indstillede derefter rumforskning","Det beviste at Sovjet-videnskab var underlegen i alle discipliner og alt teknologisk arbejde"],"correct":"Det var en symbolsk sejr der demonstrerede at det demokratiske kapitalistiske system kunne mobilisere ressourcer og innovation og dermed vinde den ideologiske kamp","accepted_answers":["Det var en symbolsk sejr der demonstrerede at det demokratiske kapitalistiske system kunne mobilisere ressourcer og innovation og dermed vinde den ideologiske kamp"],"review_text":"Neil Armstrongs skridt på Månen i 1969 var ikke blot teknologi — det var ideologisk budskab: frihed og kapitalisme kan opnå det umulige. Milliarder så det i TV. Sovjet nåede aldrig Månen. Som propaganda-sejr var det enorm."}'::jsonb,
  'mc','short','{"concepts":["månelanding","rumkapløb","ideologisk sejr","kapitalisme vs kommunisme"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',2,'auto',true,'cold_war',9,2
);

-- cw_g9b2_07 — Radio Free Europe / information war
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var Radio Free Europe og Voice of Americas rolle under Den Kolde Krig?","options":["De transmitterede vestlige nyheder og information til borgere i Østeuropa der ellers ikke havde adgang til frie medier — informationskrig via radiobølger","Stationerne programmerede primært musik uden politisk indhold for at fremme kulturel forståelse","De var primært rettet mod Sovjet-militær for at desinformere officererne","Radio Free Europe var et FN-initiativ for neutral kulturel udveksling"],"correct":"De transmitterede vestlige nyheder og information til borgere i Østeuropa der ellers ikke havde adgang til frie medier — informationskrig via radiobølger","accepted_answers":["De transmitterede vestlige nyheder og information til borgere i Østeuropa der ellers ikke havde adgang til frie medier — informationskrig via radiobølger"],"review_text":"Bag Jerntæppet var vestlige nyheder forbudte og statsmedierne kontrollerede alt. Radio Free Europe sendte nyheder og politisk analyse til millioner af østeuropæere. Østblokregeringerne jammede signalerne — men folk lyttede alligevel. Information var et våben."}'::jsonb,
  'mc','short','{"concepts":["Radio Free Europe","informationskrig","censur","Østeuropa","propaganda"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',2,'auto',true,'cold_war',9,2
);

-- ─── GRADE 9 · BAND 3 (7 questions) ─────────────────────────────────────────

-- cw_g9b3_01 — Cuba crisis consequences (hotline)
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var Cuba-krisens vigtigste konsekvens for hele verden efter at den var overstået?","options":["Bevidstheden om at atomkrig var muligt førte til den direkte hotline mellem Washington og Moskva — for at forhindre at en misforståelse udløste atomkrig","Cuba kom under permanent amerikansk militær kontrol som del af forliget","Sovjet gav afkald på alle sine atomvåben som betingelse for USA''s tilbagetrækning","FN overtog forvaltningen af alle fremtidige koldkrigs-konflikter"],"correct":"Bevidstheden om at atomkrig var muligt førte til den direkte hotline mellem Washington og Moskva — for at forhindre at en misforståelse udløste atomkrig","accepted_answers":["Bevidstheden om at atomkrig var muligt førte til den direkte hotline mellem Washington og Moskva — for at forhindre at en misforståelse udløste atomkrig"],"review_text":"Cuba-krisen lærte verden hvad det betød at stå på randen. Resultatet: en direkte hotline fra Washington til Moskva blev oprettet i 1963. Ingen ønskede at en teknisk fejl eller misforståelse skulle starte en atomkrig. Krisen skabte paradoksalt en marginalt sikrere verden."}'::jsonb,
  'mc','short','{"concepts":["Cuba-krisen","hotline","konsekvenser","atomkrig-forebyggelse","misconception-kun-Cuba"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"cold_war"}'::jsonb,
  'mc_single',3,'auto',true,'cold_war',9,3
);

-- cw_g9b3_02 — Communism theory vs practice
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forskellen på Karl Marx'' kommunistiske teori og den kommunisme Sovjet implementerede?","options":["Marx forestillede sig fælles ejerskab som befrielse af arbejderne — Sovjet-kommunisme blev et enpartidiktatur med statsejerskab og politisk undertrykkelse","De to var identiske — Marx designede specifikt Sovjet-systemet og Lenin fulgte planen nøje","Sovjet-kommunisme var faktisk tættere på kapitalisme end på Marx'' teori fordi staten ejede markedet","Marx ville ikke have anerkendt Sovjet som kommunistisk — men begge systemer var i princippet diktaturer"],"correct":"Marx forestillede sig fælles ejerskab som befrielse af arbejderne — Sovjet-kommunisme blev et enpartidiktatur med statsejerskab og politisk undertrykkelse","accepted_answers":["Marx forestillede sig fælles ejerskab som befrielse af arbejderne — Sovjet-kommunisme blev et enpartidiktatur med statsejerskab og politisk undertrykkelse"],"review_text":"Marx forestillede sig kommunisme som befrielse fra kapitalistisk udbytning — ikke diktatur og hemmelig politi. Lenin og Stalin formede teorien til noget vidt forskelligt. Ideologi og implementering kan divergere dramatisk. Det er en af historiens vigtigste lektioner."}'::jsonb,
  'mc','short','{"concepts":["Marx","kommunisme","Sovjet","teori vs praksis","misconception-kommunisme=diktatur"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"cold_war"}'::jsonb,
  'mc_single',3,'auto',true,'cold_war',9,3
);

-- cw_g9b3_03 — Cold War and culture
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad viser Den Kolde Krigs påvirkning på film, musik og litteratur?","options":["At konflikten ikke var begrænset til militær og politik — den formede hele kulturen med temaer om frygt, spionage, teknologisk fremtid og menneskelig frihed","At kun statssponsoreret propaganda-kunst var påvirket — al anden kultur var fri for politisk indflydelse","At Sovjet-kulturen var stærkt ideologisk påvirket men vestlig kultur forblev helt fri","At Den Kolde Krig knapt påvirkede kulturen — folk ignorerede i stor stil konflikten i hverdagen"],"correct":"At konflikten ikke var begrænset til militær og politik — den formede hele kulturen med temaer om frygt, spionage, teknologisk fremtid og menneskelig frihed","accepted_answers":["At konflikten ikke var begrænset til militær og politik — den formede hele kulturen med temaer om frygt, spionage, teknologisk fremtid og menneskelig frihed"],"review_text":"James Bond-film, Orwells 1984, Stanley Kubricks Dr. Strangelove, og rockmusikkens frigørelsesbudskab — alle formet af og reaktioner på Den Kolde Krig. Frygten for atomkrig og dobbelt-agenter prægede populærkulturen i årtier. Kulturen er historiens spejl."}'::jsonb,
  'mc','short','{"concepts":["kultur","film","litteratur","Kolde Krig","frygt"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"cold_war"}'::jsonb,
  'mc_single',3,'auto',true,'cold_war',9,3
);

-- cw_g9b3_04 — Nuclear deterrence: prevent or displace war?
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"En historiker hævder at atomvåben forhindrede krig under Den Kolde Krig. Hvad er den vigtigste indvending?","options":["Atomvåben forhindrede direkte krig MELLEM supermangterne — men proxy-krige der dræbte millioner fortsatte. Forhindret krig er et vestcentreret perspektiv","Påstanden er fuldstændig korrekt — ingen krige skete nogen steder i verden efter 1945","Atomvåben forhindrede slet ingen krige — konflikter fortsatte nøjagtig som de altid ville have gjort","Indvendingen er at atomvåben aldrig var en reel trussel og dermed ikke påvirkede noget"],"correct":"Atomvåben forhindrede direkte krig MELLEM supermangterne — men proxy-krige der dræbte millioner fortsatte. Forhindret krig er et vestcentreret perspektiv","accepted_answers":["Atomvåben forhindrede direkte krig MELLEM supermangterne — men proxy-krige der dræbte millioner fortsatte. Forhindret krig er et vestcentreret perspektiv"],"review_text":"MAD forhindrede USA og Sovjet i at angribe hinanden direkte. Men det skiftede krigen til proxy-konflikter: Korea, Vietnam, Angola, Afghanistan. Millioner af mennesker døde. Fra supermangts-perspektiv var det fred. Fra koreansk eller vietnamesisk perspektiv var det krig. Perspektiv afgør konklusionen."}'::jsonb,
  'mc','short','{"concepts":["atomafskrækkelse","proxy-krig","perspektiv","misconception-atomvåben-forhindrer-krig"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"cold_war"}'::jsonb,
  'mc_single',3,'auto',true,'cold_war',9,3
);

-- cw_g9b3_05 — Germany division and identity
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var den dybeste konsekvens af Tysklands deling i Øst og Vest for det tyske folk?","options":["To generationer voksede op i radikalt verschiedene politiske virkeligheder — og genforeningen i 1990 skabte ny kompleksitet da to fundamentalt different befolkninger mødtes","Delingen var primært symbolsk — begge tysklande fungerede i praksis identisk","Østtyskerne ønskede ikke genforening da de var godt tilfredse med kommunismen","Den tyske deling var planlagt som en midlertidig løsning der varede 2-3 år"],"correct":"To generationer voksede op i radikalt verschiedene politiske virkeligheder — og genforeningen i 1990 skabte ny kompleksitet da to fundamentalt different befolkninger mødtes","accepted_answers":["To generationer voksede op i radikalt verschiedene politiske virkeligheder — og genforeningen i 1990 skabte ny kompleksitet da to fundamentalt different befolkninger mødtes"],"review_text":"I vest: demokrati, velstand og rejsefrihed. I øst: enpartidiktatur, planøkonomi og Stasi-overvågning. Da Muren faldt og genforeningen kom, mødte to meget forskellige befolkninger hinanden. Ossi og Wessi stereotyper vidnede om de dybe skel der stadig eksisterer."}'::jsonb,
  'mc','short','{"concepts":["Tysklands deling","national identitet","genforening","Ossi Wessi"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"cold_war"}'::jsonb,
  'mc_single',3,'auto',true,'cold_war',9,3
);

-- cw_g9b3_06 — End of Cold War not instant (misconception)
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved forestillingen om at Den Kolde Krig pludselig sluttede da Berlinmuren faldt?","options":["Murens fald var dramatisk synligt — men årsagerne byggede sig op over årtier: Sovjet-økonomisvigt, Gorbatjovs reformer og folkeopstande i Østeuropa","Forestillingen er korrekt — Murens fald var den direkte og øjeblikkelige årsag til Den Kolde Krigs pludselige ophør","Muren faldt faktisk ikke spontant — det var et planlagt politisk arrangement","Berlinmuren faldt i 1985 under Reagan-Gorbatjov-topmødet — ikke i 1989"],"correct":"Murens fald var dramatisk synligt — men årsagerne byggede sig op over årtier: Sovjet-økonomisvigt, Gorbatjovs reformer og folkeopstande i Østeuropa","accepted_answers":["Murens fald var dramatisk synligt — men årsagerne byggede sig op over årtier: Sovjet-økonomisvigt, Gorbatjovs reformer og folkeopstande i Østeuropa"],"review_text":"Berlinmurens fald 9. november 1989 var dramatisk men ikke pludseligt. Sovjet-Unionens økonomi brød ned efter årtier. Katastrofekrigen i Afghanistan udtømte ressourcerne. Gorbatjovs reformer løsnede kontrollen. Folkeopstande fejede kommunistregimer i Polen og Ungarn. Muren var et effekt — ikke en årsag."}'::jsonb,
  'mc','short','{"concepts":["Kolde Krig afslutning","Berlinmur","Gorbatjov","misconception-øjeblikkelig slutning","kausalitet"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"cold_war"}'::jsonb,
  'mc_single',3,'auto',true,'cold_war',9,3
);

-- cw_g9b3_07 — Arms race economic costs on Soviet
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var atomkapløbets langsigtede konsekvens for Sovjet-Unionens økonomi?","options":["Atomkapløbet krævede en uforholdsmæssig andel af Sovjet-Unionens ressourcer som planøkonomien ikke kunne bære — og bidrog direkte til det endelige sammenbrud","Atomkapløbet var faktisk godt for Sovjet-Unionens økonomi fordi det skabte industriel vækst og eksportindtægter","USA brugte langt mere på atomvåben end Sovjet og det forklarede Sovjet-Unionens relative styrke","Atomkapløbet kostede begge lande nøjagtigt det samme i relative termer og favoriserede ingen"],"correct":"Atomkapløbet krævede en uforholdsmæssig andel af Sovjet-Unionens ressourcer som planøkonomien ikke kunne bære — og bidrog direkte til det endelige sammenbrud","accepted_answers":["Atomkapløbet krævede en uforholdsmæssig andel af Sovjet-Unionens ressourcer som planøkonomien ikke kunne bære — og bidrog direkte til det endelige sammenbrud"],"review_text":"Sovjet brugte en langt højere andel af sit BNP på militær end USA. En planøkonomi der prioriterede raketter over forbrugsgoder skabte mangler og utilfredshed. Atomkapløbet var ikke kun en sikkerhedsrisiko — det var en langsigtet dødsstraf for den sovjet-kommunistiske økonomi."}'::jsonb,
  'mc','short','{"concepts":["atomkapløb","Sovjet-økonomi","planøkonomi","Sovjet-sammenbrud","ressourcer"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"cold_war"}'::jsonb,
  'mc_single',3,'auto',true,'cold_war',9,3
);

-- ─── GRADE 9 · BAND 4 (5 questions) ─────────────────────────────────────────

-- cw_g9b4_01 — Moral complexity: neither side was right (misconception)
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er det mest historisk præcise svar på spørgsmålet om hvem der var den gode side i Den Kolde Krig?","options":["Ingen side var entydigt god — USA støttede diktaturer i Latinamerika og Asien; Sovjet undertrykte befolkninger og invaderede Ungarn og Tjekkoslovakiet. Begge retfærdiggjorde det ideologisk","USA var entydigt den gode side fordi det forsvarede demokrati og menneskeret globalt","Sovjet var den gode side fordi det forsvarede lighed og arbejdernes rettigheder mod kapitalisme","Det er et meningsløst spørgsmål — begge sider var identisk onde og bør ikke sammenlignes"],"correct":"Ingen side var entydigt god — USA støttede diktaturer i Latinamerika og Asien; Sovjet undertrykte befolkninger og invaderede Ungarn og Tjekkoslovakiet. Begge retfærdiggjorde det ideologisk","accepted_answers":["Ingen side var entydigt god — USA støttede diktaturer i Latinamerika og Asien; Sovjet undertrykte befolkninger og invaderede Ungarn og Tjekkoslovakiet. Begge retfærdiggjorde det ideologisk"],"review_text":"USA støttede korrupte diktatorer i Latinamerika og Asien når de var anti-kommunistiske. Sovjet knuste folkeopstande i Ungarn (1956) og Tjekkoslovakiet (1968). Begge parter brugte ideologi til at retfærdiggøre magtpolitik. En historiker stiller spørgsmål og holder begge sider ansvarlige."}'::jsonb,
  'mc','short','{"concepts":["moralsk kompleksitet","USA","Sovjet","misconception-USA-altid-rigtig","misconception-Sovjet-altid-rigtig"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',4,'auto',true,'cold_war',9,4
);

-- cw_g9b4_02 — Could the Cold War have been avoided?
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Var Den Kolde Krig uundgåelig efter 2. Verdenskrig — eller kunne den have været forhindret?","options":["Historikere er uenige: strukturalister siger modsatrettede interesser var uundgåelige; revisionister siger fejltagelser og misforståelser fra begge sider eskalerede konflikten unødigt","Den var helt uundgåelig — ideologiske modsætninger kræver altid krig og konfrontation","Den var fuldt undgåelig — Roosevelt og Stalin ville have fundet en fredsaftale hvis Roosevelt ikke var død","Den var uundgåelig alene fordi atombombens eksistens automatisk skaber konflikt"],"correct":"Historikere er uenige: strukturalister siger modsatrettede interesser var uundgåelige; revisionister siger fejltagelser og misforståelser fra begge sider eskalerede konflikten unødigt","accepted_answers":["Historikere er uenige: strukturalister siger modsatrettede interesser var uundgåelige; revisionister siger fejltagelser og misforståelser fra begge sider eskalerede konflikten unødigt"],"review_text":"Traditionalisterne siger Sovjet-ekspansion tvang USA til at reagere. Revisionisterne siger USA provokerede ved at omringe Sovjet og bruge atombombe-diplomati. Post-revisionisterne siger begge sider misforstod hinanden. Historien rummer ikke ét svar — men det er ikke det samme som at alle svar er lige gyldige."}'::jsonb,
  'mc','short','{"concepts":["Kolde Krig-oprindelse","historisk debat","uundgåelighed","strukturalisme","revisionisme"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',4,'auto',true,'cold_war',9,4
);

-- cw_g9b4_03 — How propaganda shaped both populations symmetrically
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var den dybeste lighed mellem USA-propaganda og Sovjet-propaganda under Den Kolde Krig?","options":["Begge skabte et forenklet verdensbillede — vi er de gode, de er de onde — og formede dermed hvad millioner af borgere troede var virkelighed","Begge brugte præcis de samme teknikker og medier til at sprede sit budskab til befolkningerne","USA-propaganda var faktuelt korrekt; Sovjet-propaganda var rent løgn — det var den vigtigste forskel","Begge lande afholdt sig fra at bruge propaganda mod egne borgere — kun mod den fjendtlige befolkning"],"correct":"Begge skabte et forenklet verdensbillede — vi er de gode, de er de onde — og formede dermed hvad millioner af borgere troede var virkelighed","accepted_answers":["Begge skabte et forenklet verdensbillede — vi er de gode, de er de onde — og formede dermed hvad millioner af borgere troede var virkelighed"],"review_text":"To-sidigt fjendbillede er effektiv propaganda. Begge systemer forenklede virkeligheden til os og dem. Det skabte befolkninger der var villige til at acceptere ofringer for at bekæmpe den onde fjende. Det gælder begge sider. Det er det mest foruroligende aspekt af propagandaens effektivitet."}'::jsonb,
  'mc','short','{"concepts":["propaganda","symmetri","befolkningskontrol","fjendbillede","begge sider"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',4,'auto',true,'cold_war',9,4
);

-- cw_g9b4_04 — Legacy of the Cold War today
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er Den Kolde Krigs vigtigste arv i verden i dag?","options":["Geopolitiske spændinger, kernevåbenprogrammer og alliancemønstre der alle direkte stammer fra Den Kolde Krig — inklusive NATO og delte nationer som Korea","Den Kolde Krig efterlod ingen varige spor — verden startede reelt på en blank side i 1991","Den primære arv er rumforskning og teknologi som GPS og internet — ikke politiske strukturer","Arven er primært kulturel — film og litteratur — men ingen politiske strukturer overlevede 1991"],"correct":"Geopolitiske spændinger, kernevåbenprogrammer og alliancemønstre der alle direkte stammer fra Den Kolde Krig — inklusive NATO og delte nationer som Korea","accepted_answers":["Geopolitiske spændinger, kernevåbenprogrammer og alliancemønstre der alle direkte stammer fra Den Kolde Krig — inklusive NATO og delte nationer som Korea"],"review_text":"NATO eksisterer. Nordkorea er stadig delt fra syd. Rusland og Vesten er stadig dybt mistroiske. Atomprogrammer eksisterer i mange lande. Den Kolde Krigs strukturer er ikke forsvundet — de er transformeret. 1991 var ikke et nyt kapitel; det var et afsnitsslut midt i en fortsat fortælling."}'::jsonb,
  'mc','short','{"concepts":["Kolde Krig arv","NATO","Korea","nutidig relevans","geopolitik"],"misconception_type":"temporal_confusion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',4,'auto',true,'cold_war',9,4
);

-- cw_g9b4_05 — Nuclear deterrence paradox (deepest synthesis)
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er det dybeste paradoks ved nuklear afskrækkelse som strategisk doktrin?","options":["Systemets effektivitet kræver at begge sider TROEDE på at den anden ville bruge atomvåben — men brugte de dem ville det betyde civilisationens undergang. Stabilitet baseret på troværdig irrationel trussel","Paradokset er at nuklear afskrækkelse er det eneste forsvarssystem der aldrig virker i praksis","Paradokset er at jo flere atomvåben man ejede desto svagere var man militært set","Der er intet paradoks — nuklear afskrækkelse er en rationel og simpel strategisk doktrin"],"correct":"Systemets effektivitet kræver at begge sider TROEDE på at den anden ville bruge atomvåben — men brugte de dem ville det betyde civilisationens undergang. Stabilitet baseret på troværdig irrationel trussel","accepted_answers":["Systemets effektivitet kræver at begge sider TROEDE på at den anden ville bruge atomvåben — men brugte de dem ville det betyde civilisationens undergang. Stabilitet baseret på troværdig irrationel trussel"],"review_text":"MAD kræver at truslen er troværdig: du skal overbevise fjenden om at du faktisk vil udslette jer begge. Men ingen rationel leder ville gøre det. Paradokset: rationelle ledere ville aldrig bruge atomvåben — og det er præcis det der gør truslen troværdig, fordi fjenden tror du måske er irrationel. En fascinerende og skræmmende logik."}'::jsonb,
  'mc','short','{"concepts":["nuklear afskrækkelse","MAD","paradoks","rationalitet","irrationel trussel"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',4,'auto',true,'cold_war',9,4
);
