-- Section 121 — Democracy & Power Band 1 Expansion Sprint
-- Eliminates the platform's only HIGH-risk beginner starvation point.
-- democracy_power had only 7 Band 1 questions (platform baseline: 12–18).
--
-- 6 questions: learning_objective='democracy_power', difficulty_band=1, target_grade=7
-- Topics: hvad er demokrati · hvorfor stemme · Folketing · love · borgerskab · kommunen
-- All questions: MC format, 4 options, full review_text, is_active=true
-- Uses dollar-quoting ($$) throughout.

-- ─── BAND 1 · DEMOKRATI & MAGT — 6 questions ────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er demokrati?","options":["Et system hvor borgerne vælger deres egne ledere og har indflydelse på de beslutninger der påvirker dem","Et system hvor én enkelt leder træffer alle beslutninger på vegne af befolkningen","Et system hvor kun de rigeste borgere har ret til at stemme og deltage i politik","Et system hvor militæret styrer landet og bestemmer hvem der må bo der"],"correct":"Et system hvor borgerne vælger deres egne ledere og har indflydelse på de beslutninger der påvirker dem","accepted_answers":["Et system hvor borgerne vælger deres egne ledere og har indflydelse på de beslutninger der påvirker dem"],"review_text":"Demokrati betyder folkestyre — fra de græske ord demos (folk) og kratos (styre). I et demokrati har borgerne ret til at stemme, ytre sig frit og vælge deres repræsentanter. Danmark er et parlamentarisk demokrati: vi vælger hvert fjerde år 179 medlemmer til Folketinget der laver vores love. Grundlæggende er magten hos folket — ikke hos en arvekonge, en religion eller en hær. Alternativerne i spørgsmålet beskriver autoritære styreformer som diktatur og militærjunta."}$$::jsonb,
  'mc','short',$${"concepts":["demokrati","folkestyre","valgret","repræsentation","Danmark"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"recognition","insight_type":"concept_clarification","challenge_role":"entry_level","domain":"democracy_power"}$$::jsonb,
  'mc_single',1,'auto',true,'democracy_power',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvorfor er det vigtigt at borgere stemmer ved valg?","options":["Fordi stemmeafgivning er den måde borgere vælger hvem der skal repræsentere dem og træffe beslutninger om love der påvirker alles liv","Fordi man straffes med bøde hvis man ikke møder op til stemmestedet","Fordi stemmeafgivning er den eneste måde man kan betale skat i Danmark","Fordi kun borgere der har stemt har ret til at modtage offentlige ydelser"],"correct":"Fordi stemmeafgivning er den måde borgere vælger hvem der skal repræsentere dem og træffe beslutninger om love der påvirker alles liv","accepted_answers":["Fordi stemmeafgivning er den måde borgere vælger hvem der skal repræsentere dem og træffe beslutninger om love der påvirker alles liv"],"review_text":"At stemme er den vigtigste demokratiske handling for den enkelte borger. Når du stemmer, vælger du hvem der skal sidde i Folketinget og repræsentere dine interesser. I Danmark er det frivilligt — du kan vælge ikke at stemme — men valgdeltagelse er afgørende for demokratiets legitimitet og for at alle grupper i samfundet bliver repræsenteret. Danmark har traditionelt meget høj valgdeltagelse (typisk 85–90%), hvilket er med til at give Folketinget stærk demokratisk legitimitet."}$$::jsonb,
  'mc','short',$${"concepts":["valg","valgdeltagelse","repræsentation","demokratisk legitimitet","Folketing"],"misconception_type":"factual_error","cognitive_skill":"comprehension","difficulty_type":"recognition","insight_type":"concept_clarification","challenge_role":"entry_level","domain":"democracy_power"}$$::jsonb,
  'mc_single',1,'auto',true,'democracy_power',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er Folketingets vigtigste opgave i det danske demokrati?","options":["At vedtage love og kontrollere regeringen på vegne af borgerne","At dømme kriminelle og afgøre retssager i hele landet","At lede det danske forsvar og beordre militære operationer","At administrere kommunernes daglige drift og lokale skoler"],"correct":"At vedtage love og kontrollere regeringen på vegne af borgerne","accepted_answers":["At vedtage love og kontrollere regeringen på vegne af borgerne"],"review_text":"Folketinget er Danmarks parlament med 179 folkevalgte medlemmer. Det har to kerneopgaver: at vedtage love og at kontrollere regeringen. Ingen lov træder i kraft uden Folketingets godkendelse — det er fundamentet i det parlamentariske demokrati. Domstolene (ikke Folketinget) afgør retssager. Forsvaret er under regeringens ledelse men Folketing bestemmer forsvarsbudgettet. Kommunerne klarer lokale velfærdsopgaver. At holde de tre statsmagter — lovgivende, udøvende og dømmende — adskilt beskytter mod magtmisbrug."}$$::jsonb,
  'mc','short',$${"concepts":["Folketing","lovgivning","parlamentarisme","magtens tredeling","regeringskontrol"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"recognition","insight_type":"concept_clarification","challenge_role":"entry_level","domain":"democracy_power"}$$::jsonb,
  'mc_single',1,'auto',true,'democracy_power',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvorfor har samfund brug for love?","options":["For at beskytte borgernes rettigheder, løse konflikter fredeligt og sikre at alle behandles retfærdigt uanset hvem de er","For at give politikere mulighed for at straffe borgere de er uenige med","Fordi alle love er lavet af kongen og skal følges ubetinget uden diskussion","For at forhindre borgere i at have egne meninger og ytringer"],"correct":"For at beskytte borgernes rettigheder, løse konflikter fredeligt og sikre at alle behandles retfærdigt uanset hvem de er","accepted_answers":["For at beskytte borgernes rettigheder, løse konflikter fredeligt og sikre at alle behandles retfærdigt uanset hvem de er"],"review_text":"Love er samfundets fælles spilleregler. Uden love ville magt og styrke afgøre konflikter — den svage ville ikke have beskyttelse mod den stærke. Love beskytter din frihed, din ejendom og din sikkerhed. I Danmark er det Folketinget — ikke kongen — der laver love. Kongen har kun en symbolsk ceremoniel rolle. Love gælder for alle, også politikere og politiet. Det kalder vi retsstat: ingen person eller institution er hævet over loven. Retsstaten er en af de vigtigste garantier for borgernes frihed."}$$::jsonb,
  'mc','short',$${"concepts":["love","retsstat","rettigheder","retfærdighed","Folketing"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"recognition","insight_type":"concept_clarification","challenge_role":"entry_level","domain":"democracy_power"}$$::jsonb,
  'mc_single',1,'auto',true,'democracy_power',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad kendetegner en borger i et demokrati?","options":["En person der har rettigheder som ytringsfrihed og stemmeret og samtidig har ansvar for at bidrage til og respektere fællesskabet","Kun personer der er født i landet og aldrig nogensinde har boet i et andet land","Kun voksne mænd der ejer jord og betaler en bestemt minimumsskat","En person der arbejder direkte for staten og udfører statslige opgaver"],"correct":"En person der har rettigheder som ytringsfrihed og stemmeret og samtidig har ansvar for at bidrage til og respektere fællesskabet","accepted_answers":["En person der har rettigheder som ytringsfrihed og stemmeret og samtidig har ansvar for at bidrage til og respektere fællesskabet"],"review_text":"En borger er et medlem af et samfund med både rettigheder og ansvar. I Danmark giver statsborgerskabet ret til at stemme ved valg, ytre sig frit og modtage hjælp fra velfærdsstaten. Men borgerskab indebærer også ansvar: at betale skat, følge lovene og bidrage til fællesskabet. Historisk set var valgret forbeholdt mænd med ejendom. I 1915 fik kvinder og tyende stemmeret i Danmark. I dag gælder universel stemmeret for alle danske statsborgere over 18 år — uanset køn, formue eller erhverv."}$$::jsonb,
  'mc','short',$${"concepts":["borger","rettigheder","ansvar","stemmeret","statsborgerskab"],"misconception_type":"overgeneralization","cognitive_skill":"comprehension","difficulty_type":"recognition","insight_type":"concept_clarification","challenge_role":"entry_level","domain":"democracy_power"}$$::jsonb,
  'mc_single',1,'auto',true,'democracy_power',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er kommunernes primære ansvar i det danske demokrati?","options":["At løse lokale velfærdsopgaver som folkeskoler, daginstitutioner, ældrepleje og lokale veje tæt på borgerne","At vedtage de nationale love og regler der gælder i hele landet","At dømme kriminelle sager og drive fængsler i lokalområdet","At opkræve moms og administrere den nationale indkomstskat for hele landet"],"correct":"At løse lokale velfærdsopgaver som folkeskoler, daginstitutioner, ældrepleje og lokale veje tæt på borgerne","accepted_answers":["At løse lokale velfærdsopgaver som folkeskoler, daginstitutioner, ældrepleje og lokale veje tæt på borgerne"],"review_text":"Danmark er opdelt i 98 kommuner. Kommunerne er ansvarlige for de nære velfærdsopgaver der berører dagligdagen: folkeskoler, børnehaver, ældrepleje, sociale tilbud og lokale veje. Princippet er nærhedsdemokrati — beslutninger tages tæt på borgerne så de let kan påvirke dem. Borgerne vælger kommunalbestyrelsen hvert fjerde år ved kommunalvalget. Nationale opgaver som politi, forsvar og universiteter klares af staten. Regionerne (5 i alt) er primært ansvarlige for sygehuse og sundhedsvæsen."}$$::jsonb,
  'mc','short',$${"concepts":["kommuner","nærhedsdemokrati","velfærdsopgaver","kommunalvalg","forvaltningsniveauer"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"recognition","insight_type":"concept_clarification","challenge_role":"entry_level","domain":"democracy_power"}$$::jsonb,
  'mc_single',1,'auto',true,'democracy_power',7,1
);
