-- Engelsk batch 2, 5. klasse bånd 1-2: 168 nye MC-spørgsmål (learning_objective='english', bånd 1-4).
-- Del af 1000 nye engelskspørgsmål til 3.-5. klasse. Samme indholds- og metadata-mønster som
-- 20261001000000_english_grade3_5; metadata afledes her af kategorinøglen k:
-- o=ordforråd, h=hverdagsudtryk, g=grammatik, l=læseforståelse. difficulty = bånd.
-- Bånd 1-2: reinforcement/conceptual_bridge. Bånd 3-4: challenge/reframing. All is_active=true.
-- Må KUN anvendes via apply_migration med særskilt ejer-autorisation (D-110).

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band)
SELECT
  jsonb_build_object('question', e->>'q', 'options', e->'o', 'correct', e->>'a',
                     'accepted_answers', jsonb_build_array(e->>'a'), 'review_text', e->>'r'),
  'mc', 'short',
  jsonb_build_object('concepts', jsonb_build_array(m.concept), 'cognitive_skill', m.skill,
                     'difficulty_type', m.dtype, 'misconception_type', m.mis,
                     'challenge_role', CASE WHEN (e->>'b')::int >= 3 THEN 'challenge' ELSE 'reinforcement' END,
                     'insight_type', CASE WHEN (e->>'b')::int >= 3 THEN 'reframing' ELSE 'conceptual_bridge' END,
                     'domain', 'english'),
  'mc_single', (e->>'b')::int, 'auto', true, 'english', (e->>'g')::int, (e->>'b')::int
FROM jsonb_array_elements($$[
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'history' som skolefag?","o":["geografi","samfundsfag","historie","religion"],"a":"historie","r":"'History' er historie. Geografi hedder 'geography'."},
{"g":5,"b":1,"k":"o","q":"Hvad hedder 'naturfag' på engelsk?","o":["nature","science","sport","art"],"a":"science","r":"Naturfag = science. 'Nature' betyder naturen."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'P.E.' på et engelsk skoleskema?","o":["idræt","fysik","engelsk","pause"],"a":"idræt","r":"P.E. står for 'physical education' — idræt."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'break' i skolen?","o":["brud","morgenmad","time","frikvarter"],"a":"frikvarter","r":"'Break' er frikvarter. 'Lunch break' er spisefrikvarter."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'pupil'?","o":["pige","lærer","elev","rektor"],"a":"elev","r":"'Pupil' betyder elev. Rektor hedder 'head teacher'."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'test'?","o":["tekst","prøve","tegning","træning"],"a":"prøve","r":"'Test' betyder prøve: 'We have a maths test tomorrow.'"},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'dictionary'?","o":["ordbog","dagbog","digt","lommeregner"],"a":"ordbog","r":"'Dictionary' betyder ordbog. Dagbog hedder 'diary'."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'diary'?","o":["mejeri","ordbog","dyrlæge","dagbog"],"a":"dagbog","r":"'Diary' betyder dagbog. 'Dairy' (med ai) betyder mejeri."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'England'?","o":["Irland","Skotland","England","Holland"],"a":"England","r":"'England' er England. Skotland = Scotland, Irland = Ireland."},
{"g":5,"b":1,"k":"o","q":"Hvad hedder 'Tyskland' på engelsk?","o":["Denmark","Germany","Norway","Holland"],"a":"Germany","r":"Tyskland = Germany. Danmark = Denmark."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'Sweden'?","o":["Sverige","Schweiz","Spanien","Skotland"],"a":"Sverige","r":"'Sweden' er Sverige. Schweiz hedder 'Switzerland'."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'Danish'?","o":["dansende","tysk","svensk","dansk"],"a":"dansk","r":"'Danish' betyder dansk: 'I speak Danish' = jeg taler dansk."},
{"g":5,"b":1,"k":"o","q":"Hvad hedder 'fransk' på engelsk?","o":["France","Finnish","French","Frank"],"a":"French","r":"Fransk = French. Frankrig hedder 'France'."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'coast'?","o":["kost","kyst","koste","kat"],"a":"kyst","r":"'Coast' betyder kyst. Danmark har en lang kyst."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'sky'?","o":["himmel","sky","skov","skib"],"a":"himmel","r":"'Sky' betyder himmel. En sky hedder 'cloud'."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'earth'?","o":["øre","hjerte","aske","jord eller Jorden"],"a":"jord eller Jorden","r":"'Earth' er jorden (planeten Jorden). Hjerte hedder 'heart'."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'thunder'?","o":["tunnel","tynd","torden","tusind"],"a":"torden","r":"'Thunder' betyder torden. Lyn hedder 'lightning'."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'storm'?","o":["stor","storm","strøm","sten"],"a":"storm","r":"'Storm' er det samme på engelsk og dansk."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'ice'?","o":["is (frossent vand)","is (dessert)","øje","ild"],"a":"is (frossent vand)","r":"'Ice' er frossent vand. Is som dessert hedder 'ice cream'."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'fire'?","o":["fire (tallet 4)","fyr","fejre","ild"],"a":"ild","r":"'Fire' betyder ild. Tallet fire hedder 'four'."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'leaf'?","o":["liv","løve","blad (på et træ)","lys"],"a":"blad (på et træ)","r":"'Leaf' er et blad. Flere blade = leaves."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'grass'?","o":["glas","græs","gris","grus"],"a":"græs","r":"'Grass' betyder græs. Glas hedder 'glass'."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'stone'?","o":["sten","stol","stor","stjerne"],"a":"sten","r":"'Stone' betyder sten."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'sand'?","o":["sandt","sang","sæbe","sand"],"a":"sand","r":"'Sand' er det samme ord på engelsk og dansk."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'wood'?","o":["uld","ord","træ (materiale) eller skov","væg"],"a":"træ (materiale) eller skov","r":"'Wood' er træ som materiale. 'The woods' kan også betyde skoven."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'screen'?","o":["skrig","skærm","skrue","skrin"],"a":"skærm","r":"'Screen' betyder skærm, f.eks. på en computer."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'keyboard'?","o":["tastatur","nøglebræt","klaver","kasse"],"a":"tastatur","r":"'Keyboard' er et tastatur. Det kan også være et elektrisk klaver."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'password'?","o":["pas","ordbog","brugernavn","adgangskode"],"a":"adgangskode","r":"'Password' er en adgangskode. Den skal du holde hemmelig!"},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'download'?","o":["lægge op","slette","hente ned","gemme"],"a":"hente ned","r":"'Download' betyder hente ned (fra internettet). 'Upload' betyder lægge op."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'message'?","o":["massage","besked","messe","mening"],"a":"besked","r":"'Message' betyder besked. 'Send me a message' = send mig en besked."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'photo'?","o":["foto","fod","fodbold","film"],"a":"foto","r":"'Photo' er et foto. 'Take a photo' = tage et billede."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'question'?","o":["svar","opgave","kø","spørgsmål"],"a":"spørgsmål","r":"'Question' betyder spørgsmål. Svar hedder 'answer'."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'answer'?","o":["spørgsmål","andet","svar","ånde"],"a":"svar","r":"'Answer' betyder svar eller at svare."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'idea'?","o":["ideal","idé","idiot","identitet"],"a":"idé","r":"'Idea' betyder idé."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'story'?","o":["historie (fortælling)","stor","storm","lager"],"a":"historie (fortælling)","r":"'Story' er en historie eller fortælling. Skolefaget historie hedder 'history'."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'problem'?","o":["program","prøve","pause","problem"],"a":"problem","r":"'Problem' er det samme ord på dansk og engelsk."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'money'?","o":["måned","mandag","penge","abe"],"a":"penge","r":"'Money' betyder penge. 'Monkey' er en abe."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'price'?","o":["præmie","pris","prins","ris"],"a":"pris","r":"'Price' betyder pris. Præmie hedder 'prize' — med z!"},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'right' i 'You are right'?","o":["rigtig (have ret)","højre","ret (mad)","rytme"],"a":"rigtig (have ret)","r":"'You are right' betyder du har ret. 'Right' kan også betyde højre."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'wrong'?","o":["ring","rund","rolig","forkert"],"a":"forkert","r":"'Wrong' betyder forkert."},
{"g":5,"b":1,"k":"h","q":"Hvad betyder 'Pleased to meet you'?","o":["Glæder mig til at se dig","Vi ses","Hyggeligt at møde dig","Mød mig her"],"a":"Hyggeligt at møde dig","r":"Man siger 'Pleased to meet you', når man hilser på en ny person."},
{"g":5,"b":1,"k":"h","q":"Hvad betyder 'Where are you from?'","o":["Hvor skal du hen?","Hvor kommer du fra?","Hvor bor du?","Hvor er du?"],"a":"Hvor kommer du fra?","r":"'From' betyder fra. Svar: 'I'm from Denmark.'"},
{"g":5,"b":1,"k":"h","q":"Hvad svarer man på 'Where are you from?'","o":["I'm from Denmark.","I'm Denmark.","I live from Denmark.","I from Denmark am."],"a":"I'm from Denmark.","r":"'I'm from …' = jeg kommer fra …"},
{"g":5,"b":1,"k":"h","q":"Hvad betyder 'Do you speak English?'","o":["Lærer du engelsk?","Er du englænder?","Kan du lide engelsk?","Taler du engelsk?"],"a":"Taler du engelsk?","r":"'Speak' betyder tale."},
{"g":5,"b":1,"k":"h","q":"Hvad betyder 'Sorry, I don't understand'?","o":["Undskyld, jeg hørte det ikke","Undskyld, jeg vil ikke","Undskyld, jeg forstår det ikke","Undskyld, jeg kan ikke stave"],"a":"Undskyld, jeg forstår det ikke","r":"'Understand' betyder forstå."},
{"g":5,"b":1,"k":"h","q":"Hvad betyder 'Enjoy your meal!'?","o":["Tak for mad!","Velbekomme!/God appetit!","Skål!","Spis op!"],"a":"Velbekomme!/God appetit!","r":"Man siger 'Enjoy your meal!' før man spiser — ligesom 'velbekomme' eller 'god appetit'."},
{"g":5,"b":1,"k":"h","q":"Hvad betyder 'Cheers!'?","o":["Skål!","Hurra!","Vi ses!","Velbekomme!"],"a":"Skål!","r":"'Cheers!' siger man, når man skåler. Briter bruger det også som 'tak' eller 'hej hej'."},
{"g":5,"b":1,"k":"h","q":"Hvad betyder 'Have a good weekend!'?","o":["God ferie!","Hav en god uge!","Vi ses i weekenden!","God weekend!"],"a":"God weekend!","r":"'Have a good weekend!' = god weekend!"},
{"g":5,"b":1,"k":"h","q":"Hvad betyder 'Congratulations!'?","o":["Kondolerer!","Godt nytår!","Tillykke!","Pas på!"],"a":"Tillykke!","r":"'Congratulations!' betyder tillykke."},
{"g":5,"b":1,"k":"h","q":"Hvad betyder 'Bless you!' (når nogen nyser)?","o":["Godt gået!","Prosit!","Pas på!","Hold op!"],"a":"Prosit!","r":"Når nogen nyser, siger man 'Bless you!' — ligesom 'prosit' på dansk."},
{"g":5,"b":1,"k":"h","q":"Hvad betyder 'I'm sorry to hear that'?","o":["Det er jeg ked af at høre","Undskyld, jeg hørte det ikke","Jeg vil ikke høre det","Det har jeg hørt før"],"a":"Det er jeg ked af at høre","r":"Man siger det, når nogen fortæller noget trist."},
{"g":5,"b":1,"k":"g","q":"Hvilket ord mangler? 'My parents ___ teachers.'","o":["is","am","be","are"],"a":"are","r":"'My parents' er flertal (de), så det er 'are'."},
{"g":5,"b":1,"k":"g","q":"Hvilket ord mangler? 'Everybody ___ happy today.'","o":["are","am","is","were"],"a":"is","r":"'Everybody' tæller som ental på engelsk: everybody is."},
{"g":5,"b":1,"k":"g","q":"Hvilket ord mangler? 'I ___ breakfast at 7 every day.'","o":["has","have","having","am have"],"a":"have","r":"Med 'I' hedder det 'have'. 'Have breakfast' = spise morgenmad."},
{"g":5,"b":1,"k":"g","q":"Hvilket ord mangler? 'He ___ his homework after school.'","o":["does","do","doing","dos"],"a":"does","r":"Med 'he' bliver 'do' til 'does'."},
{"g":5,"b":1,"k":"g","q":"Hvad er flertal af 'knife'?","o":["knifes","knifs","knive","knives"],"a":"knives","r":"Mange ord på -f eller -fe ændres til -ves: knife → knives."},
{"g":5,"b":1,"k":"g","q":"Hvad er flertal af 'leaf'?","o":["leafs","leafes","leaves","leaf"],"a":"leaves","r":"'Leaf' bliver til 'leaves' i flertal."},
{"g":5,"b":1,"k":"g","q":"Hvad er flertal af 'potato'?","o":["potatos","potatoes","potato","potaties"],"a":"potatoes","r":"Nogle ord på -o får -es: potato → potatoes."},
{"g":5,"b":1,"k":"g","q":"Hvad er flertal af 'sheep'?","o":["sheep","sheeps","shoop","sheepes"],"a":"sheep","r":"'Sheep' er det samme i ental og flertal: one sheep, ten sheep."},
{"g":5,"b":1,"k":"g","q":"Hvilket ord betyder 'dem'?","o":["they","their","there","them"],"a":"them","r":"'Them' betyder dem: 'I like them' = jeg kan lide dem."},
{"g":5,"b":1,"k":"g","q":"Hvilket ord mangler? 'Can you give ___ the ball?' (ham)","o":["he","his","him","her"],"a":"him","r":"'Him' betyder ham."},
{"g":5,"b":1,"k":"l","q":"Læs: 'My name is Sofia. I'm from Italy, but I live in Denmark.' Hvor kommer Sofia fra?","o":["Danmark","Italien","Spanien","Sverige"],"a":"Italien","r":"'I'm from Italy' = jeg kommer fra Italien. Hun bor (live) i Danmark."},
{"g":5,"b":1,"k":"l","q":"Læs: 'I have a brother. He is 15 and he plays basketball.' Hvilken sport dyrker broren?","o":["basketball","fodbold","håndbold","tennis"],"a":"basketball","r":"'He plays basketball' = han spiller basketball."},
{"g":5,"b":1,"k":"l","q":"Læs: 'Our school has 300 pupils and 25 teachers.' Hvor mange lærere er der?","o":["300","325","30","25"],"a":"25","r":"'25 teachers' = 25 lærere. 300 er antallet af elever (pupils)."},
{"g":5,"b":1,"k":"l","q":"Læs: 'Lucas loves reading, especially books about space.' Hvad læser Lucas helst om?","o":["dyr","sport","rummet","historie"],"a":"rummet","r":"'Space' betyder rummet (verdensrummet). 'Especially' betyder især."},
{"g":5,"b":1,"k":"l","q":"Læs: 'I usually walk to school, but today I took the bus.' Hvordan kom personen i skole i dag?","o":["til fods","med bus","på cykel","i bil"],"a":"med bus","r":"'Took the bus' = tog bussen. Normalt (usually) går personen."},
{"g":5,"b":1,"k":"l","q":"Læs: 'The weather is terrible. It's cold and it's raining.' Hvordan er vejret?","o":["forfærdeligt","fantastisk","varmt","solrigt"],"a":"forfærdeligt","r":"'Terrible' betyder forfærdeligt."},
{"g":5,"b":1,"k":"l","q":"Læs: 'Mum is a nurse. She works at night.' Hvornår arbejder mor?","o":["om morgenen","kun i weekenden","om eftermiddagen","om natten"],"a":"om natten","r":"'At night' betyder om natten."},
{"g":5,"b":1,"k":"l","q":"Læs: 'Eva's favourite season is autumn because she loves the colourful leaves.' Hvorfor kan Eva lide efteråret?","o":["fordi det sner","fordi det er varmt","på grund af de farverige blade","fordi hun har fødselsdag"],"a":"på grund af de farverige blade","r":"'Colourful leaves' = farverige blade."},
{"g":5,"b":1,"k":"l","q":"Læs: 'Jonas has got a new phone. It's black and it has a big screen.' Hvordan er telefonen?","o":["hvid med lille skærm","sort med stor skærm","sort med lille skærm","blå med stor skærm"],"a":"sort med stor skærm","r":"'Black' = sort, 'big screen' = stor skærm."},
{"g":5,"b":1,"k":"l","q":"Læs: 'We have English on Tuesdays and Thursdays.' Hvor mange gange om ugen har de engelsk?","o":["to","en","tre","fire"],"a":"to","r":"Tirsdag og torsdag = to gange om ugen."},
{"g":5,"b":1,"k":"l","q":"Læs: 'There are four people in my family: my mum, my dad, my sister and me.' Hvor mange søskende har personen?","o":["to","tre","fire","en"],"a":"en","r":"Personen har en søster. Mor og far er forældre."},
{"g":5,"b":1,"k":"l","q":"Læs: 'My dog is very old. He sleeps a lot and walks slowly.' Hvordan går hunden?","o":["hurtigt","meget","langsomt","aldrig"],"a":"langsomt","r":"'Slowly' betyder langsomt."},
{"g":5,"b":1,"k":"l","q":"Læs: 'Ida plays the guitar in a band with her friends.' Hvad gør Ida?","o":["synger i et kor","spiller guitar i et band","spiller klaver alene","danser med venner"],"a":"spiller guitar i et band","r":"'Plays the guitar in a band' = spiller guitar i et band."},
{"g":5,"b":1,"k":"l","q":"Læs: 'The shop sells fruit, vegetables and bread.' Hvad sælger butikken IKKE?","o":["tøj","frugt","grøntsager","brød"],"a":"tøj","r":"Butikken sælger frugt, grøntsager og brød — ikke tøj."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'cinema'?","o":["kiosk","sinke","teater","biograf"],"a":"biograf","r":"'Cinema' betyder biograf. Teater hedder 'theatre'."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'museum'?","o":["musik","mus","museum","marked"],"a":"museum","r":"'Museum' er det samme ord på dansk og engelsk."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'airport'?","o":["havn","lufthavn","luftballon","flystyrt"],"a":"lufthavn","r":"'Air' (luft) + 'port' (havn) = lufthavn."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'traffic lights'?","o":["lyskryds/trafiklys","billygter","gadelamper","trafikskilte"],"a":"lyskryds/trafiklys","r":"'Traffic lights' er trafiklys — rød, gul og grøn."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'corner'?","o":["korn","kone","kerne","hjørne"],"a":"hjørne","r":"'Corner' betyder hjørne: 'on the corner' = på hjørnet."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'healthy'?","o":["hellig","hel","sund","syg"],"a":"sund","r":"'Healthy' betyder sund: 'Vegetables are healthy.' Det modsatte er 'unhealthy'."},
{"g":5,"b":1,"k":"o","q":"Hvad betyder 'competition'?","o":["komposition","konkurrence","kompliment","koncert"],"a":"konkurrence","r":"'Competition' betyder konkurrence: 'She won the competition.'"},
{"g":5,"b":1,"k":"h","q":"Hvad betyder 'Excuse me, is this seat free?'","o":["Undskyld, er denne plads ledig?","Undskyld, er dette sæde gratis?","Undskyld, må jeg sidde ned?","Undskyld, hvor er min plads?"],"a":"Undskyld, er denne plads ledig?","r":"'Seat' betyder sæde/plads, og 'free' betyder her ledig."},
{"g":5,"b":1,"k":"l","q":"Læs: 'The bus was full, so Anna had to stand.' Hvorfor måtte Anna stå?","o":["Hun ville gerne stå","Bussen var forsinket","Hun skulle snart af","Bussen var fyldt"],"a":"Bussen var fyldt","r":"'Full' betyder fyldt. 'Had to' betyder måtte."},
{"g":5,"b":2,"k":"g","q":"Hvad er datid af 'get'?","o":["getted","gotted","gets","got"],"a":"got","r":"'Get' er uregelmæssig: get → got. 'I got a present' = jeg fik en gave."},
{"g":5,"b":2,"k":"g","q":"Hvad er datid af 'give'?","o":["gived","given","gave","gives"],"a":"gave","r":"'Give' er uregelmæssig: give → gave = gav."},
{"g":5,"b":2,"k":"g","q":"Hvad er datid af 'sing'?","o":["singed","sang","sung","songed"],"a":"sang","r":"'Sing' er uregelmæssig: sing → sang."},
{"g":5,"b":2,"k":"g","q":"Hvad er datid af 'run'?","o":["ran","runned","run","runs"],"a":"ran","r":"'Run' er uregelmæssig: run → ran = løb."},
{"g":5,"b":2,"k":"g","q":"Hvad er datid af 'sleep'?","o":["sleeped","slipped","sleeps","slept"],"a":"slept","r":"'Sleep' er uregelmæssig: sleep → slept = sov."},
{"g":5,"b":2,"k":"g","q":"Hvad er datid af 'say'?","o":["sayed","says","said","sad"],"a":"said","r":"'Say' er uregelmæssig: say → said = sagde."},
{"g":5,"b":2,"k":"g","q":"Hvad er datid af 'know'?","o":["knowed","knew","known","knows"],"a":"knew","r":"'Know' er uregelmæssig: know → knew = vidste."},
{"g":5,"b":2,"k":"g","q":"Hvad er datid af 'study'?","o":["studied","studyed","studid","studies"],"a":"studied","r":"Konsonant + y bliver til -ied i datid: study → studied."},
{"g":5,"b":2,"k":"g","q":"Hvad er datid af 'carry'?","o":["carryed","carred","carries","carried"],"a":"carried","r":"Konsonant + y bliver til -ied: carry → carried = bar."},
{"g":5,"b":2,"k":"g","q":"Hvilket ord mangler? 'Where ___ you go on holiday last year?'","o":["do","were","did","have"],"a":"did","r":"Spørgsmål i datid bruger 'did': Where did you go?"},
{"g":5,"b":2,"k":"g","q":"Hvilket ord mangler? 'She didn't ___ the answer.'","o":["knew","know","knows","known"],"a":"know","r":"Efter 'didn't' står verbet i grundform: didn't know."},
{"g":5,"b":2,"k":"g","q":"Hvilket ord mangler? 'What ___ you doing at 8 o'clock last night?'","o":["were","was","did","are"],"a":"were","r":"'You' bruger 'were' i datid: What were you doing? = hvad var du i gang med?"},
{"g":5,"b":2,"k":"g","q":"Hvilket ord mangler? 'He runs very ___.'","o":["quick","quicker","quickest","quickly"],"a":"quickly","r":"'Quickly' er et biord, der fortæller, hvordan han løber. Mange biord ender på -ly."},
{"g":5,"b":2,"k":"g","q":"Hvilket ord mangler? 'Please speak ___. The baby is sleeping.'","o":["quiet","quieter","quietly","quietest"],"a":"quietly","r":"Man taler 'quietly' (stille). Biordet fortæller, hvordan man taler."},
{"g":5,"b":2,"k":"g","q":"Hvilket ord mangler? 'She sings ___.' (godt)","o":["good","well","goodly","better than"],"a":"well","r":"Biordet af 'good' er 'well': She sings well."},
{"g":5,"b":2,"k":"g","q":"Hvad er biordet af 'happy'?","o":["happily","happyly","happly","happier"],"a":"happily","r":"Konsonant + y bliver til -ily: happy → happily = glad/lykkeligt."},
{"g":5,"b":2,"k":"g","q":"Hvilket ord mangler? 'There is ___ cheese in the fridge.' (noget)","o":["any","many","a few","some"],"a":"some","r":"I bekræftende sætninger bruger man 'some': There is some cheese."},
{"g":5,"b":2,"k":"g","q":"Hvilket ord mangler? 'I have ___ friends in my class.' (et par stykker)","o":["a little","much","a few","any"],"a":"a few","r":"'A few' bruges om ting, man kan tælle: a few friends = et par venner."},
{"g":5,"b":2,"k":"g","q":"Hvilket ord mangler? 'We only have ___ time left.' (lidt)","o":["a few","a little","many","few of"],"a":"a little","r":"'A little' bruges om noget, man ikke kan tælle, som tid: a little time."},
{"g":5,"b":2,"k":"g","q":"Hvilket ord mangler? 'I have lived here ___ 2020.'","o":["since","for","from","ago"],"a":"since","r":"'Since' bruges med et tidspunkt: since 2020 = siden 2020."},
{"g":5,"b":2,"k":"g","q":"Hvilket ord mangler? 'I have lived here ___ five years.'","o":["since","ago","in","for"],"a":"for","r":"'For' bruges med en tidsperiode: for five years = i fem år."},
{"g":5,"b":2,"k":"g","q":"Hvilket ord mangler? 'I saw him two days ___.'","o":["before","since","ago","for"],"a":"ago","r":"'Ago' betyder siden (tilbage i tid): two days ago = for to dage siden."},
{"g":5,"b":2,"k":"g","q":"Hvilket ord mangler? 'The cat jumped ___ the fence.'","o":["under","over","across from","between"],"a":"over","r":"'Over' betyder hen over: jumped over the fence."},
{"g":5,"b":2,"k":"g","q":"Hvilket ord mangler? 'The bank is ___ the post office and the shop.'","o":["between","behind","next","among"],"a":"between","r":"'Between' betyder mellem (to ting)."},
{"g":5,"b":2,"k":"g","q":"Hvilket ord mangler? 'This is the girl ___ lives next door.'","o":["which","what","where","who"],"a":"who","r":"'Who' bruges om personer: the girl who lives next door = pigen, der bor ved siden af."},
{"g":5,"b":2,"k":"g","q":"Hvilket ord mangler? 'This is the book ___ I told you about.'","o":["who","where","which","whose"],"a":"which","r":"'Which' bruges om ting: the book which … = bogen, som …"},
{"g":5,"b":2,"k":"o","q":"Hvad betyder 'get up'?","o":["komme op","stå op","stige op","få op"],"a":"stå op","r":"'Get up' betyder stå op (om morgenen)."},
{"g":5,"b":2,"k":"o","q":"Hvad betyder 'look for'?","o":["lede efter","se frem til","kigge på","passe på"],"a":"lede efter","r":"'Look for' betyder lede efter: I'm looking for my bag."},
{"g":5,"b":2,"k":"o","q":"Hvad betyder 'turn off' i 'Turn off the light'?","o":["tænd","drej","skift","sluk"],"a":"sluk","r":"'Turn off' betyder sluk. 'Turn on' betyder tænd."},
{"g":5,"b":2,"k":"o","q":"Hvad betyder 'put on' i 'Put on your coat'?","o":["tag af","læg fra dig","tag på","hæng op"],"a":"tag på","r":"'Put on' betyder tage på (tøj). 'Take off' betyder tage af."},
{"g":5,"b":2,"k":"o","q":"Hvad betyder 'give up'?","o":["give væk","give op","give tilbage","give en hånd"],"a":"give op","r":"'Give up' betyder give op: 'Don't give up!' = giv ikke op!"},
{"g":5,"b":2,"k":"o","q":"Hvad betyder 'wake up'?","o":["vågne","stå op og gå","vække","blive træt"],"a":"vågne","r":"'Wake up' betyder vågne. 'Wake me up' = væk mig."},
{"g":5,"b":2,"k":"o","q":"Hvad betyder 'find out'?","o":["finde vej","lede efter","gå ud","finde ud af"],"a":"finde ud af","r":"'Find out' betyder finde ud af."},
{"g":5,"b":2,"k":"o","q":"Hvad betyder 'grow up'?","o":["gro til","stå op","vokse op","blive gammel"],"a":"vokse op","r":"'Grow up' betyder vokse op. 'When I grow up' = når jeg bliver stor."},
{"g":5,"b":2,"k":"o","q":"Hvad betyder 'tidy up'?","o":["pynte op","rydde op","gøre klar","tørre op"],"a":"rydde op","r":"'Tidy up' betyder rydde op."},
{"g":5,"b":2,"k":"o","q":"Hvad betyder 'look after'?","o":["passe på","kigge efter","lede efter","se frem til"],"a":"passe på","r":"'Look after' betyder passe på: 'I look after my little brother.'"},
{"g":5,"b":2,"k":"o","q":"Hvilket ord betyder næsten det samme som 'small'?","o":["large","tall","huge","little"],"a":"little","r":"'Little' betyder også lille. 'Huge' betyder kæmpestor."},
{"g":5,"b":2,"k":"o","q":"Hvilket ord betyder næsten det samme som 'afraid'?","o":["brave","angry","scared","bored"],"a":"scared","r":"'Scared' og 'afraid' betyder begge bange."},
{"g":5,"b":2,"k":"o","q":"Hvilket ord betyder næsten det samme som 'end'?","o":["begin","finish","open","start"],"a":"finish","r":"'Finish' betyder slutte/afslutte, ligesom 'end'."},
{"g":5,"b":2,"k":"o","q":"Hvilket ord betyder næsten det samme som 'quick'?","o":["fast","slow","late","quiet"],"a":"fast","r":"'Fast' og 'quick' betyder begge hurtig."},
{"g":5,"b":2,"k":"o","q":"Hvad betyder 'huge'?","o":["hul","human","lillebitte","kæmpestor"],"a":"kæmpestor","r":"'Huge' betyder kæmpestor. Det modsatte er 'tiny'."},
{"g":5,"b":2,"k":"o","q":"Hvad betyder 'tiny'?","o":["tynd","tit","bitte lille","tyk"],"a":"bitte lille","r":"'Tiny' betyder bitte lille."},
{"g":5,"b":2,"k":"o","q":"Hvad betyder 'polite'?","o":["politi","høflig","politisk","populær"],"a":"høflig","r":"'Polite' betyder høflig. Det modsatte er 'rude' — uhøflig."},
{"g":5,"b":2,"k":"o","q":"Hvad betyder 'rude'?","o":["uhøflig","rude (glas)","rød","ru"],"a":"uhøflig","r":"'Rude' betyder uhøflig — en falsk ven! En rude hedder 'window pane'."},
{"g":5,"b":2,"k":"o","q":"Hvad betyder 'friendly'?","o":["venskab","fredelig","frisk","venlig"],"a":"venlig","r":"'Friendly' betyder venlig. 'Friend' betyder ven."},
{"g":5,"b":2,"k":"o","q":"Hvad betyder 'honest'?","o":["hest","hjemme","ærlig","høj"],"a":"ærlig","r":"'Honest' betyder ærlig. Man udtaler det uden h."},
{"g":5,"b":2,"k":"o","q":"Hvad betyder 'popular'?","o":["poppet","populær","pop-musik","pæn"],"a":"populær","r":"'Popular' betyder populær."},
{"g":5,"b":2,"k":"o","q":"Hvad betyder 'famous'?","o":["berømt","familie","fantastisk","farlig"],"a":"berømt","r":"'Famous' betyder berømt."},
{"g":5,"b":2,"k":"o","q":"Hvad betyder 'important'?","o":["importeret","umulig","stor","vigtig"],"a":"vigtig","r":"'Important' betyder vigtig."},
{"g":5,"b":2,"k":"o","q":"Hvad betyder 'possible'?","o":["umulig","positiv","mulig","passende"],"a":"mulig","r":"'Possible' betyder mulig. 'Impossible' betyder umulig."},
{"g":5,"b":2,"k":"h","q":"Hvad betyder 'What do you mean?'","o":["Hvad betyder det?","Hvad mener du?","Hvad hedder du?","Hvad vil du?"],"a":"Hvad mener du?","r":"'What do you mean?' = hvad mener du?"},
{"g":5,"b":2,"k":"h","q":"Hvad betyder 'It's not fair!'?","o":["Det er ikke retfærdigt!","Det er ikke pænt!","Det er ikke langt!","Det er ikke sjovt!"],"a":"Det er ikke retfærdigt!","r":"'Fair' betyder retfærdig."},
{"g":5,"b":2,"k":"h","q":"Hvad betyder 'That's a good point'?","o":["Det er et godt sted","Det er en god karakter","Det er en god blyant","Det er en god pointe"],"a":"Det er en god pointe","r":"'Point' betyder pointe eller argument."},
{"g":5,"b":2,"k":"h","q":"Hvad betyder 'I changed my mind'?","o":["Jeg har mistet hovedet","Jeg har glemt det","Jeg har skiftet mening","Jeg har lært det"],"a":"Jeg har skiftet mening","r":"'Change your mind' = skifte mening."},
{"g":5,"b":2,"k":"h","q":"Hvad betyder 'By the way'?","o":["Ved vejen","Forresten","På vej","Med det samme"],"a":"Forresten","r":"'By the way' bruges, når man vil sige noget nyt: forresten …"},
{"g":5,"b":2,"k":"h","q":"Hvad betyder 'Hang on a second'?","o":["Vent et øjeblik","Hæng den op","Hold fast i ét sekund","Om et sekund er det slut"],"a":"Vent et øjeblik","r":"'Hang on' betyder vent lidt."},
{"g":5,"b":2,"k":"h","q":"Hvad betyder 'Is it all right if I sit here?'","o":["Sidder jeg rigtigt her?","Er alt rigtigt her?","Må jeg sidde til højre?","Er det i orden, at jeg sidder her?"],"a":"Er det i orden, at jeg sidder her?","r":"'Is it all right if …?' = er det i orden, hvis …?"},
{"g":5,"b":2,"k":"h","q":"Hvad betyder 'Well done, you did it!'?","o":["Godt, du gjorde det færdigt i går!","Hvor er det godt lavet mad!","Godt gået, du klarede det!","Det var godt, du kom!"],"a":"Godt gået, du klarede det!","r":"'Well done' = godt gået, 'you did it' = du klarede det."},
{"g":5,"b":2,"k":"h","q":"Hvad betyder 'What's up?'","o":["Hvad er oppe?","Hvad så?/Hvordan går det?","Hvad sker der deroppe?","Hvad er klokken?"],"a":"Hvad så?/Hvordan går det?","r":"'What's up?' er en uformel hilsen: hvad så?"},
{"g":5,"b":2,"k":"h","q":"Hvad betyder 'No way!'?","o":["Aldrig i livet!/Det er ikke rigtigt!","Ingen vej!","Ikke den vej!","Nej tak!"],"a":"Aldrig i livet!/Det er ikke rigtigt!","r":"'No way!' betyder 'aldrig i livet!' eller 'det tror jeg ikke på!'"},
{"g":5,"b":2,"k":"l","q":"Læs: 'Last Saturday Mark went to a football match with his uncle. Their team lost 2-1.' Hvordan gik kampen for deres hold?","o":["De vandt","Uafgjort","Kampen blev aflyst","De tabte"],"a":"De tabte","r":"'Lost' er datid af 'lose' = tabte."},
{"g":5,"b":2,"k":"l","q":"Læs: 'Ella didn't eat her lunch because she wasn't hungry. Later she was very hungry.' Hvornår var Ella sulten?","o":["ved frokost","om morgenen","senere","aldrig"],"a":"senere","r":"'Later' betyder senere."},
{"g":5,"b":2,"k":"l","q":"Læs: 'The museum is open from 10 to 4 every day except Monday.' Hvilken dag er museet lukket?","o":["søndag","mandag","lørdag","fredag"],"a":"mandag","r":"'Except Monday' betyder undtagen mandag."},
{"g":5,"b":2,"k":"l","q":"Læs: 'Sam's grandfather grew up on a farm. He had to feed the pigs every morning before school.' Hvad skulle bedstefar gøre hver morgen?","o":["fodre grisene","malke køerne","gå tur med hunden","lave morgenmad"],"a":"fodre grisene","r":"'Feed the pigs' = fodre grisene."},
{"g":5,"b":2,"k":"l","q":"Læs: 'Lisa was so tired after the trip that she fell asleep on the sofa.' Hvad skete der med Lisa?","o":["Hun faldt ned fra sofaen","Hun gik i seng","Hun tog på tur","Hun faldt i søvn på sofaen"],"a":"Hun faldt i søvn på sofaen","r":"'Fell asleep' = faldt i søvn."},
{"g":5,"b":2,"k":"l","q":"Læs: 'Tom wanted to be a pilot when he was little. Now he is a doctor.' Hvad er Toms job nu?","o":["pilot","lærer","læge","landmand"],"a":"læge","r":"'Now he is a doctor' = nu er han læge."},
{"g":5,"b":2,"k":"l","q":"Læs: 'It took us three hours to drive to Copenhagen because there was a lot of traffic.' Hvorfor tog turen tre timer?","o":["De kørte forkert","Der var meget trafik","Bilen gik i stykker","De holdt pause"],"a":"Der var meget trafik","r":"'A lot of traffic' = meget trafik."},
{"g":5,"b":2,"k":"l","q":"Læs: 'Mia has two brothers. One is older than her, and one is younger.' Hvad passer?","o":["Mia har en storebror og en lillebror","Mia er ældst","Mia er yngst","Mia har to storebrødre"],"a":"Mia har en storebror og en lillebror","r":"En bror er ældre (older), og en er yngre (younger)."},
{"g":5,"b":2,"k":"l","q":"Læs: 'The new boy in class was shy at first, but now he talks to everybody.' Hvordan er den nye dreng nu?","o":["Han er stadig genert","Han taler med ingen","Han er flyttet","Han taler med alle"],"a":"Han taler med alle","r":"'Now he talks to everybody' = nu taler han med alle."},
{"g":5,"b":2,"k":"l","q":"Læs: 'We forgot to close the window, and the cat escaped.' Hvad skete der?","o":["Katten faldt ned","Katten kom ind","Katten slap ud","Vinduet gik i stykker"],"a":"Katten slap ud","r":"'Escaped' betyder slap ud."},
{"g":5,"b":2,"k":"l","q":"Læs: 'Ben doesn't like vegetables, except carrots.' Hvilken grøntsag kan Ben lide?","o":["ingen","gulerødder","alle","kartofler"],"a":"gulerødder","r":"'Except carrots' betyder undtagen gulerødder — dem kan han godt lide."},
{"g":5,"b":2,"k":"l","q":"Læs: 'The bakery sells 200 buns every morning, but on Sundays it sells twice as many.' Hvor mange boller sælger den om søndagen?","o":["400","200","100","300"],"a":"400","r":"'Twice as many' betyder dobbelt så mange: 2 x 200 = 400."},
{"g":5,"b":2,"k":"l","q":"Læs: 'Freja borrowed a book from the library. She must return it in two weeks.' Hvad skal Freja gøre?","o":["købe bogen","læse bogen på to dage","låne bogen ud","aflevere bogen om to uger"],"a":"aflevere bogen om to uger","r":"'Return' betyder aflevere tilbage."},
{"g":5,"b":2,"k":"l","q":"Læs: 'At the party there was music, games and a big chocolate cake. Everybody had a great time.' Hvordan var festen?","o":["Den var kedelig","Ingen kom","Alle hyggede sig","Den blev aflyst"],"a":"Alle hyggede sig","r":"'Had a great time' = havde det rigtig sjovt."},
{"g":5,"b":2,"k":"l","q":"Læs: 'Leo's alarm clock didn't ring, so he woke up late.' Hvorfor vågnede Leo sent?","o":["Han var syg","Vækkeuret ringede ikke","Han gik sent i seng","Det var weekend"],"a":"Vækkeuret ringede ikke","r":"'Alarm clock' = vækkeur. 'Didn't ring' = ringede ikke."},
{"g":5,"b":2,"k":"l","q":"Læs: 'Grandma always tells us stories about when she was a child.' Hvad handler historierne om?","o":["bedstemors barndom","eventyr","dyr","fremtiden"],"a":"bedstemors barndom","r":"'When she was a child' = da hun var barn."},
{"g":5,"b":2,"k":"l","q":"Læs: 'Most of the pupils walk to school, but a few come by bus.' Hvordan kommer de fleste elever i skole?","o":["De tager bussen","De cykler","De bliver kørt","De går"],"a":"De går","r":"'Most of the pupils walk' = de fleste elever går."},
{"g":5,"b":2,"k":"l","q":"Læs: 'The sign says: \"No dogs allowed\".' Hvad betyder skiltet?","o":["Hunde er velkomne","Pas på hunden","Hunde må ikke komme ind","Hunde skal i snor"],"a":"Hunde må ikke komme ind","r":"'Allowed' betyder tilladt. 'No dogs allowed' = hunde er ikke tilladt."},
{"g":5,"b":2,"k":"g","q":"Hvad er datid af 'break'?","o":["breaked","broke","broken","brake"],"a":"broke","r":"'Break' er uregelmæssig: break → broke = brækkede/ødelagde."},
{"g":5,"b":2,"k":"g","q":"Hvad er datid af 'leave'?","o":["left","leaved","leaft","leaves"],"a":"left","r":"'Leave' er uregelmæssig: leave → left = tog af sted/forlod."},
{"g":5,"b":2,"k":"o","q":"Hvad betyder 'pick up' i 'Mum picks me up after school'?","o":["samler op","vælger","ringer op","henter"],"a":"henter","r":"'Pick up' kan betyde hente (en person) eller samle noget op."},
{"g":5,"b":2,"k":"o","q":"Hvad betyder 'lucky'?","o":["lykkelig","lumsk","heldig","lunken"],"a":"heldig","r":"'Lucky' betyder heldig. 'Luck' betyder held."},
{"g":5,"b":2,"k":"h","q":"Hvad betyder 'Mind your head!'?","o":["Brug hovedet!","Pas på hovedet!","Tænk dig om!","Ryst på hovedet!"],"a":"Pas på hovedet!","r":"'Mind' kan betyde pas på: Mind your head! = pas på hovedet (f.eks. ved en lav dør)."},
{"g":5,"b":2,"k":"l","q":"Læs: 'Oscar spent all his money on sweets, so he couldn't buy a ticket for the cinema.' Hvorfor kunne Oscar ikke komme i biografen?","o":["Han havde brugt alle sine penge","Biografen var lukket","Han var syg","Filmen var udsolgt"],"a":"Han havde brugt alle sine penge","r":"'Spent all his money' = brugte alle sine penge."}
]$$::jsonb) AS e
JOIN (VALUES
  ('o', 'ordforråd', 'recall', 'factual', 'surface_association'),
  ('h', 'hverdagsudtryk', 'comprehension', 'conceptual', 'surface_association'),
  ('g', 'grammatik', 'application', 'applied', 'overgeneralization'),
  ('l', 'læseforståelse', 'analysis', 'inferential', 'surface_association')
) AS m(k, concept, skill, dtype, mis) ON m.k = e->>'k';
