-- Section 105 — Vikings Band 5 Sprint
-- Creates the first genuine ceiling layer for advanced grade-9 students in vikings.
-- Prior to this migration vikings had zero Band 5 questions (50 active across Bands 1-4).
--
-- 20 questions: target_grade=9, difficulty_band=5, domain=vikings, is_active=true
-- Focus: historiography, myth vs reality, Thing-democracy, slavery, women, violence ethics,
--        expansion motives, state formation, Christianisation, contemporary appropriation.
-- No factual recall. Every question requires evaluation, synthesis, or comparative reasoning.

-- ─── BAND 5 · HISTORIOGRAFI & VIKINGMYTEN (5 questions) ─────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er den afgørende fejl i den romantiserede vikingefremstilling der opstod i 1800-tallets nationalromantik — og hvad var dens politiske funktion?","options":["Fremstillingen projicerede moderne nationalistiske forestillinger om etnisk enhed og heroisk krigeridentitet tilbage på en heterogen handels- og jordbrugsbefolkning — og den tjente til at give nordeuropæiske nationalstater en glorværdig fortid der legitimerede territorial ekspansion og racetænkning","Fremstillingen var historiografisk korrekt men politisk uskyldig — den afspejlede blot ægte historisk stolthed uden ideologiske bagtanker","Vikingefremstillingen opstod i middelalderen og havde intet med 1800-tallets nationalisme at gøre","Romantiseringen var en akademisk fejltagelse uden politiske konsekvenser og er nu fuldt korrigeret i al undervisning"],"correct":"Fremstillingen projicerede moderne nationalistiske forestillinger om etnisk enhed og heroisk krigeridentitet tilbage på en heterogen handels- og jordbrugsbefolkning — og den tjente til at give nordeuropæiske nationalstater en glorværdig fortid der legitimerede territorial ekspansion og racetænkning","accepted_answers":["Fremstillingen projicerede moderne nationalistiske forestillinger om etnisk enhed og heroisk krigeridentitet tilbage på en heterogen handels- og jordbrugsbefolkning — og den tjente til at give nordeuropæiske nationalstater en glorværdig fortid der legitimerede territorial ekspansion og racetænkning"],"review_text":"1800-tallets nationalromantik — fra de tyske Romantikere til skandinavisk nationalisme — genopdagede vikingerne som grundlæggere af en overlegne nordisk race. Hornhjelm, Runerne og den heroiske krigerkultur var konstruktioner der passede til tidens politiske projekt. Nazisternes Ahnenerbe-program brugte systematisk vikingeikonografi. Problemet er dobbelt: for det første er det anakronistisk — vikinger var ikke ét folk med fælles national identitet. For det andet er det farligt — historisk mytedannelse kan bruges til at legitimere modernitetens vold. Arkæologi og DNA-forskning viser at det nordiske gen-pool var langt mere blandet end nationalister ønskede."}'::jsonb,
  'mc','short','{"concepts":["nationalromantik","vikingmyte","historiografi","anakronisme","racetænkning","politisk funktion"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"vikings"}'::jsonb,
  'mc_single',5,'auto',true,'vikings',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad afslører det faktum at ''viking'' i oldnordisk betegnede en aktivitet snarere end en etnisk eller kulturel identitet om risikoen ved historiske kategorier?","options":["At vi ukritisk overfører nutidige kategorier som etnicitet og nationalitet til fortiden — de fleste skandinaver i vikingetiden var bønder, handelsmænd og håndværkere der aldrig gik i viking, og begrebet var en beskrivelse af hvad man gjorde, ikke hvem man var","At vikinger faktisk var et særskilt folk med fælles sprog, religion og politisk organisation der adskiller dem klart fra andre middelalderfolk","At den sproglige distinktion er akademisk irrelevant fordi vikingernes identitet afspejles bedst i sagaernes selvforståelse","At moderne historikere bruger begrebet korrekt og den populærkulturelle brug er det eneste reelle problem"],"correct":"At vi ukritisk overfører nutidige kategorier som etnicitet og nationalitet til fortiden — de fleste skandinaver i vikingetiden var bønder, handelsmænd og håndværkere der aldrig gik i viking, og begrebet var en beskrivelse af hvad man gjorde, ikke hvem man var","accepted_answers":["At vi ukritisk overfører nutidige kategorier som etnicitet og nationalitet til fortiden — de fleste skandinaver i vikingetiden var bønder, handelsmænd og håndværkere der aldrig gik i viking, og begrebet var en beskrivelse af hvad man gjorde, ikke hvem man var"],"review_text":"Oldnordisk ''víkingr'' betegnede en person der gik på togt — det var en funktionel betegnelse, ikke en etnisk identifikation. En bonde der om vinteren blev hjemme og om sommeren tog på togt var viking i den ene aktivitet, bonde i den anden. Dette illustrerer det bredere historiografiske problem med anakronisme: vi tillægger fortiden vores tids kategorier. Etnisk identitet, national tilhørsforhold og kulturel kohærens er moderne begreber der ikke kan overføres ukritisk til middelalderens Skandinavien. Konsekvensen er at ''vikingsamfund'' som analytisk kategori kræver konstant kritisk opmærksomhed."}'::jsonb,
  'mc','short','{"concepts":["víkingr","anakronisme","etnisk kategori","historiografisk faldgrube","begrebshistorie","aktivitet vs identitet"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"vikings"}'::jsonb,
  'mc_single',5,'auto',true,'vikings',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad afslørede arabiske og frankiske primærkilder om vikingerne som skildrede dem udefra — og hvad er metodisk værdifuldt ved disse kilder sammenlignet med de nordiske sagaer?","options":["Udefra-kilderne tilbyder samtidige perspektiver uden idealisering: Ibn Fadlan beskrev Rus-vikingernes rituelle praksis med etnografisk præcision, frankiske annaler dokumenterede angrebenes destruktivitet uden at heroisere aktørerne — og de fortæller dermed noget andet end sagaerne der er nedskrevet 200-300 år efter begivenhederne","De arabiske og frankiske kilder er utroværdige fordi de var fjender af vikingerne og systematisk overdrev deres brutalitet","De nordiske sagaer er mere pålidelige end udenlandske kilder fordi de er skrevet af folk der kendte vikingernes kultur indefra","Alle samtidige primærkilder er metodisk utilstrækkelige og man bør udelukkende stole på arkæologiske fund"],"correct":"Udefra-kilderne tilbyder samtidige perspektiver uden idealisering: Ibn Fadlan beskrev Rus-vikingernes rituelle praksis med etnografisk præcision, frankiske annaler dokumenterede angrebenes destruktivitet uden at heroisere aktørerne — og de fortæller dermed noget andet end sagaerne der er nedskrevet 200-300 år efter begivenhederne","accepted_answers":["Udefra-kilderne tilbyder samtidige perspektiver uden idealisering: Ibn Fadlan beskrev Rus-vikingernes rituelle praksis med etnografisk præcision, frankiske annaler dokumenterede angrebenes destruktivitet uden at heroisere aktørerne — og de fortæller dermed noget andet end sagaerne der er nedskrevet 200-300 år efter begivenhederne"],"review_text":"Ibn Fadlans beretning (921-922) om Rus-vikingerne ved Volga er usædvanlig detaljeret og fri for heroisk idealisering — han var diplomat og observerede som etnograf. Frankiske annaler som Annales Regni Francorum dokumenterede angreb på Lindesfarne og Paris med stor præcision. De nordiske sagaer er til gengæld skrevet i 1200-1300-tallet om begivenheder fra 800-1000-tallet og er gennemsyret af litterære konventioner og genealogisk formål. Kildekritisk er samtidige udefra-perspektiver metodisk værdifulde netop fordi de mangler insiderens idealisering — selv om de til gengæld bærer egne fordomme."}'::jsonb,
  'mc','short','{"concepts":["Ibn Fadlan","frankiske annaler","kildekritik","sagaer","samtidige kilder","udefra-perspektiv"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"vikings"}'::jsonb,
  'mc_single',5,'auto',true,'vikings',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er det afgørende metodiske problem ved at bruge de islandske sagaer som historiske primærkilder om vikingetiden?","options":["Sagaerne er komponeret 200-400 år efter de begivenheder de skildrer, i en kristen litterær tradition, med genealogiske og politiske formål der forvrænger den historiske gengivelse — de er værdifulde som kulturelle tekster men kræver kritisk kildebrug som historisk dokumentation","Sagaerne er fuldstændig pålidelige fordi de bygger på mundtlig tradition der bevarer begivenheder præcist over generationer","Sagaerne er ubrugelige som historisk kildemateriale og bør udelukkende behandles som litterære fiktion","Problemet er rent sprogligt — moderne oversættelser mister detaljer men selve originalerne er fuldt pålidelige som historisk dokumentation"],"correct":"Sagaerne er komponeret 200-400 år efter de begivenheder de skildrer, i en kristen litterær tradition, med genealogiske og politiske formål der forvrænger den historiske gengivelse — de er værdifulde som kulturelle tekster men kræver kritisk kildebrug som historisk dokumentation","accepted_answers":["Sagaerne er komponeret 200-400 år efter de begivenheder de skildrer, i en kristen litterær tradition, med genealogiske og politiske formål der forvrænger den historiske gengivelse — de er værdifulde som kulturelle tekster men kræver kritisk kildebrug som historisk dokumentation"],"review_text":"Sagaerne er komponeret primært i 1200-1300-tallets Island af kristne forfattere der tolkede fortiden gennem en kristen etisk linse og forfølgede genealogiske formål — at legitimere familiers status og landes krav. Historikere som Sverre Bagge viser at sagaerne er primærkilder til 1200-tallets Islands selvforståelse snarere end til 800-tallets virkelighed. Det er ikke en diskvalifikation men en præcisering: sagaerne er kulturhistorisk uvurderlige men kræver triangulation med arkæologiske og samtidige skriftlige kilder. Blandingen af historisk kerne og litterær konstruktion er svær at adskille og det er netop kildekritikkens opgave."}'::jsonb,
  'mc','short','{"concepts":["sagaer","kildekritik","anakronisme","kristen kontekst","genealogi","mundtlig tradition"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"vikings"}'::jsonb,
  'mc_single',5,'auto',true,'vikings',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Er dikotomien ''fredelig handelsmand vs. voldelig raider'' en meningsfuld analytisk distinktion for vikingerne — eller er den historiografisk misvisende?","options":["Historiografisk misvisende — handel og plyndring var dele af det samme handelssystem hvor aktøren valgte strategi situationelt. De samme aktører handlede med ét samfund og plyndrede et andet afhængigt af modstanderens sårbarhed og handelsvilkårenes attraktivitet","Distinktionen er fuldt valid — handelsmænd og raidere var forskellige sociale grupper med klart adskilte aktiviteter og geografiske operationsområder","Distinktionen er korrekt men omvendt: vikingerne var primært raidere der lejlighedsvist handlede, ikke omvendt","Dikotomien er misvisende fordi vikingerne hverken handlede eller plyndrede — de var primært landmænd der sjældent forlod Skandinavien"],"correct":"Historiografisk misvisende — handel og plyndring var dele af det samme handelssystem hvor aktøren valgte strategi situationelt. De samme aktører handlede med ét samfund og plyndrede et andet afhængigt af modstanderens sårbarhed og handelsvilkårenes attraktivitet","accepted_answers":["Historiografisk misvisende — handel og plyndring var dele af det samme handelssystem hvor aktøren valgte strategi situationelt. De samme aktører handlede med ét samfund og plyndrede et andet afhængigt af modstanderens sårbarhed og handelsvilkårenes attraktivitet"],"review_text":"Arkæologiske fund fra Hedeby, Birka og Kaupang viser at de samme handelssteder modtog både handelsvarer fra øst og vest og tilstedeværelse af krigere. Neil Price og Judith Jesch viser at de samme aktører deltog i begge aktiviteter afhængigt af konteksten. I Byzans tjente norske væringegardister som elitetropper. I Bagdad handlede Rus-vikinger med arabiske købmænd. De plyndrede frankiske klostre der lå ved handelsruter de ikke kunne handle med. Strategien var adaptiv og situationsbestemt. Den binære opdeling er en moderne læsning der ikke stemmer med den faktiske kompleksitet."}'::jsonb,
  'mc','short','{"concepts":["handel","plyndring","adaptiv strategi","vikingøkonomi","historisk dikotomi","situationelt valg"],"misconception_type":"false_equivalence","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"vikings"}'::jsonb,
  'mc_single',5,'auto',true,'vikings',9,5
);

-- ─── BAND 5 · VIKINGSAMFUND, DEMOKRATI & ETIK (5 questions) ─────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Var Tingmøderne i vikingesamfundet en proto-demokratisk institution — eller var de primært oligarkiske forsamlinger der legitimerede stormænds magt?","options":["Primært oligarkiske: deltagelsesretten var i praksis begrænset til frie mænd med jord og social status, kvinder og trælle var ekskluderet, og de mænd der talte højest var dem med flest tilhængere og våben — Tinget fungerede som en konsensusmekanisme der legitimerede eliternes beslutninger","Fuldt demokratiske: alle voksne i samfundet deltog på lige fod og alle beslutninger var bundet af simpelt flertal uanset social status","Proto-demokratiske i moderne forstand: Tinget repræsenterede et system ækvivalent med nutidens parlamentariske demokrati og er en direkte forløber for dansk Folketing","Hverken oligarkisk eller demokratisk — Tinget var rent religiøst og havde ingen politisk funktion"],"correct":"Primært oligarkiske: deltagelsesretten var i praksis begrænset til frie mænd med jord og social status, kvinder og trælle var ekskluderet, og de mænd der talte højest var dem med flest tilhængere og våben — Tinget fungerede som en konsensusmekanisme der legitimerede eliternes beslutninger","accepted_answers":["Primært oligarkiske: deltagelsesretten var i praksis begrænset til frie mænd med jord og social status, kvinder og trælle var ekskluderet, og de mænd der talte højest var dem med flest tilhængere og våben — Tinget fungerede som en konsensusmekanisme der legitimerede eliternes beslutninger"],"review_text":"Tingmøderne er historisk fascinerende fordi de repræsenterede en form for regelbaseret konfliktløsning og deliberation i en tid domineret af kongemagt. Men at kalde dem proto-demokratiske kræver forsigtighed. Strukturelt var de ekskluderende: trælle (op til 10-20% af befolkningen), kvinder og løsgængere var ekskluderet. De stormænd der mødte op med flest thegner og mest prestige dominerede i praksis. Det er et mønster der ligner Atens demokrati mere end moderne universalstemmerets-demokrati. Distinktionen er vigtig: politisk deliberation eksisterer på et kontinuum, og vikingernes Ting var et markant fremskridt i middelalderlig kontekst uden at ligne moderne demokrati."}'::jsonb,
  'mc','short','{"concepts":["Ting","proto-demokrati","oligarki","deltagelse","eksklusioner","politisk deliberation"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"vikings"}'::jsonb,
  'mc_single',5,'auto',true,'vikings',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er den etiske konsekvens af at vikingernes ekspansion i vid udstrækning var finansieret af slavehandel — og hvordan komplicerer det den romantiserede fremstilling?","options":["Det underminerer enhver simpel heroisk fortælling: slavehandelen var central i vikingøkonomien, klostre og landsbyer blev plyndret primært for at skaffe trælle til salg i det arabiske og byzantinske marked — og dette placerer vikingerne i en brutal slaveriekonomis struktur der kræver etisk snarere end romantisk historisk analyse","Slaveriet var en marginal aktivitet uden central betydning for vikingernes økonomi og kan ikke bruges til at vurdere vikingsamfundet som helhed","Slaveriet var universelt i middelalderen og det fjerner ethvert etisk meningspunktuelt at fokusere på vikingernes brug deraf","Vikingernes slavehandel var mild sammenlignet med andre samfund og bør ikke tillægges moralsk vægt i historisk analyse"],"correct":"Det underminerer enhver simpel heroisk fortælling: slavehandelen var central i vikingøkonomien, klostre og landsbyer blev plyndret primært for at skaffe trælle til salg i det arabiske og byzantinske marked — og dette placerer vikingerne i en brutal slaveriekonomis struktur der kræver etisk snarere end romantisk historisk analyse","accepted_answers":["Det underminerer enhver simpel heroisk fortælling: slavehandelen var central i vikingøkonomien, klostre og landsbyer blev plyndret primært for at skaffe trælle til salg i det arabiske og byzantinske marked — og dette placerer vikingerne i en brutal slaveriekonomis struktur der kræver etisk snarere end romantisk historisk analyse"],"review_text":"Neil Price og David Wyatt viser at trællehandelen var en af vikingernes primære eksportprodukter. Irske, angelsaksiske, slaviske og frankiske fanger nåede markederne i Hedeby, Birka og videre til det arabiske Abbassid-kalifat og det byzantinske kejserriges tjeneste. Arabiske sølvmønter der strømmede nordpå var delvist betaling for menneskelig handel. At anerkende dette er ikke en moralsk dommerfælde men en historiografisk nødvendighed: vikingernes materielle civilisation hvilede delvist på et fundament af menneskelig udnyttelse. Romantiseringen udelader systematisk dette — og det gør den ikke blot upræcis men politisk manipulerbar."}'::jsonb,
  'mc','short','{"concepts":["slavehandel","trælle","vikingøkonomi","etisk analyse","romantisering","Price"],"misconception_type":"scope_confusion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"vikings"}'::jsonb,
  'mc_single',5,'auto',true,'vikings',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad viser arkæologiske og juridiske kilder om kvinders status i vikingesamfundet — og er den akademiske konsensus om relativ ligestilling velbegrundet?","options":["Delvist velbegrundet med vigtige forbehold: norrøn lovgivning gav gifte kvinder ret til skilsmisse, arv og forvaltning af husstand — og arkæologi viser gravgods der antyder social status. Men mænd dominerede politisk og militær sfære, og status varierede enormt med social klasse. Det var komparativt avanceret i middelalderlig kontekst men langt fra ligestilling i moderne forstand","Fuldt velbegrundet: vikingkvinder havde identisk status med mænd på alle samfundets områder inklusiv krigsførelse og politisk lederskab","Uholdbart: vikingkvinder var fuldstændig underkastet mandlig autoritet og havde ingen juridiske rettigheder","Spørgsmålet er ubesvareligt da vi mangler enhver kildetype der belyser kvinders faktiske status i vikingesamfundet"],"correct":"Delvist velbegrundet med vigtige forbehold: norrøn lovgivning gav gifte kvinder ret til skilsmisse, arv og forvaltning af husstand — og arkæologi viser gravgods der antyder social status. Men mænd dominerede politisk og militær sfære, og status varierede enormt med social klasse. Det var komparativt avanceret i middelalderlig kontekst men langt fra ligestilling i moderne forstand","accepted_answers":["Delvist velbegrundet med vigtige forbehold: norrøn lovgivning gav gifte kvinder ret til skilsmisse, arv og forvaltning af husstand — og arkæologi viser gravgods der antyder social status. Men mænd dominerede politisk og militær sfære, og status varierede enormt med social klasse. Det var komparativt avanceret i middelalderlig kontekst men langt fra ligestilling i moderne forstand"],"review_text":"Norrøn lovgivning er bemærkelsesværdig: kvinder kunne kræve skilsmisse ved mandens impotens, vold eller vanrøgt og beholde medgiften. Oseberg-skibet rummer to kvinder begravet med ekstraordinær rigdom. DNA-analysen af Birka-krigeren (2017 viste kromosomet XX) dokumenterede at kvinder deltog i militære ekspeditioner. Samtidig: lovgivning er ikke praksis. Konkrete kvindefigurer som Leif Erikssons søster Freydis er exceptionelle. Og skjaldkvinnerne der nævnes i sagaerne kan afspejle litterær idealisering snarere end typisk realitet. Den komparative vurdering — sammenligning med samtidige europæiske eller arabiske samfund — styrker billedet af relativ men ikke absolut avancement."}'::jsonb,
  'mc','short','{"concepts":["vikingkvinder","norrøn lov","Birka-krigeren","status","komparativ","arkæologi"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"vikings"}'::jsonb,
  'mc_single',5,'auto',true,'vikings',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Var den vold vikingerne udøvede mod klostre og landsbyer i Vesteuropa etisk anderledes end den vold der var almindelig i middelalderens øvrige krigsførelse?","options":["Primært ikke — volden var brutal men ikke systematisk anderledes end frankernes, angelsaksernes eller saracenernes krigsførelse i samme periode. Det der adskiller vikingerne er den geografiske rækkevidde, pludselighedens taktik og det faktum at de var hedenske angribere på kristen jord — hvilke skaber en skæv kildeproduktion der overdrev brutaliteten","Ja — vikingernes vold var fundamentalt anderledes og mere brutal end al samtidige krigsførelse i Europa","Nej — vikingernes angreb var faktisk de mildeste af middelalderens, da de undgik unødig drab og koncentrerede sig om plyndring af ejendom","Spørgsmålet er etisk illegitimt fordi middelalderlig vold ikke kan vurderes med etiske begreber"],"correct":"Primært ikke — volden var brutal men ikke systematisk anderledes end frankernes, angelsaksernes eller saracenernes krigsførelse i samme periode. Det der adskiller vikingerne er den geografiske rækkevidde, pludselighedens taktik og det faktum at de var hedenske angribere på kristen jord — hvilke skaber en skæv kildeproduktion der overdrev brutaliteten","accepted_answers":["Primært ikke — volden var brutal men ikke systematisk anderledes end frankernes, angelsaksernes eller saracenernes krigsførelse i samme periode. Det der adskiller vikingerne er den geografiske rækkevidde, pludselighedens taktik og det faktum at de var hedenske angribere på kristen jord — hvilke skaber en skæv kildeproduktion der overdrev brutaliteten"],"review_text":"Frankernes krigsførelse under Karl den Store involverede massakren på 4.500 saksere ved Verden (782) og tvangsomvendelse via sværdet. Angelsakserne og briterne bekrigede hinanden med sammenlignelig grusomhed. Problemet er kildeproduktionen: de eneste der systematisk dokumenterede vikingernes angreb var klostre — de primære mål — og de var ikke neutrale vidner. Middelalderens krigsførelse var generelt brutal og vikingernes angreb var effektive fordi de overraskede ubeskyttede kystsamfund, ikke fordi de var anomalt voldelige. Den etiske analyse kræver komparativ kontekst — og konteksten reducerer exceptionalistiske forklaringer."}'::jsonb,
  'mc','short','{"concepts":["middelalderlig vold","komparativ krigshistorie","kildeproduktion","kristen bias","klostre","kontekst"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"vikings"}'::jsonb,
  'mc_single',5,'auto',true,'vikings',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad afslører blodfejdesystemet i norrøn ret om forholdet mellem hævn, retfærdighed og social orden i vikingesamfundet?","options":["At blodfejden var en institutionaliseret mekanisme for konflikthåndtering i et samfund uden stærk central statsmagt — ikke kaotisk anarki men regelbaseret gengæld der opretholdt social balance, om end med høje menneskelige omkostninger. Overgangen til kongemagtsbaseret retspleje var en modernisering men ikke en simpel moralsk forbedring","Blodfejdesystemet var rent anarki uden regler — det var et lovløst system der var totalt inkompetent til at håndtere konflikter","Blodfejdesystemet var moralsk overlegent moderne statsbaseret retsvæsen fordi det gav familier direkte retfærdighed uden bureaukratisk formidling","Norrøne samfund brugte udelukkende Tingmøderne til konfliktløsning og blodfejden spillede ingen rolle i den sociale orden"],"correct":"At blodfejden var en institutionaliseret mekanisme for konflikthåndtering i et samfund uden stærk central statsmagt — ikke kaotisk anarki men regelbaseret gengæld der opretholdt social balance, om end med høje menneskelige omkostninger. Overgangen til kongemagtsbaseret retspleje var en modernisering men ikke en simpel moralsk forbedring","accepted_answers":["At blodfejden var en institutionaliseret mekanisme for konflikthåndtering i et samfund uden stærk central statsmagt — ikke kaotisk anarki men regelbaseret gengæld der opretholdt social balance, om end med høje menneskelige omkostninger. Overgangen til kongemagtsbaseret retspleje var en modernisering men ikke en simpel moralsk forbedring"],"review_text":"William Ian Miller viser i Bloodtaking and Peacemaking at den norrøne blodfejde var dybt reguleret: bøder (wergild) kunne erstatte hævn, mæglere deltog, og Tinget kunne sanktionere kompensation. Det var ikke anarki men et distribueret retssystem tilpasset et samfund med svag centralmagt. Overgangen til kongemagtsbaseret ret i 1000-1100-tallet medførte statsmonopol på vold — et fremskridt i institutionel rationalitet men også en afgivelse af familiers autonomi. Sammenligninger med andre pre-statslige retsformer — både historiske og antropologiske — bekræfter at distribueret retfærdighed er en logisk og kohærent løsning under visse strukturelle betingelser."}'::jsonb,
  'mc','short','{"concepts":["blodfejde","wergild","norrøn ret","konflikthåndtering","centralmagt","Miller"],"misconception_type":"causal_inversion","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"vikings"}'::jsonb,
  'mc_single',5,'auto',true,'vikings',9,5
);

-- ─── BAND 5 · VIKINGEKSPANSION & STATSFORMATION (4 questions) ───────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Var vikingernes ekspansion primært drevet af befolkningspres, knaphed på ressourcer, teknologisk overlegenhed eller politisk konkurrence i Skandinavien — og hvad er historiografiens konsensus?","options":["Multikausalt med tyngde på politisk konkurrence og konsolidering: stigende kongemagt i Norge og Danmark skabte tabere i den politiske kamp der søgte lykken udenfor, kombineret med skibsteknik der muliggjorde fjernekspansion og handel der skabte incitamenter. Ingen enkeltfaktor forklarer timingen tilstrækkeligt","Udelukkende befolkningspres — Skandinavien var overpopuleret og ekspansion var den eneste løsning på ressourceknaphed","Udelukkende teknologisk: skibsteknologien var den afgørende og tilstrækkelige forklaring på ekspansionens begyndelse og intensitet","Ekspansionen var tilfældig og opportunistisk uden strukturelle årsager der lader sig identificere historiografisk"],"correct":"Multikausalt med tyngde på politisk konkurrence og konsolidering: stigende kongemagt i Norge og Danmark skabte tabere i den politiske kamp der søgte lykken udenfor, kombineret med skibsteknik der muliggjorde fjernekspansion og handel der skabte incitamenter. Ingen enkeltfaktor forklarer timingen tilstrækkeligt","accepted_answers":["Multikausalt med tyngde på politisk konkurrence og konsolidering: stigende kongemagt i Norge og Danmark skabte tabere i den politiske kamp der søgte lykken udenfor, kombineret med skibsteknik der muliggjorde fjernekspansion og handel der skabte incitamenter. Ingen enkeltfaktor forklarer timingen tilstrækkeligt"],"review_text":"Anders Winroth og Neil Price peger på at én faktor alene ikke forklarer tidspunktet (ca. 793 ved Lindesfarne). Klimaoptimum i 750-1100 øgede produktiviteten. Longship-teknologien muliggjorde hurtige kystangreb. Arabisk handelsefterspørgsel skabte markeder for pelsværk, slaver og rav. Og den centrale faktor mange historikere fremhæver: konsolidering af kongemagt i Norge under Harald Hårfager og i Danmark under Gorm den Gamles efterfølgere skabte politiske tabere — stormænd og jarler der mistede status og søgte nye ressourcer udenlands. Multikausale forklaringer er metodisk stærkere end monokausalitet og afspejler historiske processer mere præcist."}'::jsonb,
  'mc','short','{"concepts":["vikingekspansion","årsager","multikausalt","kongemagt","skibsteknologi","Winroth"],"misconception_type":"causal_inversion","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"vikings"}'::jsonb,
  'mc_single',5,'auto',true,'vikings',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad afslører Rus-vikingernes rolle i grundlæggelsen af de første russiske fyrstendømmer om forholdet mellem invasion, handel og statsformation?","options":["At statsformation sjældent sker via ét folk alene: Varangierne/Rus skabte handelsruter og militær elitestruktur men de assimilerede sig hurtigt i slavisk kultur, sprog og religion — Kiev-Rus var fra starten et kulturelt hybridprojekt og Rurikid-dynastiet legitimerede sig via slavisk identitet snarere end nordisk","At Rus-vikingerne udelukkende grundlagde den russiske stat via militær erobring uden nogen form for kulturel integration","At Rus-vikingerne kun var handelsmænd uden politisk indflydelse og at de slaviske folk alene grundlagde de russiske stater","At spørgsmålet om vikingernes rolle i russisk statsformation er et politisk betændt emne der ikke kan besvares historisk"],"correct":"At statsformation sjældent sker via ét folk alene: Varangierne/Rus skabte handelsruter og militær elitestruktur men de assimilerede sig hurtigt i slavisk kultur, sprog og religion — Kiev-Rus var fra starten et kulturelt hybridprojekt og Rurikid-dynastiet legitimerede sig via slavisk identitet snarere end nordisk","accepted_answers":["At statsformation sjældent sker via ét folk alene: Varangierne/Rus skabte handelsruter og militær elitestruktur men de assimilerede sig hurtigt i slavisk kultur, sprog og religion — Kiev-Rus var fra starten et kulturelt hybridprojekt og Rurikid-dynastiet legitimerede sig via slavisk identitet snarere end nordisk"],"review_text":"Den normanniske teori (at vikingerne grundlagde Rus) og anti-normanismen (at slaverne alene skabte staten) er begge historiografisk reducerende. DNA-analyser af Rurikid-dynastiets graver viser nordisk genetik i lederskabseliten. Men Nestorkrønikens beretning om at slaverne kaldte varangierne til styre er sandsynligvis delvist propaganda. Det afgørende er at assimilationen var hurtig: Olga og Vladimir den Store (900-tallet) bar slaviske navne og Vladimir valgte ortodoks kristendom fra Byzans som dynastisk religion. Kiev-Rus er et historisk eksempel på at statsformation er en hybrid proces — og at etnisk enkelhed er en anachronistisk konstruktion."}'::jsonb,
  'mc','short','{"concepts":["Rus-vikinger","Kiev-Rus","statsformation","kulturel hybriditet","Rurikid","assimilation"],"misconception_type":"false_equivalence","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"vikings"}'::jsonb,
  'mc_single',5,'auto',true,'vikings',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad illustrerer normannernes hurtige kulturelle assimilation i Nordfrankrig — fra nordiske vikinger til franske vasaller — om forholdet mellem kulturel identitet og politisk tilpasning?","options":["At kulturel identitet er formbar og politisk motiveret: Rollons vikinger adopterede frankisk sprog, kristendommen og feudale strukturer inden for to generationer fordi integration i det frankiske system gav politisk legitimitet og adgang til rigdom. Identitet er ikke essentiel men strategisk og adaptiv","At normannerne bevarede deres nordiske identitet fuldstændigt og at Normandiet forblev en skandinavisk enklav i Frankrig frem til 1066","At assimilation var ufrivillig og påtvunget af frankisk overmagt — normannerne assimilerede ikke frivilligt men under tvang","At normannernes hurtighed i assimilation beviser at vikingerne ikke havde nogen reel kulturel identitet at miste"],"correct":"At kulturel identitet er formbar og politisk motiveret: Rollons vikinger adopterede frankisk sprog, kristendommen og feudale strukturer inden for to generationer fordi integration i det frankiske system gav politisk legitimitet og adgang til rigdom. Identitet er ikke essentiel men strategisk og adaptiv","accepted_answers":["At kulturel identitet er formbar og politisk motiveret: Rollons vikinger adopterede frankisk sprog, kristendommen og feudale strukturer inden for to generationer fordi integration i det frankiske system gav politisk legitimitet og adgang til rigdom. Identitet er ikke essentiel men strategisk og adaptiv"],"review_text":"Rollo fik Normandiet af den franske kong Karl den Enkle i 911 og hans efterkommere adopterede oldfransk som primært sprog inden for et halvt århundrede. William Erobreren (d. 1087) — Rollons oldesøn — talte primært normannisk-fransk og tænkte sandsynligvis ikke på sig selv som nordisk. Assimilationen var ikke tvungen men pragmatisk: frankisk retssystem, kirkestruktur og feudalhierarki tilbød administrativ effektivitet og legitimitet som den norrøne struktur ikke kunne matche i en statslig kontekst. Eksemplet illustrerer at kulturelle identiteter ikke er statiske essenser men relationelle konstruktioner der tilpasser sig politiske og sociale incitamenter."}'::jsonb,
  'mc','short','{"concepts":["normannerne","assimilation","kulturel identitet","Rollo","Normandiet","politisk tilpasning"],"misconception_type":"false_equivalence","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"vikings"}'::jsonb,
  'mc_single',5,'auto',true,'vikings',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er den mest præcise karakteristik af vikingernes indflydelse på England — erobring, kulturel hybridisering eller noget mere komplekst?","options":["Kulturel hybridisering over tid: Danelagen etablerede nordisk ret og sprog i store dele af England, men angelsaksisk og nordisk kultur blandede sig i stedet for at erstatte hinanden — og Knud den Stores rige (1016-1035) viste at nordiske herskere regerede via angelsaksiske institutioner snarere end at erstatte dem","Ren militær erobring: vikingerne erstattede fuldstændigt angelsaksisk kultur med nordisk i alle erobrede områder","Minimal indflydelse: vikingernes tilstedeværelse i England var kortvarig og overfladisk og efterlod ingen varige spor i sprog, ret eller kultur","Ensidig kulturel assimilation: angelsakserne assimilerede fuldstændigt de nordiske indvandrere inden for én generation"],"correct":"Kulturel hybridisering over tid: Danelagen etablerede nordisk ret og sprog i store dele af England, men angelsaksisk og nordisk kultur blandede sig i stedet for at erstatte hinanden — og Knud den Stores rige (1016-1035) viste at nordiske herskere regerede via angelsaksiske institutioner snarere end at erstatte dem","accepted_answers":["Kulturel hybridisering over tid: Danelagen etablerede nordisk ret og sprog i store dele af England, men angelsaksisk og nordisk kultur blandede sig i stedet for at erstatte hinanden — og Knud den Stores rige (1016-1035) viste at nordiske herskere regerede via angelsaksiske institutioner snarere end at erstatte dem"],"review_text":"Danelagen — det nordisk-kontrollerede område af England fra ca. 878 — efterlod varige spor: over 600 stednavne på -by, -thorpe og -thwaite i Nordengland er af nordisk oprindelse. Det engelske sprog optog hundredvis af nordiske ord (sky, window, egg, husband). Men Knud den Store er det mest illustrative eksempel på hybridisering: han regerede England som angelsaksisk monark, støttede den engelske kirke, udgav angelsaksisk-baseret lovgivning og anså sig selv som legitimt angelsaksisk dynasti. Den nordiske og angelsaksiske kultur blandede sig produktivt snarere end at den ene udslettede den anden."}'::jsonb,
  'mc','short','{"concepts":["Danelagen","kulturel hybridisering","Knud den Store","angelsaksisk","nordisk indflydelse","sproglig arv"],"misconception_type":"false_equivalence","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"vikings"}'::jsonb,
  'mc_single',5,'auto',true,'vikings',9,5
);

-- ─── BAND 5 · RELIGION, VERDENSANSKUELSE & SAMMENLIGNING (3 questions) ───────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad afslører den norrøne mytologis tragiske verdensbillede — Ragnarok og gudernes endelighed — om de værdier vikingesamfundet anerkendte og beundrede?","options":["At tapperhed og ære i mødet med det uundgåelige var kulturens centrale etiske imperativ: guderne vidste at Ragnarok kom og kæmpede alligevel — dette understreger et handlingsorienteret mod der ikke hviler på forventningen om ultimativ sejr men på handlingens integritet i sig selv","At norrøn religion var pessimistisk og frembragte en fatalistisk mentalitet der forhindrede social og kulturel fremgang","At Ragnarok-myten var ren underholdning uden etisk dimension og ikke afspejlede vikingernes faktiske værdier","At norrøn religion var identisk med nordisk shamanisme og ikke kan sammenlignes med andre religiøse traditioners etik"],"correct":"At tapperhed og ære i mødet med det uundgåelige var kulturens centrale etiske imperativ: guderne vidste at Ragnarok kom og kæmpede alligevel — dette understreger et handlingsorienteret mod der ikke hviler på forventningen om ultimativ sejr men på handlingens integritet i sig selv","accepted_answers":["At tapperhed og ære i mødet med det uundgåelige var kulturens centrale etiske imperativ: guderne vidste at Ragnarok kom og kæmpede alligevel — dette understreger et handlingsorienteret mod der ikke hviler på forventningen om ultimativ sejr men på handlingens integritet i sig selv"],"review_text":"Norrøn kosmologi er præget af et tragisk element uden parallel i kristen eller islamisk eskatologi: guderne er dødelige og ved at de vil tabe den endelige kamp. Odin samler einherjer i Valhalla ikke for at skabe en uovervindelig hær men fordi det er den rigtige ting at gøre. Denne struktur fremhæver handlingens integritet frem for konsekvensens optimisme. Sammenligning med kristen eskatologi (frelst vs. fortabt, Dommedag med guddommelig sejr) er oplysende: norrøn etik er ikke baseret på belønning og straf i det hinsides men på ærens krav i nuet. Det er en bemærkelsesværdig etisk konstruktion der har sammenligningspunkter med stoisk filosofi."}'::jsonb,
  'mc','short','{"concepts":["Ragnarok","norrøn etik","tragisk verdensanskuelse","ære","stoicisme","handlingens integritet"],"misconception_type":"scope_confusion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"vikings"}'::jsonb,
  'mc_single',5,'auto',true,'vikings',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Var skandinavernes overgang til kristendommen i 900-1100-tallet primært drevet af religiøs overbevisning, politisk kalkule eller handelsmæssige fordele?","options":["Primært politisk kalkule og handelsmæssige fordele: kristendommen gav adgang til det europæiske diplomatiske netværk, legitimerede kongemagt via kirkelig sakramentering, og kristne handelsbyer foretrak kristne samhandelspartnere — religiøs overbevisning var tilstede men næppe den afgørende drivkraft for de politiske lederes konversion","Udelukkende religiøs overbevisning: skandinaviske konger konverterede fordi de var overbevist om kristendommens teologiske sandhed","Udelukkende politisk tvang: alle skandinaver konverterede under frankisk og engelsk militært pres uden nogen frivillig dimension","Overgangen var gradvis og harmonisk og kristendommen fortrængte fuldstændigt den norrøne religion uden nogen form for synkretisme eller konflikt"],"correct":"Primært politisk kalkule og handelsmæssige fordele: kristendommen gav adgang til det europæiske diplomatiske netværk, legitimerede kongemagt via kirkelig sakramentering, og kristne handelsbyer foretrak kristne samhandelspartnere — religiøs overbevisning var tilstede men næppe den afgørende drivkraft for de politiske lederes konversion","accepted_answers":["Primært politisk kalkule og handelsmæssige fordele: kristendommen gav adgang til det europæiske diplomatiske netværk, legitimerede kongemagt via kirkelig sakramentering, og kristne handelsbyer foretrak kristne samhandelspartnere — religiøs overbevisning var tilstede men næppe den afgørende drivkraft for de politiske lederes konversion"],"review_text":"Harald Blåtand konverterede ca. 965 og beskrev sig selv på Jellingestenen som den der ''vandt sig al Danmark og Norge og gjorde danerne kristne''. Konversionen fulgte nøje diplomatiske kontakter med det tyske rige og gav Harald legitimitet i forhold til den europæiske orden. Handel i Dorestad og Hamborg forudsatte i praksis kristen dåb. Olav Tryggvason og Olav Haraldsson (Olav den Hellige) brugte omvendt kristendommen til at centralisere kongemagten i Norge. Synkretismen i overgangsfasen — norrøne motiver på kors, Tor-hammer kombineret med kors — viser at religiøs overbevisning var mere gradvis end de politiske beslutninger antydede."}'::jsonb,
  'mc','short','{"concepts":["kristendom","konversion","politisk kalkule","handel","Harald Blåtand","synkretisme"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"vikings"}'::jsonb,
  'mc_single',5,'auto',true,'vikings',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad viser vikingernes handelsnetværk — fra Newfoundland i vest til Bagdad i øst — om middelalderlig globalitet og vor tids antagelse om at globalisering er et moderne fænomen?","options":["At langdistancehandel, kulturudveksling og migrationsbevægelser er fundamentalt pre-moderne fænomener: vikingernes netværk forbandt den nordatlantiske kyst med det arabiske Abbassid-kalifat og Byzantium via Silkevejen og Flodruterne. Globalisering er ikke skabt af modernitet men er snarere et tilbagevendende historisk mønster i varierende intensitet","At middelalderens handelsnetværk var så begrænsede at de ikke kan sammenlignes med moderne globalisering og enhver sammenligning er analytisk meningsløs","At vikingerne var de eneste der foretog langdistancehandel i middelalderen og at alle andre civilisationer var isolerede","At globaliseringen er et fuldstændig nyt fænomen skabt af industrialismens infrastruktur og ikke har historiske forstadier"],"correct":"At langdistancehandel, kulturudveksling og migrationsbevægelser er fundamentalt pre-moderne fænomener: vikingernes netværk forbandt den nordatlantiske kyst med det arabiske Abbassid-kalifat og Byzantium via Silkevejen og Flodruterne. Globalisering er ikke skabt af modernitet men er snarere et tilbagevendende historisk mønster i varierende intensitet","accepted_answers":["At langdistancehandel, kulturudveksling og migrationsbevægelser er fundamentalt pre-moderne fænomener: vikingernes netværk forbandt den nordatlantiske kyst med det arabiske Abbassid-kalifat og Byzantium via Silkevejen og Flodruterne. Globalisering er ikke skabt af modernitet men er snarere et tilbagevendende historisk mønster i varierende intensitet"],"review_text":"Arkæologiske fund bekræfter netværkets rækkevidde: arabiske dirhammer i skandinaviske grave, nordisk rav og pelsværk i Bagdad, byzantinsk silke i Birka, nordamerikanske basaltvægte i Island. Volga-Rus-ruterne forbandt Skandinavien med det Kaspiske Hav og det arabiske marked. Silkevejen, Indisk Ocean-handlen og mongolernes pax mongolica viser at pre-moderne langdistancehandel var strukturelt vigtig. William McNeill og andre verdenshistorikere viser at ''globalisation'' som intensiveret interregional kontakt er et cyklisk snarere end lineært fænomen — og vikingetiden repræsenterer en af de tidlige globale ekspansionsfaser."}'::jsonb,
  'mc','short','{"concepts":["handelsnetværk","pre-moderne globalisering","Volga-ruterne","arabiske dirhammer","middelalderlig handel","McNeill"],"misconception_type":"scope_confusion","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"vikings"}'::jsonb,
  'mc_single',5,'auto',true,'vikings',9,5
);

-- ─── BAND 5 · ARVEN & NUTIDSRELEVANS (3 questions) ───────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er den historiske og etiske problematik i at moderne ekstremistiske bevægelser approprierer vikingeikonografi — runer, Odins ravn, Midgardsormen — som symboler?","options":["Approprieringen fordrejer historien i to led: vikingerne var ikke et etnisk monolitisk folk med ensartet ideologi, og de symboler der bruges var i sin tid religiøse snarere end politiske. At bruge dem som national-identitære eller racepolitiske symboler er en dobbelt historisk forfalskning der aktiverer vikingernes prestige til at legitimere moderne ideologier de ikke repræsenterede","Approprieringen er historisk korrekt fordi vikingerne faktisk delte de værdier som disse bevægelser repræsenterer","Problemet er udelukkende æstetisk — brugen af runer og ravne skaber forvirring men har ingen reel politisk konsekvens","Vikingernes symboler tilhører alle og enhver og kan ikke approprieres da de er hævdet fri kulturarv"],"correct":"Approprieringen fordrejer historien i to led: vikingerne var ikke et etnisk monolitisk folk med ensartet ideologi, og de symboler der bruges var i sin tid religiøse snarere end politiske. At bruge dem som national-identitære eller racepolitiske symboler er en dobbelt historisk forfalskning der aktiverer vikingernes prestige til at legitimere moderne ideologier de ikke repræsenterede","accepted_answers":["Approprieringen fordrejer historien i to led: vikingerne var ikke et etnisk monolitisk folk med ensartet ideologi, og de symboler der bruges var i sin tid religiøse snarere end politiske. At bruge dem som national-identitære eller racepolitiske symboler er en dobbelt historisk forfalskning der aktiverer vikingernes prestige til at legitimere moderne ideologier de ikke repræsenterede"],"review_text":"Odalsrunen, SS-runer og Valknut bruges af white supremacist-bevægelser globalt. Scholars som Carolyne Larrington og Neil Price har gentagne gange understreget at vikingesamfundet var etnisk og kulturelt blandet — DNA viser norske graver med nordafrikansk og asiatisk herkomst. Odins symbolik var religiøs og shamansk, ikke politisk-racistisk. Det dobbelte forfalskningstrin er analytisk vigtigt: (1) vikingerne var ikke homogene og (2) symbolernes funktion var en anden. Historikernes ansvar er at korrigere denne appropriering med præcis historisk viden — ikke at give symbolerne op men at reclaim dem med korrekt kontekst."}'::jsonb,
  'mc','short','{"concepts":["runer","extremisme","historisk appropriering","ikonografi","Price","dobbelt forfalskning"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"vikings"}'::jsonb,
  'mc_single',5,'auto',true,'vikings',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad kan Tingmødernes deliberative struktur lære nutidigt demokrati om forholdet mellem direkte deltagelse og repræsentation — og hvad er begrænsningerne i analogien?","options":["Tinget viser at regelbaseret offentlig deliberation med proceduremæssig lighed kan fungere uden repræsentativt bureaukrati — men analogien begrænses af at Tingets deltagerkreds var snæver og at moderne samfunds kompleksitet kræver specialiseret repræsentation som Tinget ikke tilbød. Lektionen er normativ, ikke institutionel: åbenhed og regel-respekt er tidløse demokratiske dyder","Tinget er et perfekt forbillede for moderne demokrati og bør erstatte nutidens parlamentariske system direkte","Tingets deliberative form er irrelevant for moderne demokrati fordi det var for primitivt til at have nogen overførbar indsigt","Tinget viser udelukkende at direkte demokrati altid er overlegent repræsentativt demokrati uanset samfundets størrelse og kompleksitet"],"correct":"Tinget viser at regelbaseret offentlig deliberation med proceduremæssig lighed kan fungere uden repræsentativt bureaukrati — men analogien begrænses af at Tingets deltagerkreds var snæver og at moderne samfunds kompleksitet kræver specialiseret repræsentation som Tinget ikke tilbød. Lektionen er normativ, ikke institutionel: åbenhed og regel-respekt er tidløse demokratiske dyder","accepted_answers":["Tinget viser at regelbaseret offentlig deliberation med proceduremæssig lighed kan fungere uden repræsentativt bureaukrati — men analogien begrænses af at Tingets deltagerkreds var snæver og at moderne samfunds kompleksitet kræver specialiseret repræsentation som Tinget ikke tilbød. Lektionen er normativ, ikke institutionel: åbenhed og regel-respekt er tidløse demokratiske dyder"],"review_text":"Det islandske Althing (grundlagt 930) er historisk bemærkelsesværdigt som en af verdens ældste parlamentariske institutioner. Men analogien med moderne demokrati kræver forsigtighed. Deltagerkredsen var eksklusiv (frie jordbesiddende mænd). Beslutningsprocessen var i praksis domineret af godar (høvdinge). Islandsk middelalder-demokrati kollapsede under borgerkrigens pres i 1200-tallets Sturlungaøra. Den normative lektie er stærkere end den institutionelle: offentlig deliberation, proceduremæssig orden og regelbaseret konfliktløsning er demokratiske værdier der eksisterede forud for industrisamfundet — og det udfordrer den progressive fortælling om at demokrati er et produkt af modernitet alene."}'::jsonb,
  'mc','short','{"concepts":["Ting","direkte demokrati","repræsentation","Althing","demokratihistorie","normativ lektie"],"misconception_type":"overgeneralization","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"vikings"}'::jsonb,
  'mc_single',5,'auto',true,'vikings',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad viser den nordatlantiske vikingudvandring til Island og Grønland — og den efterfølgende kollapset af den grønlandske bosætning — om forholdet mellem kulturel rigiditet og tilpasning til nye miljøer?","options":["At kulturel rigiditet kan være fatal: de grønlandske vikinger nægtede at adoptere inuitternes tilpasningsstrategier (seladyrsjagt, sælfangst, klædedragt) og fastholdt europæisk landbrugspraksis i et klima der ikke understøttede det — mens inuitterne overlevede den lille istid fordi de tilpassede sig miljøet frem for at insistere på kulturel kontinuitet","At de grønlandske vikinger kollapsede udelukkende på grund af klimaændringer som ingen menneskelig tilpasning kunne have afbødet","At de grønlandske vikinger fuldt ud tilpassede sig det arktiske miljø og at kollapset skyldtes ekstern europæisk handelsstop","At vikingernes grønlandske koloni aldrig virkelig fungerede og aldrig nåede et niveau der kan beskrives som en varig bosætning"],"correct":"At kulturel rigiditet kan være fatal: de grønlandske vikinger nægtede at adoptere inuitternes tilpasningsstrategier (seladyrsjagt, sælfangst, klædedragt) og fastholdt europæisk landbrugspraksis i et klima der ikke understøttede det — mens inuitterne overlevede den lille istid fordi de tilpassede sig miljøet frem for at insistere på kulturel kontinuitet","accepted_answers":["At kulturel rigiditet kan være fatal: de grønlandske vikinger nægtede at adoptere inuitternes tilpasningsstrategier (seladyrsjagt, sælfangst, klædedragt) og fastholdt europæisk landbrugspraksis i et klima der ikke understøttede det — mens inuitterne overlevede den lille istid fordi de tilpassede sig miljøet frem for at insistere på kulturel kontinuitet"],"review_text":"Jared Diamond analyserer kollapset i Collapse (2005): den grønlandske Norse-befolkning (peak ca. 5.000 mennesker) uddøde ca. 1400-1450 under den lille istid. Arkæologiske fund viser at de spiste kvæg, fisk og vilde dyr — men i ringe grad sæler, som var inuitternes primære fødekilde og klimatilpasning. Inuitterne overlevede fordi de tilpassede jagt, klædedragt (anoraks) og boliger (iglooer) til arktiske betingelser. Norse-grønlænderne fastholdt europæiske landbrugsnormer og sociale strukturer der krævede kvæghold — et system der ikke kunne overleve i en koldere periode. Kulturel fleksibilitet vs. kulturel rigiditet er fortsat en højaktuel problemstilling for samfund der møder klimaforandringer."}'::jsonb,
  'mc','short','{"concepts":["grønlandske vikinger","kulturel rigiditet","inuitter","klimatilpasning","Diamond","lille istid"],"misconception_type":"causal_inversion","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"vikings"}'::jsonb,
  'mc_single',5,'auto',true,'vikings',9,5
);
