-- Section 147C — World War 2 Grade 7 Capacity Expansion

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c1q${"question":"Hvad var Blitzkrieg og hvordan brugte Tyskland det i begyndelsen af 2. Verdenskrig?","options":["En lynhurtig angrebsstrategi der kombinerede tanks, fly og infanteri for at overrumple fjenden inden de kunne organisere forsvar — brugt mod Polen (1939) og Frankrig (1940)","En defensiv strategi som Tyskland brugte til at beskytte sine egne graenser mod angreb fra vest","En strategi der udelukkende baserede sig paa bombefly uden brug af landstyrker","En diplomatisk strategi der brugte trusler om krig frem for faktisk kamp"],"correct":"En lynhurtig angrebsstrategi der kombinerede tanks, fly og infanteri for at overrumple fjenden inden de kunne organisere forsvar — brugt mod Polen (1939) og Frankrig (1940)","accepted_answers":["En lynhurtig angrebsstrategi der kombinerede tanks, fly og infanteri for at overrumple fjenden inden de kunne organisere forsvar — brugt mod Polen (1939) og Frankrig (1940)"],"review_text":"Blitzkrieg betyder lynkrig paa tysk. Strategien kombinerede pansrede koeretoejer, motoriseret infanteri og kampfly i hurtige gennembrud der omringede og isolerede fjenden. Polen faldt paa tre uger i september 1939. Frankrig kollapsede paa seks uger i maj-juni 1940. Blitzkrieg var revolutionaer fordi den broed med den statiske frontkrigsforelse og viste at mobilitet og koordination kunne besejre numerisk overlegne styrker."}$c1q$::jsonb,
  'mc','short',$c1m${"concepts":["Blitzkrieg","lynkrig","tanks","Polen","Frankrig","strategi"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"recognition","insight_type":"concept_clarification","challenge_role":"entry_level","domain":"world_war_2"}$c1m$::jsonb,
  'mc_single',1,'auto',true,'world_war_2',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c2q${"question":"Hvad skete der ved Pearl Harbor den 7. december 1941 og hvad var konsekvensen?","options":["Japan angreb overraskende den amerikanske flaadebase paa Hawaii — det fik USA til at erklaere krig mod Japan og dermed officielt at traede ind i 2. Verdenskrig","USA angreb den japanske flaade for at forhindre Japan i at angribe Kina","Angrebet paa Pearl Harbor var en fejltagelse fra Japans side som ikke fik nogen kriegsmaessig konsekvens","Den tyske flaade angreb Pearl Harbor for at traekke USA ind paa Tysklands side i krigen"],"correct":"Japan angreb overraskende den amerikanske flaadebase paa Hawaii — det fik USA til at erklaere krig mod Japan og dermed officielt at traede ind i 2. Verdenskrig","accepted_answers":["Japan angreb overraskende den amerikanske flaadebase paa Hawaii — det fik USA til at erklaere krig mod Japan og dermed officielt at traede ind i 2. Verdenskrig"],"review_text":"Den 7. december 1941 angreb japanske bombefly overraskende den amerikanske flaadebase paa Hawaii. 2.403 amerikanere omkom, 19 krigsskibe blev saenket eller beskadiget. Dagen efter erklaerede USA krig mod Japan, og dage senere erklaerede Tyskland og Italien krig mod USA. Det var vendepunktet der forvandlede en europaeisk krig til en egentlig verdenskrig med USA's enorme industrielle og militaere ressourcer paa de Allieredes side."}$c2q$::jsonb,
  'mc','short',$c2m${"concepts":["Pearl Harbor","Japan","USA","kriegserklaering","Stillehavet","1941"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"recognition","insight_type":"concept_clarification","challenge_role":"entry_level","domain":"world_war_2"}$c2m$::jsonb,
  'mc_single',1,'auto',true,'world_war_2',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c3q${"question":"Hvad var de saakaldte Nuernberg-love fra 1935 og hvad betod de for joeder i Tyskland?","options":["Racistiske love der fratog tyske joeder deres statsborgerskab og forboed aeagteskab og forhold mellem joeder og ikke-joeder — et centralt juridisk skridt i nazisternes systematiske udelukkelse af joederne","Love der bestemte at alle joeder i Europa skulle deporteres til Palaestina med det samme","Love der forboed joeder at udoeve handel men tillod dem alle oevrige rettigheder som borgere","Internationale love vedtaget af Folkeforbundet der forsogte at beskytte joediske mindretal i Europa"],"correct":"Racistiske love der fratog tyske joeder deres statsborgerskab og forboed aeagteskab og forhold mellem joeder og ikke-joeder — et centralt juridisk skridt i nazisternes systematiske udelukkelse af joederne","accepted_answers":["Racistiske love der fratog tyske joeder deres statsborgerskab og forboed aeagteskab og forhold mellem joeder og ikke-joeder — et centralt juridisk skridt i nazisternes systematiske udelukkelse af joederne"],"review_text":"Nuernberg-lovene fra september 1935 fratog joeder tysk statsborgerskab og forboed aeagteskab og seksuelle forhold mellem joeder og ikke-joeder. De var ikke spontane — de var en del af en systematisk strategi for at isolere og udelukke joeder fra det tyske samfund. De kom fire aar inden massemordene begyndte og viser at Holocaust ikke var improviseret men et gradvist eskalerende forfoelgelsesprogram."}$c3q$::jsonb,
  'mc','short',$c3m${"concepts":["Nuernberg-love","statsborgerskab","racisme","juridisk udelukkelse","joedeforfoelgelse","1935"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"concept_clarification","challenge_role":"reinforcement","domain":"world_war_2"}$c3m$::jsonb,
  'mc_single',2,'auto',true,'world_war_2',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c4q${"question":"Hvad var Operation Barbarossa (1941) og hvorfor er den en af krigens vigtigste begivenheder?","options":["Tysklands invasion af Sovjetunionen i juni 1941 — den aabnede Ostfronten der blev krigens blodigste kampzone og kostede anslaet 27 millioner sovjetiske liv samt broed den tysk-sovjetiske ikke-angrebspagt","Det britiske modangreb der befriede Vesteuropa fra den tyske besaettelse","Den japanske invasion af Kina som udvidede krigen fra Europa til Asien og Stillehavet","Alliancen mellem Sovjet og USA om faelles angreb paa Japan i Stillehavet"],"correct":"Tysklands invasion af Sovjetunionen i juni 1941 — den aabnede Ostfronten der blev krigens blodigste kampzone og kostede anslaet 27 millioner sovjetiske liv samt broed den tysk-sovjetiske ikke-angrebspagt","accepted_answers":["Tysklands invasion af Sovjetunionen i juni 1941 — den aabnede Ostfronten der blev krigens blodigste kampzone og kostede anslaet 27 millioner sovjetiske liv samt broed den tysk-sovjetiske ikke-angrebspagt"],"review_text":"Den 22. juni 1941 broed Hitler den tysk-sovjetiske ikke-angrebspagt og sendte tre millioner tyske soldater ind i Sovjet. Ostfronten udviklede sig til en blodig udmaettelseskrig. Stalingrad (1942-43), Kursk (1943) og til sidst Berlin (1945) — Ostfronten kostede Sovjet anslaet 27 millioner liv og var den krig der i hoej grad knuste Nazityskland."}$c4q$::jsonb,
  'mc','short',$c4m${"concepts":["Operation Barbarossa","Ostfronten","Sovjet","ikke-angrebspagt","1941","masseofre"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"concept_clarification","challenge_role":"reinforcement","domain":"world_war_2"}$c4m$::jsonb,
  'mc_single',2,'auto',true,'world_war_2',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c5q${"question":"Hvad kendetegnede forholdet mellem samarbejde og modstand i de tyskkontrollerede lande under 2. Verdenskrig?","options":["I de fleste besatte lande tilpassede flertallet sig hverdagen mens et mindretal enten samarbejdede aktivt med nazisterne eller aktivt modstod dem — forholdet varierede fra land til land afhaengig af situation og politisk kultur","I alle besatte lande rejste befolkningerne sig ojeblikkeligt i aktiv vaebnet modstand mod nazisterne","I alle besatte lande samarbejdede befolkningerne fuldt ud med nazisterne fordi de sympatiserede med deres ideologi","Samarbejde og modstand forekom kun i Danmark — alle andre besatte lande var fuldt neutrale"],"correct":"I de fleste besatte lande tilpassede flertallet sig hverdagen mens et mindretal enten samarbejdede aktivt med nazisterne eller aktivt modstod dem — forholdet varierede fra land til land afhaengig af situation og politisk kultur","accepted_answers":["I de fleste besatte lande tilpassede flertallet sig hverdagen mens et mindretal enten samarbejdede aktivt med nazisterne eller aktivt modstod dem — forholdet varierede fra land til land afhaengig af situation og politisk kultur"],"review_text":"Besatte landes befolkninger var sjaeldent entydigt enten modstandere eller samarbejdspartnere. I Frankrig var der aktiv kollaboration (Vichy-regeringen) men ogsaa staerk modstandsbevaegelse (Résistance). I Danmark reddede befolkningen storstedelen af de joediske borgere. De fleste steder var den store midtergruppe tilpassede mennesker der forsogte at overleve hverdagen — hverken helte eller forraedere."}$c5q$::jsonb,
  'mc','short',$c5m${"concepts":["samarbejde","modstand","besatte lande","kollaboration","Resistance","hverdagen"],"misconception_type":"overgeneralization","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_2"}$c5m$::jsonb,
  'mc_single',2,'auto',true,'world_war_2',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c6q${"question":"Hvilken rolle spillede Japan i 2. Verdenskrig og hvad var dets vigtigste maal?","options":["Japan kaempede paa Aksemagternes side og forsogte at opbygge et koloniimperium i Asien og Stillehavet — det invaderede Kina, store dele af Sydostasien og angreb USA ved Pearl Harbor","Japan kaempede paa de Allieredes side og bidrog til befrielsen af Europa fra nazistisk besaettelse","Japan var neutral i 2. Verdenskrig og deltog udelukkende som humanitaer hjaelpeorganisation","Japan kaempede kun i Europa og spillede ingen rolle i Stillehavet eller Asien"],"correct":"Japan kaempede paa Aksemagternes side og forsogte at opbygge et koloniimperium i Asien og Stillehavet — det invaderede Kina, store dele af Sydostasien og angreb USA ved Pearl Harbor","accepted_answers":["Japan kaempede paa Aksemagternes side og forsogte at opbygge et koloniimperium i Asien og Stillehavet — det invaderede Kina, store dele af Sydostasien og angreb USA ved Pearl Harbor"],"review_text":"Japan var en af de tre Aksemagter (med Tyskland og Italien) og havde ambitioner om et japansk-domineret imperium i Asien. Japan invaderede Kina i 1937 og angreb Pearl Harbor i 1941. Japan erobrede Filippinerne, Indonesien, Burma og mange Stillehavsoeer. Krigen i Asien og Stillehavet kostede anslaet 20 millioner asiatiske civile livet."}$c6q$::jsonb,
  'mc','short',$c6m${"concepts":["Japan","Aksemagter","Stillehavskrigen","Pearl Harbor","koloniimperium","Asien"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"concept_clarification","challenge_role":"reinforcement","domain":"world_war_2"}$c6m$::jsonb,
  'mc_single',2,'auto',true,'world_war_2',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c7q${"question":"Hvad var Wannsee-konferencen i januar 1942 og hvad viser den om Holocaust?","options":["En hemmelig konference i Berlin hvor naziledere koordinerede den systematiske udryddelse af alle europaeiske joeder — den viser at Holocaust kraevede bureaukratisk planlaeGning og bred embedsmandsdeltagelse ikke kun SS-fanatikere","Et fredsforhandlingsmoede hvor Hitler og de allierede ledere diskuterede en mulig vaabenhvile","En international konference i 1942 hvor de allierede planlagde invasionen af Normandiet","Et moede i Berlin hvor tyske generaler planlagde det militaere angreb paa Sovjetunionen"],"correct":"En hemmelig konference i Berlin hvor naziledere koordinerede den systematiske udryddelse af alle europaeiske joeder — den viser at Holocaust kraevede bureaukratisk planlaeGning og bred embedsmandsdeltagelse ikke kun SS-fanatikere","accepted_answers":["En hemmelig konference i Berlin hvor naziledere koordinerede den systematiske udryddelse af alle europaeiske joeder — den viser at Holocaust kraevede bureaukratisk planlaeGning og bred embedsmandsdeltagelse ikke kun SS-fanatikere"],"review_text":"Den 20. januar 1942 moodtes 15 hojetplacerede nazister og embedsmaend i en villa ved Wannsee-soeen. Formaaalet var at koordinere udryddelsen af alle 11 millioner europaeiske joeder — Endloesung, den endelige losning. Modet varede ca. 90 minutter. Protokollen overlevede krigen og er chokerende i sin bureaukratiske, noeterne tone: massemord planlagt som et administrativt problem. Wannsee viser at Holocaust ikke var improviseret galskab men systematisk planlaeGning med bred embedsmandsdeltagelse."}$c7q$::jsonb,
  'mc','short',$c7m${"concepts":["Wannsee","Endloesung","koordinering","bureaukrati","planlaeGning","embedsmaend"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"challenge","domain":"world_war_2"}$c7m$::jsonb,
  'mc_single',3,'auto',true,'world_war_2',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c8q${"question":"Hvad var Warszawagetto-operoeret (april-maj 1943) og hvad viser det om joeders reaktion paa naziforfolgelsen?","options":["Joediske modstandskaempere i den lukkede ghetto i Warszawa rejste sig i bevaebnet operoer mod deportation til udryddelseslejre — det varede naesten en maaned og viser at joeder aktivt modstod nazisterne selvom modstanden til sidst blev slaaet ned","Et polsk militaerisk operoer der lykkedes med at befri Warszawa fra den tyske besaettelse i 1943","Et operoer der beviste at joederne var pacifistiske og aldrig forsogte at modstaa deportationerne","Et opgjoer mellem kommunistiske og nationalistiske polske grupper om kontrollen over Warszawa"],"correct":"Joediske modstandskaempere i den lukkede ghetto i Warszawa rejste sig i bevaebnet operoer mod deportation til udryddelseslejre — det varede naesten en maaned og viser at joeder aktivt modstod nazisterne selvom modstanden til sidst blev slaaet ned","accepted_answers":["Joediske modstandskaempere i den lukkede ghetto i Warszawa rejste sig i bevaebnet operoer mod deportation til udryddelseslejre — det varede naesten en maaned og viser at joeder aktivt modstod nazisterne selvom modstanden til sidst blev slaaet ned"],"review_text":"I april 1943 besluttede de tyske myndigheder at deportere ghettoen resterende 60.000 joeder til Treblinka. En lille gruppe modstandskaempere valgte at kaempe. De tyske tropper forventede tre dage — det tog naesten fire uger. Operoeret modviser myten om at joeder gik passivt i udryddelse. Det skete under ekstreme odds — omringet, underbevaebnet, ingen udefra kom til undsoetning. Til sidst broendte tyskerne ghettoen systematisk ned."}$c8q$::jsonb,
  'mc','short',$c8m${"concepts":["Warszawa-ghetto","operoer","modstand","deportation","Treblinka","aktiv modstand"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"challenge","domain":"world_war_2"}$c8m$::jsonb,
  'mc_single',3,'auto',true,'world_war_2',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c9q${"question":"Hvad var konsekvenserne af USA's atombombeangreb paa Hiroshima og Nagasaki i august 1945?","options":["Angrebene draebte anslaet 130.000-226.000 mennesker og fik Japan til at overgive sig den 15. august 1945 — det afsluttede 2. Verdenskrig men aabnede en ny aera med atomvaaben som global magtfaktor","Angrebene mislykkedes militaert og Japan overgav sig forst maaneder senere efter en konventionel landinvasion","Angrebene draebte udelukkende japanske soldater og efterlod den civile befolkning uskadet","USA brugte atombomber i Europa for at tvinge Nazityskland til at kapitulere i 1945"],"correct":"Angrebene draebte anslaet 130.000-226.000 mennesker og fik Japan til at overgive sig den 15. august 1945 — det afsluttede 2. Verdenskrig men aabnede en ny aera med atomvaaben som global magtfaktor","accepted_answers":["Angrebene draebte anslaet 130.000-226.000 mennesker og fik Japan til at overgive sig den 15. august 1945 — det afsluttede 2. Verdenskrig men aabnede en ny aera med atomvaaben som global magtfaktor"],"review_text":"Den 6. august 1945 kastede USA en atombombe over Hiroshima. Den 9. august faldt en anden over Nagasaki. Titusinder doede ojeblikkeligt; mange tusinde mere doede i maanederne og aarene efter af straalingsskader. Den 15. august erklaerete den japanske kejser landets overgivelse. Det var foerste og hidtil eneste gang atomvaaben er brugt i krig. Angrebene afsluttede verdenskrigens blodigste kapitel men markerede begyndelsen paa den atomare tidsalder og Den Kolde Krig."}$c9q$::jsonb,
  'mc','short',$c9m${"concepts":["Hiroshima","Nagasaki","atombombe","Japan","overgivelse","atomalder"],"misconception_type":"factual_error","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"concept_clarification","challenge_role":"challenge","domain":"world_war_2"}$c9m$::jsonb,
  'mc_single',3,'auto',true,'world_war_2',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c10q${"question":"Hvilken rolle spillede kvinder paa hjemmefronten i lande som Storbritannien og USA under 2. Verdenskrig?","options":["Kvinder overtog i store tal fabriksarbejde og krigsindustrien mens maend var ved fronten — det aendrede samfundets syn paa kvinders evner og bidrog til efterkrigstidens krav om ligestilling","Kvinder spillede ingen rolle under 2. Verdenskrig da de udelukkende opholdt sig i hjemmet","Kvinder kaempede som soldater paa alle fronter ligesom maend i alle de allierede nationer","Kvinder blev sendt ud af arbejdsmarkedet under krigen for at frigoere pladser til hjemvendte veteraner"],"correct":"Kvinder overtog i store tal fabriksarbejde og krigsindustrien mens maend var ved fronten — det aendrede samfundets syn paa kvinders evner og bidrog til efterkrigstidens krav om ligestilling","accepted_answers":["Kvinder overtog i store tal fabriksarbejde og krigsindustrien mens maend var ved fronten — det aendrede samfundets syn paa kvinders evner og bidrog til efterkrigstidens krav om ligestilling"],"review_text":"Da millioner af maend blev indkaldt til fronten, rykkede kvinder ind i fly- og ammunitionsfabrikker, som ingeniorer, sygeplejersker og i militarets stoettefunktioner. I USA blev Rosie the Riveter et ikonisk billede paa kvinders krigsindsats. I Storbritannien tjente over 640.000 kvinder i hjaeIpemilitaere enheder. Erfaringen med at kvinder kunne klare teknisk og fysisk kraevende arbejde underminerede fordomme og gav naering til efterkrigstidens krav om ligelon."}$c10q$::jsonb,
  'mc','short',$c10m${"concepts":["kvinder","hjemmefront","fabriksarbejde","ligestilling","Rosie the Riveter","efterkrigstid"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"challenge","domain":"world_war_2"}$c10m$::jsonb,
  'mc_single',3,'auto',true,'world_war_2',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c11q${"question":"Hvad var de vigtigste konsekvenser da den danske samarbejdspolitik broed sammen i august 1943?","options":["Besaettelsesmagten overtog fuld kontrol og internerede den danske haer og flaade — og den tyske plan om at deportere de danske joeder tre uger senere udloeste den redningsaktion der forte 7.000 joeder i sikkerhed i Sverige","Danmark erklaerede krig mod Tyskland og sendte tropper til Vestfronten","Samarbejdspolitikken fortsatte uaendret frem til befrielsen i maj 1945","Den danske befolkning rejste sig i masseoperoer og slog de tyske besaettelsesstyrker tilbage"],"correct":"Besaettelsesmagten overtog fuld kontrol og internerede den danske haer og flaade — og den tyske plan om at deportere de danske joeder tre uger senere udloeste den redningsaktion der forte 7.000 joeder i sikkerhed i Sverige","accepted_answers":["Besaettelsesmagten overtog fuld kontrol og internerede den danske haer og flaade — og den tyske plan om at deportere de danske joeder tre uger senere udloeste den redningsaktion der forte 7.000 joeder i sikkerhed i Sverige"],"review_text":"I august 1943 eskalerede modstandsbevaegelsen og strejker. Det tyske militaer erklaerede undtagelsestilstand, internerede den danske haer og soenksatte den danske flaade. Den nye situation fik nazisterne til at beslutte at deportere de ca. 7.000 danske joeder. Men laeKagen af planen kombineret med et usaedvanligt staerkt folkeligt engagement — fiskere, laeger, naboer — forte storstedelen over Oresund til Sverige inden razzia-natten den 1.-2. oktober 1943."}$c11q$::jsonb,
  'mc','short',$c11m${"concepts":["augustoproer","samarbejdspolitik","joederedning","besaettelse","undtagelsestilstand","1943"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"challenge","domain":"world_war_2"}$c11m$::jsonb,
  'mc_single',3,'auto',true,'world_war_2',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c12q${"question":"Hvorfor betragtes slaget ved Stalingrad (1942-43) som et afgorende vendepunkt i 2. Verdenskrig?","options":["Det forste store tyske militaere nederlag: den tyske 6. Armé paa over 300.000 mand kapitulerede — det viste at Wehrmacht kunne besejres og markerede overgangen fra tysk offensiv til defensiv paa Ostfronten","Det var det slag hvor USA for forste gang kaempede paa land mod tyske tropper i Europa","Det var det slag der befriede Frankrig fra den tyske besaettelse og aabnede en anden front mod vest","Stalingrad var kun et mindre slag og havde ingen afgorende militaer betydning for krigens forloeb"],"correct":"Det forste store tyske militaere nederlag: den tyske 6. Armé paa over 300.000 mand kapitulerede — det viste at Wehrmacht kunne besejres og markerede overgangen fra tysk offensiv til defensiv paa Ostfronten","accepted_answers":["Det forste store tyske militaere nederlag: den tyske 6. Armé paa over 300.000 mand kapitulerede — det viste at Wehrmacht kunne besejres og markerede overgangen fra tysk offensiv til defensiv paa Ostfronten"],"review_text":"Stalingrad (august 1942 — februar 1943) var en af historiens blodigste slag. Hitler beordrede den 6. Armé til at holde Stalingrad for enhver pris. Sovjet indkredsede og afskar armeen. General von Paulus kapitulerede i februar 1943 med ca. 91.000 overlevende soldater. Det var et chok for det tyske folk. Fra Stalingrad pressede Sovjet gradvist de tyske styrker tilbage mod Berlin. Det tyske momentum var knust."}$c12q$::jsonb,
  'mc','short',$c12m${"concepts":["Stalingrad","vendepunkt","Ostfronten","6. Armé","kapitulation","offensiv til defensiv"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"challenge","domain":"world_war_2"}$c12m$::jsonb,
  'mc_single',3,'auto',true,'world_war_2',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c13q${"question":"Hvad var Winston Churchills historiske betydning som Storbritanniens leder i 2. Verdenskrig?","options":["Churchill holdt fast i britisk modstand i 1940 da presset for at soege forhandlingsfred med Hitler var stoerst — hans lederevner og retorik cementerede den politiske og folkelige vilje til at kaempe og forhindrede et britisk forligsfredssoeGning","Churchill koordinerede den britiske atombombeudvikling som var afgorende for krigens afslutning","Churchill var ubetydelig for krigens resultat — USA vandt krigen med britisk neutral opbakning","Churchill beordrede personligt D-dag og var ansvarlig for den militaere planlaegning af Normandiet-landgangen"],"correct":"Churchill holdt fast i britisk modstand i 1940 da presset for at soege forhandlingsfred med Hitler var stoerst — hans lederevner og retorik cementerede den politiske og folkelige vilje til at kaempe og forhindrede et britisk forligsfredssoeGning","accepted_answers":["Churchill holdt fast i britisk modstand i 1940 da presset for at soege forhandlingsfred med Hitler var stoerst — hans lederevner og retorik cementerede den politiske og folkelige vilje til at kaempe og forhindrede et britisk forligsfredssoeGning"],"review_text":"Da Frankrig faldt i juni 1940 pressede indflydelsesrige stemmer i det britiske kabinet paa for forhandlingsfred med Hitler. Churchill afviste kategorisk. I tre beroemte taler sommeren 1940 sagde han at briterne ville kaempe paa strandene og aldrig overgive sig. Churchills valg forhindrede sandsynligvis et forlig der ville have frigivet tyske ressourcer til at slaa Sovjet. Enkeltpersoners valg kan have historisk afgorende konsekvenser."}$c13q$::jsonb,
  'mc','short',$c13m${"concepts":["Churchill","britisk modstand","forhandlingsfred","retorik","lederskab","1940"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"analytical_challenge","domain":"world_war_2"}$c13m$::jsonb,
  'mc_single',4,'auto',true,'world_war_2',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c14q${"question":"Hvad viser historisk forskning om de mennesker der udoevede Holocaust — hvem var gerningsmaendene?","options":["Forskning som Christopher Brownings om Reservepolitibataljon 101 viser at mange gerningsmaend var ordinaere mennesker uden fanatisk ideologi — konformitetspres og lydighed over for autoritet var vigtigere motivationer end medfodt ondskab","Forskning viser entydigt at alle Holocaust-gerningsmaend var ideologisk overbevist om nazismens retfaerdighed","Forskning viser at Holocaust kun var mulig fordi alle gerningsmaend var psykisk syge og ikke normale mennesker","Historikere er enige om at kun en lille SS-elite var ansvarlig — den brede befolkning vidste intet og bidrog slet ikke"],"correct":"Forskning som Christopher Brownings om Reservepolitibataljon 101 viser at mange gerningsmaend var ordinaere mennesker uden fanatisk ideologi — konformitetspres og lydighed over for autoritet var vigtigere motivationer end medfodt ondskab","accepted_answers":["Forskning som Christopher Brownings om Reservepolitibataljon 101 viser at mange gerningsmaend var ordinaere mennesker uden fanatisk ideologi — konformitetspres og lydighed over for autoritet var vigtigere motivationer end medfodt ondskab"],"review_text":"Christopher Browning analyserede i Ordinary Men (1992) middelaldrende tyske maend der ikke var SS-fanatikere. De fik valget om at deltage i masseudskydninger eller melde sig fra. Meget faa meldte fra. Frygten for at skille sig ud, gruppepres og gradvis dehumanisering af ofrene var mere forklarende end ideologisk had. Hannah Arendt formulerede lignende pointer med begrebet det ondes banalitet i sin analyse af Eichmann. Moralske katastrofer kraever ikke monstre — de kraever systemer der normaliserer ondskab."}$c14q$::jsonb,
  'mc','short',$c14m${"concepts":["ordinaere gerningsmaend","Browning","Arendt","det ondes banalitet","konformitet","lydighed"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"analytical_challenge","domain":"world_war_2"}$c14m$::jsonb,
  'mc_single',4,'auto',true,'world_war_2',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c15q${"question":"Hvad var den direkte aarsag til at Tyskland blev delt i Vest- og Osttyskland efter 2. Verdenskrig?","options":["De fire sejrende magter delte Tyskland i besaettelseszoner — den voksende spaending mellem vest og ost betod at de vestlige zoner fusionerede til Vesttyskland (BRD) og den sovjetiske zone blev til Osttyskland (DDR) i 1949","Det var en frivillig tysk beslutning at dele landet for at undgaa fremtidige krige","FN besluttede at dele Tyskland som kollektiv straf for Holocaust og krigen","USA og Sovjet delte Tyskland fysisk i 1945 med en permanent mur fra dag eet"],"correct":"De fire sejrende magter delte Tyskland i besaettelseszoner — den voksende spaending mellem vest og ost betod at de vestlige zoner fusionerede til Vesttyskland (BRD) og den sovjetiske zone blev til Osttyskland (DDR) i 1949","accepted_answers":["De fire sejrende magter delte Tyskland i besaettelseszoner — den voksende spaending mellem vest og ost betod at de vestlige zoner fusionerede til Vesttyskland (BRD) og den sovjetiske zone blev til Osttyskland (DDR) i 1949"],"review_text":"Efter Tysklands kapitulation i maj 1945 delte USA, Storbritannien, Frankrig og Sovjet landet i fire besaettelseszoner. Den voksende kloeft mellem vest og ost betod at de vestlige zoner fusionerede til Forbundsrepublikken Tyskland (BRD) i maj 1949, og den sovjetiske zone blev til Den Tyske Demokratiske Republik (DDR) i oktober 1949. Tyskland forblev delt i 40 aar til Berlinmurens fald i 1989 og genforeningen i 1990."}$c15q$::jsonb,
  'mc','short',$c15m${"concepts":["Tysklands deling","besaettelseszoner","BRD","DDR","1949","Den Kolde Krig"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"causal","insight_type":"concept_clarification","challenge_role":"analytical_challenge","domain":"world_war_2"}$c15m$::jsonb,
  'mc_single',4,'auto',true,'world_war_2',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c16q${"question":"Hvad viser den internationale reaktion paa nazisternes joedeforfolgelse i 1930'erne om tilskueres ansvar?","options":["Mange lande vidste om forfolgelserne men lukkede graenserne for joediske flygtninge og reagerede ikke — det viser at passivitet ikke er neutral men kan muliggoere forfolgelse","Alle vestlige lande aabnede straks deres graenser for joediske flygtninge da forfolgelserne begyndte","Ingen lande vidste noget om forfolgelserne af joeder for befrielsen af lejrene i 1945","FN fordoemte nazisternes forfolgelse af joeder officielt i 1937 og kraevede at det stoppede"],"correct":"Mange lande vidste om forfolgelserne men lukkede graenserne for joediske flygtninge og reagerede ikke — det viser at passivitet ikke er neutral men kan muliggoere forfolgelse","accepted_answers":["Mange lande vidste om forfolgelserne men lukkede graenserne for joediske flygtninge og reagerede ikke — det viser at passivitet ikke er neutral men kan muliggoere forfolgelse"],"review_text":"I 1938 moodtes 32 nationer i Évian i Frankrig for at diskutere den joediske flygtningekrise. Naesten alle lukkede doorene — inklusive USA og Storbritannien. Det tyske regime noterede tilfreds at Vesten talte om humanitaere hensyn men i praksis naegaede at tage imod joederne. At tilskuere — individer og nationer — har et ansvar for at reagere paa forfolgelse er en central etisk lektie fra 2. Verdenskrig."}$c16q$::jsonb,
  'mc','short',$c16m${"concepts":["tilskueres ansvar","flygtninge","Evian","passivitet","international reaktion","bystanders"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"analytical_challenge","domain":"world_war_2"}$c16m$::jsonb,
  'mc_single',4,'auto',true,'world_war_2',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c17q${"question":"Hvad kendetegnede behandlingen af civile i 2. Verdenskrig sammenlignet med 1. Verdenskrig?","options":["2. Verdenskrig var i langt hoejere grad en krig mod civile — strategiske bombninger af byer, udryddelseslejre og systematisk folkemord betod at et flertal af de ca. 70-85 millioner ofre var civile ikke soldater","2. Verdenskrig havde proportionelt faerre civile ofre end 1. Verdenskrig fordi bombardementsteknikken var mere praecis","2. Verdenskrig var en rent militaer konflikt — civile befolkninger var beskyttet og ikke involveret i kamphandlingerne","Behandlingen af civile var identisk i 1. og 2. Verdenskrig da begge krige fulgte de samme folkeretslige regler"],"correct":"2. Verdenskrig var i langt hoejere grad en krig mod civile — strategiske bombninger af byer, udryddelseslejre og systematisk folkemord betod at et flertal af de ca. 70-85 millioner ofre var civile ikke soldater","accepted_answers":["2. Verdenskrig var i langt hoejere grad en krig mod civile — strategiske bombninger af byer, udryddelseslejre og systematisk folkemord betod at et flertal af de ca. 70-85 millioner ofre var civile ikke soldater"],"review_text":"1. Verdenskrig var primaert en krig mellem soldater i skyttegrave. 2. Verdenskrig broed med dette: bomber over London, Dresden, Tokyo og Hiroshima draebte bevidst civile. Holocaust udryddede seks millioner civile joeder systematisk. Nanjing-massakren. Tyske destruktioner af byer i Sovjet og Polen. Af de anslaet 70-85 millioner krigsofre var 40-55 procent civile. Det aendrede fundamentalt den internationale folkeretslige forstaaelse af hvad krig er."}$c17q$::jsonb,
  'mc','short',$c17m${"concepts":["civile ofre","total krig","bombninger","Holocaust","folkemord","folkeretten"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"analytical_challenge","domain":"world_war_2"}$c17m$::jsonb,
  'mc_single',4,'auto',true,'world_war_2',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c18q${"question":"Var USA's brug af atombomber mod Hiroshima og Nagasaki moralsk forsvarlig — og hvad siger den historiske debat?","options":["En vedvarende etisk og historisk debat: forsvarerne argumenterer at bomberne forkortede krigen og reddede millioner af liv — kritikerne svarer at Japan allerede var taet paa overgivelse og at massedrabet paa civile aldrig kan retfaerdIgoeres","Der er historisk og etisk konsensus om at atombomberne var fuldstaendig moralsk forsvarlige og retfaerdige","Der er historisk og etisk konsensus om at atombomberne var en krigsforbrydelse og USA er officielt blevet doemt for det","Debatten er rent teknisk og handler kun om militaer effektivitet — etik er irrelevant i krig"],"correct":"En vedvarende etisk og historisk debat: forsvarerne argumenterer at bomberne forkortede krigen og reddede millioner af liv — kritikerne svarer at Japan allerede var taet paa overgivelse og at massedrabet paa civile aldrig kan retfaerdIgoeres","accepted_answers":["En vedvarende etisk og historisk debat: forsvarerne argumenterer at bomberne forkortede krigen og reddede millioner af liv — kritikerne svarer at Japan allerede var taet paa overgivelse og at massedrabet paa civile aldrig kan retfaerdIgoeres"],"review_text":"Forsvarerne (traditionelle historikere): en landinvasion af Japan kunne have kostet en million amerikanske og millioner af japanske liv — bomberne afkortede krigen og reddede liv netto. Kritikerne (revisionister): japanske signaler om overgivelsesvilje var allerede tydelige; bomberne var primaert geopolitisk signalering over for Sovjet; og massedrab paa civile kan aldrig retfaerdIgoeres uanset strategisk maal. En tredje position: begge faktorer var reelle — den moralske vurdering afhaenger af hvilke konsekvenser man tillaeGger stoerst vaegt. Debatten er ikke afsluttet."}$c18q$::jsonb,
  'mc','short',$c18m${"concepts":["atombomber","etisk debat","Hiroshima","landinvasion","civile ofre","historikerdebat"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}$c18m$::jsonb,
  'mc_single',5,'auto',true,'world_war_2',7,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c19q${"question":"Hvad fortaeller Milgrams lydigheds-eksperiment (1961) om de psykologiske mekanismer bag Holocaust?","options":["Eksperimentet viste at ordinaere mennesker er villige til at paafore andre alvorlig skade naar en autoritetsfigur beordrer dem til det — det undersoetter Hannah Arendts tese om det ondes banalitet og viser at Holocaust ikke kraevede monstre men systemer der normaliserede lydighed","Eksperimentet beviste at alle mennesker er naturligt onde og bevidst oensker at skade andre","Eksperimentet er videnskabeligt ugyldigt og bruges aldrig i serious historisk forskning om Holocaust","Eksperimentet viser at Holocaust kun var mulig fordi tyskerne genetisk er mere lydige end andre folk"],"correct":"Eksperimentet viste at ordinaere mennesker er villige til at paafore andre alvorlig skade naar en autoritetsfigur beordrer dem til det — det undersoetter Hannah Arendts tese om det ondes banalitet og viser at Holocaust ikke kraevede monstre men systemer der normaliserede lydighed","accepted_answers":["Eksperimentet viste at ordinaere mennesker er villige til at paafore andre alvorlig skade naar en autoritetsfigur beordrer dem til det — det undersoetter Hannah Arendts tese om det ondes banalitet og viser at Holocaust ikke kraevede monstre men systemer der normaliserede lydighed"],"review_text":"Stanley Milgram udfoerte sit lydigheds-eksperiment i 1961. Forsogspersoner blev bedt om at give elektrisk stoed til en skuespiller i et andet rum. 65 procent gave de staerkeste stoed paa trods af hoere raab. Milgram fortolkede det som lydighed over for autoritet under et system der frigjorde individet fra ansvar. Hannah Arendt moenttede begrebet det ondes banalitet om Eichmann — en bureaukrat der organiserede Holocaust ikke af had men af embedslydig. Moralsk ondskab kraever ikke monstre — det kraever systemer der normaliserer ondskab."}$c19q$::jsonb,
  'mc','short',$c19m${"concepts":["Milgram","lydighed","autoritet","Arendt","det ondes banalitet","psykologi og Holocaust"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}$c19m$::jsonb,
  'mc_single',5,'auto',true,'world_war_2',7,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c20q${"question":"Hvad er den vigtigste historiske lektie fra 2. Verdenskrig for forstaaelsen af demokratiets skroebelighed?","options":["At demokratier kan demokratisk vaelge en leder der afvikler demokratiet — Hitlers magtovertagelse var ikke et kup men et produkt af valgsystemets sammenbrud under ekstrem okonomisk krise der forpligter nutidige demokratier til aktiv forfatningsbeskyttelse","Demokratier er naturligt selvopretholdte og kan aldrig kollapse indefra — 2. Verdenskrig er et unikt historisk undtagelsestilfaelde","Lektien fra 2. Verdenskrig er udelukkende militaer: demokratier skal have staerke haere for at forhindre invasion","Demokratiet var ikke under pres i 2. Verdenskrig — Hitler kom til magten via militaerkup ikke demokratiske valg"],"correct":"At demokratier kan demokratisk vaelge en leder der afvikler demokratiet — Hitlers magtovertagelse var ikke et kup men et produkt af valgsystemets sammenbrud under ekstrem okonomisk krise der forpligter nutidige demokratier til aktiv forfatningsbeskyttelse","accepted_answers":["At demokratier kan demokratisk vaelge en leder der afvikler demokratiet — Hitlers magtovertagelse var ikke et kup men et produkt af valgsystemets sammenbrud under ekstrem okonomisk krise der forpligter nutidige demokratier til aktiv forfatningsbeskyttelse"],"review_text":"Weimarrepublikkens kollaps er demokratihistoriens mest studerede fallit. Hyperinflation i 1923, Verdenskrisen fra 1929 og politisk fragmentering skabte kaos som Hitler udnyttede. I januar 1933 blev Hitler udnaevnt til kansler af Hindenburg — ad legal vej, ikke ved statskup. Den demokratiske institution valgte sin egen baeddelmand. Demokrati er ikke en selvfoelge men kraever aktiv vedligeholdelse, forfatningsbeskyttelse og borgere der forsvarer dets principper ogsaa under krisetider."}$c20q$::jsonb,
  'mc','short',$c20m${"concepts":["demokratiets skroebelighed","Weimarrepublikken","Hitler","forfatningsbeskyttelse","valgsystemets sammenbrud","borgerpligt"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}$c20m$::jsonb,
  'mc_single',5,'auto',true,'world_war_2',7,5
);;
