-- Section 101 — Cold War Grade 7 Expansion Sprint
-- Closes the remaining Grade 7 content gap after Section 100 (WW2):
-- Grade 7 had 0 accessible cold_war questions.
--
-- 25 questions: target_grade=7, domain=cold_war, is_active=true
-- Band distribution: B1×6, B2×7, B3×7, B4×5
--
-- Topic coverage: USA vs Sovjet, capitalism vs communism, Iron Curtain,
-- Berlin Wall, NATO, Warsaw Pact, Cuba crisis, nuclear weapons,
-- everyday life, Denmark in the Cold War, end of Cold War.
-- Misconceptions actively targeted throughout.

-- ─── GRADE 7 · BAND 1 (6 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad kendetegnede Den Kolde Krig?","options":["En politisk og militær spænding mellem USA og Sovjet uden direkte krig dem imellem","En krig med store kamphandlinger i Europa mellem 1945 og 1991","En handelskrig der lukkede alle grænser mellem Øst og Vest","Et system hvor alle europæiske lande blev tvunget til at vælge side militært"],"correct":"En politisk og militær spænding mellem USA og Sovjet uden direkte krig dem imellem","accepted_answers":["En politisk og militær spænding mellem USA og Sovjet uden direkte krig dem imellem"],"review_text":"Den Kolde Krig (ca. 1947-1991) var en intens spænding og magtkamp mellem USA og Sovjet-Unionen. Der var ingen direkte kamp mellem de to supermagter — krigen var kold fordi der ikke blev skudt direkte på hinanden. I stedet konkurrerede de med atomvåben, propaganda og politisk indflydelse globalt."}'::jsonb,
  'mc','short','{"concepts":["Den Kolde Krig","definition","USA","Sovjet","spænding"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',1,'auto',true,'cold_war',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvorfor kaldtes konflikten den Kolde Krig?","options":["Fordi USA og Sovjet aldrig kæmpede direkte mod hinanden — det var en spænding uden åben krig","Fordi de fleste slag fandt sted i kolde klimaer i Arktis og Sibirien","Fordi krigen foregik om vinteren og sluttede hver sommer","Fordi begge lande afviste at bruge varme våben og kun brugte kemiske våben"],"correct":"Fordi USA og Sovjet aldrig kæmpede direkte mod hinanden — det var en spænding uden åben krig","accepted_answers":["Fordi USA og Sovjet aldrig kæmpede direkte mod hinanden — det var en spænding uden åben krig"],"review_text":"Krigen var kold fordi USA og Sovjet aldrig skød direkte på hinanden — det ville have betydet atomkrig og muligvis verdens undergang. I stedet kæmpede de med propaganda, spionage, atomvåben-trusler og støtte til allierede lande i andre krige. Spændingen var reel — men den direkte konfrontation undgik man."}'::jsonb,
  'mc','short','{"concepts":["kold krig","betegnelse","ingen direkte krig","spænding","misconception-kold-klima"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',1,'auto',true,'cold_war',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvem stod over for hinanden i Den Kolde Krig?","options":["USA og dets vestlige allierede mod Sovjet-Unionen og de kommunistiske lande i Øst","Frankrig og England mod Rusland og Kina","NATO-landene mod Folkeforbundet","Alle demokratier i verden mod alle diktaturer"],"correct":"USA og dets vestlige allierede mod Sovjet-Unionen og de kommunistiske lande i Øst","accepted_answers":["USA og dets vestlige allierede mod Sovjet-Unionen og de kommunistiske lande i Øst"],"review_text":"Den Kolde Krig stod primært mellem USA (kapitalisme, demokrati, Vesten) og Sovjet-Unionen (kommunisme, Østen). Begge samlede allierede: USA ledte NATO med Vesteuropa og Canada. Sovjet ledte Warszawapagten med Østeuropa. Det var en global ideologisk og magtpolitisk konfrontation."}'::jsonb,
  'mc','short','{"concepts":["USA","Sovjet","allierede","Vesten","Østen"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',1,'auto',true,'cold_war',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var NATOs formål under Den Kolde Krig?","options":["En militær alliance der samlede vestlige lande med løftet om at forsvare hinanden mod et Sovjet-angreb","En FN-organisation til at mægle i konflikter mellem Øst og Vest","En handelsaftale der udelukkede kommunistiske lande fra det globale marked","Et atomvåbenprogram ledet af USA til at angribe Sovjet"],"correct":"En militær alliance der samlede vestlige lande med løftet om at forsvare hinanden mod et Sovjet-angreb","accepted_answers":["En militær alliance der samlede vestlige lande med løftet om at forsvare hinanden mod et Sovjet-angreb"],"review_text":"NATO (North Atlantic Treaty Organization) blev grundlagt i 1949. Kernen var kollektivt forsvar: hvis et NATO-land angribes, hjælper alle de andre. Det var Vestens svar på frygten for et Sovjet-angreb på Vesteuropa. Danmark var med fra starten — og er stadig med i dag."}'::jsonb,
  'mc','short','{"concepts":["NATO","kollektivt forsvar","1949","Vesteuropa","Danmark"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',1,'auto',true,'cold_war',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad skete der med Berlinmuren den 9. november 1989?","options":["Berlinmuren faldt — Østtyske borgere brød igennem og muren blev revet ned","Berlinmuren blev forstærket efter protester fra Vestberlin","USA og Sovjet underskrev en aftale om at bevare muren som grænse","NATO-styrker sprængte muren i forbindelse med en militær operation"],"correct":"Berlinmuren faldt — Østtyske borgere brød igennem og muren blev revet ned","accepted_answers":["Berlinmuren faldt — Østtyske borgere brød igennem og muren blev revet ned"],"review_text":"Den 9. november 1989 faldt Berlinmuren. Østtyske borgere der havde demonstreret i ugevis brød igennem. Det var et historisk øjeblik — et symbol på at Den Kolde Krig var ved at slutte. Millioner af tyskere mødtes igen. To år efter opløstes Sovjet-Unionen i 1991 og Den Kolde Krig var officielt slut."}'::jsonb,
  'mc','short','{"concepts":["Berlinmuren","9. november 1989","fald","Østtyskland","befrielse"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',1,'auto',true,'cold_war',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var Berlinmuren, og hvem byggede den?","options":["En mur bygget af Østtyskland i 1961 for at forhindre borgere i at flygte fra Øst til Vestberlin","En mur bygget af NATO for at beskytte Vestberlin mod et Sovjet-angreb","En sikkerhedsmur bygget af FN for at adskille de to supermagters soldater","En mur bygget af Vestberlin for at holde østtyske agenter ude"],"correct":"En mur bygget af Østtyskland i 1961 for at forhindre borgere i at flygte fra Øst til Vestberlin","accepted_answers":["En mur bygget af Østtyskland i 1961 for at forhindre borgere i at flygte fra Øst til Vestberlin"],"review_text":"Berlinmuren blev bygget natten til den 13. august 1961 — af Østtyskland. Grunden: millioner af østtyskere flygtede til Vestberlin og Vesttyskland. Muren skulle stoppe flugten. Den lukkede østberlinerne inde — ikke vesterlændingene ude. Det var en mur rettet mod egne borgere, ikke mod ydre fjender."}'::jsonb,
  'mc','short','{"concepts":["Berlinmuren","1961","Østtyskland","flugt","misconception-holdt-vesten-ude"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',1,'auto',true,'cold_war',7,1
);

-- ─── GRADE 7 · BAND 2 (7 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad mente man med kapitalisme i USA og kommunisme i Sovjet under Den Kolde Krig?","options":["I kapitalisme ejede private virksomheder og markedet bestemte priser — i kommunisme ejede staten alt og styrede fordelingen","Kapitalisme betød fri religion og kommunisme betød obligatorisk statskirke","Kapitalisme var et militærsystem og kommunisme et fredssystem","Det var to navne for det samme økonomi-system med forskellige politiske symboler"],"correct":"I kapitalisme ejede private virksomheder og markedet bestemte priser — i kommunisme ejede staten alt og styrede fordelingen","accepted_answers":["I kapitalisme ejede private virksomheder og markedet bestemte priser — i kommunisme ejede staten alt og styrede fordelingen"],"review_text":"Kapitalisme (USA): private virksomheder og frie markeder — du kan eje en virksomhed og konkurrere. Kommunisme (Sovjet): staten ejer og fordeler alt — ingen private virksomheder, staten planlægger økonomi. Det var to fundamentalt modsatte ideer om økonomi og frihed. Det var kernen i Den Kolde Krigs ideologiske konflikt."}'::jsonb,
  'mc','short','{"concepts":["kapitalisme","kommunisme","ideologi","økonomi","USA-Sovjet"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',2,'auto',true,'cold_war',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var Jerntæppet, og hvad delte det?","options":["En politisk og ideologisk grænse der delte Europa i et frit vestligt demokrati og et kommunistisk kontrolleret Øst","En faktisk stålmur der gik fra Nordpolen til Middelhavet","Et handelssystem der forbød handel mellem de to supermagter","Et andet navn for Berlinmuren som var den eneste egentlige grænse i Europa"],"correct":"En politisk og ideologisk grænse der delte Europa i et frit vestligt demokrati og et kommunistisk kontrolleret Øst","accepted_answers":["En politisk og ideologisk grænse der delte Europa i et frit vestligt demokrati og et kommunistisk kontrolleret Øst"],"review_text":"Jerntæppet var ikke en fysisk mur overalt — det var en politisk og ideologisk grænse. Vest for tæppet: demokrati og markedsøkonomi. Øst for tæppet: kommunisme under Sovjet-kontrol. Borgere på begge sider var reelt låst fast på deres side. Winston Churchill beskrev det første gang i en berømt tale i 1946."}'::jsonb,
  'mc','short','{"concepts":["Jerntæppet","Europa-deling","Øst","Vest","politisk grænse"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',2,'auto',true,'cold_war',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var Warszawapagten, og hvad adskilte den fra NATO?","options":["Warszawapagten var Sovjet-Unionens militæralliance med Østeuropa — Sovjet kontrollerede den i praksis mens NATO var et samarbejde af ligeværdige demokratier","Warszawapagten var en fredsaftale som Sovjet og NATO underskrev i fællesskab for at undgå krig","Warszawapagten var en humanitær organisation der hjalp fattige lande i Østeuropa","Warszawapagten og NATO var identiske systemer med de samme regler bare i hvert sit hjørne af Europa"],"correct":"Warszawapagten var Sovjet-Unionens militæralliance med Østeuropa — Sovjet kontrollerede den i praksis mens NATO var et samarbejde af ligeværdige demokratier","accepted_answers":["Warszawapagten var Sovjet-Unionens militæralliance med Østeuropa — Sovjet kontrollerede den i praksis mens NATO var et samarbejde af ligeværdige demokratier"],"review_text":"Warszawapagten (1955) var Sovjet-Unionens svar på NATO — en militæralliance med Østeuropas kommunistiske lande. Forskellen: NATO var et samarbejde af demokratier med USA som den stærkeste. Warszawapagten var reelt kontrolleret af Sovjet alene — de østeuropæiske lande havde begrænset selvbestemmelse i praksis."}'::jsonb,
  'mc','short','{"concepts":["Warszawapagten","NATO","militæralliance","Sovjet","Østeuropa"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',2,'auto',true,'cold_war',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var Cuba-krisen i 1962?","options":["En 13 dage lang konfrontation da Sovjet placerede atomraketter på Cuba tæt på USA og verden kom nærmere atomkrig end nogensinde","En cubansk borgerkrig som USA og Sovjet støttede hver sin side i","Et amerikansk forsøg på at invadere Cuba for at befri befolkningen fra kommunisme","En diplomatisk krise da Cuba ansøgte om at blive optaget i NATO"],"correct":"En 13 dage lang konfrontation da Sovjet placerede atomraketter på Cuba tæt på USA og verden kom nærmere atomkrig end nogensinde","accepted_answers":["En 13 dage lang konfrontation da Sovjet placerede atomraketter på Cuba tæt på USA og verden kom nærmere atomkrig end nogensinde"],"review_text":"Cuba-krisen i oktober 1962 var Den Kolde Krigs farligste øjeblik. Sovjet placerede atomraketter på Cuba — 150 km fra USA. USA opdagede det og krævede dem fjernet. I 13 spændende dage var verden tæt på atomkrig. Til sidst trak Sovjet raketterne tilbage. En diplomatisk løsning der reddede verden fra katastrofe."}'::jsonb,
  'mc','short','{"concepts":["Cuba-krisen","1962","atomraketter","13 dage","atomkrig-trussel"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',2,'auto',true,'cold_war',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betød det for hverdagen at Danmark var med i NATO under Den Kolde Krig?","options":["Danmark var en del af det vestlige forsvar og danskerne levede med en reel baggrundsfrygt for at atomkrig kunne bryde ud","Det betød at Danmark var aktivt i krig med Sovjet hele perioden","Det betød at Danmark fik atomvåben placeret på sit territorium som en betingelse for NATO-medlemskab","Det betød at danske soldater kæmpede i Korea og Vietnam"],"correct":"Danmark var en del af det vestlige forsvar og danskerne levede med en reel baggrundsfrygt for at atomkrig kunne bryde ud","accepted_answers":["Danmark var en del af det vestlige forsvar og danskerne levede med en reel baggrundsfrygt for at atomkrig kunne bryde ud"],"review_text":"Som NATO-land var Danmark på den vestlige side. Danske soldater øvede sig i at forsvare landet mod en eventuel Sovjet-invasion. Der var reelle planer og beredskab. Danskerne levede med en baggrundsfrygt — hvad nu hvis krigen startede? Atomvåben kunne ramme alle. Men krigen kom aldrig til Danmark."}'::jsonb,
  'mc','short','{"concepts":["Danmark","NATO","hverdagsfrygt","atomkrig","beredskab"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',2,'auto',true,'cold_war',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var rumkapløbet og hvad handlede det egentlig om?","options":["En konkurrence mellem USA og Sovjet om at nå længst ud i rummet — men egentlig en ideologisk prestigekamp om hvems samfundssystem der var bedst","En videnskabelig aftale mellem USA og Sovjet om fælles rumforskning","En militær konkurrence om at placere atomraketter i rummet","En international konkurrence som alle lande deltog i på lige vilkår"],"correct":"En konkurrence mellem USA og Sovjet om at nå længst ud i rummet — men egentlig en ideologisk prestigekamp om hvems samfundssystem der var bedst","accepted_answers":["En konkurrence mellem USA og Sovjet om at nå længst ud i rummet — men egentlig en ideologisk prestigekamp om hvems samfundssystem der var bedst"],"review_text":"Rumkapløbet begyndte da Sovjet sendte Sputnik op i 1957 — verdens første satellit. USA var chokerede. Bagefter konkurrerede de to supermagter om hvem der nåede Månen, sendte den første mand i rummet osv. Men det var ikke blot videnskab — det var propaganda: hvis vi kan komme i rummet beviser vi at vores system er bedst."}'::jsonb,
  'mc','short','{"concepts":["rumkapløb","Sputnik","prestige","ideologi","propaganda"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',2,'auto',true,'cold_war',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var den vigtigste forskel på hverdagen for borgere i Vesteuropa og Østeuropa under Den Kolde Krig?","options":["Borgere i Vest kunne rejse frit, læse frie aviser og eje virksomheder — borgere i Øst levede under statsovervågning, censur og rejsebegrænsninger","Borgere i Vest var fattigere mens borgere i Øst levede i relativ velstand","Borgere i Vest måtte ikke stemme til valg mens Øst havde demokratiske valg hvert år","Forskellen var minimal — begge sider levede under de samme grundlæggende rettigheder"],"correct":"Borgere i Vest kunne rejse frit, læse frie aviser og eje virksomheder — borgere i Øst levede under statsovervågning, censur og rejsebegrænsninger","accepted_answers":["Borgere i Vest kunne rejse frit, læse frie aviser og eje virksomheder — borgere i Øst levede under statsovervågning, censur og rejsebegrænsninger"],"review_text":"I Vesteuropa: ytringsfrihed, fri presse, ret til at rejse, private virksomheder, demokratiske valg. I Østeuropa: staten overvågede borgerne, aviser var kontrollerede, det var farligt at kritisere regimet og man måtte ikke frit rejse til Vest. Den ideologiske konflikt var ikke abstrakt — den påvirkede virkelige menneskers dagligliv konkret."}'::jsonb,
  'mc','short','{"concepts":["hverdagsliv","frihed","Vest","Øst","censur","overvågning"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"cold_war"}'::jsonb,
  'mc_single',2,'auto',true,'cold_war',7,2
);

-- ─── GRADE 7 · BAND 3 (7 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvorfor opstod Den Kolde Krig netop efter 2. Verdenskrig?","options":["Fordi USA og Sovjet som de eneste tilbageværende supermagter pludselig stod alene med modsatrettede ideologier efter at den fælles fjende Hitler var besejret","Fordi FN tvang USA og Sovjet til at vælge side i en konflikt de ellers ikke ønskede","Fordi Sovjet invaderede Vesteuropa umiddelbart efter 2. Verdenskrig","Fordi USA valgte at bruge atombomben mod Japan og dermed provokerede Sovjet"],"correct":"Fordi USA og Sovjet som de eneste tilbageværende supermagter pludselig stod alene med modsatrettede ideologier efter at den fælles fjende Hitler var besejret","accepted_answers":["Fordi USA og Sovjet som de eneste tilbageværende supermagter pludselig stod alene med modsatrettede ideologier efter at den fælles fjende Hitler var besejret"],"review_text":"Under 2. Verdenskrig samarbejdede USA og Sovjet mod Hitler. Da Hitler var besejret forsvandt grundlaget for samarbejdet. Nu stod to modsatrettede systemer — demokrati og kapitalisme mod kommunisme — som de dominerende magter i en ødelagt verden. Mistillid og konkurrence om indflydelse i Europa eskalerede hurtigt til Den Kolde Krig."}'::jsonb,
  'mc','short','{"concepts":["årsager","2. Verdenskrig","ideologi","Hitler","supermagter","mistillid"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"cold_war"}'::jsonb,
  'mc_single',3,'auto',true,'cold_war',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var sammenhængen mellem NATO og Warszawapagten?","options":["NATO og Warszawapagten var to modsatrettede militæralliancer — og hver gang én side forstærkede sig, svarede den anden med endnu mere oprustning i en selvforstærkende spiral","NATO og Warszawapagten blev oprettet i fællesskab for at sikre stabiliteten i Europa","Warszawapagten var oprettet for at udfordre NATO men havde aldrig reel militær kapacitet","De to alliancer eksisterede uafhængigt af hinanden med minimalt kendskab til den andens aktiviteter"],"correct":"NATO og Warszawapagten var to modsatrettede militæralliancer — og hver gang én side forstærkede sig, svarede den anden med endnu mere oprustning i en selvforstærkende spiral","accepted_answers":["NATO og Warszawapagten var to modsatrettede militæralliancer — og hver gang én side forstærkede sig, svarede den anden med endnu mere oprustning i en selvforstærkende spiral"],"review_text":"NATO i 1949 → Sovjet svarede med Warszawapagten i 1955. Begge alliancers oprustning begrundede den andens oprustning. Det var et sikkerhedsdilemma: jo mere fjenden rustede op, jo mere måtte man selv ruste op. Den spiral fastholdt spændingen i årtier og kostede billioner."}'::jsonb,
  'mc','short','{"concepts":["NATO","Warszawapagten","sikkerhedsdilemma","oprustning","spiral"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"cold_war"}'::jsonb,
  'mc_single',3,'auto',true,'cold_war',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad viser Cuba-krisen i 1962 om risikoen for atomkrig?","options":["At selv to rationelle stater drevet af mistillid og prestige kan bringe verden på randen af atomkrig — og at det kræver kommunikation på højeste niveau at forhindre katastrofen","At Cuba-krisen beviste at atomvåben altid garanterer fred da ingen turde bruge dem","At USA vandt Den Kolde Krig på Cuba-krisen da Sovjet viste svaghed","At Cuba var den eneste egentlige trussel mod verdensfreden i hele Den Kolde Krigs periode"],"correct":"At selv to rationelle stater drevet af mistillid og prestige kan bringe verden på randen af atomkrig — og at det kræver kommunikation på højeste niveau at forhindre katastrofen","accepted_answers":["At selv to rationelle stater drevet af mistillid og prestige kan bringe verden på randen af atomkrig — og at det kræver kommunikation på højeste niveau at forhindre katastrofen"],"review_text":"Cuba-krisen viste at to lande der begge ønskede at undgå krig alligevel næsten havnede i atomkrig — drevet af mistillid, frygt og prestige. Det var kun direkte kommunikation mellem Kennedy og Khrusjtjov der forhindrede katastrofen. En enkelt fejlvurdering kunne have ændret historien."}'::jsonb,
  'mc','short','{"concepts":["Cuba-krisen","atomkrig","mistillid","prestige","kommunikation"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"cold_war"}'::jsonb,
  'mc_single',3,'auto',true,'cold_war',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Var Den Kolde Krig fredeligt fordi USA og Sovjet aldrig skød på hinanden?","options":["Nej — millioner døde i proxy-krige i Korea, Vietnam og Afghanistan hvor USA og Sovjet støttede modsatrettede sider","Ja — Den Kolde Krig var fuldstændig fredeligt og ingen døde som følge af konflikten","Ja — undtagen Cuba-krisen var der ingen militære konflikter overhovedet i perioden","Nej — USA og Sovjet kæmpede direkte mod hinanden i tre store krige"],"correct":"Nej — millioner døde i proxy-krige i Korea, Vietnam og Afghanistan hvor USA og Sovjet støttede modsatrettede sider","accepted_answers":["Nej — millioner døde i proxy-krige i Korea, Vietnam og Afghanistan hvor USA og Sovjet støttede modsatrettede sider"],"review_text":"Den Kolde Krig var ikke fredeligt for dem der boede i Koreas jungler, Vietnams rismarker eller Afghanistans bjerge. Millioner døde i proxy-krige — krige hvor USA og Sovjet støttede modsatte sider uden at kæmpe direkte. De to supermagter undgik direkte konfrontation men lod andre betale prisen med livet."}'::jsonb,
  'mc','short','{"concepts":["proxy-krig","Korea","Vietnam","Afghanistan","misconception-fredeligt"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"cold_war"}'::jsonb,
  'mc_single',3,'auto',true,'cold_war',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var de daglige begrænsninger for borgere bag Jerntæppet i Østeuropa?","options":["De måtte ikke rejse frit til Vest, aviser var censurerede, telefonopkald kunne overvåges og kritik af regimet kunne føre til fængsel","Borgere bag Jerntæppet levede under de samme vilkår som vestlige borgere men med et andet valgsystem","De eneste begrænsninger var at man ikke måtte eje bil eller ejendom","Begrænsningerne var primært religiøse — man måtte ikke udøve religion under det kommunistiske styre"],"correct":"De måtte ikke rejse frit til Vest, aviser var censurerede, telefonopkald kunne overvåges og kritik af regimet kunne føre til fængsel","accepted_answers":["De måtte ikke rejse frit til Vest, aviser var censurerede, telefonopkald kunne overvåges og kritik af regimet kunne føre til fængsel"],"review_text":"Livet bag Jerntæppet var konkret begrænsende. Du måtte ikke bare tage på ferie i Vesteuropa. Aviser fortalte ikke sandheden om Vesten. Telefoner kunne aflyttes. Naboer kunne rapportere til hemmeligt politi. Kritik af kommunismen var farligt. Det var ikke abstrakt politik — det var hverdagens fravær af frihed."}'::jsonb,
  'mc','short','{"concepts":["Jerntæppet","hverdagsliv","censur","overvågning","rejsefrihed","frygt"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"cold_war"}'::jsonb,
  'mc_single',3,'auto',true,'cold_war',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betød det for verden at to supermagter hver ejede tusindvis af atomvåben?","options":["En enkelt fejlvurdering eller ulykke kunne potentielt udslette menneskeheden — og dermed lagde en permanent skygge af angst over hele Den Kolde Krig","Det betød at atomvåbnene garanterede evig fred da ingen nogensinde ville turde bruge dem","Det betød at kun de to supermagters soldater var i fare og resten af verden var i sikkerhed","Det betød at atomvåbnene aldrig udgjorde en reel trussel da begge sider vidste de aldrig ville blive brugt"],"correct":"En enkelt fejlvurdering eller ulykke kunne potentielt udslette menneskeheden — og dermed lagde en permanent skygge af angst over hele Den Kolde Krig","accepted_answers":["En enkelt fejlvurdering eller ulykke kunne potentielt udslette menneskeheden — og dermed lagde en permanent skygge af angst over hele Den Kolde Krig"],"review_text":"Tusindvis af atomvåben på hver side betød at en krig kunne udslette hele civilisationer. MAD-logikken (Mutual Assured Destruction) sagde: angriber du, ødelægger vi begge. Det forhindrede muligvis direkte krig. Men det betød at enhver krise — som Cuba — potentielt kunne ende med dommedag. Den permanente atomtrussel prægede hele periodens psykologi."}'::jsonb,
  'mc','short','{"concepts":["atomvåben","MAD","dommedagstrussel","angst","menneskeheden"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"cold_war"}'::jsonb,
  'mc_single',3,'auto',true,'cold_war',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad forbandt Gorbatjovs reformer med Berlinmurens fald i 1989?","options":["Gorbatjovs reformer signalerede at Sovjet ikke længere ville sende tropper for at undertrykke borgeroprør i Østeuropa og det gav borgerne modet til at protestere","Gorbatjov beordrede selv Berlinmuren revet ned som et diplomatisk signal til Vesten","Berlinmurens fald foranledigede Gorbatjovs reformer — ikke den anden vej rundt","Gorbatjovs reformer var udelukkende økonomiske og påvirkede ikke det politiske klima i Østeuropa"],"correct":"Gorbatjovs reformer signalerede at Sovjet ikke længere ville sende tropper for at undertrykke borgeroprør i Østeuropa og det gav borgerne modet til at protestere","accepted_answers":["Gorbatjovs reformer signalerede at Sovjet ikke længere ville sende tropper for at undertrykke borgeroprør i Østeuropa og det gav borgerne modet til at protestere"],"review_text":"Gorbatjov kom til magten i 1985 og lancerede glasnost (åbenhed) og perestrojka (omstrukturering). Vigtigst: han signalerede at Sovjet ikke ville sende tanks mod borgeroprør. Østeuropæerne forstod budskabet. Masseprotester bredte sig. Den 9. november 1989 faldt muren — ikke fordi Gorbatjov beordrede det, men fordi hans reformer fjernede frygten for Sovjet-indgreb."}'::jsonb,
  'mc','short','{"concepts":["Gorbatjov","glasnost","perestrojka","Berlinmuren","reformer","borgeroprør"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"cold_war"}'::jsonb,
  'mc_single',3,'auto',true,'cold_war',7,3
);

-- ─── GRADE 7 · BAND 4 (5 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad lærer Den Kolde Krig os om hvad der sker når to supermagter har uforenelige ideologier og atomvåben?","options":["At selv to systemer der begge frygter ødelæggelse kan fastholde en farlig og kostbar spænding i årtier drevet af mistillid, prestige og ideologisk uforsonlighed","At atomvåben altid garanterer fred da ingen rationel aktør vil starte en atomkrig","At ideologiske konflikter altid ender i krig da kompromis er umuligt","At supermagter altid finder rationelle løsninger på konflikter når risikoen er stor nok"],"correct":"At selv to systemer der begge frygter ødelæggelse kan fastholde en farlig og kostbar spænding i årtier drevet af mistillid, prestige og ideologisk uforsonlighed","accepted_answers":["At selv to systemer der begge frygter ødelæggelse kan fastholde en farlig og kostbar spænding i årtier drevet af mistillid, prestige og ideologisk uforsonlighed"],"review_text":"Den Kolde Krig varede 45 år og kostede billioner af dollars, millioner af liv i proxy-krige og skabte en permanent atomtrussel. Det viser at selv frygten for gensidig ødelæggelse ikke eliminerer konflikten — den ændrer bare dens form. Ideologi og prestige driver beslutninger ligeså meget som rationel kalkulation."}'::jsonb,
  'mc','short','{"concepts":["ideologi","atomvåben","mistillid","prestige","sikkerhedsdilemma","lektie"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',4,'auto',true,'cold_war',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad viser Berlinmurens fald om borgernes evne til at påvirke historien?","options":["At borgerdemonstrationer under de rette historiske betingelser kan vælte systemer der troede sig uovervindelige — uden et eneste skud","At det var diplomatiske forhandlinger mellem supermagterne og ikke borgerne der egentlig fældte muren","At Berlinmurens fald var et tilfælde forårsaget af en embedsmands fejlmeldning og ikke et udtryk for borgervilje","At borgerne ikke spillede nogen afgørende rolle — det var NATO-presset der tvang Østtyskland til at åbne muren"],"correct":"At borgerdemonstrationer under de rette historiske betingelser kan vælte systemer der troede sig uovervindelige — uden et eneste skud","accepted_answers":["At borgerdemonstrationer under de rette historiske betingelser kan vælte systemer der troede sig uovervindelige — uden et eneste skud"],"review_text":"Millioner af østtyskere demonstrerede i efteråret 1989. Det var borgermodet der tvang forandringen. Den 9. november foranledigede en embedsmands fejlagtige erklæring at grænsen åbnede — men bag den fejl var uger af masseprotester der havde gjort systemet uholdbart. Borgeraktion under de rette historiske betingelser kan ændre verden."}'::jsonb,
  'mc','short','{"concepts":["Berlinmurens fald","borgermagt","demonstration","historisk forandring","civilsamfund"],"misconception_type":"scope_confusion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',4,'auto',true,'cold_war',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er det mest præcise svar på spørgsmålet om hvem der vandt Den Kolde Krig?","options":["USA og Vesten vandt i den forstand at Sovjet-systemet kollapsede — men den langsigtede verden er mere kompleks end en simpel vinder-taber-fortælling","Sovjet vandt fordi de i årtier modsatte sig USA og overlevede den militære konkurrence","Det var uafgjort da ingen af supermagternes centrale mål blev nået","FN vandt da de forhindrede krig ved at mægle i alle konflikter"],"correct":"USA og Vesten vandt i den forstand at Sovjet-systemet kollapsede — men den langsigtede verden er mere kompleks end en simpel vinder-taber-fortælling","accepted_answers":["USA og Vesten vandt i den forstand at Sovjet-systemet kollapsede — men den langsigtede verden er mere kompleks end en simpel vinder-taber-fortælling"],"review_text":"Sovjet-Unionen opløste sig selv i 1991 — USA og kapitalisme vandt den ideologiske kamp. Men sejr er kompleks: millioner døde i proxy-krige, atomvåbnene eksisterer stadig og nye autoritære regimer voksede frem. Rusland spiller fortsat en geopolitisk rolle. Den enkle vinder-taber-fortælling skjuler virkeligheder der stadig former verden."}'::jsonb,
  'mc','short','{"concepts":["sejr","Sovjet-sammenbrud","USA","kompleksitet","geopolitisk arv"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',4,'auto',true,'cold_war',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad kendetegner verden i dag som direkte resultat af Den Kolde Krig?","options":["NATO eksisterer stadig, Rusland er fortsat en atommagt med geopolitiske ambitioner og konflikter i tidligere proxy-krigs-zoner er uløste","Den Kolde Krig efterlod ingen varige spor da alt normaliserede sig hurtigt i 1991","Den vigtigste arv er at USA og Rusland nu er nære allierede med stærke handelsrelationer","Den Kolde Krigs arv er primært kulturel og politiske relationer er fuldt normaliserede"],"correct":"NATO eksisterer stadig, Rusland er fortsat en atommagt med geopolitiske ambitioner og konflikter i tidligere proxy-krigs-zoner er uløste","accepted_answers":["NATO eksisterer stadig, Rusland er fortsat en atommagt med geopolitiske ambitioner og konflikter i tidligere proxy-krigs-zoner er uløste"],"review_text":"Den Kolde Krig sluttede men dens spor er overalt. NATO eksisterer og er udvidet. Rusland ønsker fortsat geopolitisk indflydelse. Atommagtspørgsmålet er uløst. Korea er stadig delt. De lande der var proxy-krige kæmper stadig med arven. At forstå verden i dag kræver at man forstår Den Kolde Krig."}'::jsonb,
  'mc','short','{"concepts":["arv","NATO","Rusland","atomvåben","geopolitik","nutid"],"misconception_type":"scope_confusion","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',4,'auto',true,'cold_war',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad lærer Den Kolde Krig os om forholdet mellem frygt, ideologi og politiske beslutninger?","options":["At frygt og ideologisk overbevisning kan fastholde lande i årtiers kostbar konflikt fordi mistillid gør kompromis næsten umuligt","At frygt altid er irrationel og let kan overvindes ved ærlig kommunikation og dialog","At ideologi spiller en minimal rolle — økonomi er den eneste drivkraft for internationale beslutninger","At Den Kolde Krig beviste at frygt er det bedste fundament for international stabilitet"],"correct":"At frygt og ideologisk overbevisning kan fastholde lande i årtiers kostbar konflikt fordi mistillid gør kompromis næsten umuligt","accepted_answers":["At frygt og ideologisk overbevisning kan fastholde lande i årtiers kostbar konflikt fordi mistillid gør kompromis næsten umuligt"],"review_text":"Den Kolde Krig var drevet af gensidig frygt og ideologisk uforsonlighed. Frygten var ikke irrationel — atomvåben var reelle. Men frygten forhindrede den tillid der var nødvendig for at finde løsninger. Propagandaen cementerede billedet af fjenden som eksistentiel trussel. Den cyklus af frygt, mistillid og oprustning gentager sig i nutidens internationale relationer."}'::jsonb,
  'mc','short','{"concepts":["frygt","ideologi","mistillid","oprustning","politiske beslutninger","lektie"],"misconception_type":"scope_confusion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',4,'auto',true,'cold_war',7,4
);
