-- Section 80 — Middle Ages Content Sprint
-- 50 questions: Grade 5 (25) + Grade 6 (25). Opens Grade 6 for the first time.
-- Bands: B1×12, B2×14, B3×14, B4×10
-- Concepts: castles, feudalism, church, monasteries, villages, farming,
--           trade, towns, guilds, Black Death, everyday life, justice, power
-- Knights/warfare capped at ~8%. All review_text. is_active=true.

-- ─── GRADE 5 · BAND 1 (6 questions) ─────────────────────────────────────────

-- ma_g5b1_01 — Castle purpose
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var den vigtigste funktion for et middelalderslot?","options":["At beskytte den lokale adelsmand og hans folk fra angreb","Et luksus-hjem til store fester og banketter","Et fængsel til at holde kriminelle","Et handelscenter for byens markeder"],"correct":"At beskytte den lokale adelsmand og hans folk fra angreb","accepted_answers":["At beskytte den lokale adelsmand og hans folk fra angreb"],"review_text":"Middelalderslotte blev bygget til forsvar. De tykke mure, vindebro og voldgrav holdt fjender ude. Slottet var base for den adelsmand der kontrollerede det omgivende land — og tilflugtssted for hans bønder i krigstid."}'::jsonb,
  'mc','short','{"concepts":["slot","forsvar","adelsmand","middelalder"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"middle_ages"}'::jsonb,
  'mc_single',1,'auto',true,'middle_ages',5,1
);

-- ma_g5b1_02 — Feudalism basics
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var feudalsystemet i middelalderen?","options":["Et hierarki hvor kongen uddelte jord til adelsmænd mod militær tjeneste, og adelsmændene brugte bønderne til at dyrke landet mod beskyttelse","Et demokratisk system hvor borgerne valgte lokale ledere","En plan kirkerne brugte til at organisere bønnerne","Et handelssystem med faste regler for køb og salg"],"correct":"Et hierarki hvor kongen uddelte jord til adelsmænd mod militær tjeneste, og adelsmændene brugte bønderne til at dyrke landet mod beskyttelse","accepted_answers":["Et hierarki hvor kongen uddelte jord til adelsmænd mod militær tjeneste, og adelsmændene brugte bønderne til at dyrke landet mod beskyttelse"],"review_text":"Feudalisme var middelalderens måde at organisere samfundet på. Kongen ejede alt land men uddelte det mod tjeneste. Adelsmænd fik jord mod at kæmpe. Bønder dyrkede landet mod beskyttelse. Alle var bundet til hinanden i pligter og rettigheder."}'::jsonb,
  'mc','short','{"concepts":["feudalisme","hierarki","kongen","bønder","jord"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"middle_ages"}'::jsonb,
  'mc_single',1,'auto',true,'middle_ages',5,1
);

-- ma_g5b1_03 — Church social role (basic)
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad brugte kirken i middelalderen sine penge på udover gudstjenester?","options":["Hospitaler, skoler og fattigpleje — kirken var det vigtigste sociale sikkerhedsnet","Krige og hære til at erobre nye lande","Luksusvarer til brug for præsterne","Skatter til kongens hær"],"correct":"Hospitaler, skoler og fattigpleje — kirken var det vigtigste sociale sikkerhedsnet","accepted_answers":["Hospitaler, skoler og fattigpleje — kirken var det vigtigste sociale sikkerhedsnet"],"review_text":"Kirken var ikke blot et gudshus. Den drev hospitaler for syge, skoler for drenge og fattigpleje for de mindst bemidlede. Uden kirken fandtes der intet socialt sikkerhedsnet. Det er en af grundene til at kirken var så magtfuld."}'::jsonb,
  'mc','short','{"concepts":["kirkens rolle","hospital","skole","fattigpleje","misconception-kirken-kun-religion"],"misconception_type":"scope_confusion","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"middle_ages"}'::jsonb,
  'mc_single',1,'auto',true,'middle_ages',5,1
);

-- ma_g5b1_04 — Village life
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad beskriver hverdagen i en middelalderlig landsby bedst?","options":["Hårdt markarbejde, fælles ressourcer og sjælden kontakt med omverdenen","Velstående og afslappet liv med masser af handel og rejser","Konstant krig og hyppige angreb fra naboer","Stor frihed og nem mulighed for at flytte til en by"],"correct":"Hårdt markarbejde, fælles ressourcer og sjælden kontakt med omverdenen","accepted_answers":["Hårdt markarbejde, fælles ressourcer og sjælden kontakt med omverdenen"],"review_text":"De fleste middelaldermennesker var bønder i små landsbyer. De dyrkede markerne kollektivt, delte redskaber og kendte sjældent verden udenfor. En bonde kunne leve og dø i den samme landsby som sine forældre og bedsteforældre — uden at have set en by."}'::jsonb,
  'mc','short','{"concepts":["landsby","bønder","hverdagsliv","fællesskab","misconception-alle-i-slotte"],"misconception_type":"overgeneralization","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"middle_ages"}'::jsonb,
  'mc_single',1,'auto',true,'middle_ages',5,1
);

-- ma_g5b1_05 — Black Death basics
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var den Sorte Død?","options":["En pestepidemi der dræbte op til en tredjedel af Europas befolkning i 1300-tallet","Et navn for de mange krige der ødelagde store europæiske byer","En hungersnød forårsaget af dårlige høstsæsoner i 100 år i træk","En vulkaneruption der forandrede Europas klima"],"correct":"En pestepidemi der dræbte op til en tredjedel af Europas befolkning i 1300-tallet","accepted_answers":["En pestepidemi der dræbte op til en tredjedel af Europas befolkning i 1300-tallet"],"review_text":"Den Sorte Død (1347-1351) var den største katastrofe i europæisk middelalder-historie. Bubonpest spredte sig fra Central-Asien via handelsskibe. Op til 30-40% af Europas befolkning døde på få år. Byer, landsbyer og klostre mistede halvdelen af deres beboere."}'::jsonb,
  'mc','short','{"concepts":["Sorte Død","pest","1300-tallet","befolkning"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"middle_ages"}'::jsonb,
  'mc_single',1,'auto',true,'middle_ages',5,1
);

-- ma_g5b1_06 — Guild definition
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var et middelalder-laug?","options":["En organisation af håndværkere i en by der kontrollerede kvalitet, priser og uddannelse inden for sit fag","En religiøs bevægelse der organiserede kirkens velgørenhed","Et militærkorps der forsvarede byens mure","En landsbykomité der fordelte jord til bønderne"],"correct":"En organisation af håndværkere i en by der kontrollerede kvalitet, priser og uddannelse inden for sit fag","accepted_answers":["En organisation af håndværkere i en by der kontrollerede kvalitet, priser og uddannelse inden for sit fag"],"review_text":"Lauget beskyttede sine medlemmer og kontrollererede sit fag. Det fastsatte priser, sikrede kvaliteten og stod for uddannelse: læredreng, svend og mester. Lauget var byens professionelle organisation — og en vigtig grund til at byer var mere end blot markedspladser."}'::jsonb,
  'mc','short','{"concepts":["laug","håndværk","by","kvalitet","uddannelse"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"middle_ages"}'::jsonb,
  'mc_single',1,'auto',true,'middle_ages',5,1
);

-- ─── GRADE 5 · BAND 2 (7 questions) ─────────────────────────────────────────

-- ma_g5b2_01 — Why castles changed with gunpowder
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad skete med middelalderslottenes forsvarsfunktion da krudt og kanoner kom?","options":["De mistede deres militære funktion — kanonkugler slog mure ned som sværd og pile aldrig kunne","De blev endnu stærkere fordi kanonerne ikke var præcise nok til at ramme murene","Slottene forsvandt helt og erstattedes straks af åbne byer","Ridderne opgav slottene og kæmpede nu kun til søs"],"correct":"De mistede deres militære funktion — kanonkugler slog mure ned som sværd og pile aldrig kunne","accepted_answers":["De mistede deres militære funktion — kanonkugler slog mure ned som sværd og pile aldrig kunne"],"review_text":"Middelalderslottenes design var perfekt til middelalderens krig. Men kanonerne ændrede alt i 1400-1500-tallet. Kanonkugler slog de tykke mure ned. Feudalsystemets militære struktur var ikke tilpasset den nye teknologi. Det var én af grundene til at riddersamfundet ændrede sig."}'::jsonb,
  'mc','short','{"concepts":["slot","kanon","krudt","teknologiforandring","feudalisme"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"middle_ages"}'::jsonb,
  'mc_single',2,'auto',true,'middle_ages',5,2
);

-- ma_g5b2_02 — Monasteries and knowledge
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var klostrenes vigtigste bidrag til bevarelsen af viden?","options":["Munke kopierede og bevarede bøger — uden dem var megen antik viden gået tabt for evigt","Klostrene opfandt bogtrykkeriet 200 år før Gutenberg","Munke rejste til Arabien og hentede ny matematik hjem","Klostrene underviste kun riddere og adel i krigskunst"],"correct":"Munke kopierede og bevarede bøger — uden dem var megen antik viden gået tabt for evigt","accepted_answers":["Munke kopierede og bevarede bøger — uden dem var megen antik viden gået tabt for evigt"],"review_text":"Middelalderens klostre var lærdomscentre. Munke brugte måneder på at kopiere bøger i hånd — biblen, klassiske forfattere, medicinsk viden. Det var klostrenes egentlige arv: bevaring og videregivelse af viden i en tid uden trykkepresse."}'::jsonb,
  'mc','short','{"concepts":["kloster","viden","kopiering","bøger","misconception-middelalder-uvidende"],"misconception_type":"overgeneralization","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"middle_ages"}'::jsonb,
  'mc_single',2,'auto',true,'middle_ages',5,2
);

-- ma_g5b2_03 — Three-field farming
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var trevangsdriften og hvorfor brugte middelalder-bønderne den?","options":["Et system hvor markerne skiftede mellem vintersæd, sommersæd og hvile — for at holde jordens næringsindhold oppe","En metode til at vande marker via tre kanaler fra en flod","Et system med tre bønder der delte det samme stykke jord","En rotationsplan for tre forskellige afgrøder dyrket ens hele vejen"],"correct":"Et system hvor markerne skiftede mellem vintersæd, sommersæd og hvile — for at holde jordens næringsindhold oppe","accepted_answers":["Et system hvor markerne skiftede mellem vintersæd, sommersæd og hvile — for at holde jordens næringsindhold oppe"],"review_text":"Trevangsdriften var en middelalder-opfindelse der øgede udbyttet. Marker skiftede hvert år: vinterkorn, sommerkorn og hvile. Den hvilende mark genvandt næringsstoffer og gav bedre høst næste år. Det er et eksempel på at middelalder-bønderne ikke var uvidende."}'::jsonb,
  'mc','short','{"concepts":["trevangsdrift","landbrug","næringsstoffer","middelalder-teknologi"],"misconception_type":"overgeneralization","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"middle_ages"}'::jsonb,
  'mc_single',2,'auto',true,'middle_ages',5,2
);

-- ma_g5b2_04 — Black Death spread via trade
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvordan spredte den Sorte Død sig så hurtigt over hele Europa?","options":["Handelsskibe og handelsruter forbandt byerne — smitten rejste med varerne og rotterne ombord","Pesten spredte sig kun via luften og ramte alle uanset afstand","Pesten startede i kirker og spredte sig via fælles bønneritualer","Fjendtlige hære spred sygdommen bevidst som et biologisk våben"],"correct":"Handelsskibe og handelsruter forbandt byerne — smitten rejste med varerne og rotterne ombord","accepted_answers":["Handelsskibe og handelsruter forbandt byerne — smitten rejste med varerne og rotterne ombord"],"review_text":"Pesten kom til Europa via handelsskibe fra Kina — rotterne ombord bar smittede lopper. Handelsvejene der normalt bragte velstand bragte nu sygdom. Byer med aktiv handel var de første og hårdest ramte. Det viser at forbundethed ikke kun er godt."}'::jsonb,
  'mc','short','{"concepts":["Sorte Død","handel","handelsskibe","spredning","rotter"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"middle_ages"}'::jsonb,
  'mc_single',2,'auto',true,'middle_ages',5,2
);

-- ma_g5b2_05 — Church and feudal power
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var kirkens rolle i feudalsamfundets magtstruktur?","options":["Kirken legitimerede kongernes og adelens magt ved at sige den kom fra Gud — og var selv en stor magtfaktor med jord og rigdom","Kirken modvirkede al verdslig magt og stod altid på de fattiges side mod de rige","Kirken og de verdslige magthavere var altid i åben konflikt med hinanden","Kirken ejede intet og var en ren åndelig institution uden materiel magt"],"correct":"Kirken legitimerede kongernes og adelens magt ved at sige den kom fra Gud — og var selv en stor magtfaktor med jord og rigdom","accepted_answers":["Kirken legitimerede kongernes og adelens magt ved at sige den kom fra Gud — og var selv en stor magtfaktor med jord og rigdom"],"review_text":"Kongers magt kom fra Gud — og det var kirken der sagde det. Uden kirkens velsignelse var en konges krav på tronen svagere. Men kirken var ikke blot et redskab. Den ejede op til en tredjedel af Europas jord og var en gigantisk politisk og økonomisk aktør."}'::jsonb,
  'mc','short','{"concepts":["kirkens magt","feudalisme","jord","legitimitet"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"middle_ages"}'::jsonb,
  'mc_single',2,'auto',true,'middle_ages',5,2
);

-- ma_g5b2_06 — Towns grew from trade
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad drev væksten af middelalder-byer?","options":["Handel og håndværk — byer opstod ved handelsruter og markeder og voksede fordi de tilbød specialiserede varer og tjenester","Konger beordrede folk til at flytte til byer for at kontrollere dem","Byer opstod kun ved klostre og voksede fordi kirken udvidede dem","Naturkatastrofer tvang bønder til byerne"],"correct":"Handel og håndværk — byer opstod ved handelsruter og markeder og voksede fordi de tilbød specialiserede varer og tjenester","accepted_answers":["Handel og håndværk — byer opstod ved handelsruter og markeder og voksede fordi de tilbød specialiserede varer og tjenester"],"review_text":"Middelalder-byer opstod der handel var mulig: ved flodsletterne, havne og vejkrydsninger. Håndværkere slog sig ned tæt på kunderne. Lauget beskyttede handelen. Byer var ikke kongers projekt men handelsmænds og håndværkeres naturlige samlingspunkter."}'::jsonb,
  'mc','short','{"concepts":["byer","handel","håndværk","vækst","misconception-byer-uvigtige"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"middle_ages"}'::jsonb,
  'mc_single',2,'auto',true,'middle_ages',5,2
);

-- ma_g5b2_07 — Not all were poor
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved forestillingen om at alle middelaldermennesker var fattige?","options":["Handelsfolk, laugs-mestere og velstående bønder levede komfortabelt — ulighed var enorm og klasserne var tydeligt differentierede","Forestillingen er korrekt — alle fra bonde til baron levede under identiske forhold","Kun kirken var rig — alle andre grupper levede i fattigdom","Alle var fattige med undtagelse af kongen og hans nærmeste"],"correct":"Handelsfolk, laugs-mestere og velstående bønder levede komfortabelt — ulighed var enorm og klasserne var tydeligt differentierede","accepted_answers":["Handelsfolk, laugs-mestere og velstående bønder levede komfortabelt — ulighed var enorm og klasserne var tydeligt differentierede"],"review_text":"Middelalderen rummede enorme sociale forskelle. En rig købmand i Flandern levede meget bedre end en livegen bonde i Polen. Mester-håndværkere i store byer levede komfortabelt. Fattigdom var ikke universel — men social mobilitet var begrænset, og velstanden afhang meget af den familie man var født ind i."}'::jsonb,
  'mc','short','{"concepts":["rigdom","fattigdom","sociale klasser","ulighed","misconception-alle-fattige"],"misconception_type":"overgeneralization","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"middle_ages"}'::jsonb,
  'mc_single',2,'auto',true,'middle_ages',5,2
);

-- ─── GRADE 5 · BAND 3 (7 questions) ─────────────────────────────────────────

-- ma_g5b3_01 — Why feudalism emerged
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvorfor opstod feudalsystemet efter Romerrigets fald?","options":["Centralt styre kollapsede og lokale stærke mænd tilbød beskyttelse mod angreb mod til gengæld at bønderne dyrkede landet for dem","Konger planlagde bevidst feudalsystemet som den mest effektive samfundsform","Kirken opfandt feudalsystemet for at kunne kontrollere befolkningerne","Befolkningerne valgte feudalisme demokratisk frem for andre muligheder"],"correct":"Centralt styre kollapsede og lokale stærke mænd tilbød beskyttelse mod angreb mod til gengæld at bønderne dyrkede landet for dem","accepted_answers":["Centralt styre kollapsede og lokale stærke mænd tilbød beskyttelse mod angreb mod til gengæld at bønderne dyrkede landet for dem"],"review_text":"Da Romerriget faldt, forsvandt den centrale orden. Ingen politimagt, ingen hær der beskyttede vejene. Lokale krigsherrer tilbød beskyttelse — men den var ikke gratis. Bønderne betalte med arbejde og del af høsten. Feudalisme var et praktisk svar på et magtpolitisk tomrum."}'::jsonb,
  'mc','short','{"concepts":["feudalisme","Romerriget","beskyttelse","magtpolitik","oprindelse"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"middle_ages"}'::jsonb,
  'mc_single',3,'auto',true,'middle_ages',5,3
);

-- ma_g5b3_02 — Church beyond religion (misconception)
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved forestillingen om at kirken i middelalderen kun påvirkede religiøse anliggender?","options":["Kirken kontrollerede uddannelse, hospitaler, jord, kalender og politisk legitimitet — den var samfundets altdominerende institution","Forestillingen er korrekt — kirken holdt sig til rent religiøse anliggender","Kirken var vigtig i byerne men nåede ikke ud til landsbyerne","Kirken var svag i middelalderen og tabte altid til de verdslige magthavere"],"correct":"Kirken kontrollerede uddannelse, hospitaler, jord, kalender og politisk legitimitet — den var samfundets altdominerende institution","accepted_answers":["Kirken kontrollerede uddannelse, hospitaler, jord, kalender og politisk legitimitet — den var samfundets altdominerende institution"],"review_text":"Kirken bestemte hvilke dage der var helligdage og dermed fridage. Den ejede land. Den drev skolerne. Den vejledte konger og truede dem med eksklusion. At kirkens magt kun angik religion er en stor fejlslutning — den var samfundets centrale organisation på alle planer."}'::jsonb,
  'mc','short','{"concepts":["kirkens magt","uddannelse","jord","politisk legitimitet","misconception-kirken-kun-religion"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"middle_ages"}'::jsonb,
  'mc_single',3,'auto',true,'middle_ages',5,3
);

-- ma_g5b3_03 — Black Death social consequence
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var den vigtigste sociale konsekvens af den Sorte Død for de overlevende bønder?","options":["Knaphed på arbejdskraft gav overlevende bønder forhandlingsstyrke og mulighed for at kræve frihed fra livegensskab","Overlevende bønder var så traumatiserede at al social forandring standsede i et århundrede","Adelen styrkede sit greb da svækkede bønder ikke kunne modstå pres","Den Sorte Død sluttede feudalismen øjeblikkeligt og byer overtog al magt"],"correct":"Knaphed på arbejdskraft gav overlevende bønder forhandlingsstyrke og mulighed for at kræve frihed fra livegensskab","accepted_answers":["Knaphed på arbejdskraft gav overlevende bønder forhandlingsstyrke og mulighed for at kræve frihed fra livegensskab"],"review_text":"Da en tredjedel af befolkningen døde, manglede der hænder til markerne. Bønder der overlevede, kunne forhandle bedre betingelser — eller gå til en anden herre. Det paradoksale: den største katastrofe i europæisk historie skabte bedre vilkår for dem der overlevede. Pest som frigørelseskraft."}'::jsonb,
  'mc','short','{"concepts":["Sorte Død","arbejdskraft","bønder","livegensskab","frigørelse"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"middle_ages"}'::jsonb,
  'mc_single',3,'auto',true,'middle_ages',5,3
);

-- ma_g5b3_04 — Kings not all-powerful
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad begrænsede faktisk en middelalderkonges magt?","options":["Baroner med egne hære og slotte, kirken der truede med eksklusion, og praktiske problemer med kommunikation over store afstande","Ingenting — middelalderkonger var absolut magtfulde og intet begrænsede dem","Kun kirkens krav om at kongen var kristen og fulgte biblen","Kun parlamenter der var valgt af borgerne"],"correct":"Baroner med egne hære og slotte, kirken der truede med eksklusion, og praktiske problemer med kommunikation over store afstande","accepted_answers":["Baroner med egne hære og slotte, kirken der truede med eksklusion, og praktiske problemer med kommunikation over store afstande"],"review_text":"En middelalderkonge var ikke en moderne statsleder. Hans baroner havde egne hære og slotte. Ordrer tog uger at nå frem. Og kirken kunne ekskommunikere ham og dermed destabilisere hans herredømme. Kongens magt var altid forhandlet og betinget — ikke absolut."}'::jsonb,
  'mc','short','{"concepts":["kongens magt","baroner","kirken","kommunikation","misconception-kongen-kontrollerer-alt"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"middle_ages"}'::jsonb,
  'mc_single',3,'auto',true,'middle_ages',5,3
);

-- ma_g5b3_05 — Medieval knowledge (misconception)
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved forestillingen om at middelalderfolk vidste meget lidt?","options":["Munke bevarede og videreudviklede matematik, astronomi og medicin — og arabisk videnskab nåede Europa via handelen","Forestillingen er korrekt — ingen vigtige opdagelser skete i middelalderen","Middelalderfolk vidste meget om krig men intet om fredelig videnskab","Kun konger og paver havde adgang til viden — alle andre levede i uvidenhed"],"correct":"Munke bevarede og videreudviklede matematik, astronomi og medicin — og arabisk videnskab nåede Europa via handelen","accepted_answers":["Munke bevarede og videreudviklede matematik, astronomi og medicin — og arabisk videnskab nåede Europa via handelen"],"review_text":"Middelalderlige klostre og de første universiteter (opstået i 1100-tallet) arbejdede aktivt med viden. Arabiske matematikere bidrog med algebra og det tal-system vi bruger i dag. Arkitekter der byggede gotiske katedraler forstod avanceret strukturel mekanik. Middelalderen var ikke intellektuelt mørke."}'::jsonb,
  'mc','short','{"concepts":["viden","klostre","arabisk videnskab","universitet","misconception-middelalder-uvidende"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"middle_ages"}'::jsonb,
  'mc_single',3,'auto',true,'middle_ages',5,3
);

-- ma_g5b3_06 — Guild monopoly effects
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var konsekvensen af laugets kontrol over et håndværk i en by?","options":["Det beskyttede kvalitet og sikrede håndværkernes levevej — men forhindrede også fri konkurrence og nytilkomne","Det betød at alle i lauget tjente nøjagtig det samme og levede identisk","Lauget sikrede at kun adelen kunne blive mester-håndværker","Konkurrence fra laugets monopol betød at alle varer var dyre og dårlige"],"correct":"Det beskyttede kvalitet og sikrede håndværkernes levevej — men forhindrede også fri konkurrence og nytilkomne","accepted_answers":["Det beskyttede kvalitet og sikrede håndværkernes levevej — men forhindrede også fri konkurrence og nytilkomne"],"review_text":"Lauget var dobbelttydig magt. Det sikrede at sko fra Köln var af ensartet kvalitet. Men det forhindrede også folk udefra i at konkurrere. Laugets monopol var godt for laugsmedlemmerne — og dyrere for kunderne. Som alle monopoler havde det vindere og tabere."}'::jsonb,
  'mc','short','{"concepts":["laug","monopol","kvalitet","konkurrence","konsekvens"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"middle_ages"}'::jsonb,
  'mc_single',3,'auto',true,'middle_ages',5,3
);

-- ma_g5b3_07 — Life did change
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved forestillingen om at livet aldrig ændrede sig i middelalderen?","options":["Pesten ændrede befolkningsbalancen, handelsveje ændrede byerne, og universiteter opstod — middelalderen var i konstant forandring","Forestillingen er korrekt — livet var ens fra 500 til 1500","Kun politikken ændrede sig — folk levede og arbejdede identisk i 1000 år","Middelalderen var mere dynamisk end antikken men langsommere end renæssancen"],"correct":"Pesten ændrede befolkningsbalancen, handelsveje ændrede byerne, og universiteter opstod — middelalderen var i konstant forandring","accepted_answers":["Pesten ændrede befolkningsbalancen, handelsveje ændrede byerne, og universiteter opstod — middelalderen var i konstant forandring"],"review_text":"Middelalderen spænder over 1000 år. At hævde at intet ændrede sig er at behandle 1000 år som ét øjeblik. Pesten alene ændrede alt. Handelsrevolutionen i 1200-tallets byer omformede samfundet. Universiteterne skabte ny videnskab. Historien bevæger sig altid — middelalderen er ingen undtagelse."}'::jsonb,
  'mc','short','{"concepts":["forandring","dynamik","middelalder","misconception-ingen-forandring"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"middle_ages"}'::jsonb,
  'mc_single',3,'auto',true,'middle_ages',5,3
);

-- ─── GRADE 5 · BAND 4 (5 questions) ─────────────────────────────────────────

-- ma_g5b4_01 — Peasant perspective on feudalism
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad tror du at en livegen middelalder-bonde syntes om feudalsystemet?","options":["Det var en byrde — han dyrkede andres jord, betalte afgifter og var bundet til det sted han var født","Det var retfærdigt — han fik beskyttelse og mad til gengæld for sit arbejde","Det var ligegyldigt — bønder tænkte ikke over samfundets organisation","Det var positivt fordi det gav bønderne stabile og forudsigelige arbejdsforhold"],"correct":"Det var en byrde — han dyrkede andres jord, betalte afgifter og var bundet til det sted han var født","accepted_answers":["Det var en byrde — han dyrkede andres jord, betalte afgifter og var bundet til det sted han var født"],"review_text":"Den livegne bonde var juridisk bundet til herremandens jord. Han betalte afgifter i korn og arbejde. Han måtte ikke flytte uden tilladelse. Fra bondens perspektiv var feudalisme et system han ikke valgte og ikke let kunne slippe ud af. Systemet tjente herrerne bedst — ikke bønderne."}'::jsonb,
  'mc','short','{"concepts":["bonde-perspektiv","feudalisme","livegen","afgifter","perspektiv"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"middle_ages"}'::jsonb,
  'mc_single',4,'auto',true,'middle_ages',5,4
);

-- ma_g5b4_02 — Black Death: two perspectives
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betød den Sorte Død forskelligt for en overlevende bonde og for en adelsmand der ejede godset?","options":["Bonden: ny forhandlingsstyrke da arbejdskraft var knap og værdifuld. Godsejeren: katastrofalt tab af arbejdskraft og svækkelse af sin magt","Begge oplevede det identisk som en uovervindelig katastrofe","Godsejeren styrkede faktisk sit greb fordi bønder var desperate og svage","Bonden havde intet nyt — pesten ændrede intet for dem der overlevede"],"correct":"Bonden: ny forhandlingsstyrke da arbejdskraft var knap og værdifuld. Godsejeren: katastrofalt tab af arbejdskraft og svækkelse af sin magt","accepted_answers":["Bonden: ny forhandlingsstyrke da arbejdskraft var knap og værdifuld. Godsejeren: katastrofalt tab af arbejdskraft og svækkelse af sin magt"],"review_text":"Pesten var ét fænomen med vidt forskellige konsekvenser. De overlevende bønder var nu sjældne og værdifulde — de kunne kræve bedre vilkår. Godsejerne mistede ikke blot arbejdskraft men politisk kontrol. Katastrofe og mulighed eksisterede side om side — alt afhang af perspektivet."}'::jsonb,
  'mc','short','{"concepts":["Sorte Død","bonde","godsejer","perspektiv","forhandlingsstyrke"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"middle_ages"}'::jsonb,
  'mc_single',4,'auto',true,'middle_ages',5,4
);

-- ma_g5b4_03 — Church in peasant daily life
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var kirkens rolle i en bondefamilies dagligliv i middelalderen?","options":["Kirken strukturerede hele årsrytmen med helligdage og sæsonmarkering — og var den eneste institution der nåede ud til alle","Kirken påvirkede kun dem der aktivt besøgte gudstjenester regelmæssigt","Kirken var vigtig i byerne men nåede ikke ud til landsbyerne","Kirken var en byrde for bønder der betalte tiende men ikke fik noget til gengæld"],"correct":"Kirken strukturerede hele årsrytmen med helligdage og sæsonmarkering — og var den eneste institution der nåede ud til alle","accepted_answers":["Kirken strukturerede hele årsrytmen med helligdage og sæsonmarkering — og var den eneste institution der nåede ud til alle"],"review_text":"For en middelalder-bonde var kirken altgørende. Årets rytme fulgte kirkens kalender. Høst, jul, påske, fastetid — alt organiseret af kirken. Præsten var den uddannede person i landsbyen. Kirken var ikke kun tro — den var social struktur og kalender på én gang."}'::jsonb,
  'mc','short','{"concepts":["kirken","bondens dagligliv","kalender","social struktur","landsbykirke"],"misconception_type":"scope_confusion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"middle_ages"}'::jsonb,
  'mc_single',4,'auto',true,'middle_ages',5,4
);

-- ma_g5b4_04 — Knight reality vs myth
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var virkeligheden bag myten om den ædle ridder i middelalderen?","options":["Riddere var professionelle krigere — mange terroriserede de lokalsamfund de angiveligt beskyttede. Ridder-idealet opstod i litteraturen, ikke i virkeligheden","Ridderne var altid ærefulde og fulgte strenge etiske koder der beskyttede civile","Ridderne var simple bønder der kun kæmpede i absolut nødssituationer","Ridderne var primært diplomater og forhandlere der sjældent faktisk kæmpede"],"correct":"Riddere var professionelle krigere — mange terroriserede de lokalsamfund de angiveligt beskyttede. Ridder-idealet opstod i litteraturen, ikke i virkeligheden","accepted_answers":["Riddere var professionelle krigere — mange terroriserede de lokalsamfund de angiveligt beskyttede. Ridder-idealet opstod i litteraturen, ikke i virkeligheden"],"review_text":"Den romantiske ridder-forestilling opstod i middelalderlig litteratur — riddernes virkelighed var mere brutal. Mange riddere plyndrede landsbyer og afpressede bønder. Ridderkodeksen var et ideal — men idealer og virkelighed er sjældent det samme i historien. Myten og kendsgerningen er to ting."}'::jsonb,
  'mc','short','{"concepts":["ridder","myte","virkelighed","misconception-riddere-helte","litteratur vs virkelighed"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"middle_ages"}'::jsonb,
  'mc_single',4,'auto',true,'middle_ages',5,4
);

-- ma_g5b4_05 — Life changed (synthesis)
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var middelalderens vigtigste lektie om samfundsforandring?","options":["Selv de mest stabile samfundsstrukturer er historisk skabt og kan forandres — af pest, handel, ny viden og organisering","Middelalderens hierarkier var de mest stabile og kan ikke skabes igen","Viden og magt er altid i harmoni og arbejder aldrig imod hinanden","Religiøs magt er altid stærkere end politisk magt i det lange løb"],"correct":"Selv de mest stabile samfundsstrukturer er historisk skabt og kan forandres — af pest, handel, ny viden og organisering","accepted_answers":["Selv de mest stabile samfundsstrukturer er historisk skabt og kan forandres — af pest, handel, ny viden og organisering"],"review_text":"Feudalisme opstod, dominerede og opløstes. Kirkens magt voksede og eroderede. Bøndernes stilling ændredes via pest og organisering. Intet i et samfund er naturgivet og evigt — det er middelalderhistoriens dybeste lektie. Vi er selv en del af historien der vil forandres."}'::jsonb,
  'mc','short','{"concepts":["samfundsforandring","historisk forståelse","middelalder","feudalisme","foranderlighed"],"misconception_type":"temporal_confusion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"middle_ages"}'::jsonb,
  'mc_single',4,'auto',true,'middle_ages',5,4
);

-- ─── GRADE 6 · BAND 1 (6 questions) ─────────────────────────────────────────

-- ma_g6b1_01 — Feudal hierarchy
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var hierarkiet i feudalsystemet fra toppen til bunden?","options":["Kongen → baroner og riddere (lensherrer) → bønder (livegne og frie)","Kirken → kongen → ridderne → bønderne","Kongen → bønderne direkte med ridderne som formidlere","Baroner → kongen → kirken → bønderne"],"correct":"Kongen → baroner og riddere (lensherrer) → bønder (livegne og frie)","accepted_answers":["Kongen → baroner og riddere (lensherrer) → bønder (livegne og frie)"],"review_text":"Feudalhierarkiet var pyramiden der organiserede al samfundsmagt. Kongen ejer alt land i teorien. Han uddeler det til baroner mod militær tjeneste. Baroner uddeler dele til riddere mod det samme. Bønder dyrker alle andres land mod beskyttelse. Hvert niveau skyldte det over sig noget."}'::jsonb,
  'mc','short','{"concepts":["feudalhierarki","kongen","baroner","bønder","pyramide"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"middle_ages"}'::jsonb,
  'mc_single',1,'auto',true,'middle_ages',6,1
);

-- ma_g6b1_02 — Gothic cathedral
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad karakteriserede den gotiske katedral?","options":["Spidsbuer, høje hvælvinger og farverige glasmalerier der lod lyset strømme ind — et symbol på Guds lys","Tunge runde mure og mørke haller der symboliserede Guds hemmeligheder","Træ-bygninger der let kunne udvides med nye rum","Enkle hvide vægge uden dekorationer for at undgå forfængelighed"],"correct":"Spidsbuer, høje hvælvinger og farverige glasmalerier der lod lyset strømme ind — et symbol på Guds lys","accepted_answers":["Spidsbuer, høje hvælvinger og farverige glasmalerier der lod lyset strømme ind — et symbol på Guds lys"],"review_text":"Den gotiske katedral var tidens teknologiske og kunstneriske mesterværk. Spidsbuer fordelte vægten og tillod lettere, høje mure med glasmalerier. Glasmalerierne fortalte bibelhistorier for dem der ikke kunne læse. Katedralen var middelalderens mest ambitiøse projekt — et teologisk budskab i sten og glas."}'::jsonb,
  'mc','short','{"concepts":["gotisk katedral","arkitektur","glasmalerier","Gud","symbol"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"middle_ages"}'::jsonb,
  'mc_single',1,'auto',true,'middle_ages',6,1
);

-- ma_g6b1_03 — Black Death symptoms
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var de typiske symptomer på bubonpest?","options":["Store hævede bylder ved lysken og armhulerne, feber og hurtigt dødsfald — ofte inden for dage","Hoste og feber identisk med en svær influenza men mere langvarig","Blindhed og lammelse der langsomt udviklede sig over måneder","Hududslæt og tab af appetit men uden de karakteristiske bylder"],"correct":"Store hævede bylder ved lysken og armhulerne, feber og hurtigt dødsfald — ofte inden for dage","accepted_answers":["Store hævede bylder ved lysken og armhulerne, feber og hurtigt dødsfald — ofte inden for dage"],"review_text":"Bubonpest er opkaldt efter bubonerne — hævede lymfeknuder der kunne vokse til æblestørrelse. Sygdommen udviklede sig rasende hurtigt. Mange døde inden for 2-6 dage efter første symptom. Ingen forstod årsagen og ingen havde kur. Frygten var total og samfundene brød delvist sammen."}'::jsonb,
  'mc','short','{"concepts":["bubonpest","symptomer","bylder","dødsfald","Sorte Død"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"middle_ages"}'::jsonb,
  'mc_single',1,'auto',true,'middle_ages',6,1
);

-- ma_g6b1_04 — Medieval justice (ordeal)
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var \"gudsdom\" i middelalderlig retspleje?","options":["En prøve hvor anklagede gennemgik en fysisk udfordring — man troede at Gud ville beskytte den uskyldige","En afstemning af byens borgere om den anklagedes skyld","En prøve hvor den anklagede svor på biblen og Gud straffede løgnere","En undersøgelse foretaget af biskoppens repræsentant"],"correct":"En prøve hvor anklagede gennemgik en fysisk udfordring — man troede at Gud ville beskytte den uskyldige","accepted_answers":["En prøve hvor anklagede gennemgik en fysisk udfordring — man troede at Gud ville beskytte den uskyldige"],"review_text":"Gudsdom var middelalderens retssystem i mangel af bedre bevismetoder. Brænder du ved glødende jern, er du skyldig. Synker du i vand, er du uskyldig — men druknet. Systemet virker uretfærdigt nu men dengang troede man genuint at Gud greb ind. Retssystemer afspejler altid tidens verdenssyn."}'::jsonb,
  'mc','short','{"concepts":["gudsdom","retspleje","middelalder","retfærdighed","verdenssyn"],"misconception_type":"anachronism","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"middle_ages"}'::jsonb,
  'mc_single',1,'auto',true,'middle_ages',6,1
);

-- ma_g6b1_05 — Trade goods
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var de vigtigste handelsvarer i middelalderens europæiske handel?","options":["Krydderier og silke fra øst, uld og klæde fra nord og vest, pelsvarer fra Skandinavien og korn fra Polen og Baltikum","Jernvarer fra alle europæiske lande solgt til Asien","Stenkul fra England solgt til hele Europa","Diamanter og guld fra Afrika der finansierede europæiske konger"],"correct":"Krydderier og silke fra øst, uld og klæde fra nord og vest, pelsvarer fra Skandinavien og korn fra Polen og Baltikum","accepted_answers":["Krydderier og silke fra øst, uld og klæde fra nord og vest, pelsvarer fra Skandinavien og korn fra Polen og Baltikum"],"review_text":"Middelalderlig handel var kompleks og multinational. Hansestæder forbandt Østersøen med Nordvesteuropa. Venezia forbandt Europa med Mellemøsten og Asien. Krydderier var luksusvarer og den vigtigste motivation bag opdagelsesrejserne i 1400-1500-tallets begyndelse."}'::jsonb,
  'mc','short','{"concepts":["handel","krydderier","silke","uld","Hansestæder"],"misconception_type":"anachronism","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"middle_ages"}'::jsonb,
  'mc_single',1,'auto',true,'middle_ages',6,1
);

-- ma_g6b1_06 — Monastery functions
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var et middelalder-klosters vigtigste funktioner?","options":["Religiøst liv, bevarelse og kopiering af bøger, dyrkning af jord og omsorg for syge og rejsende","Udelukkende bøn og faste — alt praktisk arbejde var strengt forbudt for munke","Træning af riddere og forsvar af kirkens territorier","Uddannelse af konger og adelsmænd til embedsmandsstillinger"],"correct":"Religiøst liv, bevarelse og kopiering af bøger, dyrkning af jord og omsorg for syge og rejsende","accepted_answers":["Religiøst liv, bevarelse og kopiering af bøger, dyrkning af jord og omsorg for syge og rejsende"],"review_text":"Klostre var middelalderens multifunktionelle institutioner. Munkene levede et reguleret religiøst liv — men de var også farme, hospitaler, biblioteker og gæstehuse for rejsende. Klostre var civilisationens øer i en tid med begrænset central infrastruktur."}'::jsonb,
  'mc','short','{"concepts":["kloster","munke","bibliotek","hospital","landbrug"],"misconception_type":"scope_confusion","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"middle_ages"}'::jsonb,
  'mc_single',1,'auto',true,'middle_ages',6,1
);

-- ─── GRADE 6 · BAND 2 (7 questions) ─────────────────────────────────────────

-- ma_g6b2_01 — Black Death uneven impact
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad bestemte hvem der overlevede den Sorte Død?","options":["Adgang til rent vand, ernæring og afstand fra handelsveje spillede en rolle — og der var genetisk variation i modstandsdygtighed","Rigdom beskyttede altid — de rige overlevede og de fattige døde","Alle i byerne døde og alle på landet overlevede epidemien","Bøn og fromhed beskyttede de troende markant bedre end gudsfornægtere"],"correct":"Adgang til rent vand, ernæring og afstand fra handelsveje spillede en rolle — og der var genetisk variation i modstandsdygtighed","accepted_answers":["Adgang til rent vand, ernæring og afstand fra handelsveje spillede en rolle — og der var genetisk variation i modstandsdygtighed"],"review_text":"Overlevelse afhang af mange faktorer. Byboere tæt på forurenet vand og smittebærere var mere udsatte. Næringsindhold påvirkede immunsystemet. Genetisk variation betød at visse individer var naturligt mere modstandsdygtige. Pesten ramte skævt — men ikke forudsigeligt."}'::jsonb,
  'mc','short','{"concepts":["Sorte Død","overlevelse","vand","genetisk variation","misconception-Sorten-Dod-rammer-alle-ens"],"misconception_type":"overgeneralization","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"middle_ages"}'::jsonb,
  'mc_single',2,'auto',true,'middle_ages',6,2
);

-- ma_g6b2_02 — Most people didn't travel (misconception)
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved forestillingen om at middelalder-folk rejste hyppigt?","options":["De fleste bønder levede og døde inden for få kilometer fra deres fødested — rejser var dyre, farlige og sjældent nødvendige","Forestillingen er korrekt — pilgrimsture og handel betød at folk rejste hyppigt","Kun kvinder rejste sjældent — mænd rejste rutinemæssigt og hyppigt","Bønder rejste mindst én gang om måneden til nærmeste storby"],"correct":"De fleste bønder levede og døde inden for få kilometer fra deres fødested — rejser var dyre, farlige og sjældent nødvendige","accepted_answers":["De fleste bønder levede og døde inden for få kilometer fra deres fødested — rejser var dyre, farlige og sjældent nødvendige"],"review_text":"For de fleste middelalder-bønder var verden lille. Nærmeste by, den lokale kirke, herremandens slot — det var verdenen. Veje var farlige og rejser dyre. Handelsmænd og pilgrimme rejste — men de var undtagelsen, ikke reglen. De fleste middelalder-mennesker kendte kun deres eget hjørne af verden."}'::jsonb,
  'mc','short','{"concepts":["rejser","bønder","mobilitet","hverdagsliv","misconception-folk-rejste-oft"],"misconception_type":"overgeneralization","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"middle_ages"}'::jsonb,
  'mc_single',2,'auto',true,'middle_ages',6,2
);

-- ma_g6b2_03 — Towns and freedom from serfdom
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betød middelalder-byerne for livegne bønder der flygtede dertil?","options":["I mange byer gjaldt reglen et år og en dag i byen — og man var juridisk fri. Byerne tiltrak bønder der søgte frihed fra livegensskabet","Livegne bønder måtte aldrig flygte til byer — det var strengt ulovligt overalt i Europa","Byerne sendte altid bønder tilbage til deres herremænd","Byerne ville ikke optage bønder fra landet og afviste alle tilflyttere"],"correct":"I mange byer gjaldt reglen et år og en dag i byen — og man var juridisk fri. Byerne tiltrak bønder der søgte frihed fra livegensskabet","accepted_answers":["I mange byer gjaldt reglen et år og en dag i byen — og man var juridisk fri. Byerne tiltrak bønder der søgte frihed fra livegensskabet"],"review_text":"Det tyske udtryk Stadtluft macht frei — byluft gør fri — var ikke blot et ordsprog. Mange byer havde regler om at bønder der boede der i et år og en dag ikke kunne kræves tilbage af herremanden. Byerne var frisoner for mange der ville bryde ud af feudalismens hierarki."}'::jsonb,
  'mc','short','{"concepts":["by","frihed","livegen","livegensskab","Stadtluft macht frei"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"middle_ages"}'::jsonb,
  'mc_single',2,'auto',true,'middle_ages',6,2
);

-- ma_g6b2_04 — Pope's power over kings
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvordan kunne paven true en europæisk konges magt i middelalderen?","options":["Paven kunne ekskommunikere kongen — udelukke ham fra kirken — og dermed fritage hans undersåtter fra lydighedspligten","Paven kontrollerede alle kongers hære direkte og kunne beordre dem til krig","Paven bestemte hvem der måtte betale skat og dermed hvem der var rig eller fattig","Paven havde kun symbolsk magt og påvirkede ikke kongernes faktiske politiske beslutninger"],"correct":"Paven kunne ekskommunikere kongen — udelukke ham fra kirken — og dermed fritage hans undersåtter fra lydighedspligten","accepted_answers":["Paven kunne ekskommunikere kongen — udelukke ham fra kirken — og dermed fritage hans undersåtter fra lydighedspligten"],"review_text":"Eksklusion var tidens ultimative sanktion. Ekskommunikation betød at kongen var ude af kirken og hans sjæl i fare. Hans baroner og riddere var fritaget for at følge ham. Kejser Henrik IV stod barfodet i sneen i Canossa i 1077 for at bede paven om tilgivelse. Det siger alt om pavens faktiske magt."}'::jsonb,
  'mc','short','{"concepts":["pave","ekskommunikation","kongemagtbegrænsning","Canossa","kirkemagt"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"middle_ages"}'::jsonb,
  'mc_single',2,'auto',true,'middle_ages',6,2
);

-- ma_g6b2_05 — Trade and town symbiosis
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var sammenhængen mellem handel og byernes vækst i middelalderen?","options":["Handel skabte efterspørgsel efter specialiserede varer og tjenester der tiltrak håndværkere og handelsmænd som grundlagde permanente markeder og byer","Byer voksede primært fordi konger beordrede folk til at flytte dertil","Handel og byvækst var uafhængige — handel foregik primært på landet","Byerne opstod altid før handelen og skabte efterfølgende handelsmuligheder"],"correct":"Handel skabte efterspørgsel efter specialiserede varer og tjenester der tiltrak håndværkere og handelsmænd som grundlagde permanente markeder og byer","accepted_answers":["Handel skabte efterspørgsel efter specialiserede varer og tjenester der tiltrak håndværkere og handelsmænd som grundlagde permanente markeder og byer"],"review_text":"Handel og byer voksede i symbiose. Handelspladsen tiltrak håndværkere. Håndværkere tiltrak kunder. Kunder tiltrak endnu flere handelsmænd. Byer opstod der handel var mulig — og forsvandt hvis handelen forsvandt. Succesfulde handelsbyer voksede til stormagt-centre."}'::jsonb,
  'mc','short','{"concepts":["handel","by","symbiose","vækst","marked"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"middle_ages"}'::jsonb,
  'mc_single',2,'auto',true,'middle_ages',6,2
);

-- ma_g6b2_06 — Guild education path
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var den typiske vej fra nybegynder til mester-håndværker i et middelalder-laug?","options":["Læredreng (boede hos mesteren og lærte) → svend (rejste og lærte hos andre mestere) → mesterprøve og eget værksted","Alle startede som mester og nedsatte sig straks med eget værksted","Man arvede mesterstatus fra sin far uden nogen form for uddannelseskrav","Staten tildelte mesterstatus baseret på alder — ikke på dokumenteret dygtighed"],"correct":"Læredreng (boede hos mesteren og lærte) → svend (rejste og lærte hos andre mestere) → mesterprøve og eget værksted","accepted_answers":["Læredreng (boede hos mesteren og lærte) → svend (rejste og lærte hos andre mestere) → mesterprøve og eget værksted"],"review_text":"Laugets uddannelsesvej var struktureret og krævende. En dreng startede som læredreng — boede hos mesteren og lærte grundlaget. Derefter svend: rejste til andre byer og lærte af andre mestere. Til sidst mesterprøven — et mesterværk der beviste dygtighed. Systemet sikrede kvalitet og kontrollerede adgangen."}'::jsonb,
  'mc','short','{"concepts":["laug","læredreng","svend","mester","uddannelse"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"middle_ages"}'::jsonb,
  'mc_single',2,'auto',true,'middle_ages',6,2
);

-- ma_g6b2_07 — Women in medieval society
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var typiske roller for kvinder i middelaldersamfundet?","options":["Husholdning, børneopdragelse og tekstilproduktion — men mange arbejdede også i marken og havde i byerne undertiden adgang til laug og handel","Kvinder var fuldstændig usynlige og uden nogen aktiv rolle i middelaldersamfundet","Kvinder styrede al handel mens mænd udelukkende dyrkede markerne","Kun nonnerne i klostre havde en aktiv og synlig rolle i samfundet"],"correct":"Husholdning, børneopdragelse og tekstilproduktion — men mange arbejdede også i marken og havde i byerne undertiden adgang til laug og handel","accepted_answers":["Husholdning, børneopdragelse og tekstilproduktion — men mange arbejdede også i marken og havde i byerne undertiden adgang til laug og handel"],"review_text":"Middelalderkvinders liv varierede enormt med klasse og geografi. Bondekoner arbejdede i marken side om side med mænd. I byerne drev nogle kvinder egne forretninger og var med i laug. Adelskvinder forvaltede godser i mandens fravær. Kvinders roller var komplekse — ikke blot passive."}'::jsonb,
  'mc','short','{"concepts":["kvinder","middelalder","roller","laug","arbejde"],"misconception_type":"overgeneralization","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"middle_ages"}'::jsonb,
  'mc_single',2,'auto',true,'middle_ages',6,2
);

-- ─── GRADE 6 · BAND 3 (7 questions) ─────────────────────────────────────────

-- ma_g6b3_01 — Why feudalism declined
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var de primære årsager til feudalismens gradvise tilbagegang?","options":["Pesten reducerede arbejdskraft og gav bønder forhandlingsstyrke; handel skabte en ny pengeklasse der ikke passede ind i hierarkiet; og kanoner eliminerede ridderslottenes forsvarsfunktion","Feudalismen kollapsede øjeblikkeligt da renæssancen begyndte og alle erkendte systemets fejl","Kirken afskaffede feudalismen ved et kirkemøde fordi den stred mod evangeliet","En revolutionær bondebevægelse vandt en afgørende militær sejr og afskaffede systemet"],"correct":"Pesten reducerede arbejdskraft og gav bønder forhandlingsstyrke; handel skabte en ny pengeklasse der ikke passede ind i hierarkiet; og kanoner eliminerede ridderslottenes forsvarsfunktion","accepted_answers":["Pesten reducerede arbejdskraft og gav bønder forhandlingsstyrke; handel skabte en ny pengeklasse der ikke passede ind i hierarkiet; og kanoner eliminerede ridderslottenes forsvarsfunktion"],"review_text":"Feudalismens tilbagegang var langsom og kom fra mange sider. Pest gav bønder magt. Rige handelsmænd i byer skabte en ny klasse der ikke passede i militær-tjeneste-hierarkiet. Kanoner nedlagde riddernes slotte. Konger med store hære behøvede ikke riddernes militær. Systemet opløstes indefra og udefra på én gang."}'::jsonb,
  'mc','short','{"concepts":["feudalismens fald","pest","handel","kanoner","årsager"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"middle_ages"}'::jsonb,
  'mc_single',3,'auto',true,'middle_ages',6,3
);

-- ma_g6b3_02 — Black Death and religion
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var den Sorte Døds komplekse effekt på folks religiøse overbevisninger?","options":["Reaktionerne var delte: mange mistede troen da Guds tjenere døde som alle andre; andre søgte endnu fastere i religionen som trøst og forklaring","Alle mistede øjeblikkeligt troen — kirken oplevede total kollaps og autoritetsfald","Religionen var fuldstændig upåvirket — folk separerede pest fra religiøs overbevisning","Pesten styrkede uniformt alle menneskers tro fordi de søgte Guds nåde og tilgivelse"],"correct":"Reaktionerne var delte: mange mistede troen da Guds tjenere døde som alle andre; andre søgte endnu fastere i religionen som trøst og forklaring","accepted_answers":["Reaktionerne var delte: mange mistede troen da Guds tjenere døde som alle andre; andre søgte endnu fastere i religionen som trøst og forklaring"],"review_text":"Pesten satte troen på prøve. Præster der absoluterede de syge, døde selv. Bønner hjalp ikke. Mange reagerede med desperation. Men mange søgte fastere i troen — hvis Gud straffede, måtte man bede endnu hårdere. Pesten skabte begge reaktioner simultant. Det er historiens kompleksitet."}'::jsonb,
  'mc','short','{"concepts":["Sorte Død","religion","tro","kirkens autoritet","psykologisk effekt"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"middle_ages"}'::jsonb,
  'mc_single',3,'auto',true,'middle_ages',6,3
);

-- ma_g6b3_03 — Justice and worldview
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad viser middelalderens retssystem om datidens syn på sandhed og retfærdighed?","options":["Gudsdomme og tortur viser at man troede sandhed kunne udtrækkes via lidelse eller gudommelig indgriben — ikke via logisk bevisførelse som vi kender i dag","Det viser at middelalder-dommere var onde og sadistiske uden principper","Systemet var faktisk mere retfærdigt end nutidens fordi alle var lige for Gud","Det viser at kun adelen dømte — bønder havde slet intet retssystem"],"correct":"Gudsdomme og tortur viser at man troede sandhed kunne udtrækkes via lidelse eller gudommelig indgriben — ikke via logisk bevisførelse som vi kender i dag","accepted_answers":["Gudsdomme og tortur viser at man troede sandhed kunne udtrækkes via lidelse eller gudommelig indgriben — ikke via logisk bevisførelse som vi kender i dag"],"review_text":"Middelalderens retssystem afspejler en verdens-forståelse fundamentalt forskellig fra vores. Gud er allestedsnærværende og griber ind. Lidelse åbner for sandhed. Disse forestillinger er ikke dumme — de er konsekvente med en kristen kosmologi. At forstå systemet kræver at forstå dets egne forudsætninger."}'::jsonb,
  'mc','short','{"concepts":["retssystem","gudsdom","verdenssyn","sandhed","kontekstforståelse"],"misconception_type":"anachronism","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"middle_ages"}'::jsonb,
  'mc_single',3,'auto',true,'middle_ages',6,3
);

-- ma_g6b3_04 — Towns undermined feudalism
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad viser middelalder-handelsbyers vækst om magtforholdet i samfundet?","options":["Byer skabte en ny klasse af rige borgere der ikke passede ind i feudalhierarkiet og efterhånden krævede og fik politisk indflydelse der underminerede adelens magt","Byer var kun administrative hjælpere for kongerne uden selvstændig politisk magt","Byerne var svage og underordnede altid adelens feudale strukturer fuldstændig","Byerne var kun vigtige i Sydeuropa — nord for Alperne forblev feudalisme totalt dominerende"],"correct":"Byer skabte en ny klasse af rige borgere der ikke passede ind i feudalhierarkiet og efterhånden krævede og fik politisk indflydelse der underminerede adelens magt","accepted_answers":["Byer skabte en ny klasse af rige borgere der ikke passede ind i feudalhierarkiet og efterhånden krævede og fik politisk indflydelse der underminerede adelens magt"],"review_text":"En rig venetiansk handelsmand i 1200-tallets slutning var rigere end mange baroner — men han var ikke adelig. Byerne skabte et borgerskab der ikke passede i militær-tjeneste-logikken. Byer som Venezia og Gent var i praksis selvstyrende stater. Byerne underminerede langsomt feudalismen."}'::jsonb,
  'mc','short','{"concepts":["byer","borgerskab","feudalisme","magt","underminering","misconception-byer-uvigtige"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"middle_ages"}'::jsonb,
  'mc_single',3,'auto',true,'middle_ages',6,3
);

-- ma_g6b3_05 — Monasteries and long-term knowledge legacy
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var den langsigtede konsekvens af klostrenes vidensbevarelse?","options":["Antik filosofi, matematik og medicin overlevede og lagde fundamentet for renæssancens videnskab og den moderne videnskabelige revolution","Klostrenes bøger var ubrugelige fordi alt var skrevet på latin som ingen forstod","Klostrenes viden gik tabt da klostrene lukkede under reformationen i 1500-tallet","Klostrenes viden var kun relevant for religiøse spørgsmål og påvirkede aldrig verdslig videnskab"],"correct":"Antik filosofi, matematik og medicin overlevede og lagde fundamentet for renæssancens videnskab og den moderne videnskabelige revolution","accepted_answers":["Antik filosofi, matematik og medicin overlevede og lagde fundamentet for renæssancens videnskab og den moderne videnskabelige revolution"],"review_text":"Uden klostrenes kopieringsarbejde var Aristoteles og de store antikke matematikere gået tabt. Renæssancens genopdagelse af antikken var mulig fordi middelalderlige munke bevarede den. En direkte linje løber fra antikkens viden via klostrenes bevarelse til den moderne videnskab."}'::jsonb,
  'mc','short','{"concepts":["klostre","viden","antikken","renæssance","langsigtet konsekvens"],"misconception_type":"temporal_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"middle_ages"}'::jsonb,
  'mc_single',3,'auto',true,'middle_ages',6,3
);

-- ma_g6b3_06 — Feudalism inequality from peasant view
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Fra den livegne bondes perspektiv — hvad var det systematisk uretfærdige ved feudalisme?","options":["Han arbejdede og betalte afgifter til herremanden, betalte tiende til kirken og havde ingen politisk stemme — al hans produktion tjente andre","Systemet var retfærdigt da bonden fik beskyttelse og stabile arbejdsforhold til gengæld","Bonden valgte systemet frivilligt og kunne til enhver tid forlade det han ikke brød sig om","Bonden var faktisk privilegeret sammenlignet med ridderne der måtte kæmpe og risikere livet"],"correct":"Han arbejdede og betalte afgifter til herremanden, betalte tiende til kirken og havde ingen politisk stemme — al hans produktion tjente andre","accepted_answers":["Han arbejdede og betalte afgifter til herremanden, betalte tiende til kirken og havde ingen politisk stemme — al hans produktion tjente andre"],"review_text":"Den livegne betalte på alle fronter. Til herremanden: del af høsten og obligatorisk arbejde på hans marker. Til kirken: tiende (en tiendedel af alt). Han ejede intet land. Han måtte ikke flytte. Han havde ingen politisk magt. Det feudale system producerede velstand for toppen ved at udtage det fra bunden."}'::jsonb,
  'mc','short','{"concepts":["livegen","bonde-perspektiv","feudalisme","afgifter","tiende","uretfærdighed"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"middle_ages"}'::jsonb,
  'mc_single',3,'auto',true,'middle_ages',6,3
);

-- ma_g6b3_07 — Church decline toward end of Middle Ages
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var årsagerne til at kirkens autoritet begyndte at svækkes mod middelalderens slutning?","options":["Pestens rædsler udfordrede kirkens forklaringer; intern korruption og to konkurrerende paver skabte mistillid; og humanisme satte mennesket frem for Gud","Kirken svækkedes fordi konger militært erobrede pavernes territorier og lande","Kirken frivilligt opgav sin magt for at fokusere udelukkende på ren spiritualitet","Kirken var aldrig magtfuld — der var intet egentligt at svække"],"correct":"Pestens rædsler udfordrede kirkens forklaringer; intern korruption og to konkurrerende paver skabte mistillid; og humanisme satte mennesket frem for Gud","accepted_answers":["Pestens rædsler udfordrede kirkens forklaringer; intern korruption og to konkurrerende paver skabte mistillid; og humanisme satte mennesket frem for Gud"],"review_text":"Kirkens store autoritetskrise kom fra alle sider. Pesten: Guds tjenere døde som syndere. Det store skisma (1378-1417): to og til tider tre paver på én gang. Korruption: simoni og rig klerus. Humanisterne: mennesket som målestok. Alt dette banede vej for reformationen et århundrede senere."}'::jsonb,
  'mc','short','{"concepts":["kirkens fald","pest","korruption","skisma","humanisme","reformationen"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"middle_ages"}'::jsonb,
  'mc_single',3,'auto',true,'middle_ages',6,3
);

-- ─── GRADE 6 · BAND 4 (5 questions) ─────────────────────────────────────────

-- ma_g6b4_01 — Pope vs kings conflict (core issue)
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var kernen i konflikten mellem pave og konger i middelalderen?","options":["Begge hævdede øverste autoritet — paven sagde åndelig magt var over verdslig; kongerne sagde de var Guds udvalgte og ikke underordnet paven","Konflikten handlede udelukkende om kirkejord og skatter — ikke om principielt spørgsmål om autoritet","Konger og paver var altid allierede med fælles interesser mod de europæiske folk","Konflikten eksisterede kun i Sydeuropa og berørte ikke nordlige kongeriger"],"correct":"Begge hævdede øverste autoritet — paven sagde åndelig magt var over verdslig; kongerne sagde de var Guds udvalgte og ikke underordnet paven","accepted_answers":["Begge hævdede øverste autoritet — paven sagde åndelig magt var over verdslig; kongerne sagde de var Guds udvalgte og ikke underordnet paven"],"review_text":"Investiturstriden (1076-1122) var den store kamp: hvem bestemmer hvem der må være biskop — paven eller kongen? Begge sider brugte Biblen til at begrunde deres position. Det var ikke blot et religiøst spørgsmål — det var spørgsmål om hvem der har den øverste magt i kristenheden."}'::jsonb,
  'mc','short','{"concepts":["pave-konger-konflikt","autoritet","investiturstrid","Canossa","magt"],"misconception_type":"scope_confusion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"middle_ages"}'::jsonb,
  'mc_single',4,'auto',true,'middle_ages',6,4
);

-- ma_g6b4_02 — Three perspectives on feudalism
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var feudalismens funktion set fra bondens, baronens og kongens perspektiv?","options":["Bonden: overleve under andres beskyttelse. Baronen: maksimere ressourcer fra lenet. Kongen: opretholde magt via loyaliteter han aldrig fuldt kontrollerede","Alle tre oplevede feudalisme som retfærdigt og den naturlige samfundsorden","Alle tre ønskede at afskaffe systemet men turde ikke af frygt for uro","Baronen var den eneste der profiterede — bonden og kongen tabte altid"],"correct":"Bonden: overleve under andres beskyttelse. Baronen: maksimere ressourcer fra lenet. Kongen: opretholde magt via loyaliteter han aldrig fuldt kontrollerede","accepted_answers":["Bonden: overleve under andres beskyttelse. Baronen: maksimere ressourcer fra lenet. Kongen: opretholde magt via loyaliteter han aldrig fuldt kontrollerede"],"review_text":"Feudalisme fungerede forskelligt for alle tre. Bonden betalte for alle andres position. Baronen forvaltede med maksimal ressourceudnyttelse. Kongen var afhængig af baroner han ikke altid kontrollerede. Det var et system med iboende spændinger — og de spændinger opløste det til sidst."}'::jsonb,
  'mc','short','{"concepts":["feudalisme","tre perspektiver","bonde","baron","kongen"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"middle_ages"}'::jsonb,
  'mc_single',4,'auto',true,'middle_ages',6,4
);

-- ma_g6b4_03 — Black Death: catastrophe AND catalyst
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Var den Sorte Død primært en katastrofe eller en katalysator for social forandring?","options":["Begge dele simultant — katastrofal i tab af liv men den accelererede social forandring der ellers ville have taget generationer","Det var udelukkende katastrofe uden nogen som helst positiv konsekvens for nogen","Det var primært en positiv katalysator — de sociale forandringer opvejede klart tabene","Hverken katastrofe eller katalysator — samfundet vendte hurtigt til præcis den gamle tilstand"],"correct":"Begge dele simultant — katastrofal i tab af liv men den accelererede social forandring der ellers ville have taget generationer","accepted_answers":["Begge dele simultant — katastrofal i tab af liv men den accelererede social forandring der ellers ville have taget generationer"],"review_text":"Historikere ser pesten som et dobbelt fænomen. Katastrofen er åbenlys: 30-40% af Europas befolkning døde. Men den accelererede forandringer der allerede var i gang: bøndernes frigørelse, byernes vækst, kirkens autoritetskrise. Pest som motor for social forandring er et ubehageligt men historisk præcist blik."}'::jsonb,
  'mc','short','{"concepts":["Sorte Død","katastrofe","katalysator","social forandring","kompleksitet"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"middle_ages"}'::jsonb,
  'mc_single',4,'auto',true,'middle_ages',6,4
);

-- ma_g6b4_04 — Middle Ages legacy
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er middelalderens vigtigste arv til det moderne Europa?","options":["Parlamenter og stænderforsamlinger, universiteter, gotiske katedraler, nationale sprog og grundlæggende retssystemer — fundamentale strukturer der stadig eksisterer","Middelalderen efterlod intet positivt — den var blot en mørk periode der bør glemmes","Kun kirkens kunst er bevaret — alt andet forsvandt med middelalderens afslutning","Middelalderens vigtigste arv er riddervæsenet og turnerings-kulturen"],"correct":"Parlamenter og stænderforsamlinger, universiteter, gotiske katedraler, nationale sprog og grundlæggende retssystemer — fundamentale strukturer der stadig eksisterer","accepted_answers":["Parlamenter og stænderforsamlinger, universiteter, gotiske katedraler, nationale sprog og grundlæggende retssystemer — fundamentale strukturer der stadig eksisterer"],"review_text":"Mange institutioner vi tager for givet stammer fra middelalderen. Universiteter opstod i 1100-1200-tallet. Parlamenter udviklede sig fra middelalderlige stænderforsamlinger. Nationale sprog erstattede latin. Katedraler står stadig. Middelalderens arv er overalt — den er blot usynlig fordi vi er vant til den."}'::jsonb,
  'mc','short','{"concepts":["middelalderens arv","universiteter","parlament","nationalsprog","katedral"],"misconception_type":"temporal_confusion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"middle_ages"}'::jsonb,
  'mc_single',4,'auto',true,'middle_ages',6,4
);

-- ma_g6b4_05 — Deepest lesson from the Middle Ages
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er den dybeste historiske lektie fra middelalderens 1000 år?","options":["At samfundsstrukturer ikke er naturgivne men historisk skabte — og at de kan forandres af pest, handel, ny viden og organisering","At middelalderens hierarkier var de mest stabile og bør genindføres som model","At viden og magt altid arbejder i harmoni og aldrig er i grundlæggende konflikt","At religiøs magt altid i det lange løb sejrer over politisk magt"],"correct":"At samfundsstrukturer ikke er naturgivne men historisk skabte — og at de kan forandres af pest, handel, ny viden og organisering","accepted_answers":["At samfundsstrukturer ikke er naturgivne men historisk skabte — og at de kan forandres af pest, handel, ny viden og organisering"],"review_text":"Feudalisme opstod, dominerede og opløstes. Kirkens magt voksede og eroderede. Bøndernes stilling ændredes via pest og organisering. Intet i et samfund er naturgivet og evigt. Vi er selv en del af den historiske forandring der altid fortsætter. Det er middelalderhistoriens dybeste og vigtigste lektie."}'::jsonb,
  'mc','short','{"concepts":["samfundsforandring","historisk forståelse","foranderlighed","middelalder","lektie"],"misconception_type":"temporal_confusion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"middle_ages"}'::jsonb,
  'mc_single',4,'auto',true,'middle_ages',6,4
);;
