-- Section 108 — World War 1 Band 5 Sprint
-- Creates the first genuine ceiling layer for advanced grade-9 students in world_war_1.
-- Prior to this migration world_war_1 had zero Band 5 questions (50 active across Bands 1-4).
--
-- 20 questions: target_grade=9, difficulty_band=5, domain=world_war_1, is_active=true
-- Distribution: Origins(5) + Total War(3) + Historiography(4) + Versailles(4) + Modern Relevance(4)
-- Uses dollar-quoting ($$) throughout to avoid apostrophe escaping issues.

-- ─── BAND 5 · VERDENSKRIGENS ÅRSAGER (5 questions) ──────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Var 1. Verdenskrig et resultat af strukturelle kræfter der var ude af kontrol — eller af bevidste menneskelige beslutninger der kunne have været truffet anderledes?","options":["Primært bevidste beslutninger: i julikrisen 1914 havde de europæiske ledere gentagne lejligheder til at deeskalere, og de valgte eskalering. Strukturelle faktorer (alliancer, mobiliseringsplaner) skabte pres men determinerede ikke udfaldet — de forklarer mulighedsbetingelserne, ikke de konkrete valg","Udelukkende strukturelt: alliancesystemet, kappestriden og mobiliseringsplanerne var sat i bevægelse og ingen enkelt leder kunne have stoppet krigen i 1914","Udelukkende intentionelt: Tyskland planlagde bevidst krigen i detalje fra mindst 1912 og alle andre landes beslutninger var reaktioner på det tyske program","Spørgsmålet er historisk irrelevant — krige er altid et produkt af uforanderlige menneskelige natur-egenskaber og strukturanalyse giver ingen ny indsigt"],"correct":"Primært bevidste beslutninger: i julikrisen 1914 havde de europæiske ledere gentagne lejligheder til at deeskalere, og de valgte eskalering. Strukturelle faktorer (alliancer, mobiliseringsplaner) skabte pres men determinerede ikke udfaldet — de forklarer mulighedsbetingelserne, ikke de konkrete valg","accepted_answers":["Primært bevidste beslutninger: i julikrisen 1914 havde de europæiske ledere gentagne lejligheder til at deeskalere, og de valgte eskalering. Strukturelle faktorer (alliancer, mobiliseringsplaner) skabte pres men determinerede ikke udfaldet — de forklarer mulighedsbetingelserne, ikke de konkrete valg"],"review_text":"Debatten om 1. Verdenskrigs årsager handler fundamentalt om forholdet mellem struktur og agency. Strukturalisterne (som A.J.P. Taylor) peger på at Schlieffen-planen, den generelle mobiliseringslogik og alliancekæden skabte et system der eskalerede automatisk. Men Christopher Clarks Sleepwalkers (2012) viser at julkrisen indeholdt talrige decision points: Willy-Nicky-telegramvekslingen, den britiske intervention var ikke given, og Østrigs beslutning om at afvise det serbiske svar (der imødekom næsten alle krav) var bevidst. Margaret MacMillan viser i The War That Ended Peace (2013) at lederne i 1914 var vilje-begavede aktører der traf valg under pres — og at erkendelsen er nødvendig for at lektien er anvendelig: strukturer skaber risici, men mennesker eskalerer krige."}$$::jsonb,
  'mc','short',$${"concepts":["struktur vs agency","julikrise","Schlieffen-planen","beslutningsteori","MacMillan","Clark"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}$$::jsonb,
  'mc_single',5,'auto',true,'world_war_1',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er Fritz Fischers centrale tese om Tysklands ansvar for 1. Verdenskrig — og hvad er det stærkeste modargument?","options":["Fischer: Tyskland søgte bevidst en europæisk krig for at opnå stormagtstatus (Weltpolitik) og en dominerende stilling i Europa — dokumenteret i september-programmet 1914. Modargument: september-programmet er et krigsmåls-dokument udformet EFTER krigsudbrudet og beviser ikke en præventiv aggressionsplan; andre magters chauvinisme, Ruslands mobilisering og Østrigs ultimatum spillede selvstændige roller","Fischer: Tysklands industri finansierede krigsplanlægning fra 1870 og krigsudbrudet var et bevidst imperialistisk projekt. Modargument: Fischer ignorerer at industrien i alle lande finansierede militær","Fischer: Wilhelminsk Tyskland var psykologisk ustabilt og kaiseren alene besluttede krigen. Modargument: kaiseren var faktisk marginal i de faktiske beslutninger","Fischer er fuldstændig korrekt og hans tese er historiografisk konsensus — alle modargumenter er politisk motiverede"],"correct":"Fischer: Tyskland søgte bevidst en europæisk krig for at opnå stormagtstatus (Weltpolitik) og en dominerende stilling i Europa — dokumenteret i september-programmet 1914. Modargument: september-programmet er et krigsmåls-dokument udformet EFTER krigsudbrudet og beviser ikke en præventiv aggressionsplan; andre magters chauvinisme, Ruslands mobilisering og Østrigs ultimatum spillede selvstændige roller","accepted_answers":["Fischer: Tyskland søgte bevidst en europæisk krig for at opnå stormagtstatus (Weltpolitik) og en dominerende stilling i Europa — dokumenteret i september-programmet 1914. Modargument: september-programmet er et krigsmåls-dokument udformet EFTER krigsudbrudet og beviser ikke en præventiv aggressionsplan; andre magters chauvinisme, Ruslands mobilisering og Østrigs ultimatum spillede selvstændige roller"],"review_text":"Fritz Fischers Griff nach der Weltmacht (1961) var en historisk bombe: en tysk historiker der hævdede at hans eget land aktivt planlagde den storkrig der kostede 20 millioner liv. Fischer baserede sig på september-programmet (Bethmann Hollwegs krigsformålsdokument fra 9. september 1914) der beskriver massiv tysk territorial ekspansion. Modargumenterne er metodologisk seriøse: september-programmet er udformet efter krigsudbrudet og under krigens pres — det dokumenterer krigsformål, ikke krigsplanlægning fra 1912. Gerhard Ritter og John Keegan fremhæver at alliancesystemet og de militære planer i alle lande skabte den strukturelle fælde. Christopher Clarks Sleepwalkers viser at den serbiske og russiske part i julikrisen er underspillet hos Fischer. Debatten er metodologisk vigtig: hvad dokumenterer historiske tekster, og hvad de beviser om intentioner er ikke det samme."}$$::jsonb,
  'mc','short',$${"concepts":["Fischer","september-programmet","Weltpolitik","Griff nach der Weltmacht","tysk krigsansvar","metodologi"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}$$::jsonb,
  'mc_single',5,'auto',true,'world_war_1',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er kernen i Christopher Clarks somnambulisme-tese i The Sleepwalkers (2012) — og hvad er dens vigtigste historiografiske konsekvens?","options":["Clark hævder at de europæiske ledere i 1914 gik ind i krigen som søvngængere — vidende nok til at se faren for sig men ude af stand til at stoppe op og tænke. Konsekvensen: ansvaret er distribueret over alle stormagter og den simplificerede skyld-på-ét-land-forklaring er historisk uholdbar","Clark hævder at krigen var fuldt planlagt og bevidst iværksat af alle magter i fællesskab som en imperialistisk konspiration","Clark rehabiliterer fuldstændigt Wilhelminsk Tysklands adfærd og placerer al skyld på Serbien og Rusland","Clarks tese er ren politisk revisionisme uden kildemæssigt grundlag og anerkendes ikke af seriøse historikere"],"correct":"Clark hævder at de europæiske ledere i 1914 gik ind i krigen som søvngængere — vidende nok til at se faren for sig men ude af stand til at stoppe op og tænke. Konsekvensen: ansvaret er distribueret over alle stormagter og den simplificerede skyld-på-ét-land-forklaring er historisk uholdbar","accepted_answers":["Clark hævder at de europæiske ledere i 1914 gik ind i krigen som søvngængere — vidende nok til at se faren for sig men ude af stand til at stoppe op og tænke. Konsekvensen: ansvaret er distribueret over alle stormagter og den simplificerede skyld-på-ét-land-forklaring er historisk uholdbar"],"review_text":"Clarks Sleepwalkers er den mest indflydelsesrige engelsksprogede 1. Verdenskrig-historiografi i de seneste årtier. Hans nøglepåstand er en fordeling af ansvaret: Serbien handlede aggressivt i julikrisen og skjulte viden om Sarajevo-attentatet, Rusland mobiliserede hurtigere og mere aggressivt end nødvendigt, og Østrig-Ungarn var medansvarlig for ultimatumets uacceptable form. Clarks metodologiske pointe er vigtig: han analyserer alle stormagternes beslutningsprocesser med samme grundighed — ikke kun det tyske. Kritikken (bl.a. fra John Horne og Alan Kramer) er at Clark undervurderer den strukturelle tyske militarisme og Berlins aktive opbakning til Østrigs ultimatum via blanchechecken. Somnambulisme-metaforen er analytisk stærk: lederne var ikke uskyldig ignorante men heller ikke kyniske krigsmaskiner."}$$::jsonb,
  'mc','short',$${"concepts":["Clark","sleepwalkers","somnambulisme","fordelt ansvar","julikrise","historiografi"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}$$::jsonb,
  'mc_single',5,'auto',true,'world_war_1',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Gjorde alliancesystemet i Europa 1914 krig uundgåelig — eller var alliancer en nødvendig men ikke tilstrækkelig årsag?","options":["Nødvendig men ikke tilstrækkelig: alliancerne skabte automatisk eskalering hvis nogen stormagtskrig startede, men de startede ikke selv krigen. Julikrisen viser at lande som Storbritannien faktisk tøvede med at aktivere allianceforpligtelserne — beslutningen om at eskalere til verdenskrig krævede aktive valg ud over alliancernes mekaniske logik","Alliancerne var den tilstrækkelige årsag: da blot ét skud faldt, var den automatiske eskalering uundgåelig og ingen menneskelig beslutning kunne have stoppet det","Alliancerne forhindrede faktisk krigen fra 1871-1914 og er dermed freden snarere end krigens årsag — Sarajevo-attentatet overrumplede et system der ellers fungerede","Alliancesystemet er irrelevant for forståelsen af 1914 — nationalisme og imperialisme var de eneste reelle årsager"],"correct":"Nødvendig men ikke tilstrækkelig: alliancerne skabte automatisk eskalering hvis nogen stormagtskrig startede, men de startede ikke selv krigen. Julikrisen viser at lande som Storbritannien faktisk tøvede med at aktivere allianceforpligtelserne — beslutningen om at eskalere til verdenskrig krævede aktive valg ud over alliancernes mekaniske logik","accepted_answers":["Nødvendig men ikke tilstrækkelig: alliancerne skabte automatisk eskalering hvis nogen stormagtskrig startede, men de startede ikke selv krigen. Julikrisen viser at lande som Storbritannien faktisk tøvede med at aktivere allianceforpligtelserne — beslutningen om at eskalere til verdenskrig krævede aktive valg ud over alliancernes mekaniske logik"],"review_text":"Det klassiske argument er at alliancernes kædereaktion var automatisk: Østrig angriber Serbien → Rusland mobiliserer → Tyskland erklærer krig mod Rusland → Frankrig trækkes ind → Tyskland invaderer Belgien → England aktiverer garantien. Men analysen er forenklet. England var ikke juridisk forpligtet af ententen til at gå i krig — der var ingen formel forsvarsalliance med Frankrig. Den britiske kabinetssamling i august 1914 var åbent delibererende og Belgiens invasion tippede beslutningen. Italien var med i Triplealliancen men valgte neutralitet i 1914 og skiftede side i 1915. Alliancer satte præmisserne men determinerede ikke alle valg. Den nødvendige/tilstrækkelige distinktion er analytisk central: alliancer var nødvendige for at en regional krig i Balkan kunne blive verdenskrig, men menneskelige valg omformede dem til netop det."}$$::jsonb,
  'mc','short',$${"concepts":["alliancesystem","kædereaktion","nødvendig årsag","tilstrækkelig årsag","julikrise","automatisk eskalering"],"misconception_type":"causal_inversion","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}$$::jsonb,
  'mc_single',5,'auto',true,'world_war_1',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad viser nationalismens rolle i optakten til 1. Verdenskrig om forholdet mellem national identitet som konstruktiv og destruktiv politisk kraft?","options":["Nationalismen var konstruktiv som identitets-og mobiliseringskraft men destruktiv som eksklusionslogik: den skabte den folkelige opbakning til krig i august 1914 (en masse-entusiasme der overraskede lederne) men den var baseret på fjendebilleder der dehumaniserede modparten og umuliggjorde diplomatisk kompromis","Nationalisme var udelukkende konstruktiv og krigens årsag var udelukkende imperialisme — nationalisme er en apolitisk identitetskategori","Nationalisme var den eneste årsag til krigen og alt andet (alliancer, kappestriden) var sekundære symptomer på nationalismens logik","Nationalisme er altid destruktiv og statsbyggeri burde altid basere sig på andre principper end national identitet"],"correct":"Nationalismen var konstruktiv som identitets-og mobiliseringskraft men destruktiv som eksklusionslogik: den skabte den folkelige opbakning til krig i august 1914 (en masse-entusiasme der overraskede lederne) men den var baseret på fjendebilleder der dehumaniserede modparten og umuliggjorde diplomatisk kompromis","accepted_answers":["Nationalismen var konstruktiv som identitets-og mobiliseringskraft men destruktiv som eksklusionslogik: den skabte den folkelige opbakning til krig i august 1914 (en masse-entusiasme der overraskede lederne) men den var baseret på fjendebilleder der dehumaniserede modparten og umuliggjorde diplomatisk kompromis"],"review_text":"Augustentusiasmen — den folkelige begejstring for krig i 1914 — viser nationalistisk mobilisering i sin mest kraftfulde form. Historikere som Jeffrey Verhey (The Spirit of 1914) har nyanceret billedet: entusiasmen var mere begrænset og klassespecifik end myten, og frygt og usikkerhed spillede en større rolle end rent begejstring. Men nationalistiske fjendebilleder — den tyske Barbarei-propaganda om belgiske grusomheder, den franske revanche-retorik, den britiske Gott strafe England-karikatering — understøttede den offentlige accept af krigen. Den samme nationalistiske logik der samlede folk om fælles identitet, ekskluderede dem der ikke passede ind og fremstillede modparten som en eksistentiel trussel. Nationalismens dobbeltrolle er fortsat relevant: som demokratisk mobiliseringskraft og som eksklusionsmaskine."}$$::jsonb,
  'mc','short',$${"concepts":["nationalisme","augustentusiasme","fjendebilleder","mobilisering","Verhey","konstruktiv vs destruktiv"],"misconception_type":"false_equivalence","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}$$::jsonb,
  'mc_single',5,'auto',true,'world_war_1',9,5
);

-- ─── BAND 5 · TOTALKRIG & ETIK (3 questions) ─────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad kendetegner 1. Verdenskrig som totalkrig — og hvad er den etiske konsekvens af mobiliseringen af hele samfundet til krigsformål?","options":["Totalkrig ophæver distinktionen mellem kombattanter og civile som relevante kategorier: når hele det civile samfund er inddraget i krigsproduktion, propaganda og logistik, bliver civilsamfundet et legitimt mål ifølge visse militærstrategiske logikker — og dette er præcis det etisk problematiske ved totalkrig-konceptet","Totalkrig er etisk uproblematisk fordi al mobilisering er defensiv og frivillig i demokratier","Totalkrig beskytter faktisk civile bedre end begrænset krig fordi den giver alle borgere en rolle og dermed en beskyttelsesstatus","Distinktionen mellem kombattanter og civile er irrelevant i moderne industrialiseret krig — etiske principper kan ikke anvendes"],"correct":"Totalkrig ophæver distinktionen mellem kombattanter og civile som relevante kategorier: når hele det civile samfund er inddraget i krigsproduktion, propaganda og logistik, bliver civilsamfundet et legitimt mål ifølge visse militærstrategiske logikker — og dette er præcis det etisk problematiske ved totalkrig-konceptet","accepted_answers":["Totalkrig ophæver distinktionen mellem kombattanter og civile som relevante kategorier: når hele det civile samfund er inddraget i krigsproduktion, propaganda og logistik, bliver civilsamfundet et legitimt mål ifølge visse militærstrategiske logikker — og dette er præcis det etisk problematiske ved totalkrig-konceptet"],"review_text":"1. Verdenskrig er den første konflikt der med rette kan betegnes som totalkrig i industriel skala. Det kendetegner begrebet: (1) hele det nationale økonomi omlægges til krigsproduktion, (2) hele den mandlige befolkning mobiliseres militært, (3) propaganda engagerer den civile befolkning ideologisk og (4) den martitime blokade bruger sult som våben mod en modstanders civilbefolkning. Den britiske kontinentalblokade af Tyskland og de tyske U-bådskampagner mod britisk handelsskibsfart er begge eksempler på at civile og civilsamfund bevidst gøres til mål. Hague-konventionerne (1899, 1907) forsøgte at regulere krigføring, men de var utilstrækkelige til totalkrig-virkeligheden. Just war-teoriens distinktionsprincip kollapser under totalkrig-logikken — og dette er det fundamentale etiske problem ved 20. århundredets industrialiserede krige."}$$::jsonb,
  'mc','short',$${"concepts":["totalkrig","distinktionsprincip","civilmobilisering","blokade","just war","industrialiseret krig"],"misconception_type":"scope_confusion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}$$::jsonb,
  'mc_single',5,'auto',true,'world_war_1',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad afslører 1. Verdenskrigs behandling af shell shock (combat stress) om forholdet mellem militær disciplin, medicinsk forståelse og menneskelig værdighed?","options":["Behandlingen afslører en fundamental konflikt: militæret fortolkede shell shock som fejhed og desertement og straffede det med henrettelse, mens læger som W.H.R. Rivers begyndte at forstå det som en psykologisk sårbarhed. Konflikten illustrerer at institutionelle interesser (disciplin) kan kollidere med videnskabelig erkendelse og menneskelig værdighed","Shell shock var simpelthen fysisk skade og hele debatten om psykologisk dimension er retrospektiv medicinshistorisk konstruktion","Militærets behandling af shell shock var etisk korrekt fordi krigseffektivitet kræver disciplin der prioriteres over individuelle psykologiske behov","Britisk militær anerkendte straks shell shock som en legitim lidelse og behandlede alle ramte med fuld medicinsk støtte"],"correct":"Behandlingen afslører en fundamental konflikt: militæret fortolkede shell shock som fejhed og desertement og straffede det med henrettelse, mens læger som W.H.R. Rivers begyndte at forstå det som en psykologisk sårbarhed. Konflikten illustrerer at institutionelle interesser (disciplin) kan kollidere med videnskabelig erkendelse og menneskelig værdighed","accepted_answers":["Behandlingen afslører en fundamental konflikt: militæret fortolkede shell shock som fejhed og desertement og straffede det med henrettelse, mens læger som W.H.R. Rivers begyndte at forstå det som en psykologisk sårbarhed. Konflikten illustrerer at institutionelle interesser (disciplin) kan kollidere med videnskabelig erkendelse og menneskelig værdighed"],"review_text":"Shell shock — det vi i dag kalder PTSD — ramte hundreder af tusinder af soldater i 1. Verdenskrig. Den britiske militære reaktion var dybt ambivalent: 306 britiske soldater blev henrettet for fejhed eller desertement — mange af dem sandsynligvis shell shock-ramte. W.H.R. Rivers pionerbehandling af Siegfried Sassoon på Craiglockhart Hospital pegede på en psykodynamisk forståelse som Pat Barker har udforsket i Regeneration-trilogien. Den institutionelle modstand mod at anerkende shell shock som en legitim medicinsk diagnose skyldtes frygten for at undergrave krigsmoralen — et eksempel på at militære institutioner kan undertrykke medicinsk erkendelse når den truer institutionens kernefunktioner. Storbritanniens efterkrigstid-debat om at benåde de henrettede (gennemført symbolsk i 2006) viser at spørgsmålet om institutionel ansvar ikke forsvinder med historiens gang."}$$::jsonb,
  'mc','short',$${"concepts":["shell shock","PTSD","W.H.R. Rivers","militær disciplin","medicinsk etik","henrettelse for fejhed"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}$$::jsonb,
  'mc_single',5,'auto',true,'world_war_1',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad afslører inddragelsen af koloniale tropper fra Afrika, Indien og Indokina i 1. Verdenskrig om magtforholdene i det europæiske kolonisystem?","options":["Det afslører at kolonimagternes krige hvilede på koloniserede befolkningers ofre: over en million indiske soldater kæmpede for det britiske imperium, 600.000 nordafrikanske og vest-afrikanske tropper kæmpede for Frankrig — og disse soldater vendte hjem med erfaring med europæisk vold og krav om de rettigheder de kæmpede for. Kolonierne finansierede og bemandede en krig de ikke havde valgt","Koloniale tropper deltog fuldstændig frivilligt og med fuld ligebehandling og oplevede ingen form for racemæssig diskrimination","De koloniale troppers inddragelse beviser at kolonialisme var et gensidigt fordelagtigt system med ægte fællesskabsfølelse","Inddragelsen er historisk marginal og bør ikke vurderes i en krigshistorisk sammenhæng da tallene er for små"],"correct":"Det afslører at kolonimagternes krige hvilede på koloniserede befolkningers ofre: over en million indiske soldater kæmpede for det britiske imperium, 600.000 nordafrikanske og vest-afrikanske tropper kæmpede for Frankrig — og disse soldater vendte hjem med erfaring med europæisk vold og krav om de rettigheder de kæmpede for. Kolonierne finansierede og bemandede en krig de ikke havde valgt","accepted_answers":["Det afslører at kolonimagternes krige hvilede på koloniserede befolkningers ofre: over en million indiske soldater kæmpede for det britiske imperium, 600.000 nordafrikanske og vest-afrikanske tropper kæmpede for Frankrig — og disse soldater vendte hjem med erfaring med europæisk vold og krav om de rettigheder de kæmpede for. Kolonierne finansierede og bemandede en krig de ikke havde valgt"],"review_text":"1. Verdenskrig var aldrig kun en europæisk krig. Britisk Indien bidrog med 1,5 millioner soldater. Det franske empire brugte Tirailleurs Sénégalais i fronttjeneste. Australien, Canada, New Zealand og Sydafrika sendte hundredetusinder. Den historiske konsekvens: koloniserede folk der kæmpede for europæiske frihedsidealer vendte hjem og stillede spørgsmålet om deres egen frihed. W.E.B. Du Bois analyserede i The African Roots of War (1915) at imperialismen var krigens egentlige drivkraft. Nationalistbevægelserne i Indien (Gandhi), Vietnam (Ho Chi Minh var i Paris under fredsforhandlingerne) og Afrika fik stærkere legitimitet efter 1918. Versailles-konferencens afvisning af Japans racelighedserklæring viste at Wilsons selvbestemmelsesprincipper ikke gjaldt for ikke-hvide folk — en afvisning der direkte accelererede antikoloniale bevægelser globalt."}$$::jsonb,
  'mc','short',$${"concepts":["koloniale tropper","imperialisme","selvbestemmelse","antikolonialisme","Du Bois","Versailles og race"],"misconception_type":"scope_confusion","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}$$::jsonb,
  'mc_single',5,'auto',true,'world_war_1',9,5
);

-- ─── BAND 5 · HISTORIOGRAFI (4 questions) ────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er den vigtigste metodologiske lære af Fischer-kontroversualen for historievidenskaben generelt?","options":["At primærkilder som politiske dokumenter ikke entydigt beviser intentioner: Fischer brugte september-programmet som bevis for krigsplanlægning, men dokumentet er udfærdiget efter krigsudbrudet under krigens pres — den samme kilde kan fortolkes som krigsformålsdokument snarere end som bevis for prækrig-intention. Kildekritik kræver kontekstanalyse ikke blot kildelæsning","At tyske arkiver er de eneste relevante for at forstå 1. Verdenskrigs årsager og alle andre nationers arkiver er sekundære","At Fritz Fischer bevidst forfalskede historien og dermed diskvalificerer sig som historiker","At politiske dokumenter altid afspejler nøjagtigt de intentioner der lå bag dem og kan bruges som direkte bevis"],"correct":"At primærkilder som politiske dokumenter ikke entydigt beviser intentioner: Fischer brugte september-programmet som bevis for krigsplanlægning, men dokumentet er udfærdiget efter krigsudbrudet under krigens pres — den samme kilde kan fortolkes som krigsformålsdokument snarere end som bevis for prækrig-intention. Kildekritik kræver kontekstanalyse ikke blot kildelæsning","accepted_answers":["At primærkilder som politiske dokumenter ikke entydigt beviser intentioner: Fischer brugte september-programmet som bevis for krigsplanlægning, men dokumentet er udfærdiget efter krigsudbrudet under krigens pres — den samme kilde kan fortolkes som krigsformålsdokument snarere end som bevis for prækrig-intention. Kildekritik kræver kontekstanalyse ikke blot kildelæsning"],"review_text":"Fischer-kontroversen er metodologisk lærerig ud over sin historiske substans. Fischers kildebrug illustrerer en central faldgrube: at slutte fra hvad en stat gør under krigen til hvad den planlagde før krigen. September-programmet er et beslaglæggelsesdokument — det beskriver hvad Bethmann Hollweg ville gøre med sejren hvis den kom. Det beviser at tyske krigsmål var ekspansionistiske, men det beviser ikke at disse mål eksisterede og drev udenrigspolitikken inden august 1914. Kritikerne (Ritter, Erdmann) påpegede at konteksten — krigen var allerede i gang — er afgørende for dokumentets fortolkning. Lektionen er universel: primærkilder er ikke transparente vinduer til fortiden men tekster der kræver kontekstanalyse. At bestemme hvad en kilde beviser versus hvad den blot antyder er kildekritikkens kerneopgave."}$$::jsonb,
  'mc','short',$${"concepts":["kildekritik","september-programmet","intentionsbevis","Fischer-metode","kontekstanalyse","historiografi"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}$$::jsonb,
  'mc_single',5,'auto',true,'world_war_1',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er den vigtigste forskel på intentionalistiske og strukturelle forklaringer af 1. Verdenskrigs udbrud — og hvilken type forklaring er metodisk stærkest?","options":["Intentionalister fokuserer på ledernes bevidste valg og planer (Fischer: Tysland planlagde krigen), strukturalister fokuserer på systemiske faktorer (alliancer, kappestriden, mobiliseringslogik). Metodisk er begge nødvendige og utilstrækkelige alene: struktur forklarer mulighedsbetingelserne, intention forklarer de konkrete valg — syntesen er mest frugtbar","Intentionalistiske forklaringer er altid metodisk overlegne fordi krige kun kan udbrydes af bevidste valg","Strukturelle forklaringer er altid metodisk overlegne fordi menneskelig intention er uverificerbar og dermed uvidenskabelig","Distinktionen er irrelevant — alle historiske forklaringer er blot politiske fortolkninger uden metodisk hierarki"],"correct":"Intentionalister fokuserer på ledernes bevidste valg og planer (Fischer: Tysland planlagde krigen), strukturalister fokuserer på systemiske faktorer (alliancer, kappestriden, mobiliseringslogik). Metodisk er begge nødvendige og utilstrækkelige alene: struktur forklarer mulighedsbetingelserne, intention forklarer de konkrete valg — syntesen er mest frugtbar","accepted_answers":["Intentionalister fokuserer på ledernes bevidste valg og planer (Fischer: Tysland planlagde krigen), strukturalister fokuserer på systemiske faktorer (alliancer, kappestriden, mobiliseringslogik). Metodisk er begge nødvendige og utilstrækkelige alene: struktur forklarer mulighedsbetingelserne, intention forklarer de konkrete valg — syntesen er mest frugtbar"],"review_text":"Intentionalisme og strukturalisme repræsenterer to grundlæggende historiografiske orienteringer der går langt ud over 1. Verdenskrig. Fischers intentionalisme sætter menneskelig vilje og plan i centrum og frisætter historikeren til at placere moralsk ansvar. Den strukturalistiske skole (Taylor i The Origins of the Second World War, eller systemperspektivet hos Kennedy) ser strukturer som det primære — individers handlinger er determineret eller i det mindste kraftigt kanaliseret af de systemer de opererer inden for. Metodisk producerer rene intentionalistiske forklaringer et identifikationsproblem: intentioner kan ikke observeres direkte, kun infereres fra handlinger og tekster. Rene strukturforklaringer risikerer at fratage aktørerne handlingsfrihed og dermed moralsk ansvar. Den frugtbare syntese — som Margaret MacMillan og Christopher Clark praktiserer — kombinerer begge: strukturer definerer handlingsrummet, aktørerne fylder det med konkrete valg."}$$::jsonb,
  'mc','short',$${"concepts":["intentionalisme","strukturalisme","metodologi","Fischer","MacMillan","forklaringstyper"],"misconception_type":"false_equivalence","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}$$::jsonb,
  'mc_single',5,'auto',true,'world_war_1',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er den historiografiske konsensus om Versailles-traktatens rolle i Hitlers fremvækst — og hvad er svaghederne ved den simplificerede kausalitet?","options":["Versailles var en nødvendig men ikke tilstrækkelig faktor: den skabte legitim frustration i Tyskland der Nazi-propagandaen udnyttede, men mange europæiske lande led under lign ydmygelse uden at producere fascisme. Kausaliteten er kompleks: Weimarrepublikkens institutionelle svagheder, den store depression og de konservative politikeres fejltagelser i 1932-33 var ligesom Versailles afgørende","Versailles forårsagede direkte og uundgåeligt Hitlers fremvækst — uden Versailles ingen Hitler","Versailles var fuldstændig irrelevant for Hitlers fremvækst — årsagen var udelukkende Hitlers personlighed","Versailles var for mild — en hårdere fred ville have forhindret Hitlers fremvækst ved at eliminere Tysklands militære kapacitet fuldstændigt"],"correct":"Versailles var en nødvendig men ikke tilstrækkelig faktor: den skabte legitim frustration i Tyskland der Nazi-propagandaen udnyttede, men mange europæiske lande led under lign ydmygelse uden at producere fascisme. Kausaliteten er kompleks: Weimarrepublikkens institutionelle svagheder, den store depression og de konservative politikeres fejltagelser i 1932-33 var ligesom Versailles afgørende","accepted_answers":["Versailles var en nødvendig men ikke tilstrækkelig faktor: den skabte legitim frustration i Tyskland der Nazi-propagandaen udnyttede, men mange europæiske lande led under lign ydmygelse uden at producere fascisme. Kausaliteten er kompleks: Weimarrepublikkens institutionelle svagheder, den store depression og de konservative politikeres fejltagelser i 1932-33 var ligesom Versailles afgørende"],"review_text":"Dolkstødslegenden og Versailles-ydmygelsen var hjørnestenen i Nazistisk propaganda. Men historiografisk er den direkte kausalitet uholdbar. Ungarn (Trianon-traktaten), Bulgarien og Østrig led under identisk ydmygende fredsbetingelser uden at producere et sammenligneligtfascistisk regime af Hitlertypes rækkevidde. John Maynard Keynes kritik af Versailles i The Economic Consequences of the Peace (1919) var indflydelsesrig og rettede — freden var for hård til at stå og for mild til at lamme. Men Keynes kan ikke bevise at en anderledes fred ville have forhindret Hitler. Den store depression (1929-33), Weimarrepublikkens forfatningelle svagheder (artikel 48), von Hindenburgs tillidsbrist til parlamentarisk regering og de konservatives bevidste undervurdering af Hitler i januar 1933 er alle mindst ligeså afgørende faktorer. Monokausal Versailles-forklaring er attraktiv men historisk utilstrækkelig."}$$::jsonb,
  'mc','short',$${"concepts":["Versailles","Hitler","monokausalitet","Keynes","Weimar","nødvendig vs tilstrækkelig"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}$$::jsonb,
  'mc_single',5,'auto',true,'world_war_1',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad afslører erindringskulturen og mindesmærkerne for de faldne i 1. Verdenskrig om det politiske indhold i historisk hukommelse?","options":["Erindringskulturen er politisk konstrueret og eksklusiv: britiske og franske mindesmærker centrerer om de hvide imperietropper, medens koloniale soldater stort set er usynlige — og nationernes fortolkning af krigen (britisk: heroisk offer, tysk: forrædt af Dolkstød, franskmænd: forsvar af civilisation) tjener politiske narrativer frem for at formidle krigens fulde kompleksitet","Mindesmærker og erindringskultur er politisk neutrale — de afspejler objektivt historiske kendsgerninger","Alle landes erindringskultur er identisk og der er ingen national forskel i hvordan 1. Verdenskrig erindres og fortolkes","Erindringskulturen er udelukkende styret af veteraners private sorg og har intet politisk indhold"],"correct":"Erindringskulturen er politisk konstrueret og eksklusiv: britiske og franske mindesmærker centrerer om de hvide imperietropper, medens koloniale soldater stort set er usynlige — og nationernes fortolkning af krigen (britisk: heroisk offer, tysk: forrædt af Dolkstød, franskmænd: forsvar af civilisation) tjener politiske narrativer frem for at formidle krigens fulde kompleksitet","accepted_answers":["Erindringskulturen er politisk konstrueret og eksklusiv: britiske og franske mindesmærker centrerer om de hvide imperietropper, medens koloniale soldater stort set er usynlige — og nationernes fortolkning af krigen (britisk: heroisk offer, tysk: forrædt af Dolkstød, franskmænd: forsvar af civilisation) tjener politiske narrativer frem for at formidle krigens fulde kompleksitet"],"review_text":"Paul Fussells The Great War and Modern Memory (1975) er grundværket om 1. Verdenskrigs litterære og kulturelle erindringskultur. Jay Winters Sites of Memory, Sites of Mourning viser at mindesmærker er politisk og socialt konstruerede rum. Den britiske poppy-tradition er nationalt samlende men ekskluderer de 1,5 million indiske soldater der kæmpede for imperiet — Thiepval Memorial nævner dem næppe. Den tyske dolkstødslegende er det mest katastrofale eksempel: en politisk myte konstrueret af generaler for at unddrage militæret ansvaret for nederlaget og placere det på civile og socialdemokrater — med fatale konsekvenser for Weimarrepublikken. Erindringspolitik er aldrig neutral: hvem erindres, hvilke ofre anerkendes og hvilke fortolkningsrammer dominerer er altid resultatet af magtrelationer."}$$::jsonb,
  'mc','short',$${"concepts":["erindringspolitik","mindesmærker","koloniale soldater","dolkstødslegende","Fussell","konstrueret hukommelse"],"misconception_type":"scope_confusion","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}$$::jsonb,
  'mc_single',5,'auto',true,'world_war_1',9,5
);

-- ─── BAND 5 · VERSAILLES & KONSEKVENSER (4 questions) ────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Var Versailles-traktaten af 1919 for hård, for mild eller et strukturelt uholdbartdokument — og hvad er det stærkeste argument for hvert synspunkt?","options":["Strukturelt uholdbart: for hård til at accepteres som permanent løsning men for mild til at lamme Tysklands militære genrejsning. Keynes argumentation: de reparationskrav der faktisk var mulige at inddrive var ikke store nok til permanent at svække Tyskland, men selve ydmygelsen og symbolpolitikken (artikel 231) skabte politisk fjendskab som freden ikke kunne overleve","For hård: reparationerne var så store at ingen fredstid-regulering var mulig og ydmygelsen var unødvendig og kontraproduktiv","For mild: en hård Carthagofreds (som Frankrig ønskede) ville have forhindret Tysklands militære genopbygning og dermed elimineret betingelserne for 2. Verdenskrig","Versailles var retfærdig og fuldt proportional med Tysklands faktiske ansvar og krigsskade"],"correct":"Strukturelt uholdbart: for hård til at accepteres som permanent løsning men for mild til at lamme Tysklands militære genrejsning. Keynes argumentation: de reparationskrav der faktisk var mulige at inddrive var ikke store nok til permanent at svækketyskland, men selve ydmygelsen og symbolpolitikken (artikel 231) skabte politisk fjendskab som freden ikke kunne overleve","accepted_answers":["Strukturelt uholdbart: for hård til at accepteres som permanent løsning men for mild til at lamme Tysklands militære genrejsning. Keynes argumentation: de reparationskrav der faktisk var mulige at inddrive var ikke store nok til permanent at svækketyskland, men selve ydmygelsen og symbolpolitikken (artikel 231) skabte politisk fjendskab som freden ikke kunne overleve"],"review_text":"Keynes analyserede i 1919 at Versailles var uholdbar: reparationskravene (132 milliarder guldmark) oversteg det Europa der faktisk kunne inddrive, og freden var for mild til at lamme og for hård til at forsone. Franske generaler som Foch kommenterede: dette er ikke fred, det er en 20-årig våbenstilstand. Margaret MacMillan og Sally Marks har nyanseret billedet: de faktiske reparationsbetalinger Weimar-Tyskland foretog var relativt beskedne (inflationen i 1923 annullerede effektivt den tidlige gæld), og det var symbolpolitikken — artikel 231, Rhinlands besættelse, tabet af Elsass-Lothringen — der var politisk uacceptabel i tysk opinion. Den komplekse strukturelle uholdbarhed er metodisk den stærkeste position: Versailles var hverken konsekvent hård eller konsekvent mild men snarere et ustabilt kompromis der tilfredsstillede ingen."}$$::jsonb,
  'mc','short',$${"concepts":["Versailles","Keynes","reparationer","artikel 231","strukturel uholdbarhed","Carthagofreds"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}$$::jsonb,
  'mc_single',5,'auto',true,'world_war_1',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad var det grundlæggende dilemma i Woodrow Wilsons 14 punkter som fredsgrundlag — og hvorfor lykkedes det ikke at realisere dem?","options":["Dilemmaet var spændingen mellem universelle principper (selvbestemmelse, åbne forhandlinger, folkenes ret) og realpolitisk logik (Frankrigs sikkerhedskrav, Storbritanniens imperiale interesser, Italiens territoriale ambitioner). Wilsons idealisme manglede institutionel magt til at realiseres mod alliancepartnernes modstand — og USA ratificerede ikke selv Folkeforbundet","Wilsons 14 punkter blev fuldt realiseret i Versailles-traktaten og Folkeforbundets oprettelse","Dilemmaet var at Wilson personligt var korrupt og solgte principperne til Frankrig og England","Principperne fejlede fordi selvbestemmelse er et inkoherent begreb der aldrig kan operationaliseres i praksis"],"correct":"Dilemmaet var spændingen mellem universelle principper (selvbestemmelse, åbne forhandlinger, folkenes ret) og realpolitisk logik (Frankrigs sikkerhedskrav, Storbritanniens imperiale interesser, Italiens territoriale ambitioner). Wilsons idealisme manglede institutionel magt til at realiseres mod alliancepartnernes modstand — og USA ratificerede ikke selv Folkeforbundet","accepted_answers":["Dilemmaet var spændingen mellem universelle principper (selvbestemmelse, åbne forhandlinger, folkenes ret) og realpolitisk logik (Frankrigs sikkerhedskrav, Storbritanniens imperiale interesser, Italiens territoriale ambitioner). Wilsons idealisme manglede institutionel magt til at realiseres mod alliancepartnernes modstand — og USA ratificerede ikke selv Folkeforbundet"],"review_text":"Wilsons 14 punkter (8. januar 1918) var et genuint idealismeprojekt: punkt 1 (åbne forhandlinger), punkt 3 (frihandel), punkt 14 (Folkeforbundet). Men Paris-fredskonferencen i 1919 var domineret af Clemenceau (Frankrig krævede kompensation og sikkerhed) og Lloyd George (der var under parlamentarisk pres). Wilsons selvbestemmelsesprincipper blev selektivt anvendt: tyske mindretal i Tjekkiet og Polen fik ikke selvbestemmelse, koloniserede folk i Afrika og Asien fik det slet ikke. Den egyptiske delegation (Wafd) og den vietnamesiske (med Ho Chi Minh) blev ignoreret. Og den ultimative ironi: det amerikanske senat ratificerede ikke Folkeforbundspagten — USA trak sig fra sin egen grundlæggelse. Dilemmaet er klassisk og tidløst: universalistisk idealistisk diplomati konfronteret med realpolitiske interesser og institutionelle begrænsninger."}$$::jsonb,
  'mc','short',$${"concepts":["Wilson","14 punkter","selvbestemmelse","idealism vs realpolitik","Folkeforbundet","Paris-fredskonference"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}$$::jsonb,
  'mc_single',5,'auto',true,'world_war_1',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Gjorde 1. Verdenskrig 2. Verdenskrig historisk nødvendig — eller var der strukturelle muligheder for at undgå den anden krig?","options":["Ikke nødvendig men sandsynliggjort: Versailles skabte reel frustration og en ustabil europæisk orden, men mange faktorer var kontingente — depression, Weimarrepublikkens institutionelle svagheder og konservativernes undervurdering af Hitler i 1932-33 var selvstændige variable. En anderledes Versailles (Marshallplan-logik) kunne have ændret sandsynligheden","Fuldt nødvendig: Versailles bestemte automatisk at en 2. Verdenskrig ville følge inden for 30 år","Ikke relateret: 2. Verdenskrig opstod uafhængigt af 1. Verdenskrig og er primært resultatet af Hitlers psykologiske særtræk","1. Verdenskrig forhindrede faktisk en potentielt endnu mere destruktiv 2. Verdenskrig ved at udtømme de europæiske stormagters militære kapacitet"],"correct":"Ikke nødvendig men sandsynliggjort: Versailles skabte reel frustration og en ustabil europæisk orden, men mange faktorer var kontingente — depression, Weimarrepublikkens institutionelle svagheder og konservativernes undervurdering af Hitler i 1932-33 var selvstændige variable. En anderledes Versailles (Marshallplan-logik) kunne have ændret sandsynligheden","accepted_answers":["Ikke nødvendig men sandsynliggjort: Versailles skabte reel frustration og en ustabil europæisk orden, men mange faktorer var kontingente — depression, Weimarrepublikkens institutionelle svagheder og konservativernes undervurdering af Hitler i 1932-33 var selvstændige variable. En anderledes Versailles (Marshallplan-logik) kunne have ændret sandsynligheden"],"review_text":"Determinismen Versailles→Hitler→krig er historiografisk attraktiv men overforenklet. De historiske argumenter for kontingensen: (1) Weimars relativt succesfulde stabiliseringsperiode 1924-29 (Dawes-planen, Locarno-traktaten, Stresemann) viste at forsoningspolitik var mulig, (2) den store depression som eksogen shockfaktor kollapsede Weimarrepublikkens sociale grundlag på en måde ingen traktat hatte determineret, (3) Hitlers vej til magten krævede specifik elitepolitisk fejlberegning i januar 1933. Kontrafaktisk: USA implementerede i 1948 Marshallplanen der modtager-finansierede netop de lande USA havde vundet over i 2. Verdenskrig — og producerede stabilt demokrati og fred. Marshallplanens logik gjaldt ikke i 1919 og det er et kontingent faktum, ikke en strukturel nødvendighed. Historisk nødvendighed er et uholdbart begreb — det fratager aktørerne handlingsfrihed og dermed ansvar."}$$::jsonb,
  'mc','short',$${"concepts":["determinisme","kontingent årsag","Marshallplan","Weimar","depression","historisk nødvendighed"],"misconception_type":"causal_inversion","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}$$::jsonb,
  'mc_single',5,'auto',true,'world_war_1',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad viser frafaldet af Wilsons 14 punkter på Paris-konferencen om forholdet mellem international idealistisk folkeret og national interesse i fredsskabelse?","options":["At folkeret og universelle principper kun kan realiseres hvis de store magtaktører har incitament til at overholde dem — Wilson manglede tvangsmiddel og indenrigspolitisk støtte, mens Clemenceau og Lloyd George havde nationale valgtekniske og sikkerhedsmæssige grunde til at afvise principperne. Folkeret er ikke selvhåndhævende","At folkeret automatisk sejrer i internationale forhandlinger fordi den repræsenterer den moralske sandhed","At Wilsons principper var fejlagtige og international orden altid og kun bygger på realpower","At frafaldet beviser at idealistisk diplomati aldrig bør forsøges da det altid korrumperes af realpolitik"],"correct":"At folkeret og universelle principper kun kan realiseres hvis de store magtaktører har incitament til at overholde dem — Wilson manglede tvangsmiddel og indenrigspolitisk støtte, mens Clemenceau og Lloyd George havde nationale valgtekniske og sikkerhedsmæssige grunde til at afvise principperne. Folkeret er ikke selvhåndhævende","accepted_answers":["At folkeret og universelle principper kun kan realiseres hvis de store magtaktører har incitament til at overholde dem — Wilson manglede tvangsmiddel og indenrigspolitisk støtte, mens Clemenceau og Lloyd George havde nationale valgtekniske og sikkerhedsmæssige grunde til at afvise principperne. Folkeret er ikke selvhåndhævende"],"review_text":"Wilsons forhandlingssituation i Paris illustrerer folkeret-realpolitik-paradokset. Han var institutionelt svag: USA deltog ikke i krigen fra starten, han var under partisan-politisk pres hjemme (det republikanskkontrollerede senat), og hans helbredsproblemer svækkede ham i forhandlingernes afgørende fase. Clemenceau havde et mandsat fra den franske befolkning om hård fred. Lloyd George var midt i et valg der kørte på We will make Germany pay. Ingen af de europæiske stormagter havde incitament til at prioritere wilsonske principper over nationale interesser. Det klassiske folkeret-problem: universel ret er kun bindende hvis dem den binder den accepterer og håndhæver den. Folkeforbundets manglende teeth — ingen bindende håndhævelsesmekanisme og USA udeblev — demonstrerede det samme: international orden kræver magtunderstøttelse, ikke blot moralsk autoritet."}$$::jsonb,
  'mc','short',$${"concepts":["folkeret","realpolitik","Wilson","Clemenceau","håndhævelse","Folkeforbundet"],"misconception_type":"false_equivalence","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}$$::jsonb,
  'mc_single',5,'auto',true,'world_war_1',9,5
);

-- ─── BAND 5 · MODERNE RELEVANS (4 questions) ─────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er de vigtigste lektioner fra julikrisen 1914 for krisehåndtering i en verden med moderne kernevåben og hurtige kommunikationssystemer?","options":["At krisekommunikation, klare deeskaleringsmekanismer og forståelse for modpartens intern politiske pres er afgørende — 1914 viste at fejlfortolkning af signaler, mobiliseringstidslinjer der ikke tillod pause og manglende direkte kommunikationskanaler eskalerede en regional konflikt til verdenskrig. Moderne kernevåben gør tilsvarende eskalering eksistentielt katastrofal","At moderne kommunikationsteknologi har fuldstændig elimineret risikoen for 1914-type fejlkommunikation","At kernevåben alene løser krisehåndteringsproblemet via afskrækkelsens automatiske stabiliserende effekt","At 1914-lektionerne ikke er relevante for det 21. århundrede fordi geopolitisk kontekst er fuldstændig anderledes"],"correct":"At krisekommunikation, klare deeskaleringsmekanismer og forståelse for modpartens intern politiske pres er afgørende — 1914 viste at fejlfortolkning af signaler, mobiliseringstidslinjer der ikke tillod pause og manglende direkte kommunikationskanaler eskalerede en regional konflikt til verdenskrig. Moderne kernevåben gør tilsvarende eskalering eksistentielt katastrofal","accepted_answers":["At krisekommunikation, klare deeskaleringsmekanismer og forståelse for modpartens intern politiske pres er afgørende — 1914 viste at fejlfortolkning af signaler, mobiliseringstidslinjer der ikke tillod pause og manglende direkte kommunikationskanaler eskalerede en regional konflikt til verdenskrig. Moderne kernevåben gør tilsvarende eskalering eksistentielt katastrofal"],"review_text":"Graham Allisons Essence of Decision (Cuba-analyse) og Robert Jervis Perception and Misperception in International Politics anvender 1914-lektionerne direkte på moderne krisehåndtering. I julikrisen 1914: de diplomatiske kanaler var langsomme (telegram tog 12-24 timer), mobiliseringsplanerne var stive tidsplaner der ikke tillod politisk afbrydelse, og ledere fejlfortolkede hinandens signaler systematisk (Østrig troede Rusland bluffede, Rusland troede Østrig ville acceptere det serbiske svar). Den røde telefon (oprettet 1963 efter Cubas missilkrise) var direkte inspireret af 1914-analogien. I dag er kommunikationsteknologien hurtigere men krisedynamikken er ikke forsvundet: Taiwan-strædekriser, nordkoreanske provokationer og Rusland-NATO-konflikter aktiverer præcis de samme eskaleringslogikker. Forskellen er at moderne kernevåben giver en eksponentielt større konsekvens af fejlkalkule."}$$::jsonb,
  'mc','short',$${"concepts":["krisehåndtering","kommunikation","eskalering","kernevåben","julikrise 1914","moderne relevans"],"misconception_type":"scope_confusion","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}$$::jsonb,
  'mc_single',5,'auto',true,'world_war_1',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Er det australske og newzealandske ANZAC-narrativ et eksempel på legitim national erindringskultur eller en selektiv mytologisering der forvrænger historien?","options":["Begge på én gang: ANZAC-narrativet bygger på reelle krigsofre og reel tapperhed ved Gallipoli og Vestfronten — men det selektiviserer og mytologiserer ved at fremstille Gallipoli som en nations-fordrende begivenhed, ignorere at kampagnen var et strategisk fiasko planlagt af Churchill, og underspille at australske og newzealandske soldater kæmpede for et britisk imperium der ikke behandlede dem som ligeværdige","ANZAC-narrativet er ren propaganda uden historisk grundlag","ANZAC er en fuldstændig objektiv historisk rekonstruktion af krigen uden nogen form for national mytologisering","National erindringskultur er altid legitimt og bør aldrig analyseres kritisk fordi det krænker de faldnes minde"],"correct":"Begge på én gang: ANZAC-narrativet bygger på reelle krigsofre og reel tapperhed ved Gallipoli og Vestfronten — men det selektiviserer og mytologiserer ved at fremstille Gallipoli som en nations-fordrende begivenhed, ignorere at kampagnen var et strategisk fiasko planlagt af Churchill, og underspille at australske og newzealandske soldater kæmpede for et britisk imperium der ikke behandlede dem som ligeværdige","accepted_answers":["Begge på én gang: ANZAC-narrativet bygger på reelle krigsofre og reel tapperhed ved Gallipoli og Vestfronten — men det selektiviserer og mytologiserer ved at fremstille Gallipoli som en nations-fordrende begivenhed, ignorere at kampagnen var et strategisk fiasko planlagt af Churchill, og underspille at australske og newzealandske soldater kæmpede for et britisk imperium der ikke behandlede dem som ligeværdige"],"review_text":"ANZAC Day (25. april) er Australiens og New Zealands vigtigste nationale højtid — et rite de passage der er blevet stadig mere fremtrædende siden 1980erne. Historiografisk er ANZAC-narrativet både autentisk og konstrueret. Gallipoli-kampagnen (april-december 1915) var et katastrofalt strategisk fejlskridt baseret på Churchills optimistiske vurdering af Dardanellernes forsvarbarhed — 8.709 australske og 2.721 newzealandske soldater døde, og kampagnen mislykkedes fuldstændigt. Alligevel er den mytologiseret som nations-fødsel. Kritikere som Henry Reynolds og Marilyn Lake påpeger at narrativet ekskluderer de Aboriginale og Maori soldater der kæmpede, og at den heroiske ramme forhindrer en kritisk analyse af imperialismens rolle. Det er et universelt mønster: nationale erindringskulturer indeholder altid et udvalg der tjener national sammenhængskraft på bekostning af historisk kompleksitet."}$$::jsonb,
  'mc','short',$${"concepts":["ANZAC","national erindringskultur","Gallipoli","mytologisering","Churchill","selektiv hukommelse"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}$$::jsonb,
  'mc_single',5,'auto',true,'world_war_1',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Er nationalisme i det 21. århundrede stadig en potentiel kilde til mellemstatslig konflikt — og hvad kan 1914-erfaringen bidrage med til denne analyse?","options":["Ja — nationalisme kan fortsat destabilisere: 1914 viser at nationalistisk opinion kan gøre diplomatisk deeskalering politisk umulig for ledere under valgpres. Nutidigt: Kinas nationalisme om Taiwan, indisk-pakistansk nationalisme om Kashmir og russisk nationalisme om Ukraine demonstrerer at mekanismerne fra 1914 ikke er historiske kuriositeter","Nej — moderne demokratier er strukturelt immune mod nationalistisk krigsrisiko fordi demokratier aldrig kæmper mod hinanden","1914-erfaringen er irrelevant for det 21. århundrede fordi nationalisme er elimineret som politisk kraft af globalisering","Nationalisme er i dag udelukkende en positiv kraft der styrker demokratisk deltagelse uden destabiliserende konsekvenser"],"correct":"Ja — nationalisme kan fortsat destabilisere: 1914 viser at nationalistisk opinion kan gøre diplomatisk deeskalering politisk umulig for ledere under valgpres. Nutidigt: Kinas nationalisme om Taiwan, indisk-pakistansk nationalisme om Kashmir og russisk nationalisme om Ukraine demonstrerer at mekanismerne fra 1914 ikke er historiske kuriositeter","accepted_answers":["Ja — nationalisme kan fortsat destabilisere: 1914 viser at nationalistisk opinion kan gøre diplomatisk deeskalering politisk umulig for ledere under valgpres. Nutidigt: Kinas nationalisme om Taiwan, indisk-pakistansk nationalisme om Kashmir og russisk nationalisme om Ukraine demonstrerer at mekanismerne fra 1914 ikke er historiske kuriositeter"],"review_text":"1914-lektionerne om nationalismens destabiliserende potentiale er direkte overførbare. Mekanismen: nationalistisk opinion sætter et loft for hvad ledere kan forhandle sig til uden at miste legitimitet. Østrigs udenrigsminister Berchtold vidste at et mildt svar på Sarajevo-attentatet ville cost ham dynastisk og politisk kapital — det nationalistiske pres begrænsede rationaliteten. I det 21. århundrede: Kinas nationalistiske opinion om Taiwan giver Xi Jinping begrænset forhandlingsrum; Indiens og Pakistans nationalistiske pres om Kashmir gør de-eskalering efter grænseincidenter politisk farlig for lederne; Putins Rusland-nationalisme om Ukraine (Rusland og Ukraine som ét folk) reducerede hans forhandlingsvilje. Den demokratiske fredsteoris antagelse om at demokratiske ledere altid kan kontrollere nationalistisk pres er empirisk fejlagtig — populistisk demokrati kan forstærke nationalistisk logik snarere end dæmpe den."}$$::jsonb,
  'mc','short',$${"concepts":["nationalisme","destabilisering","Taiwan","Kashmir","Ukraine","demokratisk fredsteori"],"misconception_type":"overgeneralization","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}$$::jsonb,
  'mc_single',5,'auto',true,'world_war_1',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er 1. Verdenskrigens vigtigste bidrag til det internationale systems institutionelle arkitektur — og har de institutioner der opstod leveret på løftet?","options":["Krigens vigtigste bidrag var etableringen af idéen om kollektiv sikkerhed via Folkeforbundet — at stater forpligter sig til kollektivt at standse aggression. Folkeforbundet mislykkedes (Japan 1931, Italien 1935, ingen reaktion på Hitler) men dets fejl informerede FN-designet som er mere robust — selvom vetorettens paralyserende dynamik reproducerer det centrale problem","Folkeforbundet var en fuldstændig succes der effektivt forhindrede alle efterfølgende konflikter","1. Verdenskrig bidrog intet til international institutionel arkitektur — alle vigtige internationale institutioner opstod uafhængigt","Folkeforbundets fiasko beviser at kollektiv sikkerhed som princip er fuldstændig ubrugelig og at realpower er den eneste stabile basis for international orden"],"correct":"Krigens vigtigste bidrag var etableringen af idéen om kollektiv sikkerhed via Folkeforbundet — at stater forpligter sig til kollektivt at standse aggression. Folkeforbundet mislykkedes (Japan 1931, Italien 1935, ingen reaktion på Hitler) men dets fejl informerede FN-designet som er mere robust — selvom vetorettens paralyserende dynamik reproducerer det centrale problem","accepted_answers":["Krigens vigtigste bidrag var etableringen af idéen om kollektiv sikkerhed via Folkeforbundet — at stater forpligter sig til kollektivt at standse aggression. Folkeforbundet mislykkedes (Japan 1931, Italien 1935, ingen reaktion på Hitler) men dets fejl informerede FN-designet som er mere robust — selvom vetorettens paralyserende dynamik reproducerer det centrale problem"],"review_text":"1. Verdenskrig producerede to transformative institutionelle ideer: kollektiv sikkerhed (Folkeforbundet) og human rights-baseret international ret (Nürnberg-principperne kom fra 2. krig men var intellektuelt grundlagt i reaktionen på 1. verdenskrigs grusomheder). Folkeforbundet fejlede af tre årsager: ingen universal deltagelse (USA udeblev, Sovjet udelukket initialt), ingen bindende håndhævelsesmekanisme og enstemmighedskravet lammet beslutningsdygtighed. FN forsøgte at rette disse: et Sikkerhedsråd med fem permanente magter og mulighed for kvalificeret flertalsbeslutning. Men den permanente medlens vetoretten reproducerede en ny version af enstemmigheds-problemet: Rusland og Kinas veto over Syrien, USA over Israel. Institutionel læring er reel men begrænset: hvert design-fix skaber nye designproblemer, og magtpolitik underminerer systematisk universelle principper."}$$::jsonb,
  'mc','short',$${"concepts":["kollektiv sikkerhed","Folkeforbundet","FN","vetoretten","institutionel læring","håndhævelse"],"misconception_type":"causal_inversion","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}$$::jsonb,
  'mc_single',5,'auto',true,'world_war_1',9,5
);
