-- Section 82 — World War 1 — Grade 7 (25 questions)

-- ─── GRADE 7 · BAND 1 (6 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var alliancesystemet foer Forste Verdenskrig?","options":["En raekke aftaler der betod at hvis et land blev angrebet maatte dets allierede hjaelpe det","En handelsaftale der hjalp lande med at saelge varer til hinanden","En fredsaftale der garanterede at Europa aldrig ville have krig igen","Et system hvor lande maatte spoerge en domstol foer de aabnede krig"],"correct":"En raekke aftaler der betod at hvis et land blev angrebet maatte dets allierede hjaelpe det","accepted_answers":["En raekke aftaler der betod at hvis et land blev angrebet maatte dets allierede hjaelpe det"],"review_text":"Europa var delt i to store alliancer. Triple Entente: Frankrig, Rusland og England. Triple Alliance: Germany, Oestrig-Ungarn og Italien. Hvis et land gik i krig ville alle dets allierede automatisk goere det samme."}'::jsonb,
  'mc','short','{"concepts":["alliancer","Triple Entente","Triple Alliance","automatisk krig"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_1',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvem blev myrdet i Sarajevo i 1914 og udloeste dermed Forste Verdenskrig?","options":["Den ostrigsk-ungarnske aartehertug Franz Ferdinand","Kejser Wilhelm II af Germany","Tsar Nikolaj II af Rusland","Kong George V af England"],"correct":"Den ostrigsk-ungarnske aartehertug Franz Ferdinand","accepted_answers":["Den ostrigsk-ungarnske aartehertug Franz Ferdinand"],"review_text":"Den 28. juni 1914 blev den ostrigsk-ungarnske aartehertug Franz Ferdinand skudt i Sarajevo. Gerningsmanden var den serbiske nationalist Gavrilo Princip. Mordet udloeste en kaedereaktion der endte i verdenskrig."}'::jsonb,
  'mc','short','{"concepts":["Franz Ferdinand","Sarajevo","mordet","udbrud"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_1',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var skyttegravskrig?","options":["En type krig hvor soldaterne boede og kaempede i lange udgravede groefte","En type krig der foregik paa havet","En krig hvor kavaleri var den vigtigste styrke","En krig der foregik i bjerge og skove"],"correct":"En type krig hvor soldaterne boede og kaempede i lange udgravede groefte","accepted_answers":["En type krig hvor soldaterne boede og kaempede i lange udgravede groefte"],"review_text":"Paa Vestfronten gravede begge sider lange groefte. Soldaterne boede i disse groefte og forsoegte at erobre fjendens stillinger. Imellem de to sider laag ingenmandsland som var ekstremt farligt at krydse."}'::jsonb,
  'mc','short','{"concepts":["skyttegrove","Vestfronten","ingenmandsland","doedvande"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_1',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var ny militaer teknologi i Forste Verdenskrig?","options":["Giftgas, maskingevaerer og fly","Nukleare bomber og missiler","Lasservaaben og droner","Svaerd og hestevogne"],"correct":"Giftgas, maskingevaerer og fly","accepted_answers":["Giftgas, maskingevaerer og fly"],"review_text":"Forste Verdenskrig indfoerte ny og frygtelig teknologi. Giftgas drab og skaadede tusindvis. Maskingevaerer kunne skyde hundredvis af kugler i minuttet. Fly blev brugt til rekognoscering og bomninger. Det goerede krigen endnu mere dodelig."}'::jsonb,
  'mc','short','{"concepts":["giftgas","maskingevaer","fly","ny teknologi","dodelig"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_1',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var nationalisme i Europas sammenaenhaeng foer Forste Verdenskrig?","options":["En staerk tro paa at ens eget folk og nation fortjente magt og selvraadighed","En politisk bevaegelse der oenskede at afskaffe alle graenser i Europa","En religioes bevaegelse der ville forene alle kristne lande","Et okonomisk system baseret paa international handel"],"correct":"En staerk tro paa at ens eget folk og nation fortjente magt og selvraadighed","accepted_answers":["En staerk tro paa at ens eget folk og nation fortjente magt og selvraadighed"],"review_text":"Nationalisme betod at folk folte staerk tilknytning til deres nation. Det styrkede sammenholdet i mange lande. Men det skabte ogsaa fjendskab og konkurrence mellem nationer og bidrog til krigen."}'::jsonb,
  'mc','short','{"concepts":["nationalisme","nation","identitet","rivalisering"],"misconception_type":"scope_confusion","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_1',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad skete der med kvinders rolle under Forste Verdenskrig?","options":["Kvinder overtog mange mandsdomineerede jobs da maend var ved fronten","Kvinders rolle aendrede sig slet ikke under krigen","Kvinder fik forbud mod at arbejde for at beskytte dem","Kvinder kaeempede som soldater paa alle fronter"],"correct":"Kvinder overtog mange mandsdomineerede jobs da maend var ved fronten","accepted_answers":["Kvinder overtog mange mandsdomineerede jobs da maend var ved fronten"],"review_text":"Da maendene blev sendt til fronten manglede fabrikker og gaarde arbejdskraft. Kvinder overtog jobs i vaabenfabrikker, transport og sundhedsvaesen. Det aendrede synet paa hvad kvinder kunne og maatte goere."}'::jsonb,
  'mc','short','{"concepts":["kvinder","roller","arbejde","fabrikker","forandring"],"misconception_type":"overgeneralization","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_1',7,1
);

-- ─── GRADE 7 · BAND 2 (7 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvorfor betod alliancesystemet at en lokal konflikt hurtigt blev en verdenskrig?","options":["Fordi hvert land der gik i krig automatisk trak sine allierede med ind","Fordi alliancerne forbod lande at foere krig mod hinanden","Fordi alle lande i verden var med i den samme alliance","Fordi ingen lande ville hjaelpe hinanden og det skabte kaos"],"correct":"Fordi hvert land der gik i krig automatisk trak sine allierede med ind","accepted_answers":["Fordi hvert land der gik i krig automatisk trak sine allierede med ind"],"review_text":"Oestrig-Ungarn erklaerede krig mod Serbien. Rusland mobiliserede for at hjaelpe Serbien. Germany erklaerede krig mod Rusland. Frankrig og England kom ind. Paa faa uger var en lokal konflikt blevet en europaeisk krig."}'::jsonb,
  'mc','short','{"concepts":["alliancer","kaedereaktion","eskalering","verdenskrig"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_1',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var forholdet mellem mordet paa Franz Ferdinand og Forste Verdenskrigs udbrud?","options":["Mordet var den gnist der udloeste krigen men de egentlige aarsager var dybe spaendinger der havde bygget op i aartier","Mordet var den eneste og direkte aarsag til krigen","Mordet var uvaesentligt og krigen ville have brudt ud uanset hvad","Mordet foraarsakede kun en kortvarig konflikt"],"correct":"Mordet var den gnist der udloeste krigen men de egentlige aarsager var dybe spaendinger der havde bygget op i aartier","accepted_answers":["Mordet var den gnist der udloeste krigen men de egentlige aarsager var dybe spaendinger der havde bygget op i aartier"],"review_text":"Franz Ferdinand var gnisten ikke aarsagen. Nationalisme, rustningskaapplobet, imperialisme og alliancesystemet havde bygget op i aaratier. Mordet var blot den begivenhed der satte det hele i gang."}'::jsonb,
  'mc','short','{"concepts":["Franz Ferdinand","gnist","strukturelle aarsager","MAIN","misconception-en-aarsag"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_1',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvorfor var skyttegravskrigen saa dodelig?","options":["Maskingevaerer dræbte alle der angreb over aabent terrae og skaabte en blodig doedvande","Soldaterne var traeante til at doe og betragtede det ikke som et problem","Skyttegravene var kun til pynt og kampen foregik egentlig andre steder","Teknologien var saa ny at soldaterne ikke vidste hvad de foretog sig"],"correct":"Maskingevaerer dræbte alle der angreb over aabent terrae og skaabte en blodig doedvande","accepted_answers":["Maskingevaerer dræbte alle der angreb over aabent terrae og skaabte en blodig doedvande"],"review_text":"Et enkelt maskingevaer kunne dræbe hundredvis af angribende soldater paa minutter. Forsvar var nu langt stærkere end angreb. Det betod at krigen gik i staa i aaarevis mens begge sider led enorme tab."}'::jsonb,
  'mc','short','{"concepts":["maskingevaer","defensiv teknologi","doedvande","tab"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_1',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var formaaalet med propaganda under Forste Verdenskrig?","options":["At holde befolkningens moral oppe, rekruttere soldater og fremstille fjenden som ond","At formidle objektiv information om krigens foerlob","At koordinere militaere operationer mellem allierede","At kommunikere med soldaterne ved fronten"],"correct":"At holde befolkningens moral oppe, rekruttere soldater og fremstille fjenden som ond","accepted_answers":["At holde befolkningens moral oppe, rekruttere soldater og fremstille fjenden som ond"],"review_text":"Alle krigsfoerende lande brugte propaganda aktivt. Plakater og film fremstillede fjenden som barbarisk. Det var vigtigt for at faa maeand til at melde sig og faa befolkningen til at stoette krigen."}'::jsonb,
  'mc','short','{"concepts":["propaganda","moral","rekruttering","fjendebillede","manipulation"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_1',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvordan ramte Forste Verdenskrig civile bag fronten?","options":["Via rationering af mad, bomninger af byer og sorgen over at miste familiemedlemmer","Civile var fuldt beskyttede og maerkede naesten ikke krigen","Kun civile naer fronten maerkede krigen","Civile tjente penge fordi fabrikker arbejdede haardere"],"correct":"Via rationering af mad, bomninger af byer og sorgen over at miste familiemedlemmer","accepted_answers":["Via rationering af mad, bomninger af byer og sorgen over at miste familiemedlemmer"],"review_text":"Krigen var ikke kun for soldater. Civile maerkede den via madmangel, bombeangreb og den konstante frygt for at miste en far, bror eller son. For mange familier varede sorgen i aartier."}'::jsonb,
  'mc','short','{"concepts":["civile","hjemmefront","rationering","bomninger","misconception-kun-soldater"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_1',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvorfor fortsatte soldaterne med at kaempe i de frygtelige skyttegrove aar efter aar?","options":["Kombination af pligtsfolelse, kammeratskab, frygt for straf og propaganda om aere og heroisme","Fordi de syntes det var spaeaendende","Fordi de ikke vidste hvad der foregik","Fordi de troede krigen ville slutte inden for faa uger"],"correct":"Kombination af pligtsfolelse, kammeratskab, frygt for straf og propaganda om aere og heroisme","accepted_answers":["Kombination af pligtsfolelse, kammeratskab, frygt for straf og propaganda om aere og heroisme"],"review_text":"Soldaterne fortsatte ikke kun af mod. Kammeratskab, pligtsfolelse og frygt for militaer straf holdt dem i graevterne. Desertore risikerede doedsstraffen. Propaganda overbeviste mange om at de kaeempede for et hoejere formaal."}'::jsonb,
  'mc','short','{"concepts":["soldater","kammeratskab","pligtsfolelse","straf","propaganda"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"perspective_shift","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_1',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var rustningskaapplobet foer Forste Verdenskrig?","options":["En konkurrence mellem de store magter om at opbygge storre og staerkere haer og flaader end sine rivaler","En konkurrence om at bygge de bedste jernbaner i Europa","En konkurrence om at erobre flest kolonier i Afrika","En aftale om at dele militaere teknologier med hinanden"],"correct":"En konkurrence mellem de store magter om at opbygge storre og staerkere haer og flaader end sine rivaler","accepted_answers":["En konkurrence mellem de store magter om at opbygge storre og staerkere haer og flaader end sine rivaler"],"review_text":"Isaer England og Germany havde et intenst kaapplob om floestyrke. Begge lande byggede krigsskibe i et rasende tempo. Det skabte frygt og mistillid og goerede krig mere sandsynlig."}'::jsonb,
  'mc','short','{"concepts":["rustningskaapplob","militarisme","flaaade","Germany","England","spaending"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_1',7,2
);

-- ─── GRADE 7 · BAND 3 (7 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved forestillingen om at nationalisme altid var positiv foer Forste Verdenskrig?","options":["Nationalisme skabte ogsaa had til andre folkegrupper og rivalisering der goerede krig mere sandsynlig","Forestillingen er korrekt nationalisme var altid en positiv kraft","Nationalisme forhindrede faktisk krig","Nationalisme eksisterede ikke foer Forste Verdenskrig"],"correct":"Nationalisme skabte ogsaa had til andre folkegrupper og rivalisering der goerede krig mere sandsynlig","accepted_answers":["Nationalisme skabte ogsaa had til andre folkegrupper og rivalisering der goerede krig mere sandsynlig"],"review_text":"Nationalisme kan vaere positiv som stolthed over sin kultur. Men den kan ogsaa vaere farlig naar den betyder at man ser andre nationer som fjender. I perioden foer 1914 skabte nationalisme rivalisering der bidrog til krigen."}'::jsonb,
  'mc','short','{"concepts":["nationalisme","had","rivalisering","misconception-nationalisme-positiv","dobbelttydig"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_1',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved forestillingen om at mordet paa Franz Ferdinand alene foraarsagede Forste Verdenskrig?","options":["Krigen havde fire dybe strukturelle aarsager bygget op i aartier: nationalisme, alliancer, imperialisme og militarisme","Forestillingen er korrekt mordet var den eneste reelle aarsag","Det er forkert fordi krigen ikke havde noget med mordet at goere","Det er forkert fordi det var Rusland der startede krigen"],"correct":"Krigen havde fire dybe strukturelle aarsager bygget op i aartier: nationalisme, alliancer, imperialisme og militarisme","accepted_answers":["Krigen havde fire dybe strukturelle aarsager bygget op i aartier: nationalisme, alliancer, imperialisme og militarisme"],"review_text":"Historikere bruger forkortelsen MAIN: Militarisme, Alliancer, Imperialisme, Nationalisme. Mordet var gnisten der taendte en situation der allerede var ekstremt spraeangfarlig. Fjern mordet og krigen ville sandsynligvis stadig have brudt ud."}'::jsonb,
  'mc','short','{"concepts":["MAIN","enkelt-aarsag","strukturelle aarsager","misconception-en-aarsag"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_1',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved forestillingen om at ny teknologi goerede krigen lettere for soldaterne?","options":["Ny teknologi skaabte de vaerst taenkelige vilkaar og goerede krigen endnu mere dodelig og langvarig","Forestillingen er korrekt teknologien hjalp soldaterne med at vinde hurtigt","Teknologien aendrede intet i praksis","Teknologien skadede primaert civile ikke soldaterne"],"correct":"Ny teknologi skaabte de vaerst taenkelige vilkaar og goerede krigen endnu mere dodelig og langvarig","accepted_answers":["Ny teknologi skaabte de vaerst taenkelige vilkaar og goerede krigen endnu mere dodelig og langvarig"],"review_text":"Giftgas, maskingevaerer og artilleri skabte et af historiens blodigste slagmarker. Teknologien styrkede forsvaret men svaekkede angrebet. Det skaabte en doedvande der kostede millioner af liv og varede fire aar."}'::jsonb,
  'mc','short','{"concepts":["teknologi","doedvande","dodelig","misconception-teknologi-lettere","artilleri"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_1',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var den langsigtede konsekvens af kvinders indsats under Forste Verdenskrig?","options":["Det hjalp med at aendre synet paa kvinder som kompetente deltagere og styrkede stemmeretsbevaeegelsen","Kvinder vendte straks tilbage til de gamle roller og intet aendrede sig","Krigen svaekkede kvinders position i samfundet","Kvindernes roller aendrede sig kun i England"],"correct":"Det hjalp med at aendre synet paa kvinder som kompetente deltagere og styrkede stemmeretsbevaeegelsen","accepted_answers":["Det hjalp med at aendre synet paa kvinder som kompetente deltagere og styrkede stemmeretsbevaeegelsen"],"review_text":"I mange lande fik kvinder stemmeret kort efter krigen: England i 1918, USA i 1920. Krigen havde bevist at kvinder var fuldt kompetente til at drive samfundet. Det var svaert at tage den erkendelse tilbage."}'::jsonb,
  'mc','short','{"concepts":["kvinder","stemmeret","kompetence","langsigtede konsekvenser","forandring"],"misconception_type":"temporal_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_1',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved forestillingen om at Versailles-traktaten loeste Europas problemer?","options":["Traktaten ydmygede Germany saa haardt at den skabte betingelserne Hitler senere udnyttede","Forestillingen er korrekt traktaten skabte varig fred","Traktaten var for mild mod Germany og det var problemet","Traktaten loeste problemerne men kun til 1920"],"correct":"Traktaten ydmygede Germany saa haardt at den skabte betingelserne Hitler senere udnyttede","accepted_answers":["Traktaten ydmygede Germany saa haardt at den skabte betingelserne Hitler senere udnyttede"],"review_text":"Versailles paaloede Germany skylden for hele krigen og kraevede gigantiske erstatninger. Den tyske befolkning oplevede det som en dyb ydmygelse. Det skabte bitter vrede der gav Hitler og nationalsocialismen gunstige betingelser."}'::jsonb,
  'mc','short','{"concepts":["Versailles","ydmygelse","Hitler","konsekvenser","misconception-Versailles-loeste"],"misconception_type":"temporal_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_1',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forbindelsen mellem Forste og Anden Verdenskrig?","options":["Versailles-traktatens haarde betingelser skabte okonomisk nod og national ydmygelse i Germany der banede vejen for Hitler","Der er ingen forbindels de to krige var fuldstaendig uafhaengige","Forbindelsen er at de samme lande kaeampede mod hinanden","Forbindelsen er kun geografisk"],"correct":"Versailles-traktatens haarde betingelser skabte okonomisk nod og national ydmygelse i Germany der banede vejen for Hitler","accepted_answers":["Versailles-traktatens haarde betingelser skabte okonomisk nod og national ydmygelse i Germany der banede vejen for Hitler"],"review_text":"Anden Verdenskrig voksede direkte ud af Forste. Versailles ydmygede Germany. Den Store Depression forvaerrerede krisen. Hitler lovede at gaengaelde ydmygelsen. Uden Versailles er det svaert at forestille sig Hitlers opkomst."}'::jsonb,
  'mc','short','{"concepts":["Versailles","Hitler","WWI-WWII forbindels","misconception-uafhaengige"],"misconception_type":"temporal_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_1',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvordan bidrog imperialisme til Forste Verdenskrigs udbrud?","options":["Konkurrence om kolonier i Afrika og Asien skabte spaendinger og fjendskab mellem de europaeiske stormagter","Imperialisme forhindrede krigen fordi kolonier gav lande rigdom nok til at vaere tilfredse","Imperialisme var ikke relateret til krigen","Kun Frankrig og England rivaliserede om kolonier alle andre var tilfredse"],"correct":"Konkurrence om kolonier i Afrika og Asien skabte spaendinger og fjendskab mellem de europaeiske stormagter","accepted_answers":["Konkurrence om kolonier i Afrika og Asien skabte spaendinger og fjendskab mellem de europaeiske stormagter"],"review_text":"I 1914 kontrollerede de europaeiske magter store dele af verden. Konkurrencen om nye kolonier og ressourcer skabte bitter rivalisering. Det styrkede militarismen og skabte en atmosfaere af gensidig mistillid."}'::jsonb,
  'mc','short','{"concepts":["imperialisme","kolonier","rivalisering","spaendinger","MAIN"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_1',7,3
);

-- ─── GRADE 7 · BAND 4 (5 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betod skyttegravskrigen for den enkelte soldat i hverdagen?","options":["Konstant frygt, livsvilkaar med rotter og mudder og lange perioder af kedsomhed afbrudt af ekstrem vold","Spaeaendende og heroisk krig med mange muligheder for at vise mod","Komfortabel og rolig tjeneste med god mad","Soldaterne kaeampede kun i korte slag og hvilede resten af tiden"],"correct":"Konstant frygt, livsvilkaar med rotter og mudder og lange perioder af kedsomhed afbrudt af ekstrem vold","accepted_answers":["Konstant frygt, livsvilkaar med rotter og mudder og lange perioder af kedsomhed afbrudt af ekstrem vold"],"review_text":"Skyttegravene var fyldt med mudder, rotter og lig. Soldaterne levede i konstant frygt for artilleri og gasangreb. Perioder af kedsomhed blev brudt af frygtelige angrebsbolger. Mange fik psykologiske skader vi i dag kalder PTSD."}'::jsonb,
  'mc','short','{"concepts":["soldaters hverdagsliv","skyttegroven","PTSD","realitet vs heroisme","misconception-krigen-spaeandende"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_1',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved forestillingen om at Germany alene bar ansvaret for Forste Verdenskrig?","options":["Alle de store magter bidrog til optrapningen via militarisme, imperialisme og nationalisme","Forestillingen er korrekt Germany bar fuldt ansvar","Det er forkert fordi kun Oestrig-Ungarn bar ansvaret","Det er forkert fordi ingen lande bar ansvar krigen startede tilfaeldigt"],"correct":"Alle de store magter bidrog til optrapningen via militarisme, imperialisme og nationalisme","accepted_answers":["Alle de store magter bidrog til optrapningen via militarisme, imperialisme og nationalisme"],"review_text":"Versailles-traktatens krigsscyldsklausul var politisk ikke historisk. England og Frankrig konkurrerede aggressivt om kolonier. Rusland mobiliserede hurtigt. Oestrig-Ungarn udnyttede mordet. Alle store magter bidrog til eskalationen."}'::jsonb,
  'mc','short','{"concepts":["krigsansvar","Germany","delt ansvar","misconception-kun-Germany"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_1',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Var Versailles-traktaten for haerd mod Germany?","options":["Mange historikere mener den var for haerd fordi den skabte ydmygelse og okonomisk nod der hjalp Hitler til magten","Traktaten var for mild og det var grunden til at Hitler kom til magten","Traktaten var fuldt retfaerdig og havde ingen negative konsekvenser","Traktaten var irrelevant da Germany ignorerede den"],"correct":"Mange historikere mener den var for haerd fordi den skabte ydmygelse og okonomisk nod der hjalp Hitler til magten","accepted_answers":["Mange historikere mener den var for haerd fordi den skabte ydmygelse og okonomisk nod der hjalp Hitler til magten"],"review_text":"Fra fransk perspektiv var haardhed forstaaeelig: Frankrig var haerget. Men okonomisten Keynes advarede allerede i 1919 om at betingelserne ville skabe en ny krig. Han fik ret i 1939."}'::jsonb,
  'mc','short','{"concepts":["Versailles","retfaerdig fred","Keynes","Hitler","perspektiver"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_1',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad viser det at England, Frankrig og USA alle brugte propaganda under Forste Verdenskrig?","options":["At demokratier er villige til at manipulere borgerne naar de foeler krigen er eksistentiel og at propaganda ikke er forbeholdt diktaturer","At demokratier var ligesaa slemme som diktaturer","At propaganda altid er etisk i krigstid","At propaganda kun eksisterede i Centraleuropa"],"correct":"At demokratier er villige til at manipulere borgerne naar de foeler krigen er eksistentiel og at propaganda ikke er forbeholdt diktaturer","accepted_answers":["At demokratier er villige til at manipulere borgerne naar de foeler krigen er eksistentiel og at propaganda ikke er forbeholdt diktaturer"],"review_text":"England, Frankrig og USA oprettede dedikerede propagandaministerier. Plakater, film og aviser manipulerede den offentlige mening. Det viser at propaganda er et redskab alle stater griber til i krig uanset styreform."}'::jsonb,
  'mc','short','{"concepts":["propaganda","demokrati","diktatur","misconception-propaganda-kun-diktaturer"],"misconception_type":"scope_confusion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_1',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad viser soldaters breve og dagboeger om kloeften mellem officiel propaganda og krigens virkelighed?","options":["At soldaterne oplevede en krig meget forskellig fra den heroiske fremstilling mens censuren forhindrede dem i at fortaelle sandheden hjem","At soldaterne var enige i propagandaens fremstilling","At soldaterne ikke vidste hvad krigen var om","At soldaterne levede komfortabelt og var glade for oplevelsen"],"correct":"At soldaterne oplevede en krig meget forskellig fra den heroiske fremstilling mens censuren forhindrede dem i at fortaelle sandheden hjem","accepted_answers":["At soldaterne oplevede en krig meget forskellig fra den heroiske fremstilling mens censuren forhindrede dem i at fortaelle sandheden hjem"],"review_text":"Soldaternes breve hjem var censurerede. De maatte ikke skrive sandheden. Men dagboeger afslorer den raaende virkelighed: kameraterne der doede, den konstante frygt, meningsloesheden. Der var en enorm kloeft mellem officiel fremstilling og oplevd virkelighed."}'::jsonb,
  'mc','short','{"concepts":["censur","breve","dagboeger","virkelighed vs propaganda","kloeft"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_1',7,4
);;
