
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er kernen i striden mellem marxistisk socialhistorie (Soboul) og den revisionistiske fortolkning (Furet) af den franske revolution — og hvad er styrken ved hver position?","options":["Soboul ser revolutionen som en borgerlig klassekamp mod feudalt aristokrati — Furet afviser klassekampstolkningen og ser den som en politisk-ideologisk katastrofe der skabte totalitarismens skabelon. Styrken ved Soboul er strukturel forklaring, ved Furet er det fokus på ideologiens selvstændige kraft og revolutionens uforudsete konsekvenser","Soboul er en neutral historiker uden ideologisk agenda og Furet er en marxist — de repræsenterer modstridende politiske projekter der begge forvrænger historien","Furet er historiografisk overlegen fordi han fokuserer på kultur og politik mens Soboul er forældet og bør ignoreres","De to fortolkninger er identiske i konklusioner og adskiller sig kun i metodologisk terminologi"],"correct":"Soboul ser revolutionen som en borgerlig klassekamp mod feudalt aristokrati — Furet afviser klassekampstolkningen og ser den som en politisk-ideologisk katastrofe der skabte totalitarismens skabelon. Styrken ved Soboul er strukturel forklaring, ved Furet er det fokus på ideologiens selvstændige kraft og revolutionens uforudsete konsekvenser","accepted_answers":["Soboul ser revolutionen som en borgerlig klassekamp mod feudalt aristokrati — Furet afviser klassekampstolkningen og ser den som en politisk-ideologisk katastrofe der skabte totalitarismens skabelon. Styrken ved Soboul er strukturel forklaring, ved Furet er det fokus på ideologiens selvstændige kraft og revolutionens uforudsete konsekvenser"],"review_text":"Albert Soboul fulgte den marxistiske fortolkning: revolutionen fjernede feudale produktionsforhold og installerede borgerlig kapitalisme — en nødvendig historisk fase. Francois Furet brod afgørende med denne fortolkning i Penser la Revolution francaise (1978) og haevdede at revolutionen ikke var et strukturelt nodvendigt resultat af klassekonflikter men et ideologisk projekt der installerede en ny form for politisk absolutisme. Furets pointe er at Raedselssregimets logik la i selve Rousseaus folkesuverenitetsidé: nar folket er suveraent, er al opposition mod folkeviljen kontrarevolutionaer og dermed kriminel. Ingen enkelt tolkning er komplet men konfrontationen skaerper forstaelsen af revolutionens dobbelte arv."}$$::jsonb,
  'mc','short',$${"concepts":["Soboul","Furet","marxistisk historiografi","revisionisme","klassekamp","totalitarisme"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad viser den atlantiske revolutions-ramme — der sammenligner den amerikanske (1776), franske (1789) og haitiske (1791) revolution — om revolutionernes indbyrdes afhengighed og begraensninger?","options":["At de tre revolutioner var forbundne processer der delte et faelles ideologisk sprog om rettigheder og frihed — men at hvert lands sociale struktur bestemte hvem der faktisk modtog rettighederne. Haitisk frihed var den mest radikale fordi den inkluderede de enslaved, men netop derfor den der modte mest modstand fra de andre revolutionsnationer","At de tre revolutioner var fuldstaendig uafhaengige begivenheder uden indbyrdes forbindelse eller gensidig paavirkning","At den amerikanske revolution var den eneste virkelige revolution og de to andre blot var opstande","At revolutionerne bevisede at oplysningsidealerne var universelt gyldige og umiddelbart overfoorbare til alle samfund"],"correct":"At de tre revolutioner var forbundne processer der delte et faelles ideologisk sprog om rettigheder og frihed — men at hvert lands sociale struktur bestemte hvem der faktisk modtog rettighederne. Haitisk frihed var den mest radikale fordi den inkluderede de enslaved, men netop derfor den der modte mest modstand fra de andre revolutionsnationer","accepted_answers":["At de tre revolutioner var forbundne processer der delte et faelles ideologisk sprog om rettigheder og frihed — men at hvert lands sociale struktur bestemte hvem der faktisk modtog rettighederne. Haitisk frihed var den mest radikale fordi den inkluderede de enslaved, men netop derfor den der modte mest modstand fra de andre revolutionsnationer"],"review_text":"Robert Palmers The Age of the Democratic Revolution (1959) lancerede begrebet atlantisk revolution. Ideologisk forbandt Paine, Lafayette og Toussaint Louverture et faelles oplysningssprog om naturlige rettigheder. Men implementeringen afspejlede sociale strukturer: den amerikanske revolution bevarede slaveriet, den franske revolution ekskluderede kvinder og koloniserede folk, og den haitiske revolution — den eneste succesfulde slaveopstand i historien — blev straffet med international isolation og franske krigsskadeerstatninger paa 150 millioner franc. Rammen viser at universalitetsidealerne var selektive fra starten og at de mest radikale konsekvenser konsekvent modte storst modstand fra de ovrige revolutionsnationer."}$$::jsonb,
  'mc','short',$${"concepts":["atlantisk revolution","Palmer","Haiti","USA","Frankrig","selektiv universalisme"],"misconception_type":"scope_confusion","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Var den franske revolution en borgerlig revolution i marxistisk forstand — og hvad er de staerkeste argumenter for og imod denne fortolkning?","options":["For: aristokratiets politiske magt blev systematisk afmonteret, feudale privilegier afskaffet og ejendomsretten kodificeret — imod: den sociale revolution var ufuldstaendig, arbejderklassen opnaede minimale materielle gevinster, og mange revolutionaere ledere var selv fra adelen. Tolkningsdebatten er fortsat aaben","For: borgerskabet var den eneste klasse der profiterede overhovedet, og enhver anden tolkning er politisk motiveret — imod: ingen relevante faktiske indvendinger","Imod: det var udelukkende en politisk revolution drevet af ideer uden nogen forbindelse til sociale klasser eller materielle interesser","For: alle historikere er enige om at det var en klassisk borgerlig revolution uden meningsfulde indvendinger"],"correct":"For: aristokratiets politiske magt blev systematisk afmonteret, feudale privilegier afskaffet og ejendomsretten kodificeret — imod: den sociale revolution var ufuldstaendig, arbejderklassen opnaede minimale materielle gevinster, og mange revolutionaere ledere var selv fra adelen. Tolkningsdebatten er fortsat aaben","accepted_answers":["For: aristokratiets politiske magt blev systematisk afmonteret, feudale privilegier afskaffet og ejendomsretten kodificeret — imod: den sociale revolution var ufuldstaendig, arbejderklassen opnaede minimale materielle gevinster, og mange revolutionaere ledere var selv fra adelen. Tolkningsdebatten er fortsat aaben"],"review_text":"Den marxistiske borgerlig-revolution-tese har staerke argumenter: afskaffelsen af standssamfundet, nationaliseringen af kirkegods, Civilkoden der beskyttede ejendomsret og kontrakt — alt peger paa at borgerskabets interesser strukturerede revolutionens juridiske output. Men revisionist-historikere som William Doyle og Denis Richet viser at den adel der mistede privilegier og den borgerstand der vandt var socialt overlappende klasser med faelles okonomiske interesser snarere end klart adskilte antagonister. Sansculotterne (byproletariatet) mobiliserede revolutionen radikalt men opnaede minimale langsigtede gevinster. Tolkningsdebatten er uafklaret — og det er netop dens historiografiske vaerdi."}$$::jsonb,
  'mc','short',$${"concepts":["borgerlig revolution","marxistisk tolkning","revisionism","Doyle","sansculotter","klasse"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad adskiller den amerikanske fra den franske revolution i graden af social radikalisme — og hvad forklarer forskellen?","options":["Den franske revolution var langt mere socialt radikal: den afskaffede standssamfundet, konfiskerede aristokratisk og kirkelig ejendom og forsøgte at omstrukturere samfundet fra grunden — den amerikanske revolution primaert aendrede det politiske system uden at anfaegte den eksisterende sociale orden inklusiv slaveriet. Forskellen forklares af de eksisterende sociale strukturers dybde","De to revolutioner var identisk radikale og produkte nojagtig samme sociale resultater","Den amerikanske revolution var mere radikal fordi den skabte det forste moderne demokrati med alle borgerrettigheder for alle borgere","Den franske revolution var mere moderat fordi Frankrig allerede var et mere demokratisk samfund inden revolutionen"],"correct":"Den franske revolution var langt mere socialt radikal: den afskaffede standssamfundet, konfiskerede aristokratisk og kirkelig ejendom og forsøgte at omstrukturere samfundet fra grunden — den amerikanske revolution primaert aendrede det politiske system uden at anfaegte den eksisterende sociale orden inklusiv slaveriet. Forskellen forklares af de eksisterende sociale strukturers dybde","accepted_answers":["Den franske revolution var langt mere socialt radikal: den afskaffede standssamfundet, konfiskerede aristokratisk og kirkelig ejendom og forsøgte at omstrukturere samfundet fra grunden — den amerikanske revolution primaert aendrede det politiske system uden at anfaegte den eksisterende sociale orden inklusiv slaveriet. Forskellen forklares af de eksisterende sociale strukturers dybde"],"review_text":"Den amerikanske revolution var primaert en politisk og fiskal revolution mod britisk kolonistyring — den anfaegtede ikke slaveriet (der faktisk blev beskyttet i forfatningen af 1787), den eksisterende ejendomsfordeling eller den sociale orden i kolonierne. Den franske revolution derimod angreb standssamfundets fundamenter: noblessen mistede privilegier, kirkens godser blev nationaliseret og distribueret, og folkesuvereniteten erstattede monarkisk legitimitet. Forklaringen er de eksisterende institutioners dybde: det franske feodale system kraevede en mere radikal omvaeltning for at fjernes. Den radikale forskel producerede ogsaa den radikale konsekvens: Terroren var i vid udstraekning et produkt af den dybere sociale konflikt."}$$::jsonb,
  'mc','short',$${"concepts":["social radikalisme","amerikansk revolution","fransk revolution","standssamfund","slaveri","komparativ"],"misconception_type":"false_equivalence","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er Edmund Burkes afgørende indvending mod den franske revolution — og hvad er Thomas Paines modsvar — og hvad fortæller debatten om grundlaget for politisk legitimitet?","options":["Burke: politisk orden hviler paa arvede institutioner, tradition og gradvis forandring — ikke paa abstrakte fornuftsbaserede principper. Paine: hvert generations ret til at indrette sit styre er grundlaeggende og traditioners autoritet er tyrannisk fastfrysning af afdodes magt over de levende. Debatten definerer grundkonflikten mellem konservatisme og liberalisme","Burke var irrationalist og Paine var rationalist — debatten er ikke politisk men epistemologisk og handler om videnskab vs tro","Burke er korrekt og Paine er korrekt — de to positioner er kompatible og supplerer hinanden uden modsaetning","Debatten er forældet og relevant kun for 1700-tallets England — den har ingen moderne politisk resonans"],"correct":"Burke: politisk orden hviler paa arvede institutioner, tradition og gradvis forandring — ikke paa abstrakte fornuftsbaserede principper. Paine: hvert generations ret til at indrette sit styre er grundlaeggende og traditioners autoritet er tyrannisk fastfrysning af afdodes magt over de levende. Debatten definerer grundkonflikten mellem konservatisme og liberalisme","accepted_answers":["Burke: politisk orden hviler paa arvede institutioner, tradition og gradvis forandring — ikke paa abstrakte fornuftsbaserede principper. Paine: hvert generations ret til at indrette sit styre er grundlaeggende og traditioners autoritet er tyrannisk fastfrysning af afdodes magt over de levende. Debatten definerer grundkonflikten mellem konservatisme og liberalisme"],"review_text":"Burkes Reflections on the Revolution in France (1790) er det kanoniske konservative manifest. Hans kerne-argument: samfundet er en kontrakt mellem de levende, de dode og de ufodte — man kan ikke nedrive institutioner der er vokset over generationer via abstrakt fornuftsbaseret design. Paines Rights of Man (1791) er det direkte modsvar: afdodes autoritet er tyranni og hvert generation har ret og pligt til at organisere sig efter egne principper. Debatten er filosofisk frugtbar og fortsat relevant: den strukturerer grundkonflikten i al politisk teori om legitimitet. Brexit-debatten om parlamentarisk suveraenitet vs folkelige mandater baerer praecis samme struktur."}$$::jsonb,
  'mc','short',$${"concepts":["Burke","Paine","konservatisme","liberalisme","politisk legitimitet","tradition vs fornuft"],"misconception_type":"scope_confusion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Var Raedselssregimet (La Terreur, 1793-1794) et nodvendigt forsvar for revolutionen eller et forraederi mod dens principper — og hvad er den staerkeste version af begge argumenter?","options":["Forsvar: Frankrig stod over for indre kontrarevolution og ydre invasion fra monarkiske koalitioner — Terroren var et ekstraordinaert nodforanstaltning i en eksistentiel krise. Forraederi: henrettelsen af 16.594 mennesker via summarisk retsforfolgelsskraenkede praecis de rettigheder revolutionen haevdede at beskytte — og Robespierre transformerede folkesuvereniteten til et redskab for politisk udrensning","Forsvar: alle henrettelser under Terroren var juridisk korrekte og proportionelle. Forraederi: Terroren beviser at demokrati altid leder til folkemord","Forsvar: Terroren var nodvendig fordi alle der blev henrettet faktisk var kontrarevolutionaere. Forraederi: revolutionen burde have bevaret kongemagten","Der er ingen meningsfuld etisk diskussion om Terroren — den var blot et politisk instrument og politiske instrumenter kan ikke vurderes etisk"],"correct":"Forsvar: Frankrig stod over for indre kontrarevolution og ydre invasion fra monarkiske koalitioner — Terroren var et ekstraordinaert nodforanstaltning i en eksistentiel krise. Forraederi: henrettelsen af 16.594 mennesker via summarisk retsforfolgelsskraenkede praecis de rettigheder revolutionen haevdede at beskytte — og Robespierre transformerede folkesuvereniteten til et redskab for politisk udrensning","accepted_answers":["Forsvar: Frankrig stod over for indre kontrarevolution og ydre invasion fra monarkiske koalitioner — Terroren var et ekstraordinaert nodforanstaltning i en eksistentiel krise. Forraederi: henrettelsen af 16.594 mennesker via summarisk retsforfolgelsskraenkede praecis de rettigheder revolutionen haevdede at beskytte — og Robespierre transformerede folkesuvereniteten til et redskab for politisk udrensning"],"review_text":"Forsvaret for Terroren har realpolitiske argumenter: den Vendeiske opstand draebte over 200.000, den forste koalitionskrig truede selve statens eksistens og Comite de salut public handlede under genuint existentiel pres. Men kritikken er etisk afgørende: Komiteen afskaffede den ordinaere retsprocedure via Loi de prairial (juni 1794) der fjernede forsvarsretten og definerede kontrarevolution saa bredt at det daekKede enhver mistanke. Robespierre haevdede at dyd og terror var supplerende principper under republikkens forsvar — en logik der forvandler demokratisk legitimitet til en tom formel. Hannah Arendts analyse viser at Rousseaus almenviljebegreb indeholder praecis denne totalitaristiske potentiale."}$$::jsonb,
  'mc','short',$${"concepts":["Terreur","Robespierre","revolutionsvold","folkesuvænitet","Arendt","nødvendighed vs principper"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er den moralfilosofiske distinktion mellem revolutionær vold der er etisk forsvarlig og terrorisme — og hvad er kriteriet der adskiller dem?","options":["Distinktionen hviler paa proportionalitet, diskriminering og politisk formaal: revolutionaer vold rettet mod et undertrykkende regime der spaerrer alle fredelige kanaler kan i teorien opfylde just war-kriterierne — terrorisme kraenker systematisk distinktionsprincippet ved bevidst at maalrette civile. Men graensen er omstridt og afhaenger delvist af perspektiv","Der er ingen meningsfuld distinktion — al politisk vold er terrorisme uanset formaal og kontekst","Revolutionaer vold er altid etisk forsvarlig fordi den sigter mod frihed og retfaerdighed — terrorisme er altid forkert fordi den sigter mod frygt","Distinktionen er rent juridisk og etik er irrelevant for analysen af politisk vold"],"correct":"Distinktionen hviler paa proportionalitet, diskriminering og politisk formaal: revolutionaer vold rettet mod et undertrykkende regime der spaerrer alle fredelige kanaler kan i teorien opfylde just war-kriterierne — terrorisme kraenker systematisk distinktionsprincippet ved bevidst at maalrette civile. Men graensen er omstridt og afhaenger delvist af perspektiv","accepted_answers":["Distinktionen hviler paa proportionalitet, diskriminering og politisk formaal: revolutionaer vold rettet mod et undertrykkende regime der spaerrer alle fredelige kanaler kan i teorien opfylde just war-kriterierne — terrorisme kraenker systematisk distinktionsprincippet ved bevidst at maalrette civile. Men graensen er omstridt og afhaenger delvist af perspektiv"],"review_text":"Just war-teoriens kriterier giver et analytisk greb: retfaerdig aarsag (systematisk undertrykkelse), last resort (fredelige midler udtømt), diskriminering (civile skaanes), proportionalitet (skaden ikke overstiger maalet). Den kanoniske case er Nelson Mandela og ANCs overgang til vabnet kamp i 1961 efter Sharpeville: fredelig modstand var afproeved og blokeret. Michael Walzer viser i Just and Unjust Wars at terrorisme er defineret ved den bevidste maalretning af civile for at skabe politisk frygt — og denne definition er ikke formaalssbestemt men handlingsbestemt. Det ubehagelige svar er at konteksten er afgørende: en mands terrorist er en anden mands frihedskasemper — ikke som relativ moralisme men som en erkendelse af at kriterierne kraever konkret kontekstualisering."}$$::jsonb,
  'mc','short',$${"concepts":["revolutionær vold","terrorisme","just war","diskriminering","proportionalitet","Walzer"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad afslører den haitiske revolutions skaebne — isolation, franske krigsskadeerstatninger og international miskendelse — om de atlantiske revolutionernes raekkevidde?","options":["At de atlantiske revolutionernes universelle rettighedssprog var selektivt fra starten: da enslaved haitianere realiserede oplysningsidealerne fuldt ud, modte de blokade, krig og et krav om 150 millioner franc i kompensation til de franske slaveejerinteresser — frihed gjaldt for hvide europaere, ikke for koloniserede afrikanere","At den haitiske revolutions problemer skyldtes intern politisk ustabilitet og ikke havde noget med international modstand at gore","At USA og Frankrig aktivt stottede den haitiske revolution og at dens vanskeligheder var selvforvoldte","At revolutionens universalisme faktisk var konsistent og alle revolutionsnationer behandlede Haiti ligevaerdigt med hvide nationer"],"correct":"At de atlantiske revolutionernes universelle rettighedssprog var selektivt fra starten: da enslaved haitianere realiserede oplysningsidealerne fuldt ud, modte de blokade, krig og et krav om 150 millioner franc i kompensation til de franske slaveejerinteresser — frihed gjaldt for hvide europaere, ikke for koloniserede afrikanere","accepted_answers":["At de atlantiske revolutionernes universelle rettighedssprog var selektivt fra starten: da enslaved haitianere realiserede oplysningsidealerne fuldt ud, modte de blokade, krig og et krav om 150 millioner franc i kompensation til de franske slaveejerinteresser — frihed gjaldt for hvide europaere, ikke for koloniserede afrikanere"],"review_text":"Haiti erklaerede uafhaengighed 1. januar 1804 som verdens forste sorte republik og den eneste succesfulde slaveopstand i historien. Reaktionen fra Frankrig: anerkendelse kom forst i 1825 og betinget af at Haiti betalte 150 millioner franc i erstatning til de tidligere slavejere. USA anerkendte ikke Haiti diplomatisk for 1862. Gaelden — i nutidsvaerdi estimeret til op mod 21 milliarder dollar — tyngede Haitis okonomi i over et aaarhundrede. Saidiya Hartman og Laurent Dubois viser at den haitiske revolutions isolation er den mest afslorende test paa oplysningsuniversalismens faktiske graenser."}$$::jsonb,
  'mc','short',$${"concepts":["Haiti","slaveopstand","reparationer","oplysningsuniversalisme","Toussaint","selektiv frihed"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Var Napoleon Bonaparte revolutionens fuldbyrdelse eller forraederi — og hvad er kriterierne for denne bedommelse?","options":["Begge paa een gang i forskellig henseende: Napoleon kodificerede revolutionens civile resultater i Napoleonskoden (ejendomsret, retsligestilling, sekulaer stat) men afviklede demokratiet, genetablerede monarkiet i ny form og udbredte revolutionens principper via imperialisme der modsagde dem. Bedommelsen afhaenger af om man prioriterer institutionelle resultater eller demokratisk form","Udelukkende fuldbyrdelse: Napoleon gennemforte revolutionens reformer mere effektivt end noget revolutionaert regime","Udelukkende forraederi: Napoleon modsatte sig alle revolutionens principper og etablerede et system identisk med det absolutte monarki han afloste","Napoleon er et irrelevant sidespor — revolutionen sluttede med Thermidor i 1794"],"correct":"Begge paa een gang i forskellig henseende: Napoleon kodificerede revolutionens civile resultater i Napoleonskoden (ejendomsret, retsligestilling, sekulaer stat) men afviklede demokratiet, genetablerede monarkiet i ny form og udbredte revolutionens principper via imperialisme der modsagde dem. Bedommelsen afhaenger af om man prioriterer institutionelle resultater eller demokratisk form","accepted_answers":["Begge paa een gang i forskellig henseende: Napoleon kodificerede revolutionens civile resultater i Napoleonskoden (ejendomsret, retsligestilling, sekulaer stat) men afviklede demokratiet, genetablerede monarkiet i ny form og udbredte revolutionens principper via imperialisme der modsagde dem. Bedommelsen afhaenger af om man prioriterer institutionelle resultater eller demokratisk form"],"review_text":"Napoleonskoden (1804) er revolutionens varigste institutionelle resultat: ejendomsret, kontrakt, sekulaer civilstandsregistrering, ligestilling for alle mandlige borgere foran loven. Disse koder spredte sig til hele Europa. Men Napoleon genetablerede arveligt kejserdoemme, undertrykte pressen, genindsatte slaveriet i kolonierne (1802) og brugte revolutionens frihedsretorik til at legitimere militaer ekspansion. Bedommelsen afspejler et reelt analytisk valg: revolutioner vurderes efter institutionelle outputs (Napoleon positiv) eller efter demokratisk selvbestemmelse (Napoleon negativ). Begge kriterier er legitime."}$$::jsonb,
  'mc','short',$${"concepts":["Napoleon","Napoleonskoden","revolution","fuldbyrdelse","forræderi","demokrati vs institutioner"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er den fundamentale modsigelse i Erklaering om menneskets og borgerens rettigheder (1789) — og hvad afslorer den om oplysningens universalistiske selvforstaelse?","options":["Erklaering proklamerede universelle naturlige rettigheder men ekskluderede systematisk kvinder, koloniserede folk og fattige der manglede ejendom — universalismen var i praksis partikularisme forklaedt som universalisme. Rettigheder tilkom reelt den hvide, mandlige, ejendomsbesiddende borger","Erklaering var fuldt konsistent og inkluderede alle mennesker fra starten uden nogen eksklusioner","Modsigelsen var rent juridisk — den skyldes tekniske formuleringsfejl og ikke bevidste politiske valg","Eksklusionerne kan ikke vurderes med nutidige standarder da rettigheder var et nyt begreb"],"correct":"Erklaering proklamerede universelle naturlige rettigheder men ekskluderede systematisk kvinder, koloniserede folk og fattige der manglede ejendom — universalismen var i praksis partikularisme forklaedt som universalisme. Rettigheder tilkom reelt den hvide, mandlige, ejendomsbesiddende borger","accepted_answers":["Erklaering proklamerede universelle naturlige rettigheder men ekskluderede systematisk kvinder, koloniserede folk og fattige der manglede ejendom — universalismen var i praksis partikularisme forklaedt som universalisme. Rettigheder tilkom reelt den hvide, mandlige, ejendomsbesiddende borger"],"review_text":"Erklaerningens artikel 1 — Alle mennesker er fodt frie og lige i vaerdighed og rettigheder — er et af historiens mest radikale politiske udsagn og et af de mest selektivt implementerede. Kvinder var politisk ekskluderet — Olympe de Gouges erklaering om kvindens rettigheder (1791) svarede direkte paa dette. Koloniserede folk i Haiti og Guadeloupe var juridisk enslaved. Sansculotterne der bemandede barrikaderne modtog passiv borgerrettighed uden valgret (aktivt borgerskab kraevede ejendom). Joan Scotts og Lynn Hunts forskning viser at den franske revolutions universalisme var konstruktivt tvetydig: den skabte et sprog som ekskluderede grupper sidenhen brugte til at kraeve inklusion — men universalismens graenser var fra starten politisk bestemte."}$$::jsonb,
  'mc','short',$${"concepts":["Erklæringen","universalisme","eksklusioner","kvinder","kolonier","partikularisme"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er Olympe de Gouges historiske og filosofiske bidrag — og hvad afslorer hendes skaebne om revolutionens reelle holdning til kvindelig politisk deltagelse?","options":["De Gouges viste at revolutionens universalistiske logik nodvendigvis inkluderede kvinder — men at det politiske flertal ikke ville acceptere denne konsekvens. Hendes henrettelse (1793) afslorer at Terroren maalrettede kvinder der kraevede politiske rettigheder lige saa meget som kontrarevolutionaere","De Gouges var en marginal figur uden historisk betydning","Hendes henrettelse skyldtes udelukkende hendes politiske stoette til den moderante floj og havde intet med kvindepolitik at gore","De Gouges vandt faktisk sine politiske krav og Den Forste Republik gav kvinder stemmeret i 1793"],"correct":"De Gouges viste at revolutionens universalistiske logik nodvendigvis inkluderede kvinder — men at det politiske flertal ikke ville acceptere denne konsekvens. Hendes henrettelse (1793) afslorer at Terroren maalrettede kvinder der kraevede politiske rettigheder lige saa meget som kontrarevolutionaere","accepted_answers":["De Gouges viste at revolutionens universalistiske logik nodvendigvis inkluderede kvinder — men at det politiske flertal ikke ville acceptere denne konsekvens. Hendes henrettelse (1793) afslorer at Terroren maalrettede kvinder der kraevede politiske rettigheder lige saa meget som kontrarevolutionaere"],"review_text":"Olympe de Gouges Declaration des droits de la femme et de la citoyenne (1791) er et centralt politisk-filosofisk dokument. Hendes argument var stringent: hvis menneskelige rettigheder er naturlige, er de ikke konsbetingede — en kvinde der kan bestiges retfaerdigt af galgen kan bestiges retfaerdigt af talerstolen. Robespierre og Jacobinerne forbod kvindelige politiske klubber i 1793 og de Gouges blev guillotineret samme aar. Den officielle begrundelse var hendes forsvar for Girondins, men selve kriminaliseringen af kvindelig politisk organisering afslorer at revolutionens universalisme aktivt modstoeed sin logiske konsekvens. Frankrig gav forst kvinder stemmeret i 1944."}$$::jsonb,
  'mc','short',$${"concepts":["Olympe de Gouges","kvinderettigheder","universalisme","Terreur","politisk eksklusioner","1791"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Var de latinamerikanske uafhaengighedsbevaegelserri 1810-1820erne reelle folkelige revolutioner eller primaert elitens overtagelse af magten fra spanske koloniale administratorer?","options":["Primaert elitebaserede magtovertagelser: creolsk overklasse onskeede frihed fra spansk handelskontrol men bevarede plantation- og hacienda-systemet, slaveriet og den sociale hierarkiske orden. Urbefolkning og enslaved opnaede minimale gevinster","Fuldt folkeligt befrielsesprojekter: alle sociale klasser deltog og opnaede ligevaerdige gevinster","Reelle folkelige revolutioner drevet af urbefolkningens mobilisering mod baade spansk styre og creolsk overklasse","Ikke revolutioner overhovedet men administrativt ophor af kolonibaaand fra Madrid"],"correct":"Primaert elitebaserede magtovertagelser: creolsk overklasse onskeede frihed fra spansk handelskontrol men bevarede plantation- og hacienda-systemet, slaveriet og den sociale hierarkiske orden. Urbefolkning og enslaved opnaede minimale gevinster","accepted_answers":["Primaert elitebaserede magtovertagelser: creolsk overklasse onskeede frihed fra spansk handelskontrol men bevarede plantation- og hacienda-systemet, slaveriet og den sociale hierarkiske orden. Urbefolkning og enslaved opnaede minimale gevinster"],"review_text":"John Lynch og Tulio Halperin Donghi viser at de latinamerikanske uafhaengighedsbevaegelserr primaert tjente den creolske elite der onskede frihed fra handelsbegransninger og adgang til administrative embeder — ikke fundamental social omstrukturering. Simon Bolivar var slave-ejende plantageejer. Mexicos uafhaengighedskrig begyndte med Hidalgos folkelige opstand men endte med en creolsk konservativ magtovertagelse. Slaveriet fortsatte i Cuba og Brasilien i aartier. Den haitiske revolutions radikale konsekvenser var praecis hvad den latinamerikanske elite fragtede og sogte at undgaa."}$$::jsonb,
  'mc','short',$${"concepts":["latinamerikansk uafhængighed","creolsk elite","Bolívar","sociale gevinster","folkelig revolution","magtovertagelse"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er Jean-Jacques Rousseaus begreb om almenviljen (volonte generale) — og hvorfor indeholder det ifølge kritikere en totalitaer potentiale?","options":["Almenviljen er det sande faelles bedste der transcenderer summen af individuelle interesser og hvis man modstaar den modstaar man sin egentlige frihed — kritikerne ser heri et totalitaert potentiale: den der haevder at repraesentere almenviljen kan legitimere tvang mod oppositionen i frihedens navn","Almenviljen er identisk med flertallets aktuelle onsker og indeholder intet totalitaert potentiale","Rousseaus begreb er et simpelt demokratisk princip der blot beskriver majoritetsdemokrati","Furets kritik er fejlagtig — almenviljebegrebet beskytter individuelle rettigheder mod statslig indgriben"],"correct":"Almenviljen er det sande faelles bedste der transcenderer summen af individuelle interesser og hvis man modstaar den modstaar man sin egentlige frihed — kritikerne ser heri et totalitaert potentiale: den der haevder at repraesentere almenviljen kan legitimere tvang mod oppositionen i frihedens navn","accepted_answers":["Almenviljen er det sande faelles bedste der transcenderer summen af individuelle interesser og hvis man modstaar den modstaar man sin egentlige frihed — kritikerne ser heri et totalitaert potentiale: den der haevder at repraesentere almenviljen kan legitimere tvang mod oppositionen i frihedens navn"],"review_text":"Rousseaus Contrat social (1762) definerer almenviljen som det faelles bedste — ikke summen af individuelle interesser (volonte de tous) men det genuint kollektive. Det ubehagelige element: man kan blive tvunget til at vaere fri. Robespierre brugte praecis denne logik: den der modstoeed revolutionen modstood ikke Robespierre men den suveraene folkevilje — og den revolutionaere terror mod kontrarevolutionaere var dermed selve friheden der forsvarede sig selv. Jacob Talmons The Origins of Totalitarian Democracy (1952) viser at Rousseaus begreb er grundlaget for den totalistiske demokratisme der legitimerer folkeforraeaderikategorier. Analysen er vigtig fordi den viser at demokratisk teori kan producere anti-demokratiske konsekvenser."}$$::jsonb,
  'mc','short',$${"concepts":["Rousseau","almenvilje","totalitarisme","Furet","Talmon","folkesuvænitet"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er de strukturelle betingelser der ifølge Theda Skocpol forklarer revolutionernes succes — og hvad indebærer dette for forstaelsen af revolutionaer agency?","options":["Skocpol viser at succesfulde revolutioner kraever tre samtidige faktorer: statslig svaghed, elite-fraktionering og folkelig mobilisering. Konsekvensen: revolutioner sker ikke blot fordi folk vil dem — de kraever strukturelle muligheder. Dette begraenser revolutionaer agency men udelukker ikke dens rolle","Revolutioner lykkes udelukkende pga. ledernes karisma og ideologiske overbevisning","Skocpol beviser at revolutioner er deterministisk determinerede af strukturer og at individer ingen reel indflydelse har","Revolutioner er tilfaeldige begivenheder uden strukturelle forudsaetninger"],"correct":"Skocpol viser at succesfulde revolutioner kraever tre samtidige faktorer: statslig svaghed, elite-fraktionering og folkelig mobilisering. Konsekvensen: revolutioner sker ikke blot fordi folk vil dem — de kraever strukturelle muligheder. Dette begraenser revolutionaer agency men udelukker ikke dens rolle","accepted_answers":["Skocpol viser at succesfulde revolutioner kraever tre samtidige faktorer: statslig svaghed, elite-fraktionering og folkelig mobilisering. Konsekvensen: revolutioner sker ikke blot fordi folk vil dem — de kraever strukturelle muligheder. Dette begraenser revolutionaer agency men udelukker ikke dens rolle"],"review_text":"Theda Skocpols States and Social Revolutions (1979) er en klassiker i komparativ revolutionsforskning. Hun sammenligner Frankrig 1789, Rusland 1917 og Kina 1949 og finder tre strukturelle forudsaetninger: (1) statslig krise (fiskal sammenbrud, militaere nederlag) (2) elite-splittelse der svaeekker den herskende klasses kohærens og (3) folkelig autonomi der muliggor mobilisering nedefra. Skocpols bidrag er anti-voluntaristisk: revolutioner er ikke resultater af staerk vilje eller korrekt ideologi alene — strukturelle muligheder er nodvendige betingelser. Men strukturerne determinerer ikke agenten: hvem der leder mobiliseringen og hvilken ideologi der sejrer bestemmes stadigvaeek af politisk kamp."}$$::jsonb,
  'mc','short',$${"concepts":["Skocpol","strukturel analyse","revolutionsteori","statssvaghed","elite-fraktionering","agency"],"misconception_type":"causal_inversion","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad adskiller revolutioner der producerer varige demokratier fra dem der ender i autoritarisme — og hvad viser historiske cases om de afgørende faktorer?","options":["De afgørende faktorer er eksistensen af institutionelle garantier, elite-konsensus om spillereglerne og fravaeret af ekstern trussellogik der legitimerer undtagelsestilstand. Den amerikanske revolution skabte institutioner — den franske skabte volatil folkesuvænitet der kraevede staerk haand","Demokratisk resultat afhaenger udelukkende af revolutionaerernes ideologiske renhed","Revolutioner der producerer demokratier er altid dem med voldeligst mobilisering","Alle revolutioner producerer uundgaaeligt autoritarisme og demokratier opstaar kun via gradvis reform"],"correct":"De afgørende faktorer er eksistensen af institutionelle garantier, elite-konsensus om spillereglerne og fravaeret af ekstern trussellogik der legitimerer undtagelsestilstand. Den amerikanske revolution skabte institutioner — den franske skabte volatil folkesuvænitet der kraevede staerk haand","accepted_answers":["De afgørende faktorer er eksistensen af institutionelle garantier, elite-konsensus om spillereglerne og fravaeret af ekstern trussellogik der legitimerer undtagelsestilstand. Den amerikanske revolution skabte institutioner — den franske skabte volatil folkesuvænitet der kraevede staerk haand"],"review_text":"Samuel Huntington og Larry Diamond viser at demokratisk konsolidering efter revolution kraever tre elementer: institutionelle garantier der begraenser flertalstyrannet, elite-konsensus om spillereglers legitimitet og et sikkert nok miljoe til at undtagelsestilstand ikke legitimeres permanent. Den amerikanske revolution skabte Checks and Balances, Bill of Rights og føderal struktur. Den franske revolution skabte folkesuvaenitetsdogme der ikke tog hensyn til mindretalsrettigheder — enhver trussel mod folket kunne legitimere suspension af spillereglerne. Post-Arabisk Foraar: Tunesien konsoliderede demokrati via institutionernes robusthed, Egypten og Libyen faldt tilbage fordi institutionerne ikke eksisterede."}$$::jsonb,
  'mc','short',$${"concepts":["demokratisk konsolidering","institutioner","elite-konsensus","arabisk forår","Huntington","folkesuvænitet"],"misconception_type":"false_equivalence","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er begrebet revolution analytisk — og hvad er den vigtigste distinktion mellem en revolution og et statskup?","options":["Revolutioner involverer fundamental omstrukturering af social og politisk orden med bred folkelig mobilisering — statskup er elitebaserede magtskift der ikke aendrer de underliggende samfundsstrukturer. Distinktionen er vigtig fordi revolution baerer en normativ belastning af legitimitet der kan bruges til at retfaerdiggoere vold","Der er ingen meningsfuld analytisk distinktion — revolution og kup er synonyme begreber","Revolutioner er altid progressive og demokratiske mens statskup altid er reaktionaere","Distinktionen er juridisk: revolution er lovlig og kup er ulovlig"],"correct":"Revolutioner involverer fundamental omstrukturering af social og politisk orden med bred folkelig mobilisering — statskup er elitebaserede magtskift der ikke aendrer de underliggende samfundsstrukturer. Distinktionen er vigtig fordi revolution baerer en normativ belastning af legitimitet der kan bruges til at retfaerdiggoere vold","accepted_answers":["Revolutioner involverer fundamental omstrukturering af social og politisk orden med bred folkelig mobilisering — statskup er elitebaserede magtskift der ikke aendrer de underliggende samfundsstrukturer. Distinktionen er vigtig fordi revolution baerer en normativ belastning af legitimitet der kan bruges til at retfaerdiggoere vold"],"review_text":"Crane Brinton og Charles Tilly viser at revolution som analytisk begreb kraever to elementer: (1) folkelig mobilisering der transcenderer eliternes kontrol og (2) fundamental aendring af den politiske og sociale orden. Et statskup (Pinochet i Chile 1973, de Gaulles magtovertagelse 1958) er et elitebaseret magtskift der ikke nodvendigvis aendrer de strukturelle relationer. Men distinktionen er normativt ladet: revolutionaer legitimitet bruges konsekvent af aktorer der onsker at retfaerdiggoere vold. Den iranske revolution (1979) var genuint folkelig men producerede autoritarisme. Den franske Thermidor (1794) var et kup mod Robespierre men inde i en revolution. Begrebet er analytisk nyttigt men kraever konstant kritisk bevidsthed."}$$::jsonb,
  'mc','short',$${"concepts":["revolution","statskup","folkelig mobilisering","Brinton","Tilly","normativ belastning"],"misconception_type":"false_equivalence","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er den afgørende forskel paa den konstitutionelle arv fra den amerikanske revolution og Napoleonskoden som udtryk for to forskellige opfattelser af individets relation til staten?","options":["Den amerikanske tradition (Bill of Rights, Checks and Balances) fokuserer paa negative rettigheder — hvad staten IKKE maa gore mod individet. Den napoleonske tradition fokuserer paa positiv kodificering af statslig orden og individets rettigheder inden for statens ramme. Denne distinktion strukturerer stadig forskellen mellem angloamerikansk og kontinentaleuropaeisk retsfilosofi","De to systemer er juridisk identiske og adskiller sig kun terminologisk","Napoleonskoden beskytter individet bedre fordi den er mere detaljeret","Den amerikanske tradition er totalitaer og den napoleonske er liberal"],"correct":"Den amerikanske tradition (Bill of Rights, Checks and Balances) fokuserer paa negative rettigheder — hvad staten IKKE maa gore mod individet. Den napoleonske tradition fokuserer paa positiv kodificering af statslig orden og individets rettigheder inden for statens ramme. Denne distinktion strukturerer stadig forskellen mellem angloamerikansk og kontinentaleuropaeisk retsfilosofi","accepted_answers":["Den amerikanske tradition (Bill of Rights, Checks and Balances) fokuserer paa negative rettigheder — hvad staten IKKE maa gore mod individet. Den napoleonske tradition fokuserer paa positiv kodificering af statslig orden og individets rettigheder inden for statens ramme. Denne distinktion strukturerer stadig forskellen mellem angloamerikansk og kontinentaleuropaeisk retsfilosofi"],"review_text":"Isaiah Berlins distinktion mellem negativ frihed (frihed fra indgreb) og positiv frihed (kapacitet til selvrealisering via institutioner) er relevant her. Den amerikanske Bill of Rights (1791) er primaert negativt rettighedsbaseret: Congress shall make no law... Den napoleonske Civilkode er positiv: den definerer hvad rettigheder ER og etablerer statens rolle i at garantere dem. Det angloamerikanske common law-system er case-baseret og evolutions-orienteret. Det kontinentaleuropaeiske civilretssystem er kodifikations-orienteret. Distinktionen har moderne konsekvenser: EU-retsordenen er langt taettere paa den napoleonske model mens britisk og amerikansk ret trakker paa den saedvaneret-baserede tradition."}$$::jsonb,
  'mc','short',$${"concepts":["negative rettigheder","Napoleonskoden","Bill of Rights","Berlin","retsfilosofi","angloamerikansk vs kontinental"],"misconception_type":"false_equivalence","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Er voldelig revolution etisk forsvarlig i et samfund med demokratiske alternativer — og hvad er det staerkeste argument for begge positioner?","options":["Primaert nej med en snaever undtagelse: i et fungerende demokrati er fredelige kanaler tilgaengelige og revolutionaer vold er uforholdsmæssig. Undtagelsen: hvis demokratiet formelt eksisterer men reelt udelukker systematisk underordnede grupper, kan det haevdes at demokratiet er en facade — men bevisbyrden er ekstremt hoj","Ja — politisk vold er altid forsvarlig hvis maalet er frihed og demokrati","Nej — voldelig revolution er aldrig forsvarlig under nogen omstaendigheder","Spoergsmaalet er meningsloest da etik ikke kan anvendes paa politisk vold"],"correct":"Primaert nej med en snaever undtagelse: i et fungerende demokrati er fredelige kanaler tilgaengelige og revolutionaer vold er uforholdsmæssig. Undtagelsen: hvis demokratiet formelt eksisterer men reelt udelukker systematisk underordnede grupper, kan det haevdes at demokratiet er en facade — men bevisbyrden er ekstremt hoj","accepted_answers":["Primaert nej med en snaever undtagelse: i et fungerende demokrati er fredelige kanaler tilgaengelige og revolutionaer vold er uforholdsmæssig. Undtagelsen: hvis demokratiet formelt eksisterer men reelt udelukker systematisk underordnede grupper, kan det haevdes at demokratiet er en facade — men bevisbyrden er ekstremt hoj"],"review_text":"Just war-teoriens last resort-princip er afgørende: vold er kun forsvarlig hvis alle fredelige alternativer er udtømt. I et fungerende demokrati med pressefrihed, stemmeret, civil ulydighed og retssystem er bevisbyrden ekstremt hoj. Men begrebet fungerende demokrati er ikke selvindlysende: Martin Luther King Jr. arbejdede i et formelt demokrati der systematisk ekskluderede afroamerikanere via Jim Crow. Hans valg af civil ulydighed frem for revolution var delvist strategisk og delvist etisk. Demokratiets legitimitet som fredelig kanal-garanti afhaenger af om demokratiet faktisk inkluderer alle."}$$::jsonb,
  'mc','short',$${"concepts":["revolutionær vold","demokratiske alternativer","last resort","civil ulydighed","MLK","demokratisk inklusion"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad viser det arabiske foraar (2010-2012) om forholdet mellem revolution og demokratisk konsolidering — og hvilken lektie trækker det fra den franske revolutions erfaringer?","options":["At revolution er en nodvendig men ikke tilstraekkelig betingelse for demokrati: folkelig mobilisering kan vaelte autoritaere regimer men demokratisk konsolidering kraever institutioner, elite-konsensus og civil-samfundets robusthed. Den franske revolutions lektie er analog: folkesuvaeniteten krav uden institutionelle garantier skaber ustabilitet","At arabisk foraar beviser at demokrati er kulturelt uforeneligt med arabisk og islamisk civilisation","At problemet udelukkende var vestlig indblanding","At revolutioner altid producerer demokrati og at arabisk foraar var en succes"],"correct":"At revolution er en nodvendig men ikke tilstraekkelig betingelse for demokrati: folkelig mobilisering kan vaelte autoritaere regimer men demokratisk konsolidering kraever institutioner, elite-konsensus og civil-samfundets robusthed. Den franske revolutions lektie er analog: folkesuvaeniteten krav uden institutionelle garantier skaber ustabilitet","accepted_answers":["At revolution er en nodvendig men ikke tilstraekkelig betingelse for demokrati: folkelig mobilisering kan vaelte autoritaere regimer men demokratisk konsolidering kraever institutioner, elite-konsensus og civil-samfundets robusthed. Den franske revolutions lektie er analog: folkesuvaeniteten krav uden institutionelle garantier skaber ustabilitet"],"review_text":"Tunesien — det eneste arabisk foraar-land der konsoliderede demokrati — havde relativt staerke fagforeninger (UGTT), en professionaliseret juriststand og en islamistisk bevaegelsse (Ennahda) der valgte institutionelt samarbejde. Egypten og Libyen manglede alle tre. Sammenligningen med 1789 er praecis: den franske revolution havde en mobiliseret befolkning men Ancien Regimes institutioner var nedrevet og erstattet af volontaristiske folkesuvaenitetsorganer uden procedurel modvaegt. Thermidor, Napoleon og Restaurationen var konsekvenserne. Institutionel forudsaetning er ikke en reaktionaer betingelse for revolution — det er analysen af hvad der faar revolutions-energi til at omdannes til stabil demokratisk praksis snarere end autoritaer tilbagevenden."}$$::jsonb,
  'mc','short',$${"concepts":["arabisk forår","demokratisk konsolidering","institutioner","Tunesien","Egypten","lektie fra 1789"],"misconception_type":"causal_inversion","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Kan frihed, lighed og broderskab som den franske revolutions tre grundprincipper faktisk realiseres samtidigt — eller er der strukturel spaending imellem dem?","options":["Strukturel spaending er reel: ubegrænset negativ frihed (liberalisme) kan underminere lighed fordi markedet producerer ulige resultater — og radikal lighed (socialisme) kan begraense frihed via statslig omfordeling. Broderskab kan trues af begge extremer. Moderne demokratier forsoger at balancere alle tre via kompromis","De tre principper er fuldstaendig kompatible og kan altid realiseres simultant","Lighed og frihed er kompatible men broderskab er et irrationelt princip der bor udgaa af demokratisk teori","Friheden er det eneste reelle princip — lighed og broderskab er kollektivistiske illusioner"],"correct":"Strukturel spaending er reel: ubegrænset negativ frihed (liberalisme) kan underminere lighed fordi markedet producerer ulige resultater — og radikal lighed (socialisme) kan begraense frihed via statslig omfordeling. Broderskab kan trues af begge extremer. Moderne demokratier forsoger at balancere alle tre via kompromis","accepted_answers":["Strukturel spaending er reel: ubegrænset negativ frihed (liberalisme) kan underminere lighed fordi markedet producerer ulige resultater — og radikal lighed (socialisme) kan begraense frihed via statslig omfordeling. Broderskab kan trues af begge extremer. Moderne demokratier forsoger at balancere alle tre via kompromis"],"review_text":"Isaiah Berlins Two Concepts of Liberty (1958) er den klassiske analyse af frihed-lighed-spaendingen. Negativ frihed (frihed fra statsindgreb) og positiv frihed (kapacitet til selvrealisering via ressourcer) peger i strukturelt modsat retning: at give alle positiv frihed kraever statsindgreb der begraenser negativ frihed. John Rawls A Theory of Justice (1971) forsoegte en syntese via differensprincippet: ulighed er retfaerdig kun hvis den gavner de mindst priviligerede. Skandinaviske velfaeerdsstater repraesenterer et kompromis, angloamerikansk liberalisme et andet. Den franske revolutions triade er fortsat den politiske filosofis grundproblem — det kraever politisk valg der afspejler vaerdiprioritering."}$$::jsonb,
  'mc','short',$${"concepts":["frihed","lighed","broderskab","Berlin","Rawls","strukturel spænding"],"misconception_type":"false_equivalence","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);
;
