-- Section 107 — Revolutions Democracy Band 5 Sprint
-- Creates the first genuine ceiling layer for advanced grade-9 students in revolutions_democracy.
-- Prior to this migration revolutions_democracy had zero Band 5 questions (50 active across Bands 1-4).
--
-- 20 questions: target_grade=9, difficulty_band=5, domain=revolutions_democracy, is_active=true
-- Uses dollar-quoting ($$) for JSONB values to avoid apostrophe escaping issues.

-- ─── BAND 5 · HISTORIOGRAFI & REVOLUTIONSTEORI (5 questions) ────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er kernen i striden mellem marxistisk socialhistorie (Soboul) og den revisionistiske fortolkning (Furet) af den franske revolution — og hvad er styrken ved hver position?","options":["Soboul ser revolutionen som en borgerlig klassekamp mod feudalt aristokrati — Furet afviser klassekampstolkningen og ser den som en politisk-ideologisk katastrofe der skabte totalitarismens skabelon. Styrken ved Soboul er strukturel forklaring, ved Furet er det fokus på ideologiens selvstændige kraft og revolutionens uforudsete konsekvenser","Soboul er en neutral historiker uden ideologisk agenda og Furet er en marxist — de repræsenterer modstridende politiske projekter der begge forvrænger historien","Furet er historiografisk overlegen fordi han fokuserer på kultur og politik mens Soboul er forældet og bør ignoreres","De to fortolkninger er identiske i konklusioner og adskiller sig kun i metodologisk terminologi"],"correct":"Soboul ser revolutionen som en borgerlig klassekamp mod feudalt aristokrati — Furet afviser klassekampstolkningen og ser den som en politisk-ideologisk katastrofe der skabte totalitarismens skabelon. Styrken ved Soboul er strukturel forklaring, ved Furet er det fokus på ideologiens selvstændige kraft og revolutionens uforudsete konsekvenser","accepted_answers":["Soboul ser revolutionen som en borgerlig klassekamp mod feudalt aristokrati — Furet afviser klassekampstolkningen og ser den som en politisk-ideologisk katastrofe der skabte totalitarismens skabelon. Styrken ved Soboul er strukturel forklaring, ved Furet er det fokus på ideologiens selvstændige kraft og revolutionens uforudsete konsekvenser"],"review_text":"Albert Soboul fulgte den marxistiske fortolkning: revolutionen fjernede feudale produktionsforhold og installerede borgerlig kapitalisme — en nødvendig historisk fase. François Furet brød afgørende med denne fortolkning i Penser la Révolution française (1978) og hævdede at revolutionen ikke var et strukturelt nødvendigt resultat af klassekonflikter men et ideologisk projekt der installerede en ny form for politisk absolutisme. Furets pointe er at Rædselsregimets logik lå i selve Rousseaus folkesuverenitetsidé: når folket er suverænt, er al opposition mod folkeviljen kontrarevolutionær og dermed kriminel. Ingen enkelt tolkning er komplet men konfrontationen skærper forståelsen af revolutionens dobbelte arv."}$$::jsonb,
  'mc','short',$${"concepts":["Soboul","Furet","marxistisk historiografi","revisionisme","klassekamp","totalitarisme"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad viser den atlantiske revolutions-ramme — der sammenligner den amerikanske (1776), franske (1789) og haitiske (1791) revolution — om revolutionernes indbyrdes afhængighed og begrænsninger?","options":["At de tre revolutioner var forbundne processer der delte et fælles ideologisk sprog om rettigheder og frihed — men at hvert lands sociale struktur bestemte hvem der faktisk modtog rettighederne. Haitisk frihed var den mest radikale fordi den inkluderede de enslaved, men netop derfor den der mødte mest modstand fra de andre revolutionsnationer","At de tre revolutioner var fuldstændig uafhængige begivenheder uden indbyrdes forbindelse eller gensidig påvirkning","At den amerikanske revolution var den eneste virkelige revolution og de to andre blot var opstande","At revolutionerne bevisede at oplysningsidealerne var universelt gyldige og umiddelbart overførbare til alle samfund"],"correct":"At de tre revolutioner var forbundne processer der delte et fælles ideologisk sprog om rettigheder og frihed — men at hvert lands sociale struktur bestemte hvem der faktisk modtog rettighederne. Haitisk frihed var den mest radikale fordi den inkluderede de enslaved, men netop derfor den der mødte mest modstand fra de andre revolutionsnationer","accepted_answers":["At de tre revolutioner var forbundne processer der delte et fælles ideologisk sprog om rettigheder og frihed — men at hvert lands sociale struktur bestemte hvem der faktisk modtog rettighederne. Haitisk frihed var den mest radikale fordi den inkluderede de enslaved, men netop derfor den der mødte mest modstand fra de andre revolutionsnationer"],"review_text":"Robert Palmers The Age of the Democratic Revolution (1959) lancerede begrebet atlantisk revolution. Ideologisk forbandt Paine, Lafayette og Toussaint Louverture et fælles oplysningssprog om naturlige rettigheder. Men implementeringen afspejlede sociale strukturer: den amerikanske revolution bevarede slaveriet, den franske revolution ekskluderede kvinder og koloniserede folk, og den haitiske revolution — den eneste succesfulde slaveopstand i historien — blev straffet med international isolation og franske krigsskadeerstatninger på 150 millioner franc. Rammen viser at universalitetsidealerne var selektive fra starten og at de mest radikale konsekvenser konsekvent mødte størst modstand fra de øvrige revolutionsnationer."}$$::jsonb,
  'mc','short',$${"concepts":["atlantisk revolution","Palmer","Haiti","USA","Frankrig","selektiv universalisme"],"misconception_type":"scope_confusion","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Var den franske revolution en borgerlig revolution i marxistisk forstand — og hvad er de stærkeste argumenter for og imod denne fortolkning?","options":["For: aristokratiets politiske magt blev systematisk afmonteret, feudale privilegier afskaffet og ejendomsretten kodificeret — imod: den sociale revolution var ufuldstændig, arbejderklassen opnåede minimale materielle gevinster, og mange revolutionære ledere var selv fra adelen. Tolkningsdebatten er fortsat åben","For: borgerskabet var den eneste klasse der profiterede overhovedet, og enhver anden tolkning er politisk motiveret — imod: ingen relevante faktiske indvendinger","Imod: det var udelukkende en politisk revolution drevet af ideer uden nogen forbindelse til sociale klasser eller materielle interesser","For: alle historikere er enige om at det var en klassisk borgerlig revolution uden meningsfulde indvendinger"],"correct":"For: aristokratiets politiske magt blev systematisk afmonteret, feudale privilegier afskaffet og ejendomsretten kodificeret — imod: den sociale revolution var ufuldstændig, arbejderklassen opnåede minimale materielle gevinster, og mange revolutionære ledere var selv fra adelen. Tolkningsdebatten er fortsat åben","accepted_answers":["For: aristokratiets politiske magt blev systematisk afmonteret, feudale privilegier afskaffet og ejendomsretten kodificeret — imod: den sociale revolution var ufuldstændig, arbejderklassen opnåede minimale materielle gevinster, og mange revolutionære ledere var selv fra adelen. Tolkningsdebatten er fortsat åben"],"review_text":"Den marxistiske borgerlig-revolution-tese har stærke argumenter: afskaffelsen af standssamfundet, nationaliseringen af kirkegods, Civilkoden der beskyttede ejendomsret og kontrakt — alt peger på at borgerskabets interesser strukturerede revolutionens juridiske output. Men revisionist-historikere som William Doyle og Denis Richet viser at den adel der mistede privilegier og den borgerstand der vandt var socialt overlappende klasser med fælles økonomiske interesser snarere end klart adskilte antagonister. Sansculotterne (byproletariatet) mobiliserede revolutionen radikalt men opnåede minimale langsigtede gevinster. Tolkningsdebatten er uafklaret — og det er netop dens historiografiske værdi."}$$::jsonb,
  'mc','short',$${"concepts":["borgerlig revolution","marxistisk tolkning","revisionism","Doyle","sansculotter","klasse"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad adskiller den amerikanske fra den franske revolution i graden af social radikalisme — og hvad forklarer forskellen?","options":["Den franske revolution var langt mere socialt radikal: den afskaffede standssamfundet, konfiskerede aristokratisk og kirkelig ejendom og forsøgte at omstrukturere samfundet fra grunden — den amerikanske revolution primært ændrede det politiske system uden at anfægte den eksisterende sociale orden inklusiv slaveriet. Forskellen forklares af de eksisterende sociale strukturers dybde","De to revolutioner var identisk radikale og produkte nøjagtig samme sociale resultater","Den amerikanske revolution var mere radikal fordi den skabte det første moderne demokrati med alle borgerrettigheder for alle borgere","Den franske revolution var mere moderat fordi Frankrig allerede var et mere demokratisk samfund inden revolutionen"],"correct":"Den franske revolution var langt mere socialt radikal: den afskaffede standssamfundet, konfiskerede aristokratisk og kirkelig ejendom og forsøgte at omstrukturere samfundet fra grunden — den amerikanske revolution primært ændrede det politiske system uden at anfægte den eksisterende sociale orden inklusiv slaveriet. Forskellen forklares af de eksisterende sociale strukturers dybde","accepted_answers":["Den franske revolution var langt mere socialt radikal: den afskaffede standssamfundet, konfiskerede aristokratisk og kirkelig ejendom og forsøgte at omstrukturere samfundet fra grunden — den amerikanske revolution primært ændrede det politiske system uden at anfægte den eksisterende sociale orden inklusiv slaveriet. Forskellen forklares af de eksisterende sociale strukturers dybde"],"review_text":"Den amerikanske revolution var primært en politisk og fiskal revolution mod britisk kolonistyring — den anfægtede ikke slaveriet (der faktisk blev beskyttet i forfatningen af 1787), den eksisterende ejendomsfordeling eller den sociale orden i kolonierne. Den franske revolution derimod angreb standssamfundets fundamenter: noblessen mistede privilegier, kirkens godser blev nationaliseret og distribueret, og folkesuvereniteten erstattede monarkisk legitimitet. Forklaringen er de eksisterende institutioners dybde: det franske féodale system krævede en mere radikal omvæltning for at fjernes. Den radikale forskel producerede også den radikale konsekvens: Terroren var i vid udstrækning et produkt af den dybere sociale konflikt."}$$::jsonb,
  'mc','short',$${"concepts":["social radikalisme","amerikansk revolution","fransk revolution","standssamfund","slaveri","komparativ"],"misconception_type":"false_equivalence","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er Edmund Burkes afgørende indvending mod den franske revolution — og hvad er Thomas Paines modsvar — og hvad fortæller debatten om grundlaget for politisk legitimitet?","options":["Burke: politisk orden hviler på arvede institutioner, tradition og gradvis forandring — ikke på abstrakte fornuftsbaserede principper. Paine: hvert generations ret til at indrette sit styre er grundlæggende og traditioners autoritet er tyrannisk fastfrysning af afdødes magt over de levende. Debatten definerer grundkonflikten mellem konservatisme og liberalisme","Burke var irrationalist og Paine var rationalist — debatten er ikke politisk men epistemologisk og handler om videnskab vs tro","Burke er korrekt og Paine er korrekt — de to positioner er kompatible og supplerer hinanden uden modsætning","Debatten er forældet og relevant kun for 1700-tallets England — den har ingen moderne politisk resonans"],"correct":"Burke: politisk orden hviler på arvede institutioner, tradition og gradvis forandring — ikke på abstrakte fornuftsbaserede principper. Paine: hvert generations ret til at indrette sit styre er grundlæggende og traditioners autoritet er tyrannisk fastfrysning af afdødes magt over de levende. Debatten definerer grundkonflikten mellem konservatisme og liberalisme","accepted_answers":["Burke: politisk orden hviler på arvede institutioner, tradition og gradvis forandring — ikke på abstrakte fornuftsbaserede principper. Paine: hvert generations ret til at indrette sit styre er grundlæggende og traditioners autoritet er tyrannisk fastfrysning af afdødes magt over de levende. Debatten definerer grundkonflikten mellem konservatisme og liberalisme"],"review_text":"Burkes Reflections on the Revolution in France (1790) er det kanoniske konservative manifest. Hans kerne-argument: samfundet er en kontrakt mellem de levende, de døde og de ufødte — man kan ikke nedrive institutioner der er vokset over generationer via abstrakt fornuftsbaseret design. Paines Rights of Man (1791) er det direkte modsvar: afdødes autoritet er tyranni og hvert generation har ret og pligt til at organisere sig efter egne principper. Debatten er filosofisk frugtbar og fortsat relevant: den strukturerer grundkonflikten i al politisk teori om legitimitet. Brexit-debatten om parlamentarisk suverænitet vs folkelige mandater bærer præcis samme struktur."}$$::jsonb,
  'mc','short',$${"concepts":["Burke","Paine","konservatisme","liberalisme","politisk legitimitet","tradition vs fornuft"],"misconception_type":"scope_confusion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

-- ─── BAND 5 · REVOLUTIONSVOLDETS ETIK (4 questions) ─────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Var Rædselsregimet (La Terreur, 1793-1794) et nødvendigt forsvar for revolutionen eller et forræderi mod dens principper — og hvad er den stærkeste version af begge argumenter?","options":["Forsvar: Frankrig stod over for indre kontrarevolution og ydre invasion fra monarkiske koalitioner — Terroren var et ekstraordinært nødforanstaltning i en eksistentiel krise. Forræderi: henrettelsen af 16.594 mennesker via summarisk retsforfølgelse krænkede præcis de rettigheder revolutionen hævdede at beskytte — og Robespierre transformerede folkesuvereniteten til et redskab for politisk udrensning","Forsvar: alle henrettelser under Terroren var juridisk korrekte og proportionelle. Forræderi: Terroren beviser at demokrati altid leder til folkemord","Forsvar: Terroren var nødvendig fordi alle der blev henrettet faktisk var kontrarevolutionære. Forræderi: revolutionen burde have bevaret kongemagten","Der er ingen meningsfuld etisk diskussion om Terroren — den var blot et politisk instrument og politiske instrumenter kan ikke vurderes etisk"],"correct":"Forsvar: Frankrig stod over for indre kontrarevolution og ydre invasion fra monarkiske koalitioner — Terroren var et ekstraordinært nødforanstaltning i en eksistentiel krise. Forræderi: henrettelsen af 16.594 mennesker via summarisk retsforfølgelse krænkede præcis de rettigheder revolutionen hævdede at beskytte — og Robespierre transformerede folkesuvereniteten til et redskab for politisk udrensning","accepted_answers":["Forsvar: Frankrig stod over for indre kontrarevolution og ydre invasion fra monarkiske koalitioner — Terroren var et ekstraordinært nødforanstaltning i en eksistentiel krise. Forræderi: henrettelsen af 16.594 mennesker via summarisk retsforfølgelse krænkede præcis de rettigheder revolutionen hævdede at beskytte — og Robespierre transformerede folkesuvereniteten til et redskab for politisk udrensning"],"review_text":"Forsvaret for Terroren har realpolitiske argumenter: den Vendéiske opstand dræbte over 200.000, den første koalitionskrig truede selve statens eksistens og Comité de salut public handlede under genuint existentiel pres. Men kritikken er etisk afgørende: Komitéen afskaffede den ordinære retsprocedure via Loi de prairial (juni 1794) der fjernede forsvarsretten og definerede kontrarevolution så bredt at det dækkede enhver mistanke. Robespierre hævdede at dyd og terror var supplerende principper under republikkens forsvar — en logik der forvandler demokratisk legitimitet til en tom formel. Hannah Arendts analyse viser at Rousseaus almenviljebegreb indeholder præcis denne totalitaristiske potentiale."}$$::jsonb,
  'mc','short',$${"concepts":["Terreur","Robespierre","revolutionsvold","folkesuvænitet","Arendt","nødvendighed vs principper"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er den moralfilosofiske distinktion mellem revolutionær vold der er etisk forsvarlig og terrorisme — og hvad er kriteriet der adskiller dem?","options":["Distinktionen hviler på proportionalitet, diskriminering og politisk formål: revolutionær vold rettet mod et undertrykkende regime der spærrer alle fredelige kanaler kan i teorien opfylde just war-kriterierne — terrorisme krænker systematisk distinktionsprincippet ved bevidst at målrette civile. Men grænsen er omstridt og afhænger delvist af perspektiv","Der er ingen meningsfuld distinktion — al politisk vold er terrorisme uanset formål og kontekst","Revolutionær vold er altid etisk forsvarlig fordi den sigter mod frihed og retfærdighed — terrorisme er altid forkert fordi den sigter mod frygt","Distinktionen er rent juridisk og etik er irrelevant for analysen af politisk vold"],"correct":"Distinktionen hviler på proportionalitet, diskriminering og politisk formål: revolutionær vold rettet mod et undertrykkende regime der spærrer alle fredelige kanaler kan i teorien opfylde just war-kriterierne — terrorisme krænker systematisk distinktionsprincippet ved bevidst at målrette civile. Men grænsen er omstridt og afhænger delvist af perspektiv","accepted_answers":["Distinktionen hviler på proportionalitet, diskriminering og politisk formål: revolutionær vold rettet mod et undertrykkende regime der spærrer alle fredelige kanaler kan i teorien opfylde just war-kriterierne — terrorisme krænker systematisk distinktionsprincippet ved bevidst at målrette civile. Men grænsen er omstridt og afhænger delvist af perspektiv"],"review_text":"Just war-teoriens kriterier giver et analytisk greb: retfærdig årsag (systematisk undertrykkelse), last resort (fredelige midler udtømt), diskriminering (civile skånes), proportionalitet (skaden ikke overstiger målet). Den kanoniske case er Nelson Mandela og ANC's overgang til væbnet kamp i 1961 efter Sharpeville: fredelig modstand var afprøvet og blokeret. Michael Walzer viser i Just and Unjust Wars at terrorisme er defineret ved den bevidste målretning af civile for at skabe politisk frygt — og denne definition er ikke formålsbestemt men handlingsbestemt. Det ubehagelige svar er at konteksten er afgørende: én mands terrorist er en anden mands frihedskæmper — ikke som relativ moralisme men som en erkendelse af at kriterierne kræver konkret kontekstualisering."}$$::jsonb,
  'mc','short',$${"concepts":["revolutionær vold","terrorisme","just war","diskriminering","proportionalitet","Walzer"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad afslører den haitiske revolutions skæbne — isolation, franske krigsskadeerstatninger og international miskendelse — om de atlantiske revolutionernes rækkevidde?","options":["At de atlantiske revolutionernes universelle rettighedssprog var selektivt fra starten: da enslaved haitianere realiserede oplysningsidealerne fuldt ud, mødte de blokade, krig og et krav om 150 millioner franc i kompensation til de franske slaveejerinteresser — frihed gjaldt for hvide europæere, ikke for koloniserede afrikanere","At den haitiske revolutions problemer skyldtes intern politisk ustabilitet og ikke havde noget med international modstand at gøre","At USA og Frankrig aktivt støttede den haitiske revolution og at dens vanskeligheder var selvforvoldte","At revolutionens universalisme faktisk var konsistent og alle revolutionsnationer behandlede Haiti ligeværdigt med hvide nationer"],"correct":"At de atlantiske revolutionernes universelle rettighedssprog var selektivt fra starten: da enslaved haitianere realiserede oplysningsidealerne fuldt ud, mødte de blokade, krig og et krav om 150 millioner franc i kompensation til de franske slaveejerinteresser — frihed gjaldt for hvide europæere, ikke for koloniserede afrikanere","accepted_answers":["At de atlantiske revolutionernes universelle rettighedssprog var selektivt fra starten: da enslaved haitianere realiserede oplysningsidealerne fuldt ud, mødte de blokade, krig og et krav om 150 millioner franc i kompensation til de franske slaveejerinteresser — frihed gjaldt for hvide europæere, ikke for koloniserede afrikanere"],"review_text":"Haiti erklærede uafhængighed 1. januar 1804 som verdens første sorte republik og den eneste succesfulde slaveopstand i historien. Reaktionen fra det frihedsrevolutionære Frankrig: anerkendelse kom først i 1825 og betinget af at Haiti betalte 150 millioner franc i erstatning til de tidligere slavejere for det tab de led ved at miste deres ejendom. USA anerkendte ikke Haiti diplomatisk før 1862. Gælden — i nutidsværdi estimeret til op mod 21 milliarder dollar — tyngede Haitis økonomi i over et århundrede. Saidiya Hartman og Laurent Dubois viser at den haitiske revolutions isolation er den mest afslørnde test på oplysningsuniversalismens faktiske grænser."}$$::jsonb,
  'mc','short',$${"concepts":["Haiti","slaveopstand","reparationer","oplysningsuniversalisme","Toussaint","selektiv frihed"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Var Napoleon Bonaparte revolutionens fuldbyrdelse eller forræderi — og hvad er kriterierne for denne bedømmelse?","options":["Begge på én gang i forskellig henseende: Napoleon kodificerede revolutionens civile resultater i Napoleonskoden (ejendomsret, retsligestilling, sekulær stat) men afviklede demokratiet, genetablerede monarkiet i ny form og udbredte revolutionens principper via imperialisme der modsagde dem. Bedømmelsen afhænger af om man prioriterer institutionelle resultater eller demokratisk form","Udelukkende fuldbyrdelse: Napoleon gennemførte revolutionens reformer mere effektivt end noget revolutionært regime og er dermed dens sande fuldbyrder","Udelukkende forræderi: Napoleon modsatte sig alle revolutionens principper og etablerede et system identisk med det absolutte monarki han afløste","Napoleon er et irrelevant sidespor — revolutionen sluttede med Thermidor i 1794 og alt derefter er postrevolutionær konsolidering"],"correct":"Begge på én gang i forskellig henseende: Napoleon kodificerede revolutionens civile resultater i Napoleonskoden (ejendomsret, retsligestilling, sekulær stat) men afviklede demokratiet, genetablerede monarkiet i ny form og udbredte revolutionens principper via imperialisme der modsagde dem. Bedømmelsen afhænger af om man prioriterer institutionelle resultater eller demokratisk form","accepted_answers":["Begge på én gang i forskellig henseende: Napoleon kodificerede revolutionens civile resultater i Napoleonskoden (ejendomsret, retsligestilling, sekulær stat) men afviklede demokratiet, genetablerede monarkiet i ny form og udbredte revolutionens principper via imperialisme der modsagde dem. Bedømmelsen afhænger af om man prioriterer institutionelle resultater eller demokratisk form"],"review_text":"Napoleonskoden (1804) er revolutionens varigste institutionelle resultat: ejendomsret, kontrakt, sekulær civilstandsregistrering, ligestilling for alle mandlige borgere foran loven. Disse koder spredte sig til hele Europa. Men Napoleon genetablerede arveligt kejserdømme, undertrykte pressen, genindsatte slaveriet i kolonierne (1802) og brugte revolutionens frihedsretorik til at legitimere militær ekspansion der enslaved snarere end frigav. Bedømmelsen afspejler et reelt analytisk valg: revolutioner vurderes efter institutionelle outputs (Napoleon positiv) eller efter demokratisk selvbestemmelse (Napoleon negativ). Begge kriterier er legitime."}$$::jsonb,
  'mc','short',$${"concepts":["Napoleon","Napoleonskoden","revolution","fuldbyrdelse","forræderi","demokrati vs institutioner"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

-- ─── BAND 5 · DEMOKRATISK TEORI & RETTIGHEDER (4 questions) ─────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er den fundamentale modsigelse i Erklæringen om menneskets og borgerens rettigheder (1789) — og hvad afslører den om oplysningens universalistiske selvforståelse?","options":["Erklæringen proklamerede universelle naturlige rettigheder men ekskluderede systematisk kvinder, koloniserede folk og fattige der manglede ejendom — universalismen var i praksis partikularisme forklædt som universalisme. Det afsløres ved at rettigheder reelt tilkom den hvide, mandlige, ejendomsbesiddende borger","Erklæringen var fuldt konsistent og inkluderede alle mennesker fra starten uden nogen eksklusioner","Modsigelsen var rent juridisk og ikke politisk — den skyldes tekniske formuleringsfejl og ikke bevidste politiske valg","Eksklusionerne var historisk acceptable og kan ikke vurderes med nutidige standarder da rettigheder var et nyt begreb"],"correct":"Erklæringen proklamerede universelle naturlige rettigheder men ekskluderede systematisk kvinder, koloniserede folk og fattige der manglede ejendom — universalismen var i praksis partikularisme forklædt som universalisme. Det afsløres ved at rettigheder reelt tilkom den hvide, mandlige, ejendomsbesiddende borger","accepted_answers":["Erklæringen proklamerede universelle naturlige rettigheder men ekskluderede systematisk kvinder, koloniserede folk og fattige der manglede ejendom — universalismen var i praksis partikularisme forklædt som universalisme. Det afsløres ved at rettigheder reelt tilkom den hvide, mandlige, ejendomsbesiddende borger"],"review_text":"Erklæringens artikel 1 — Alle mennesker er født frie og lige i værdighed og rettigheder — er ét af historiens mest radikale politiske udsagn. Og ét af de mest selektivt implementerede. Kvinder var politisk ekskluderet — Olympe de Gouges Erklæring om kvindens rettigheder (1791) svarede direkte på dette. Koloniserede folk i Haiti og Guadeloupe var juridisk enslaved. Sansculotterne der faktisk bemandede barrikaderne modtog passiv borgerrettighed uden valgret (aktivt borgerskab krævede ejendom). Joan Scotts og Lynn Hunts forskning viser at den franske revolutions universalisme var konstruktivt tvetydig: den skabte et sprog som ekskluderede grupper sidenhen brugte til at kræve inklusion — men universalismens grænser var fra starten politisk bestemte, ikke abstrakt nødvendige."}$$::jsonb,
  'mc','short',$${"concepts":["Erklæringen","universalisme","eksklusioner","kvinder","kolonier","partikularisme"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er Olympe de Gouges historiske og filosofiske bidrag — og hvad afslører hendes skæbne om revolutionens reelle holdning til kvindelig politisk deltagelse?","options":["De Gouges viste at revolutionens universalistiske logik nødvendigvis inkluderede kvinder — men at det politiske flertal ikke ville acceptere denne konsekvens. Hendes henrettelse (1793) afslører at Terroren målrettede kvinder der krævede politiske rettigheder lige så meget som kontrarevolutionære","De Gouges var en marginal figur uden historisk betydning der ikke repræsenterede nogen bredere politisk bevægelse","Hendes henrettelse skyldtes udelukkende hendes politiske støtte til den moderante fløj og havde intet med kvindepolitik at gøre","De Gouges vandt faktisk sine politiske krav og Den Første Republik gav kvinder stemmeret i 1793"],"correct":"De Gouges viste at revolutionens universalistiske logik nødvendigvis inkluderede kvinder — men at det politiske flertal ikke ville acceptere denne konsekvens. Hendes henrettelse (1793) afslører at Terroren målrettede kvinder der krævede politiske rettigheder lige så meget som kontrarevolutionære","accepted_answers":["De Gouges viste at revolutionens universalistiske logik nødvendigvis inkluderede kvinder — men at det politiske flertal ikke ville acceptere denne konsekvens. Hendes henrettelse (1793) afslører at Terroren målrettede kvinder der krævede politiske rettigheder lige så meget som kontrarevolutionære"],"review_text":"Olympe de Gouges Déclaration des droits de la femme et de la citoyenne (1791) er et centralt politisk-filosofisk dokument. Hendes argument var stringent: hvis menneskelige rettigheder er naturlige, er de ikke kønsbetingede — en kvinde der kan bestiges retfærdigt af galgen kan bestiges retfærdigt af talerstolen. Robespierre og Jacobinerne forbød kvindelige politiske klubber i 1793 og de Gouges blev guillotineret samme år. Den officielle begrundelse var hendes forsvar for Girondins, men selve kriminaliseringen af kvindelig politisk organisering afslører at revolutionens universalisme aktivt modstod sin logiske konsekvens. Frankrig gav først kvinder stemmeret i 1944."}$$::jsonb,
  'mc','short',$${"concepts":["Olympe de Gouges","kvinderettigheder","universalisme","Terreur","politisk eksklusioner","1791"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Var de latinamerikanske uafhængighedsbevægelser i 1810-1820erne reelle folkelige revolutioner eller primært elitens overtagelse af magten fra spanske koloniale administratorer?","options":["Primært elitebaserede magtovertagelser: creolsk overklasse ønskede frihed fra spansk handelskontrol og bureaukratisk konkurrence men bevarede plantation- og hacienda-systemet, slaveriet (i de fleste tilfælde) og den sociale hierarkiske orden. Urbefolkning og enslaved deltog men opnåede minimale gevinster","Fuldt folkeligt befrielsesprojekter: alle sociale klasser deltog og opnåede ligeværdige gevinster fra uafhængigheden","Reelle folkelige revolutioner drevet af urbefolkningens og de enslaved peopless mobilisering mod både spansk styre og creolsk overklasse","Ikke revolutioner overhovedet men administrativt ophør af kolonibånd fra Madrid på grund af Napoleons invasion af Spanien"],"correct":"Primært elitebaserede magtovertagelser: creolsk overklasse ønskede frihed fra spansk handelskontrol og bureaukratisk konkurrence men bevarede plantation- og hacienda-systemet, slaveriet (i de fleste tilfælde) og den sociale hierarkiske orden. Urbefolkning og enslaved deltog men opnåede minimale gevinster","accepted_answers":["Primært elitebaserede magtovertagelser: creolsk overklasse ønskede frihed fra spansk handelskontrol og bureaukratisk konkurrence men bevarede plantation- og hacienda-systemet, slaveriet (i de fleste tilfælde) og den sociale hierarkiske orden. Urbefolkning og enslaved deltog men opnåede minimale gevinster"],"review_text":"John Lynch og Tulio Halperin Donghi viser at de latinamerikanske uafhængighedsbevægelser primært tjente den creolske elite (spanske efterkommere født i Latinamerika) der ønskede frihed fra handelsbegrænsninger og adgang til administrative embeder — ikke fundamental social omstrukturering. Simón Bolívar var slave-ejende plantageejer. Mexicos uafhængighedskrig begyndte med Hidalgos folkelige opstand (urbefolkning og mestizer) men endte med en creolsk konservativ magtovertagelse. Slaveriet fortsatte i Cuba og Brasilien i årtier. Den haitiske revolutions radikale konsekvenser var præcis hvad den latinamerikanske elite frygtede og søgte at undgå."}$$::jsonb,
  'mc','short',$${"concepts":["latinamerikansk uafhængighed","creolsk elite","Bolívar","sociale gevinster","folkelig revolution","magtovertagelse"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er Jean-Jacques Rousseaus begreb om almenviljen (volonté générale) — og hvorfor indeholder det ifølge kritikere en totalitær potentiale?","options":["Almenviljen er det sande fælles bedste der transcenderer summen af individuelle interesser og hvis man modstår den, modstår man sin egentlige frihed — kritikerne (bl.a. Furet og Talmon) ser heri et totalitært potentiale: den der hævder at repræsentere almenviljen kan legitimere tvang mod oppositionen i frihedens navn","Almenviljen er identisk med flertallets aktuelle ønsker og indeholder intet totalitært potentiale","Rousseaus begreb er et simpelt demokratisk princip der blot beskriver majoritetsdemokrati og ikke adskiller sig fra Lockes kontraktteori","Furets kritik er fejlagtig — almenviljebegrebet beskytter individuelle rettigheder mod statslig indgriben"],"correct":"Almenviljen er det sande fælles bedste der transcenderer summen af individuelle interesser og hvis man modstår den, modstår man sin egentlige frihed — kritikerne (bl.a. Furet og Talmon) ser heri et totalitært potentiale: den der hævder at repræsentere almenviljen kan legitimere tvang mod oppositionen i frihedens navn","accepted_answers":["Almenviljen er det sande fælles bedste der transcenderer summen af individuelle interesser og hvis man modstår den, modstår man sin egentlige frihed — kritikerne (bl.a. Furet og Talmon) ser heri et totalitært potentiale: den der hævder at repræsentere almenviljen kan legitimere tvang mod oppositionen i frihedens navn"],"review_text":"Rousseaus Contrat social (1762) definerer almenviljen som det fælles bedste — ikke summen af individuelle interesser (volonté de tous) men det genuint kollektive. Det ubehagelige element: man kan blive tvunget til at være fri (on le forcera d'etre libre). Robespierre brugte præcis denne logik: den der modstod revolutionen modstod ikke Robespierre men den suveræne folkevilje — og den revolutionære terror mod kontrarevolutionære var dermed selve friheden der forsvarede sig selv. Jacob Talmons The Origins of Totalitarian Democracy (1952) viser at Rousseaus begreb er grundlaget for den totalistiske demokratisme der legitimerer folkeforræderi-kategorier. Analysen er vigtig fordi den viser at demokratisk teori kan producere anti-demokratiske konsekvenser."}$$::jsonb,
  'mc','short',$${"concepts":["Rousseau","almenvilje","totalitarisme","Furet","Talmon","folkesuvænitet"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

-- ─── BAND 5 · KOMPARATIVE REVOLUTIONER (4 questions) ─────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er de strukturelle betingelser der ifølge Theda Skocpol forklarer revolutionernes succes — og hvad indebærer dette for forståelsen af revolutionær agency?","options":["Skocpol viser at succesfulde revolutioner kræver tre samtidige faktorer: statslig svaghed (militære nederlag eller fiskal krise), elite-fraktionering og folkelig mobilisering. Konsekvensen: revolutioner sker ikke blot fordi folk vil dem — de kræver strukturelle muligheder. Dette begrænser revolutionær agency men udelukker ikke dens rolle","Revolutioner lykkes udelukkende pga. ledernes karisma og ideologiske overbevisning — strukturelle faktorer er irrelevante","Skocpol beviser at revolutioner er deterministisk determinerede af strukturer og at individer ingen reel indflydelse har på historiske omvæltninger","Revolutioner er tilfældige begivenheder uden strukturelle forudsætninger der lader sig identificere"],"correct":"Skocpol viser at succesfulde revolutioner kræver tre samtidige faktorer: statslig svaghed (militære nederlag eller fiskal krise), elite-fraktionering og folkelig mobilisering. Konsekvensen: revolutioner sker ikke blot fordi folk vil dem — de kræver strukturelle muligheder. Dette begrænser revolutionær agency men udelukker ikke dens rolle","accepted_answers":["Skocpol viser at succesfulde revolutioner kræver tre samtidige faktorer: statslig svaghed (militære nederlag eller fiskal krise), elite-fraktionering og folkelig mobilisering. Konsekvensen: revolutioner sker ikke blot fordi folk vil dem — de kræver strukturelle muligheder. Dette begrænser revolutionær agency men udelukker ikke dens rolle"],"review_text":"Theda Skocpols States and Social Revolutions (1979) er en klassiker i komparativ revolutionsforskning. Hun sammenligner Frankrig 1789, Rusland 1917 og Kina 1949 og finder tre strukturelle forudsætninger: (1) statslig krise (fiskal sammenbrud, militære nederlag) (2) elite-splittelse der svækker den herskende klasses kohærens og (3) folkelig autonomi der muliggør mobilisering nedefra. Skocpols bidrag er anti-voluntaristisk: revolutioner er ikke resultater af stærk vilje eller korrekt ideologi alene — strukturelle muligheder er nødvendige betingelser. Men strukturerne determinerer ikke agenten: hvem der leder mobiliseringen, hvilken ideologi der sejrer og hvilken retning revolutionen tager, bestemmes stadigvæk af politisk kamp."}$$::jsonb,
  'mc','short',$${"concepts":["Skocpol","strukturel analyse","revolutionsteori","statssvaghed","elite-fraktionering","agency"],"misconception_type":"causal_inversion","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad adskiller revolutioner der producerer varige demokratier fra dem der ender i autoritarisme — og hvad viser historiske cases om de afgørende faktorer?","options":["De afgørende faktorer er eksistensen af institutionelle garantier (konstitutionelle rettigheder, uafhængige domstole, pressefrihed), elite-konsensus om spillereglerne og fraværet af ekstern trussellogik der legitimerer undtagelsestilstand. Den amerikanske revolution skabte institutioner — den franske skabte volatil folkesuvænitet der krævede stærk hånd","Demokratisk resultat afhænger udelukkende af revolutionærernes ideologiske renhed og moralske kvalitet","Revolutioner der producerer demokratier er altid dem med voldeligst mobilisering — vold er den afgørende faktor for demokratisk konsolidering","Alle revolutioner producerer uundgåeligt autoritarisme og demokratier opstår kun via gradvis reform, aldrig revolution"],"correct":"De afgørende faktorer er eksistensen af institutionelle garantier (konstitutionelle rettigheder, uafhængige domstole, pressefrihed), elite-konsensus om spillereglerne og fraværet af ekstern trussellogik der legitimerer undtagelsestilstand. Den amerikanske revolution skabte institutioner — den franske skabte volatil folkesuvænitet der krævede stærk hånd","accepted_answers":["De afgørende faktorer er eksistensen af institutionelle garantier (konstitutionelle rettigheder, uafhængige domstole, pressefrihed), elite-konsensus om spillereglerne og fraværet af ekstern trussellogik der legitimerer undtagelsestilstand. Den amerikanske revolution skabte institutioner — den franske skabte volatil folkesuvænitet der krævede stærk hånd"],"review_text":"Samuel Huntington og Larry Diamond viser at demokratisk konsolidering efter revolution kræver tre elementer: institutionelle garantier der begrænser flertalstyrannet, elite-konsensus om spillereglers legitimitet og et sikkert nok miljø til at undtagelsestilstand ikke legitimeres permanent. Den amerikanske revolution skabte Checks and Balances, Bill of Rights og føderal struktur — institutioner designet til at begrænse ethvert flertal. Den franske revolution skabte folkesuvænitetsdogme der ikke tog hensyn til mindretalsrettigheder. Konsekvensen var at enhver trussel mod folket kunne legitimere suspension af spillereglerne. Post-Arabisk Forår viser samme mønster: Tunesien konsoliderede demokrati via institutionernes robusthed, Egypten og Libyen faldt tilbage til autoritarisme fordi institutionerne ikke eksisterede."}$$::jsonb,
  'mc','short',$${"concepts":["demokratisk konsolidering","institutioner","elite-konsensus","arabisk forår","Huntington","folkesuvænitet"],"misconception_type":"false_equivalence","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er begrebet revolution analytisk — og hvad er den vigtigste distinktion mellem en revolution og et statskup?","options":["Revolutioner involverer fundamental omstrukturering af social og politisk orden med bred folkelig mobilisering — statskup er elitebaserede magtskift der ikke ændrer de underliggende samfundsstrukturer. Distinktionen er vigtig fordi revolution bærer en normativ belastning af legitimitet der kan bruges til at retfærdiggøre vold","Der er ingen meningsfuld analytisk distinktion — revolution og kup er synonyme begreber med identisk politisk indhold","Revolutioner er altid progressive og demokratiske mens statskup altid er reaktionære og autoritære","Distinktionen er juridisk: revolution er lovlig og kup er ulovlig — ethvert andet kriterium er politisk snarere end analytisk"],"correct":"Revolutioner involverer fundamental omstrukturering af social og politisk orden med bred folkelig mobilisering — statskup er elitebaserede magtskift der ikke ændrer de underliggende samfundsstrukturer. Distinktionen er vigtig fordi revolution bærer en normativ belastning af legitimitet der kan bruges til at retfærdiggøre vold","accepted_answers":["Revolutioner involverer fundamental omstrukturering af social og politisk orden med bred folkelig mobilisering — statskup er elitebaserede magtskift der ikke ændrer de underliggende samfundsstrukturer. Distinktionen er vigtig fordi revolution bærer en normativ belastning af legitimitet der kan bruges til at retfærdiggøre vold"],"review_text":"Crane Brinton og Charles Tilly viser at revolution som analytisk begreb kræver to elementer: (1) folkelig mobilisering der transcenderer eliternes kontrol og (2) fundamental ændring af den politiske og sociale orden. Et statskup (Pinochet i Chile 1973, de Gaulles magtovertagelse 1958) er et elitebaseret magtskift der ikke nødvendigvis ændrer de strukturelle relationer. Men distinktionen er normativt ladet: revolutionær legitimitet bruges konsekvent af aktører der ønsker at retfærdiggøre vold. Den iranske revolution (1979) var genuint folkelig men producerede autoritarisme. Den franske Thermidor (1794) var et kup mod Robespierre men inde i en revolution. Begrebet er analytisk nyttigt men kræver konstant kritisk bevidsthed om dets normative belastning."}$$::jsonb,
  'mc','short',$${"concepts":["revolution","statskup","folkelig mobilisering","Brinton","Tilly","normativ belastning"],"misconception_type":"false_equivalence","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er den afgørende forskel på den konstitutionelle arv fra den amerikanske revolution og Napoleonskoden som udtryk for to forskellige opfattelser af individets relation til staten?","options":["Den amerikanske tradition (Bill of Rights, Checks and Balances) fokuserer på negative rettigheder — hvad staten IKKE må gøre mod individet. Den napoleonske tradition fokuserer på positiv kodificering af statslig orden og individets rettigheder inden for statens ramme. Denne distinktion strukturerer stadig forskellen mellem angloamerikansk og kontinentaleuropæisk retsfilosofi","De to systemer er juridisk identiske og adskiller sig kun terminologisk","Napoleonskoden beskytter individet bedre end den amerikanske tradition fordi den er mere detaljeret","Den amerikanske tradition er totalitær og den napoleonske er liberal — distinktionen er absolut og entydig"],"correct":"Den amerikanske tradition (Bill of Rights, Checks and Balances) fokuserer på negative rettigheder — hvad staten IKKE må gøre mod individet. Den napoleonske tradition fokuserer på positiv kodificering af statslig orden og individets rettigheder inden for statens ramme. Denne distinktion strukturerer stadig forskellen mellem angloamerikansk og kontinentaleuropæisk retsfilosofi","accepted_answers":["Den amerikanske tradition (Bill of Rights, Checks and Balances) fokuserer på negative rettigheder — hvad staten IKKE må gøre mod individet. Den napoleonske tradition fokuserer på positiv kodificering af statslig orden og individets rettigheder inden for statens ramme. Denne distinktion strukturerer stadig forskellen mellem angloamerikansk og kontinentaleuropæisk retsfilosofi"],"review_text":"Isaiah Berlins distinktion mellem negativ frihed (frihed fra indgreb) og positiv frihed (kapacitet til selvrealisering via institutioner) er relevant her. Den amerikanske Bill of Rights (1791) er primært negativt rettighedsbaseret: Congress shall make no law... Den napoleonske Civilkode er positiv: den definerer hvad rettigheder ER og etablerer statens rolle i at garantere dem. Det angloamerikanske common law-system er case-baseret og evolutions-orienteret. Det kontinentaleuropæiske civilretssystem er kodifikations-orienteret. Distinktionen har moderne konsekvenser: EU-retsordenen er langt tættere på den napoleonske model mens britisk og amerikansk ret trækker på den sædvaneret-baserede tradition. Begge systemer har reelle rettighedsgarantier men forskellig filosofisk grundforståelse."}$$::jsonb,
  'mc','short',$${"concepts":["negative rettigheder","Napoleonskoden","Bill of Rights","Berlin","retsfilosofi","angloamerikansk vs kontinental"],"misconception_type":"false_equivalence","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

-- ─── BAND 5 · NUTIDSRELEVANS & DEMOKRATITEORI (3 questions) ─────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Er voldelig revolution etisk forsvarlig i et samfund med demokratiske alternativer — og hvad er det stærkeste argument for begge positioner?","options":["Primært nej med en snæver undtagelse: i et fungerende demokrati er fredelige kanaler tilgængelige og revolutionær vold er uforholdsmæssig og skader dem man hævder at repræsentere. Undtagelsen: hvis demokratiet formelt eksisterer men reelt udelukker systematisk underordnede grupper, kan det hævdes at demokratiet er en facade — men bevisbyrden er ekstremt høj","Ja — politisk vold er altid forsvarlig hvis målet er frihed og demokrati","Nej — voldelig revolution er aldrig forsvarlig under nogen omstændigheder uanset de eksisterende politiske betingelser","Spørgsmålet er meningsløst da etik ikke kan anvendes på politisk vold"],"correct":"Primært nej med en snæver undtagelse: i et fungerende demokrati er fredelige kanaler tilgængelige og revolutionær vold er uforholdsmæssig og skader dem man hævder at repræsentere. Undtagelsen: hvis demokratiet formelt eksisterer men reelt udelukker systematisk underordnede grupper, kan det hævdes at demokratiet er en facade — men bevisbyrden er ekstremt høj","accepted_answers":["Primært nej med en snæver undtagelse: i et fungerende demokrati er fredelige kanaler tilgængelige og revolutionær vold er uforholdsmæssig og skader dem man hævder at repræsentere. Undtagelsen: hvis demokratiet formelt eksisterer men reelt udelukker systematisk underordnede grupper, kan det hævdes at demokratiet er en facade — men bevisbyrden er ekstremt høj"],"review_text":"Just war-teoriens last resort-princip er afgørende: vold er kun forsvarlig hvis alle fredelige alternativer er udtømt. I et fungerende demokrati med pressefrihed, stemmeret, civil ulydighed og retssystem er bevisbyrden for at disse kanaler er utilstrækkelige ekstremt høj. Men begrebet fungerende demokrati er ikke selvindlysende: Martin Luther King Jr. arbejdede i et formelt demokrati der systematisk ekskluderede afroamerikanere via Jim Crow. Hans valg af civil ulydighed frem for revolution var delvist strategisk og delvist etisk. Spørgsmålet afslører at demokratiets legitimitet som fredelig kanal-garanti afhænger af om demokratiet faktisk inkluderer alle. En analyse der ikke tager dette forbehold alvorligt, besvarer ikke spørgsmålet men omgår det."}$$::jsonb,
  'mc','short',$${"concepts":["revolutionær vold","demokratiske alternativer","last resort","civil ulydighed","MLK","demokratisk inklusion"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad viser det arabiske forår (2010-2012) om forholdet mellem revolution og demokratisk konsolidering — og hvilken lektie trækker det fra den franske revolutions erfaringer?","options":["At revolution er en nødvendig men ikke tilstrækkelig betingelse for demokrati: bredt folkelig mobilisering kan vælte autoritære regimer men demokratisk konsolidering kræver institutioner, elite-konsensus og civil-societets robusthed — og disse manglede i de fleste arabiske lande. Den franske revolutions lektie er analog: folkesuvænitetens krav uden institutionelle garantier skaber ustabilitet","At arabisk forår beviser at demokrati er kulturelt uforeneligt med arabisk og islamisk civilisation og aldrig kan fungere i disse samfund","At problemet udelukkende var vestlig indblanding som saboterede folkenes vilje til frihed","At revolutioner altid producerer demokrati og at arabisk forår var en fuldstændig succes på alle parametre"],"correct":"At revolution er en nødvendig men ikke tilstrækkelig betingelse for demokrati: bredt folkelig mobilisering kan vælte autoritære regimer men demokratisk konsolidering kræver institutioner, elite-konsensus og civil-societets robusthed — og disse manglede i de fleste arabiske lande. Den franske revolutions lektie er analog: folkesuvænitetens krav uden institutionelle garantier skaber ustabilitet","accepted_answers":["At revolution er en nødvendig men ikke tilstrækkelig betingelse for demokrati: bredt folkelig mobilisering kan vælte autoritære regimer men demokratisk konsolidering kræver institutioner, elite-konsensus og civil-societets robusthed — og disse manglede i de fleste arabiske lande. Den franske revolutions lektie er analog: folkesuvænitetens krav uden institutionelle garantier skaber ustabilitet"],"review_text":"Tunesien — det eneste arabisk forår-land der konsoliderede demokrati — havde relativt stærke fagforeninger (UGTT), en professionaliseret juriststand og en islamistisk bevægelse (Ennahda) der valgte institutionelt samarbejde. Egypten og Libyen manglede alle tre. Sammenligningen med 1789 er præcis: den franske revolution havde en mobiliseret befolkning men Ancien Régimes institutioner var nedrevet og erstattet af volontaristiske folkesuvænitetsorganer uden procedurel modvægt. Thermidor, Napoleon og Restaurationen var konsekvenserne. Institutionel forudsætning er ikke en reaktionær betingelse for revolution — det er analysen af hvad der får revolutions-energi til at omdannes til stabil demokratisk praksis snarere end autoritær tilbagevenden."}$$::jsonb,
  'mc','short',$${"concepts":["arabisk forår","demokratisk konsolidering","institutioner","Tunesien","Egypten","lektie fra 1789"],"misconception_type":"causal_inversion","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Kan frihed, lighed og broderskab som den franske revolutions tre grundprincipper faktisk realiseres samtidigt — eller er der strukturel spænding imellem dem?","options":["Strukturel spænding er reel: ubegrænset negativ frihed (liberalisme) kan underminere lighed fordi markedet producerer ulige resultater — og radikal lighed (socialisme) kan begrænse frihed via statslig omfordeling. Broderskab (solidaritet) kan trues af begge extremer. Moderne demokratier forsøger at balancere alle tre via kompromis og ingen har løst spændingen fuldstændigt","De tre principper er fuldstændig kompatible og kan altid realiseres simultant uden nogen konflikt","Lighed og frihed er kompatible men broderskab er et irrationelt princip der bør udgå af demokratisk teori","Friheden er det eneste reelle princip — lighed og broderskab er kollektivistiske illusioner der krænker individets rettigheder"],"correct":"Strukturel spænding er reel: ubegrænset negativ frihed (liberalisme) kan underminere lighed fordi markedet producerer ulige resultater — og radikal lighed (socialisme) kan begrænse frihed via statslig omfordeling. Broderskab (solidaritet) kan trues af begge extremer. Moderne demokratier forsøger at balancere alle tre via kompromis og ingen har løst spændingen fuldstændigt","accepted_answers":["Strukturel spænding er reel: ubegrænset negativ frihed (liberalisme) kan underminere lighed fordi markedet producerer ulige resultater — og radikal lighed (socialisme) kan begrænse frihed via statslig omfordeling. Broderskab (solidaritet) kan trues af begge extremer. Moderne demokratier forsøger at balancere alle tre via kompromis og ingen har løst spændingen fuldstændigt"],"review_text":"Isaiah Berlins Two Concepts of Liberty (1958) er den klassiske analyse af frihed-lighed-spændingen. Negativ frihed (frihed fra statsindgreb) og positiv frihed (kapacitet til selvrealisering via ressourcer) peger i strukturelt modsat retning: at give alle positiv frihed kræver statsindgreb der begrænser negativ frihed. John Rawls A Theory of Justice (1971) forsøgte en syntese via differensprincippet: ulighed er retfærdig kun hvis den gavner de mindst privilegerede. Skandinaviske velfærdsstater repræsenterer ét kompromis, angloamerikansk liberalisme et andet. Den franske revolutions triade er fortsat den politiske filosofis grundproblem — ikke fordi det er uløseligt men fordi det kræver politisk valg der afspejler værdiprioritering."}$$::jsonb,
  'mc','short',$${"concepts":["frihed","lighed","broderskab","Berlin","Rawls","strukturel spænding"],"misconception_type":"false_equivalence","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"revolutions_democracy"}$$::jsonb,
  'mc_single',5,'auto',true,'revolutions_democracy',9,5
);
