-- Section 124 — Cold War Band 4 Reinforcement Sprint
-- cold_war had 15 Band 4 questions (5 per grade across G7/G8/G9).
-- Adding 5 questions (2+2+1) to reach 20 B4, matching the B5 count and smoothing
-- the B3(21)→B4(15)→B5(20) shape to B3(21)→B4(20)→B5(20).
--
-- Topics not yet in cold_war B4:
--   G7: proxy wars (MAD og stedfortræderkrige) · rumkapløbet (prestige og teknologi)
--   G8: détente/afspænding · Cubakrisen
--   G9: Sovjet-kollaps (strukturel analyse)
--
-- All questions require cause-and-effect reasoning — not pure recall.
-- All questions: MC format, 4 options, full review_text, is_active=true
-- Uses dollar-quoting ($$) throughout.

-- ─── BAND 4 · DEN KOLDE KRIG — Grade 7 (2 questions) ────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvorfor kæmpede USA og Sovjet gennem andre lande i stedet for direkte mod hinanden under Den Kolde Krig?","options":["Fordi begge supermagter havde atomvåben der ville betyde gensidig ødelæggelse ved direkte krig — proxy-krige i Korea, Vietnam og Afghanistan gav dem mulighed for at konkurrere om global indflydelse uden at risikere atomkrig","Fordi FN-pagten eksplicit forbød USA og Sovjet at erklære krig direkte mod hinanden og begge lande respekterede dette forbud","Fordi USA og Sovjet faktisk holdt af hinanden og bevidst undgik at slå hinandens egne soldater ihjel","Fordi begge lande var for fattige til at finansiere direkte militæroperationer og derfor valgte den billigere proxy-løsning"],"correct":"Fordi begge supermagter havde atomvåben der ville betyde gensidig ødelæggelse ved direkte krig — proxy-krige i Korea, Vietnam og Afghanistan gav dem mulighed for at konkurrere om global indflydelse uden at risikere atomkrig","accepted_answers":["Fordi begge supermagter havde atomvåben der ville betyde gensidig ødelæggelse ved direkte krig — proxy-krige i Korea, Vietnam og Afghanistan gav dem mulighed for at konkurrere om global indflydelse uden at risikere atomkrig"],"review_text":"Den gensidigt sikrede ødelæggelse (MAD — Mutually Assured Destruction) betød at en direkte militær konfrontation ville resultere i atomkrig og civilisationens undergang. Begge sider vidste det og byggede bevidst deres strategi på denne erkendelse. Proxy-krige — konflikter hvor supermagterne støttede modstående sider med våben, rådgivere og penge — gav dem mulighed for at konkurrere om global indflydelse uden at krydse den fatale tærskel. Korea (1950-53) kostede over 36.000 amerikanske liv; Vietnam (1955-75) over 58.000 og millioner af vietnamesere; Sovjet i Afghanistan (1979-89) ca. 15.000 sovjetiske soldater. Millioner af mennesker i de berørte lande betalte prisen for supermagternes strategiske kalkule."}$$::jsonb,
  'mc','short',$${"concepts":["proxy-krige","MAD","atomafskrækkelse","Korea","Vietnam","Afghanistan"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"analytical_challenge","domain":"cold_war"}$$::jsonb,
  'mc_single',4,'auto',true,'cold_war',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvorfor brugte USA og Sovjet enorme ressourcer på et kapløb om at nå rummet i 1950'erne og 1960'erne?","options":["Rumkapløbet handlede mere om prestige og teknologisk overlegenhed end selve rummet — at sætte en satellit i kredsløb eller lande på Månen signalerede over for hele verden at ens system var stærkere og dermed en bedre samfundsmodel","Rumkapløbet opstod fordi begge lande oprigtigt troede at den der nåede rummet først ville finde ressourcer der kunne løse deres nationale økonomiproblemer","Rumkapløbet var rent videnskabeligt og ingen af siderne tillagde det politisk eller militær strategisk betydning","USA og Sovjet samarbejdede i hemmelighed om rumforskning fordi begge anerkendte at international videnskab var vigtigere end ideologisk konkurrence"],"correct":"Rumkapløbet handlede mere om prestige og teknologisk overlegenhed end selve rummet — at sætte en satellit i kredsløb eller lande på Månen signalerede over for hele verden at ens system var stærkere og dermed en bedre samfundsmodel","accepted_answers":["Rumkapløbet handlede mere om prestige og teknologisk overlegenhed end selve rummet — at sætte en satellit i kredsløb eller lande på Månen signalerede over for hele verden at ens system var stærkere og dermed en bedre samfundsmodel"],"review_text":"Sputnik 1 (oktober 1957) sendte chokbølger gennem USA. Sovjet hatte slået dem til den første satellit i kredsløb. Det reelle budskab var militært: raketter kraftige nok til at sende en satellit i kredsløb kunne også bære atomsprængtlader til amerikanske byer. Rumkapløbet blev et globalt teater for den ideologiske konkurrence — for de ikke-allierede nationer i Afrika, Asien og Latinamerika der skulle vælge side signalerede rumresultater teknologisk og dermed systemisk overlegenhed. Gagarins rumflyvning (april 1961) var Sovjet-propaganda-triumf; Apollos månelanding (juli 1969) vendte prestige-regnskabet. Kennedy sagde direkte: vi gør det ikke fordi det er let men fordi det viser hvem vi er."}$$::jsonb,
  'mc','short',$${"concepts":["rumkapløbet","Sputnik","Apollo","prestige","teknologisk overlegenhed","ideologisk konkurrence"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"analytical_challenge","domain":"cold_war"}$$::jsonb,
  'mc_single',4,'auto',true,'cold_war',7,4
);

-- ─── BAND 4 · DEN KOLDE KRIG — Grade 8 (2 questions) ────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad forklarer at USA og Sovjet søgte afspænding (détente) i begyndelsen af 1970'erne trods årtiers dyb mistillid?","options":["Begge sider erkendte at rustningskappestrid og proxy-krige var ekstremt dyre — USA var udmattet af Vietnam, Sovjet ønskede vestlig teknologi og handel, og Nixon/Kissinger så strategisk fordel i at splitte den kommunistiske verden ved at nærme sig Kina","Afspændingen opstod fordi begge sider nu troede at Den Kolde Krig var afsluttet og der ikke var noget tilbage at kæmpe om","Nixon og Brezhnev var personlige venner og valgte at stoppe konflikten på grundlag af gensidig sympati og personlig tillid","FN pålagde begge sider forhandlinger under trussel om internationale sanktioner der ville have skadet begge landes økonomi"],"correct":"Begge sider erkendte at rustningskappestrid og proxy-krige var ekstremt dyre — USA var udmattet af Vietnam, Sovjet ønskede vestlig teknologi og handel, og Nixon/Kissinger så strategisk fordel i at splitte den kommunistiske verden ved at nærme sig Kina","accepted_answers":["Begge sider erkendte at rustningskappestrid og proxy-krige var ekstremt dyre — USA var udmattet af Vietnam, Sovjet ønskede vestlig teknologi og handel, og Nixon/Kissinger så strategisk fordel i at splitte den kommunistiske verden ved at nærme sig Kina"],"review_text":"Détente (fransk for afspænding) i 1969-1979 var ikke en opgiven af Den Kolde Krig men en strategisk tilpasning. USA: Vietnam kostede 58.000 liv og underminerede hjemlig opbakning. Nixon og Kissinger så at Kina og Sovjet var blevet rivaler og brugte Nixons Kina-besøg (1972) til at lægge pres på Sovjet. Sovjet: ønskede vestlig korntilførsel (den planlagte økonomi producerede ikke nok), teknologisk adgang og anerkendelse af Østeuropas status quo. SALT I-aftalen (1972) begrænsede for første gang strategiske atomvåben. Helsinki-aftalerne (1975) cementerede grænser. Men détente kollapsede da Sovjet invaderede Afghanistan i december 1979 — Jimmy Carter trak USA's OL-deltagelse tilbage og øgede forsvarsudgifterne."}$$::jsonb,
  'mc','short',$${"concepts":["détente","afspænding","Nixon","Kissinger","SALT I","Vietnam"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"analytical_challenge","domain":"cold_war"}$$::jsonb,
  'mc_single',4,'auto',true,'cold_war',8,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad afslørede Cubakrisen i 1962 om risikoen for atomkrig under Den Kolde Krig?","options":["At verden i 13 dage var på randen af atomkrig — ikke udelukkende fordi supermagterne planlagde det men fordi enkeltpersoners beslutninger under ekstremt pres og fejllæsninger af signaler næsten udløste en katastrofe","At USA altid ville vinde en militær konfrontation med Sovjet fordi USA's atomarsenal var markant større og mere avanceret","At Cubakrisen beviste at atomvåben ikke var reelt farlige da ingen alligevel turde bruge dem og freden dermed var garanteret","At krisen udelukkende skyldtes Cuba og Castros egensindige beslutning om at invitere sovjetiske missiler mod begge supermagters ønske"],"correct":"At verden i 13 dage var på randen af atomkrig — ikke udelukkende fordi supermagterne planlagde det men fordi enkeltpersoners beslutninger under ekstremt pres og fejllæsninger af signaler næsten udløste en katastrofe","accepted_answers":["At verden i 13 dage var på randen af atomkrig — ikke udelukkende fordi supermagterne planlagde det men fordi enkeltpersoners beslutninger under ekstremt pres og fejllæsninger af signaler næsten udløste en katastrofe"],"review_text":"Oktober 1962: USA opdagede at Sovjet opstillede atomraketter på Cuba 150 km fra Florida. 13 dage af hemmelige forhandlinger og offentlig konfrontation. Hvad der ikke var offentligt kendt dengang: den sovjetiske ubåd B-59 var allerede udsat for amerikanske dybvandsbomber og kaptajnen var klar til at affyre en atomtorpedo. Kun den tredje officer Vasili Arkhipovs veto forhindrede det — én persons beslutning i panik adskilte verden fra katastrofe. Kennedy og Khrusjtjov løste krisen diplomatisk: Sovjet fjernede raketterne, USA lovede ikke at invadere Cuba og fjernede i hemmelighed egne missiler fra Tyrkiet. Krisen viste at atomkrig ikke kun kræver politikeres bevidste valg — fejltagelser, tekniske svigt og individuelle beslutninger under pres er reelle risici."}$$::jsonb,
  'mc','short',$${"concepts":["Cubakrisen","atomkrig","Kennedy","Khrusjtjov","Arkhipov","eskalationsrisiko"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"analytical_challenge","domain":"cold_war"}$$::jsonb,
  'mc_single',4,'auto',true,'cold_war',8,4
);

-- ─── BAND 4 · DEN KOLDE KRIG — Grade 9 (1 question) ─────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad forklarer bedst at Sovjetunionen kollapsede i 1991 frem for at fortsætte?","options":["Multi-kausal: planøkonomien var strukturelt ineffektiv og teknologisk stagneret, Gorbatjovs glasnost og perestrojka løsnede kontrol uden at løse problemerne, og undertrykte nationaliteter i Baltikum, Ukraine og Kaukasus benyttede åbenheden til at kræve uafhængighed","Sovjet kollapsede udelukkende fordi Reagans massive oprustning tvang Sovjet til et kapløb de ikke kunne finansiere — én præsident vandt Den Kolde Krig","Gorbatjov planlagde bevidst og systematisk Sovjet-Unionens opløsning fra begyndelsen af sin ledelse i 1985","Sovjet kollapsede primært fordi den ortodokse kirke genvandt befolkningens loyalitet og millioner af borgere vendte ryggen til den kommunistiske ideologi"],"correct":"Multi-kausal: planøkonomien var strukturelt ineffektiv og teknologisk stagneret, Gorbatjovs glasnost og perestrojka løsnede kontrol uden at løse problemerne, og undertrykte nationaliteter i Baltikum, Ukraine og Kaukasus benyttede åbenheden til at kræve uafhængighed","accepted_answers":["Multi-kausal: planøkonomien var strukturelt ineffektiv og teknologisk stagneret, Gorbatjovs glasnost og perestrojka løsnede kontrol uden at løse problemerne, og undertrykte nationaliteter i Baltikum, Ukraine og Kaukasus benyttede åbenheden til at kræve uafhængighed"],"review_text":"Sovjet-kollapsens årsager er et centralt historiografisk debatemne. Strukturelt: planøkonomien skabte aldrig forbrugsvarernes overflod som Vesten tilbød og teknologisk stagnation blev synliggjort af Tsjernobyl-katastrofen (1986). Gorbatjovs glasnost (åbenhed fra 1986) og perestrojka (omstrukturering) var designet til at modernisere og redde systemet — ikke nedlægge det. Men glasnost muliggjorde fri presse der afslørede systemets fejl og korruption. De baltiske stater (Estland, Letland, Litauen) erklærede uafhængighed i 1990; Ukraine og Georgien fulgte. Reagans oprustning (Stjernekrigsprogrammet) bidrog til det økonomiske pres men historikere som Archie Brown og Stephen Kotkin understreger at interne strukturelle faktorer var afgørende — tilskrivningen til Reagan er en politisk myte snarere end historisk analyse."}$$::jsonb,
  'mc','short',$${"concepts":["Sovjet-kollaps","Gorbatjov","glasnost","perestrojka","planøkonomi","nationaliteter"],"misconception_type":"causal_inversion","cognitive_skill":"synthesis","difficulty_type":"multi_causal","insight_type":"perspective_shift","challenge_role":"analytical_challenge","domain":"cold_war"}$$::jsonb,
  'mc_single',4,'auto',true,'cold_war',9,4
);
