-- Section 147A — Democracy & Power Grade 7 Band Expansion
-- democracy_power, target_grade=7, is_active=true
-- Distribution: B1(2) + B2(4) + B3(6) + B4(5) + B5(3) = 20 questions
-- Topics: ministers, dictatorship, separation of powers, referenda, EU, opposition,
--         propaganda, human rights, citizen proposals, polarisation, welfare state,
--         disinformation, corruption, crisis governance, populism, education & democracy,
--         media ownership, inequality, democratic self-destruction, digital platforms
-- Before: B1=13 B2=14 B3=12 B4=5  B5=0  → 44 active
-- After:  B1=15 B2=18 B3=18 B4=10 B5=3  → 64 active
-- Uses dollar-quoting ($$) throughout.

-- ─── BAND 1 (2 questions) ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er en ministers vigtigste opgave i Danmarks regering?","options":["At lede et ministerium og gennemføre politikken på et bestemt område på vegne af regeringen","At holde tale i Folketing et og stemme for alle love","At repræsentere Danmark ved internationale sportsbegivenheder","At kontrollere om domstolene dømmer rigtigt"],"correct":"At lede et ministerium og gennemføre politikken på et bestemt område på vegne af regeringen","accepted_answers":["At lede et ministerium og gennemføre politikken på et bestemt område på vegne af regeringen"],"review_text":"En minister leder et ministerium — fx Undervisningsministeriet eller Sundhedsministeriet. Ministeren er ansvarlig for at gennemføre regeringens politik på sit område og kan stilles til ansvar i Folketing et. Statsministeren er regeringsleder og koordinerer de øvrige ministre. Danmark har typisk 15-20 ministre. Det er ikke ministeren der laver lovene — det er Folketing et. Men ministeren udmønter og administrerer lovene i praksis."}$$::jsonb,
  'mc','short',$${"concepts":["minister","ministerium","udøvende magt","regeringen"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"recognition","insight_type":"concept_clarification","challenge_role":"entry_level","domain":"democracy_power"}$$::jsonb,
  'mc_single',1,'auto',true,'democracy_power',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er det vigtigste kendetegn ved et ikke-demokratisk styre?","options":["Borgerne kan ikke afsætte landets leder gennem frie og fair valg","Der er ingen skriftlige love i landet","Alle borgere er fattige og ingen har ejendomsret","Landet har ingen hær eller politi"],"correct":"Borgerne kan ikke afsætte landets leder gennem frie og fair valg","accepted_answers":["Borgerne kan ikke afsætte landets leder gennem frie og fair valg"],"review_text":"Det fundamentale kendetegn ved demokrati er ikke blot at der er valg — det er at borgerne reelt kan afsætte magthaverne. I et diktatur eller autoritært styre kan lederen forblive ved magten uden borgernes accept. Nogle diktaturer afholder endda valg — men de er ikke frie og fair. Det er muligheden for at stemme nogen ud der adskiller demokratiet fra alle andre styreformer."}$$::jsonb,
  'mc','short',$${"concepts":["diktatur","demokrati","valgret","magtskifte","afsætning"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"recognition","insight_type":"concept_clarification","challenge_role":"entry_level","domain":"democracy_power"}$$::jsonb,
  'mc_single',1,'auto',true,'democracy_power',7,1
);

-- ─── BAND 2 (4 questions) ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er 'magtens tredeling' og hvad er dens formål?","options":["At opdele statens magt i tre uafhængige grene — lovgivende, udøvende og dømmende — for at forhindre at én part får al magt","At dele skatteindtægterne ligeligt mellem landets tre regioner","At sikre at de tre største partier i Folketing et altid er enige","At give tre ministerier ansvaret for at kontrollere statsbudgettet"],"correct":"At opdele statens magt i tre uafhængige grene — lovgivende, udøvende og dømmende — for at forhindre at én part får al magt","accepted_answers":["At opdele statens magt i tre uafhængige grene — lovgivende, udøvende og dømmende — for at forhindre at én part får al magt"],"review_text":"Magtens tredeling er et grundprincip i demokratiet. Folketing et (lovgivende magt) vedtager love. Regeringen (udøvende magt) gennemfører dem. Domstolene (dømmende magt) fortolker dem og sikrer at ingen bryder loven — heller ikke regeringen. Adskillelsen forhindrer at én person eller gruppe kontrollerer alt og beskytter borgernes rettigheder. I Danmark er adskillelsen reel men ikke absolut — regeringen sidder fordi den har Folketing ets tillid, og domstolene er en vigtig selvstændig modsats."}$$::jsonb,
  'mc','short',$${"concepts":["magtens tredeling","lovgivende magt","udøvende magt","dømmende magt","magtadskillelse"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"concept_clarification","challenge_role":"reinforcement","domain":"democracy_power"}$$::jsonb,
  'mc_single',2,'auto',true,'democracy_power',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er en folkeafstemning og hvornår bruges den i Danmark?","options":["En afstemning hvor alle borgere direkte stemmer om et bestemt spørgsmål — bruges bl.a. ved grundlovsændringer og ved afgivelse af suverænitet til EU","Den normale valghandling ved Folketing svalgene der afholdes hvert fjerde år","En afstemning kun for politikere i Folketing et om vigtige lovforslag","En meningsmåling foretaget af DR der bruges som vejledning for politikerne"],"correct":"En afstemning hvor alle borgere direkte stemmer om et bestemt spørgsmål — bruges bl.a. ved grundlovsændringer og ved afgivelse af suverænitet til EU","accepted_answers":["En afstemning hvor alle borgere direkte stemmer om et bestemt spørgsmål — bruges bl.a. ved grundlovsændringer og ved afgivelse af suverænitet til EU"],"review_text":"En folkeafstemning giver alle borgere direkte indflydelse på en konkret beslutning. I Danmark er det obligatorisk med folkeafstemning ved grundlovsændringer. Det bruges også ved vigtige EU-spørgsmål — fx stemte Danmark nej til Maastricht-traktaten i 1992 og ja til Edinburgh-aftalen i 1993. Folkeafstemninger er et element af direkte demokrati i et ellers repræsentativt demokrati og giver borgerne mulighed for at overstyre Folketing et på de allervigtigste spørgsmål."}$$::jsonb,
  'mc','short',$${"concepts":["folkeafstemning","direkte demokrati","Grundloven","EU","suverænitet"],"misconception_type":"surface_association","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"concept_clarification","challenge_role":"reinforcement","domain":"democracy_power"}$$::jsonb,
  'mc_single',2,'auto',true,'democracy_power',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er EU's rolle i forhold til dansk lovgivning?","options":["EU kan vedtage regler der gælder direkte i Danmark og som har forrang for dansk lovgivning inden for EU's kompetenceområder","EU kan kun give anbefalinger til Danmark — Danmark er aldrig forpligtet til at følge dem","EU bestemmer al dansk lovgivning og Folketing et har ingen selvstændig lovgivningsmagt","EU og Danmark har ingen politisk forbindelse — EU handler udelukkende om handel og økonomi"],"correct":"EU kan vedtage regler der gælder direkte i Danmark og som har forrang for dansk lovgivning inden for EU's kompetenceområder","accepted_answers":["EU kan vedtage regler der gælder direkte i Danmark og som har forrang for dansk lovgivning inden for EU's kompetenceområder"],"review_text":"Danmark er EU-medlem og det betyder at EU-lovgivning på visse områder — som handel, miljø og arbejdsmarkedsret — gælder direkte i Danmark og har forrang for dansk lov. Men Danmark har via folkeafstemninger beholdt forbehold på bl.a. euroen og forsvarssamarbejdet. Folketing et har stadig stor selvstændig lovgivningsmagt — men deler den med EU på de kompetenceområder Danmark har overdraget. Det er et eksempel på at dansk demokrati er indlejret i et større overnationalt system."}$$::jsonb,
  'mc','short',$${"concepts":["EU","suverænitet","dansk lovgivning","forrang","forbehold"],"misconception_type":"overgeneralization","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"democracy_power"}$$::jsonb,
  'mc_single',2,'auto',true,'democracy_power',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er oppositionspartiers funktion i et demokrati?","options":["At kritisere og kontrollere regeringen, stille alternative forslag og repræsentere de vælgere der ikke støtter den siddende regering","At samarbejde med regeringen om alle love for at sikre stabile flertal","At forberede sig på at danne ny regering hvis valget vindes — og ellers holde sig passive","At hindre alle regeringens lovforslag i at blive vedtaget"],"correct":"At kritisere og kontrollere regeringen, stille alternative forslag og repræsentere de vælgere der ikke støtter den siddende regering","accepted_answers":["At kritisere og kontrollere regeringen, stille alternative forslag og repræsentere de vælgere der ikke støtter den siddende regering"],"review_text":"Oppositionen er demokratiets interne kontrolmekanisme. Oppositionspartierne sidder ikke i regering men kan stille spørgsmål til ministre, fremsætte mistillidsvotum og komme med alternative politiske forslag. De repræsenterer den del af befolkningen der ikke stemte på regeringspartierne. Et demokrati uden reel opposition er ikke et reelt demokrati — det er et etpartisystem med et demokratisk skin."}$$::jsonb,
  'mc','short',$${"concepts":["opposition","kontrol","parlamentarisme","repræsentation","alternativ"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"democracy_power"}$$::jsonb,
  'mc_single',2,'auto',true,'democracy_power',7,2
);

-- ─── BAND 3 (6 questions) ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er forskellen på propaganda og journalistik?","options":["Propaganda har til formål at manipulere holdninger og forvrænger eller skjuler fakta for at støtte et bestemt synspunkt — journalistik stræber mod at afdække virkeligheden uafhængigt af interesser","Propaganda er altid statsstyret mens journalistik altid er privat og uafhængig","Propaganda er falsk og journalistik er sand — det er den eneste forskel","Propaganda er kun et fænomen fra 2. verdenskrig — i dag er alle medier troværdige"],"correct":"Propaganda har til formål at manipulere holdninger og forvrænger eller skjuler fakta for at støtte et bestemt synspunkt — journalistik stræber mod at afdække virkeligheden uafhængigt af interesser","accepted_answers":["Propaganda har til formål at manipulere holdninger og forvrænger eller skjuler fakta for at støtte et bestemt synspunkt — journalistik stræber mod at afdække virkeligheden uafhængigt af interesser"],"review_text":"Propaganda er information der bevidst vinkles for at forme folks holdninger — det kan komme fra stater, partier eller private aktører og er hverken nyt eller kun historisk. Journalistik stræber mod uafhængig faktaafdækning med kildekontrol og redaktionel vurdering. Grænsen kan være uklar i praksis. Det afgørende er hensigten: propaganda forsøger at overtale ved at manipulere, journalistik forsøger at informere. Propaganda er farlig for demokratiet fordi den underminerer borgernes evne til at danne selvstændige holdninger baseret på fakta."}$$::jsonb,
  'mc','short',$${"concepts":["propaganda","journalistik","manipulation","fakta","mediekritik"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"conceptual","insight_type":"perspective_shift","challenge_role":"challenge","domain":"democracy_power"}$$::jsonb,
  'mc_single',3,'auto',true,'democracy_power',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er menneskerettigheder og hvem sikrer dem internationalt?","options":["Grundlæggende rettigheder alle mennesker har i kraft af at være mennesker — vedtaget i FN's Menneskerettighedserklæring og håndhævet bl.a. via Den Europæiske Menneskerettighedsdomstol","Rettigheder som kun gælder i demokratier og som diktaturer frit kan ignorere","Regler vedtaget af den danske regering som kun gælder for danske statsborgere","Rettigheder der kun gælder hvis man kan betale for en advokat til at håndhæve dem"],"correct":"Grundlæggende rettigheder alle mennesker har i kraft af at være mennesker — vedtaget i FN's Menneskerettighedserklæring og håndhævet bl.a. via Den Europæiske Menneskerettighedsdomstol","accepted_answers":["Grundlæggende rettigheder alle mennesker har i kraft af at være mennesker — vedtaget i FN's Menneskerettighedserklæring og håndhævet bl.a. via Den Europæiske Menneskerettighedsdomstol"],"review_text":"FN's Verdenserklæring om Menneskerettigheder fra 1948 fastslog at alle mennesker har grundlæggende rettigheder uanset nationalitet, race, køn eller religion. Den Europæiske Menneskerettighedskonvention (1950) er bindende for Danmark og håndhæves af Menneskerettighedsdomstolen i Strasbourg — enkeltpersoner kan klage direkte. Menneskerettigheder sætter grænser for hvad selv demokratisk valgte regeringer lovligt kan gøre mod borgerne. De er ikke blot idealer — de er håndhævelige retsnormer."}$$::jsonb,
  'mc','short',$${"concepts":["menneskerettigheder","FN","Menneskerettighedsdomstolen","universalitet","international lov"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"conceptual","insight_type":"concept_clarification","challenge_role":"challenge","domain":"democracy_power"}$$::jsonb,
  'mc_single',3,'auto',true,'democracy_power',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er et borgerforslag og hvad sker der med det i Folketing et?","options":["Et lovforslag borgere kan indsende som Folketing et er forpligtet til at behandle hvis det samler mindst 50.000 støtter inden for 180 dage","En anmodning til kommunen om at reparere en vej eller bygge en legeplads","En underskriftindsamling der automatisk ændrer en lov hvis nok underskriver","Et forslag der kun kan indsendes af borgere med videregående uddannelse"],"correct":"Et lovforslag borgere kan indsende som Folketing et er forpligtet til at behandle hvis det samler mindst 50.000 støtter inden for 180 dage","accepted_answers":["Et lovforslag borgere kan indsende som Folketing et er forpligtet til at behandle hvis det samler mindst 50.000 støtter inden for 180 dage"],"review_text":"Borgerforslaget (indført i 2018) er en konkret måde borgere kan bringe et emne på den politiske dagsorden uden at have et partimandat. Hvis forslaget samler 50.000 gyldige støtter inden for 180 dage er Folketing et forpligtet til at behandle det i et udvalgsmøde. Det garanterer ikke at forslaget vedtages — men det sikrer at Folketing et tager stilling. Det er direkte demokrati i praksis og et vigtigt redskab for borgere der ønsker forandring uden at vente på et parti."}$$::jsonb,
  'mc','short',$${"concepts":["borgerforslag","direkte demokrati","folkelig initiativret","Folketing","50.000"],"misconception_type":"overgeneralization","cognitive_skill":"application","difficulty_type":"factual","insight_type":"concept_clarification","challenge_role":"challenge","domain":"democracy_power"}$$::jsonb,
  'mc_single',3,'auto',true,'democracy_power',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er politisk polarisering og hvad er risikoen for demokratiet?","options":["Polarisering er når samfundet opdeles i stærkt modsatrettede lejre der ikke kan kommunikere — det truer demokratiet fordi kompromis og fælles løsninger bliver næsten umulige","Polarisering er et tegn på et sundt demokrati fordi det viser at borgerne har klare og engagerede holdninger","Politisk polarisering er kun et problem i USA — det sker ikke i nordeuropæiske demokratier","Polarisering opstår kun når valgdeltagelsen er lav og kan løses med obligatorisk stemmepligt"],"correct":"Polarisering er når samfundet opdeles i stærkt modsatrettede lejre der ikke kan kommunikere — det truer demokratiet fordi kompromis og fælles løsninger bliver næsten umulige","accepted_answers":["Polarisering er når samfundet opdeles i stærkt modsatrettede lejre der ikke kan kommunikere — det truer demokratiet fordi kompromis og fælles løsninger bliver næsten umulige"],"review_text":"I stærkt polariserede samfund ses den politiske modstander ikke som en legitim konkurrent med andre værdier men som en fjende. Det gør kompromis — som er demokratiets livsnerve — næsten umuligt. USA er det tydeligste eksempel: Kongressen har svært ved at vedtage love fordi parterne ikke samarbejder. I Danmark er polariseringen vokset de seneste år men er fortsat lavere end i mange lande. Sociale mediers algoritmer kan forstærke polarisering ved at vise folk indhold der bekræfter deres eksisterende holdninger."}$$::jsonb,
  'mc','short',$${"concepts":["polarisering","kompromis","demokratisk erosion","sociale medier","algoritmer"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"challenge","domain":"democracy_power"}$$::jsonb,
  'mc_single',3,'auto',true,'democracy_power',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er sammenhængen mellem velfærdsstaten og demokratiet?","options":["Velfærdsstaten kan styrke demokratiet ved at reducere ekstrem ulighed der ellers giver velhavende borgere uforholdsmæssig politisk magt","Velfærdsstaten og demokratiet er fuldstændig adskilte — det ene har ingen effekt på det andet","Velfærdsstaten svækker demokratiet fordi den gør borgerne afhængige af staten og dermed politisk passive","Kun lande med en velfærdsstat kan være demokratier — alle andre er per definition diktaturer"],"correct":"Velfærdsstaten kan styrke demokratiet ved at reducere ekstrem ulighed der ellers giver velhavende borgere uforholdsmæssig politisk magt","accepted_answers":["Velfærdsstaten kan styrke demokratiet ved at reducere ekstrem ulighed der ellers giver velhavende borgere uforholdsmæssig politisk magt"],"review_text":"Den skandinaviske model kombinerer høje skatter med stærke offentlige ydelser og reducerer den sociale ulighed som ellers kan skabe et klasseskel i politisk deltagelse. Borgere med lav indkomst deltager typisk mindre i demokratiet. Forskning viser at mere egalitære samfund har stærkere demokratisk deltagelse og mere tillid til institutioner. Det er ikke et universalt argument — liberale demokratier med lavere velfærd fungerer også. Men ekstrem ulighed er en dokumenteret demokratisk risikofaktor."}$$::jsonb,
  'mc','short',$${"concepts":["velfærdsstat","ulighed","demokratisk deltagelse","skandinavisk model","social kapital"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"reframing","challenge_role":"challenge","domain":"democracy_power"}$$::jsonb,
  'mc_single',3,'auto',true,'democracy_power',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er desinformation og hvad er dens konsekvens for demokratiet?","options":["Bevidst spredning af falsk eller vildledende information — det underminerer borgernes evne til at træffe velinformerede valg og svækker tilliden til demokratiske institutioner","Desinformation er kun et problem i lande uden pressefrihed — i frie demokratier korrigeres det automatisk","Desinformation er et nyt fænomen opstået med sociale medier og eksisterede ikke som politisk redskab før","Bevidst falsk information er harmløs hvis den straks modbevises af andre borgere"],"correct":"Bevidst spredning af falsk eller vildledende information — det underminerer borgernes evne til at træffe velinformerede valg og svækker tilliden til demokratiske institutioner","accepted_answers":["Bevidst spredning af falsk eller vildledende information — det underminerer borgernes evne til at træffe velinformerede valg og svækker tilliden til demokratiske institutioner"],"review_text":"Desinformation (bevidst falsk information) er forskellig fra misinformation (utilsigtet fejl). Demokratiet kræver at borgere kan basere deres valg på faktuelle oplysninger. Desinformation der systematisk spredes via sociale medier kan fordreje valgresultater og underminere tilliden til institutioner. Covid-19 illustrerede dette: falske påstande om vacciner spredte sig hurtigt og påvirkede folkesundheden. Moderne demokratier kæmper med at afveje bekæmpelse af desinformation mod ytringsfriheden — det er en af de sværeste demokratiske balanceproblemer i dag."}$$::jsonb,
  'mc','short',$${"concepts":["desinformation","misinformation","demokratisk meningsdannelse","sociale medier","ytringsfrihed"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"concept_clarification","challenge_role":"challenge","domain":"democracy_power"}$$::jsonb,
  'mc_single',3,'auto',true,'democracy_power',7,3
);

-- ─── BAND 4 (5 questions) ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er korruption og hvordan underminerer det demokratiet?","options":["Korruption er misbrug af offentlig magt til privat fordel — det underminerer demokratiet fordi det erstatter forbindelsen mellem borger og beslutning med penge og personlige forbindelser","Korruption er kun et problem i diktaturer — demokratier er immune fordi vælgerne kan straffe korrupte politikere","Korruption er ubetydelig i moderne demokratier fordi medierne altid afslører det hurtigt","Korruption er kun skadeligt hvis det er ulovligt — legal begunstigelse er en naturlig del af politik"],"correct":"Korruption er misbrug af offentlig magt til privat fordel — det underminerer demokratiet fordi det erstatter forbindelsen mellem borger og beslutning med penge og personlige forbindelser","accepted_answers":["Korruption er misbrug af offentlig magt til privat fordel — det underminerer demokratiet fordi det erstatter forbindelsen mellem borger og beslutning med penge og personlige forbindelser"],"review_text":"Korruption — fx bestikkelse, nepotisme og magtmisbrug — eksisterer i alle samfundstyper men er mere udbredt i svage demokratier. I korrupte systemer bestemmer penge og forbindelser hvem der får adgang til magt og ressourcer i stedet for demokratiske processer. Transparency Internationals Korruptionsperceptionsindeks viser at Danmark konsekvent er et af verdens mindst korrupte lande — et resultat af stærke institutioner, transparens og pressefrihed. Men ingen demokrati er immunt: korruption starter som undtagelse og ender som norm hvis den ikke bekæmpes aktivt."}$$::jsonb,
  'mc','short',$${"concepts":["korruption","misbrug","institutioner","transparens","Transparency International"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"analytical_challenge","domain":"democracy_power"}$$::jsonb,
  'mc_single',4,'auto',true,'democracy_power',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er risikoen ved at en regering udvider sine magtbeføjelser under en national krise som pandemi eller krig?","options":["Nødlovgivning kan være nødvendig i en krise — men den skaber en demokratisk risiko hvis de udvidede beføjelser ikke ophæves igen efter krisen og dermed cementerer magtkoncentration","Der er ingen demokratisk risiko — kriser kræver altid stærke ledere og midlertidig magtkoncentration er altid godartet","Demokratier bør suspendere demokratiet midlertidigt under kriser fordi demokrati er for langsomt","Borgerne er altid villige til at give afkald på alle rettigheder under kriser og det er aldrig et demokratisk problem"],"correct":"Nødlovgivning kan være nødvendig i en krise — men den skaber en demokratisk risiko hvis de udvidede beføjelser ikke ophæves igen efter krisen og dermed cementerer magtkoncentration","accepted_answers":["Nødlovgivning kan være nødvendig i en krise — men den skaber en demokratisk risiko hvis de udvidede beføjelser ikke ophæves igen efter krisen og dermed cementerer magtkoncentration"],"review_text":"Under Covid-19 vedtog mange demokratier nødlovgivning med begrænset parlamentarisk kontrol. Det kan være nødvendigt i en akut krise — men historien viser at midlertidige beføjelser kan blive permanente. Victor Orbán brugte Covid-19 som begrundelse for at regere ved dekret i Ungarn i 2020. Demokratiske kontrolmekanismer — parlamentsoversigt, domstolsprøvelse, pressefrihed — er vigtigst præcis under kriser. Prisen for et velfungerende demokrati er at det er langsommere end et autoritært styre i akutte situationer."}$$::jsonb,
  'mc','short',$${"concepts":["nødlovgivning","magtkoncentration","demokratisk kontrol","krise","Orbán"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"analytical_challenge","domain":"democracy_power"}$$::jsonb,
  'mc_single',4,'auto',true,'democracy_power',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er populisme og hvad er den demokratiske risiko ved det?","options":["Populisme opstiller et skel mellem 'det ægte folk' og en 'korrupt elite' — det underminerer demokratiet ved at bruge demokratisk retorik til at delegitimere de institutioner der beskytter demokratiet","Populisme er det samme som at lytte til borgernes ønsker og er altid et udtryk for sundt demokrati","Populisme er kun et problem i fattige lande — rige demokratier er immune mod populistiske bevægelser","Populisme er en specifik politisk ideologi med et fast sæt af politikker på linje med socialisme eller liberalisme"],"correct":"Populisme opstiller et skel mellem 'det ægte folk' og en 'korrupt elite' — det underminerer demokratiet ved at bruge demokratisk retorik til at delegitimere de institutioner der beskytter demokratiet","accepted_answers":["Populisme opstiller et skel mellem 'det ægte folk' og en 'korrupt elite' — det underminerer demokratiet ved at bruge demokratisk retorik til at delegitimere de institutioner der beskytter demokratiet"],"review_text":"Populistiske bevægelser deler en logik: de hævder at repræsentere 'det sande folk' mod en 'korrupt elite' der kontrollerer institutionerne. Det lyder demokratisk — men i praksis bruges logikken til at delegitimere kritiske institutioner (domstole, medier, valgkommissioner) som del af den 'korrupte elite'. Resultatet er erosion af de kontrolmekanismer der beskytter demokratiet mod magtmisbrug. Populisme kan komme fra både højre og venstre — det definerende er ikke politikken men logikken om folk mod elite."}$$::jsonb,
  'mc','short',$${"concepts":["populisme","elite","folk","demokratisk erosion","institutioner","delegitimering"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"analytical_challenge","domain":"democracy_power"}$$::jsonb,
  'mc_single',4,'auto',true,'democracy_power',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er sammenhængen mellem uddannelsesniveau og demokratisk deltagelse?","options":["Borgere med højere uddannelse deltager statistisk mere i demokratiet — systematisk lav uddannelse hos store grupper skaber politisk underrepræsentation af disse gruppers interesser","Uddannelse og demokratisk deltagelse er fuldstændig uafhængige — alle borgere stemmer og engagerer sig lige meget uanset uddannelsesniveau","For høj uddannelse er skadelig for demokratiet fordi veluddannede borgere overkomplicerer simple politiske spørgsmål","Uddannelse øger demokratisk deltagelse men kun i lande med obligatorisk stemmepligt"],"correct":"Borgere med højere uddannelse deltager statistisk mere i demokratiet — systematisk lav uddannelse hos store grupper skaber politisk underrepræsentation af disse gruppers interesser","accepted_answers":["Borgere med højere uddannelse deltager statistisk mere i demokratiet — systematisk lav uddannelse hos store grupper skaber politisk underrepræsentation af disse gruppers interesser"],"review_text":"Forskning fra danske og internationale valg viser konsekvent at valgdeltagelse og politisk engagement stiger med uddannelsesniveau. Det skaber en demokratisk skævhed: borgere med lav uddannelse — der typisk er mest afhængige af sociale velfærdspolitikker — er underrepræsenterede i den politiske debat. Det er et argument for folkeskole og adgang til uddannelse som demokratiske investeringer ud over det rent erhvervsmæssige. Politisk kompetence erhverves ikke kun i skolen: foreningsliv og civilsamfund spiller også en vigtig rolle."}$$::jsonb,
  'mc','short',$${"concepts":["uddannelse","demokratisk deltagelse","valgdeltagelse","politisk kompetence","underrepræsentation"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"causal","insight_type":"reframing","challenge_role":"analytical_challenge","domain":"democracy_power"}$$::jsonb,
  'mc_single',4,'auto',true,'democracy_power',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er den demokratiske risiko ved at et fåtal af ejere kontrollerer de fleste store medier?","options":["Mediekoncentration kan skævvride den offentlige debat og give medieejeerne uforholdsmæssig politisk indflydelse som ikke er demokratisk legitimeret","Mediernes ejerskab er irrelevant for demokratiet fordi journalister altid er uafhængige af ejernes interesser","Mediekoncentration styrker demokratiet fordi færre ejere giver mere konsistent og stabil nyhedsdækning","Det er kun et problem hvis medieejerne er udenlandske — dansk medieejerskab er altid demokratisk uskadeligt"],"correct":"Mediekoncentration kan skævvride den offentlige debat og give medieejeerne uforholdsmæssig politisk indflydelse som ikke er demokratisk legitimeret","accepted_answers":["Mediekoncentration kan skævvride den offentlige debat og give medieejeerne uforholdsmæssig politisk indflydelse som ikke er demokratisk legitimeret"],"review_text":"I Danmark ejer en håndfuld virksomheder størstedelen af de store trykte og digitale medier. Medieejere kan indirekte påvirke redaktionel linje og prioritering af historier — selv uden direkte indblanding skaber ansættelse af redaktionschefer en strukturel loyalitet. Fri og mangfoldig presse kræver ikke blot frihed fra statskontrol men også beskyttelse mod kommerciel og politisk koncentration. Det er baggrunden for statsstøtte til mediemangfoldighed i Danmark. Medieejerskab er en del af den reelle magtfordeling — ikke kun den formelle."}$$::jsonb,
  'mc','short',$${"concepts":["mediekoncentration","pressefrihed","ejerskab","demokratisk kontrol","mangfoldighed"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"analytical_challenge","domain":"democracy_power"}$$::jsonb,
  'mc_single',4,'auto',true,'democracy_power',7,4
);

-- ─── BAND 5 (3 questions) ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Kan et demokrati med ekstrem ulighed levere reel politisk lighed?","options":["Ekstrem ulighed underminerer demokratiets reelle lighed: rigdom giver adgang til politisk magt via medier, lobbyisme og valgkampfinansiering og skaber et de facto oligarki bag det demokratiske facade","Demokrati og ulighed er fuldt kompatible fordi politisk lighed og økonomisk ulighed er fuldstændig adskilte sfærer der ikke påvirker hinanden","Ulighed styrker demokratiet fordi velstående borgere har mere tid og resurser til politisk engagement der gavner hele samfundet","Det er et meningsløst spørgsmål fordi alle samfund har ulighed og alle demokratier overlever uanset graden"],"correct":"Ekstrem ulighed underminerer demokratiets reelle lighed: rigdom giver adgang til politisk magt via medier, lobbyisme og valgkampfinansiering og skaber et de facto oligarki bag det demokratiske facade","accepted_answers":["Ekstrem ulighed underminerer demokratiets reelle lighed: rigdom giver adgang til politisk magt via medier, lobbyisme og valgkampfinansiering og skaber et de facto oligarki bag det demokratiske facade"],"review_text":"De mest egalitære demokratier (Skandinavien, New Zealand, Canada) scorer typisk højest på demokratiske kvalitetsmål. Forskning viser at i stærkt ulige samfund er rige borgeres politiske indflydelse uforholdsmæssig stor — via medieejerskab, politiske donationer og netværk. I USA er det dokumenteret at politiske beslutninger i langt højere grad afspejler velhavende borgeres præferencer end brede befolkningsgruppers. Demokratiets formelle lighed (én stemme) kan blive meningsløs hvis den reelle politiske magt er voldsomt skævt fordelt. Det er ikke et argument for absolut lighed — men for at ekstrem ulighed er en systemisk trussel mod demokratiets substans."}$$::jsonb,
  'mc','short',$${"concepts":["ulighed","oligarki","lobbyisme","demokratisk lighed","politisk magt","kapitalisme"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"democracy_power"}$$::jsonb,
  'mc_single',5,'auto',true,'democracy_power',7,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er paradokset i at et demokrati kan stemme sig selv ud af demokratiet — og hvad er den normative konsekvens?","options":["Et demokrati kan bruge demokratiske procedurer til at afskaffe sig selv — det viser at demokrati ikke kan retfærdiggøres udelukkende ved procedurer men kræver substantielle værdier som mindretalsrettigheder der ikke kan sættes til afstemning","Det er et rent teoretisk problem der aldrig er sket i virkeligheden og som moderne demokratiske institutioner har gjort umuligt","Paradokset er kun relevant for nye demokratier — etablerede demokratier som Danmark er immune mod selvafvikling","Paradokset løses simpelt ved at forbyde partier der er imod demokrati — det er tilstrækkelig beskyttelse"],"correct":"Et demokrati kan bruge demokratiske procedurer til at afskaffe sig selv — det viser at demokrati ikke kan retfærdiggøres udelukkende ved procedurer men kræver substantielle værdier som mindretalsrettigheder der ikke kan sættes til afstemning","accepted_answers":["Et demokrati kan bruge demokratiske procedurer til at afskaffe sig selv — det viser at demokrati ikke kan retfærdiggøres udelukkende ved procedurer men kræver substantielle værdier som mindretalsrettigheder der ikke kan sættes til afstemning"],"review_text":"I 1933 brugte Nazityskland Rigsdagen til at vedtage Ermächtigungsgesetz med 2/3 flertal — og dermed afskaffe demokratiet ad demokratisk vej. Det er ikke et teoretisk eksempel: det skete. Den normative konsekvens er afgørende: demokrati kan ikke retfærdiggøres udelukkende ved at flertallet ønsker det, fordi flertallet kan ønske at afskaffe demokratiet. Løsningen mange demokratier har valgt er evighedsklausuler — den tyske Grundlovs artikel 79(3) erklærer visse principper ufravigelige selv med 100% flertal. Demokratiets selvforsvar kræver at visse grundlæggende værdier er undtaget fra afstemning."}$$::jsonb,
  'mc','short',$${"concepts":["demokratisk paradoks","selvafvikling","Ermächtigungsgesetz","evighedsklausuler","proceduralisme","substantielle værdier"],"misconception_type":"scope_confusion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"democracy_power"}$$::jsonb,
  'mc_single',5,'auto',true,'democracy_power',7,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er de vigtigste modsatrettede effekter digitale platforme har på demokratiet?","options":["Platforme sænker adgangsbarrieren for politisk deltagelse og spredning af information — men skaber også algoritmisk polarisering, ekkokamre og desinformation der fragmenterer den fælles offentlige diskurs demokratiet kræver","Digitale platforme styrker udelukkende demokratiet fordi politisk information aldrig har været mere tilgængeligt for alle borgere","Digitale platforme truer udelukkende demokratiet og bør reguleres bort fordi fordelene er ubetydelige sammenlignet med skaderne","Platforme er politisk neutrale teknologier der hverken styrker eller svækker demokratiet — det er op til den enkelte bruger"],"correct":"Platforme sænker adgangsbarrieren for politisk deltagelse og spredning af information — men skaber også algoritmisk polarisering, ekkokamre og desinformation der fragmenterer den fælles offentlige diskurs demokratiet kræver","accepted_answers":["Platforme sænker adgangsbarrieren for politisk deltagelse og spredning af information — men skaber også algoritmisk polarisering, ekkokamre og desinformation der fragmenterer den fælles offentlige diskurs demokratiet kræver"],"review_text":"Digitale platforme har modsatrettede demokratiske effekter. Positivt: Arab Spring-mobiliseringen, marginaliserede gruppers adgang til offentlighed, transparens om magthavers adfærd. Negativt: Algoritmer optimerer for engagement som polariserede indlæg genererer — det skaber ekkokamre og forstærker desinformation. Forskning viser at falske nyheder spredes markant hurtigere end korrektioner på sociale medier. EU's Digital Services Act (2022) er et reguleringsrespons. Demokratiets kerneproblem med platforme er ikke teknologien men de incentivsystemer der belønner oprørende indhold. Det er et uafklaret spørgsmål om demokratiet kan tilpasse sig hurtigt nok."}$$::jsonb,
  'mc','short',$${"concepts":["digitale platforme","algoritmer","ekkokamre","polarisering","desinformation","offentlig diskurs"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"democracy_power"}$$::jsonb,
  'mc_single',5,'auto',true,'democracy_power',7,5
);
