-- Section 100 — World War 2 Grade 7 Expansion Sprint
-- Closes the largest content gap found by Section 99 Inventory Audit:
-- Grade 7 had 0 accessible world_war_2 questions.
--
-- 25 questions: target_grade=7, domain=world_war_2, is_active=true
-- Band distribution: B1×6, B2×7, B3×7, B4×5
--
-- Topic coverage: Rise of Nazism, Hitler, Holocaust, Danish occupation,
-- resistance, rescue of Danish Jews, D-Day, liberation, human rights.
-- Misconceptions actively targeted throughout.

-- ─── GRADE 7 · BAND 1 (6 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var 2. Verdenskrig?","options":["En krig der rasede i Europa og resten af verden fra 1939 til 1945","En krig der kun foregik i Asien og Stillehavet","Et navn for borgerkrigene i Europa i mellemkrigstiden","En militær øvelse arrangeret af Folkeforbundet"],"correct":"En krig der rasede i Europa og resten af verden fra 1939 til 1945","accepted_answers":["En krig der rasede i Europa og resten af verden fra 1939 til 1945"],"review_text":"2. Verdenskrig varede fra 1939 til 1945 og var den mest ødelæggende krig i menneskehedens historie. Over 70 millioner mennesker døde — soldater og civile. Krigen startede da Nazi-Tyskland invaderede Polen den 1. september 1939 og endte med Tysklands kapitulation i maj 1945."}'::jsonb,
  'mc','short','{"concepts":["2. Verdenskrig","1939-1945","Polen","Nazi-Tyskland"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_2"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_2',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvem kæmpede på de to sider i 2. Verdenskrig?","options":["De Allierede (England, USA, Frankrig, Sovjet) mod Aksemagterne (Tyskland, Italien, Japan)","England og Frankrig mod USA og Rusland","Europa mod Amerika og Asien","Demokratier mod alle monarkier"],"correct":"De Allierede (England, USA, Frankrig, Sovjet) mod Aksemagterne (Tyskland, Italien, Japan)","accepted_answers":["De Allierede (England, USA, Frankrig, Sovjet) mod Aksemagterne (Tyskland, Italien, Japan)"],"review_text":"Krigen stod mellem to grupper. Aksemagterne: Nazi-Tyskland ledet af Hitler, Italien under Mussolini og Japan. De Allierede: England, Frankrig, Sovjet og USA fra 1941. Danmark var besat af Tyskland men havnede officielt på de Allieredes side da krigen sluttede."}'::jsonb,
  'mc','short','{"concepts":["Allierede","Aksemagterne","England","USA","Sovjet","Tyskland"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_2"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_2',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var Adolf Hitlers rolle i 2. Verdenskrig?","options":["Han var Nazitysklands leder og den person der bar størst ansvar for krigen og Holocaust","Han var en tysk general der gennemførte krigen men ikke startede den","Han var Østrigs præsident der tabte valget og flygtede til Tyskland","Han var leder af Italien og grundlæggeren af fascismen"],"correct":"Han var Nazitysklands leder og den person der bar størst ansvar for krigen og Holocaust","accepted_answers":["Han var Nazitysklands leder og den person der bar størst ansvar for krigen og Holocaust"],"review_text":"Adolf Hitler var Nazitysklands Führer og den person der mere end nogen anden drev krigen. Han planlagde invasionen af Polen og var arkitekten bag Holocaust — den systematiske udryddelse af millioner af jøder og andre grupper. Hans regime startede krigen da han beordrede invasionen af Polen i 1939."}'::jsonb,
  'mc','short','{"concepts":["Hitler","Führer","Nazi-Tyskland","Holocaust","krig"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_2"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_2',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad dækker begrebet Holocaust over?","options":["Nazisternes systematiske mord på seks millioner jøder og millioner af andre grupper","Et navn for 2. Verdenskrigs militære slag tilsammen","En hungerkatastrofe i Sovjet forårsaget af krigen","Bombningerne af tyske byer af de Allierede"],"correct":"Nazisternes systematiske mord på seks millioner jøder og millioner af andre grupper","accepted_answers":["Nazisternes systematiske mord på seks millioner jøder og millioner af andre grupper"],"review_text":"Holocaust var et planlagt folkemord. Nazisterne dræbte ca. seks millioner jøder — to tredjedele af Europas jødiske befolkning. De myrdede også romaer, handikappede, homoseksuelle og politiske modstandere. Det var ikke et biprodukt af krigen men et bevidst program der var planlagt og systematisk gennemført."}'::jsonb,
  'mc','short','{"concepts":["Holocaust","folkemord","jøder","systematisk","millioner"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_2"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_2',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad skete der i Danmark den 9. april 1940?","options":["Nazi-Tyskland invaderede og besatte Danmark","Danmark erklærede krig mod Tyskland","Danmark blev befriet fra tysk besættelse","Danmark indgik en fredsaftale med de Allierede"],"correct":"Nazi-Tyskland invaderede og besatte Danmark","accepted_answers":["Nazi-Tyskland invaderede og besatte Danmark"],"review_text":"Den 9. april 1940 om morgenen invaderede tyske tropper Danmark. Den danske militære modstand varede kun få timer — hæren var for lille til at stoppe invasionen. Kongen og regeringen valgte at undgive sig for at beskytte den danske befolkning. Besættelsen varede fem år til den 5. maj 1945."}'::jsonb,
  'mc','short','{"concepts":["9. april 1940","invasion","besættelse","Danmark","tyske tropper"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_2"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_2',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvordan sluttede 2. Verdenskrig i Danmark?","options":["Danmark blev befriet den 5. maj 1945 da de tyske styrker kapitulerede","Danmark sejrede over Tyskland efter store militære slag","Danmark underskrev en fredsaftale med Hitler i Berlin","De Allierede bombede Danmark fri fra tysk besættelse"],"correct":"Danmark blev befriet den 5. maj 1945 da de tyske styrker kapitulerede","accepted_answers":["Danmark blev befriet den 5. maj 1945 da de tyske styrker kapitulerede"],"review_text":"Den 5. maj 1945 overgav de tyske styrker sig i Danmark. Det var en enorm lettelse efter fem år under besættelsen. I gaderne fejrede danskerne friheden med lys i vinduerne. Befrielsesdagen den 5. maj fejres stadig hvert år som en vigtig del af dansk hukommelse om krigen."}'::jsonb,
  'mc','short','{"concepts":["5. maj 1945","befrielse","kapitulation","befrielsesdagen"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_2"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_2',7,1
);

-- ─── GRADE 7 · BAND 2 (7 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvorfor lykkedes det Hitler og nazisterne at komme til magten i Tyskland i 1933?","options":["Den tyske befolkning var dybt frustreret over fattigdom og ydmygelsen efter 1. Verdenskrig og nazisterne lovede at genoprette Tysklands storhed","Hitler gennemførte et hemmeligt kup og tog magten med militær magt","De europæiske stormagter tvang Hitler til at blive kansler for at stabilisere Europa","Hitler vandt et flertal ved et normalt demokratisk valg og alle tyskere støttede ham entusiastisk fra starten"],"correct":"Den tyske befolkning var dybt frustreret over fattigdom og ydmygelsen efter 1. Verdenskrig og nazisterne lovede at genoprette Tysklands storhed","accepted_answers":["Den tyske befolkning var dybt frustreret over fattigdom og ydmygelsen efter 1. Verdenskrig og nazisterne lovede at genoprette Tysklands storhed"],"review_text":"Versaillestraktaten efter 1. Verdenskrig ydmygede Tyskland med store krigsskadeerstatninger og territoriale tab. Så kom den store depression i 1929 med massearbejdsløshed. Nazisterne udnyttede denne frustration ved at love arbejde, stolthed og en syndebuk — jøderne. Hitlers vej til magten gik igennem demokratiets svagheder under ekstreme forhold."}'::jsonb,
  'mc','short','{"concepts":["Hitler","Nazi-parti","Versailles","ydmygelse","depression","syndebuk"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_2"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_2',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betød den tyske besættelse for danskernes hverdag?","options":["Danskerne var underlagt tyske ordrer og regler — der var udgangsforbud, censur og rationering af mad","Besættelsen ændrede ikke hverdagen da Danmark fik lov at styre sig selv fuldstændigt","Alle danskere blev sendt til arbejdslejre i Tyskland","Danskerne kæmpede daglige gadekampe mod de tyske soldater"],"correct":"Danskerne var underlagt tyske ordrer og regler — der var udgangsforbud, censur og rationering af mad","accepted_answers":["Danskerne var underlagt tyske ordrer og regler — der var udgangsforbud, censur og rationering af mad"],"review_text":"Hverdagen under besættelsen var begrænsende på mange måder. Tyske soldater patruljerede gaderne. Aviser blev censureret — man kunne ikke skrive frit om krigen. Der var rationering af mad og brændsel. Udgangsforbud om natten. Og frygten for at sige eller gøre noget forkert kunne have alvorlige konsekvenser."}'::jsonb,
  'mc','short','{"concepts":["besættelse","hverdag","censur","rationering","udgangsforbud","frygt"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_2"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_2',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var den nazistiske begrundelse for at forfølge og myrde jøderne?","options":["Nazisterne brugte en racistisk ideologi der fremstillede jøder som biologisk mindreværdige og ansvarlige for Tysklands problemer","Det var en religiøs konflikt da nazisterne som kristne angreb en anden religion","Jøderne havde erklæret krig mod Tyskland inden krigen brød ud","Det skyldtes en konkret kriminel handling som den jødiske befolkning kollektivt stod bag"],"correct":"Nazisterne brugte en racistisk ideologi der fremstillede jøder som biologisk mindreværdige og ansvarlige for Tysklands problemer","accepted_answers":["Nazisterne brugte en racistisk ideologi der fremstillede jøder som biologisk mindreværdige og ansvarlige for Tysklands problemer"],"review_text":"Nazi-ideologien var biologisk racisme. Hitler mente at der fandtes overlegne og underlegne racer og at jøderne var skyld i alt hvad der var galt i Tyskland — arbejdsløsheden, krigsunderlaget i 1918, alt. Det var ikke baseret på fakta men på had og propaganda. Jøderne blev gjort til syndebukke for at give den tyske frustration et ansigt."}'::jsonb,
  'mc','short','{"concepts":["racisme","ideologi","syndebuk","forfølgelse","had","misconception-religiøs"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_2"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_2',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var redningen af de danske jøder i oktober 1943?","options":["Danske borgere og fiskere hjalp ca. 7.000 jøder med at flygte til det neutrale Sverige i ly af natten","Den danske hær besejrede de tyske tropper og forhindrede deportationerne","De danske jøder gemte sig i kirker som de tyske soldater respekterede og ikke turde storme","Den danske regering forhandlede en aftale med Nazi-Tyskland om at beskytte de danske jøder"],"correct":"Danske borgere og fiskere hjalp ca. 7.000 jøder med at flygte til det neutrale Sverige i ly af natten","accepted_answers":["Danske borgere og fiskere hjalp ca. 7.000 jøder med at flygte til det neutrale Sverige i ly af natten"],"review_text":"I oktober 1943 planlagde nazisterne at deportere de danske jøder til koncentrationslejre. Men danskerne reagerede. Fiskere, naboer og fremmede hjalp med at skjule og transportere ca. 7.000 jøder over Øresund til Sverige der var neutralt. Det var en af krigens store menneskelige historier om mod og solidaritet — og det reddede næsten alle danske jøder."}'::jsonb,
  'mc','short','{"concepts":["redning","danske jøder","Sverige","fiskere","solidaritet","1943"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_2"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_2',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad skete der på D-dag den 6. juni 1944?","options":["De Allieredes landgang i Normandiet i Frankrig — begyndelsen på befrielsen af det besatte Vesteuropa","Den dag USA tabte det første store slag mod Japan i Stillehavet","Tidspunktet da Sovjet-styrkerne tog Berlin og afsluttede krigen i Europa","Den dag Hitler erklærede krig mod USA og England"],"correct":"De Allieredes landgang i Normandiet i Frankrig — begyndelsen på befrielsen af det besatte Vesteuropa","accepted_answers":["De Allieredes landgang i Normandiet i Frankrig — begyndelsen på befrielsen af det besatte Vesteuropa"],"review_text":"Den 6. juni 1944 landede over 150.000 Allierede soldater på strandene i Normandiet. Det var det største amphibiøse militærangreb i historien. D-dag åbnede en ny front mod vest og begyndte den lange befrielse af Frankrig og resten af det besatte Europa. Men det tog stadig næsten et år at afslutte krigen."}'::jsonb,
  'mc','short','{"concepts":["D-dag","Normandiet","Frankrig","landgang","befrielse","1944"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_2"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_2',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Støttede alle tyskere nazisterne og Hitler?","options":["Nej — mange var bange, passive eller imod men åben protest var farligt og kunne koste livet","Ja — meningsmålinger viste at næsten alle tyskere støttede Hitler aktivt i hele krigsperioden","Ja — nazisternes valgsejr i 1933 viste at hele den tyske befolkning var enig og begejstret","Nej — men alle der var imod emigrerede og der var ingen modstand overhovedet i Tyskland"],"correct":"Nej — mange var bange, passive eller imod men åben protest var farligt og kunne koste livet","accepted_answers":["Nej — mange var bange, passive eller imod men åben protest var farligt og kunne koste livet"],"review_text":"Myten om at alle tyskere var nazister er forkert. Mange var bange. Gestapo og SS overvågede og straffede modstand hårdt. Nogle hjalp jøder på trods af risikoen. Andre fulgte ordrer fordi de frygtede konsekvenserne. Det er farligt at reducere et helt folk til kollektiv skyld — og det forhindrer os i at forstå hvad der rent faktisk skete og hvorfor."}'::jsonb,
  'mc','short','{"concepts":["alle-tyskere-misconception","modstand","Gestapo","frygt","kollektiv-skyld"],"misconception_type":"overgeneralization","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_2"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_2',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var den danske modstandsbevægelse under besættelsen?","options":["En voksende gruppe danskere der aktivt modstod den tyske besættelse ved sabotage, illegale aviser og hjælp til Allierede","Den officielle danske hær der kæmpede åbent mod de tyske styrker","En diplomatisk organisation der forsøgte at forhandle med nazisterne på dansk regerings vegne","En bevægelse der arbejdede for at Danmark frivilligt skulle slutte sig til Nazityskland"],"correct":"En voksende gruppe danskere der aktivt modstod den tyske besættelse ved sabotage, illegale aviser og hjælp til Allierede","accepted_answers":["En voksende gruppe danskere der aktivt modstod den tyske besættelse ved sabotage, illegale aviser og hjælp til Allierede"],"review_text":"Modstandsbevægelsen voksede gradvist under besættelsen. I starten var der illegale aviser der fortalte sandheden om besættelsen og krigen. Siden kom sabotage af fabrikker og jernbaner der arbejdede for tyskerne. Modstandsfolk hjalp også Allierede agenter og jøder med at flygte. Det var farligt — opdagelse betød fængsel, koncentrationslejr eller dødsstraf."}'::jsonb,
  'mc','short','{"concepts":["modstandsbevægelse","sabotage","illegale aviser","besættelse","risiko"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_2"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_2',7,2
);

-- ─── GRADE 7 · BAND 3 (7 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvordan bidrog freden efter 1. Verdenskrig til udbruddet af 2. Verdenskrig?","options":["Versaillestraktaten ydmygede Tyskland og skabte den frustration og vrede som nazisterne udnyttede til at komme til magten","Versaillestraktaten var en retfærdig fred der ikke kan bebrejdes for hvad der skete siden","Versaillestraktaten tvang Hitler juridisk til at starte en krig for at genvinde tabte tyske territorier","Freden skabte en stærk demokratisk bevægelse i Tyskland som nazisterne stjal ved et kup"],"correct":"Versaillestraktaten ydmygede Tyskland og skabte den frustration og vrede som nazisterne udnyttede til at komme til magten","accepted_answers":["Versaillestraktaten ydmygede Tyskland og skabte den frustration og vrede som nazisterne udnyttede til at komme til magten"],"review_text":"Versaillestraktaten i 1919 pålagde Tyskland ydmygende vilkår: kollektiv krigsskyld, tab af territorier og enorme krigsskadeerstatninger. Den tyske økonomi kollapsede. Denne nationale ydmygelse skabte grobund for ekstremisme. Hitler brugte løftet om at gøre op med Versaillesydmygelsen som sit vigtigste politiske budskab. Hårde fredsvilkår kan plante frøene til den næste krig."}'::jsonb,
  'mc','short','{"concepts":["Versailles","ydmygelse","grobund","ekstremisme","årsager","krig-og-fred"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_2',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvorfor valgte den danske regering ikke at føre en lang militær modstand mod den tyske invasion den 9. april 1940?","options":["Den danske hær var for lille til at vinde og en lang kamp ville have kostet mange civile liv uden at ændre det endelige resultat","Fordi den danske regering hemmelig sympatiserede med Hitler og ikke ønskede at kæmpe","Fordi den danske befolkning nægtede at lade sig mobilisere og ingen ville kæmpe","Fordi England lovede at befri Danmark inden for en uge hvis Danmark blot undgav sig"],"correct":"Den danske hær var for lille til at vinde og en lang kamp ville have kostet mange civile liv uden at ændre det endelige resultat","accepted_answers":["Den danske hær var for lille til at vinde og en lang kamp ville have kostet mange civile liv uden at ændre det endelige resultat"],"review_text":"Den 9. april stod Danmark over for et fundamentalt valg. En lille hær mod Europas stærkeste krigsmaskine. Konsekvensen af fortsat modstand: massakre på civile og totalt militært sammenbrud. Konsekvensen af overgivelse: bevarelse af den danske stat og mulighed for at beskytte befolkningen. Det var en kold pragmatisk beregning — ikke fejhed. Men prisen var fem år under besættelsen."}'::jsonb,
  'mc','short','{"concepts":["9. april","overgivelse","pragmatisme","hærens størrelse","civile liv","valg"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_2',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad gør Holocaust til et historisk unikt forbrydelse mod menneskeheden?","options":["Det var det første industrialiserede folkemord — planlagt og gennemført med bureaukratisk præcision med det mål systematisk at udrydde en hel folkegrupppe","Det var historiens største krig med flest krigsofre samlet set","Det var det første angreb på civile i en krig nogensinde","Det var den første gang et lands regering vendte sig mod sine egne borgere"],"correct":"Det var det første industrialiserede folkemord — planlagt og gennemført med bureaukratisk præcision med det mål systematisk at udrydde en hel folkegrupppe","accepted_answers":["Det var det første industrialiserede folkemord — planlagt og gennemført med bureaukratisk præcision med det mål systematisk at udrydde en hel folkegrupppe"],"review_text":"Folkedrab er sket i historien. Men Holocaust var nyt på en chokerende måde: det var industrialiseret og bureaukratisk. Togplaner, registre, videnskabeligt udviklede gaskamre, fabriksagtige krematorier. Staten mobiliserede alle sine ressourcer for at myrde systematisk og effektivt. Det er præcis dette der gør det til et definerende forbrydelse mod menneskeheden — ikke tilfældig vold men planlagt udryddelse."}'::jsonb,
  'mc','short','{"concepts":["Holocaust","industrialiseret folkemord","bureaukrati","systematisk","udryddelse"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_2',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var sammenhængen mellem nazistisk propaganda og den tyske befolknings støtte til regimet?","options":["Propaganda kontrollerede hvad folk vidste og troede — det var svært at modstå et system der styrede al information og straffede åben kritik","Propaganda var ineffektiv og tyske borgere gennemskuede den straks","Propaganda var kun rettet mod udlandet — tyske borgere fik sandfærdige informationer om regimet","Propaganda skabte støtte men folk valgte frit at tro på den uden noget pres eller konsekvens"],"correct":"Propaganda kontrollerede hvad folk vidste og troede — det var svært at modstå et system der styrede al information og straffede åben kritik","accepted_answers":["Propaganda kontrollerede hvad folk vidste og troede — det var svært at modstå et system der styrede al information og straffede åben kritik"],"review_text":"Nazistisk propaganda var allesteds nærværende. Goebbels styrede pressen, radio, film og kunst. Kritisk information var forbudt. Modstand risikerede fængsel. At forstå propaganda er ikke at undskylde dem der fulgte ordrer — men det forklarer hvordan normale mennesker kan ende med at deltage i noget ekstremt når de berøves adgang til sandheden."}'::jsonb,
  'mc','short','{"concepts":["propaganda","Goebbels","kontrol","censur","normalisering","misconception-ineffektiv"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_2',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad viser redningen af de danske jøder i 1943 om enkeltmenneskets mulighed for at handle moralsk under ekstremt pres?","options":["At det er muligt at vælge det rigtige selv i en situation domineret af frygt og fare — og at sådanne valg kan redde virkelige menneskeliv","At det kun er muligt at handle moralsk når myndighederne giver tilladelse til det","At de fleste danskere var ligeglade og at det kun var ganske få der valgte at hjælpe","At redningen var koordineret af den officielle danske regering og den regulære hær"],"correct":"At det er muligt at vælge det rigtige selv i en situation domineret af frygt og fare — og at sådanne valg kan redde virkelige menneskeliv","accepted_answers":["At det er muligt at vælge det rigtige selv i en situation domineret af frygt og fare — og at sådanne valg kan redde virkelige menneskeliv"],"review_text":"Naboer og fiskere der skjulte jøder og sejlede dem til Sverige risikerede fængsel og deportation. De var ikke helte i en eventyrlig forstand. Det var almindelige mennesker der valgte at handle på trods af frygten. Historien er et eksempel på at individuelle moralske valg under ekstreme omstændigheder gør en reel og konkret forskel for rigtige menneskers liv."}'::jsonb,
  'mc','short','{"concepts":["individuel moral","mod","solidaritet","valg","ansvar","redning"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_2',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betød samarbejdspolitikken i det besatte Danmark og hvad var dens formål?","options":["Den officielle danske regerings strategi om at samarbejde med besættelsesmagten for at bevare dansk selvstyre og beskytte befolkningen mod det værste","Et udtryk for at den danske regering sympatiserede med nazismen og ønskede at hjælpe Hitler militært","En hemmelig aftale om at støtte de Allierede i det skjulte mens man officielt arbejdede med Tyskland","En modstandsbevægelse der foregav at samarbejde for at sabotere besættelsen fra indsiden"],"correct":"Den officielle danske regerings strategi om at samarbejde med besættelsesmagten for at bevare dansk selvstyre og beskytte befolkningen mod det værste","accepted_answers":["Den officielle danske regerings strategi om at samarbejde med besættelsesmagten for at bevare dansk selvstyre og beskytte befolkningen mod det værste"],"review_text":"Samarbejdspolitikken var kontroversiel men ikke naiv. Den danske regering valgte at beholde en form for selvstyre ved at samarbejde — i stedet for at risikere at nazisterne indsatte en SS-leder. Det bevarede visse rettigheder og institutioner. Men prisen var at Danmark fremmede Tysklands krigsøkonomi. Det er et komplekst moralsk dilemma som stadig debatteres af historikere."}'::jsonb,
  'mc','short','{"concepts":["samarbejdspolitik","selvstyre","kompromis","dilemma","besættelse","strategi"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_2',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvordan påvirkede erfaringerne fra 2. Verdenskrig og Holocaust oprettelsen af FN og Menneskerettighedserklæringen i 1948?","options":["Verdens ledere ville forhindre at en stat igen systematisk kunne forfølge sine egne borgere og formulerede universelle rettigheder der stod over nationale love","FN og erklæringen blev oprettet for at hylde de Allierede sejrherrer og kriminalisere taberlandene","Erklæringen handlede primært om at regulere fremtidig krigføring og ikke om civile rettigheder og frihed","Verdens ledere var overraskede over Holocaust da ingen vidste det skete under krigen"],"correct":"Verdens ledere ville forhindre at en stat igen systematisk kunne forfølge sine egne borgere og formulerede universelle rettigheder der stod over nationale love","accepted_answers":["Verdens ledere ville forhindre at en stat igen systematisk kunne forfølge sine egne borgere og formulerede universelle rettigheder der stod over nationale love"],"review_text":"Da verden så omfanget af Holocaust sagde verdens ledere: aldrig igen. FN blev grundlagt i 1945. Den Universelle Menneskerettighedserklæring fulgte i 1948. Ideen: der findes rettigheder der tilkommer alle mennesker uanset nationalitet — og ingen stat har ret til at krænke dem. Demokratisk beskyttelse af minoriteter er et direkte svar på nazismens forbrydelser."}'::jsonb,
  'mc','short','{"concepts":["FN","menneskerettigheder","1948","aldrig-igen","universelle rettigheder","Holocaust-konsekvenser"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_2',7,3
);

-- ─── GRADE 7 · BAND 4 (5 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad viser Nürnberg-processerne om personligt ansvar for krigsforbrydelser?","options":["At det at følge ordrer ikke fritager nogen for moralsk og juridisk ansvar for forbrydelser mod menneskeheden","At soldater og embedsmænd ikke kan dømmes da de blot udførte statslige ordrer","At kun Hitlers allerinderste kreds var ansvarlig — alle andre var blot ufrivillige udøvere","At internationale domstole ikke har ret til at dømme for handlinger begået under krig"],"correct":"At det at følge ordrer ikke fritager nogen for moralsk og juridisk ansvar for forbrydelser mod menneskeheden","accepted_answers":["At det at følge ordrer ikke fritager nogen for moralsk og juridisk ansvar for forbrydelser mod menneskeheden"],"review_text":"Nürnberg-processerne (1945-46) dømte naziledere for forbrydelser mod menneskeheden. Forsvaret sagde: vi fulgte blot ordrer. Domstolen forkastede det: der findes handlinger der er forbudte uanset hvem der befalede dem. Det lagde grundlaget for nutidens internationale strafferet og slår fast at vi alle har et individuelt ansvar der overstiger statens ordrer."}'::jsonb,
  'mc','short','{"concepts":["Nürnberg","ansvar","ordrer","forbrydelser mod menneskeheden","international strafferet"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_2',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvilke langsigtede konsekvenser havde 2. Verdenskrig for verdens politiske orden?","options":["Krigen skabte en ny verdensorden med USA og Sovjet som supermagter og lagde grundlaget for Den Kolde Krig, FN og det moderne menneskerettighedssystem","Krigen løste alle internationale konflikter og skabte halvtreds år med stabil fred i hele verden","Krigen fik ingen varig politisk effekt da Europa hurtigt genopbyggede sin dominans som den gamle orden","Krigen endte med at det britiske imperiums globale dominans fortsatte uforandret i årtier"],"correct":"Krigen skabte en ny verdensorden med USA og Sovjet som supermagter og lagde grundlaget for Den Kolde Krig, FN og det moderne menneskerettighedssystem","accepted_answers":["Krigen skabte en ny verdensorden med USA og Sovjet som supermagter og lagde grundlaget for Den Kolde Krig, FN og det moderne menneskerettighedssystem"],"review_text":"2. Verdenskrig omformede verden fundamentalt. Det britiske og franske imperiums svækkedes og begyndte at opløses. USA og Sovjet stod som to supermagter og Den Kolde Krig begyndte. Europa integrerede sig for at forhindre ny krig — kimen til EU. FN og Menneskerettighedserklæringen kom til. Krigen ændrede hvem der bestemte i verden og hvilke regler der gjaldt."}'::jsonb,
  'mc','short','{"concepts":["efterkrigstid","verdensorden","USA","Sovjet","Den Kolde Krig","FN","EU-kimen"],"misconception_type":"scope_confusion","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_2',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad lærer historien om nazismens fremkomst os om demokratiets sårbarhed?","options":["Demokrati kan undermineres indefra af bevægelser der bruger demokratiske valg til at opnå magten og derefter afvikler de demokratiske institutioner","Demokrati er naturligt immunt mod ekstremisme da vælgerne altid vil vælge det moderate","Nazismens fremkomst skyldtes kun særlige tyske kulturelle afvigelser og kan aldrig gentage sig andre steder","Demokrati kan kun undermineres udefra ved militær invasion — aldrig af indre politiske kræfter"],"correct":"Demokrati kan undermineres indefra af bevægelser der bruger demokratiske valg til at opnå magten og derefter afvikler de demokratiske institutioner","accepted_answers":["Demokrati kan undermineres indefra af bevægelser der bruger demokratiske valg til at opnå magten og derefter afvikler de demokratiske institutioner"],"review_text":"Hitler kom til magten gennem demokratiske processer i 1933. Derefter afviklede han hurtigt demokratiet: forbød partier, fængsled modstandere og ophævede borgerrettigheder. Det viser at demokrati ikke er en automatisk beskyttelse. Det kræver aktive borgere der forsvarer institutionerne. En vigtig lektie for alle demokratier — inklusiv nutidens."}'::jsonb,
  'mc','short','{"concepts":["demokrati","sårbarhed","ekstremisme","institutioner","borgeransvar","historisk lektie"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_2',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvorfor afsluttede D-dag den 6. juni 1944 ikke krigen øjeblikkeligt?","options":["D-dag åbnede en ny front men det tog næsten et år for de Allierede at kæmpe sig igennem stærk tysk modstand og nå Berlin","D-dag fejlede militært og de Allierede måtte finde en helt anden strategi for at vinde krigen","De tyske styrker overgav sig øjeblikkeligt på D-dag da de vidste de ikke kunne vinde imod de Allierede","D-dag var kun et symbolsk angreb og den reelle sejr kom udelukkende fra Sovjet-styrkerne i øst"],"correct":"D-dag åbnede en ny front men det tog næsten et år for de Allierede at kæmpe sig igennem stærk tysk modstand og nå Berlin","accepted_answers":["D-dag åbnede en ny front men det tog næsten et år for de Allierede at kæmpe sig igennem stærk tysk modstand og nå Berlin"],"review_text":"D-dag var afgørende men ikke øjeblikkeligt afsluttende. De Allierede kæmpede sig langsomt frem gennem Frankrig og Belgien og ind i Tyskland. Battle of the Bulge i december 1944 viste at Tyskland stadig kunne kæmpe hårdt. Berlin faldt ikke til de Allierede og Sovjet-styrkerne før maj 1945. D-dag er det punkt hvorfra krigen kun gik én vej — men den stoppede ikke den næste dag."}'::jsonb,
  'mc','short','{"concepts":["D-dag","Normandiet","sejrens forløb","krigen slut","misconception-øjeblikkelig-sejr"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_2',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvorfor er det vigtigt at vi stadig husker og underviser i Holocaust i dag?","options":["Fordi forståelse af historiske forbrydelser er den bedste beskyttelse mod at de gentages — og fordi aktiv hukommelse er en del af demokratiets forsvar","Fordi vi bør bruge historien til at bebrejde nutidens tyskere kollektivt for fortiden","Fordi Holocausts ofre kræver personlig skyld hos alle europæere der lever i dag","Fordi historierne primært er interessant underholdning der viser hvor langt civilisationen er kommet"],"correct":"Fordi forståelse af historiske forbrydelser er den bedste beskyttelse mod at de gentages — og fordi aktiv hukommelse er en del af demokratiets forsvar","accepted_answers":["Fordi forståelse af historiske forbrydelser er den bedste beskyttelse mod at de gentages — og fordi aktiv hukommelse er en del af demokratiets forsvar"],"review_text":"Aldrig igen — det er ikke bare en sætning men en forpligtelse. At kende Holocaust: dets opbygning, mekanismer og menneskelige konsekvenser, er at have et redskab til at genkende faresignaler i nutiden. Diskrimination, dehumanisering, syndebuk-logik — det starter altid et sted. Historisk hukommelse er ikke fortid. Det er beskyttelse af fremtiden."}'::jsonb,
  'mc','short','{"concepts":["historisk hukommelse","aldrig-igen","demokrati","forebyggelse","fremtiden","ansvar"],"misconception_type":"scope_confusion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_2',7,4
);
