-- Section 104 — Cold War Band 5 Sprint
-- Creates the second genuine ceiling layer for advanced grade-9 students in cold_war.
-- Prior to this migration cold_war had zero Band 5 questions.
--
-- 20 questions: target_grade=9, difficulty_band=5, domain=cold_war, is_active=true
-- Focus: nuclear deterrence, MAD, proxy wars, Cuban Missile Crisis, ideology vs geopolitics,
--        Soviet collapse, democracy vs authoritarianism, contemporary relevance.
-- No factual recall. Every question requires analytical judgment, evaluation, or synthesis.

-- ─── BAND 5 · NUCLEAR DETERRENCE & MAD (5 questions) ────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er paradokset i den gensidigt sikrede ødelæggelse (MAD) som strategisk stabilisator under den kolde krig?","options":["Paradokset er at stabilitet hviler på den ubetingede vilje til at begå et massemordet der er moralsk monstruøst — freden opretholdes kun fordi begge parter genuint er i stand til og forpligtet til at udslette millioner af civile","MAD er ikke paradoksalt men en simpel og rationel afskrækkelsesteori uden moralske komplikationer","Paradokset er at MAD aldrig var en reel strategi — det var kun en propagandaløgn for at skræmme den egne befolkning","MAD stabiliserede freden fuldstændigt og uden bivirkninger og er dermed det mest succesfulde sikkerhedssystem i historien"],"correct":"Paradokset er at stabilitet hviler på den ubetingede vilje til at begå et massemordet der er moralsk monstruøst — freden opretholdes kun fordi begge parter genuint er i stand til og forpligtet til at udslette millioner af civile","accepted_answers":["Paradokset er at stabilitet hviler på den ubetingede vilje til at begå et massemordet der er moralsk monstruøst — freden opretholdes kun fordi begge parter genuint er i stand til og forpligtet til at udslette millioner af civile"],"review_text":"MAD hvilede på en logik der er grundlæggende pervers: hvis en af parterne nogensinde faktisk BRUGTE sin kapacitet, ville systemet have fejlet totalt. Stabiliteten krævede at begge sider troede på den anden sides villighed til massemord — og at denne tro var gensidig og robust. Filosoffer som Gregory Kavka beskrev dette som en ''paradoxical deterrence'': den moralske legitimitet af selve trusslen er tvivlsom fordi det aldrig ville være rationelt at gennemføre den. Yderligere var systemet afhængigt af fuldstændig rationalitet hos beslutningstagerne — en antagelse der gentagne gange viste sig problematisk."}'::jsonb,
  'mc','short','{"concepts":["MAD","nuklear afskrækkelse","paradoks","massemord","stabilitet","rationalitet"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',5,'auto',true,'cold_war',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Er nuklear afskrækkelse etisk forsvarlig som grundlag for international sikkerhed — og hvad er den stærkeste indvending?","options":["Nej — afskrækkelse hviler på en trussel om massemordet der er moralsk forkert at gennemføre, og strategien overdrager sikkerheden til psykologiske og tekniske systemer der kan fejle, snarere end til politisk og diplomatisk opbygning","Ja — resultatet taler for sig selv: ingen atomkrig siden 1945 er bevis på at systemet er etisk forsvarligt fordi konsekvenserne er gode","Ja — det er etisk at true med atomkrig fordi truslen aldrig behøver at blive gennemført og dermed har ingen moralsk pris","Spørgsmålet er irrelevant fordi stater ikke er moralske aktører og statslig adfærd ikke kan vurderes med etiske begreber"],"correct":"Nej — afskrækkelse hviler på en trussel om massemordet der er moralsk forkert at gennemføre, og strategien overdrager sikkerheden til psykologiske og tekniske systemer der kan fejle, snarere end til politisk og diplomatisk opbygning","accepted_answers":["Nej — afskrækkelse hviler på en trussel om massemordet der er moralsk forkert at gennemføre, og strategien overdrager sikkerheden til psykologiske og tekniske systemer der kan fejle, snarere end til politisk og diplomatisk opbygning"],"review_text":"Den konsekventialistiske forsvar af nuklear afskrækkelse er tillokkende: ingen storkrig i 70 år. Men deontologisk etik peger på at det er moralsk forkert at true med handlinger der ville være moralsk forkerte at gennemføre. Yderligere er det empirisk tvivlsomt om stabilitet skyldtes MAD eller andre faktorer (økonomi, institutioner, diplomatiske kanaler). Historien indeholder mindst seks dokumenterede tilfælde — herunder Stanislav Petrov-episoden 1983 — hvor forkerte data eller menneskelige fejl næsten udløste atomkrig. Sikkerhedssystemet overdrager verdensfreden til teknologisk fejlrate."}'::jsonb,
  'mc','short','{"concepts":["nuklear etik","afskrækkelse","deontologi","konsekventialisme","teknisk fejl","Petrov"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',5,'auto',true,'cold_war',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er den afgørende svaghed ved afskrækkelsesteorien som forklaring på den kolde krigs fredelige udgang?","options":["Teorien forudsætter permanent og fejlfri rationalitet hos begge sider — men de dokumenterede nærved-hændelser viser at afskrækkelsesstabilitet delvist skyldtes held snarere end systemisk rationalitet","Afskrækkelsesteorien fejler fordi ingen af parterne nogensinde faktisk troede på den andens kernevåbenkapacitet","Teorien er korrekt og komplet — rationalitetsantagelsen var velbegrundet fordi alle aktører altid handler rationelt under ekstremt pres","Afskrækkelse var irrelevant for den kolde krig fordi begge magter faktisk ønskede krig men valgte fred af ekonomiske årsager"],"correct":"Teorien forudsætter permanent og fejlfri rationalitet hos begge sider — men de dokumenterede nærved-hændelser viser at afskrækkelsesstabilitet delvist skyldtes held snarere end systemisk rationalitet","accepted_answers":["Teorien forudsætter permanent og fejlfri rationalitet hos begge sider — men de dokumenterede nærved-hændelser viser at afskrækkelsesstabilitet delvist skyldtes held snarere end systemisk rationalitet"],"review_text":"Afskrækkelsesteorien antager at begge parters beslutningstagere altid er rationelle, velinformerede og i kontrol. Dokumenterede nærved-hændelser modsiger dette: 1983 troede Sovjet fejlagtigt at NATO-øvelsen Able Archer var et faktisk angreb og forberedte modangreb. 1962 var en sovjet U-båd under Cubas blokade tæt på at affyre en atombombe — kaptajnen var overbevist om at krig allerede var begyndt. Robert McNamara konkluderede i sin alderdom at Vietnam- og Kuba-lektionerne viste at sund fornuft, held og enkeltpersoners beslutninger var afgørende — ikke systemet."}'::jsonb,
  'mc','short','{"concepts":["afskrækkelse","rationalitetsantagelse","Able Archer","nærved-hændelser","held","McNamara"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',5,'auto',true,'cold_war',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Var atomkapløbet under den kolde krig et resultat af rationel strategi eller strukturel tvang — og hvad er konsekvensen af svaret for forståelsen af sikkerhedspolitik?","options":["Primært strukturel tvang — sikkerhedsdilemmaet tvang begge sider til at opbygge kapaciteten uanset egentlig militær nødvendighed, fordi enhver kapabilitetsfordel hos modparten krævede kompensation. Det indikerer at atomkapløb kan opstå selv uden aggressiv intention","Udelukkende rationel strategi — begge sider beregnede præcist hvad der var nødvendigt og opbyggede præcis denne kapacitet og ikke mere","Kapløbet var primært drevet af industrielle interesser uden strategisk grundlag — militæret og forsvarsindustrien samarbejdede om at opretholde truslen","Svaret er irrelevant for moderne sikkerhedspolitik da atomvåben er forældet teknologi"],"correct":"Primært strukturel tvang — sikkerhedsdilemmaet tvang begge sider til at opbygge kapaciteten uanset egentlig militær nødvendighed, fordi enhver kapabilitetsfordel hos modparten krævede kompensation. Det indikerer at atomkapløb kan opstå selv uden aggressiv intention","accepted_answers":["Primært strukturel tvang — sikkerhedsdilemmaet tvang begge sider til at opbygge kapaciteten uanset egentlig militær nødvendighed, fordi enhver kapabilitetsfordel hos modparten krævede kompensation. Det indikerer at atomkapløb kan opstå selv uden aggressiv intention"],"review_text":"Sikkerhedsdilemmaet er centralt: begge supermagter opbyggede arsenaler langt ud over enhver rationel militær begrundelse — USA og USSR nåede samlet op på over 60.000 kernevåben. Eisenhowers advarsel mod det militærindustrielle kompleks (1961) pegede på at interne politiske og industrielle dynamikker drev opbygningen uafhængigt af strategisk nødvendighed. Det strukturelle argument har stærk moderne relevans: Kinas, Indiens, Pakistans og Nordkoreas kernevåbenprogrammer viser at kapløbsdynamikken kan opstå uden ekspressiv aggressiv intention — blot via gensidigt misforhold og usikkerhed."}'::jsonb,
  'mc','short','{"concepts":["atomkapløb","sikkerhedsdilemma","strukturel tvang","militærindustrielt kompleks","Eisenhower","kapacitetsmatch"],"misconception_type":"causal_inversion","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',5,'auto',true,'cold_war',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er det centrale argument for at NATOs nuklear first-use-politik er etisk problematisk — selv set fra et afskrækkelses-perspektiv?","options":["First-use underminerer afskrækkelsens stabilitet fordi det giver modparten incitament til at ramme først ved kriseoptrappning — og det strider mod distinktionsprincippet da first-use-scenariet næsten nødvendigvis involverer civile mål","First-use er etisk ukontroversielt fordi det er en defensiv strategi der kun aktiveres hvis NATO angribes konventionelt","First-use er strategisk overlegen no-first-use fordi det giver NATO maksimal fleksibilitet og aldrig ville blive brugt","Det er etisk korrekt fordi NATO er et demokratisk forsvarsalliancens og demokratier har moralsk ret til alle defensive midler"],"correct":"First-use underminerer afskrækkelsens stabilitet fordi det giver modparten incitament til at ramme først ved kriseoptrappning — og det strider mod distinktionsprincippet da first-use-scenariet næsten nødvendigvis involverer civile mål","accepted_answers":["First-use underminerer afskrækkelsens stabilitet fordi det giver modparten incitament til at ramme først ved kriseoptrappning — og det strider mod distinktionsprincippet da first-use-scenariet næsten nødvendigvis involverer civile mål"],"review_text":"First-use-politikken er NATOs eksplicitte standpunkt: alliancen forbeholder sig ret til at bruge atomvåben som første mod et konventionelt angreb der truer dens eksistens. Kritikken fra strategisk perspektiv: under en krise med optrappning ved modparten at NATO kan bruge atomer først — dette skaber incitament til selv at ramme præventivt. No-first-use-politikken (Kina, Indien) hævdes at reducere denne dynamik. Etisk er first-use vanskeligt at forene med distinktionsprincippet: et konventionelt angreb mod NATOs territorium ville næppe berettige massemordet på civile der følger af ethvert atomvåbenscenarie."}'::jsonb,
  'mc','short','{"concepts":["first-use","no-first-use","NATO","nuklear etik","distinktionsprincip","krisestabilitet"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',5,'auto',true,'cold_war',9,5
);

-- ─── BAND 5 · PROXY WARS & GEOPOLITIK (4 questions) ─────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Var den kolde krigs proxy-krige primært drevet af ideologisk overbevisning eller geopolitisk magtinteresse — og hvad viser svaret om stormagters reelle motivation?","options":["Primært geopolitisk: begge supermagter støttede regimer der modsagde deres egne demokrati- og frihedsidealer når det tjente strategiske interesser — USA støttede diktaturer i Latinamerika og Mellemøsten, Sovjet støttede nationalister der ikke var marxister","Udelukkende ideologisk: begge magter handlede konsekvent ud fra principper og støttede kun regimer der delte deres ideologiske grundværdier","Primært ideologisk for USA og primært geopolitisk for Sovjet — asymmetrien forklarer at Vesten vandt den kolde krig","Geopolitik og ideologi er identiske begreber i en koldkrigskontekst og distinktionen er analytisk meningsløs"],"correct":"Primært geopolitisk: begge supermagter støttede regimer der modsagde deres egne demokrati- og frihedsidealer når det tjente strategiske interesser — USA støttede diktaturer i Latinamerika og Mellemøsten, Sovjet støttede nationalister der ikke var marxister","accepted_answers":["Primært geopolitisk: begge supermagter støttede regimer der modsagde deres egne demokrati- og frihedsidealer når det tjente strategiske interesser — USA støttede diktaturer i Latinamerika og Mellemøsten, Sovjet støttede nationalister der ikke var marxister"],"review_text":"USA støttede Pinochet i Chile (1973), Mobutu i Zaire, Shah i Iran og Saudi-Arabien — alle regimer der krænkede de liberale principper USA hævdede at forsvare globalt. Sovjet støttede arabisk nationalisme i Egypten og Syrien der ikke var marxistisk men strategisk nyttigt. Begge magter prioriterede allierede der leverede baser, naturressourcer og regional indflydelse over allierede der delte ideologi. Det er en vigtig lektion: staters reelle politik kan afvige markant fra den officielle ideologiske selvforståelse, og demokrati-promotering kan fungere som instrumentaliseret retorik snarere end oprigtigt mål."}'::jsonb,
  'mc','short','{"concepts":["proxy-krige","geopolitik","ideologi","USA","Sovjet","diktaturer","interessebaseret politik"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',5,'auto',true,'cold_war',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er den vigtigste lærdom fra det amerikanske engagement i Vietnam for forståelsen af stormagternes interventionskraft under den kolde krig?","options":["At overlegen militær kapacitet ikke kan kompensere for manglende politisk legitimitet hos den støttede side og manglende forståelse for lokal politisk dynamik — og at containment-doktrinen fejlfortolkede komplekse nationale befrielseskrige som ideologisk monolitiske sovjet-styrede projekter","At USA tabte Vietnam fordi den militære kapacitet var utilstrækkelig og en større troppeindsats ville have ændret udfaldet","At Vietnam beviste at kommunismen er strukturelt uovervindelig i nationalistiske kontekster og at USA aldrig burde have forsøgt indgriben","At lærdommet fra Vietnam er udelukkende teknisk og militært og har ingen bredere politisk relevans"],"correct":"At overlegen militær kapacitet ikke kan kompensere for manglende politisk legitimitet hos den støttede side og manglende forståelse for lokal politisk dynamik — og at containment-doktrinen fejlfortolkede komplekse nationale befrielseskrige som ideologisk monolitiske sovjet-styrede projekter","accepted_answers":["At overlegen militær kapacitet ikke kan kompensere for manglende politisk legitimitet hos den støttede side og manglende forståelse for lokal politisk dynamik — og at containment-doktrinen fejlfortolkede komplekse nationale befrielseskrige som ideologisk monolitiske sovjet-styrede projekter"],"review_text":"Sydvietnam-regeringen manglede folkelig legitimitet — Diems styre var korrupt og elitepræget. Containment-doktrinen antog at alle kommunistiske bevægelser var led i en koordineret sovjet-ledet ekspansion — men den vietnamesiske kommunisme var i høj grad en national frigørelseskamp med rødder i antikolonialisme mod Frankrig. USAs militære overlegenhed (500.000 soldater, massiv bombning) var utilstrækkelig fordi den politiske forudsætning for sejr — en legitim og folkebåret sydvietnamesisk stat — aldrig eksisterede. Lektionen gentages i Irak og Afghanistan."}'::jsonb,
  'mc','short','{"concepts":["Vietnam","containment","politisk legitimitet","antikolonialisme","militær kapacitet","intervention"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',5,'auto',true,'cold_war',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er den langsigtede arv fra den kolde krigs proxy-støtte til islamistiske guerillabevægelser i Afghanistan i 1980erne?","options":["At CIA og Saudi-Arabien uddannede og udrustede mujahedinkrigere som del af Operation Cyclone — og at mange af disse netværk, våben og taktikker sidenhen dannede infrastrukturen for al-Qaeda og Taliban og dermed delvist skabte den trussel USA bekæmpede efter 2001","At støtten var udelukkende humanitær og ikke bidrog til efterfølgende destabilisering","At arven udelukkende er positiv da sovjet-nederlaget i Afghanistan direkte accelererede den kolde krigs afslutning","At forbindelsen mellem CIAs Afghanistan-program og al-Qaeda er en konspirationsteori uden historisk belæg"],"correct":"At CIA og Saudi-Arabien uddannede og udrustede mujahedinkrigere som del af Operation Cyclone — og at mange af disse netværk, våben og taktikker sidenhen dannede infrastrukturen for al-Qaeda og Taliban og dermed delvist skabte den trussel USA bekæmpede efter 2001","accepted_answers":["At CIA og Saudi-Arabien uddannede og udrustede mujahedinkrigere som del af Operation Cyclone — og at mange af disse netværk, våben og taktikker sidenhen dannede infrastrukturen for al-Qaeda og Taliban og dermed delvist skabte den trussel USA bekæmpede efter 2001"],"review_text":"Operation Cyclone (1979-1989) var CIAs største skjulte operation nogensinde og finansierede og trænede afghanske mujahedinkrigere mod den sovjetiske besættelse. Bin Laden var selv aktiv i Afghanistan i 1980erne og profiterede af de netværk der blev opbygget. Taliban opstod fra de pakistanske madrasser der var finansieret som del af anti-sovjet-programmet. Det er et klassisk eksempel på blowback: politikker der opnår kortsigtede geopolitiske mål kan skabe langsigtede sikkerhedstrusler. Zbigniew Brzeziński fortrød aldrig Afghanistan-beslutningen — han mente afslutningen af den kolde krig vejede tungere end de efterfølgende konsekvenser."}'::jsonb,
  'mc','short','{"concepts":["Afghanistan","Operation Cyclone","blowback","al-Qaeda","mujahedin","langsigtede konsekvenser"],"misconception_type":"causal_inversion","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',5,'auto',true,'cold_war',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad illustrerer Koreakrigens status som en konflikt der aldrig fik en fredstraktat om forholdet mellem den kolde krigs bipolaritet og regionale konflikters opløsning?","options":["At den kolde krigs bipolare logik frøs regionale konflikter i en status quo der ikke løste de underliggende spændinger men blot fastholdt dem — Korea er fortsat teknisk i krig og repræsenterer risikoen for at koldkrigs-arrangementer overlever systemets sammenbrud","At manglen på fredstraktat er en administrativ fejl uden realpolitisk konsekvens","At Korea beviser at FN ikke kan løse regionale konflikter og at FN bør nedlægges","At Korea-konflikten er unik og ikke ligner nogen anden koldkrigs-konflikt og derfor ikke kan generalisere til andre tilfælde"],"correct":"At den kolde krigs bipolare logik frøs regionale konflikter i en status quo der ikke løste de underliggende spændinger men blot fastholdt dem — Korea er fortsat teknisk i krig og repræsenterer risikoen for at koldkrigs-arrangementer overlever systemets sammenbrud","accepted_answers":["At den kolde krigs bipolare logik frøs regionale konflikter i en status quo der ikke løste de underliggende spændinger men blot fastholdt dem — Korea er fortsat teknisk i krig og repræsenterer risikoen for at koldkrigs-arrangementer overlever systemets sammenbrud"],"review_text":"Koreakrigen (1950-53) endte med en våbenstilstandsaftale, ikke en fredstraktat — de to Koreaer er teknisk set stadig i krig. Den demilitariserede zone er en af verdens tættest militariserede grænser. Nordkorea har siden 2006 testet atomvåben. Den kolde krigs bipolare orden frøs konflikter ved at gøre stormagtsindgriben mulig men ikke løsning mulig: USA og Kina sikrede begge Koreacars overlevelse men blokerede genforening. En analog dynamik gælder for Taiwan-strædet, Berlin-løsningen og mange andre koldkrigs-opdelinger. Bipolaritetens arv er geopolitiske frysepunkter der fortsat genererer risici."}'::jsonb,
  'mc','short','{"concepts":["Koreakrig","våbenstilstand","bipolaritet","frysepunkter","Nordkorea","arv"],"misconception_type":"scope_confusion","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',5,'auto',true,'cold_war',9,5
);

-- ─── BAND 5 · CUBAS MISSILKRISE (3 questions) ────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad viser Cubas missilkrise i 1962 om forholdet mellem politisk ledelses kvalitet og nuklear sikkerhed?","options":["At individuelle lederes evne til at modstå pres fra militærrådgivere og tænke langsigtet var afgørende — Kennedy og Khrusjtjov fandt begge diplomatiske udveje trods massivt internt pres for militær eskalering","At missilkrisen bekræftede at MAD-systemet automatisk vil stabilisere alle kriser og at ledernes individuelle kvaliteter er irrelevante","At krisen udelukkende var drevet af militær logik og at diplomatisk ledelse ingen rolle spillede","At missilkrisen viste at autoritære beslutningstagere som Khrusjtjov altid handler mere rationelt end demokratiske ledere under pres"],"correct":"At individuelle lederes evne til at modstå pres fra militærrådgivere og tænke langsigtet var afgørende — Kennedy og Khrusjtjov fandt begge diplomatiske udveje trods massivt internt pres for militær eskalering","accepted_answers":["At individuelle lederes evne til at modstå pres fra militærrådgivere og tænke langsigtet var afgørende — Kennedy og Khrusjtjov fandt begge diplomatiske udveje trods massivt internt pres for militær eskalering"],"review_text":"Kennedys ExComm-rådgivere anbefalede luftbombardement eller invasion. Kennedy valgte blokaden og hemmelige forhandlinger. Khrusjtjov modstod internt pres fra hærledelsen der ønskede eskalering. Backchannel-forhandlingerne via John Scali og Aleksandr Fomin åbnede en vej ud som de officielle kanaler ikke kunne. Arkhipov-episoden — en sovjet-ubåds officer der nægtede at godkende affyring af atomtorpedo — viser at enkeltpersoner på lavt niveau ligeså kan være afgørende. Konklusionen: nuklear sikkerhed afhænger af menneskelig dømmekraft på alle niveauer, ikke bare af systemiske strukturer."}'::jsonb,
  'mc','short','{"concepts":["Cubas missilkrise","Kennedy","Khrusjtjov","lederskab","diplomati","Arkhipov","backchannel"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',5,'auto',true,'cold_war',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var den reelle kompromisstruktur der løste Cubas missilkrise — og hvad siger den om forholdet mellem offentlig og hemmelig diplomati?","options":["Sovjet fjernede missilerne fra Cuba mod at USA offentligt forpligtede sig til ikke at invadere Cuba og hemmeligt fjernede Jupiter-missilerne fra Tyrkiet — den hemmelige del muliggjorde aftalen men kunne ikke afsløres offentligt","USA besejrede Sovjet militært og Khrusjtjov trak sig tilbage uden nogen form for kompensation til Sovjet","Aftalen var udelukkende offentlig og Kennedy videreformidlede alle detaljer til den amerikanske befolkning og til allierede","Krisen løstes ved at begge parter indvilligede i fuldstændig atomnedrusting af begge lande"],"correct":"Sovjet fjernede missilerne fra Cuba mod at USA offentligt forpligtede sig til ikke at invadere Cuba og hemmeligt fjernede Jupiter-missilerne fra Tyrkiet — den hemmelige del muliggjorde aftalen men kunne ikke afsløres offentligt","accepted_answers":["Sovjet fjernede missilerne fra Cuba mod at USA offentligt forpligtede sig til ikke at invadere Cuba og hemmeligt fjernede Jupiter-missilerne fra Tyrkiet — den hemmelige del muliggjorde aftalen men kunne ikke afsløres offentligt"],"review_text":"Den faktiske aftale er illustrativ for international diplomati: USA fjernede Jupiter-missilerne fra Tyrkiet indenfor seks måneder — noget Kennedy privat allerede ville have gjort — men dette kunne ikke afsløres offentligt fordi det ville fremstå som kapitulation over for Sovjet. Den offentlige narrativ om en klar amerikansk sejr var delvist fabrikeret: det var et reelt kompromis. Khrusjtjov led dog internt tab af prestige i Sovjet-apparatet og blev delvist afsat bl.a. som konsekvens. Eksemplet viser at international aftaleindgåelse kræver at parterne kan redde ansigt — en nødvendighed der skaber spænding med demokratiets krav om åbenhed."}'::jsonb,
  'mc','short','{"concepts":["missilkrise","Tyrkiet","Jupiter-missiler","hemmelig diplomati","ansigtsredning","kompromis"],"misconception_type":"false_equivalence","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',5,'auto',true,'cold_war',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er den vigtigste konklusion fra Cubas missilkrise for konstruktionen af systemer til krisehåndtering i den nukleare tidsalder?","options":["At direkte kommunikationskanaler, klar eskaleringslogik og mekanismer der beskytter beslutningstagere mod tidspres er afgørende — den røde telefon og efterfølgende risikoreduktionstiltag var direkte reaktioner på krisens nærved-katastrofe","At krisehåndtering kun fungerer via afskrækkelse og at der ikke er behov for kommunikationskanaler da stabilitet automatisk følger af MAD","At krisen bekræftede at FN er den rette aktør til at håndtere alle nukleare kriser og at supermagtsdiplomati er irrelevant","At missilkrisens vigtigste lærdom er at demokratier aldrig bør forhandle med ikke-demokratiske stater"],"correct":"At direkte kommunikationskanaler, klar eskaleringslogik og mekanismer der beskytter beslutningstagere mod tidspres er afgørende — den røde telefon og efterfølgende risikoreduktionstiltag var direkte reaktioner på krisens nærved-katastrofe","accepted_answers":["At direkte kommunikationskanaler, klar eskaleringslogik og mekanismer der beskytter beslutningstagere mod tidspres er afgørende — den røde telefon og efterfølgende risikoreduktionstiltag var direkte reaktioner på krisens nærved-katastrofe"],"review_text":"Den Røde Telefon (Moscow-Washington Direct Communication Link) blev oprettet i august 1963 — direkte som konsekvens af missilkrisens kommunikationsproblemer. Parterne oplevede at forsinkede og fejloversatte beskeder skabte farlig usikkerhed. Efterfølgende tiltag inkluderede Hotline-aftalen (1971), Nuclear Accidents Agreement (1971) og START-traktaterne. Alle var baseret på den erkendelse at krisedynamikken kan eskalere hurtigere end politiske systemer kan reagere rationelt. I dag er problemet at de institutionelle strukturer fra 1960erne ikke er tilpasset nukleare aktører som Nordkorea, Pakistan og Indien der ikke er integrerede i samme kommunikationssystemer."}'::jsonb,
  'mc','short','{"concepts":["rød telefon","krisehåndtering","kommunikationskanaler","eskaleringslogik","tidspres","institutionel læring"],"misconception_type":"scope_confusion","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',5,'auto',true,'cold_war',9,5
);

-- ─── BAND 5 · SOVJET-KOLLAPS & DEMOKRATISK TRANSITION (4 questions) ──────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Var Sovjetunionens kollaps i 1991 primært et resultat af interne systemfejl eller af det vestlige pres fra den kolde krig — og hvad viser svaret om systemers stabilitet?","options":["Primært interne systemfejl: planøkonomiens strukturelle ineffektivitet, nationalistiske spændinger i de 15 SSRer og en informationsøkonomi der ikke fungerede under central styring var afgørende. Det vestlige pres accelererede muligvis kollapset men skabte det ikke","Udelukkende vestligt pres: Reagan-doktrinen og SDI-programmet tvang Sovjet til et kapløb der udmattede dem","Interne og eksterne faktorer er fuldstændigt identiske i forklaringskraft og kan ikke adskilles analytisk","Kollapset var planlagt og strategisk gennemført af Gorbatjov som en bevidst reformstrategi der lykkedes perfekt"],"correct":"Primært interne systemfejl: planøkonomiens strukturelle ineffektivitet, nationalistiske spændinger i de 15 SSRer og en informationsøkonomi der ikke fungerede under central styring var afgørende. Det vestlige pres accelererede muligvis kollapset men skabte det ikke","accepted_answers":["Primært interne systemfejl: planøkonomiens strukturelle ineffektivitet, nationalistiske spændinger i de 15 SSRer og en informationsøkonomi der ikke fungerede under central styring var afgørende. Det vestlige pres accelererede muligvis kollapset men skabte det ikke"],"review_text":"Revisionistiske historikere som Stephen Kotkin og Philip Zelikow peger på at Sovjet-systemets interne fejl var afgørende: planøkonomien kunne ikke håndtere den teknologiske revolution, korruption og informationsskjul gennemsyrede systemet og de ikke-russiske sovjetrepublikker havde voksende nationale identiteter der fungerede som centrifugale kræfter. Olieprisfald i 1980erne ødelagde Sovjet-budgetterne. Reagan-doktrinens betydning er omstridt: de fleste eksperter mener den accelererede en allerede intern bevægelse mod kollaps. Analysen er vigtig fordi den afviser enkle militante forklaringer og peger på systemisk og institutionel årsag."}'::jsonb,
  'mc','short','{"concepts":["Sovjet-kollaps","planøkonomi","nationalisme","systemfejl","Reagan","interne årsager"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',5,'auto',true,'cold_war',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad forklarer at Østeuropa relativt hurtigt demokratiserede efter 1989 mens Rusland og de fleste post-sovjet stater ikke lykkedes med varig demokratisering?","options":["EUs og NATOs udvidelsesperspektiv fungerede som institutionel anker der skabte incitamenter og betingelser for demokratisk konsolidering i Østeuropa — mens Rusland og CIS-landene manglede denne eksterne trækmotor og udviklede hybridregimer","Østeuropæere er kulturelt mere demokratisk indstillede end russere og centralasiatere og kulturforskellen forklarer alene udfaldet","Rusland valgte aktivt autoritarisme fordi Putin er en diktator — demokratiseringsfejlen er personlighedsbaseret og ikke strukturel","Demokratisering lykkedes i Østeuropa fordi USA invaderede og påtvang demokrati via militær tilstedeværelse"],"correct":"EUs og NATOs udvidelsesperspektiv fungerede som institutionel anker der skabte incitamenter og betingelser for demokratisk konsolidering i Østeuropa — mens Rusland og CIS-landene manglede denne eksterne trækmotor og udviklede hybridregimer","accepted_answers":["EUs og NATOs udvidelsesperspektiv fungerede som institutionel anker der skabte incitamenter og betingelser for demokratisk konsolidering i Østeuropa — mens Rusland og CIS-landene manglede denne eksterne trækmotor og udviklede hybridregimer"],"review_text":"Demokratiseringsforsker Lucan Way og Steven Levitsky viser at den vigtigste prædiktor for vellykket demokratisering i post-sovjet-lande var tilknytning til EU. Polen, Tjekkiet, Ungarn og de baltiske lande konsoliderede demokratiet delvist fordi EU-medlemskab krævede institutionelle reformer, retsstatsgarantier og antikorruption. Ukraine illustrerer spændingen: orientering mod EU (Maidan 2014) vs. russisk indflydelsessfære. Rusland, Kasakhstan og Hviderusland manglede dette ankerpunkt. Analysen er kritisk for samtiden: Ungarns demokratiske regression siden 2010 viser at EUs trækmotor ikke er ubegrænset når et land allerede er medlem."}'::jsonb,
  'mc','short','{"concepts":["demokratisering","EU-udvidelse","institutionel anker","post-sovjet","hybridregime","Østeuropa"],"misconception_type":"causal_inversion","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',5,'auto',true,'cold_war',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er den vigtigste evaluering af Mikhail Gorbatjovs historiske rolle — reformator der frigjorde kræfter han ikke kunne kontrollere eller statsmand der bevidst afviklede et uretfærdigt system?","options":["Han var primært en systemreformator der fejlberegnede: glasnost og perestrojka skulle redde Sovjet-systemet ikke afskaffe det — men reformerne frigjorde kræfter der oversteg hans kontrol og kulminerede i et sammenbrud han ikke planlagde","Han var en bevidst demokratisk statsmand der målrettet nedlagde det sovjet-imperium han selv styrede","Han var en svag leder hvis fejl udelukkende skyldtes mangel på personlig beslutsomhed — en stærkere leder ville have reddet Sovjet","Han havde ingen indflydelse på Sovjet-kollapset og var blot et instrument for de historiske kræfter der allerede var i bevægelse"],"correct":"Han var primært en systemreformator der fejlberegnede: glasnost og perestrojka skulle redde Sovjet-systemet ikke afskaffe det — men reformerne frigjorde kræfter der oversteg hans kontrol og kulminerede i et sammenbrud han ikke planlagde","accepted_answers":["Han var primært en systemreformator der fejlberegnede: glasnost og perestrojka skulle redde Sovjet-systemet ikke afskaffe det — men reformerne frigjorde kræfter der oversteg hans kontrol og kulminerede i et sammenbrud han ikke planlagde"],"review_text":"Gorbatjov er et eksempel på reformatorens dilemma: halv-reformer kan undergrave et system uden at konsolidere et nyt. Glasnost (åbenhed) løsnede informationskontrollen og muliggjorde kritisk debat — men skabte også rum for nationalistiske bevægelser i SSRerne. Perestrojka (omstrukturering) decentraliserede økonomierne men skabte kaos snarere end velfungerende markeder. Gorbatjov nægtede at bruge militær magt mod de baltiske republikkerne i 1991 — en afgørende beslutning der adskiller ham fra sine forgængere. Han ønskede et reformeret Sovjet-union, ikke opløsning. Historiens ironi er at hans største bedrift — fred og et fredeligt imperiums endeligt — ikke var hans eksplicitte mål."}'::jsonb,
  'mc','short','{"concepts":["Gorbatjov","glasnost","perestrojka","reformatorens dilemma","Sovjet-kollaps","historisk rolle"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',5,'auto',true,'cold_war',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Var den kolde krigs afslutning i 1989-1991 et resultat af vestlig strategi, sovjet-systemets indre sammenbrud eller af folkelig mobilisering i Østeuropa?","options":["Alle tre faktorer bidrog men folkelig mobilisering — Solidarność i Polen, Velvet Revolution i Tjekkiet, Murens fald — var den direkte katalysator der omsatte systemsvaghed og vestlig strategi til konkrete forandringer","Udelukkende vestlig strategi: Reagan-doktrinen og SDI tvang Sovjet til kollaps via militær og ekonomisk udmattelse","Udelukkende indre sammenbrud: Sovjet ville være imploderet uanset enhver ekstern faktor og folkelig modstand var irrelevant","Den kolde krig sluttede primært fordi Kinas stigende magt tvang begge supermagter til at samarbejde"],"correct":"Alle tre faktorer bidrog men folkelig mobilisering — Solidarność i Polen, Velvet Revolution i Tjekkiet, Murens fald — var den direkte katalysator der omsatte systemsvaghed og vestlig strategi til konkrete forandringer","accepted_answers":["Alle tre faktorer bidrog men folkelig mobilisering — Solidarność i Polen, Velvet Revolution i Tjekkiet, Murens fald — var den direkte katalysator der omsatte systemsvaghed og vestlig strategi til konkrete forandringer"],"review_text":"Monokausal forklaring er utilstrækkelig. Sovjet-systemets structurelle svaghed (planøkonomi, informationsproblemer) var nødvendig betingelse. Vestlig strategi og det politisk-teknologiske pres bidrog. Men den direkte katalysator var folkelig mobilisering: Solidarność i Polen fra 1980, borgerbevægelserne i DDR, Tjekkiet og Rumænien i 1989. Gorbatjovs beslutning om ikke at bruge militær magt — i modsætning til 1956 og 1968 — muliggjorde disse bevægelsers succes. Det er den vigtigste af lektionerne: strukturelle og strategiske faktorer skaber muligheder men folk — i ordets bogstaveligste forstand — foretager de afgørende valg."}'::jsonb,
  'mc','short','{"concepts":["kold krigs afslutning","Solidarność","folkelig mobilisering","Murens fald","Gorbatjov","multikausalt"],"misconception_type":"causal_inversion","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',5,'auto',true,'cold_war',9,5
);

-- ─── BAND 5 · IDEOLOGI, DEMOKRATI VS. AUTORITARISME & AKTUALITET (4 questions) ─

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er den vigtigste indvending mod Francis Fukuyamas tese om historiens afslutning — at liberal demokrati er historiens endelige politiske form?","options":["At liberal demokrati ikke er universelt triumferende: Kinas vækst under autoritarisme, demokratisk regression i Ungarn, Tyrkiet og Rusland og populismens globale fremvækst viser at den liberale demokratiske model ikke har elimineret alternativerne","At Fukuyamas tese er fuldstændig korrekt: demokratier er den dominerende styreform og ingen alternative systemer har reel fremtid","At Fukuyamas tese fejler fordi kommunismen faktisk er bedre end liberal demokrati og vil vende tilbage som dominerende form","At historiens afslutning er en sociologisk kendsgerning og ikke en normativ påstand og dermed er hverken korrekt eller forkert"],"correct":"At liberal demokrati ikke er universelt triumferende: Kinas vækst under autoritarisme, demokratisk regression i Ungarn, Tyrkiet og Rusland og populismens globale fremvækst viser at den liberale demokratiske model ikke har elimineret alternativerne","accepted_answers":["At liberal demokrati ikke er universelt triumferende: Kinas vækst under autoritarisme, demokratisk regression i Ungarn, Tyrkiet og Rusland og populismens globale fremvækst viser at den liberale demokratiske model ikke har elimineret alternativerne"],"review_text":"Fukuyama (1989, 1992) argumenterede at liberal demokrati er den endelige politiske form fordi det er den eneste der løser modernitetens krav om anerkendelse og materiel velfærd. Argumentet syntes bekræftet af 1989-91. Men Kina viste at et autoritært system kan levere høj vækst over årtier uden demokratisering. Den tredje demokratiseringsbølges tilbagegang — Freedom House rapporterer sammenhængende demokratisk regression siden 2006 — og populismens fremvækst i etablerede demokratier viser at den liberale demokratiske orden er under pres. Fukuyama selv har modificeret sine konklusioner. Tesen er ikke forkert men for triumferende og undervurderede autoritarismens adaptionsevne."}'::jsonb,
  'mc','short','{"concepts":["Fukuyama","historiens afslutning","demokratisk regression","autoritarisme","Kina","populisme"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',5,'auto',true,'cold_war',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad forklarer at det internationale system efter den kolde krigs afslutning ikke skabte en varig liberal verdensorden men i stedet udviklede sig mod stigende stormagt-konkurrence?","options":["NATOs østudvidelse, den amerikanske unilateralisme efter 2001 og Kinas fremvækst skabte alle motivationer for Rusland og Kina til at udfordre den regelbaserede orden — mens Vesten antog at markedsintegration automatisk ville producere demokratisering","Den liberale verdensorden mislykkedes fordi kommunisme er permanent stærkere end liberalisme","Det internationale system fungerer faktisk som en stabil liberal verdensorden og udfordringerne er blot overfladiske og forbigående","NATOs sammenbrud var den primære årsag til international ustabilitet efter den kolde krig"],"correct":"NATOs østudvidelse, den amerikanske unilateralisme efter 2001 og Kinas fremvækst skabte alle motivationer for Rusland og Kina til at udfordre den regelbaserede orden — mens Vesten antog at markedsintegration automatisk ville producere demokratisering","accepted_answers":["NATOs østudvidelse, den amerikanske unilateralisme efter 2001 og Kinas fremvækst skabte alle motivationer for Rusland og Kina til at udfordre den regelbaserede orden — mens Vesten antog at markedsintegration automatisk ville producere demokratisering"],"review_text":"Den liberale orden-antagelse var at integration i det globale marked ville producere demokratisering — en antagelse der modsagdes af Kinas post-WTO-udvikling. John Mearsheimers realistiske kritik: USA gik fra unipolær dominans i 1990erne til konfrontation med styrkede Rusland og Kina fordi NATO-udvidelse og aggressiv liberalpolitik skabte sikkerhedsdilemmaer der drev Rusland og Kina tættere. Irak-invasionen 2003 underminerede den regelbaserede ordens moralske autoritet. Ukrainekrigen 2022 er et direkte produkt af disse spændinger. Analytikere er dybt uenige om skylden men er enige om at den unipolære optimisme var fejlberegnet."}'::jsonb,
  'mc','short','{"concepts":["liberal verdensorden","NATO-udvidelse","stormagt-konkurrence","markedsintegration","demokratisering","rebalancering"],"misconception_type":"causal_inversion","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',5,'auto',true,'cold_war',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er det stærkeste argument for at den kolde krigs nuklear-erfaringer er relevante for den nukleare risiko i det 21. århundrede — og hvad er det stærkeste modargument?","options":["For relevans: eskaleringslogikker, kommunikationsproblemer og menneskelig fejlrate er universelle og gælder for nye nukleare aktører som Nordkorea og Pakistan. Mod relevans: bipolar afskrækkelsesstabilitet forudsætter to rationelle aktører — multipolær og regional nuklear dynamik er strukturelt anderledes","For relevans: alle nukleare staters ledere har læst de samme doktriner og handler identisk. Mod relevans: teknologien er forældet og moderne nukleare systemer kan ikke fejle","For relevans: den kolde krig sluttede fredeligt og beviser at nuklear afskrækkelse altid virker. Mod relevans: problemet er løst af international lov","For relevans: Rusland og USA stadig har de fleste atomvåben og 1960ernes aftaler gælder fortsat fuldt ud. Mod relevans: Kina er for lille en aktør til at udgøre en reel risiko"],"correct":"For relevans: eskaleringslogikker, kommunikationsproblemer og menneskelig fejlrate er universelle og gælder for nye nukleare aktører som Nordkorea og Pakistan. Mod relevans: bipolar afskrækkelsesstabilitet forudsætter to rationelle aktører — multipolær og regional nuklear dynamik er strukturelt anderledes","accepted_answers":["For relevans: eskaleringslogikker, kommunikationsproblemer og menneskelig fejlrate er universelle og gælder for nye nukleare aktører som Nordkorea og Pakistan. Mod relevans: bipolar afskrækkelsesstabilitet forudsætter to rationelle aktører — multipolær og regional nuklear dynamik er strukturelt anderledes"],"review_text":"Den kolde krigs afskrækkelsestori er bygget på bipolær stabilitet: to rationelle aktører med symmetrisk kapacitet. Moderne nukleare risici er multipolare: ni nukleare stater, inkl. Pakistan og Indien der har uløste territoriale konflikter, og Nordkorea hvis ledelses rationalitetsantagelse er tvivlsom. Det bilaterale afskrækkelsessystem fungerede trods nærved-hændelser fordi begge parter havde stærke incentiver til at undgå krig. I et multipolært scenarie er eskaleringslogikkerne mere komplekse og de koldkrigs-opbyggede kommunikationskanaler eksisterer ikke for alle aktørpar. Erfaringerne er relevante som advarsel men ikke som en tilstrækkelig model."}'::jsonb,
  'mc','short','{"concepts":["nuklear risiko","multipolaritet","Nordkorea","Pakistan","bipolær afskrækkelse","moderne relevans"],"misconception_type":"scope_confusion","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',5,'auto',true,'cold_war',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad viser den kolde krigs historiske forløb om forholdet mellem demokrati og fred — den såkaldte demokratiske fredsteori?","options":["Den kolde krig giver begrænset støtte: demokratier førte ikke storkrig mod hinanden men bekrigede aktivt ikke-demokratiske stater og støttede diktatorer der tjente geopolitiske interesser. Teorien er sandsynligvis sand for demokrati-par men understøtter ikke at demokratier altid fremmer fred generelt","Den kolde krig bekræfter fuldstændigt at demokratier aldrig fører krig og at demokratiudbredelse er den sikre vej til verdensfred","Den kolde krig afviser demokratisk fredsteori fordi USA og USSR aldrig kæmpede direkte mod hinanden","Demokratisk fredsteori er empirisk korrekt og det betyder at demokrati er det eneste politiske system der kan legitimt give mulighed for statsmæssig magtudøvelse"],"correct":"Den kolde krig giver begrænset støtte: demokratier førte ikke storkrig mod hinanden men bekrigede aktivt ikke-demokratiske stater og støttede diktatorer der tjente geopolitiske interesser. Teorien er sandsynligvis sand for demokrati-par men understøtter ikke at demokratier altid fremmer fred generelt","accepted_answers":["Den kolde krig giver begrænset støtte: demokratier førte ikke storkrig mod hinanden men bekrigede aktivt ikke-demokratiske stater og støttede diktatorer der tjente geopolitiske interesser. Teorien er sandsynligvis sand for demokrati-par men understøtter ikke at demokratier altid fremmer fred generelt"],"review_text":"Den demokratiske fredsteori (Kant, Doyle, Russett) påstår at liberale demokratier ikke fører krig mod hinanden — og den empiriske rekord er faktisk imponerende: ingen krig mellem etablerede liberale demokratier siden 1945. Men den kolde krig viser teoriens grænser: USA invaderede Grenada (1983), støttede Pinochets kup i Chile (1973), deltog i Koreakrigens massecivilbombing og i Vietnamkrigen. At demokratier er fredelige over for andre demokratier udelukker ikke aggressiv adfærd over for ikke-demokratier. Teorien beskriver et mønster der er statistisk solidt men politisk misbrugeligt som begrundelse for regimeskifte."}'::jsonb,
  'mc','short','{"concepts":["demokratisk fredsteori","demokrati og krig","kold krig","USA","proxy-krige","Kant"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}'::jsonb,
  'mc_single',5,'auto',true,'cold_war',9,5
);;
