-- Section 115 — Prehistoric Denmark Band 4 Strengthening Sprint
-- Prior to this migration prehistoric_denmark had only 4 Band 4 questions (minimum for Band 5 readiness is 10).
-- This migration adds 6 Band 4 questions to bring the total to 10.
--
-- 6 questions: target_grade=4, difficulty_band=4, domain=prehistoric_denmark, is_active=true
-- Distribution: Kildefortolkning(2) + Historisk betydning(2) + Evaluering & moderne relevans(2)
-- Grade 4 readability. Concrete vocabulary. Short sentences.
-- Uses dollar-quoting ($$) throughout to avoid apostrophe escaping issues.

-- ─── BAND 4 · KILDEFORTOLKNING (2 questions) ─────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad kan moseligene fortælle os — og hvad kan de IKKE fortælle os?","options":["Vi kan se udseende, alder og hvad de spiste til sidst. Men vi kan ikke vide hvad de tænkte, hvad de troede på eller om de var lykkelige — arkæologer kan læse fysiske spor men ikke tanker og følelser","Moseligene kan fortælle os alt om forhistorisk liv — der er ingen grænser for hvad vi kan lære af dem","Moseligene kan slet ikke fortælle os noget nyttigt — de er kun nysgerrige tilfældige fund","Vi kan kun se hvad de spiste — kroppen fortæller os ingenting andet"],"correct":"Vi kan se udseende, alder og hvad de spiste til sidst. Men vi kan ikke vide hvad de tænkte, hvad de troede på eller om de var lykkelige — arkæologer kan læse fysiske spor men ikke tanker og følelser","accepted_answers":["Vi kan se udseende, alder og hvad de spiste til sidst. Men vi kan ikke vide hvad de tænkte, hvad de troede på eller om de var lykkelige — arkæologer kan læse fysiske spor men ikke tanker og følelser"],"review_text":"Tollandmanden har bevaret ansigt, hud og maveindhold. Vi ved præcis hvad han spiste til sin sidste middag. Vi ved han var ca. 30-40 år gammel. Men vi ved ikke om han var bange, glad eller om han forstod hvad der skete med ham. Fysiske spor giver fysisk viden. Det indre liv er for altid skjult for os."}$$::jsonb,
  'mc','short',$${"concepts":["moseleg","kildefortolkning","epistemologi","grænser for viden","Tollandmanden"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"prehistoric_denmark"}$$::jsonb,
  'mc_single',4,'auto',true,'prehistoric_denmark',4,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvorfor ved vi meget mere om rige end om fattige mennesker i forhistorisk Danmark?","options":["Fordi de rige fik store grave med mange ting der overlever i tusindvis af år — fattige folk blev begravet enkelt og der er næsten ingen spor tilbage","Fordi de rige var vigtigere mennesker og fortjente at blive husket bedre","Fordi der ikke var fattige folk i forhistorien — alle var rige","Fordi arkæologer bevidst kun er interesserede i rige mennesker og ignorerer de fattige"],"correct":"Fordi de rige fik store grave med mange ting der overlever i tusindvis af år — fattige folk blev begravet enkelt og der er næsten ingen spor tilbage","accepted_answers":["Fordi de rige fik store grave med mange ting der overlever i tusindvis af år — fattige folk blev begravet enkelt og der er næsten ingen spor tilbage"],"review_text":"En stor gravhøj med bronzevåben og smykker holder i 3.000 år. En simpel jordbegravelse uden genstande forsvinder fuldstændig. Det er ikke arkæologernes valg — det er hvad materialer der overlever. Det betyder at den forhistorie vi kender bedst er elitens historie. De allerfleste forhistoriske danskere er usynlige for os."}$$::jsonb,
  'mc','short',$${"concepts":["bevaringsbias","sociale klasser","grave","arkæologi","elitens historie"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"prehistoric_denmark"}$$::jsonb,
  'mc_single',4,'auto',true,'prehistoric_denmark',4,4
);

-- ─── BAND 4 · HISTORISK BETYDNING (2 questions) ──────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Flint, bronze, jern og landbrug — hvilken forandring var den vigtigste og hvorfor?","options":["Landbruget var den dybeste forandring fordi det ændrede alt på én gang: hvad folk spiste, hvor de boede, hvor mange de var og hvordan samfundet var bygget op. De andre forandringer var vigtige men de byggede ovenpå landbrugets fundament","Jernet var det vigtigste fordi det var det nyeste og stærkeste metal af dem alle","Flint var det vigtigste fordi det kom først og alle andre opdagelser byggede direkte videre på det","Alle forandringerne var præcis lige vigtige og det er umuligt at rangere dem"],"correct":"Landbruget var den dybeste forandring fordi det ændrede alt på én gang: hvad folk spiste, hvor de boede, hvor mange de var og hvordan samfundet var bygget op. De andre forandringer var vigtige men de byggede ovenpå landbrugets fundament","accepted_answers":["Landbruget var den dybeste forandring fordi det ændrede alt på én gang: hvad folk spiste, hvor de boede, hvor mange de var og hvordan samfundet var bygget op. De andre forandringer var vigtige men de byggede ovenpå landbrugets fundament"],"review_text":"Landbruget er fundamentet. Uden fast bopæl er der intet behov for store redskabslagre eller kornlagre. Uden overskud af mad er der ingen specialiserede håndværkere. Bronze- og jernalderens teknologiske fremskridt var mulige fordi landbruget allerede havde skabt faste samfund. Rækkefølgen af årsag og virkning starter med markerne."}$$::jsonb,
  'mc','short',$${"concepts":["landbrug","teknologi","rangordning","årsag-virkning","historisk betydning"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"prehistoric_denmark"}$$::jsonb,
  'mc_single',4,'auto',true,'prehistoric_denmark',4,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Bronzelurerne fra Bronzealderen er smukt udformede musikinstrumenter der kræver præcis støbning. Hvad fortæller det os om bronzealdersfolkene?","options":["At de ikke bare overlevede — de havde tid og ressourcer til musik og skønhed. Det viser et samfund med overskud og kulturelt liv ud over det strengt nødvendige","At alle i Bronzealderen udelukkende var musikere og ikke lavede andet arbejde","At de kopierede instrumenterne fra Sydeuropa uden selv at forstå hvad de lavede","At de tilfældigt støbte disse former og ikke vidste at det var musikinstrumenter"],"correct":"At de ikke bare overlevede — de havde tid og ressourcer til musik og skønhed. Det viser et samfund med overskud og kulturelt liv ud over det strengt nødvendige","accepted_answers":["At de ikke bare overlevede — de havde tid og ressourcer til musik og skønhed. Det viser et samfund med overskud og kulturelt liv ud over det strengt nødvendige"],"review_text":"En bronzelur kræver avanceret metalstøbning, musikalsk forståelse og en kultur der sætter pris på musik. Det er bevis for at disse folk ikke levede fra hånden til munden. De havde tid og overskud til kunst og kultur. Det passer slet ikke med billedet af primitive mennesker der bare kæmper for at overleve."}$$::jsonb,
  'mc','short',$${"concepts":["bronzelur","kultur","overskud","sofistikering","Bronzealder"],"misconception_type":"scope_confusion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"prehistoric_denmark"}$$::jsonb,
  'mc_single',4,'auto',true,'prehistoric_denmark',4,4
);

-- ─── BAND 4 · EVALUERING & MODERNE RELEVANS (2 questions) ────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvis man kalder forhistoriske folk for primitive — hvad afslører det ord så om os selv?","options":["Ordet viser at vi rangordner historiske perioder som dårligere til bedre — men forhistoriske folk løste alle de problemer de stod over for. Ordet siger mere om vores selvoptagethed end om dem","Ordet er præcist og nyttigt fordi forhistoriske folk faktisk var underlegne mennesker på alle måder","Ordet er bare et neutralt fagbegreb uden nogen holdning bag sig","Det er korrekt at kalde dem primitive — det er bare fakta at de vidste færre ting end vi gør"],"correct":"Ordet viser at vi rangordner historiske perioder som dårligere til bedre — men forhistoriske folk løste alle de problemer de stod over for. Ordet siger mere om vores selvoptagethed end om dem","accepted_answers":["Ordet viser at vi rangordner historiske perioder som dårligere til bedre — men forhistoriske folk løste alle de problemer de stod over for. Ordet siger mere om vores selvoptagethed end om dem"],"review_text":"En stenalderbonde der overlever en hård skandinavisk vinter besidder viden om planter, vejr, dyr og håndværk som de fleste mennesker i dag mangler totalt. De var ikke primitive — de var eksperter på det liv de levede. Når vi kalder dem primitive, siger vi egentlig bare at nutiden er bedre. Det er en holdning, ikke et faktum."}$$::jsonb,
  'mc','short',$${"concepts":["primitiv","sproglig bevidsthed","perspektiv","rangordning","historisk forståelse"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"prehistoric_denmark"}$$::jsonb,
  'mc_single',4,'auto',true,'prehistoric_denmark',4,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad fortæller det os om menneskers natur at forhistoriske danskere handlede med folk tusindvis af kilometer borte — selv uden biler, skrift eller telefoner?","options":["At kontakt, nysgerrighed og handel er grundlæggende menneskelige egenskaber — ikke moderne opfindelser. Mennesker har altid søgt forbindelser ud over deres nærmeste kreds","At det var rent tilfældigt og ikke udtryk for nogen bestemt menneskelig egenskab","At forhistoriske folk var mere intelligente end os fordi de klarede det helt uden teknologi","At handel i forhistorien var sjælden og kun skete i desperate nødsituationer"],"correct":"At kontakt, nysgerrighed og handel er grundlæggende menneskelige egenskaber — ikke moderne opfindelser. Mennesker har altid søgt forbindelser ud over deres nærmeste kreds","accepted_answers":["At kontakt, nysgerrighed og handel er grundlæggende menneskelige egenskaber — ikke moderne opfindelser. Mennesker har altid søgt forbindelser ud over deres nærmeste kreds"],"review_text":"Ravvejen strakte sig fra Danmarks kyster ned til Middelhavet. Det krævede mellemmænd, tillid til fremmede og handel over generationer. Det er ikke særligt moderne — det er dybt menneskeligt. Globalisering er ikke en ny opfindelse. Den menneskelige trang til forbindelser og handel er tusindvis af år gammel."}$$::jsonb,
  'mc','short',$${"concepts":["handel","menneskelig natur","ravvejen","forbindelser","moderne relevans"],"misconception_type":"temporal_confusion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"prehistoric_denmark"}$$::jsonb,
  'mc_single',4,'auto',true,'prehistoric_denmark',4,4
);
