INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvorfor var handel ofte mere indbringende for vikinger end plyndring?","options":["Handel skabte vedvarende netværk og gentagende indkomst mens plyndring var uforudsigelig og satte vikingerne i direkte konfrontation med forsvarsstyrker — handelsruter som Volgahandelen med Byzans og arabiske markeder genererede rigdom over årtier","Plyndring var altid mere indbringende end handel fordi man fik varerne gratis og risikoen var minimal","Vikingerne opgav plyndring fordi den katolske kirke forbød angreb på kristne samfund under trussel om bannlysning","Handel var lettere end plyndring fordi det ikke krævede de samme skibsfærdigheder og navigationskendskab"],"correct":"Handel skabte vedvarende netværk og gentagende indkomst mens plyndring var uforudsigelig og satte vikingerne i direkte konfrontation med forsvarsstyrker — handelsruter som Volgahandelen med Byzans og arabiske markeder genererede rigdom over årtier","accepted_answers":["Handel skabte vedvarende netværk og gentagende indkomst mens plyndring var uforudsigelig og satte vikingerne i direkte konfrontation med forsvarsstyrker — handelsruter som Volgahandelen med Byzans og arabiske markeder genererede rigdom over årtier"],"review_text":"Vikingetidens handelsnetværk strakte sig fra Skandinavien til Byzans og arabiske markeder. Vikingerne handlede med pels, rav, slaver og hvaltand mod sølv, silke og krydderier. Volgahandelen bragte arabiske dirham-mønter til Skandinavien i enorme mængder — møntfundene i skandinaviske skattefund dokumenterer dette direkte. Hedeby (ved Slesvig) og Birka (Sverige) var store internationale handelsbyer. Handel krævede præcis de samme færdigheder som plyndring — erfarne sømænd og navigationskendskab — men handelspartnerne forblev samarbejdsvillige fremover, mens plyndringsofre slog tilbage og befæstede sig. Det ensidige billede af vikingen som primært plyndrer dækker over at handel faktisk var den mest bæredygtige kilde til velstand."}$$::jsonb,
  'mc','short',$${"concepts":["handel","plyndring","Volgahandelen","Hedeby","arabiske dirham","handelsnetværk"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"analytical_challenge","domain":"vikings"}$$::jsonb,
  'mc_single',4,'auto',true,'vikings',8,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvorfor lykkedes vikingetidens bosættelse på Island men ikke i Vinland (Nordamerika)?","options":["Island var nærmest ubeboet ved nordboernes ankomst og havde tilstrækkelige ressourcer til at bære en bofæstet befolkning, mens Vinland allerede var befolket af indfødte folk der effektivt modstod nordboerne og bosættelsen var for isoleret til at modtage forstærkning","Nordboerne foretrak altid koldt klima og ville ikke bosætte sig permanent i det varmere Vinland","Vinland mislykkedes fordi jordbunden var for blød til nordisk landbrug og nordboerne kendte ikke til lokale afgrøder","Island lykkedes fordi irske munke allerede havde ryddet og kultiveret landet inden vikingernes ankomst"],"correct":"Island var nærmest ubeboet ved nordboernes ankomst og havde tilstrækkelige ressourcer til at bære en bofæstet befolkning, mens Vinland allerede var befolket af indfødte folk der effektivt modstod nordboerne og bosættelsen var for isoleret til at modtage forstærkning","accepted_answers":["Island var nærmest ubeboet ved nordboernes ankomst og havde tilstrækkelige ressourcer til at bære en bofæstet befolkning, mens Vinland allerede var befolket af indfødte folk der effektivt modstod nordboerne og bosættelsen var for isoleret til at modtage forstærkning"],"review_text":"Island var da vikingerne ankom ca. 874 e.Kr. nærmest folketomt — kun irske munke (papar) opholdt sig der kortvarigt. Første bosætter var ifølge traditionen Ingólfr Arnarson. Øen havde god fiskebestand, græsningsarealer og ingen fjendtlige naboer. Vinland (sandsynligvis Newfoundland, Canada) var derimod befolket af folk nordboerne kaldte skrælinger — formentlig Beothuk eller algonquin-folk. L'Anse aux Meadows i Newfoundland er den eneste arkæologisk bekræftede normanniske bosættelse i Nordamerika og dateres til ca. 1000 e.Kr. Sagaerne om Eirik den Røde og Leif Eriksson beskriver vedvarende konflikter med skrælinger som den afgørende årsag til opgøret ca. 1010 e.Kr. Den lille koloni manglede simpelthen forstærkning nok fra Island eller Grønland til at fastholde territoriet."}$$::jsonb,
  'mc','short',$${"concepts":["Island","Vinland","L'Anse aux Meadows","skrælinger","nordatlantisk bosættelse","Leif Eriksson"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"analytical_challenge","domain":"vikings"}$$::jsonb,
  'mc_single',4,'auto',true,'vikings',8,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvorfor konverterede skandinaviske konger til kristendommen i vikingetiden?","options":["Kristendommen gav skandinaviske konger adgang til kirkens administrative netværk, skriftkulturen og forbindelser til europæiske kongehuse — det styrkede kongens position over lokale høvdinge og legitimerede centraliseret magt","Skandinaviske konger konverterede fordi de fik åbenbaringer og troede at den kristne gud var stærkere end Odin og Thor","Paven truede med at invadere Skandinavien med den tyske kejsers hær hvis kongerne ikke konverterede inden en given frist","Kristendommen var billigere at praktisere end nordisk religion fordi den ikke krævede dyre dyreofringer og tempelbygninger"],"correct":"Kristendommen gav skandinaviske konger adgang til kirkens administrative netværk, skriftkulturen og forbindelser til europæiske kongehuse — det styrkede kongens position over lokale høvdinge og legitimerede centraliseret magt","accepted_answers":["Kristendommen gav skandinaviske konger adgang til kirkens administrative netværk, skriftkulturen og forbindelser til europæiske kongehuse — det styrkede kongens position over lokale høvdinge og legitimerede centraliseret magt"],"review_text":"Harald Blåtand af Danmark konverterede ca. 965 e.Kr. og lod opføre de store Jellingstene — den ene med teksten 'Harald som vandt sig hele Danmark og Norge og gjorde danerne kristne'. Konversionens politiske dimension er afgørende: kirkens administration (bisper, præster, klostre) gav kongen loyale embedsmænd der ikke var bundet af æt-loyaliteter til lokale høvdinge. Skriftkulturen muliggjorde lovsamlinger, breve og administrative dokumenter. Forbindelser til det frankiske og tyske kongehus via kristen alliancepolitik gav diplomatisk status og handelsfordele. Norges Olav Haraldsson (den Hellige, d. 1030) brugte aktivt kristendommen som statsbyggerredskab. Konversionerne var sjældent primært religiøse — de var bevidste politiske strategibeslutninger med dybtgående konsekvenser for magtfordelingen."}$$::jsonb,
  'mc','short',$${"concepts":["kristendom","konversion","Harald Blåtand","Jellingstene","kirkeadministration","statsopbygning"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"analytical_challenge","domain":"vikings"}$$::jsonb,
  'mc_single',4,'auto',true,'vikings',8,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvordan ændrede fremvæksten af stærkere skandinaviske konger det vikingetidens samfund?","options":["Stærkere konger begrænsede gradvist lokale høvdingers selvstændighed ved at indføre mere ensartet lovgivning og skatteindkrævning — det transformerede løst forbundne stammestyrker til tidlige stater og drev mange høvdinge til at søge nye muligheder på vikingetogt i udlandet","Stærkere konger betød at thing-forsamlingerne øjeblikkeligt ophørte og al beslutningstagning lå hos kongen alene fra det øjeblik han overtog magten","Kongernes voksende magt svækkede vikingernes militære evner fordi ressourcer nu gik til hoflivet og pragt frem for krigstogt og skibsbygning","Kongemagt ændrede intet i det skandinaviske samfund fordi de fleste vikinger boede i fjerntliggende egne og ignorerede kongernes autoritet fuldstændigt"],"correct":"Stærkere konger begrænsede gradvist lokale høvdingers selvstændighed ved at indføre mere ensartet lovgivning og skatteindkrævning — det transformerede løst forbundne stammestyrker til tidlige stater og drev mange høvdinge til at søge nye muligheder på vikingetogt i udlandet","accepted_answers":["Stærkere konger begrænsede gradvist lokale høvdingers selvstændighed ved at indføre mere ensartet lovgivning og skatteindkrævning — det transformerede løst forbundne stammestyrker til tidlige stater og drev mange høvdinge til at søge nye muligheder på vikingetogt i udlandet"],"review_text":"Harald Hårfager samler ifølge Snorre Sturlasons kongesagaer Norge under én kongemagt ca. 872 e.Kr. ved slaget i Hafrsfjord. Historikere diskuterer omfanget af denne centralisering, men processen er reel: konger skabte gradvist mere homogene riger med leding-systemet (pligtig flådetjeneste og skat), fælles lovgivning og kontrol over handelsbyerne. Thing-forsamlingerne fortsatte men fik gradvist mere begrænset selvstændig magt. Den afgørende pointe er at mange af de vikingetogt der skabte bosættelser i England, Normandiet og Irland netop var drevet af høvdinge og krigergrupper der tabte indflydelse hjemme — de søgte nye ressourcer og territorier udenlands da kongen pressede dem ud af magten derhjemme. Vikingeekspansionen og den skandinaviske statsopbygning er direkte forbundne processer."}$$::jsonb,
  'mc','short',$${"concepts":["kongemagt","Harald Hårfager","leding","thing-forsamling","statsopbygning","vikingetogt"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"analytical_challenge","domain":"vikings"}$$::jsonb,
  'mc_single',4,'auto',true,'vikings',8,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvorfor giver forskellige historiske kilder så kontrasterende billeder af vikingerne?","options":["Fordi kildernes ophavsmænd afgørende påvirker perspektivet: munke og angelsaksiske krøniker beskriver primært angreb der traumatiserede dem, mens nordiske sagaer hylder krigersk ære — begge er ensidige og ingen giver et neutralt helhedsbillede af vikingesamfundet","Fordi moderne historikere bevidst har overdrevet vikingernes voldelige sider for at gøre perioden mere dramatisk og salgbar til et bredt publikum","Fordi alle skriftlige kilder fra vikingetiden er forfalsket og omskrevet af middelalderens munke der ville fremstille vikingerne negativt","Fordi vikingerne efterlod næsten ingen spor og al historisk viden om dem er baseret på rent kvalificeret gætværk uden fast evidens"],"correct":"Fordi kildernes ophavsmænd afgørende påvirker perspektivet: munke og angelsaksiske krøniker beskriver primært angreb der traumatiserede dem, mens nordiske sagaer hylder krigersk ære — begge er ensidige og ingen giver et neutralt helhedsbillede af vikingesamfundet","accepted_answers":["Fordi kildernes ophavsmænd afgørende påvirker perspektivet: munke og angelsaksiske krøniker beskriver primært angreb der traumatiserede dem, mens nordiske sagaer hylder krigersk ære — begge er ensidige og ingen giver et neutralt helhedsbillede af vikingesamfundet"],"review_text":"Kildeproblemet med vikingerne er klassisk: vi ser dem primært gennem andres øjne. Lindisfarne-krøniken (793) beskriver et traumatiseret klostersamfunds oplevelse af et angreb. Angelsaksiske annaler fokuserer naturligt på plyndring og brandskatning. Araberen Ibn Fadlan beskriver rus-vikinger ved Volgafloden (921 e.Kr.) med en fremmedkulturels fascination og forundring. De nordiske sagaer er nedskrevet 200-300 år efter begivenhederne, primært på Island i 1200-tallet, og glorificerer krigeridealet systematisk. Arkæologiske fund som handelsbyen Hedeby, Osebergskibet og vikingetidsgrave er mere neutrale vidnesbyrd — men de fortæller heller ikke den fulde sociale og politiske historie. En historiker må aktivt sammenstille disse vidt forskellige perspektiver og erkende at ingen enkelt kilde rummer hele sandheden om vikingetidens komplekse samfund."}$$::jsonb,
  'mc','short',$${"concepts":["kildekritik","Lindisfarne","Ibn Fadlan","sagaer","angelsaksiske krøniker","historisk perspektiv"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"interpretive","insight_type":"perspective_shift","challenge_role":"analytical_challenge","domain":"vikings"}$$::jsonb,
  'mc_single',4,'auto',true,'vikings',9,4
);;
