
INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v1q${"question":"Hvad betegner begrebet vikingetiden og hvornaar regner historikere den for at have fundet sted?","options":["Perioden ca. 793-1066 e.Kr. da skandinaviske folk ekspanderede over store dele af Europa og videre via handel, bosatning og plyndring","Perioden ca. 500-1200 e.Kr. da hele Europa var under skandinavisk kontrol","Forhistorien i Skandinavien - perioden inden skrift og kristendom ca. 2000-200 f.Kr.","Oldtidsdanmark i perioden ca. 200-500 e.Kr. inden den store folkevandring"],"correct":"Perioden ca. 793-1066 e.Kr. da skandinaviske folk ekspanderede over store dele af Europa og videre via handel, bosatning og plyndring","accepted_answers":["Perioden ca. 793-1066 e.Kr. da skandinaviske folk ekspanderede over store dele af Europa og videre via handel, bosatning og plyndring"],"review_text":"Vikingetiden regnes traditionelt fra plyndringen af Lindisfarne-klostret i England i 793 til Vilhelm Erobrerens sejr ved Hastings i 1066 som satte et punktum for skandinavisk ekspansion mod vest. Perioden er kendetegnet ved skandinavers enorme geografiske raeKKvidde: fra Nordamerika i vest til Konstantinopel og Bagdad i oest. Det er ikke en periode der var afgraenset og klar for dem der levede i den - periodiseringen er en moderne historisk konstruktion."}$v1q$::jsonb,
  'mc','short',$v1m${"concepts":["vikingetiden","periodisering","793","1066","skandinavisk ekspansion"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"recognition","insight_type":"concept_clarification","challenge_role":"entry_level","domain":"vikings"}$v1m$::jsonb,
  'mc_single',1,'auto',true,'vikings',8,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v2q${"question":"Hvad kendetegnede de tre skandinaviske udgangspunkter og hvilke retninger ekspanderede de primaert?","options":["Nordmaendene ekspanderede primaert mod vest (Irland, Island, Nordamerika), danskerne mod syd og vest (England, Frankrig), og svenskerne primaert mod oest (russiske floder, Byzans)","Alle tre skandinaviske folk ekspanderede udelukkende mod England og delte territoriet ligeligt imellem sig","Danskerne ekspanderede mod oest, nordmaendene mod syd og svenskerne mod vest - retningerne var omvendte af hvad de fleste tror","Der var ingen forskel paa de tre folk - alle vikinger var ens og kaempede de samme steder med de samme maal"],"correct":"Nordmaendene ekspanderede primaert mod vest (Irland, Island, Nordamerika), danskerne mod syd og vest (England, Frankrig), og svenskerne primaert mod oest (russiske floder, Byzans)","accepted_answers":["Nordmaendene ekspanderede primaert mod vest (Irland, Island, Nordamerika), danskerne mod syd og vest (England, Frankrig), og svenskerne primaert mod oest (russiske floder, Byzans)"],"review_text":"De tre skandinaviske folk havde geografisk betingede ekspansionsretninger. Norge med sin lange kystlinje vendt mod Atlanterhavet sendte vikinger mod de britiske oeer, Faeroeerne, Island og til sidst Groenland og Vinland. Danmark med sin placering ud mod Nordsoen og Kanalen rettede sig mod England og Det Frankiske Rige. Sverige med adgang til Oestersen og russiske vandveje skabte handelsruter oest- og sydpaa til Byzans og det islamiske Abbasidiske Kalifat. Denne geografiske logik forklarer meget af vikingetidens kompleksitet."}$v2q$::jsonb,
  'mc','short',$v2m${"concepts":["Norge","Danmark","Sverige","ekspansionsretninger","geografisk logik"],"misconception_type":"overgeneralization","cognitive_skill":"comprehension","difficulty_type":"recognition","insight_type":"concept_clarification","challenge_role":"entry_level","domain":"vikings"}$v2m$::jsonb,
  'mc_single',1,'auto',true,'vikings',8,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v3q${"question":"Hvilke typer kilder bruger historikere til at studere vikingetiden og hvad er den vigtigste udfordring ved dem?","options":["Sagaerne, runesten, arkaeologiske fund og fremmede skriftlige beretninger - udfordringen er at kilderne er fragmentariske, partiske eller nedskrevet laenge efter de beskrevne begivenheder","Vikingerne efterlod detaljerede historiske kroeniKer der giver et praecist og komplet billede af vikingesamfundet","Den eneste trovaerdige kilde er arkaeologiske fund da alle skriftlige kilder er demonstreret falske","Sagaerne er skrevet af vikingerne selv under vikingetiden og er derfor de mest direkte og trovaerdige kilder vi har"],"correct":"Sagaerne, runesten, arkaeologiske fund og fremmede skriftlige beretninger - udfordringen er at kilderne er fragmentariske, partiske eller nedskrevet laenge efter de beskrevne begivenheder","accepted_answers":["Sagaerne, runesten, arkaeologiske fund og fremmede skriftlige beretninger - udfordringen er at kilderne er fragmentariske, partiske eller nedskrevet laenge efter de beskrevne begivenheder"],"review_text":"Kildeunderlaget for vikingetiden er broget. Islandske sagaer er skrevet 150-300 aar efter de begivenheder de beskriver og blander fakta og fiktion. Runestene er samtidige men korte og formulerede som mindesmaeRKer ikke historieskrivning. Arabiske, frankiske og angelsaksiske skriftlige beretninger er samtidige men skrevet af vikingernes ofre eller handelspartnere og dermed partiske. Arkaeologiske fund (skibe, redskaber, bopladser) er objektive men stumme om motiver og beslutninger. Videnskabeligt historiearbejde kraever kritisk krydsning af alle kildetyper."}$v3q$::jsonb,
  'mc','short',$v3m${"concepts":["sagaer","runesten","arkaeologi","kildekritik","fragmentarisk"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"concept_clarification","challenge_role":"reinforcement","domain":"vikings"}$v3m$::jsonb,
  'mc_single',2,'auto',true,'vikings',8,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v4q${"question":"Hvilken central rolle spillede langskibet i vikingernes ekspansion?","options":["Langskibet kombinerede lavt dybgangde der muliggjorde sejlads op i floder og landing paa strande med hoej soedygtighed der muliggjorde oceankrydsninger til Island og Nordamerika","Langskibet blev udelukkende brugt til krigstogter - vikingerne brugte helt andre skibstyper til handel","Langskibet var for skroebeligt til oceansejlads og blev kun brugt langs kyster og i rolige fjorde","Langskibet var vikingernes vigtigste opfindelse men for lavt til at baere last saa handel var umulig med det"],"correct":"Langskibet kombinerede lavt dybgangde der muliggjorde sejlads op i floder og landing paa strande med hoej soedygtighed der muliggjorde oceankrydsninger til Island og Nordamerika","accepted_answers":["Langskibet kombinerede lavt dybgangde der muliggjorde sejlads op i floder og landing paa strande med hoej soedygtighed der muliggjorde oceankrydsninger til Island og Nordamerika"],"review_text":"Langskibet var en teknologisk revolution inden for sejlads. Med kun 50-90 cm dybgangde kunne det sejle op i de europaeiske floder - Seine, Thames, Rhinen og russiske vandveje - langt fra havet til overraskelsesangreb langt inde paa kontinentet. Symmetrisk for og agter betoed det kunne sejle begge veje uden at vende. Klinkbyggeriet (overlappende planker) gav fleksibilitet i boenige. Knorren (handelsskibet) var bredere og dybere til last. Begge skibstyper supplerede hinanden i vikingernes maritime system."}$v4q$::jsonb,
  'mc','short',$v4m${"concepts":["langskib","dybgangde","floder","oceansejlads","teknologi"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"concept_clarification","challenge_role":"reinforcement","domain":"vikings"}$v4m$::jsonb,
  'mc_single',2,'auto',true,'vikings',8,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v5q${"question":"Hvad var Valhalla i den norroene religion og hvilken funktion havde forestillingen om det for vikingernes krigerkultur?","options":["Odins kongsgaard i Asgaard hvortil faldne krigere hentedes af valkyrierne - forestillingen ophoeJede krigerisk mod og adfaerd ved at love et haederfuldt efterliv til dem der faldt i kamp","Helheimen - det underjordiske rige hvortil alle doede kom uanset hvordan de levede og doede","En historisk borg i Sverige som vikingerne brugte som kongesaede og religiost centrum for blotsoffre","En forestilling kun udbredt paa Island der spillede ingen rolle for vikingerne i Danmark og Norge"],"correct":"Odins kongsgaard i Asgaard hvortil faldne krigere hentedes af valkyrierne - forestillingen ophoeJede krigerisk mod og adfaerd ved at love et haederfuldt efterliv til dem der faldt i kamp","accepted_answers":["Odins kongsgaard i Asgaard hvortil faldne krigere hentedes af valkyrierne - forestillingen ophoeJede krigerisk mod og adfaerd ved at love et haederfuldt efterliv til dem der faldt i kamp"],"review_text":"I norroeen kosmologi var Valhalla den store sal i Asgaard hvor halvdelen af krigsofferdoede (einherjar) kom efter at vaere udvalgt af Odins valkyrier. Her traenede de til Ragnarok den endelige kamp. Kontrasten var Hel - det graa rige for dem der doede af sygdom eller alderdom. Denne forestilling om et hierarki af efterliv efter doedsomstoendighed - ikke efter moralsk opfoersel som i kristen teologi - understoettede en krigerkultur hvor kampdoed var haedrende. Forestillingen er primaert rekonstrueret fra islandske tekster fra 1200-tallet og er muligvis mere islandsk end pan-skandinavisk."}$v5q$::jsonb,
  'mc','short',$v5m${"concepts":["Valhalla","Odin","valkyrier","norroen religion","krigerkultur","einherjar"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"concept_clarification","challenge_role":"reinforcement","domain":"vikings"}$v5m$::jsonb,
  'mc_single',2,'auto',true,'vikings',8,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v6q${"question":"Hvad kendetegnede den sociale hierarki i vikingesamfundet?","options":["Tre hovedelag: jarler (adel og hoeVdinge), karle (frie boender, haandvaerKere og handelsmaend) og thraller (slaver) - traeldom var udbredt og traellen var et vigtigt resultat af vikingernes fangsttagning under togter","Et fuldstaendigt ligeligt samfund uden nogen social hierarki hvor alle skandinaver havde de samme rettigheder og pligter","Et feudalt system som i resten af middelalderens Europa med vasaller, lensherrer og livegne boender","To lag: konger og almue - der var ingen mellemgruppe af frie boender eller adel i vikingesamfundet"],"correct":"Tre hovedelag: jarler (adel og hoeVdinge), karle (frie boender, haandvaerKere og handelsmaend) og thraller (slaver) - traeldom var udbredt og traellen var et vigtigt resultat af vikingernes fangsttagning under togter","accepted_answers":["Tre hovedelag: jarler (adel og hoeVdinge), karle (frie boender, haandvaerKere og handelsmaend) og thraller (slaver) - traeldom var udbredt og traellen var et vigtigt resultat af vikingernes fangsttagning under togter"],"review_text":"Vikingesamfundets tre lag er rekonstrueret primaert fra den islandske Rigsthulakvad og arkaeologiske fund. Jarlerne var de maeGtige hoeVdinge med mange thegner. Karlerne var den brede frie middelklasse af boender der ejede jord, bar vaaben og deltog i tinget. Thrallerne var slaver taget under togter - primaert fra de britiske oeer og Irland. Traellehandel var en vaesentlig del af vikingernes oeKonomi; arabiske handelspartnere betalte soelv for skandinaviske slaver. Tingen (det lokale raad) gav frie karle en demokratisk stemme der ikke fandtes i Vesteuropas feudale samfund."}$v6q$::jsonb,
  'mc','short',$v6m${"concepts":["jarl","karl","thrall","social hierarki","traeldom","tinget"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"vikings"}$v6m$::jsonb,
  'mc_single',2,'auto',true,'vikings',8,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v7q${"question":"Hvorfor er begrebet viking problematisk som historisk kategori og hvad er det mere praecist en betegnelse for?","options":["De fleste skandinaver var boender og handelsmaend - viking betegner sandsynligvis dem der deltog i togter (af norroen vikingr) og var altsaa en aktivitet ikke en identitet der daeKKede hele befolkningen","Viking er en praecis betegnelse der daeKKer alle skandinaver i perioden 793-1066 da hele befolkningen deltog aktivt i plyndretogter","Viking er et moderne ord opfundet af romantiske forfattere i 1800-tallet der ingen historisk rod overhovedet har","Viking betegner specifikt den kristne del af den skandinaviske befolkning der modstod de hedenske traditioner"],"correct":"De fleste skandinaver var boender og handelsmaend - viking betegner sandsynligvis dem der deltog i togter (af norroen vikingr) og var altsaa en aktivitet ikke en identitet der daeKKede hele befolkningen","accepted_answers":["De fleste skandinaver var boender og handelsmaend - viking betegner sandsynligvis dem der deltog i togter (af norroen vikingr) og var altsaa en aktivitet ikke en identitet der daeKKede hele befolkningen"],"review_text":"Det norroene ord vikingr optraeder i kilderne som betegnelse for en person der er gaaet paa togt - ikke som en national eller etnisk identitet. At kalde hele den skandinaviske befolkning i 793-1066 for vikinger svarer til at kalde alle nutidens danskere for soldater fordi nogle tjener i haeren. Langt de fleste skandinaver levede som boender, fiskere og haandvaerKere og deltog aldrig i togter. Brugen af viking som samlet identitetsbetegnelse er primaert en konstruktion fra 1800-tallets nationalromantik der soeGte heroiske forfaedre. Det er et godt eksempel paa at periodernes navne afspejler eftertidens selvbillede mere end de historiske aktoerers selvforstaAEelse."}$v7q$::jsonb,
  'mc','short',$v7m${"concepts":["viking som kategori","vikingr","aktivitet vs identitet","nationalromantik","kildekritik"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"challenge","domain":"vikings"}$v7m$::jsonb,
  'mc_single',3,'auto',true,'vikings',8,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v8q${"question":"Hvordan bidrog svenske vikinger til at forbinde oest og vest i middelalderen via handelsnetvaerk?","options":["Svenske vikinger sejlede oest via russiske floder til Konstantinopel og Bagdad og oprettede handelsposter som Novgorod og Kiev der skabte en rute der forbandt Nordeuropas pelse og slaver med det islamiske soelvmarked og Byzans","Vikingernes handel var begraenset til Nordvesteuropa og de havde ingen kontakt med den islamiske verden eller Byzans","Svenske vikinger erobrede Konstantinopel og oprettede et skandinavisk imperium i hele Oesteuropa","Vikingernes oestlige handelsnetvaerk var ubetydelig sammenlignet med arabernes og romernes handelsveje"],"correct":"Svenske vikinger sejlede oest via russiske floder til Konstantinopel og Bagdad og oprettede handelsposter som Novgorod og Kiev der skabte en rute der forbandt Nordeuropas pelse og slaver med det islamiske soelvmarked og Byzans","accepted_answers":["Svenske vikinger sejlede oest via russiske floder til Konstantinopel og Bagdad og oprettede handelsposter som Novgorod og Kiev der skabte en rute der forbandt Nordeuropas pelse og slaver med det islamiske soelvmarked og Byzans"],"review_text":"Svenske vikinger - i kilderne kaldet vaeringe eller rus - sejlede ad Dnepr og Volga-ruterne til det Kaspiske Hav og Sortehavet. De oprettede handelsposter som Staraja Ladoga, Novgorod og Kiev og handlede med arabiske soelvmoenter (dirhemer) fundet i tusindvis i skandinaviske arkaeologiske fund. Fra nord bragte de pelse, voks, rav og slaver. Fra syd og oest bragte de soelv, silke og krydderier. Disse rus-vikinger lagde grunden til det tidlige russiske fyrstendoemme Kievan Rus. Det er et eksempel paa at vikingetiden var langt mere handelsdrevet end det populaere billede tilsiger."}$v8q$::jsonb,
  'mc','short',$v8m${"concepts":["vaeringe","Rus-ruten","Kievan Rus","Novgorod","Kiev","oesterhandel"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"challenge","domain":"vikings"}$v8m$::jsonb,
  'mc_single',3,'auto',true,'vikings',8,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v9q${"question":"Hvad kendetegnede kristningsprocessen i Skandinavien og hvad var dens vigtigste konsekvenser?","options":["Kristningen var gradvis (ca. 960-1100) drevet af missionaerer, politisk pres og kongers strategiske valg - konsekvenserne var kirkebyggeri, skriftlig latinkultur, integration i det europaeiske netvaerk og gradvis afvikling af norroen religion","Skandinavien blev kristent paa en enkelt dag i aar 1000 da alle nordiske konger underskrev en traktat i Rom","Kristningen var tvungen og alle skandinaver modstod aktivt og blev kun kristne under direkte militaer trussel","Kristningen aendrede kun privat religioes praksis og havde ingen politiske eller kulturelle konsekvenser for samfundsstrukturen"],"correct":"Kristningen var gradvis (ca. 960-1100) drevet af missionaerer, politisk pres og kongers strategiske valg - konsekvenserne var kirkebyggeri, skriftlig latinkultur, integration i det europaeiske netvaerk og gradvis afvikling af norroen religion","accepted_answers":["Kristningen var gradvis (ca. 960-1100) drevet af missionaerer, politisk pres og kongers strategiske valg - konsekvenserne var kirkebyggeri, skriftlig latinkultur, integration i det europaeiske netvaerk og gradvis afvikling af norroen religion"],"review_text":"Harald Blaatand erklaerede sig selv kristen ca. 960 og rejste Jellingsten II som erklaerer ham som den der kristnede danskerne. Men kristning var en langvarig process ikke en enkelt begivenhed. Kongernes motiver var delvist politiske: kristen kongeideologi legitimerede centralmagt, og en kristen konge var en mere acceptabel handelspartner for det kristne Europa. Konsekvenserne var dybe: kirker og klostre opbyggede en latinsk skriftkultur, kirkens retslige normer overtog tingsystemets lokale lov, og offerskik, kremering og norroene grave erstattedes med kristne begravelser. Norroen religion overlevede som folkemindekultur men ikke som institutionel praksis."}$v9q$::jsonb,
  'mc','short',$v9m${"concepts":["kristning","Harald Blaatand","Jellingsten","latinkultur","politisk legitimitet"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"challenge","domain":"vikings"}$v9m$::jsonb,
  'mc_single',3,'auto',true,'vikings',8,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v10q${"question":"Hvad kendetegnede kvinders retsstilling i vikingesamfundet sammenlignet med kvinder i det samtidige Vesteuropa?","options":["Vikingetidens kvinder havde relativt betydelige rettigheder i en middelalderlig sammenhaeng - de kunne eje ejendom, kraeve skilsmisse og drive handel - men var stadig underordnet maend og kilderne er begraensede","Vikingetidens kvinder var fuldstaendigt ligestillede med maend og havde noeJagtig de samme juridiske og politiske rettigheder","Vikingetidens kvinder var mere undertrykte end samtidige europaeiske kvinder og havde ingen juridiske rettigheder overhovedet","Kvinder spillede ingen rolle i vikingesamfundet og omtales slet ikke i de historiske eller arkaeologiske kilder"],"correct":"Vikingetidens kvinder havde relativt betydelige rettigheder i en middelalderlig sammenhaeng - de kunne eje ejendom, kraeve skilsmisse og drive handel - men var stadig underordnet maend og kilderne er begraensede","accepted_answers":["Vikingetidens kvinder havde relativt betydelige rettigheder i en middelalderlig sammenhaeng - de kunne eje ejendom, kraeve skilsmisse og drive handel - men var stadig underordnet maend og kilderne er begraensede"],"review_text":"Juridiske bestemmelser fra islandske love (Graagas) og sagabeskrivelser antyder at vikingetidens kvinder kunne eje ejendom selvstaendigt, arve, indgaa og oplose aegteskab, og have husstandsmyndighed. Det var mere end samtidige frankiske og angelsaksiske kvinder i mange tilfaelde. Arkaeologiske fund af velhavende kvindegrave (fx Osebergskibet med to kvinder) bekraefter at hoeJststaaende kvinder havde reel status. Men kilderne er primaert fra det islandske miljoee og fra eliten - hverdagskvindens retsstilling var sandsynligvis mere begraenset. Nuancen er vigtig: relativt mere rettigheder er ikke det samme som ligestilling."}$v10q$::jsonb,
  'mc','short',$v10m${"concepts":["kvinder","retsstilling","Graagas","Osebergskib","middelalderlig sammenligning"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"reframing","challenge_role":"challenge","domain":"vikings"}$v10m$::jsonb,
  'mc_single',3,'auto',true,'vikings',8,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v11q${"question":"Hvorfor er distinktionen mellem vikingen som raider og vikingen som settler vigtig for en nuanceret historisk forstaAEelse?","options":["De samme skandinaver der plyndrede et sted i een generation kunne bosatte sig fredeligt i en anden - raiding og bosatning var ikke to typer vikinger men aktiviteter betinget af muligheder: Danelaw og Normandiet var bosatninger og Island et nybygningssamfund","Raidere og settlere var to fuldstaendigt adskilte grupper - plyndrerne vendte altid hjem mens settlerne aldrig plyndrede","Distinktionen er irrelevant fordi alle vikingetogter endte med permanent bosatning i de plyndrede omraader","Vikingerne bosatte sig aldrig permanent uden for Skandinavien - de vendte altid hjem til Skandinavien efter plyndretogterne"],"correct":"De samme skandinaver der plyndrede et sted i een generation kunne bosatte sig fredeligt i en anden - raiding og bosatning var ikke to typer vikinger men aktiviteter betinget af muligheder: Danelaw og Normandiet var bosatninger og Island et nybygningssamfund","accepted_answers":["De samme skandinaver der plyndrede et sted i een generation kunne bosatte sig fredeligt i en anden - raiding og bosatning var ikke to typer vikinger men aktiviteter betinget af muligheder: Danelaw og Normandiet var bosatninger og Island et nybygningssamfund"],"review_text":"Danelaw i det nordoestlige England og Normandiet i Frankrig er eksempler paa at skandinaver der i foerste generation plyndrede regionerne i naeste generation bosatte sig, integrerede sig med lokalbefolkningerne og til sidst adopterede lokalt sprog og kultur. Island og Faeroeerne var modsat jomfrueligt land besat fredeligt uden forudgaaende plyndring. Vinland i Nordamerika var et bosattelsesforsog der mislykkedes paa grund af konflikter med lokalbefolkning. Billedet af vikingen som udelukkende plyndrer er en forenkling der overser den demografiske bevoegelse og kulturelle integration der var en mindst ligesaa stor del af vikingetidens historiske arv."}$v11q$::jsonb,
  'mc','short',$v11m${"concepts":["raiding","bosatning","Danelaw","Normandiet","Island","integration"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"challenge","domain":"vikings"}$v11m$::jsonb,
  'mc_single',3,'auto',true,'vikings',8,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v12q${"question":"Hvad er runestenenes historiske vaerdi som kilde til vikingetiden og hvad er deres vigtigste begraensninger?","options":["Runestene er samtidige primaerkilder der giver direkte information om sociale relationer og geografiske ruter - men de er fragmentariske, geografisk skaevt fordelt, skrevet af og for eliten og fortaeller sjaeldent om aarsager eller kontekst","Runestene er ubrugelige som historiske kilder fordi runeskrift kun brugt til magiske ritualer ikke faktuel kommunikation","Runestene er de eneste fuldstaendigt trovaerdige kilder til vikingetiden da de er samtidige og ikke filtreret gennem eftertidens fortolkning","Runestene er middelalderlige forfalskninger skabt af romantiske forfattere i 1800-tallet for at glorificere den nordiske fortid"],"correct":"Runestene er samtidige primaerkilder der giver direkte information om sociale relationer og geografiske ruter - men de er fragmentariske, geografisk skaevt fordelt, skrevet af og for eliten og fortaeller sjaeldent om aarsager eller kontekst","accepted_answers":["Runestene er samtidige primaerkilder der giver direkte information om sociale relationer og geografiske ruter - men de er fragmentariske, geografisk skaevt fordelt, skrevet af og for eliten og fortaeller sjaeldent om aarsager eller kontekst"],"review_text":"Over 3.000 runestene er fundet primaert i Sverige, Danmark og Norge. De er enestaAEnde som samtidige skriftlige primaerkilder - men deres indhold er begraenset. De fleste er mindestene rejst af familier for afdoede slaegtninge og fortaeller hvem der rejste stenen, hvem der er doet og undertiden hvor. Byzantium-stenene fra Sverige naevner maend der doede i Graekland og bekraefter vikingernes oestlige ruter. Men de er formuleret stereotypt, fortaeller ikke om historiske begivenheder, motiver eller samfundsstrukturer, og er geografisk koncentreret i Sverige. Runestene er nyttige brikker - men de er ikke et komplet historisk vidnesbyrd."}$v12q$::jsonb,
  'mc','short',$v12m${"concepts":["runesten","primaerKilde","kildekritik","elitekilde","geografisk skaevhed"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"vikings"}$v12m$::jsonb,
  'mc_single',3,'auto',true,'vikings',8,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v13q${"question":"Hvordan bidrog vikingetiden til dannelsen af tidlige stater i Europa?","options":["Vikingernes bosatninger og konsolidering skabte direkte nye statsdannelser: normannerne stiftede hertugdoemmet Normandiet og erobrede England i 1066 og Sicilien; svenske vikinger grundlagde Kievan Rus; og i Skandinavien skabte presset udefra en konsolidering til tre riger","Vikingerne forhindrede europaeisk statsdannelse ved konstant at destabilisere eksisterende kongedoemmer og lod aldrig stabile stater opstaa","Vikingetiden bidrog ikke til europaeisk statsdannelse da vikingerne altid trak sig tilbage til Skandinavien efter togterne","Den eneste statsformation vikingerne bidrog til var Rusland - i Vesteuropa oedelagde de udelukkende eksisterende strukturer"],"correct":"Vikingernes bosatninger og konsolidering skabte direkte nye statsdannelser: normannerne stiftede hertugdoemmet Normandiet og erobrede England i 1066 og Sicilien; svenske vikinger grundlagde Kievan Rus; og i Skandinavien skabte presset udefra en konsolidering til tre riger","accepted_answers":["Vikingernes bosatninger og konsolidering skabte direkte nye statsdannelser: normannerne stiftede hertugdoemmet Normandiet og erobrede England i 1066 og Sicilien; svenske vikinger grundlagde Kievan Rus; og i Skandinavien skabte presset udefra en konsolidering til tre riger"],"review_text":"Vikingetidens statsformende konsekvenser er markante. Normandiet: skandinaviske bosattere under Rollo fik hertugdoemmet i 911 og deres efterkommer Vilhelm Erobreren aendrede Englands historie permanent i 1066. Normannerne erobrede siden Sicilien og grundlagde et multietnisk kongedoemme i Middelhavet. Kievan Rus: svenske rus-vikinger oprettede de tidlige fyrstendoemmer der lagde grunden til Rusland, Ukraine og Hviderusland. I Skandinavien selv skabte vikingetogternes organisering af krigere og ressourcer en centraliseringsproces der konsoliderede de tre kongedoemmer Danmark, Norge og Sverige. Vold og statsdannelse er historisk taet forbundne."}$v13q$::jsonb,
  'mc','short',$v13m${"concepts":["statsdannelse","Normandiet","Kievan Rus","normannerne","Danmark","centralmagt"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"analytical_challenge","domain":"vikings"}$v13m$::jsonb,
  'mc_single',4,'auto',true,'vikings',8,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v14q${"question":"I hvilken grad er det populaere billede af vikingerne med hornede hjelme og ren barbari et historisk konstrueret myte?","options":["I hoej grad: hornede hjelme er aldrig fundet fra vikingetiden og stammer fra romantikkens operaer; barbaribilledet er skabt af vikingernes ofres ensidige beretninger og 1800-tallets nationalromantik; arkaeologien viser et samfund med kompleks handel, retsorden og kunst","Det populaere billede er fuldstaendigt historisk korrekt og bekraeftes ensartet af alle arkaeologiske fund fra vikingetiden","Billedet er overdrevet men er et resultat af fejlfortolkninger i akademisk forskning fra 1900-tallet ikke af romantikken","Det er umuligt at vurdere det populaere vikinge-billede da vi ikke har tilstraekkelige historiske kilder til perioden"],"correct":"I hoej grad: hornede hjelme er aldrig fundet fra vikingetiden og stammer fra romantikkens operaer; barbaribilledet er skabt af vikingernes ofres ensidige beretninger og 1800-tallets nationalromantik; arkaeologien viser et samfund med kompleks handel, retsorden og kunst","accepted_answers":["I hoej grad: hornede hjelme er aldrig fundet fra vikingetiden og stammer fra romantikkens operaer; barbaribilledet er skabt af vikingernes ofres ensidige beretninger og 1800-tallets nationalromantik; arkaeologien viser et samfund med kompleks handel, retsorden og kunst"],"review_text":"De hornede hjelme stammer fra Wagners Nibelung-operaer (1870erne) og romantiske illustratorer som Lorenz Froelich. Det eneste bevarede vikingehjelmfragment fra Gjermundbu er rundt uden horn. Barbaribilledet dominerer fordi de vigtigste skriftlige samtidskilder er skrevet af klostrene - vikingernes ofre - der naturligvis beskrev plyndringen ikke den daglige handel. 1800-tallets nationalromantik i Skandinavien, Tyskland og England genopfandt vikingerne som heroiske forfaedre tilpasset nationalistiske behov. Arkaeologien viser et andet billede: raffineret guldsmedekunst, velfungerende handelsbyer (Hedeby, Ribe), skriftlig retslig tradition og internationale handelsnetvaerk. Myter om fortiden fortaeller os mere om dem der skabte myterne end om fortiden selv."}$v14q$::jsonb,
  'mc','short',$v14m${"concepts":["hornede hjelme","myte","nationalromantik","kildekritik","arkaeologisk billede","historieskrivning"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"vikings"}$v14m$::jsonb,
  'mc_single',5,'auto',true,'vikings',8,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v15q${"question":"Hvad afsloeRer vikingetidens kombination af vold og kulturel udveksling om drivkraefterne bag historisk forandring?","options":["At vold og kulturel udveksling ofte er to sider af den samme historiske dynamik - vikingerne terroriserede klostre og oprettede handelsnetvaerk, blandede kulturer og adopterede lokale skikke; forandring sker sjaeldent gennem ren konstruktion eller ren destruktion men i samspillet","At vold aldrig foerer til kulturel udveksling da vold oedelaegger de kulturer den roerer ved fuldstaendigt","At vikingernes kulturelle udveksling var fuldstaendigt adskilt fra deres vold med to specialiserede grupper: handelsvikinger og krigsvikinger","At vikingetidens kulturelle udveksling var rent ensidig: vikingerne adopterede fremmede kulturer men bidrog ikke selv med noget til de kulturer de moedte"],"correct":"At vold og kulturel udveksling ofte er to sider af den samme historiske dynamik - vikingerne terroriserede klostre og oprettede handelsnetvaerk, blandede kulturer og adopterede lokale skikke; forandring sker sjaeldent gennem ren konstruktion eller ren destruktion men i samspillet","accepted_answers":["At vold og kulturel udveksling ofte er to sider af den samme historiske dynamik - vikingerne terroriserede klostre og oprettede handelsnetvaerk, blandede kulturer og adopterede lokale skikke; forandring sker sjaeldent gennem ren konstruktion eller ren destruktion men i samspillet"],"review_text":"Vikingetiden er et historiografisk interessant tilfaelde fordi den tvinger os til at holde to tanker i hovedet paa een gang. De samme aktoerer (skandinaviske maend fra samme samfund) plyndrede irske klostre, grundlagde Dublin som handelsby og adopterede irsk keltisk kunst i skandinavisk metalarbejde. Normannerne plyndrede Frankrig, bosatte sig i Normandiet og skabte en frankisk-skandinavisk ridderkrigerkulturs syntese. Rus-vikingerne traengte ind i slaviske samfund og skabte Kievan Rus med blandet slavisk-skandinavisk kultur. Historisk forandring er sjaeldent en ryddetabel - det er en kompleks proces af oedelaeggelse, adoption, blanding og transformation. Det er ubehageligt men vigtigt at anerkende at vold kan vaere historisk produktiv."}$v15q$::jsonb,
  'mc','short',$v15m${"concepts":["vold og kulturudveksling","historisk forandring","hybridisering","Normandiet","Rus","kompleksitet"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"vikings"}$v15m$::jsonb,
  'mc_single',5,'auto',true,'vikings',8,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v16q${"question":"Var vikingetiden primaert en skandinavisk historie eller en europaeisk og global historie - og hvad siger perspektivvalget om historieskrivningens natur?","options":["Begge perspektiver er legitime men belyser forskelligt: som skandinavisk historie handler den om statsdannelse og kristning; som europaeisk og global handler den om handelsnetvaerk og kulturblanding fra Nordamerika til Centralasien; perspektivvalget bestemmer hvad der er centralt og hvad der er perifert","Vikingetiden var udelukkende en skandinavisk historie da dens konsekvenser for resten af verden var ubetydelige","Vikingetiden var udelukkende en europaeisk historie - Skandinavien var kun udgangspunktet og aendrede sig ikke under perioden","Det er irrelevant om man vaelger skandinavisk eller globalt perspektiv da begge perspektiver giver noeJagtig det samme historiske billede"],"correct":"Begge perspektiver er legitime men belyser forskelligt: som skandinavisk historie handler den om statsdannelse og kristning; som europaeisk og global handler den om handelsnetvaerk og kulturblanding fra Nordamerika til Centralasien; perspektivvalget bestemmer hvad der er centralt og hvad der er perifert","accepted_answers":["Begge perspektiver er legitime men belyser forskelligt: som skandinavisk historie handler den om statsdannelse og kristning; som europaeisk og global handler den om handelsnetvaerk og kulturblanding fra Nordamerika til Centralasien; perspektivvalget bestemmer hvad der er centralt og hvad der er perifert"],"review_text":"Valget af perspektiv er ikke neutralt i historieskrivning - det skaber narrativet. Et skandinavisk perspektiv placerer Harald Blaatand, Jelling-monumenterne og kristningen centralt og fortaeller historien om Skandinaviens integration i det europaeiske civilisationsfaellesskab. Et globalt perspektiv placerer handelsruterne centralt: Vinland i vest, Bagdad i oest, konstantinopolitansk guldsmedekunst i nordiske grave og arabiske moenter i svenske skatte. De to fortaellinger er ikke i modstrid - de er komplementaere billeder af den samme virkelighed set fra forskellige vinkler. ErkEndelsen af at historieskrivning altid er perspektivbaseret er en af historiedisciplinens vigtigste metodiske indsigter: der er ikke een sand fortaelling men mange valide men delvise fortaellinger."}$v16q$::jsonb,
  'mc','short',$v16m${"concepts":["perspektivvalg","skandinavisk vs globalt","historieskrivning","narrativ","metodisk indsigt"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"vikings"}$v16m$::jsonb,
  'mc_single',5,'auto',true,'vikings',8,5
);
;
