-- Section 83 — Reformation & Monarchy — Grade 6 (25 questions)
-- B1x6, B2x7, B3x7, B4x5. Domain: reformation_monarchy.

-- ─── GRADE 6 · BAND 1 (6 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvem var Martin Luther?","options":["En tysk praest der protesterede mod den katolske kirkes praksis i 1517","En dansk biskop der grundlagde den protestantiske kirke","En tysk kejser der forjoede paven fra Europa","En dansk praest der oversatte bibelen til latin"],"correct":"En tysk praest der protesterede mod den katolske kirkes praksis i 1517","accepted_answers":["En tysk praest der protesterede mod den katolske kirkes praksis i 1517"],"review_text":"Martin Luther var en tysk praest. Han protesterede mod den katolske kirke i 1517. Hans ideer spredte sig hurtigt og startede Reformationen i Europa."}'::jsonb,
  'mc','short','{"concepts":["Martin Luther","Reformationen","protestantisme","1517"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',1,'auto',true,'reformation_monarchy',6,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var Reformationen?","options":["En religioes og politisk bevaegelse der brued med den katolske kirke og skabte den protestantiske kirke","En reform af den katolske kirke som paven godkendte","En krig mellem England og Frankrig om retten til at vaere kristen","En bevaegelse der ville afskaffe al religion i Europa"],"correct":"En religioes og politisk bevaegelse der brued med den katolske kirke og skabte den protestantiske kirke","accepted_answers":["En religioes og politisk bevaegelse der brued med den katolske kirke og skabte den protestantiske kirke"],"review_text":"Reformationen startede som en religioes protest men blev ogsaa en politisk bevaegelse. Den brued med den katolske kirke i Rom og skabte nye protestantiske kirker i Europa."}'::jsonb,
  'mc','short','{"concepts":["Reformationen","protestantisme","katolsk kirke","kirkehistorie"],"misconception_type":"scope_confusion","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',1,'auto',true,'reformation_monarchy',6,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad kritiserede Martin Luther i den katolske kirke?","options":["At kirken solgte afladsbreve der lovede syndernes tilgivelse mod betaling","At kirken havde for faae kirker i Europa","At kirken brugte for mange penge paa fattigpleje","At kirken laeste for meget i bibelen"],"correct":"At kirken solgte afladsbreve der lovede syndernes tilgivelse mod betaling","accepted_answers":["At kirken solgte afladsbreve der lovede syndernes tilgivelse mod betaling"],"review_text":"Afladsbreve var papirbeviser den katolske kirke solgte. De lovede syndernes tilgivelse mod betaling. Luther mente det var forkert at kobe sig til Guds naade. Kun tro kunne give tilgivelse."}'::jsonb,
  'mc','short','{"concepts":["afladsbreve","kritik","Luther","naade","betaling"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',1,'auto',true,'reformation_monarchy',6,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad kendetegnede den nye protestantiske kirke?","options":["Gudstjeneste paa folkets eget sprog og fokus paa bibelen fremfor pavens autoritet","Gudstjeneste paa latin og direkte linje til paven i Rom","Ingen kirker eller praester folk bad alene derhjemme","Kirker der kun var aabne om sondagen og ellers lukkede"],"correct":"Gudstjeneste paa folkets eget sprog og fokus paa bibelen fremfor pavens autoritet","accepted_answers":["Gudstjeneste paa folkets eget sprog og fokus paa bibelen fremfor pavens autoritet"],"review_text":"I den katolske kirke var gudstjenesten paa latin som de fleste ikke forstod. I den protestantiske kirke horte folk gudstjenesten paa deres eget sprog. Bibelen var nu tilgaengelig for alle og ikke kun for praesterne."}'::jsonb,
  'mc','short','{"concepts":["protestantisme","folkesprog","bibelen","gudstjeneste"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',1,'auto',true,'reformation_monarchy',6,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad gjoerde Christian III i forbindelse med Reformationen i Danmark?","options":["Han indfoerte den lutherske reformation i Danmark i 1536 og blev kirkens overhoved","Han afviste Reformationen og forblev katolik","Han overlod beslutningen til den danske befolkning","Han inviterede paven til Danmark for at lede kirken"],"correct":"Han indfoerte den lutherske reformation i Danmark i 1536 og blev kirkens overhoved","accepted_answers":["Han indfoerte den lutherske reformation i Danmark i 1536 og blev kirkens overhoved"],"review_text":"I 1536 indfoerte Christian III den lutherske reformation i Danmark. Kongen overtog kontrollen over kirken. De katolske biskopper mistede deres magt. Danmark blev et luthersk land."}'::jsonb,
  'mc','short','{"concepts":["Christian III","dansk Reformation","1536","kirkens overhoved"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',1,'auto',true,'reformation_monarchy',6,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad aendrede sig i hverdagen for en dansk borger efter Reformationen i 1536?","options":["Gudstjenesten skete nu paa dansk og ikke paa latin og kongen var nu kirkens overhoved fremfor paven","Folk behoevede ikke laengere gaa i kirke","Alle kirker blev revet ned og bygget op igen","Religion forsvandt fuldstaendigt fra hverdagen"],"correct":"Gudstjenesten skete nu paa dansk og ikke paa latin og kongen var nu kirkens overhoved fremfor paven","accepted_answers":["Gudstjenesten skete nu paa dansk og ikke paa latin og kongen var nu kirkens overhoved fremfor paven"],"review_text":"For den menige borger var den stoerste forskel at gudstjenesten nu var paa dansk. Man forstod hvad praesten sagde. Paven i Rom havde ikke laengere nogen magt i Danmark. Kongen var nu kirkens overhoved."}'::jsonb,
  'mc','short','{"concepts":["hverdagsliv","gudstjeneste","dansk sprog","Reformation"],"misconception_type":"overgeneralization","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',1,'auto',true,'reformation_monarchy',6,1
);

-- ─── GRADE 6 · BAND 2 (7 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvorfor slog Martin Luther sine 95 teser op paa kirkedoren i Wittenberg i 1517?","options":["For at invitere til offentlig diskussion om den katolske kirkes brug af afladsbreve","For at opsige sin stilling som praest","For at erklaere krig mod paven","For at reklamere for sin nye kirke"],"correct":"For at invitere til offentlig diskussion om den katolske kirkes brug af afladsbreve","accepted_answers":["For at invitere til offentlig diskussion om den katolske kirkes brug af afladsbreve"],"review_text":"I 1517 slog Luther 95 argumenter op paa kirkedoren i Wittenberg. Det var en invitation til akademisk diskussion. Han vidste ikke at hans ideer ville sprede sig saa hurtigt og skabe en revolution."}'::jsonb,
  'mc','short','{"concepts":["95 teser","Wittenberg","afladsbreve","diskussion"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',2,'auto',true,'reformation_monarchy',6,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad skete der med kirkens magt i Danmark efter Reformationen?","options":["Kirken mistede sin selvstaendige politiske og okonomiske magt og kom under kongens kontrol","Kirkens magt voksede fordi den protestantiske kirke var mere populaer","Kirken beholdt al sin magt men skiftede blot leder fra paven til en dansk biskop","Kirken mistede al indflydelse paa samfundet fuldstaendigt"],"correct":"Kirken mistede sin selvstaendige politiske og okonomiske magt og kom under kongens kontrol","accepted_answers":["Kirken mistede sin selvstaendige politiske og okonomiske magt og kom under kongens kontrol"],"review_text":"Den katolske kirke havde ejet enorme jordarealer og haft politisk magt. Efter Reformationen overtog kongen kirkens ejendomme. Kirken kom under kongens kontrol. Det styrkede kongens magt enormt."}'::jsonb,
  'mc','short','{"concepts":["kirkens magt","kongens magt","ejendom","Reformation"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',2,'auto',true,'reformation_monarchy',6,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvorfor hjalp bogtrykkerkunsten Reformationen med at sprede sig hurtigt?","options":["Luthers skrifter kunne nu trykkes i tusindvis af eksemplarer og naae folk overalt i Europa","Bogtrykkerkunsten hjalp paven med at sende svar til Luther","Bogtrykkerkunsten muliggjorde kun skrivning paa latin","Bogtrykkerkunsten var ikke vigtig for Reformationen"],"correct":"Luthers skrifter kunne nu trykkes i tusindvis af eksemplarer og naae folk overalt i Europa","accepted_answers":["Luthers skrifter kunne nu trykkes i tusindvis af eksemplarer og naae folk overalt i Europa"],"review_text":"Foer bogtrykkerkunsten tog det maaneder at kopiere en bog i haand. Med trykkeriet kunne Luthers skrifter kopieres i tusindvis paa dage. Hans ideer spredte sig til hele Europa paa rekordtid."}'::jsonb,
  'mc','short','{"concepts":["bogtrykkeri","spredning","Luther","massekommunikation"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',2,'auto',true,'reformation_monarchy',6,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvorfor stoettede mange europaeiske konger Reformationen?","options":["Fordi Reformationen gav kongen mulighed for at overtage kirkens rigdom og slippe fri af pavens autoritet","Fordi konger var dybe troende lutheranere der elskede Luthers teologi","Fordi paven bad konger om at stoette Reformationen","Fordi konger var bange for at folket ville tvinge dem"],"correct":"Fordi Reformationen gav kongen mulighed for at overtage kirkens rigdom og slippe fri af pavens autoritet","accepted_answers":["Fordi Reformationen gav kongen mulighed for at overtage kirkens rigdom og slippe fri af pavens autoritet"],"review_text":"Den katolske kirke ejede op til en tredjedel af al jord i Europa. Reformationen gav konger mulighed for at overtage kirkens ejendomme og saette sig fri af pavens politiske indflydelse. For mange konger var Reformationen ogsaa et magttrek."}'::jsonb,
  'mc','short','{"concepts":["konger","kirkens rigdom","paven","politisk magt"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',2,'auto',true,'reformation_monarchy',6,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad skete der med klostrenes og kirkens ejendomme i Danmark efter Reformationen?","options":["Kongen overtog dem og brugte indtagterne til at styrke statsmagten","Ejendommene blev delt ud til fattige borgere","Ejendommene forblev i kirkens haaende men under luthersk ledelse","Alle klostre og kirker blev brudt ned"],"correct":"Kongen overtog dem og brugte indtagterne til at styrke statsmagten","accepted_answers":["Kongen overtog dem og brugte indtagterne til at styrke statsmagten"],"review_text":"Det var enorme vaerdier. Klostre, gaarde og landsbyer som kirken ejede gik nu til kongen. Det gjorde kongen rig og svaekkede kirken. Reformationen var ikke bare en religioes begivenhed men ogsaa en okonomisk revolution."}'::jsonb,
  'mc','short','{"concepts":["klostre","kirkens ejendom","kongens rigdom","okonomisk revolution"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',2,'auto',true,'reformation_monarchy',6,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betod Reformationen for de danske boender i praksis?","options":["Den religiose aendring kom men den soziale og okonomiske undertrykkelse fortsatte uaendret","Boender fik frihed og jord som beloening for at stoette Reformationen","Boender mistede al religion og det goerde livet svaerere","Boender fik stemmeret og politisk magt"],"correct":"Den religiose aendring kom men den soziale og okonomiske undertrykkelse fortsatte uaendret","accepted_answers":["Den religiose aendring kom men den soziale og okonomiske undertrykkelse fortsatte uaendret"],"review_text":"Boender horte nu gudstjenesten paa dansk og forstod den bedre. Men de ejede stadig ikke land. De betalte stadig afgifter. Den politiske og soziale forandring kom ikke til boenderne med Reformationen."}'::jsonb,
  'mc','short','{"concepts":["boender","Reformation","sozial uforandret","okonomisk undertrykkelse"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',2,'auto',true,'reformation_monarchy',6,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er enevaelde?","options":["Et styresystem hvor kongen har al lovgivende, udovende og dommende magt alene","Et styresystem hvor kongen deler magten med adelen og kirken","Et demokrati hvor folket valgte kongen hvert femte aar","Et system hvor kirken og kongen regerede side om side med ens magt"],"correct":"Et styresystem hvor kongen har al lovgivende, udovende og dommende magt alene","accepted_answers":["Et styresystem hvor kongen har al lovgivende, udovende og dommende magt alene"],"review_text":"Enevaelde betyder at kongen alene har al magt. Han laver lovene. Han udforer dem. Han er overdommer. Der er ingen parlement og ingen adel der kan blokere ham. Danmark fik enevaelde i 1660."}'::jsonb,
  'mc','short','{"concepts":["enevaelde","absolut monarki","kongens magt","1660"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',2,'auto',true,'reformation_monarchy',6,2
);

-- ─── GRADE 6 · BAND 3 (7 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved forestillingen om at Reformationen kun var en religioes begivenhed?","options":["Reformationen aendrede ogsaa magtbalancen politisk og okonomisk ved at flytte kirkens rigdom og magt til fyrsterne","Forestillingen er korrekt Reformationen handlede kun om religion","Det er forkert fordi Reformationen var kun politisk og intet med religion at goere","Det er forkert fordi Reformationen kun paavirket adelen"],"correct":"Reformationen aendrede ogsaa magtbalancen politisk og okonomisk ved at flytte kirkens rigdom og magt til fyrsterne","accepted_answers":["Reformationen aendrede ogsaa magtbalancen politisk og okonomisk ved at flytte kirkens rigdom og magt til fyrsterne"],"review_text":"Reformationen aendrede ikke blot gudstjenesten. Den aendrede hvem der ejede jord og hvem der havde politisk autoritet. Konger i hele Europa fik et vaeldigt magtloeft da de overtog kirkens ejendomme og saatte sig fri af paven."}'::jsonb,
  'mc','short','{"concepts":["Reformation","politisk","okonomisk","kirkens rigdom","misconception-kun-religion"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',3,'auto',true,'reformation_monarchy',6,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvem profiterede mest paa den danske Reformation i 1536?","options":["Kongen som overtog kirkens ejendomme og blev kirkens overhoved og dermed svaekkede alle rivaler","Boenderne som fik fri jord og ikke laengere betalte tiende til kirken","Praesterne som fik hoejere loen og mere magt","Adelen som overtog alle klostre"],"correct":"Kongen som overtog kirkens ejendomme og blev kirkens overhoved og dermed svaekkede alle rivaler","accepted_answers":["Kongen som overtog kirkens ejendomme og blev kirkens overhoved og dermed svaekkede alle rivaler"],"review_text":"Christian III vandt enormt paa Reformationen. Han konfiskerede kirkens jord og klostrenes ejendomme. Han afsatte de katolske biskopper. Ingen rivalmagt i Danmark var laengere stor nok til at udfordre ham. Det var begyndelsen paa kongens vej mod enevaelde."}'::jsonb,
  'mc','short','{"concepts":["Christian III","vinder","kirkens ejendom","magtbalance","vejen mod enevaelde"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',3,'auto',true,'reformation_monarchy',6,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var forbindelsen mellem Reformationen og uddannelse?","options":["Luther insisterede paa at alle skulle kunne laese bibelen selv og det fremmede grundlaeggende skoleundervisning","Reformationen lukkede alle skoler fordi kirken ikke laengere kontrollerede undervisningen","Uddannelse var upaavirkede af Reformationen","Kun adelen fik bedre uddannelse resten mistede adgang"],"correct":"Luther insisterede paa at alle skulle kunne laese bibelen selv og det fremmede grundlaeggende skoleundervisning","accepted_answers":["Luther insisterede paa at alle skulle kunne laese bibelen selv og det fremmede grundlaeggende skoleundervisning"],"review_text":"Luther mente at alle troende selv skulle kunne laese bibelen. Det kraevede at folk kunne laese. Gradvist opstod skoler som laerte born at laese. Det var ikke universelt tilgaengeligt men Reformationen satte uddannelse paa dagsordenen."}'::jsonb,
  'mc','short','{"concepts":["uddannelse","laesning","bibelen","Reformation","skoler"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',3,'auto',true,'reformation_monarchy',6,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved forestillingen om at kirken i middelalderen kun paavirket religiose anliggender?","options":["Kirken kontrollerede skole, hospital, kalender og politisk legitimitet og var samfundets mest indflydelsesrige institution","Forestillingen er korrekt kirken holdt sig til rent religiose anliggender","Kirken paavirket kun rige folk resten var uberort","Kirken var vigtig i byerne men naaede ikke ud til landsbyerne"],"correct":"Kirken kontrollerede skole, hospital, kalender og politisk legitimitet og var samfundets mest indflydelsesrige institution","accepted_answers":["Kirken kontrollerede skole, hospital, kalender og politisk legitimitet og var samfundets mest indflydelsesrige institution"],"review_text":"Kirken drev skoler og hospitaler. Den ejede jord. Den kontrollerede kalenderen. Den legitimerede kongers magt. At sige at kirken kun var religioes er at misforstaa hvad kirken var. Den var samfundets centrale institution."}'::jsonb,
  'mc','short','{"concepts":["kirkens rolle","skole","hospital","magt","misconception-kirken-kun-religion"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',3,'auto',true,'reformation_monarchy',6,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betod det at leve under enevaelde for en dansk bonde i 1600-1700-tallet?","options":["Bonden var underlagt kongens love direkte men ejede stadig intet land og var bundet til godset","Bonden fik ejendomsret over den jord han dyrkede","Bonden fik mulighed for at klage direkte til kongen","Bondens liv forbedredes markant under enevaeldet"],"correct":"Bonden var underlagt kongens love direkte men ejede stadig intet land og var bundet til godset","accepted_answers":["Bonden var underlagt kongens love direkte men ejede stadig intet land og var bundet til godset"],"review_text":"Enevaeldet aendrede kongens magt men ikke bondens dagligdag. Bonden dyrkede stadig andres jord. Han betalte stadig afgifter. Den store politiske forandring i toppen aendrede ikke vilkaarene i bunden."}'::jsonb,
  'mc','short','{"concepts":["bonde","enevaelde","hverdagsliv","ingen forandring i bunden"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',3,'auto',true,'reformation_monarchy',6,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved forestillingen om at alle i Danmark bejede Reformationen i 1536?","options":["De katolske biskopper blev arresteret og mange i kirken modsatte sig Reformationen som Christian III gennemtvang med magt","Forestillingen er korrekt alle bejede Reformationen med glaede","Det er forkert fordi ingen stoettede Reformationen","Det er forkert fordi Reformationen kom gradvist uden modstand"],"correct":"De katolske biskopper blev arresteret og mange i kirken modsatte sig Reformationen som Christian III gennemtvang med magt","accepted_answers":["De katolske biskopper blev arresteret og mange i kirken modsatte sig Reformationen som Christian III gennemtvang med magt"],"review_text":"Christian III gennemfoerte Reformationen ved at arrestere de katolske biskopper. Det var ikke en fredelig overgang. Dele af adelen og kirken modsatte sig. Reformationen var en magtmassig gennemtvingning ikke en frivillig kollektiv beslutning."}'::jsonb,
  'mc','short','{"concepts":["modstand","biskopper","Christian III","gennemtvingning","misconception-alle-stoettede"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',3,'auto',true,'reformation_monarchy',6,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad aendrede Reformationen ved det enkelte menneskes forhold til Gud?","options":["I katolsk tradition var praesten mellemled til Gud. I luthersk tro var der en direkte linje mellem den troende og Gud","Luthersk tro kraevede at man boede i et kloster for at naerme sig Gud","I luthersk tro behoevede man ikke laengere at tro paa Gud","Reformationen aendrede intet ved forholdet til Gud kun gudstjenestesproget"],"correct":"I katolsk tradition var praesten mellemled til Gud. I luthersk tro var der en direkte linje mellem den troende og Gud","accepted_answers":["I katolsk tradition var praesten mellemled til Gud. I luthersk tro var der en direkte linje mellem den troende og Gud"],"review_text":"I den katolske kirke gik man til Gud via praesten og sakramenterne. Luther sagde at troen alene var nok. Man behoevede ikke kirken som mellemled. Det var et fundamentalt skift i synet paa menneskets forhold til Gud og autoritet."}'::jsonb,
  'mc','short','{"concepts":["direkte linje","Gud","tro","praestens rolle","Reformation"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',3,'auto',true,'reformation_monarchy',6,3
);

-- ─── GRADE 6 · BAND 4 (5 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad tror du at en dansk bonde syntes om Reformationen i 1536?","options":["Blandet: gudstjenesten paa dansk var bedre men den okonomiske undertrykkelse og den manglende frihed fortsatte","Ren glaede fordi Reformationen frigjorde boenderne fra adelen","Ren modstand fordi boenderne elskede den katolske kirke","Ligegyldighed fordi religion ikke betod noget for boenderne"],"correct":"Blandet: gudstjenesten paa dansk var bedre men den okonomiske undertrykkelse og den manglende frihed fortsatte","accepted_answers":["Blandet: gudstjenesten paa dansk var bedre men den okonomiske undertrykkelse og den manglende frihed fortsatte"],"review_text":"Bonden horte nu gudstjenesten paa dansk og forstod den bedre. Men bonden ejede stadig intet. Han betalte stadig afgifter. Reformationen aendrede hvem der regerede religionen men ikke hvem der ejede landet. Fra bondens perspektiv var den okonomiske virkelighed uforandret."}'::jsonb,
  'mc','short','{"concepts":["bonde-perspektiv","Reformation","okonomisk virkelighed","gudstjeneste"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',4,'auto',true,'reformation_monarchy',6,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var de to vigtigste aarsager til at den katolske kirke mistede saa megen magt i 1500-tallets Europa?","options":["Intern korruption i kirken svaekkede dens trovaerdighed og fyrsters okonomiske interesse i at overtage kirkens rigdomme","Kirken valgte frivilligt at opgive sin magt for at fokusere paa spiritualitet","Befolkningerne tvang kirken ved revolution","Paven beordrede kirkerne til at overgive magten til fyrsterne"],"correct":"Intern korruption i kirken svaekkede dens trovaerdighed og fyrsters okonomiske interesse i at overtage kirkens rigdomme","accepted_answers":["Intern korruption i kirken svaekkede dens trovaerdighed og fyrsters okonomiske interesse i at overtage kirkens rigdomme"],"review_text":"Kirken var svaeekket indefra. Korrupte praester og afladshandelen underminerede trovaerdigheden. Dertil kom at konger og fyrster saa en stor okonomisk mulighed i kirkens enorme ejendomme. Begge kraefter bidrog til kirkens magtfald."}'::jsonb,
  'mc','short','{"concepts":["korruption","kirkens magt","fyrster","okonomisk interesse","trovaerdighed"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',4,'auto',true,'reformation_monarchy',6,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var Luthers egentlige udfordring til den etablerede orden?","options":["Han sagde at den individuelle samvittighed og bibelen var autoritet over pavens og kirkens traditioner","Han sagde at konger burde afsaette paven militaert","Han sagde at al religion var forkert og burde afskaffes","Han sagde at kirken burde ejes af adelen og ikke af paven"],"correct":"Han sagde at den individuelle samvittighed og bibelen var autoritet over pavens og kirkens traditioner","accepted_answers":["Han sagde at den individuelle samvittighed og bibelen var autoritet over pavens og kirkens traditioner"],"review_text":"Luthers revolutionaere idé var enkel men farlig: bibelen og den personlige samvittighed er over kirkens tradition og pavens autoritet. Det udfordrede ikke blot religionen men hele den magtstruktur der var bygget paa kirkens monopol paa Guds ord."}'::jsonb,
  'mc','short','{"concepts":["individuel samvittighed","bibelen","autoritet","paven","revolution"],"misconception_type":"scope_confusion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',4,'auto',true,'reformation_monarchy',6,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forbindelsen mellem Reformationens ide om individets samvittighed og den gradvise vej mod demokrati?","options":["Reformationen fremhaevede individets evne til at fortolke bibelen selv og saaede froe til ideen om at individet ogsaa kan have politiske rettigheder","Reformationen indfoerte straks demokrati i alle lutherske lande","Der er ingen forbindels Reformationen og demokrati er helt uafhaengige","Reformationen forhindrede demokrati fordi den styrkede kongens magt"],"correct":"Reformationen fremhaevede individets evne til at fortolke bibelen selv og saaede froe til ideen om at individet ogsaa kan have politiske rettigheder","accepted_answers":["Reformationen fremhaevede individets evne til at fortolke bibelen selv og saaede froe til ideen om at individet ogsaa kan have politiske rettigheder"],"review_text":"Luthers ide om den individuelle samvittighed som autoritet var subversiv. Hvis den enkelt kan fortolke bibelen selv hvem sagde saa at han ikke ogsaa kan have en mening om politik? Det var ikke en direkte vej men froe der spirede over aarhundreder."}'::jsonb,
  'mc','short','{"concepts":["individuel samvittighed","demokrati","politiske rettigheder","langsigtede konsekvenser"],"misconception_type":"temporal_confusion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',4,'auto',true,'reformation_monarchy',6,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Var enevaeldet godt for det danske folk?","options":["Det afhang af hvem man spurgte: for borgerskabet gav det stabilitet men for adelen svaekkede det privilegier og for boenderne aendrede det naesten intet","Enevaeldet var godt for alle fordi kongen vaernede om alle borgeres interesser","Enevaeldet var skadeligt for alle fordi ingen kunne beklage sig","Enevaeldet var godt for adelen fordi de beholdt al magt"],"correct":"Det afhang af hvem man spurgte: for borgerskabet gav det stabilitet men for adelen svaekkede det privilegier og for boenderne aendrede det naesten intet","accepted_answers":["Det afhang af hvem man spurgte: for borgerskabet gav det stabilitet men for adelen svaekkede det privilegier og for boenderne aendrede det naesten intet"],"review_text":"Enevaeldet betod lov og orden og stabilitet som borgerskab og handel profiterede af. Adelen mistede sin politiske magt. Boenderne maerkede lidt forskel. Enevaelde var ikke simpelt godt eller ondt men et komplekst system med vindere og tabere."}'::jsonb,
  'mc','short','{"concepts":["enevaelde","perspektiver","borgerskab","adel","bonde"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"reformation_monarchy"}'::jsonb,
  'mc_single',4,'auto',true,'reformation_monarchy',6,4
);;
