-- Section 103 — World War 2 Band 5 Sprint
-- Creates the first genuine ceiling layer for advanced grade-9 students in world_war_2.
-- Prior to this migration world_war_2 had zero Band 5 questions despite being the
-- platform's largest domain (118 questions, 21 at Band 4).
--
-- 20 questions: target_grade=9, difficulty_band=5, domain=world_war_2, is_active=true
-- Focus: synthesis, evaluation, historiography, democratic lessons, ethical reasoning.
-- No factual recall. Every question requires genuine analytical judgment.

-- ─── BAND 5 · HISTORIOGRAPHY (6 questions) ───────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er den afgørende svaghed ved monokausal forklaring af Hitlers magtovertagelse med Versaillesfreden alene?","options":["Fordi mange europæiske lande led under lignende ydmygelse og fattigdom uden at vende sig til fascisme — forklaringen ignorerer det politiske agentur og de specifikke institutionelle og valgmæssige valg der muliggjorde nazismens fremvækst","Fordi Versaillesfreden faktisk var meget lemfældig over for Tyskland og ikke kan have haft nogen psykologisk effekt","Fordi den store depression ramte USA og ikke Europa og dermed ikke kan have haft nogen relevans for tysk politik","Fordi Hitler aldrig nævnte Versaillesfreden i sin politiske retorik og den var dermed uden politisk betydning"],"correct":"Fordi mange europæiske lande led under lignende ydmygelse og fattigdom uden at vende sig til fascisme — forklaringen ignorerer det politiske agentur og de specifikke institutionelle og valgmæssige valg der muliggjorde nazismens fremvækst","accepted_answers":["Fordi mange europæiske lande led under lignende ydmygelse og fattigdom uden at vende sig til fascisme — forklaringen ignorerer det politiske agentur og de specifikke institutionelle og valgmæssige valg der muliggjorde nazismens fremvækst"],"review_text":"Versaillesfreden skabte reel frustration i Tyskland. Men Portugal, Østrigs, Ungarns og mange andre landes befolkninger oplevede lignende national ydmygelse og fattigdom uden at producere fascisme. Versailles var en nødvendig men ikke tilstrækkelig forklaring. De afgørende faktorer var specifikke for Weimars institutionelle svaghed, de konservative politikeres undervurdering af Hitler i 1932-33 og Hitlers egne politiske evner. Monokausal forklaring gør det umuligt at forstå HVORFOR fascismen sejrede i netop Tyskland og dermed at forebygge lignende processer."}'::jsonb,
  'mc','short','{"concepts":["Versailles","monokausalitet","Weimarrepublikken","historiografi","politisk agentur"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',5,'auto',true,'world_war_2',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er den vigtigste konklusion i Christopher Brownings forskning i de mænd der udgjorde Reservepolitibataljon 101 under Holocaust?","options":["At almindelige middelaldrende mænd valgte aktivt at dræbe selv da de fik mulighed for at sige fra — og at konformitet, gruppepres og gradvis desensibilisering er stærkere forklaringer end fanatisme eller direkte tvang","At alle mænd i bataljonen var overbeviste nazister der udelukkende dræbte af ideologisk overbevisning","At soldaterne handlede udelukkende under direkte tvang og ikke havde noget reelt valg","At antisemitisme var en nødvendig forudsætning for at deltage — ingen dræbte uden at have internaliseret nazistisk raceideologi fuldt ud"],"correct":"At almindelige middelaldrende mænd valgte aktivt at dræbe selv da de fik mulighed for at sige fra — og at konformitet, gruppepres og gradvis desensibilisering er stærkere forklaringer end fanatisme eller direkte tvang","accepted_answers":["At almindelige middelaldrende mænd valgte aktivt at dræbe selv da de fik mulighed for at sige fra — og at konformitet, gruppepres og gradvis desensibilisering er stærkere forklaringer end fanatisme eller direkte tvang"],"review_text":"Browning viste at bataljonen eksplicit fik tilbud om at sige fra — og at de fleste alligevel valgte at dræbe. Ikke af fanatisme men af konformitet: man ville ikke svigte kammeraterne eller fremstå fejg. Gradvis desensibilisering betød at det første drab var det sværeste. Bataljonen var ikke særligt nazistisk ideologisk. Brownings pointe er ubehagelig: det kræver ikke monstre at begå massemordet. Det kræver situationelt pres, gruppenormer og bureaukratisk afstand til konsekvenserne — mekanismer der er universelt menneskelige."}'::jsonb,
  'mc','short','{"concepts":["Browning","Reservepolitibataljon 101","konformitet","gruppepres","desensibilisering","ordinary men"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',5,'auto',true,'world_war_2',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er kernen i Hannah Arendts begreb om ondskabens banalitet formuleret efter Eichmann-retssagen i Jerusalem?","options":["At Adolf Eichmann ikke var en sadistisk monster men en tankeløs bureaukrat der afgav sin moralske autonomi til systemet — og at ekstrem ondskab kan drives af manglende evne til at tænke frem for af had eller ideologisk fanatisme","At ondskab altid er banalt i den forstand at det er enkelt at begå og kræver minimal menneskelig indsats","At Eichmann var psykologisk normal og dermed skyldfri fordi normalitet fritager for moralsk ansvar","At systemisk ondskab kun er mulig under totalitære regimer og aldrig kan opstå i demokratier"],"correct":"At Adolf Eichmann ikke var en sadistisk monster men en tankeløs bureaukrat der afgav sin moralske autonomi til systemet — og at ekstrem ondskab kan drives af manglende evne til at tænke frem for af had eller ideologisk fanatisme","accepted_answers":["At Adolf Eichmann ikke var en sadistisk monster men en tankeløs bureaukrat der afgav sin moralske autonomi til systemet — og at ekstrem ondskab kan drives af manglende evne til at tænke frem for af had eller ideologisk fanatisme"],"review_text":"Arendts pointe var provokerende: Eichmann var hverken fjollet eller sadistisk. Han var en effektiv embedsmand der udførte ordrer uden at stille spørgsmål ved deres konsekvenser for virkelige mennesker. Det var ikke hadet der drev ham men fraværet af moralsk tænkning. Begrebet er dybt ubehageligt fordi det placerer Holocaust ikke i en undtagelsestilstand af monstrøsitet men i en potentiel normalitet: bureaukratisk lydighed og fraværet af refleksion kan producere folkemord. Arendts analyse er fortsat kontroversiel — mange historikere mener hun undervurderede Eichmanns ideologiske antisemitisme."}'::jsonb,
  'mc','short','{"concepts":["Arendt","ondskabens banalitet","Eichmann","bureaukrati","moralsk autonomi","tankeløshed"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',5,'auto',true,'world_war_2',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forskellen på intentionalistiske og funktionalistiske forklaringer af Holocausts opståen — og hvad er den historiografiske konsensus?","options":["Intentionalister mener Hitler planlagde folkemord fra starten — funktionalister mener den endelige løsning opstod gradvist via bureaukratisk radikalisering. Konsensus peger på en syntese: intentioner fandtes men den konkrete form opstod kumulativt","Funktionalisme er historiografisk korrekt og intentionalisme er fuldstændig afvist af alle seriøse historikere","Intentionalisme er den eneste videnskabeligt holdbare forklaring da Hitlers mål var nedskrevet i Mein Kampf","Distinktionen er akademisk irrelevant for forståelsen af Holocaust og undervises kun fordi historikere vil komplicere enkle sandheder"],"correct":"Intentionalister mener Hitler planlagde folkemord fra starten — funktionalister mener den endelige løsning opstod gradvist via bureaukratisk radikalisering. Konsensus peger på en syntese: intentioner fandtes men den konkrete form opstod kumulativt","accepted_answers":["Intentionalister mener Hitler planlagde folkemord fra starten — funktionalister mener den endelige løsning opstod gradvist via bureaukratisk radikalisering. Konsensus peger på en syntese: intentioner fandtes men den konkrete form opstod kumulativt"],"review_text":"Intentionalisterne (fx Lucy Dawidowicz) hævder at Hitler havde et folkemordsprojekt fra Mein Kampf. Funktionalisterne (fx Martin Broszat) hævder at den endelige løsning voksede frem funktionelt: bureaukrater konkurrerede om at radikalisere jødepolitikken uden et centralt direktiv. De fleste nutidige historikere — herunder Christopher Browning og Ian Kershaw — er funktionelle intentionalister: Hitler havde eliminatoriske intentioner men den konkrete form opstod i en kumulativ radikaliseringsproces drevet af bureaukratisk konkurrence og krigens pres. Distinktionen er vigtig fordi den bestemmer om ansvar er koncentreret hos Hitler alene eller distribueret i systemet som helhed."}'::jsonb,
  'mc','short','{"concepts":["intentionalisme","funktionalisme","historiografi","Holocaust-forklaring","Browning","Kershaw"],"misconception_type":"false_equivalence","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',5,'auto',true,'world_war_2',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er den vigtigste indvending mod kulturelle forklaringer der ser Holocaust som et produkt af en specifik national mentalitet snarere end universelle menneskelige mekanismer?","options":["At Holocaust fandt sted med aktiv medvirken fra borgere i mange europæiske lande og at eksperimentel socialpsykologi viser at systematisk ondskab er mulig for statistisk normale mennesker på tværs af kulturer","At kulturelle forklaringer er historiografisk umulige fordi kultur ikke kan måles videnskabeligt","At tyske kulturelle træk er fuldstændig unikke og ikke deles af nogen andre europæiske nationer","At kulturforklaringer er korrekte men politisk problematiske og bør undgås i offentlig diskurs"],"correct":"At Holocaust fandt sted med aktiv medvirken fra borgere i mange europæiske lande og at eksperimentel socialpsykologi viser at systematisk ondskab er mulig for statistisk normale mennesker på tværs af kulturer","accepted_answers":["At Holocaust fandt sted med aktiv medvirken fra borgere i mange europæiske lande og at eksperimentel socialpsykologi viser at systematisk ondskab er mulig for statistisk normale mennesker på tværs af kulturer"],"review_text":"Daniel Goldhagen argumenterede i Hitlers villige bødler (1996) at en specifik eliminatorisk antisemitisme i tysk kultur var den afgørende faktor. Modargumenterne er stærke: Holocaust involverede litauere, ukrainere, rumænere og franskmænd som aktive deltagere. Brownings forskning viser at mekanismerne er socialt universelle. Milgrams lydighedseksperimenter fandt identiske resultater i USA, Australien og Jordan. Kulturforklaringen risikerer at gøre Holocaust til noget der kun KAN ske i ét land — og det er den farligste af alle konklusioner fordi den fjerner universaliteten af forebyggelseslektionen."}'::jsonb,
  'mc','short','{"concepts":["Goldhagen","kulturforklaring","universelle mekanismer","komparativ analyse","nationalkarakter"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',5,'auto',true,'world_war_2',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad viser den gradvise eskalering af jødeforfølgelsen fra 1933 til 1945 om mekanismerne bag folkemord?","options":["At folkemord sjældent begynder med massemordet — det forudgås af juridisk diskrimination, social dehumanisering og gradvis normalisering der sænker barriererne for vold trin for trin","At folkemord altid er planlagt fra starten og gennemføres som ét koordineret program uden forudgående gradvise stadier","At eskalering primært drives af militær nødvendighed og ikke ideologi — krigslogikken tvang frem hvad ideologien ønskede","At eskaleringsmodellen beviser at det ikke ville have ændret noget at stoppe de tidlige stadier — konsekvensen ville have været den samme"],"correct":"At folkemord sjældent begynder med massemordet — det forudgås af juridisk diskrimination, social dehumanisering og gradvis normalisering der sænker barriererne for vold trin for trin","accepted_answers":["At folkemord sjældent begynder med massemordet — det forudgås af juridisk diskrimination, social dehumanisering og gradvis normalisering der sænker barriererne for vold trin for trin"],"review_text":"Gregory Stantons model viser eskalationen: klassifikation, symbolisering, diskrimination, dehumanisering, organisation, polarisering, forberedelse, forfølgelse, udryddelse, benægtelse. I Nazityskland: Nürnberglovene (1935) → Kristallnacht (1938) → ghettoer og deportationer → Wannsee-konferencen (1942) → industrialiseret folkemord. Hvert trin syntes umuligt at forudse men fulgte logisk af det foregående. Det er den vigtigste forebyggende lektie: folkedrab begynder ikke med gaskamrene. Det begynder med lovene, sproget og normaliseringen af diskrimination."}'::jsonb,
  'mc','short','{"concepts":["eskalering","folkemord","dehumanisering","normalisering","Stanton","forebyggelse"],"misconception_type":"causal_inversion","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',5,'auto',true,'world_war_2',9,5
);

-- ─── BAND 5 · ETHICAL REASONING (6 questions) ────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Var Neville Chamberlains appeasement-politik over for Hitler ved München-aftalen i 1938 rationel statspolitik eller naiv kapitulation?","options":["Overvejende naiv kapitulation — fordi appeasement-logikken undervurderede at revisionist-imperialistiske aktører ikke stopper ved ét indrømmelse, og de tolv vundne måneder blev bedre udnyttet af Tyskland end af de Allierede","Rationel statspolitik — fordi Britain og Frankrig var militært uforberedte og München gav afgørende tid til oprustning","En diplomatisk succes der mislykkedes udelukkende fordi Hitlers løgnagtighed var umulig at forudse på forhånd","Et nødvendigt skridt for at sikre folkelig opbakning til en kommende krig som Chamberlain vidste var uundgåelig"],"correct":"Overvejende naiv kapitulation — fordi appeasement-logikken undervurderede at revisionist-imperialistiske aktører ikke stopper ved ét indrømmelse, og de tolv vundne måneder blev bedre udnyttet af Tyskland end af de Allierede","accepted_answers":["Overvejende naiv kapitulation — fordi appeasement-logikken undervurderede at revisionist-imperialistiske aktører ikke stopper ved ét indrømmelse, og de tolv vundne måneder blev bedre udnyttet af Tyskland end af de Allierede"],"review_text":"Forsvarerne af appeasement peger på at Frankrig og England faktisk var militært svage i 1938. Men efterfølgende analyser viser at det ofrede Tjekkoslovakiet — med sit stærke militær og forsvarsindustri — udgjorde en betydelig magtbalance. De tolv måneder fra München til krigens udbrud udnyttede Tyskland til massiv militær opbygning i langt højere grad end de Allierede. Appeasement-logikken antog at Hitler var en rationel aktør med begrænsede reviderende mål — en antagelse der var historisk forkert. Lektionen for samtiden: diktatorer der bydes imødekommenhed fortolker det som svaghed."}'::jsonb,
  'mc','short','{"concepts":["appeasement","München","Chamberlain","rationel aktør","revisionist","lektie"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',5,'auto',true,'world_war_2',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Var de Allieredes strategiske bombekampagner mod tyske byer — herunder Dresden i februar 1945 — moralsk forsvarlige?","options":["Overvejende nej — bombningerne krænkede krigsrettens princip om distinktion mellem kombattanter og civile, og den militære nytte var tilstrækkelig usikker til at udgøre etisk problematiske beslutninger uanset krigens retfærdige formål","Ja — fordi krigen mod nazismen var en krig mod det absolutte onde og enhver taktik der afkortede krigen var dermed moralsk legitimeret","Ja — fordi Versaillesfreden specifikt pålagde Tyskland at alle civile bygninger måtte bruges militært og alle byer var dermed lovlige mål","Spørgsmålet er irrelevant — krigshandlinger kan ikke vurderes etisk fordi al krigsførelse befinder sig uden for moralens rækkevidde"],"correct":"Overvejende nej — bombningerne krænkede krigsrettens princip om distinktion mellem kombattanter og civile, og den militære nytte var tilstrækkelig usikker til at udgøre etisk problematiske beslutninger uanset krigens retfærdige formål","accepted_answers":["Overvejende nej — bombningerne krænkede krigsrettens princip om distinktion mellem kombattanter og civile, og den militære nytte var tilstrækkelig usikker til at udgøre etisk problematiske beslutninger uanset krigens retfærdige formål"],"review_text":"Det er legitimt at skelne: bombing af fabrikker og jernbaner var militært forsvarlig. Men ved Dresden, Hamburg og Köln var det eksplicitte formål at terrorisere civilbefolkningen og bryde kampviljen — en strategi uforenelig med distinktionsprincippet i humanitær folkeret. Det moralsk vanskellige er at nazismens forbrydelser var så extreme at de skabte et psykologisk fundament for at alt er tilladt — præcis den logik man kritiserede hos modparten. Retfærdig krig-teoriens krav om proportionalitet og distinktion gælder uanset fjendens moralske status."}'::jsonb,
  'mc','short','{"concepts":["Dresden","strategisk bombning","distinktionsprincippet","krigsret","just war","proportionalitet"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',5,'auto',true,'world_war_2',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er den afgørende forskel på kollektiv skyld og kollektivt ansvar i forbindelse med det tyske folk og Holocaust?","options":["Kollektiv skyld tilskriver moralsk fordømmelse til alle gruppemedlemmer uanset individuelle valg — kollektivt ansvar handler om hvad nulevende generationer har forpligtelse til at erkende og handle på selv om de personligt er uskyldige","Der er ingen meningsfuld forskel — begge begreber placerer den samme moralske forpligtelse på de samme mennesker","Kollektivt ansvar er stærkere end kollektiv skyld fordi det kræver materiel kompensation fra alle nulevende tyskere","Begge begreber er etisk uacceptable og bør afvises fuldstændigt i enhver diskussion om historisk retfærdighed"],"correct":"Kollektiv skyld tilskriver moralsk fordømmelse til alle gruppemedlemmer uanset individuelle valg — kollektivt ansvar handler om hvad nulevende generationer har forpligtelse til at erkende og handle på selv om de personligt er uskyldige","accepted_answers":["Kollektiv skyld tilskriver moralsk fordømmelse til alle gruppemedlemmer uanset individuelle valg — kollektivt ansvar handler om hvad nulevende generationer har forpligtelse til at erkende og handle på selv om de personligt er uskyldige"],"review_text":"Karl Jaspers skelnen fra 1946 er central. Juridisk skyld kan kun placeres på individer der handlede. Moralsk skyld er personlig. Men politisk ansvar — det Jaspers kalder kollektivt ansvar — tilkommer nationen som politisk enhed der bærer konsekvenserne af den historiske arv. Den nulevende tysker er ikke skyldig i Holocaust men har et ansvar for at den historiske erkendelse forbliver levende og informerer nutidens demokratiske praksis. Det er et afgørende skel: det muliggør erindring og handling uden at straffe mennesker for hvad de er født ind i."}'::jsonb,
  'mc','short','{"concepts":["kollektiv skyld","kollektivt ansvar","Jaspers","generationsansvar","historisk retfærdighed"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',5,'auto',true,'world_war_2',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvornår er modstand mod et totalitært styre ikke blot moralsk tilladt men moralsk forpligtende?","options":["Når den skade systemet forvolder er tilstrækkelig grav, fredelige alternativer er udtømt og man har kapacitet til effektiv modstand — og forpligtelsen stiger proportionalt med ens direkte involvering i systemets forbrydelser","Modstand er altid kun moralsk tilladt men aldrig forpligtende — den individuelle samvittighed har suveræn ret til at prioritere sin egen overlevelse","Modstand er kun moralsk forpligtende når den er garanteret at lykkes — meningsløs modstand er moralsk ligegyldig","Modstand er altid moralsk forpligtende under ethvert totalitært styre uanset risiko, kapacitet og udsigt til succes"],"correct":"Når den skade systemet forvolder er tilstrækkelig grav, fredelige alternativer er udtømt og man har kapacitet til effektiv modstand — og forpligtelsen stiger proportionalt med ens direkte involvering i systemets forbrydelser","accepted_answers":["Når den skade systemet forvolder er tilstrækkelig grav, fredelige alternativer er udtømt og man har kapacitet til effektiv modstand — og forpligtelsen stiger proportionalt med ens direkte involvering i systemets forbrydelser"],"review_text":"Retfærdig krig-teorien skelner mellem hvad man MÅ gøre og hvad man SKAL gøre. Modstand er tilladt og moralsk god i en vis udstrækning under totalitarisme. Den bliver forpligtende når skaden stiger til et niveau som et rationelt og moralsk menneske ikke kan tillade sig at ignorere. Proportionalitetsprincippet er centralt: en menig kommunal embedsmand er i en anden situation end en SS-officer der ved præcist hvad der foregår. Involvering øger forpligtelsen. Det forklarer hvorfor Stauffenbergs attentatforsøg er moralsk heroisk mens den passive kontormedarbejder er i en mere grådelig men ikke identisk moralsk position."}'::jsonb,
  'mc','short','{"concepts":["modstand","totalitarisme","moralsk forpligtelse","just war","proportionalitet","involvering"],"misconception_type":"scope_confusion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',5,'auto',true,'world_war_2',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad adskiller moralsk den passive tilskuer fra den aktive gerningsmand i analysen af medansvar under Holocaust?","options":["Ikke primært moralsk afstand men graden af bevidst valg, kendskab til konsekvenserne og objektiv mulighed for at handle anderledes — spektret er gradueret og alle positioner indebærer et proportionalt moralsk medansvar","Den passive tilskuer bærer intet moralsk ansvar — passivitet er moralsk neutral da den ikke involverer nogen aktiv handling","Tilskueren og gerningsmanden bærer præcis identisk moralsk ansvar fordi undladelse og handling er etisk fuldstændig ækvivalente","Kun de der direkte begik mord bærer moralsk ansvar — alle andre positioner er moralsk irrelevante for forståelsen af Holocaust"],"correct":"Ikke primært moralsk afstand men graden af bevidst valg, kendskab til konsekvenserne og objektiv mulighed for at handle anderledes — spektret er gradueret og alle positioner indebærer et proportionalt moralsk medansvar","accepted_answers":["Ikke primært moralsk afstand men graden af bevidst valg, kendskab til konsekvenserne og objektiv mulighed for at handle anderledes — spektret er gradueret og alle positioner indebærer et proportionalt moralsk medansvar"],"review_text":"Raul Hilbergs tredeling (gerningsmænd, ofre, tilskuere) peger på at tilskuere er etisk centrale: deres passivitet muliggjorde folkemordets fortsatte eskalation. Det er ikke det samme som at gøre tilskuere til mordere. Men analysen viser at mødet med den der lider skaber en moralsk fordring som det ikke er neutralt at afvise. Graden af ansvar stiger med graden af valg: den der havde mulighed for at hjælpe, kendte til konsekvenserne og valgte ikke at handle bærer mere ansvar end den der var fuldstændig uvidende og magtesløs. Spektret er kontinuerligt — ikke en binær fordeling."}'::jsonb,
  'mc','short','{"concepts":["tilskuer","gerningsmand","medansvar","moralsk spektrum","Hilberg","valg"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',5,'auto',true,'world_war_2',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er paradokset i at betragte Hitler som en historisk afvigelse snarere end som et produkt af identificerbare politiske og sociale processer?","options":["Forestillingen om afvigelse er psykologisk trøstende men historiografisk destruktiv: den befrier institutioner, partier og vælgere fra medansvar og gør det umuligt at forstå og dermed forebygge tilsvarende processer i fremtiden","Forestillingen er korrekt og nyttig fordi den præcist identificerer at kun en psykopat kan planlægge og gennemføre Holocaust","Paradokset er at afvigelse-forklaringen er historisk korrekt men politisk farlig — man bør bruge den analytisk men undgå den i offentlig diskurs","Forestillingen er hverken paradoksal eller problematisk — de fleste historikere er enige om at Hitler var et unikt og ugentageligt fænomen"],"correct":"Forestillingen om afvigelse er psykologisk trøstende men historiografisk destruktiv: den befrier institutioner, partier og vælgere fra medansvar og gør det umuligt at forstå og dermed forebygge tilsvarende processer i fremtiden","accepted_answers":["Forestillingen om afvigelse er psykologisk trøstende men historiografisk destruktiv: den befrier institutioner, partier og vælgere fra medansvar og gør det umuligt at forstå og dermed forebygge tilsvarende processer i fremtiden"],"review_text":"Fremstillingen af Hitler som et monster er psykologisk tillokkende. Den fritager os: vi ville aldrig have valgt ham, vi ville have modstået. Men forskning viser at Hitler vandt frie valg, at hans popularitet var reel, at normale mennesker begik massemordet og at institutioner frivilligt lod sig ensrette. Afvigelse-myten er det vigtigste forsvar mod at lektionen absorberes. Historiografisk er den farlig fordi den gør Holocaust til et produkt af personlighed snarere end af system, strukturer og kollektive valg — og derved fratager analysen dens forebyggende kraft."}'::jsonb,
  'mc','short','{"concepts":["Hitler","afvigelse","monster-myte","politiske processer","forebyggelse","historiografi"],"misconception_type":"scope_confusion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',5,'auto',true,'world_war_2',9,5
);

-- ─── BAND 5 · DEMOCRATIC LESSONS (4 questions) ───────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er det stærkeste argument for at Nürnberg-processerne repræsenterede legitim international ret snarere end blot sejrherrernes retfærdighed?","options":["At processerne etablerede det universelle princip at statslige aktører er individuelt ansvarlige for forbrydelser mod menneskeheden uanset national lovgivning — et princip sidenhen kodificeret i international ret og i princippet gældende for alle nationer","At dommerpanelet bestod af repræsentanter fra fire nationer og dermed repræsenterede international konsensus","At de tiltalte fik mulighed for at føre forsvar og proceduremæssigt fik en retfærdig retssag","At anklageskrifterne udelukkende fokuserede på handlinger der var ulovlige efter eksisterende tysk ret"],"correct":"At processerne etablerede det universelle princip at statslige aktører er individuelt ansvarlige for forbrydelser mod menneskeheden uanset national lovgivning — et princip sidenhen kodificeret i international ret og i princippet gældende for alle nationer","accepted_answers":["At processerne etablerede det universelle princip at statslige aktører er individuelt ansvarlige for forbrydelser mod menneskeheden uanset national lovgivning — et princip sidenhen kodificeret i international ret og i princippet gældende for alle nationer"],"review_text":"Indvendingen mod Nürnberg er at sejrherrerne dømte taberne for forbrydelser der ikke var entydigt definerede i international ret ved krigens start, og at Allierede handlinger (Dresden, Hiroshima, det sovjetiske folkemord) aldrig blev efterforsket. Det er en gyldig indvending. Men det afgørende argument for legitimiteten er at Nürnberg skabte et retsprincip — individuel ansvar for forbrydelser mod menneskeheden — der siden er anvendt mod aktører fra mange nationer i Den Internationale Straffedomstol. Prøven på om et juridisk princip er universelt og ikke politisk er netop om det anvendes konsekvent over tid."}'::jsonb,
  'mc','short','{"concepts":["Nürnberg","legitim ret","sejrherrernes retfærdighed","international strafferet","universalitet"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',5,'auto',true,'world_war_2',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er den vigtigste institutionelle lærdom fra nazismens fremkomst om hvad demokratier kræver for at overleve ekstremismens pres?","options":["At demokrati kræver mere end frie valg — det kræver uafhængige institutioner, konstitutionelle garantier for minoritetsrettigheder, en kritisk og informeret offentlighed og politisk vilje til aktivt at forsvare demokratiets spilleregler mod aktører der vil afvikle dem","At demokratiet primært overlever via stærk centralregering der hurtigt og hårdt slår ned på ekstremistiske bevægelser","At demokratier er naturligt immune mod intern afvikling og at Weimars sammenbrud var en unik historisk undtagelse uden generel lærdom","At det afgørende er det økonomiske system — kapitalisme beskytter demokratiet og ethvert socialistisk element nedbryder det"],"correct":"At demokrati kræver mere end frie valg — det kræver uafhængige institutioner, konstitutionelle garantier for minoritetsrettigheder, en kritisk og informeret offentlighed og politisk vilje til aktivt at forsvare demokratiets spilleregler mod aktører der vil afvikle dem","accepted_answers":["At demokrati kræver mere end frie valg — det kræver uafhængige institutioner, konstitutionelle garantier for minoritetsrettigheder, en kritisk og informeret offentlighed og politisk vilje til aktivt at forsvare demokratiets spilleregler mod aktører der vil afvikle dem"],"review_text":"Weimars fald viser at formelle demokratiske strukturer er utilstrækkelige: valgretten eksisterede, men institutionerne var svage. Forfatningsdomstolen fungerede ikke effektivt. Pressen var sårbar. De konservative der indbød Hitler undervurderede risikoen. Demokratiforskere som Levitsky og Ziblatt viser at demokratier oftere dør indefra — via valgte ledere der gradvist afvikler kontrolinstanser — end ved militærkup. Den institutionelle lærdom: demokratiet kræver aktivt forsvar af dets spilleregler og ikke blot afholdelse af valg."}'::jsonb,
  'mc','short','{"concepts":["demokrati","Weimarrepublikken","institutioner","demokratisk regression","spilleregler","aktiv forsvar"],"misconception_type":"overgeneralization","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',5,'auto',true,'world_war_2',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad kendetegner Tysklands model for Vergangenheitsbewältigung og hvad gør den til et muligt internationalt forbillede?","options":["En løbende institutionaliseret proces der integrerer ansvar for nazistiske forbrydelser som et permanent element i national identitet — via obligatorisk historieundervisning, forbud mod Holocaust-benægtelse, statslig erindringspolitik og materielle erstatninger — frem for at betragte forsoningen som afsluttet","En model der fokuserer på at glemme fortiden og vende blikket fremad for at undgå national splid og generationskonflikt","En juridisk model der udelukkende fokuserer på retsforfølgelse af konkrete gerningsmænd og ikke involverer den bredere befolkning","En model der er unik for Tysklands specifikke situation og ikke kan overføres til nationer med koloniale eller diktatoriske forbrydelser"],"correct":"En løbende institutionaliseret proces der integrerer ansvar for nazistiske forbrydelser som et permanent element i national identitet — via obligatorisk historieundervisning, forbud mod Holocaust-benægtelse, statslig erindringspolitik og materielle erstatninger — frem for at betragte forsoningen som afsluttet","accepted_answers":["En løbende institutionaliseret proces der integrerer ansvar for nazistiske forbrydelser som et permanent element i national identitet — via obligatorisk historieundervisning, forbud mod Holocaust-benægtelse, statslig erindringspolitik og materielle erstatninger — frem for at betragte forsoningen som afsluttet"],"review_text":"Vergangenheitsbewältigung er ikke en engangsbegivenhed men en løbende proces — det adskiller den afgørende fra mange andre landes tilgang. Kernen er at fortiden ikke betragtes som afsluttet men som permanent relevant for nutidens demokrati. Konkret: Holocaust-undervisning er obligatorisk, Holocaust-benægtelse er strafbart, der er et netværk af mindesmærker og museer og erstatninger er betalt til Israel og overlevende. Kritikken er at modellen fortsat primært fokuserer på jøders forfølgelse og i ringere grad på Tysklands koloniale forbrydelser. Som forbillede er den stærkest på institutionalisering og svagere på universel anvendelse."}'::jsonb,
  'mc','short','{"concepts":["Vergangenheitsbewältigung","erindringspolitik","historisk ansvar","institutionalisering","forbillede"],"misconception_type":"scope_confusion","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',5,'auto',true,'world_war_2',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var den strukturelle fejl i Folkeforbundets design der gjorde det ude af stand til at forhindre 2. Verdenskrig — og er fejlen korrigeret i FN?","options":["Folkeforbundet krævede enstemmighed og havde ingen bindende håndhævelsesmekanisme — og USA deltog aldrig. FN rettede dette delvist via Sikkerhedsrådet men introducerede vetorettens paralyserende dynamik som en ny strukturel svaghed","Folkeforbundet fejlede fordi det var for aggressivt og provokerede stormagterne til at forlade det","Fejlen var at Folkeforbundet ikke inkluderede Nazityskland som fuldgyldigt medlem fra starten","FN har fuldt ud rettet Folkeforbundets fejl og er i dag en funktionel verdensregering med reelt effektive håndhævelsesmekanismer"],"correct":"Folkeforbundet krævede enstemmighed og havde ingen bindende håndhævelsesmekanisme — og USA deltog aldrig. FN rettede dette delvist via Sikkerhedsrådet men introducerede vetorettens paralyserende dynamik som en ny strukturel svaghed","accepted_answers":["Folkeforbundet krævede enstemmighed og havde ingen bindende håndhævelsesmekanisme — og USA deltog aldrig. FN rettede dette delvist via Sikkerhedsrådet men introducerede vetorettens paralyserende dynamik som en ny strukturel svaghed"],"review_text":"Folkeforbundets design-fejl var fundamental: beslutninger krævede enstemmighed og USA ratificerede aldrig traktaten. Folkeforbundet kunne ikke stoppe Japans invasion af Manchuriet (1931) eller Italiens invasion af Etiopien (1935). FN forbedrede dette med et Sikkerhedsråd der kan handle ved kvalificeret flertal — men de fem permanente membres vetoret reproducerer en ny version af den samme svaghed: stormagtsinteresser kan blokere handling. Ruslands og Kinas veto over Syrien er et nutidigt eksempel. Internationalt samarbejde rummer en strukturel spænding mellem magtpolitik og universel håndhævelse som endnu ikke er løst."}'::jsonb,
  'mc','short','{"concepts":["Folkeforbundet","FN","strukturel fejl","enstemmighed","vetoretten","håndhævelse"],"misconception_type":"false_equivalence","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',5,'auto',true,'world_war_2',9,5
);

-- ─── BAND 5 · SYNTHESIS & CONTEMPORARY RELEVANCE (4 questions) ───────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er den afgørende konsekvens af Holocaust for international rets forståelse af forholdet mellem statssuverænitet og borgerbeskyttelse?","options":["At statssuverænitet ikke beskytter en stats ret til systematisk at forfølge og myrde sine egne borgere — og at det internationale samfund under visse betingelser har en moralsk og retlig forpligtelse til at intervenere som formuleret i Responsibility to Protect-doktrinen","At statssuverænitet er absolut og at intet udefrakommende indgreb i en stats interne anliggender nogensinde kan retfærdiggøres uanset handlingernes karakter","At FNs oprettelse betød at stater afgav deres suverænitet fuldstændigt og er underlagt løbende international overvågning på alle politikområder","At Holocaust ikke ændrede international rets forståelse af statssuverænitet — FN-pagten bekræftede uindskrænket statssuverænitet"],"correct":"At statssuverænitet ikke beskytter en stats ret til systematisk at forfølge og myrde sine egne borgere — og at det internationale samfund under visse betingelser har en moralsk og retlig forpligtelse til at intervenere som formuleret i Responsibility to Protect-doktrinen","accepted_answers":["At statssuverænitet ikke beskytter en stats ret til systematisk at forfølge og myrde sine egne borgere — og at det internationale samfund under visse betingelser har en moralsk og retlig forpligtelse til at intervenere som formuleret i Responsibility to Protect-doktrinen"],"review_text":"FN-pagten af 1945 indeholdt en spænding: den fastslog statssuverænitet men anerkendte universelle menneskerettigheder. Holocaust var den direkte katalysator for Menneskerettighedserklæringen (1948) og gradvist for Responsibility to Protect-doktrinen (R2P, vedtaget 2005) der slår fast at det internationale samfund har ansvar for at beskytte borgere mod masseforbrydelser når deres stat fejler. R2P er kontroversiel fordi den kolliderer med suverænitetsprincippet og er svær at håndhæve konsekvent — men den repræsenterer en direkte institutionel reaktion på Holocaust-lektionen."}'::jsonb,
  'mc','short','{"concepts":["statssuverænitet","R2P","humanitær intervention","FN","menneskeret","Holocaust-konsekvens"],"misconception_type":"false_equivalence","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',5,'auto',true,'world_war_2',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er det vigtigste argument imod påstanden om at Holocaust er et historisk unikt fænomen der ikke kan sammenlignes med andre folkedrab?","options":["At komparativ folkemordsforskning identificerer strukturelle mønstre der går igen på tværs af kontekster — og at overbetoningen af unikhed risikerer at gøre forebyggelseslektionerne uanvendelige i nye sammenhænge som Rwanda og Cambodja","At Holocaust var langt mindre systematisk end andre folkedrab og dermed ikke er exceptionelt men snarere rutinepræget","At jøder aldrig har været udsat for forfølgelse inden Holocaust og at alle sammenligninger med andre grupper derfor er anakronistiske","At Holocausts industrielle skala gør det til det eneste reelle folkedrab i historien mens alle andre er af en fundamentalt anderledes karakter"],"correct":"At komparativ folkemordsforskning identificerer strukturelle mønstre der går igen på tværs af kontekster — og at overbetoningen af unikhed risikerer at gøre forebyggelseslektionerne uanvendelige i nye sammenhænge som Rwanda og Cambodja","accepted_answers":["At komparativ folkemordsforskning identificerer strukturelle mønstre der går igen på tværs af kontekster — og at overbetoningen af unikhed risikerer at gøre forebyggelseslektionerne uanvendelige i nye sammenhænge som Rwanda og Cambodja"],"review_text":"Debatten om Holocausts unikhed er reel og historiografisk vigtig. Argumentet for unikhed er at kombinationen af industriel systematik, ideologisk totalitet og statslig kapacitet er historisk enestående. Argumentet imod eksklusiv unikhed er at det kan isolere Holocaust fra den komparative analyse der er nødvendig for forebyggelse. Rwanda (1994) og Cambodja (1975-79) viste lignende eskaleringsmønstre: dehumanisering, statsapparatets mobilisering, international passivitet. Spørgsmålet er ikke om Holocaust er det moralsk værste men om lektionerne er universelt overførbare."}'::jsonb,
  'mc','short','{"concepts":["Holocaust unikhed","komparativ folkemordsforskning","Rwanda","forebyggelse","universalitet"],"misconception_type":"scope_confusion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',5,'auto',true,'world_war_2',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Under hvilke betingelser er militær humanitær intervention i en fremmed stats interne anliggender etisk forsvarlig?","options":["Når systematiske og grove krænkelser af menneskeret er dokumenterede, fredelige midler er udtømt, interventionen er proportional og primært humanitært motiveret og der er rimelig udsigt til at begrænse skaden","Humanitær militær intervention er aldrig etisk forsvarlig fordi statssuverænitet er absolut og ukrænkelig","Enhver intervention foretaget af demokratier mod diktaturer er etisk forsvarlig uanset konkrete omstændigheder","Intervention er kun forsvarlig hvis den er godkendt af det angrebne lands befolkning via forudgående folkeafstemning"],"correct":"Når systematiske og grove krænkelser af menneskeret er dokumenterede, fredelige midler er udtømt, interventionen er proportional og primært humanitært motiveret og der er rimelig udsigt til at begrænse skaden","accepted_answers":["Når systematiske og grove krænkelser af menneskeret er dokumenterede, fredelige midler er udtømt, interventionen er proportional og primært humanitært motiveret og der er rimelig udsigt til at begrænse skaden"],"review_text":"Just war-teoriens kriterier for retfærdig krig — retfærdig årsag, last resort, proportionalitet, rimelig udsigt til succes — gælder også for humanitær intervention. R2P-doktrinen (2005) kodificerede dette i FN-regi. Paradokset er at lande med kapacitet til at intervenere sjældent handler rent humanitært. Irakkrigen (2003) hævdede humanitær begrundelse men var primært strategisk motiveret — hvilket underminerede doktrinens troværdighed. Rwanda (1994) viste modsatrettede fejl: kapaciteten var til stede men den politiske vilje manglede. Spørgsmålet er aktuelt og uløst."}'::jsonb,
  'mc','short','{"concepts":["humanitær intervention","R2P","just war","proportionalitet","last resort","statssuverænitet"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',5,'auto',true,'world_war_2',9,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Kan den europæiske integration siden 1945 forstås som en bevidst institutionel reaktion på nationalismens destruktive potentiale — og har projektet haft den tiltænkte effekt?","options":["Ja som reaktion — grundlæggernes eksplicitte formål var at gøre fremtidig europæisk storkrig umulig via økonomisk og politisk interdependens. Effekten er reel men ufuldstændig: ingen krig mellem EU-lande siden 1945 men nationalismen er vendt stærkt tilbage","Nej — EU var udelukkende et handelsprojekt uden noget historisk eller fredspolitisk formål","Ja og med fuld succes — nationalisme er elimineret som politisk kraft i Europa og kan ikke genopstå","EU er skabt som svar på Den Kolde Krig og ikke som reaktion på 2. Verdenskrig og nationalisme"],"correct":"Ja som reaktion — grundlæggernes eksplicitte formål var at gøre fremtidig europæisk storkrig umulig via økonomisk og politisk interdependens. Effekten er reel men ufuldstændig: ingen krig mellem EU-lande siden 1945 men nationalismen er vendt stærkt tilbage","accepted_answers":["Ja som reaktion — grundlæggernes eksplicitte formål var at gøre fremtidig europæisk storkrig umulig via økonomisk og politisk interdependens. Effekten er reel men ufuldstændig: ingen krig mellem EU-lande siden 1945 men nationalismen er vendt stærkt tilbage"],"review_text":"Robert Schuman, Jean Monnet og Konrad Adenauer var eksplicitte: formålet med Kul- og Stålunionen (1951) var at gøre krig umulig ved at sammenflette de industrier der havde drevet to verdenskrige. Det har virket på interstatstats-niveau: ingen krig mellem EU-lande i 70 år. Men Brexit, Ungarns og Polens demokratiske regression og voksende nationalistiske partier i Frankrig, Italien og Sverige viser at integrationsprojektet ikke har elimineret nationalismen — det har blot sat den i bero under de rette betingelser. Projektet er ufærdigt."}'::jsonb,
  'mc','short','{"concepts":["EU","europæisk integration","nationalisme","Schuman","interdependens","demokratisk regression"],"misconception_type":"overgeneralization","cognitive_skill":"synthesis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',5,'auto',true,'world_war_2',9,5
);
