-- Section 147B — Cold War Grade 7 Capacity Expansion
-- cold_war, target_grade=7, is_active=true
-- Distribution: B1(2) + B2(4) + B3(6) + B4(5) + B5(3) = 20 questions

-- ─── BAND 1 (2 questions) ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $q1${"question":"Hvad var Marshallplanen og hvem stod bag den?","options":["Et amerikansk hjælpeprogram fra 1948 der gav milliarder til at genopbygge Vesteuropa efter 2. verdenskrig for at forhindre kommunismens udbredelse","En sovjet-plan for at bygge en mur tværs gennem Europa for at adskille øst og vest","En aftale mellem USA og Sovjet om at dele Europa i to militære zoner","Et dansk program for at sende hjælp til lande ødelagt af atomvåben"],"correct":"Et amerikansk hjælpeprogram fra 1948 der gav milliarder til at genopbygge Vesteuropa efter 2. verdenskrig for at forhindre kommunismens udbredelse","accepted_answers":["Et amerikansk hjælpeprogram fra 1948 der gav milliarder til at genopbygge Vesteuropa efter 2. verdenskrig for at forhindre kommunismens udbredelse"],"review_text":"Efter 2. verdenskrig var Europa i ruiner. USA lancerede Marshallplanen i 1948 og sendte milliarder af dollars til at genopbygge Vesteuropa. Formålet var dobbelt: hjælpe Europa og forhindre at fattigdom og kaos ville gøre lande sårbare over for kommunistiske bevaegelser. Sovjet afviste planen og forbød sine satellitlande at tage imod hjaelpen. Det cementerede opdelingen af Europa i to blokke."}$q1$::jsonb,
  'mc','short',$m1${"concepts":["Marshallplanen","genopbygning","kommunismebekaempelse","USA","Vesteuropa"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"recognition","insight_type":"concept_clarification","challenge_role":"entry_level","domain":"cold_war"}$m1$::jsonb,
  'mc_single',1,'auto',true,'cold_war',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $q2${"question":"Hvad var Koreakrigen (1950-1953) og hvad var dens forbindelse til Den Kolde Krig?","options":["En proxy-krig hvor USA stoettede Sydkorea og Kina samt Sovjet stoettede Nordkorea — et eksempel paa at Den Kolde Krig ofte udspillede sig via krige i andre lande","En krig direkte mellem USA og Sovjet om kontrollen over Korea","En intern borgerkrig i Korea der ikke havde noget med Den Kolde Krig at goere","En krig der endte med at Korea blev forenet under et kommunistisk styre"],"correct":"En proxy-krig hvor USA stoettede Sydkorea og Kina samt Sovjet stoettede Nordkorea — et eksempel paa at Den Kolde Krig ofte udspillede sig via krige i andre lande","accepted_answers":["En proxy-krig hvor USA stoettede Sydkorea og Kina samt Sovjet stoettede Nordkorea — et eksempel paa at Den Kolde Krig ofte udspillede sig via krige i andre lande"],"review_text":"Koreakrigen (1950-53) var det forste store militaere sammenstoed i Den Kolde Krig. Da Nordkorea invaderede Sydkorea, svarede USA og FN-styrker. Over 36.000 amerikanere og millioner af koreanere omkom. Krigen endte uafgjort — Korea er stadig delt ved den 38. breddegrad. Det var et klassisk eksempel paa en proxy-krig: USA og Sovjet/Kina kaempede mod hinanden via andre landes haere for at undgaa direkte atomkonfrontation."}$q2$::jsonb,
  'mc','short',$m2${"concepts":["Koreakrigen","proxy-krig","USA","Nordkorea","Sydkorea","Den Kolde Krig"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"recognition","insight_type":"concept_clarification","challenge_role":"entry_level","domain":"cold_war"}$m2$::jsonb,
  'mc_single',1,'auto',true,'cold_war',7,1
);

-- ─── BAND 2 (4 questions) ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $q3${"question":"Hvad var oprustningskapløbet under Den Kolde Krig?","options":["Den gensidige opbygning af stadig mere avancerede atomvaaben og militaer kapacitet mellem USA og Sovjet — begge parter frygtede at den anden ville opnaa militaer overlegenhed","En konkurrence om hvem der hurtigst kunne genopbygge sin oekonomi efter 2. verdenskrig","En kapløb om at opruste Europa med konventionelle styrker for at forhindre invasion fra Mellemsøsten","En konkurrence om at vaere den forste til at sende et menneske til Maanen"],"correct":"Den gensidige opbygning af stadig mere avancerede atomvaaben og militaer kapacitet mellem USA og Sovjet — begge parter frygtede at den anden ville opnaa militaer overlegenhed","accepted_answers":["Den gensidige opbygning af stadig mere avancerede atomvaaben og militaer kapacitet mellem USA og Sovjet — begge parter frygtede at den anden ville opnaa militaer overlegenhed"],"review_text":"Oprustningskapløbet var en central drivkraft i Den Kolde Krig. Da Sovjet testede sin forste atombombe i 1949 var det et chok for USA som troede de havde monopolet. Herefter udviklede begge lande stadig kraftigere vaaben. I 1960'erne havde begge sider nok vaaben til at udslette menneskeheden mange gange. Det skabte en paradoksal situation: jo mere man oprustede, jo mere sikker var man paa at begge parter ville blive odelagt ved krig."}$q3$::jsonb,
  'mc','short',$m3${"concepts":["oprustningskapløbet","atomvaaben","militaer overlegenhed","USA","Sovjet","brintbombe"],"misconception_type":"surface_association","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"concept_clarification","challenge_role":"reinforcement","domain":"cold_war"}$m3$::jsonb,
  'mc_single',2,'auto',true,'cold_war',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $q4${"question":"Hvordan brugte USA og Sovjet propaganda under Den Kolde Krig?","options":["Begge sider brugte systematisk propaganda til at fremstille deres eget system som overlegent og modstanderens som ondskabsfuldt — via film, radio, aviser og kulturelle programmer","Kun Sovjet brugte propaganda — USA havde fri presse og brugte aldrig bevidst propaganda","Propaganda spillede en uvaesentlig rolle fordi borgerne paa begge sider gennemskuede det hurtigt","Propaganda var kun rettet mod neutrale lande — borgere i USA og Sovjet fik altid sandfaerdig information"],"correct":"Begge sider brugte systematisk propaganda til at fremstille deres eget system som overlegent og modstanderens som ondskabsfuldt — via film, radio, aviser og kulturelle programmer","accepted_answers":["Begge sider brugte systematisk propaganda til at fremstille deres eget system som overlegent og modstanderens som ondskabsfuldt — via film, radio, aviser og kulturelle programmer"],"review_text":"Propaganda var en central del af Den Kolde Krig — en ideekrig ligesaa meget som en militaer konflikt. USA brugte Voice of America, CIA-finansierede kulturprogrammer og Hollywood-film. Sovjet brugte statsmedier og stoette til kommunistiske bevaegelser globalt. Begge sider forsoegte at vinde de ikke-allierede nationers sympati. Propaganda var ikke kun loegn — den ramte ogsaa reelle svagheder hos modstanderen."}$q4$::jsonb,
  'mc','short',$m4${"concepts":["propaganda","ideologisk krig","Voice of America","CIA","Hollywood","Sovjet-medier"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"cold_war"}$m4$::jsonb,
  'mc_single',2,'auto',true,'cold_war',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $q5${"question":"Hvad var afspænding (détente) og hvad opnaaede man i 1970'erne?","options":["En periode med forsigtigt diplomatisk samarbejde og nedrustningsaftaler mellem USA og Sovjet der reducerede den umiddelbare atomrisiko selvom grundlæggende uenigheder forblev","En permanent fred der betød at Den Kolde Krig reelt sluttede i 1970'erne","En aftale om at dele verden i to adskilte sfærer med absolut non-intervention i hinandens zone","Et kulturelt samarbejde der betød at borgere frit kunne rejse mellem øst og vest"],"correct":"En periode med forsigtigt diplomatisk samarbejde og nedrustningsaftaler mellem USA og Sovjet der reducerede den umiddelbare atomrisiko selvom grundlæggende uenigheder forblev","accepted_answers":["En periode med forsigtigt diplomatisk samarbejde og nedrustningsaftaler mellem USA og Sovjet der reducerede den umiddelbare atomrisiko selvom grundlæggende uenigheder forblev"],"review_text":"Afspænding (détente paa fransk) var 1970'ernes forsøg paa at normalisere forholdet mellem supermagterne. Nixon besøgte Kina i 1972, SALT I-traktaten (1972) begrænsede strategiske atomvåben, og Helsingfors-aftalen (1975) anerkendte Europas grænser. Det reducerede den umiddelbare krigsrisiko — men Den Kolde Krig fortsatte. Afspændingen kollapsede da Sovjet invaderede Afghanistan i 1979 og Reagan genoptog en haaard konfrontationslinje. Afspænding var en pause, ikke en fred."}$q5$::jsonb,
  'mc','short',$m5${"concepts":["afspænding","détente","SALT","Nixon","Helsingfors","nedrustning"],"misconception_type":"overgeneralization","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"cold_war"}$m5$::jsonb,
  'mc_single',2,'auto',true,'cold_war',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $q6${"question":"Hvad var Berlin-blokaden (1948-49) og hvad viste den om Den Kolde Krig?","options":["Sovjet afskærede alle forsyninger til Vestberlin for at tvinge de vestlige allierede ud — USA og allierede svarede med en massiv luftbro der forsynede byen i 11 måneder","USA blokerede al handel med Østberlin for at straffe Sovjet for delingen af Europa","Vestberlin blokerede selv vejen ind fra øst for at forhindre kommunister i at rejse frit","FN blokerede Berlin for at forhindre et nyt militært sammenstød"],"correct":"Sovjet afskærede alle forsyninger til Vestberlin for at tvinge de vestlige allierede ud — USA og allierede svarede med en massiv luftbro der forsynede byen i 11 måneder","accepted_answers":["Sovjet afskærede alle forsyninger til Vestberlin for at tvinge de vestlige allierede ud — USA og allierede svarede med en massiv luftbro der forsynede byen i 11 måneder"],"review_text":"I juni 1948 blokerede Sovjet alle landveje og jernbaner til Vestberlin. Formålet var at tvinge vestmagterne til at opgive Vestberlin. USA og allierede svarede med en luftbro der i 11 måneder dagligt fløj mad, kul og forsyninger ind. Sovjet gav op i maj 1949. Blokaden viste Den Kolde Krigs logik: konfrontation uden direkte skud — men med enorm spænding."}$q6$::jsonb,
  'mc','short',$m6${"concepts":["Berlin-blokaden","luftbro","Vestberlin","Sovjet","konfrontation","1948"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"concept_clarification","challenge_role":"reinforcement","domain":"cold_war"}$m6$::jsonb,
  'mc_single',2,'auto',true,'cold_war',7,2
);

-- ─── BAND 3 (6 questions) ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $q7${"question":"Hvad var Glasnost og Perestrojka og hvad var Gorbatjovs formal med dem?","options":["Reformprogrammer lanceret i 1980'erne — Glasnost (aabenhed) betød mere ytringsfrihed og Perestrojka (omstrukturering) betød ökonomiske reformer — formalet var at redde det sovjetiske system men reformerne accelererede i stedet dets sammenbrud","Militaere programmer der skulle modernisere den sovjetiske haer og gore den i stand til at besejre NATO","Propagandaprogrammer der skulle overbevise vestlige borgere om kommunismens overlegenhed","Aftaler med USA om fælles nedrustning der betod at begge sider afviklede storstedelen af deres atomvåben"],"correct":"Reformprogrammer lanceret i 1980'erne — Glasnost (aabenhed) betød mere ytringsfrihed og Perestrojka (omstrukturering) betød ökonomiske reformer — formalet var at redde det sovjetiske system men reformerne accelererede i stedet dets sammenbrud","accepted_answers":["Reformprogrammer lanceret i 1980'erne — Glasnost (aabenhed) betød mere ytringsfrihed og Perestrojka (omstrukturering) betød ökonomiske reformer — formalet var at redde det sovjetiske system men reformerne accelererede i stedet dets sammenbrud"],"review_text":"Gorbatjov lancerede reformerne for at redde et Sovjet der stagnerede okonomisk. Glasnost gav relativ pressefrihed. Perestrojka forsoegte markedslignende reformer af planokonomien. Ironien var at reformerne udlosdte de kraefter der styrtede systemet: frihed til at tale betod frihed til at kraeve mere frihed. Da Gorbatjov ikke ville bruge militaer magt til at holde Ostblokken nede, kollapsede den i 1989-91."}$q7$::jsonb,
  'mc','short',$m7${"concepts":["Glasnost","Perestrojka","Gorbatjov","reformer","Sovjet-sammenbrud","aabenhed"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"challenge","domain":"cold_war"}$m7$::jsonb,
  'mc_single',3,'auto',true,'cold_war',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $q8${"question":"Hvad var de vigtigste årsager til Sovjetunionens sammenbrud i 1991?","options":["En kombination af okonomisk stagnation, den militaere overbelastning fra oprustningskaplobeet og Afghanistan-krigen, Gorbatjovs reformer der udlosdte centrifugale kraefter og folkebevagelser i satellit-staterne","USA angreb Sovjet militaert i 1991 og tvang det til at overgive sig","Sovjet kollapsede udelukkende fordi Gorbatjov var en svag leder der personligt odelagde et ellers velfungerende system","Sovjet opgav frivilligt at vaere supermagt fordi lederne besluttede at demokrati var et bedre system end kommunisme"],"correct":"En kombination af okonomisk stagnation, den militaere overbelastning fra oprustningskaplobeet og Afghanistan-krigen, Gorbatjovs reformer der udlosdte centrifugale kraefter og folkebevagelser i satellit-staterne","accepted_answers":["En kombination af okonomisk stagnation, den militaere overbelastning fra oprustningskaplobeet og Afghanistan-krigen, Gorbatjovs reformer der udlosdte centrifugale kraefter og folkebevagelser i satellit-staterne"],"review_text":"Sovjet-sammenbruddet var resultatet af strukturelle svagheder opbygget i aartier. Planokonomien producerede nok vaaben men ikke nok forbrugsgoder. Afghanistan-krigen kostede 15.000 soldaterliv. Oprustningskaplobeet dranede en okonomi der aldrig var stor nok. Gorbatjovs reformer aabnede laaGet — og da han ikke ville skyde paa demonstranterne i Osteuropa, kollapsede imperiet: Polen, Ungarn, DDR, Tjekkoslovakiet, Rumaenien — og til sidst Sovjet selv i december 1991."}$q8$::jsonb,
  'mc','short',$m8${"concepts":["Sovjet-sammenbrud","planoekonomi","Afghanistan","Gorbatjov","folkebevagelser","1991"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"challenge","domain":"cold_war"}$m8$::jsonb,
  'mc_single',3,'auto',true,'cold_war',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $q9${"question":"Hvad var doktrinen om gensidig sikret odelaeggelse (MAD) og hvorfor betragtes den paradoksalt som en form for stabilitet?","options":["Doktrinen om at ethvert atomangreb ville udlose et gengaeldelsesangreb der ville odelaegge angriberen — det skabte paradoksal stabilitet fordi begge sider vidste at en krig ville betyde begges undergang","En aftale om at USA og Sovjet aldrig ville bruge atomvaaben fordi de var for farlige","Et offensivt program der planlagde hvornaar og hvordan man bedst kunne slaa til med atomvaaben forst","En doktrin der betod at begge sider opbyggede konventionelle styrker i stedet for atomvaaben"],"correct":"Doktrinen om at ethvert atomangreb ville udlose et gengaeldelsesangreb der ville odelaegge angriberen — det skabte paradoksal stabilitet fordi begge sider vidste at en krig ville betyde begges undergang","accepted_answers":["Doktrinen om at ethvert atomangreb ville udlose et gengaeldelsesangreb der ville odelaegge angriberen — det skabte paradoksal stabilitet fordi begge sider vidste at en krig ville betyde begges undergang"],"review_text":"MAD (Mutually Assured Destruction) var den uhyggelige logik bag Den Kolde Krigs relative fred. Begge supermagter havde nok atomvaaben til at udslette modstanderen — selv efter et forste angreb. Det betod at ingen rationel leder ville angribe. Fred gennem skaermt var reelt — ingen 3. verdenskrig broed ud. Men logikken forudsatte rationelle ledere: i 1983 var Sovjet-computere taet paa at udlose en atomalarm der viste sig at vaere falsk. Stanislav Petrov standsede en potentiel atomkrig."}$q9$::jsonb,
  'mc','short',$m9${"concepts":["MAD","gensidig odelaegelse","atomafskraekelse","paradoksal stabilitet","Petrov"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"challenge","domain":"cold_war"}$m9$::jsonb,
  'mc_single',3,'auto',true,'cold_war',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $q10${"question":"Hvad viste USA's engagement i Vietnam-krigen om Den Kolde Krigs logik og dens begrænsinIger?","options":["USA gik ind i Vietnam for at forhindre kommunismens udbredelse (dominoteorien) — men interventionen fejlede og viste at ideologisk engagement i proxy-krige ikke noedvendigvis kan vindes med militær styrke","USA vandt Vietnam-krigen og forhindrede effektivt kommunismens udbredelse i Sydostasien","Vietnam-krigen havde ingen forbindelse til Den Kolde Krig — det var en ren intern borgerkrig","USA gik ind i Vietnam fordi Sovjet direkte angreb amerikanske soldater"],"correct":"USA gik ind i Vietnam for at forhindre kommunismens udbredelse (dominoteorien) — men interventionen fejlede og viste at ideologisk engagement i proxy-krige ikke noedvendigvis kan vindes med militær styrke","accepted_answers":["USA gik ind i Vietnam for at forhindre kommunismens udbredelse (dominoteorien) — men interventionen fejlede og viste at ideologisk engagement i proxy-krige ikke noedvendigvis kan vindes med militær styrke"],"review_text":"USA's Vietnam-engagement (1955-75) var drevet af dominoteorien. USA sendte over 500.000 soldater og tabte 58.000 amerikanske liv — og trak sig alligevel ud i 1975. Nord-Vietnam vandt. Den mest magtfulde haer i verden kunne ikke besejre en guerillabevagelse med lokal stotte. Vietnam aendrede det amerikanske selvbillede og viste Cold War-logikkens begransninger."}$q10$::jsonb,
  'mc','short',$m10${"concepts":["Vietnam-krigen","dominoteorien","guerilla","proxy-krig","USA","kommunisme"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"challenge","domain":"cold_war"}$m10$::jsonb,
  'mc_single',3,'auto',true,'cold_war',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $q11${"question":"Hvad laerte Sovjet af sin krig i Afghanistan (1979-1989)?","options":["At militaer intervention i fremmede lande er ekstremt kostbar og kan undergrave selv en supermagt — ligesom Vietnam laerte USA at guerillakrige er naesten umulige at vinde","At moderne atomvaaben kan bruges til at vinde guerillakrige hurtigt og effektivt","At Afghanistan var en let militaer sejr der styrkede Sovjet og viste kommunismens militaere overlegenhed","At Sovjet med den rigtige strategi kunne have vundet — nederlaget skyldes udelukkende forraederi hjemme"],"correct":"At militaer intervention i fremmede lande er ekstremt kostbar og kan undergrave selv en supermagt — ligesom Vietnam laerte USA at guerillakrige er naesten umulige at vinde","accepted_answers":["At militaer intervention i fremmede lande er ekstremt kostbar og kan undergrave selv en supermagt — ligesom Vietnam laerte USA at guerillakrige er naesten umulige at vinde"],"review_text":"Sovjet invaderede Afghanistan i december 1979. USA stoettede islamistiske modstandskaempere (mujahideen) via CIA. 15.000 sovjetiske soldater omkom, og Sovjet trak sig ud i 1989 uden at have vundet. Afghanistan-krigen var Sovjet's Vietnam: en kostbar, tabt guerillakrig der accelererede Sovjet-sammenbruddet."}$q11$::jsonb,
  'mc','short',$m11${"concepts":["Afghanistan","guerillakrig","Sovjet","mujahideen","CIA","Vietnam-parallel"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"challenge","domain":"cold_war"}$m11$::jsonb,
  'mc_single',3,'auto',true,'cold_war',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $q12${"question":"Hvad var Helsingfors-aftalen (1975) og hvad var dens demokratiske betydning?","options":["En aftale der anerkendte Europas graenser og forpligtede alle signatarer — inklusiv Sovjet — til at respektere menneskerettigheder, som borgerne i Ostblokken brugte som platform for at kraeve rettigheder","En militaer aftale om at fjerne alle atomvaaben fra Europa og erstatte dem med konventionelle styrker","En aftale om permanent opdeling af Europa i ostlig og vestlig sfaere med absolut non-intervention","En handelsaftale der aabnede fri handel mellem Vest- og Osteuropa for forste gang"],"correct":"En aftale der anerkendte Europas graenser og forpligtede alle signatarer — inklusiv Sovjet — til at respektere menneskerettigheder, som borgerne i Ostblokken brugte som platform for at kraeve rettigheder","accepted_answers":["En aftale der anerkendte Europas graenser og forpligtede alle signatarer — inklusiv Sovjet — til at respektere menneskerettigheder, som borgerne i Ostblokken brugte som platform for at kraeve rettigheder"],"review_text":"Helsingfors-aftalen (1975) var afspendingstidens store diplomatiske resultat. Sovjet fik anerkendelse af de europaeiske graenser. Til gengaeld accepterede de forpligtelse til menneskerettigheder. Borgere i Polen og Tjekkoslovakiet brugte aftalen som juridisk platform til at kraeve rettigheder. Charta 77 og Solidarnosc blomstrede delvis i ly af Helsingfors-aftalen. Ord paa papir kan have reale konsekvenser."}$q12$::jsonb,
  'mc','short',$m12${"concepts":["Helsingfors","menneskerettigheder","Solidarnosc","Charta 77","afspending","ostblok"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"challenge","domain":"cold_war"}$m12$::jsonb,
  'mc_single',3,'auto',true,'cold_war',7,3
);

-- ─── BAND 4 (5 questions) ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $q13${"question":"Hvad er historikernes argument for at atomvaabnene faktisk forhindrede en 3. verdenskrig?","options":["Den gensidige atomtrussel forhindrede direkte stormagtskrig fordi rationelle ledere vidste at en krig ville betyde begge parters undergang — i modsaetning til 1. og 2. verdenskrig hvor magtbalancer kollapsede i regulaer krig","Atomvaabnene forhindrede ikke krig — 3. verdenskrig blev forhindret af FN's fredsbevarende styrker","Atomvaabnene spillede ingen rolle — USA og Sovjet ville aldrig have kaempet direkte mod hinanden","Atomvaabnene forhindrede krig fordi de var for komplekse og dyre til at bruge"],"correct":"Den gensidige atomtrussel forhindrede direkte stormagtskrig fordi rationelle ledere vidste at en krig ville betyde begge parters undergang — i modsaetning til 1. og 2. verdenskrig hvor magtbalancer kollapsede i regulaer krig","accepted_answers":["Den gensidige atomtrussel forhindrede direkte stormagtskrig fordi rationelle ledere vidste at en krig ville betyde begge parters undergang — i modsaetning til 1. og 2. verdenskrig hvor magtbalancer kollapsede i regulaer krig"],"review_text":"Den lange fred — at Vesteuropa ikke oplevede storkrig i 70+ aar — er historisk bemaerkelsesvaerdig. Historikere som John Lewis Gaddis argumenterer at atomafskraekkelse var noeglen. Magtbalancer uden atomvaaben kollapsede to gange paa 30 aar (1914, 1939). Med atomvaaben var prisen for fejlkalkulation saa hoej at rationelle aktorer valgte afspending frem for eskalation. Det er et ubehageligt men empirisk faktum."}$q13$::jsonb,
  'mc','short',$m13${"concepts":["atomafskraekkelse","den lange fred","Gaddis","bipolaritet","stabilitet","MAD"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"analytical_challenge","domain":"cold_war"}$m13$::jsonb,
  'mc_single',4,'auto',true,'cold_war',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $q14${"question":"Hvad er Den Kolde Krigs vigtigste arv i Rusland og den post-sovjetiske verden?","options":["En dyb national ydmygelse over imperiekollapset, mistillid til Vestens intentioner og en politisk kultur der soeger at genvinde stormagts-status — dynamikker der forklarer meget af Ruslands adfaerd efter 1991","Rusland omfavnede fuldt demokrati og markedsoekonomi efter 1991 og Den Kolde Krigs arv er fuldstaendig overvundet","Den Kolde Krig har ingen relevans for nutidigt Rusland — landet er fuldstaendig nyt siden 1991","Rusland er permanent svaekket og kan aldrig igen spille en vigtig rolle i international politik"],"correct":"En dyb national ydmygelse over imperiekollapset, mistillid til Vestens intentioner og en politisk kultur der soeger at genvinde stormagts-status — dynamikker der forklarer meget af Ruslands adfaerd efter 1991","accepted_answers":["En dyb national ydmygelse over imperiekollapset, mistillid til Vestens intentioner og en politisk kultur der soeger at genvinde stormagts-status — dynamikker der forklarer meget af Ruslands adfaerd efter 1991"],"review_text":"Sovjet-sammenbruddet var for mange russere et nationalt traume: imperiet gik tabt, levestandarden kollapsede i 1990'erne, og NATO udvidede sig ostpaa. Putin kaldte sammenbruddet 'det 20. aarhundredes storste geopolitiske katastrofe'. Russisk udenrigspolitik siden 2000 kan forstaaes som forsog paa at genvinde indflydelse: Georgien 2008, Ukraine 2014 og 2022. Den Kolde Krigs arv lever videre i geopolitikkens struktur."}$q14$::jsonb,
  'mc','short',$m14${"concepts":["Rusland","imperial arv","NATO-udvidelse","Putin","ydmygelse","post-sovjet"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"analytical_challenge","domain":"cold_war"}$m14$::jsonb,
  'mc_single',4,'auto',true,'cold_war',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $q15${"question":"Hvad betod Den Kolde Krig for landene i den tredje verden?","options":["Mange udviklingslande blev slagmarker for supermagternes proxy-krige og led enorme menneskelige tab — deres egne politiske valg blev undergravet af supermagt-intervention der prioriterede ideologisk loyalitet over lokal velfaerd","Den tredje verden noed godt af Den Kolde Krig fordi begge supermagter gav generoes bistand uden betingelser","Lande i den tredje verden var uinteressante for supermagterne og fik lov at udvikle sig i fred","Den Kolde Krig styrkede demokrati og stabilitet i de fleste lande i Afrika, Asien og Latinamerika"],"correct":"Mange udviklingslande blev slagmarker for supermagternes proxy-krige og led enorme menneskelige tab — deres egne politiske valg blev undergravet af supermagt-intervention der prioriterede ideologisk loyalitet over lokal velfaerd","accepted_answers":["Mange udviklingslande blev slagmarker for supermagternes proxy-krige og led enorme menneskelige tab — deres egne politiske valg blev undergravet af supermagt-intervention der prioriterede ideologisk loyalitet over lokal velfaerd"],"review_text":"Korea, Vietnam, Angola, Nicaragua, El Salvador, Afghanistan — overalt forsoegte begge supermagter at sikre sig loyale regimer. USA stoettede anti-kommunistiske diktatorer; Sovjet stoettede marxistiske regimer. Chile 1973: CIA stoettede kuppet mod den folkevalgte Allende. Det globale system 1945-89 kostede de fattigste stater uforholdsmaessigt dyrt."}$q15$::jsonb,
  'mc','short',$m15${"concepts":["tredje verden","proxy-krige","CIA","intervention","Chile","menneskelige omkostninger"],"misconception_type":"scope_confusion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"analytical_challenge","domain":"cold_war"}$m15$::jsonb,
  'mc_single',4,'auto',true,'cold_war',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $q16${"question":"Hvad viser Den Kolde Krigs teknologikaploop om sammenhaengen mellem militaer konkurrence og civil teknologiudvikling?","options":["Militaer konkurrence drev teknologiske gennembrud der sidenhen kom civilsamfundet til gode — internettet, GPS og satellitkommunikation stammer direkte fra Cold War-forskning","Al Cold War-teknologisk forskning var hemmeligt militaer og er aldrig delt med offentligheden","Teknologikaplobeet var rent spildt — ingen af opdagelserne har haft civile anvendelser","Kun rumfart-teknologien kom fra Den Kolde Krig — al anden moderne teknologi har andre rodder"],"correct":"Militaer konkurrence drev teknologiske gennembrud der sidenhen kom civilsamfundet til gode — internettet, GPS og satellitkommunikation stammer direkte fra Cold War-forskning","accepted_answers":["Militaer konkurrence drev teknologiske gennembrud der sidenhen kom civilsamfundet til gode — internettet, GPS og satellitkommunikation stammer direkte fra Cold War-forskning"],"review_text":"Internettets forgaenger ARPANET var et amerikansk militaerprojekt. GPS blev udviklet af det amerikanske forsvar. Satellitkommunikation udsprang af rumkaplobeet. Cold War-ressourcerne finansierede grundlaeggende teknologier vi alle bruger dagligt."}$q16$::jsonb,
  'mc','short',$m16${"concepts":["internet","ARPANET","GPS","satellit","teknologispin-off","militaerforskning"],"misconception_type":"scope_confusion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"analytical_challenge","domain":"cold_war"}$m16$::jsonb,
  'mc_single',4,'auto',true,'cold_war',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $q17${"question":"Hvad viste Cuba-krisen om nødvendigheden af direkte kommunikation mellem supermagterne?","options":["Cuba-krisen viste at mangel paa direkte kommunikation oegede atomrisikoen dramatisk — derfor oprettede USA og Sovjet en direkte krisekommunikationslinje (den rode telefon) i 1963","Cuba-krisen viste at supermagterne aldrig behovede direkte kommunikation — diplomater tog altid tid nok","Den rode telefon eksisterede allerede faar Cuba-krisen og spillede en afgørende rolle under selve krisen","Cuba-krisen viste at atomkrig var uundgaaelig og kun ren held forhindrede den"],"correct":"Cuba-krisen viste at mangel paa direkte kommunikation oegede atomrisikoen dramatisk — derfor oprettede USA og Sovjet en direkte krisekommunikationslinje (den rode telefon) i 1963","accepted_answers":["Cuba-krisen viste at mangel paa direkte kommunikation oegede atomrisikoen dramatisk — derfor oprettede USA og Sovjet en direkte krisekommunikationslinje (den rode telefon) i 1963"],"review_text":"Under Cuba-krisen (oktober 1962) tog det timer at sende beskeder via telegram. Som direkte resultat oprettede USA og Sovjet i 1963 en direkte kommunikationslinje. Den rode telefon var teknisk en teletype, ikke en telefon. Den blev brugt under Seksdagskrigen 1967 og Yom Kippur-krigen 1973. Kriser skaber ikke kun risiko men ogsaa institutionelle laeringsresponser."}$q17$::jsonb,
  'mc','short',$m17${"concepts":["rode telefon","Cuba-krisen","krisekommunikation","direkte linje","institutionel laering"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"causal","insight_type":"reframing","challenge_role":"analytical_challenge","domain":"cold_war"}$m17$::jsonb,
  'mc_single',4,'auto',true,'cold_war',7,4
);

-- ─── BAND 5 (3 questions) ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $q18${"question":"Var Den Kolde Krig uundgaaelig givet USA og Sovjet's ideologiske og geopolitiske modsaetninger?","options":["Revisionistiske historikere argumenterer at fejltagelser og misforstaaelser spillede en stor rolle — men strukturalisterne svarer at to supermagter med uforenelige ideologier og globale ambitioner naeppe kunne have undgaaet systematisk konfrontation","Den Kolde Krig var 100 procent uundgaaelig fordi kommunisme og kapitalisme er naaturnodvendigt fjendtlige","Den Kolde Krig var fuldt ud undgaaelig — to rationelle statsledere i 1945 var nok til at have forebygget hele konflikten","Sporgsmaalet er rent akademisk og har ingen relevans for nutidige supermagtsforhold"],"correct":"Revisionistiske historikere argumenterer at fejltagelser og misforstaaelser spillede en stor rolle — men strukturalisterne svarer at to supermagter med uforenelige ideologier og globale ambitioner naeppe kunne have undgaaet systematisk konfrontation","accepted_answers":["Revisionistiske historikere argumenterer at fejltagelser og misforstaaelser spillede en stor rolle — men strukturalisterne svarer at to supermagter med uforenelige ideologier og globale ambitioner naeppe kunne have undgaaet systematisk konfrontation"],"review_text":"Ortodokse historikere: Stalins ekspansionisme var uundgaaeligt konfronterende. Revisionistiske: USA's aggressive containment-politik drev konflikten. Post-revisionistiske: begge sider bidrog via misforstaaelse. Strukturalister: bipolaere systemer producerer afskraekkelse men ikke fred. Ingen enkelt faktor forklarer 45 aar med global spaending. Sporgsmaalet paavirker direkte om USA og Kina kan undgaa den samme dynamik."}$q18$::jsonb,
  'mc','short',$m18${"concepts":["uundgaaelighed","revisionisme","strukturalisme","bipolaritet","historikerdebat","USA-Kina"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}$m18$::jsonb,
  'mc_single',5,'auto',true,'cold_war',7,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $q19${"question":"Hvad fortæller Den Kolde Krig om stabiliteten i bipolare magtbalancesystemer sammenlignet med multipolære systemer?","options":["Bipolære systemer kan skabe en form for stabilitet fordi klare alliancer reducerer usikkerhed — men de er skrøbelige fordi eskalation i ét led kan sprede sig globalt og der er ingen tredjepart til at mægle","Bipolære systemer er altid mere stabile end multipolære fordi klare alliancer eliminerer al usikkerhed","Multipolære systemer er altid mere stabile fordi mange aktører balancerer hinanden og ingen enkelt aktør dominerer","Magtbalanceteorier er fuldstændig irrelevante — det var udelukkende ideologi der drev Den Kolde Krig"],"correct":"Bipolære systemer kan skabe en form for stabilitet fordi klare alliancer reducerer usikkerhed — men de er skrøbelige fordi eskalation i ét led kan sprede sig globalt og der er ingen tredjepart til at mægle","accepted_answers":["Bipolære systemer kan skabe en form for stabilitet fordi klare alliancer reducerer usikkerhed — men de er skrøbelige fordi eskalation i ét led kan sprede sig globalt og der er ingen tredjepart til at mægle"],"review_text":"Kenneth Waltz' neorealisme argumenterer at bipolære systemer paradoksalt er mere stabile end multipolære. Men Den Kolde Krig viste ogsaa skrøbelighed: Cuba-krisens naerved-atomkrig og Stanislav Petrovs falske raketvarsel i 1983. Sammenlignet med 1. verdenskrig — et multipolært alliancesystem der kollapsede lynhurtigt — holdt den bipolære orden. Men det er uklogt at se det som systemisk nødvendighed snarere end en kombination af rationelle aktører, held og MAD-logik."}$q19$::jsonb,
  'mc','short',$m19${"concepts":["bipolaritet","multipolaritet","Waltz","neorealisme","magtbalance","stabilitet"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}$m19$::jsonb,
  'mc_single',5,'auto',true,'cold_war',7,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $q20${"question":"Hvad er den analytisk vigtigste lektie Den Kolde Krig giver for forståelsen af nutidens forhold mellem USA og Kina?","options":["Historien viser at en etableret magt og en stigende magt hyppigt ender i konflikt — Den Kolde Krig demonstrerer at dette kan undgås med afskrækkelse og diplomati men kræver institutionelle kanaler og aktiv kriseforebyggelse","Den Kolde Krig viser at USA altid vinder og Kina vil kollapse ligesom Sovjet gjorde","Den Kolde Krig er fuldstændig irrelevant for USA-Kina-forholdet fordi situationen er fundamentalt anderledes","Den vigtigste lektie er at militær oprustning altid er den bedste løsning mod en rivaliserende supermagt"],"correct":"Historien viser at en etableret magt og en stigende magt hyppigt ender i konflikt — Den Kolde Krig demonstrerer at dette kan undgås med afskrækkelse og diplomati men kræver institutionelle kanaler og aktiv kriseforebyggelse","accepted_answers":["Historien viser at en etableret magt og en stigende magt hyppigt ender i konflikt — Den Kolde Krig demonstrerer at dette kan undgås med afskrækkelse og diplomati men kræver institutionelle kanaler og aktiv kriseforebyggelse"],"review_text":"Graham Allison identificerede at ud af 16 historiske tilfaelde hvor en stigende magt udfordrede en etableret magt, endte 12 i krig — Thukydides-faelden. Den Kolde Krig er et af de 4 der undgik krig. Lektionerne: institutionelle kommunikationskanaler, krisehåndtering ved Cuba, klare rode linjer og gensidig afskraekkelse forhindrede det vaerste. Den vigtigste lektie er at undgaaelse kraever aktivt institutionelt arbejde og vilje til diplomati."}$q20$::jsonb,
  'mc','short',$m20${"concepts":["Thukydides-faelde","USA-Kina","Allison","stigende magt","diplomati","kriseforebyggelse"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}$m20$::jsonb,
  'mc_single',5,'auto',true,'cold_war',7,5
);;
