-- Engelsk batch 2, 4. klasse bånd 3-4: 166 nye MC-spørgsmål (learning_objective='english', bånd 1-4).
-- Del af 1000 nye engelskspørgsmål til 3.-5. klasse. Samme indholds- og metadata-mønster som
-- 20261001000000_english_grade3_5; metadata afledes her af kategorinøglen k:
-- o=ordforråd, h=hverdagsudtryk, g=grammatik, l=læseforståelse. difficulty = bånd.
-- Bånd 1-2: reinforcement/conceptual_bridge. Bånd 3-4: challenge/reframing. All is_active=true.
-- Må KUN anvendes via apply_migration med særskilt ejer-autorisation (D-110).

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band)
SELECT
  jsonb_build_object('question', e->>'q', 'options', e->'o', 'correct', e->>'a',
                     'accepted_answers', jsonb_build_array(e->>'a'), 'review_text', e->>'r'),
  'mc', 'short',
  jsonb_build_object('concepts', jsonb_build_array(m.concept), 'cognitive_skill', m.skill,
                     'difficulty_type', m.dtype, 'misconception_type', m.mis,
                     'challenge_role', CASE WHEN (e->>'b')::int >= 3 THEN 'challenge' ELSE 'reinforcement' END,
                     'insight_type', CASE WHEN (e->>'b')::int >= 3 THEN 'reframing' ELSE 'conceptual_bridge' END,
                     'domain', 'english'),
  'mc_single', (e->>'b')::int, 'auto', true, 'english', (e->>'g')::int, (e->>'b')::int
FROM jsonb_array_elements($$[
{"g":4,"b":3,"k":"g","q":"Hvilken sætning beskriver noget, der sker lige nu?","o":["Tom reads comics every day.","Tom read a comic yesterday.","Tom will read a comic.","Tom is reading a comic."],"a":"Tom is reading a comic.","r":"'Is reading' (is + -ing) bruges om noget, der sker lige nu."},
{"g":4,"b":3,"k":"g","q":"Hvilken sætning beskriver en vane?","o":["I am playing tennis now.","I played tennis yesterday.","I play tennis every Tuesday.","I will play tennis tomorrow."],"a":"I play tennis every Tuesday.","r":"'Every Tuesday' (hver tirsdag) viser en vane. Så bruger man nutid: I play."},
{"g":4,"b":3,"k":"g","q":"Hvilket ord mangler? 'Listen! Somebody ___ at the door.'","o":["knocks","is knocking","knock","knocked"],"a":"is knocking","r":"'Listen!' viser, at det sker lige nu: is knocking = banker."},
{"g":4,"b":3,"k":"g","q":"Hvad er datid af 'go'?","o":["went","goed","gone","goes"],"a":"went","r":"'Go' er uregelmæssig: go → went. 'I went to school' = jeg gik i skole."},
{"g":4,"b":3,"k":"g","q":"Hvad er datid af 'see'?","o":["seed","seen","sees","saw"],"a":"saw","r":"'See' er uregelmæssig: see → saw. 'I saw a film' = jeg så en film."},
{"g":4,"b":3,"k":"g","q":"Hvad er datid af 'have'?","o":["haved","has","had","haded"],"a":"had","r":"'Have' → 'had' i datid: I had a cold = jeg var forkølet."},
{"g":4,"b":3,"k":"g","q":"Hvad er datid af 'come'?","o":["comed","came","come","comes"],"a":"came","r":"'Come' er uregelmæssig: come → came."},
{"g":4,"b":3,"k":"g","q":"Hvad er datid af 'drink'?","o":["drank","drinked","drunk","drinks"],"a":"drank","r":"'Drink' er uregelmæssig: drink → drank."},
{"g":4,"b":3,"k":"g","q":"Hvad er datid af 'make'?","o":["maked","maden","makes","made"],"a":"made","r":"'Make' er uregelmæssig: make → made. 'We made a cake' = vi lavede en kage."},
{"g":4,"b":3,"k":"g","q":"Hvad er datid af 'visit'?","o":["visitted","visit","visited","visitd"],"a":"visited","r":"'Visit' er regelmæssig og får bare -ed: visited."},
{"g":4,"b":3,"k":"g","q":"Hvad er datid af 'stop'?","o":["stoped","stopped","stopt","stops"],"a":"stopped","r":"Korte ord med kort vokal fordobler sidste konsonant: stop → stopped."},
{"g":4,"b":3,"k":"g","q":"Hvilket ord mangler? 'Did you ___ your homework?'","o":["do","did","done","does"],"a":"do","r":"Efter 'did' står verbet i grundform: Did you do …?"},
{"g":4,"b":3,"k":"g","q":"Hvilket ord mangler? 'I didn't ___ the bus.' (nåede ikke bussen)","o":["caught","catches","catching","catch"],"a":"catch","r":"Efter 'didn't' står verbet i grundform: I didn't catch the bus."},
{"g":4,"b":3,"k":"g","q":"Hvilket ord mangler? 'There ___ a lot of people at the party yesterday.'","o":["was","are","were","is"],"a":"were","r":"'People' er flertal, og 'yesterday' viser datid: there were."},
{"g":4,"b":3,"k":"g","q":"Hvilket ord mangler? 'An elephant is ___ than a mouse.'","o":["biger","bigger","more big","biggest"],"a":"bigger","r":"Korte ord med kort vokal fordobler konsonanten: big → bigger."},
{"g":4,"b":3,"k":"g","q":"Hvilket ord mangler? 'Summer is ___ than winter.'","o":["warmer","warm","warmest","more warm"],"a":"warmer","r":"Når man sammenligner to ting: warm → warmer."},
{"g":4,"b":3,"k":"g","q":"Hvilket ord mangler? 'This is the ___ dog in the world!'","o":["smaller","small","most small","smallest"],"a":"smallest","r":"'The …-est' bruges om den mest af alle: smallest = mindst."},
{"g":4,"b":3,"k":"g","q":"Hvad er 'happier' et eksempel på?","o":["datid","flertal","komparativ (højere grad)","superlativ (højeste grad)"],"a":"komparativ (højere grad)","r":"'Happier' betyder gladere. Ord på -y skifter til -ier."},
{"g":4,"b":3,"k":"g","q":"Hvilket ord mangler? 'I ___ eat breakfast. I'm never hungry in the morning.'","o":["always","never","usually","often"],"a":"never","r":"'Never' betyder aldrig — det passer med 'I'm never hungry'."},
{"g":4,"b":3,"k":"g","q":"Hvor står 'always' i sætningen?","o":["She always walks to school.","She walks always to school.","Always she walk to school.","She walks to always school."],"a":"She always walks to school.","r":"Ord som always, often og never står normalt foran verbet: She always walks."},
{"g":4,"b":3,"k":"g","q":"Hvilket ord mangler? 'This is my sister___ room.' (min søsters værelse)","o":["s'","s","es","'s"],"a":"'s","r":"Ejefald får apostrof + s: my sister's room."},
{"g":4,"b":3,"k":"g","q":"Hvilket ord mangler? 'Have you got ___ milk?'","o":["a","an","any","many"],"a":"any","r":"I spørgsmål bruger man ofte 'any': Have you got any milk?"},
{"g":4,"b":3,"k":"g","q":"Hvilket ord mangler? 'I'd like ___ water, please.'","o":["any","some","a","many"],"a":"some","r":"I sætninger, hvor man beder om noget, bruger man 'some': some water."},
{"g":4,"b":3,"k":"g","q":"Hvilket spørgsmålsord passer? '___ do you live?' – 'In Odense.'","o":["Where","When","What","Who"],"a":"Where","r":"Svaret er et sted (Odense), så spørgsmålet er 'Where' = hvor."},
{"g":4,"b":3,"k":"g","q":"Hvilket spørgsmålsord passer? '___ is your birthday?' – 'In July.'","o":["Where","Who","How","When"],"a":"When","r":"Svaret er et tidspunkt (in July), så man spørger 'When' = hvornår."},
{"g":4,"b":3,"k":"g","q":"Hvilket spørgsmålsord passer? '___ is your teacher?' – 'Mrs Brown.'","o":["What","Where","Who","Which"],"a":"Who","r":"Svaret er en person, så man spørger 'Who' = hvem."},
{"g":4,"b":3,"k":"g","q":"Hvilket spørgsmålsord passer? '___ are you crying?' – 'Because I fell.'","o":["How","Why","What","Who"],"a":"Why","r":"Svaret starter med 'because' (fordi), så spørgsmålet er 'Why' = hvorfor."},
{"g":4,"b":3,"k":"o","q":"Hvilket ord passer IKKE ind? doctor – nurse – dentist – hospital","o":["hospital","doctor","nurse","dentist"],"a":"hospital","r":"Doctor, nurse og dentist er personer/jobs. 'Hospital' er et sted."},
{"g":4,"b":3,"k":"o","q":"Hvilket ord passer IKKE ind? jumper – skirt – jeans – kitchen","o":["jumper","skirt","jeans","kitchen"],"a":"kitchen","r":"Jumper, skirt og jeans er tøj. 'Kitchen' er et køkken."},
{"g":4,"b":3,"k":"o","q":"Hvilket ord passer IKKE ind? happy – sad – angry – quickly","o":["happy","sad","quickly","angry"],"a":"quickly","r":"Happy, sad og angry er følelser. 'Quickly' betyder hurtigt."},
{"g":4,"b":3,"k":"o","q":"Hvilket ord passer IKKE ind? guitar – piano – drum – football","o":["guitar","football","piano","drum"],"a":"football","r":"Guitar, piano og drum er instrumenter. 'Football' er en sport."},
{"g":4,"b":3,"k":"o","q":"Hvilket ord passer IKKE ind? lion – tiger – shark – cheetah","o":["shark","lion","tiger","cheetah"],"a":"shark","r":"Løve, tiger og gepard er kattedyr på land. Hajen (shark) lever i havet."},
{"g":4,"b":3,"k":"o","q":"Hvad er det modsatte af 'expensive'?","o":["rich","poor","nice","cheap"],"a":"cheap","r":"'Expensive' betyder dyr, og 'cheap' betyder billig."},
{"g":4,"b":3,"k":"o","q":"Hvad er det modsatte af 'difficult'?","o":["hard","heavy","easy","dirty"],"a":"easy","r":"'Difficult' betyder svær, og 'easy' betyder nem. 'Hard' betyder også svær."},
{"g":4,"b":3,"k":"o","q":"Hvad er det modsatte af 'remember'?","o":["forgive","forget","remind","repeat"],"a":"forget","r":"'Remember' betyder huske, og 'forget' betyder glemme."},
{"g":4,"b":3,"k":"o","q":"Hvad er det modsatte af 'arrive'?","o":["leave","stay","wait","come"],"a":"leave","r":"'Arrive' betyder ankomme, og 'leave' betyder tage af sted."},
{"g":4,"b":3,"k":"o","q":"Hvad er det modsatte af 'buy'?","o":["pay","spend","bring","sell"],"a":"sell","r":"'Buy' betyder købe, og 'sell' betyder sælge."},
{"g":4,"b":3,"k":"o","q":"Hvad er det modsatte af 'always'?","o":["often","sometimes","never","usually"],"a":"never","r":"'Always' betyder altid, og 'never' betyder aldrig."},
{"g":4,"b":3,"k":"o","q":"Hvilket ord betyder næsten det samme som 'big'?","o":["little","large","tiny","long"],"a":"large","r":"'Large' betyder også stor. 'Tiny' betyder bitte lille."},
{"g":4,"b":3,"k":"o","q":"Hvilket ord betyder næsten det samme som 'happy'?","o":["glad","sad","bad","mad"],"a":"glad","r":"'Glad' på engelsk betyder glad eller fornøjet — ligesom på dansk!"},
{"g":4,"b":3,"k":"o","q":"Hvilket ord betyder næsten det samme som 'start'?","o":["end","finish","stop","begin"],"a":"begin","r":"'Begin' betyder begynde — det samme som 'start'."},
{"g":4,"b":3,"k":"o","q":"Hvad betyder 'often'?","o":["åben","aldrig","ofte","efter"],"a":"ofte","r":"'Often' betyder ofte. 'I often read' = jeg læser ofte."},
{"g":4,"b":3,"k":"o","q":"Hvad betyder 'sometimes'?","o":["altid","nogle gange","aldrig","samme tid"],"a":"nogle gange","r":"'Sometimes' betyder nogle gange eller af og til."},
{"g":4,"b":3,"k":"o","q":"Hvad betyder 'already'?","o":["allerede","alle klar","altid","alene"],"a":"allerede","r":"'Already' betyder allerede: 'I have already eaten' = jeg har allerede spist."},
{"g":4,"b":3,"k":"o","q":"Hvad betyder 'together'?","o":["til dag","alene","i morgen","sammen"],"a":"sammen","r":"'Together' betyder sammen. 'Let's do it together' = lad os gøre det sammen."},
{"g":4,"b":3,"k":"o","q":"Hvad betyder 'country'?","o":["landsby","grevskab","land","by"],"a":"land","r":"'Country' betyder land, f.eks. Danmark. 'Countryside' betyder landet (modsat byen)."},
{"g":4,"b":3,"k":"o","q":"Hvad betyder 'world'?","o":["ord","verden","værelse","vold"],"a":"verden","r":"'World' betyder verden. 'Word' (uden l) betyder ord."},
{"g":4,"b":3,"k":"o","q":"Hvad betyder 'mountain'?","o":["bjerg","mønt","mund","monster"],"a":"bjerg","r":"'Mountain' betyder bjerg."},
{"g":4,"b":3,"k":"o","q":"Hvad betyder 'river'?","o":["rive","regnbue","rytter","flod"],"a":"flod","r":"'River' betyder flod eller å."},
{"g":4,"b":3,"k":"o","q":"Hvad betyder 'lake'?","o":["lak","lagen","sø","leg"],"a":"sø","r":"'Lake' betyder sø. Hav hedder 'sea'."},
{"g":4,"b":3,"k":"o","q":"Hvad betyder 'field'?","o":["fjeld","mark","fil","fjer"],"a":"mark","r":"'Field' betyder mark — f.eks. 'football field' = fodboldbane."},
{"g":4,"b":3,"k":"o","q":"Hvad betyder 'map'?","o":["kort (landkort)","mappe","mad","maske"],"a":"kort (landkort)","r":"'Map' betyder landkort. Mappe hedder 'folder'."},
{"g":4,"b":3,"k":"o","q":"Hvad betyder 'ticket'?","o":["tiger","tæppe","tegning","billet"],"a":"billet","r":"'Ticket' betyder billet — f.eks. til bussen eller biografen."},
{"g":4,"b":3,"k":"o","q":"Hvad betyder 'journey'?","o":["dagbog","journal","rejse","jagt"],"a":"rejse","r":"'Journey' betyder rejse eller tur."},
{"g":4,"b":3,"k":"h","q":"Hvad betyder 'I'm looking for my keys'?","o":["Jeg kigger på mine nøgler","Jeg leder efter mine nøgler","Jeg har fundet mine nøgler","Jeg har mistet mine nøgler i går"],"a":"Jeg leder efter mine nøgler","r":"'Look for' betyder lede efter."},
{"g":4,"b":3,"k":"h","q":"Hvad betyder 'What does it mean?'","o":["Hvad betyder det?","Hvad mener du?","Hvad hedder det?","Hvad koster det?"],"a":"Hvad betyder det?","r":"'Mean' betyder betyde. Brug det, når du ikke forstår et ord."},
{"g":4,"b":3,"k":"h","q":"Hvad betyder 'How do you spell it?'","o":["Hvordan siger man det?","Hvordan laver man det?","Hvordan har du det?","Hvordan staver man det?"],"a":"Hvordan staver man det?","r":"'Spell' betyder stave."},
{"g":4,"b":3,"k":"h","q":"Hvad betyder 'It doesn't matter'?","o":["Det passer ikke","Det virker ikke","Det gør ikke noget","Det er ikke mit"],"a":"Det gør ikke noget","r":"'It doesn't matter' = det er ligegyldigt/det gør ikke noget."},
{"g":4,"b":3,"k":"h","q":"Hvad betyder 'I'm not sure'?","o":["Jeg er ikke klar","Jeg er ikke sikker","Jeg er ikke sur","Jeg er ikke syg"],"a":"Jeg er ikke sikker","r":"'Sure' betyder sikker. 'I'm not sure' = jeg er ikke sikker."},
{"g":4,"b":3,"k":"h","q":"Hvad betyder 'Could you open the window, please?'","o":["Vil du åbne vinduet?","Kan du lukke vinduet?","Må jeg åbne vinduet?","Er vinduet åbent?"],"a":"Vil du åbne vinduet?","r":"'Could you …, please?' er en høflig måde at bede nogen om noget på."},
{"g":4,"b":3,"k":"h","q":"Hvad betyder 'What a pity!'?","o":["Hvor sjovt!","Hvor flot!","Hvor heldigt!","Hvor ærgerligt!"],"a":"Hvor ærgerligt!","r":"'What a pity' siger man, når noget er ærgerligt."},
{"g":4,"b":3,"k":"h","q":"Hvad betyder 'I'm afraid of the dark'?","o":["Jeg kan lide mørke","Jeg er træt om aftenen","Jeg er bange for mørke","Jeg kan ikke se noget"],"a":"Jeg er bange for mørke","r":"'Afraid of' betyder bange for, og 'the dark' er mørket."},
{"g":4,"b":3,"k":"h","q":"Hvad betyder 'Hold on!'?","o":["Hold fast og løb!","Vent lidt!","Hold op!","Kom med!"],"a":"Vent lidt!","r":"'Hold on' betyder vent lidt — f.eks. i telefonen."},
{"g":4,"b":3,"k":"l","q":"Læs: 'Last summer we went to Spain. It was very hot, and we swam every day.' Hvornår var de i Spanien?","o":["sidste sommer","næste sommer","i vinter","sidste weekend"],"a":"sidste sommer","r":"'Last summer' betyder sidste sommer. 'Went' er datid af 'go'."},
{"g":4,"b":3,"k":"l","q":"Læs: 'Ali was ill on Monday, so he didn't go to school.' Hvorfor var Ali ikke i skole?","o":["Det var weekend","Han kom for sent","Skolen var lukket","Han var syg"],"a":"Han var syg","r":"'Ill' betyder syg, og 'so' betyder derfor."},
{"g":4,"b":3,"k":"l","q":"Læs: 'Anna is older than Ben. Ben is older than Carl.' Hvem er yngst?","o":["Anna","Ben","Carl","De er lige gamle"],"a":"Carl","r":"Anna er ældst, så Ben, og Carl er yngst."},
{"g":4,"b":3,"k":"l","q":"Læs: 'The cake was in the oven for too long.' Hvad skete der sikkert med kagen?","o":["Den blev kold","Den blev brændt","Den blev for lille","Den blev rå"],"a":"Den blev brændt","r":"'Too long' betyder for længe. Så brænder kagen tit på."},
{"g":4,"b":3,"k":"l","q":"Læs: 'Kate never eats meat. She loves vegetables.' Hvad spiser Kate IKKE?","o":["kød","grøntsager","frugt","brød"],"a":"kød","r":"'Never eats meat' betyder spiser aldrig kød."},
{"g":4,"b":3,"k":"l","q":"Læs: 'We didn't play outside because it was snowing.' Hvorfor legede de ikke udenfor?","o":["Det var mørkt","De var syge","De havde lektier","Det sneede"],"a":"Det sneede","r":"'Because it was snowing' = fordi det sneede."},
{"g":4,"b":3,"k":"l","q":"Læs: 'Max has three pets: a dog, a hamster and a parrot. The parrot can talk.' Hvilket dyr kan tale?","o":["hunden","hamsteren","papegøjen","ingen af dem"],"a":"papegøjen","r":"'Parrot' betyder papegøje."},
{"g":4,"b":3,"k":"l","q":"Læs: 'The train leaves at 10:15. It is 10:20 now.' Hvad er der sket?","o":["Toget kommer om fem minutter","Toget er kørt","Toget holder stadig","Toget er aflyst"],"a":"Toget er kørt","r":"Toget kørte (leaves) 10:15, og klokken er nu 10:20."},
{"g":4,"b":3,"k":"l","q":"Læs: 'My sister plays the violin. She practises every day after school.' Hvornår øver søsteren?","o":["hver dag efter skole","kun i weekenden","om morgenen","før skole"],"a":"hver dag efter skole","r":"'Every day after school' = hver dag efter skole."},
{"g":4,"b":3,"k":"l","q":"Læs: 'Tom forgot his lunch box, so his friend shared her sandwich with him.' Hvad gjorde vennen?","o":["Hun gav ham penge","Hun hentede hans madpakke","Hun spiste hans madpakke","Hun delte sin sandwich"],"a":"Hun delte sin sandwich","r":"'Shared' betyder delte. 'Forgot' betyder glemte."},
{"g":4,"b":3,"k":"l","q":"Læs: 'Ella's shoes are too small. She needs new ones.' Hvad har Ella brug for?","o":["mindre sko","nye strømper","nye sko","en ny kjole"],"a":"nye sko","r":"'Too small' = for små, og 'new ones' = nye (sko)."},
{"g":4,"b":3,"k":"l","q":"Læs: 'It was dark, but Leo wasn't scared because he had a torch.' Hvorfor var Leo ikke bange?","o":["Han var sammen med sin far","Han havde en lommelygte","Det var lyst","Han sov"],"a":"Han havde en lommelygte","r":"'Torch' betyder lommelygte (britisk)."},
{"g":4,"b":3,"k":"l","q":"Læs: 'Mia wants to buy a book. It costs 8 pounds. She has 10 pounds.' Hvor mange penge får hun tilbage?","o":["2 pund","8 pund","10 pund","18 pund"],"a":"2 pund","r":"10 pund minus 8 pund = 2 pund tilbage."},
{"g":4,"b":3,"k":"l","q":"Læs: 'The museum is closed on Mondays. Today is Monday.' Kan man besøge museet i dag?","o":["Ja","Ja, men kun om eftermiddagen","Det står der ikke","Nej"],"a":"Nej","r":"Museet er lukket om mandagen (closed on Mondays), og i dag er mandag."},
{"g":4,"b":3,"k":"l","q":"Læs: 'Sam got a new puppy. He named it Bobby.' Hvad er Bobby?","o":["en kat","en ven","en hvalp","en bamse"],"a":"en hvalp","r":"'Puppy' er en hvalp. 'Named it' = gav den navnet."},
{"g":4,"b":3,"k":"l","q":"Læs: 'Our teacher was ill, so we had a different teacher today.' Hvad skete der?","o":["Læreren kom for sent","De havde en anden lærer","Skolen var lukket","De havde fri"],"a":"De havde en anden lærer","r":"'A different teacher' = en anden lærer. Den normale lærer var syg (ill)."},
{"g":4,"b":3,"k":"l","q":"Læs: 'Before lunch we had maths. After lunch we had music.' Hvad havde de efter frokost?","o":["musik","matematik","idræt","engelsk"],"a":"musik","r":"'After lunch' = efter frokost. Der havde de musik."},
{"g":4,"b":3,"k":"g","q":"Hvad er datid af 'write'?","o":["writed","written","writes","wrote"],"a":"wrote","r":"'Write' er uregelmæssig: write → wrote. 'I wrote a letter' = jeg skrev et brev."},
{"g":4,"b":3,"k":"o","q":"Hvad betyder 'neighbourhood'?","o":["nabo","naboland","nabolag","nærhed"],"a":"nabolag","r":"'Neighbourhood' betyder nabolag — området, hvor man bor."},
{"g":4,"b":3,"k":"l","q":"Læs: 'Oscar's room is very messy. There are clothes and toys everywhere.' Hvordan er Oscars værelse?","o":["pænt","rodet","tomt","stort"],"a":"rodet","r":"'Messy' betyder rodet. Der er tøj og legetøj overalt (everywhere)."},
{"g":4,"b":4,"k":"g","q":"Hvilket ord mangler? 'My drawing is good, but yours is ___.'","o":["better","gooder","best","more good"],"a":"better","r":"'Good' er uregelmæssig: good → better → best."},
{"g":4,"b":4,"k":"g","q":"Hvilket ord mangler? 'This is the ___ film I have ever seen!' (dårligste)","o":["baddest","worse","most bad","worst"],"a":"worst","r":"'Bad' er uregelmæssig: bad → worse → worst."},
{"g":4,"b":4,"k":"g","q":"Hvilket ord mangler? 'A cheetah is the ___ animal on land.'","o":["faster","most fast","fastest","fast"],"a":"fastest","r":"Geparden er den hurtigste af alle, så man bruger 'the fastest'."},
{"g":4,"b":4,"k":"g","q":"Hvilket ord mangler? 'Maths is ___ than music for me.' (sværere)","o":["difficulter","more difficult","most difficult","difficultest"],"a":"more difficult","r":"Lange ord får 'more' foran i stedet for -er: more difficult."},
{"g":4,"b":4,"k":"g","q":"Hvilket ord mangler? 'This is the ___ book in the library.' (mest interessante)","o":["most interesting","interestingest","more interesting","interestinger"],"a":"most interesting","r":"Lange ord får 'the most' foran: the most interesting."},
{"g":4,"b":4,"k":"g","q":"Hvilket ord mangler? 'Look at those clouds! It's ___ to rain.'","o":["go","goes","went","going"],"a":"going","r":"'Be going to' bruges, når man kan se, at noget vil ske: It's going to rain."},
{"g":4,"b":4,"k":"g","q":"Hvilket ord mangler? 'I think it ___ be sunny tomorrow.'","o":["is","did","will","was"],"a":"will","r":"'Will' bruges om fremtiden, især om gæt: I think it will be sunny."},
{"g":4,"b":4,"k":"g","q":"Hvilket ord mangler? 'You ___ wear a helmet when you ride a bike.' (skal)","o":["can","must","may","would"],"a":"must","r":"'Must' betyder skal (det er vigtigt). Man skal bære cykelhjelm."},
{"g":4,"b":4,"k":"g","q":"Hvilket ord mangler? 'You ___ eat so many sweets. It's bad for your teeth.'","o":["shouldn't","should","must","can"],"a":"shouldn't","r":"'Shouldn't' betyder bør ikke. Det giver et godt råd."},
{"g":4,"b":4,"k":"g","q":"Hvilket ord mangler? 'How ___ apples do you want?'","o":["much","lot","more of","many"],"a":"many","r":"'Many' bruges om ting, man kan tælle: how many apples?"},
{"g":4,"b":4,"k":"g","q":"Hvilket ord mangler? 'How ___ milk is in the fridge?'","o":["many","lot","much","few"],"a":"much","r":"'Much' bruges om ting, man ikke kan tælle, som mælk: how much milk?"},
{"g":4,"b":4,"k":"g","q":"Hvilket ord mangler? 'There isn't ___ bread left.'","o":["some","any","a","many"],"a":"any","r":"I nægtende sætninger bruger man 'any': There isn't any bread."},
{"g":4,"b":4,"k":"g","q":"Hvad er datid af 'buy'?","o":["bought","buyed","brought","buys"],"a":"bought","r":"'Buy' er uregelmæssig: buy → bought. Pas på: 'brought' er datid af 'bring'."},
{"g":4,"b":4,"k":"g","q":"Hvad er datid af 'take'?","o":["taked","taken","tooked","took"],"a":"took","r":"'Take' er uregelmæssig: take → took."},
{"g":4,"b":4,"k":"g","q":"Hvad er datid af 'swim'?","o":["swimmed","swum","swam","swims"],"a":"swam","r":"'Swim' er uregelmæssig: swim → swam."},
{"g":4,"b":4,"k":"g","q":"Hvad er datid af 'find'?","o":["finded","found","fand","founded"],"a":"found","r":"'Find' er uregelmæssig: find → found = fandt."},
{"g":4,"b":4,"k":"g","q":"Hvad er datid af 'tell'?","o":["told","telled","tolled","tells"],"a":"told","r":"'Tell' er uregelmæssig: tell → told = fortalte."},
{"g":4,"b":4,"k":"g","q":"Hvad er datid af 'fly'?","o":["flied","flown","flyed","flew"],"a":"flew","r":"'Fly' er uregelmæssig: fly → flew = fløj."},
{"g":4,"b":4,"k":"g","q":"Hvilket ord mangler? 'I was watching TV when the phone ___.'","o":["ring","rings","rang","ringing"],"a":"rang","r":"Noget kort afbryder noget, der var i gang: datid af 'ring' er 'rang'."},
{"g":4,"b":4,"k":"g","q":"Hvilket ord mangler? 'The children ___ playing when it started to rain.'","o":["was","were","are","is"],"a":"were","r":"'The children' er flertal: they were playing = de var i gang med at lege."},
{"g":4,"b":4,"k":"g","q":"Hvilken sætning med ejefald er rigtig?","o":["My father's car is red.","My fathers car is red.","My father car's is red.","My fathers' car are red."],"a":"My father's car is red.","r":"Ejefald: my father's car = min fars bil."},
{"g":4,"b":4,"k":"g","q":"Hvilket ord mangler? 'She is good ___ drawing.'","o":["in","on","for","at"],"a":"at","r":"Man siger 'good at' = god til: She is good at drawing."},
{"g":4,"b":4,"k":"g","q":"Hvilket ord mangler? 'I'm interested ___ animals.'","o":["on","at","in","of"],"a":"in","r":"Man siger 'interested in' = interesseret i."},
{"g":4,"b":4,"k":"g","q":"Hvilket ord mangler? 'We waited ___ the bus for 20 minutes.'","o":["on","for","at","to"],"a":"for","r":"'Wait for' betyder vente på: wait for the bus."},
{"g":4,"b":4,"k":"o","q":"Hvad betyder det engelske ord 'gift'?","o":["gave","gift (giftig)","gift (ægtegift)","gyse"],"a":"gave","r":"Falsk ven! 'Gift' betyder gave på engelsk. Gift (giftigt) hedder 'poison'."},
{"g":4,"b":4,"k":"o","q":"Hvad betyder det engelske ord 'fabric'?","o":["fabrik","fabel","figur","stof (til tøj)"],"a":"stof (til tøj)","r":"Falsk ven! 'Fabric' er stof. En fabrik hedder 'factory'."},
{"g":4,"b":4,"k":"o","q":"Hvad betyder det engelske ord 'eventually'?","o":["eventuelt","aldrig","til sidst","med det samme"],"a":"til sidst","r":"Falsk ven! 'Eventually' betyder til sidst. 'Eventuelt' hedder 'possibly'."},
{"g":4,"b":4,"k":"o","q":"Hvad betyder 'brave'?","o":["brav","modig","bred","bange"],"a":"modig","r":"'Brave' betyder modig. Det modsatte er 'scared' eller 'cowardly'."},
{"g":4,"b":4,"k":"o","q":"Hvad betyder 'proud'?","o":["stolt","prut","pæn","privat"],"a":"stolt","r":"'Proud' betyder stolt: 'I'm proud of you' = jeg er stolt af dig."},
{"g":4,"b":4,"k":"o","q":"Hvad betyder 'surprised'?","o":["overgivet","sur","sikker","overrasket"],"a":"overrasket","r":"'Surprised' betyder overrasket. 'Surprise!' = overraskelse!"},
{"g":4,"b":4,"k":"o","q":"Hvad betyder 'excited'?","o":["eksotisk","udmattet","spændt eller begejstret","ekstra"],"a":"spændt eller begejstret","r":"'Excited' betyder spændt eller begejstret: 'I'm excited about the trip.'"},
{"g":4,"b":4,"k":"o","q":"Hvad betyder 'lonely'?","o":["lumsk","ensom","lang","lyst"],"a":"ensom","r":"'Lonely' betyder ensom."},
{"g":4,"b":4,"k":"o","q":"Hvad betyder 'worried'?","o":["bekymret","vred","varm","vågen"],"a":"bekymret","r":"'Worried' betyder bekymret. 'Don't worry' = bare rolig."},
{"g":4,"b":4,"k":"o","q":"Hvad betyder 'safe'?","o":["saft","sej","syg","sikker"],"a":"sikker","r":"'Safe' betyder sikker eller i sikkerhed. Det modsatte er 'dangerous' — farlig."},
{"g":4,"b":4,"k":"o","q":"Hvad betyder 'enough'?","o":["ingen","endnu","nok","ensom"],"a":"nok","r":"'Enough' betyder nok: 'I have enough money' = jeg har penge nok."},
{"g":4,"b":4,"k":"o","q":"Hvad betyder 'almost'?","o":["altid","næsten","mest","alle"],"a":"næsten","r":"'Almost' betyder næsten: 'It's almost ten' = klokken er næsten ti."},
{"g":4,"b":4,"k":"o","q":"Hvad betyder 'suddenly'?","o":["pludselig","sjældent","langsomt","søndag"],"a":"pludselig","r":"'Suddenly' betyder pludselig."},
{"g":4,"b":4,"k":"o","q":"Hvad betyder 'carefully'?","o":["bekymret","hurtigt","kærligt","forsigtigt"],"a":"forsigtigt","r":"'Carefully' betyder forsigtigt. 'Careful' betyder forsigtig."},
{"g":4,"b":4,"k":"o","q":"Hvilket sammensat ord betyder 'fodboldbane'?","o":["foot ballfield","ball foot pitch","football pitch","pitch football"],"a":"football pitch","r":"Fodboldbane hedder 'football pitch' (eller 'football field')."},
{"g":4,"b":4,"k":"o","q":"Hvad betyder 'birthday cake'?","o":["fødselsdagsgave","fødselsdagskage","fødselsdagsfest","fødselsdagssang"],"a":"fødselsdagskage","r":"'Birthday' + 'cake' = fødselsdagskage."},
{"g":4,"b":4,"k":"o","q":"Hvad betyder 'toothbrush'?","o":["tandbørste","tandpasta","tandlæge","hårbørste"],"a":"tandbørste","r":"'Tooth' (tand) + 'brush' (børste) = tandbørste."},
{"g":4,"b":4,"k":"o","q":"Hvad betyder 'bedtime'?","o":["sengetøj","godnathistorie","morgentid","sengetid"],"a":"sengetid","r":"'Bed' (seng) + 'time' (tid) = sengetid."},
{"g":4,"b":4,"k":"o","q":"Hvad betyder 'homework'?","o":["husarbejde","hjemmeside","lektier","hjemrejse"],"a":"lektier","r":"'Homework' betyder lektier (arbejde, man laver derhjemme)."},
{"g":4,"b":4,"k":"o","q":"Hvad betyder 'sunglasses'?","o":["solcreme","solbriller","solskin","solsikke"],"a":"solbriller","r":"'Sun' (sol) + 'glasses' (briller) = solbriller."},
{"g":4,"b":4,"k":"o","q":"Hvad betyder 'raincoat'?","o":["regnfrakke","regnbue","regnvejr","regnorm"],"a":"regnfrakke","r":"'Rain' (regn) + 'coat' (frakke) = regnfrakke."},
{"g":4,"b":4,"k":"h","q":"Hvad betyder 'It's up to you'?","o":["Det er oppe hos dig","Det er din tur","Det er dit problem","Det er op til dig"],"a":"Det er op til dig","r":"'It's up to you' = du bestemmer."},
{"g":4,"b":4,"k":"h","q":"Hvad betyder 'Never mind'?","o":["Glem aldrig","Pas på","Det gør ikke noget","Tænk dig om"],"a":"Det gør ikke noget","r":"'Never mind' bruges, når noget ikke er vigtigt: glem det, det gør ikke noget."},
{"g":4,"b":4,"k":"h","q":"Hvad betyder 'I can't wait!'?","o":["Jeg kan ikke vente her","Jeg glæder mig vildt!","Jeg har ikke tid","Jeg venter gerne"],"a":"Jeg glæder mig vildt!","r":"'I can't wait' siger man, når man glæder sig meget til noget."},
{"g":4,"b":4,"k":"h","q":"Hvad betyder 'Take care!'?","o":["Pas godt på dig selv!","Tag den!","Tag det roligt!","Tag med!"],"a":"Pas godt på dig selv!","r":"'Take care' siger man ofte, når man siger farvel."},
{"g":4,"b":4,"k":"h","q":"Hvad betyder 'What's the matter?'","o":["Hvad betyder det?","Hvad er klokken?","Hvad laver du?","Hvad er der i vejen?"],"a":"Hvad er der i vejen?","r":"'What's the matter?' spørger, om der er noget galt."},
{"g":4,"b":4,"k":"h","q":"Hvad betyder 'Make yourself at home'?","o":["Gå hjem nu","Lav dit eget hjem","Føl dig som hjemme","Ryd op derhjemme"],"a":"Føl dig som hjemme","r":"Værten siger 'Make yourself at home' til gæster."},
{"g":4,"b":4,"k":"h","q":"Hvad betyder 'I'm on my way'?","o":["Jeg står i vejen","Jeg er på vej","Jeg går min egen vej","Jeg er faret vild"],"a":"Jeg er på vej","r":"'On my way' betyder på vej."},
{"g":4,"b":4,"k":"h","q":"Hvad betyder 'Could you speak more slowly, please?'","o":["Kan du tale langsommere?","Kan du tale højere?","Kan du sige det igen?","Kan du tale engelsk?"],"a":"Kan du tale langsommere?","r":"'Slowly' betyder langsomt, og 'more slowly' betyder langsommere."},
{"g":4,"b":4,"k":"h","q":"Hvordan siger man høfligt, at man gerne vil have noget at drikke?","o":["Give me drink.","I want drink now.","Drink, you give me.","I'd like something to drink, please."],"a":"I'd like something to drink, please.","r":"'I'd like' (= I would like) er en høflig måde at sige 'jeg vil gerne have'."},
{"g":4,"b":4,"k":"h","q":"Hvad betyder 'You're joking!'?","o":["Du er sjov at se på","Du er en joker","Det er løgn!/Du laver sjov!","Du er sur"],"a":"Det er løgn!/Du laver sjov!","r":"'You're joking!' siger man, når man er overrasket: det mener du ikke!"},
{"g":4,"b":4,"k":"l","q":"Læs: 'Emma was walking home when it started to rain. She didn't have an umbrella, so she ran.' Hvorfor løb Emma?","o":["Hun kom for sent","Hun havde ingen paraply","Hun var bange","Hun skulle nå bussen"],"a":"Hun havde ingen paraply","r":"'She didn't have an umbrella' = hun havde ingen paraply. 'So' = derfor."},
{"g":4,"b":4,"k":"l","q":"Læs: 'The red team scored 3 goals. The blue team scored 5.' Hvem vandt?","o":["det blå hold","det røde hold","uafgjort","det står der ikke"],"a":"det blå hold","r":"Det blå hold scorede flest mål (5 mod 3)."},
{"g":4,"b":4,"k":"l","q":"Læs: 'Jake is saving his pocket money because he wants to buy a new game.' Hvorfor sparer Jake op?","o":["Han vil give en gave","Han skal på ferie","Han har mistet sine penge","Han vil købe et nyt spil"],"a":"Han vil købe et nyt spil","r":"'Saving' betyder sparer op, og 'because' betyder fordi."},
{"g":4,"b":4,"k":"l","q":"Læs: 'Sophie had a bad dream and woke up in the middle of the night.' Hvornår vågnede Sophie?","o":["tidligt om morgenen","om eftermiddagen","midt om natten","om aftenen"],"a":"midt om natten","r":"'In the middle of the night' = midt om natten."},
{"g":4,"b":4,"k":"l","q":"Læs: 'Grandpa can't read the small letters without his glasses.' Hvad har bedstefar brug for?","o":["en lup","sine briller","en lampe","en ny bog"],"a":"sine briller","r":"'Glasses' betyder briller. Uden dem kan han ikke læse de små bogstaver."},
{"g":4,"b":4,"k":"l","q":"Læs: 'The library was so quiet that you could hear a pin drop.' Hvordan var der på biblioteket?","o":["helt stille","meget larmende","mørkt","fyldt med mennesker"],"a":"helt stille","r":"'You could hear a pin drop' = man kunne høre en knappenål falde — der var helt stille."},
{"g":4,"b":4,"k":"l","q":"Læs: 'Lily's mum said: \"You can go out when you have tidied your room.\"' Hvad skal Lily gøre først?","o":["gå ud","lave lektier","spise","rydde sit værelse op"],"a":"rydde sit værelse op","r":"'When you have tidied your room' = når du har ryddet op på dit værelse."},
{"g":4,"b":4,"k":"l","q":"Læs: 'Oliver missed the bus, so he was late for school.' Hvorfor kom Oliver for sent?","o":["Han sov for længe","Bussen var aflyst","Han kom ikke med bussen","Han var syg"],"a":"Han kom ikke med bussen","r":"'Missed the bus' betyder ikke nåede bussen."},
{"g":4,"b":4,"k":"l","q":"Læs: 'Hannah is allergic to cats, so she can't visit her friend who has three cats.' Hvorfor kan Hannah ikke besøge veninden?","o":["Hun er bange for katte","Hun er allergisk over for katte","Veninden bor langt væk","Veninden er syg"],"a":"Hun er allergisk over for katte","r":"'Allergic to cats' betyder allergisk over for katte."},
{"g":4,"b":4,"k":"l","q":"Læs: 'The museum was boring at first, but then we saw the dinosaurs, and it was amazing!' Hvad syntes de om dinosaurerne?","o":["De var fantastiske","De var kedelige","De var uhyggelige","De var for små"],"a":"De var fantastiske","r":"'Amazing' betyder fantastisk. 'At first' betyder først."},
{"g":4,"b":4,"k":"l","q":"Læs: 'Noah studied hard for the test, and he got the best mark in the class.' Hvorfor fik Noah den bedste karakter?","o":["Testen var nem","Han snød","Han var heldig","Han havde læst meget på det"],"a":"Han havde læst meget på det","r":"'Studied hard' betyder læste meget/arbejdede hårdt."},
{"g":4,"b":4,"k":"l","q":"Læs: 'It's Sunday morning, and Dad is still asleep.' Hvad laver far?","o":["Han spiser morgenmad","Han løber en tur","Han sover stadig","Han læser avis"],"a":"Han sover stadig","r":"'Still asleep' betyder sover stadig."},
{"g":4,"b":4,"k":"l","q":"Læs: 'Ava wanted to buy ice cream, but the shop had sold out.' Hvorfor fik Ava ikke is?","o":["Hun havde ingen penge","Butikken havde ikke mere is","Butikken var lukket","Hun kunne ikke lide isen"],"a":"Butikken havde ikke mere is","r":"'Sold out' betyder udsolgt."},
{"g":4,"b":4,"k":"l","q":"Læs: 'Liam and his dad built a birdhouse. Now birds live in it.' Hvad byggede de?","o":["et fuglehus","et legehus","en hundehule","et træhus"],"a":"et fuglehus","r":"'Birdhouse' = fuglehus (bird + house)."},
{"g":4,"b":4,"k":"l","q":"Læs: 'The film was so funny that we laughed all the time.' Hvordan var filmen?","o":["meget trist","meget lang","meget uhyggelig","meget sjov"],"a":"meget sjov","r":"'So funny' = så sjov. 'Laughed' = grinede."},
{"g":4,"b":4,"k":"l","q":"Læs: 'I can't find my phone. I had it when I was in the kitchen.' Hvor er telefonen sikkert?","o":["i haven","i skolen","i køkkenet","i bilen"],"a":"i køkkenet","r":"Personen havde telefonen i køkkenet — det er det bedste sted at lede."},
{"g":4,"b":4,"k":"l","q":"Læs: 'Freya is the youngest of three sisters. Her sisters are 12 and 14.' Hvad ved vi om Freya?","o":["Hun er 14 år","Hun er under 12 år","Hun er ældst","Hun har en bror"],"a":"Hun er under 12 år","r":"Freya er yngst (the youngest), så hun er yngre end 12."},
{"g":4,"b":4,"k":"l","q":"Læs: 'Ben's tooth hurt, so his mum took him to the dentist.' Hvor tog mor Ben hen?","o":["til tandlægen","til lægen","til frisøren","i skole"],"a":"til tandlægen","r":"'Dentist' betyder tandlæge. Hans tand gjorde ondt (hurt)."},
{"g":4,"b":4,"k":"l","q":"Læs: 'We wanted to have a picnic, but it was too windy, so we ate inside.' Hvor spiste de?","o":["i parken","på stranden","i skoven","indenfor"],"a":"indenfor","r":"'Ate inside' = spiste indenfor. Det blæste for meget (too windy)."},
{"g":4,"b":4,"k":"g","q":"Hvad er datid af 'begin'?","o":["beginned","begun","began","begins"],"a":"began","r":"'Begin' er uregelmæssig: begin → began = begyndte."},
{"g":4,"b":4,"k":"g","q":"Hvad er datid af 'think'?","o":["thinked","thought","thank","taught"],"a":"thought","r":"'Think' er uregelmæssig: think → thought. 'Taught' er datid af 'teach'."},
{"g":4,"b":4,"k":"g","q":"Hvilket ord mangler? 'We ___ visit Grandma next weekend. We have already planned it.'","o":["are going to","went to","were","did"],"a":"are going to","r":"Noget, man har planlagt, udtrykkes tit med 'be going to'."},
{"g":4,"b":4,"k":"g","q":"Hvilket ord mangler? 'Neither Tom ___ Sara likes spinach.'","o":["or","and","but","nor"],"a":"nor","r":"'Neither … nor' betyder hverken … eller."},
{"g":4,"b":4,"k":"o","q":"Hvad betyder det engelske ord 'sensible'?","o":["sensibel (følsom)","sanselig","fornuftig","sentimental"],"a":"fornuftig","r":"Falsk ven! 'Sensible' betyder fornuftig. Følsom hedder 'sensitive'."},
{"g":4,"b":4,"k":"o","q":"Hvad betyder 'borrow'?","o":["låne ud","låne (af nogen)","bore","borge"],"a":"låne (af nogen)","r":"'Borrow' er at låne af nogen. At låne noget ud til nogen hedder 'lend'."},
{"g":4,"b":4,"k":"h","q":"Hvad betyder 'Fingers crossed!'?","o":["Jeg krydser fingre!","Du har fået fingrene i klemme!","Hold fingrene væk!","Fingrene er krydset over!"],"a":"Jeg krydser fingre!","r":"'Fingers crossed' betyder 'jeg krydser fingre' — man håber, det går godt."},
{"g":4,"b":4,"k":"l","q":"Læs: 'The bakery smells of fresh bread every morning.' Hvad dufter der af?","o":["kaffe","blomster","kager","frisk brød"],"a":"frisk brød","r":"'Smells of fresh bread' = dufter af frisk brød."},
{"g":4,"b":4,"k":"l","q":"Læs: 'Mila practised the piano for weeks, and at the concert she didn't make a single mistake.' Hvordan gik koncerten?","o":["Hun lavede mange fejl","Hun glemte at komme","Hun lavede ingen fejl","Koncerten blev aflyst"],"a":"Hun lavede ingen fejl","r":"'Didn't make a single mistake' = lavede ikke en eneste fejl."}
]$$::jsonb) AS e
JOIN (VALUES
  ('o', 'ordforråd', 'recall', 'factual', 'surface_association'),
  ('h', 'hverdagsudtryk', 'comprehension', 'conceptual', 'surface_association'),
  ('g', 'grammatik', 'application', 'applied', 'overgeneralization'),
  ('l', 'læseforståelse', 'analysis', 'inferential', 'surface_association')
) AS m(k, concept, skill, dtype, mis) ON m.k = e->>'k';
