-- Section 147B — Cold War Grade 7 Capacity Expansion
-- cold_war, target_grade=7, is_active=true
-- Distribution: B1(2) + B2(4) + B3(6) + B4(5) + B5(3) = 20 questions
-- Topics: Marshall Plan, Korea War, arms race, propaganda, détente, Berlin Blockade,
--         Glasnost/Perestroika, Soviet collapse, MAD doctrine, Vietnam, Afghanistan,
--         Helsinki Accords, nuclear deterrence as stability, Cold War legacy in Russia,
--         Third World proxy wars, technology spin-offs, hotline/crisis comms,
--         inevitability debate, bipolarity theory, USA-China lessons
-- Before: B1=6 B2=7 B3=7 B4=7 B5=0 → 27 active
-- After:  B1=8 B2=11 B3=13 B4=12 B5=3 → 47 active
-- Uses dollar-quoting ($$) throughout.

-- ─── BAND 1 (2 questions) ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad var Marshallplanen og hvem stod bag den?","options":["Et amerikansk hjælpeprogram fra 1948 der gav milliarder til at genopbygge Vesteuropa efter 2. verdenskrig for at forhindre kommunismens udbredelse","En sovjet-plan for at bygge en mur tværs gennem Europa for at adskille øst og vest","En aftale mellem USA og Sovjet om at dele Europa i to militære zoner","Et dansk program for at sende hjælp til lande ødelagt af atomvåben"],"correct":"Et amerikansk hjælpeprogram fra 1948 der gav milliarder til at genopbygge Vesteuropa efter 2. verdenskrig for at forhindre kommunismens udbredelse","accepted_answers":["Et amerikansk hjælpeprogram fra 1948 der gav milliarder til at genopbygge Vesteuropa efter 2. verdenskrig for at forhindre kommunismens udbredelse"],"review_text":"Efter 2. verdenskrig var Europa i ruiner. USA lancerede Marshallplanen i 1948 — opkaldt efter udenrigsminister George Marshall — og sendte milliarder af dollars til at genopbygge Vesteuropa. Formålet var dobbelt: hjælpe Europa og forhindre at fattigdom og kaos ville gøre lande sårbare over for kommunistiske bevægelser. Sovjet afviste planen og forbød sine satellitlande at tage imod hjælpen. Det cementerede opdelingen af Europa i to blokke."}$$::jsonb,
  'mc','short',$${"concepts":["Marshallplanen","genopbygning","kommunismebekæmpelse","USA","Vesteuropa"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"recognition","insight_type":"concept_clarification","challenge_role":"entry_level","domain":"cold_war"}$$::jsonb,
  'mc_single',1,'auto',true,'cold_war',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad var Koreakrigen (1950-1953) og hvad var dens forbindelse til Den Kolde Krig?","options":["En proxy-krig hvor USA støttede Sydkorea og Kina samt Sovjet støttede Nordkorea — et eksempel på at Den Kolde Krig ofte udspillede sig via krige i andre lande","En krig direkte mellem USA og Sovjet om kontrollen over Korea","En intern borgerkrig i Korea der ikke havde noget med Den Kolde Krig at gøre","En krig der endte med at Korea blev forenet under et kommunistisk styre"],"correct":"En proxy-krig hvor USA støttede Sydkorea og Kina samt Sovjet støttede Nordkorea — et eksempel på at Den Kolde Krig ofte udspillede sig via krige i andre lande","accepted_answers":["En proxy-krig hvor USA støttede Sydkorea og Kina samt Sovjet støttede Nordkorea — et eksempel på at Den Kolde Krig ofte udspillede sig via krige i andre lande"],"review_text":"Koreakrigen (1950-53) var det første store militære sammenstød i Den Kolde Krig. Da Nordkorea invaderede Sydkorea, svarede USA og FN-styrker. Over 36.000 amerikanere og millioner af koreanere omkom. Krigen endte uafgjort — Korea er stadig delt ved den 38. breddegrad. Det var et klassisk eksempel på en proxy-krig: USA og Sovjet/Kina kæmpede mod hinanden via andre landes hære for at undgå direkte atomkonfrontation."}$$::jsonb,
  'mc','short',$${"concepts":["Koreakrigen","proxy-krig","USA","Nordkorea","Sydkorea","Den Kolde Krig"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"recognition","insight_type":"concept_clarification","challenge_role":"entry_level","domain":"cold_war"}$$::jsonb,
  'mc_single',1,'auto',true,'cold_war',7,1
);

-- ─── BAND 2 (4 questions) ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad var oprustningskapløbet under Den Kolde Krig?","options":["Den gensidige opbygning af stadig mere avancerede atomvåben og militær kapacitet mellem USA og Sovjet — begge parter frygtede at den anden ville opnå militær overlegenhed","En konkurrence om hvem der hurtigst kunne genopbygge sin økonomi efter 2. verdenskrig","En kapløb om at opruste Europa med konventionelle styrker for at forhindre invasion fra Mellemøsten","En konkurrence om at være den første til at sende et menneske til Månen"],"correct":"Den gensidige opbygning af stadig mere avancerede atomvåben og militær kapacitet mellem USA og Sovjet — begge parter frygtede at den anden ville opnå militær overlegenhed","accepted_answers":["Den gensidige opbygning af stadig mere avancerede atomvåben og militær kapacitet mellem USA og Sovjet — begge parter frygtede at den anden ville opnå militær overlegenhed"],"review_text":"Oprustningskapløbet var en central drivkraft i Den Kolde Krig. Da Sovjet testede sin første atombombe i 1949 var det et chok for USA som troede de havde monopolet. Herefter udviklede begge lande stadig kraftigere våben — brintbomber, interkontinentale missiler, atombærende ubåde. I 1960'erne havde begge sider nok våben til at udslette menneskeheden mange gange. Det skabte en paradoksal situation: jo mere man oprustede, jo mere sikker var man på at begge parter ville blive ødelagt ved krig."}$$::jsonb,
  'mc','short',$${"concepts":["oprustningskapløbet","atomvåben","militær overlegenhed","USA","Sovjet","brintbombe"],"misconception_type":"surface_association","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"concept_clarification","challenge_role":"reinforcement","domain":"cold_war"}$$::jsonb,
  'mc_single',2,'auto',true,'cold_war',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvordan brugte USA og Sovjet propaganda under Den Kolde Krig?","options":["Begge sider brugte systematisk propaganda til at fremstille deres eget system som overlegent og modstanderens som ondskabsfuldt — via film, radio, aviser og kulturelle programmer","Kun Sovjet brugte propaganda — USA havde fri presse og brugte aldrig bevidst propaganda","Propaganda spillede en uvæsentlig rolle fordi borgerne på begge sider gennemskuede det hurtigt","Propaganda var kun rettet mod neutrale lande — borgere i USA og Sovjet fik altid sandfærdig information"],"correct":"Begge sider brugte systematisk propaganda til at fremstille deres eget system som overlegent og modstanderens som ondskabsfuldt — via film, radio, aviser og kulturelle programmer","accepted_answers":["Begge sider brugte systematisk propaganda til at fremstille deres eget system som overlegent og modstanderens som ondskabsfuldt — via film, radio, aviser og kulturelle programmer"],"review_text":"Propaganda var en central del af Den Kolde Krig — en idékrig ligeså meget som en militær konflikt. USA brugte Voice of America, CIA-finansierede kulturprogrammer og Hollywood-film til at fremstille det frie samfund positivt. Sovjet brugte statsmedier og støtte til kommunistiske bevægelser globalt. Begge sider forsøgte at vinde de ikke-allierede nationers sympati. Propaganda var ikke kun løgn — den ramte også reelle svagheder hos modstanderen og bidrog til at forme hele generationers verdensbillede."}$$::jsonb,
  'mc','short',$${"concepts":["propaganda","ideologisk krig","Voice of America","CIA","Hollywood","Sovjet-medier"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"cold_war"}$$::jsonb,
  'mc_single',2,'auto',true,'cold_war',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad var afspænding (détente) og hvad opnåede man i 1970'erne?","options":["En periode med forsigtigt diplomatisk samarbejde og nedrustningsaftaler mellem USA og Sovjet der reducerede den umiddelbare atomrisiko selvom grundlæggende uenigheder forblev","En permanent fred der betød at Den Kolde Krig reelt sluttede i 1970'erne","En aftale om at dele verden i to adskilte sfærer med absolut non-intervention i hinandens zone","Et kulturelt samarbejde der betød at borgere frit kunne rejse mellem øst og vest"],"correct":"En periode med forsigtigt diplomatisk samarbejde og nedrustningsaftaler mellem USA og Sovjet der reducerede den umiddelbare atomrisiko selvom grundlæggende uenigheder forblev","accepted_answers":["En periode med forsigtigt diplomatisk samarbejde og nedrustningsaftaler mellem USA og Sovjet der reducerede den umiddelbare atomrisiko selvom grundlæggende uenigheder forblev"],"review_text":"Afspænding (détente på fransk) var 1970'ernes forsøg på at normalisere forholdet mellem supermagterne. Nixon besøgte Kina i 1972, SALT I-traktaten (1972) begrænsede strategiske atomvåben, og Helsingfors-aftalen (1975) anerkendte Europas grænser. Det reducerede den umiddelbare krigsrisiko — men Den Kolde Krig fortsatte. Afspændingen kollapsede da Sovjet invaderede Afghanistan i 1979 og Reagan genoptog en hård konfrontationslinje i 1980'erne. Afspænding var en pause, ikke en fred."}$$::jsonb,
  'mc','short',$${"concepts":["afspænding","détente","SALT","Nixon","Helsingfors","nedrustning"],"misconception_type":"overgeneralization","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"cold_war"}$$::jsonb,
  'mc_single',2,'auto',true,'cold_war',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad var Berlin-blokaden (1948-49) og hvad viste den om Den Kolde Krig?","options":["Sovjet afskærede alle forsyninger til Vestberlin for at tvinge de vestlige allierede ud — USA og allierede svarede med en massiv luftbro der forsynede byen i 11 måneder","USA blokerede al handel med Østberlin for at straffe Sovjet for delingen af Europa","Vestberlin blokerede selv vejen ind fra øst for at forhindre kommunister i at rejse frit","FN blokerede Berlin for at forhindre et nyt militært sammenstød"],"correct":"Sovjet afskærede alle forsyninger til Vestberlin for at tvinge de vestlige allierede ud — USA og allierede svarede med en massiv luftbro der forsynede byen i 11 måneder","accepted_answers":["Sovjet afskærede alle forsyninger til Vestberlin for at tvinge de vestlige allierede ud — USA og allierede svarede med en massiv luftbro der forsynede byen i 11 måneder"],"review_text":"I juni 1948 blokerede Sovjet alle landveje og jernbaner til Vestberlin — en by midt i den sovjetiske zone. Formålet var at tvinge vestmagterne til at opgive Vestberlin. USA og allierede svarede med en logistisk mesterydelse: en luftbro der i 11 måneder dagligt fløj mad, kul og forsyninger ind. Sovjet gav op i maj 1949. Blokaden viste Den Kolde Krigs logik: konfrontation uden direkte skud — men med enorm spænding. Den styrkede vesttyskernes tillid til USA som en troværdig allieret."}$$::jsonb,
  'mc','short',$${"concepts":["Berlin-blokaden","luftbro","Vestberlin","Sovjet","konfrontation","1948"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"concept_clarification","challenge_role":"reinforcement","domain":"cold_war"}$$::jsonb,
  'mc_single',2,'auto',true,'cold_war',7,2
);

-- ─── BAND 3 (6 questions) ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad var Glasnost og Perestrojka og hvad var Gorbatjovs formål med dem?","options":["Reformprogrammer lanceret i 1980'erne — Glasnost (åbenhed) betød mere ytringsfrihed og Perestrojka (omstrukturering) betød økonomiske reformer — formålet var at redde det sovjetiske system men reformerne accelererede i stedet dets sammenbrud","Militære programmer der skulle modernisere den sovjetiske hær og gøre den i stand til at besejre NATO","Propagandaprogrammer der skulle overbevise vestlige borgere om kommunismens overlegenhed","Aftaler med USA om fælles nedrustning der betød at begge sider afviklede størstedelen af deres atomvåben"],"correct":"Reformprogrammer lanceret i 1980'erne — Glasnost (åbenhed) betød mere ytringsfrihed og Perestrojka (omstrukturering) betød økonomiske reformer — formålet var at redde det sovjetiske system men reformerne accelererede i stedet dets sammenbrud","accepted_answers":["Reformprogrammer lanceret i 1980'erne — Glasnost (åbenhed) betød mere ytringsfrihed og Perestrojka (omstrukturering) betød økonomiske reformer — formålet var at redde det sovjetiske system men reformerne accelererede i stedet dets sammenbrud"],"review_text":"Gorbatjov (leder fra 1985) lancerede reformerne for at redde et Sovjet der stagnerede økonomisk og tabte Den Kolde Krig. Glasnost gav relativ pressefrihed — for første gang kunne sovjetborgere åbent diskutere systemets fejl. Perestrojka forsøgte markedslignende reformer af planøkonomien. Ironien var at reformerne udløste de kræfter der styrtede systemet: frihed til at tale betød frihed til at kræve mere frihed. Da Gorbatjov ikke ville bruge militær magt til at holde Østblokken nede, kollapsede den i 1989-91."}$$::jsonb,
  'mc','short',$${"concepts":["Glasnost","Perestrojka","Gorbatjov","reformer","Sovjet-sammenbrud","åbenhed"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"challenge","domain":"cold_war"}$$::jsonb,
  'mc_single',3,'auto',true,'cold_war',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad var de vigtigste årsager til Sovjetunionens sammenbrud i 1991?","options":["En kombination af økonomisk stagnation, den militære overbelastning fra oprustningskapløbet og Afghanistan-krigen, Gorbatjovs reformer der udløste centrifugale kræfter og folkebevægelser i satellit-staterne","USA angreb Sovjet militært i 1991 og tvang det til at overgive sig","Sovjet kollapsede udelukkende fordi Gorbatjov var en svag leder der personligt ødelagde et ellers velfungerende system","Sovjet opgav frivilligt at være supermagt fordi lederne besluttede at demokrati var et bedre system end kommunisme"],"correct":"En kombination af økonomisk stagnation, den militære overbelastning fra oprustningskapløbet og Afghanistan-krigen, Gorbatjovs reformer der udløste centrifugale kræfter og folkebevægelser i satellit-staterne","accepted_answers":["En kombination af økonomisk stagnation, den militære overbelastning fra oprustningskapløbet og Afghanistan-krigen, Gorbatjovs reformer der udløste centrifugale kræfter og folkebevægelser i satellit-staterne"],"review_text":"Sovjet-sammenbruddet var resultatet af strukturelle svagheder opbygget i årtier. Planøkonomien producerede nok våben men ikke nok forbrugsgoder. Afghanistanskrigen kostede 15.000 soldaterliv og enorme ressourcer uden gevinst. Oprustningskapløbet drænte en økonomi der aldrig var stor nok. Gorbatjovs reformer åbnede låget — og da han ikke ville skyde på demonstranterne i Østeuropa, kollapsede imperiet: Polen, Ungarn, DDR, Tjekkoslovakiet, Rumænien — og til sidst Sovjet selv i december 1991."}$$::jsonb,
  'mc','short',$${"concepts":["Sovjet-sammenbrud","planøkonomi","Afghanistan","Gorbatjov","folkebevægelser","1991"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"challenge","domain":"cold_war"}$$::jsonb,
  'mc_single',3,'auto',true,'cold_war',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad var doktrinen om gensidig sikret ødelæggelse (MAD) og hvorfor betragtes den paradoksalt som en form for stabilitet?","options":["Doktrinen om at ethvert atomangreb ville udløse et gengældelsesangreb der ville ødelægge angriberen — det skabte paradoksal stabilitet fordi begge sider vidste at en krig ville betyde begges undergang","En aftale om at USA og Sovjet aldrig ville bruge atomvåben fordi de var for farlige","Et offensivt program der planlagde hvornår og hvordan man bedst kunne slå til med atomvåben først","En doktrin der betød at begge sider opbyggede konventionelle styrker i stedet for atomvåben"],"correct":"Doktrinen om at ethvert atomangreb ville udløse et gengældelsesangreb der ville ødelægge angriberen — det skabte paradoksal stabilitet fordi begge sider vidste at en krig ville betyde begges undergang","accepted_answers":["Doktrinen om at ethvert atomangreb ville udløse et gengældelsesangreb der ville ødelægge angriberen — det skabte paradoksal stabilitet fordi begge sider vidste at en krig ville betyde begges undergang"],"review_text":"MAD (Mutually Assured Destruction) var den uhyggelige logik bag Den Kolde Krigs relative fred. Begge supermagter havde nok atomvåben til at udslette modstanderen — selv efter at have modtaget et første angreb. Det betød at ingen rationel leder ville angribe fordi resultatet ville være ens egen undergang. Fred gennem skræk var reelt — ingen 3. verdenskrig brød ud. Men logikken forudsatte rationelle ledere og fejlfri systemer: i 1983 var Sovjet-computere tæt på at udløse en atomalarm der viste sig at være falsk. En enkelt officer, Stanislav Petrov, standsede en potentiel atomkrig."}$$::jsonb,
  'mc','short',$${"concepts":["MAD","gensidig ødelæggelse","atomafskrækkelse","paradoksal stabilitet","Petrov"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"challenge","domain":"cold_war"}$$::jsonb,
  'mc_single',3,'auto',true,'cold_war',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad viste USA's engagement i Vietnam-krigen om Den Kolde Krigs logik og dens begrænsninger?","options":["USA gik ind i Vietnam for at forhindre kommunismens udbredelse (dominoteorien) — men interventionen fejlede og viste at ideologisk engagement i proxy-krige ikke nødvendigvis kan vindes med militær styrke","USA vandt Vietnam-krigen og forhindrede effektivt kommunismens udbredelse i Sydøstasien","Vietnam-krigen havde ingen forbindelse til Den Kolde Krig — det var en ren intern borgerkrig","USA gik ind i Vietnam fordi Sovjet direkte angreb amerikanske soldater"],"correct":"USA gik ind i Vietnam for at forhindre kommunismens udbredelse (dominoteorien) — men interventionen fejlede og viste at ideologisk engagement i proxy-krige ikke nødvendigvis kan vindes med militær styrke","accepted_answers":["USA gik ind i Vietnam for at forhindre kommunismens udbredelse (dominoteorien) — men interventionen fejlede og viste at ideologisk engagement i proxy-krige ikke nødvendigvis kan vindes med militær styrke"],"review_text":"USA's Vietnam-engagement (1955-75) var drevet af dominoteorien: hvis Vietnam faldt til kommunismen, ville hele Sydøstasien falde. USA sendte over 500.000 soldater og tabte 58.000 amerikanske liv — og trak sig alligevel ud i 1975. Nord-Vietnam vandt. Lektionen var brutal: den mest magtfulde hær i verden kunne ikke besejre en guerillabevægelse med lokal støtte. Vietnam ændrede det amerikanske selvbillede og satte spørgsmålstegn ved USA's globale interventionslinje. Det var Cold War-logikkens desperate og til sidst skadelige overstræk."}$$::jsonb,
  'mc','short',$${"concepts":["Vietnam-krigen","dominoteorien","guerilla","proxy-krig","USA","kommunisme"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"challenge","domain":"cold_war"}$$::jsonb,
  'mc_single',3,'auto',true,'cold_war',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad lærte Sovjet af sin krig i Afghanistan (1979-1989)?","options":["At militær intervention i fremmede lande er ekstremt kostbar og kan undergrave selv en supermagt — ligesom Vietnam lærte USA at guerillakrige er næsten umulige at vinde","At moderne atomvåben kan bruges til at vinde guerillakrige hurtigt og effektivt","At Afghanistan var en let militær sejr der styrkede Sovjet og viste kommunismens militære overlegenhed","At Sovjet med den rigtige strategi kunne have vundet — nederlaget skyldes udelukkende forræderi hjemme"],"correct":"At militær intervention i fremmede lande er ekstremt kostbar og kan undergrave selv en supermagt — ligesom Vietnam lærte USA at guerillakrige er næsten umulige at vinde","accepted_answers":["At militær intervention i fremmede lande er ekstremt kostbar og kan undergrave selv en supermagt — ligesom Vietnam lærte USA at guerillakrige er næsten umulige at vinde"],"review_text":"Sovjet invaderede Afghanistan i december 1979 for at støtte et marxistisk styre. Det de mødte var en brutal guerillakrig. USA støttede islamistiske modstandskæmpere (mujahideen) via CIA. 15.000 sovjetiske soldater omkom, millioner af afghanere døde eller flygtede, og Sovjet trak sig ud i 1989 uden at have vundet. Afghanistan-krigen var Sovjet's Vietnam: en kostbar, tabt guerillakrig der drænte ressourcer og moral — og accelererede sammenbruddet. Den satte samtidig Afghanistan på en kurs der endte med Taliban og 9/11."}$$::jsonb,
  'mc','short',$${"concepts":["Afghanistan","guerillakrig","Sovjet","mujahideen","CIA","Vietnam-parallel"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"challenge","domain":"cold_war"}$$::jsonb,
  'mc_single',3,'auto',true,'cold_war',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad var Helsingfors-aftalen (1975) og hvad var dens demokratiske betydning?","options":["En aftale der anerkendte Europas grænser og forpligtede alle signatarer — inklusiv Sovjet — til at respektere menneskerettigheder, som borgerne i Østblokken brugte som platform for at kræve rettigheder","En militær aftale om at fjerne alle atomvåben fra Europa og erstatte dem med konventionelle styrker","En aftale om permanent opdeling af Europa i østlig og vestlig sfære med absolut non-intervention","En handelsaftale der åbnede fri handel mellem Vest- og Østeuropa for første gang"],"correct":"En aftale der anerkendte Europas grænser og forpligtede alle signatarer — inklusiv Sovjet — til at respektere menneskerettigheder, som borgerne i Østblokken brugte som platform for at kræve rettigheder","accepted_answers":["En aftale der anerkendte Europas grænser og forpligtede alle signatarer — inklusiv Sovjet — til at respektere menneskerettigheder, som borgerne i Østblokken brugte som platform for at kræve rettigheder"],"review_text":"Helsingfors-aftalen (1975) var afspændingstidens store diplomatiske resultat. Sovjet fik anerkendelse af de europæiske grænser. Til gengæld accepterede de forpligtelse til at respektere menneskerettigheder og grundlæggende friheder. Det virkede som tom formalitet — men borgere i Polen, Tjekkoslovakiet og andre østbloklande brugte aftalen som juridisk platform til at kræve rettigheder. Charta 77 i Tjekkoslovakiet og Solidarność i Polen blomstrede delvis i ly af Helsingfors-aftalen. Ord på papir kan have reale konsekvenser."}$$::jsonb,
  'mc','short',$${"concepts":["Helsingfors","menneskerettigheder","Solidarność","Charta 77","afspænding","østblok"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"challenge","domain":"cold_war"}$$::jsonb,
  'mc_single',3,'auto',true,'cold_war',7,3
);

-- ─── BAND 4 (5 questions) ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er historikernes argument for at atomvåbnene faktisk forhindrede en 3. verdenskrig?","options":["Den gensidige atomtrussel forhindrede direkte stormagtskrig fordi rationelle ledere vidste at en krig ville betyde begge parters undergang — i modsætning til 1. og 2. verdenskrig hvor magtbalancer kollapsede i regulær krig","Atomvåbnene forhindrede ikke krig — 3. verdenskrig blev forhindret af FN's fredsbevarende styrker","Atomvåbnene spillede ingen rolle — USA og Sovjet ville aldrig have kæmpet direkte mod hinanden under alle omstændigheder","Atomvåbnene forhindrede krig fordi de var for komplekse og dyre til at bruge — ikke fordi nogen frygtede dem"],"correct":"Den gensidige atomtrussel forhindrede direkte stormagtskrig fordi rationelle ledere vidste at en krig ville betyde begge parters undergang — i modsætning til 1. og 2. verdenskrig hvor magtbalancer kollapsede i regulær krig","accepted_answers":["Den gensidige atomtrussel forhindrede direkte stormagtskrig fordi rationelle ledere vidste at en krig ville betyde begge parters undergang — i modsætning til 1. og 2. verdenskrig hvor magtbalancer kollapsede i regulær krig"],"review_text":"Den lange fred — at Vesteuropa ikke oplevede storkrig i 70+ år — er historisk bemærkelsesværdig sammenlignet med forrige århundrede. Historikere som John Lewis Gaddis argumenterer at atomafskrækkelse var nøglen. Magtbalancer uden atomvåben kollapsede to gange på 30 år (1914, 1939). Med atomvåben var prisen for fejlkalkulation så astronomisk høj at rationelle aktører valgte afspænding frem for eskalation. Argumentet er ikke at atomvåben er gode — men at de i en konkret historisk situation etablerede en skræk-baseret stabilitet. Det er et ubehageligt men empirisk påpegningsværdigt faktum."}$$::jsonb,
  'mc','short',$${"concepts":["atomafskrækkelse","den lange fred","Gaddis","bipolaritet","stabilitet","MAD"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"analytical_challenge","domain":"cold_war"}$$::jsonb,
  'mc_single',4,'auto',true,'cold_war',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er Den Kolde Krigs vigtigste arv i Rusland og den post-sovjetiske verden?","options":["En dyb national ydmygelse over imperiekollapset, mistillid til Vestens intentioner og en politisk kultur der søger at genvinde stormagts-status — dynamikker der forklarer meget af Ruslands adfærd efter 1991","Rusland omfavnede fuldt demokrati og markedsøkonomi efter 1991 og Den Kolde Krigs arv er fuldstændig overvundet","Den Kolde Krig har ingen relevans for nutidigt Rusland — landet er fuldstændig nyt siden 1991","Rusland er permanent svækket af Sovjet-sammenbruddet og kan aldrig igen spille en vigtig rolle i international politik"],"correct":"En dyb national ydmygelse over imperiekollapset, mistillid til Vestens intentioner og en politisk kultur der søger at genvinde stormagts-status — dynamikker der forklarer meget af Ruslands adfærd efter 1991","accepted_answers":["En dyb national ydmygelse over imperiekollapset, mistillid til Vestens intentioner og en politisk kultur der søger at genvinde stormagts-status — dynamikker der forklarer meget af Ruslands adfærd efter 1991"],"review_text":"Sovjet-sammenbruddet var for mange russere ikke en befrielse men et nationalt traume: imperiet gik tabt, levestandarden kollapsede i 1990'erne, og NATO udvidede sig østpå. Putin — der kaldte Sovjet-sammenbruddet 'det 20. århundredes største geopolitiske katastrofe' — kanaliserede denne ydmygelse. Russisk udenrigspolitik siden 2000 kan forstås som forsøg på at genvinde indflydelse i nærområdet: Georgien 2008, Ukraine 2014 og 2022. Den Kolde Krigs arv er ikke overvundet — den lever videre i geopolitikkens struktur og i den russiske selvforståelse."}$$::jsonb,
  'mc','short',$${"concepts":["Rusland","imperial arv","NATO-udvidelse","Putin","ydmygelse","post-sovjet"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"analytical_challenge","domain":"cold_war"}$$::jsonb,
  'mc_single',4,'auto',true,'cold_war',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad betød Den Kolde Krig for landene i den tredje verden?","options":["Mange udviklingslande blev slagmarker for supermagternes proxy-krige og led enorme menneskelige tab — deres egne politiske valg blev undergravet af supermagt-intervention der prioriterede ideologisk loyalitet over lokal velfærd","Den tredje verden nød godt af Den Kolde Krig fordi begge supermagter gav generøs bistand uden betingelser","Lande i den tredje verden var uinteressante for supermagterne og fik lov at udvikle sig i fred","Den Kolde Krig styrkede demokrati og stabilitet i de fleste lande i Afrika, Asien og Latinamerika"],"correct":"Mange udviklingslande blev slagmarker for supermagternes proxy-krige og led enorme menneskelige tab — deres egne politiske valg blev undergravet af supermagt-intervention der prioriterede ideologisk loyalitet over lokal velfærd","accepted_answers":["Mange udviklingslande blev slagmarker for supermagternes proxy-krige og led enorme menneskelige tab — deres egne politiske valg blev undergravet af supermagt-intervention der prioriterede ideologisk loyalitet over lokal velfærd"],"review_text":"Korea, Vietnam, Angola, Mozambique, Nicaragua, El Salvador, Afghanistan — overalt forsøgte begge supermagter at sikre sig loyale regimer. USA støttede anti-kommunistiske diktatorer; Sovjet støttede marxistiske regimer. Millioner af civile omkom. Chile 1973: CIA støttede kuppet mod den folkevalgte Allende. Congo, Indonesia, Iran — interventionernes liste er lang. Det globale system 1945-89 var ikke bipolært set fra den tredje verdens perspektiv — det var et system hvor supermagternes kamp kostede de fattigste og svageste stater uforholdsmæssigt dyrt."}$$::jsonb,
  'mc','short',$${"concepts":["tredje verden","proxy-krige","CIA","intervention","Chile","menneskelige omkostninger"],"misconception_type":"scope_confusion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"analytical_challenge","domain":"cold_war"}$$::jsonb,
  'mc_single',4,'auto',true,'cold_war',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad viser Den Kolde Krigs teknologikapløb om sammenhængen mellem militær konkurrence og civil teknologiudvikling?","options":["Militær konkurrence drev teknologiske gennembrud der sidenhen kom civilsamfundet til gode — internettet, GPS og satellitkommunikation stammer direkte fra Cold War-forskning","Al Cold War-teknologisk forskning var hemmeligt militær og er aldrig delt med offentligheden","Teknologikapløbet var rent spildt — ingen af opdagelserne har haft civile anvendelser","Kun rumfart-teknologien kom fra Den Kolde Krig — al anden moderne teknologi har andre rødder"],"correct":"Militær konkurrence drev teknologiske gennembrud der sidenhen kom civilsamfundet til gode — internettet, GPS og satellitkommunikation stammer direkte fra Cold War-forskning","accepted_answers":["Militær konkurrence drev teknologiske gennembrud der sidenhen kom civilsamfundet til gode — internettet, GPS og satellitkommunikation stammer direkte fra Cold War-forskning"],"review_text":"Internettets forgænger ARPANET var et amerikansk militærprojekt designet til at modstå et atomangreb. GPS blev udviklet af det amerikanske forsvar. Satellitkommunikation udsprang af rumkapløbet. Moderne jetfly fik enorm militær investering. Det er ikke et argument for at militær konkurrence er det bedste grundlag for teknologisk fremgang — men et faktum at Cold War-ressourcerne finansierede grundlæggende teknologier vi alle bruger dagligt. Spørgsmålet er om de samme investeringer i fredelig forskning ville have givet endnu bedre resultater."}$$::jsonb,
  'mc','short',$${"concepts":["internet","ARPANET","GPS","satellit","teknologispin-off","militærforskning"],"misconception_type":"scope_confusion","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"analytical_challenge","domain":"cold_war"}$$::jsonb,
  'mc_single',4,'auto',true,'cold_war',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad viste Cuba-krisen om nødvendigheden af direkte kommunikation mellem supermagterne?","options":["Cuba-krisen viste at mangel på direkte kommunikation øgede atomrisikoen dramatisk — derfor oprettede USA og Sovjet en direkte krisekommunikationslinje (den røde telefon) i 1963","Cuba-krisen viste at supermagterne aldrig behøvede direkte kommunikation — diplomater tog altid tid nok","Den røde telefon eksisterede allerede før Cuba-krisen og spillede en afgørende rolle under selve krisen","Cuba-krisen viste at atomkrig var uundgåelig og kun ren held forhindrede den"],"correct":"Cuba-krisen viste at mangel på direkte kommunikation øgede atomrisikoen dramatisk — derfor oprettede USA og Sovjet en direkte krisekommunikationslinje (den røde telefon) i 1963","accepted_answers":["Cuba-krisen viste at mangel på direkte kommunikation øgede atomrisikoen dramatisk — derfor oprettede USA og Sovjet en direkte krisekommunikationslinje (den røde telefon) i 1963"],"review_text":"Under Cuba-krisen (oktober 1962) tog det timer at sende og modtage beskeder via telegram og ambassadørnetværk — uacceptabelt når beslutninger skulle træffes på minutter. Som direkte resultat oprettede USA og Sovjet i 1963 en direkte kommunikationslinje (teknisk en teletype, ikke en telefon). Den blev brugt under bl.a. Seksdagskrigen 1967 og Yom Kippur-krigen 1973. Det er et eksempel på at internationale kriser ikke kun skaber risiko men også institutionelle læringssvar: systemer forbedres fordi konsekvenserne af fejl er for store."}$$::jsonb,
  'mc','short',$${"concepts":["røde telefon","Cuba-krisen","krisekommunikation","direkte linje","institutionel læring"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"causal","insight_type":"reframing","challenge_role":"analytical_challenge","domain":"cold_war"}$$::jsonb,
  'mc_single',4,'auto',true,'cold_war',7,4
);

-- ─── BAND 5 (3 questions) ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Var Den Kolde Krig uundgåelig givet USA's og Sovjet's ideologiske og geopolitiske modsætninger — og hvad siger den historiske debat?","options":["Revisionistiske historikere argumenterer at fejltagelser og misforståelser spillede en stor rolle — men strukturalisterne svarer at to supermagter med uforenelige ideologier og globale ambitioner næppe kunne have undgået systematisk konfrontation","Den Kolde Krig var 100% uundgåelig fordi kommunisme og kapitalisme er naturnødvendigt fjendtlige og aldrig kan sameksistere fredeligt","Den Kolde Krig var fuldt ud undgåelig — to rationelle statsledere i 1945 var nok til at have forebygget hele konflikten","Spørgsmålet om Den Kolde Krigs uundgåelighed er rent akademisk og har ingen relevans for nutidige supermagtsforhold"],"correct":"Revisionistiske historikere argumenterer at fejltagelser og misforståelser spillede en stor rolle — men strukturalisterne svarer at to supermagter med uforenelige ideologier og globale ambitioner næppe kunne have undgået systematisk konfrontation","accepted_answers":["Revisionistiske historikere argumenterer at fejltagelser og misforståelser spillede en stor rolle — men strukturalisterne svarer at to supermagter med uforenelige ideologier og globale ambitioner næppe kunne have undgået systematisk konfrontation"],"review_text":"Historikerdebatten er reel og fagligt levende. Ortodokse: Stalins ekspansionisme var uundgåeligt konfronterende. Revisionistiske (William A. Williams m.fl.): USA's aggressive containment-politik og kapitalinteresser drev konflikten. Post-revisionistiske: begge sider bidrog via misforståelse og overdrevet trusselsvurdering. Strukturalister: bipolære systemer med nukleare aktører producerer afskrækkelse men ikke nødvendigvis fred. Svaret er nuanceret — ingen enkelt faktor forklarer 45 år med global spænding. Men spørgsmålet er ikke kun historisk: det påvirker direkte om USA og Kina kan undgå den samme dynamik."}$$::jsonb,
  'mc','short',$${"concepts":["uundgåelighed","revisionisme","strukturalisme","bipolaritet","historikerDebat","USA-Kina"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}$$::jsonb,
  'mc_single',5,'auto',true,'cold_war',7,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad fortæller Den Kolde Krig om stabiliteten i bipolære magtbalancesystemer sammenlignet med multipolære systemer?","options":["Bipolære systemer kan skabe en form for stabilitet fordi klare alliancer reducerer usikkerhed — men de er skrøbelige fordi eskalation i ét led kan sprede sig globalt og der er ingen tredjepart til at mægle","Bipolære systemer er altid mere stabile end multipolære fordi klare alliancer eliminerer al usikkerhed","Multipolære systemer er altid mere stabile fordi mange aktører balancerer hinanden og ingen enkelt aktør dominerer","Magtbalanceteorier er fuldstændig irrelevante for forståelsen af Den Kolde Krig — det var udelukkende ideologi der drev konflikten"],"correct":"Bipolære systemer kan skabe en form for stabilitet fordi klare alliancer reducerer usikkerhed — men de er skrøbelige fordi eskalation i ét led kan sprede sig globalt og der er ingen tredjepart til at mægle","accepted_answers":["Bipolære systemer kan skabe en form for stabilitet fordi klare alliancer reducerer usikkerhed — men de er skrøbelige fordi eskalation i ét led kan sprede sig globalt og der er ingen tredjepart til at mægle"],"review_text":"Kenneth Waltz' neorealisme argumenterer at bipolære systemer paradoksalt er mere stabile end multipolære: to dominerende magter ved præcis hvem modstanderen er og overvåger hinanden tæt. Men Den Kolde Krig viste også skrøbeligheden: Cuba-krisens nærved-atomkrig og Stanislav Petrovs falske raketvarsel i 1983. Sammenlignet med 1. verdenskrig — et multipolært alliancesystem der kollapsede lynhurtigt — holdt den bipolære orden uden direkte supermagt-krig. Men det er uklogt at se det som systemisk nødvendighed snarere end en kombination af rationelle aktører, held og MAD-logik."}$$::jsonb,
  'mc','short',$${"concepts":["bipolaritet","multipolaritet","Waltz","neorealisme","magtbalance","stabilitet"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}$$::jsonb,
  'mc_single',5,'auto',true,'cold_war',7,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $${"question":"Hvad er den analytisk vigtigste lektie Den Kolde Krig giver for forståelsen af nutidens forhold mellem USA og Kina?","options":["Historien viser at en etableret magt og en stigende magt hyppigt ender i konflikt — Den Kolde Krig demonstrerer at dette kan undgås med afskrækkelse og diplomati men kræver institutionelle kanaler og aktiv kriseforebyggelse","Den Kolde Krig viser at USA altid vinder og Kina vil kollapse ligesom Sovjet gjorde","Den Kolde Krig er fuldstændig irrelevant for USA-Kina-forholdet fordi situationen er fundamentalt anderledes","Den vigtigste lektie er at militær oprustning altid er den bedste løsning mod en rivaliserende supermagt"],"correct":"Historien viser at en etableret magt og en stigende magt hyppigt ender i konflikt — Den Kolde Krig demonstrerer at dette kan undgås med afskrækkelse og diplomati men kræver institutionelle kanaler og aktiv kriseforebyggelse","accepted_answers":["Historien viser at en etableret magt og en stigende magt hyppigt ender i konflikt — Den Kolde Krig demonstrerer at dette kan undgås med afskrækkelse og diplomati men kræver institutionelle kanaler og aktiv kriseforebyggelse"],"review_text":"Graham Allison (Harvard) identificerede at ud af 16 historiske tilfælde hvor en stigende magt udfordrede en etableret magt, endte 12 i krig — den såkaldte Thukydides-fælde. Den Kolde Krig er et af de 4 der undgik krig. Lektionerne: institutionelle kommunikationskanaler (den røde telefon), krisehåndtering (Cuba), klare røde linjer og gensidig afskrækkelse forhindrede det værste. USA-Kina-forholdet har mange paralleller: teknologikapløb, proxy-konkurrence, ideologisk konflikt og nukleare kapabiliteter. Den vigtigste lektie er ikke at krig er uundgåelig — men at undgåelse kræver aktivt institutionelt arbejde og vilje til diplomati."}$$::jsonb,
  'mc','short',$${"concepts":["Thukydides-fælde","USA-Kina","Allison","stigende magt","diplomati","kriseforebyggelse"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"cold_war"}$$::jsonb,
  'mc_single',5,'auto',true,'cold_war',7,5
);
