-- Section 148 — Vikings Grade 8 Band Coverage Fix
-- learning_objective=vikings, target_grade=8, is_active=true
-- Distribution: B1(2) + B2(4) + B3(6) + B4(1) + B5(3) = 16 questions
-- Existing G8 topics avoided: handel>plyndring, Island vs Vinland,
--   konger konverterede, kongemagts-konsolidering (all B4, existing)
-- New topics: periodisation, geographic origins, source criticism,
--   longship, Valhalla/Norse religion, social hierarchy,
--   "viking" as category, eastern trade networks, Christianization,
--   women's legal position, raider vs settler, runestones,
--   state formation (B4), myth/19c construction (B5),
--   violence+cultural exchange (B5), historiographic perspective (B5)
-- Before G8-specific: B1=0 B2=0 B3=0 B4=4 B5=0 → 4
-- After  G8-specific: B1=2 B2=4 B3=6 B4=5 B5=3 → 20
-- Cumulative grade-8 pool before: 54 (G4:25 + G5:25 + G8:4)
-- Cumulative grade-8 pool after:  70 (G4:25 + G5:25 + G8:20)

-- ─── BAND 1 (2 questions) ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v1q${"question":"Hvad betegner begrebet vikingetiden og hvornår regner historikere den for at have fundet sted?","options":["Perioden ca. 793-1066 e.Kr. da skandinaviske folk ekspanderede over store dele af Europa og videre via handel, bosætning og plyndring","Perioden ca. 500-1200 e.Kr. da hele Europa var under skandinavisk kontrol","Forhistorien i Skandinavien — perioden inden skrift og kristendom ca. 2000-200 f.Kr.","Oldtidsdanmark i perioden ca. 200-500 e.Kr. inden den store folkevandring"],"correct":"Perioden ca. 793-1066 e.Kr. da skandinaviske folk ekspanderede over store dele af Europa og videre via handel, bosætning og plyndring","accepted_answers":["Perioden ca. 793-1066 e.Kr. da skandinaviske folk ekspanderede over store dele af Europa og videre via handel, bosætning og plyndring"],"review_text":"Vikingetiden regnes traditionelt fra plyndringen af Lindisfarne-klostret i England i 793 til Vilhelm Erobrerens sejr ved Hastings i 1066 som satte et punktum for skandinavisk ekspansion mod vest. Perioden er kendetegnet ved skandinavers enorme geografiske rækkevidde: fra Nordamerika i vest til Konstantinopel og Bagdad i øst. Det er ikke en periode der var afgrænset og klar for dem der levede i den — periodiseringen er en moderne historisk konstruktion."}$v1q$::jsonb,
  'mc','short',$v1m${"concepts":["vikingetiden","periodisering","793","1066","skandinavisk ekspansion"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"recognition","insight_type":"concept_clarification","challenge_role":"entry_level","domain":"vikings"}$v1m$::jsonb,
  'mc_single',1,'auto',true,'vikings',8,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v2q${"question":"Hvad kendetegnede de tre skandinaviske udgangspunkter og hvilke retninger ekspanderede de primært?","options":["Nordmændene ekspanderede primært mod vest (Irland, Island, Nordamerika), danskerne mod syd og vest (England, Frankrig), og svenskerne primært mod øst (russiske floder, Byzans)","Alle tre skandinaviske folk ekspanderede udelukkende mod England og delte territoriet ligeligt imellem sig","Danskerne ekspanderede mod øst, nordmændene mod syd og svenskerne mod vest — retningerne var omvendte af hvad de fleste tror","Der var ingen forskel på de tre folk — alle vikinger var ens og kæmpede de samme steder med de samme mål"],"correct":"Nordmændene ekspanderede primært mod vest (Irland, Island, Nordamerika), danskerne mod syd og vest (England, Frankrig), og svenskerne primært mod øst (russiske floder, Byzans)","accepted_answers":["Nordmændene ekspanderede primært mod vest (Irland, Island, Nordamerika), danskerne mod syd og vest (England, Frankrig), og svenskerne primært mod øst (russiske floder, Byzans)"],"review_text":"De tre skandinaviske folk havde geografisk betingede ekspansionsretninger. Norge med sin lange kystlinje vendt mod Atlanterhavet sendte vikinger mod de britiske øer, Færøerne, Island og til sidst Grønland og Vinland. Danmark med sin placering ud mod Nordsøen og Kanalen rettede sig mod England og Det Frankiske Rige. Sverige med adgang til Østersøen og russiske vandveje skabte handelsruter øst- og sydpå til Byzans og det islamiske Abbasidiske Kalifat. Denne geografiske logik forklarer meget af vikingetidens kompleksitet."}$v2q$::jsonb,
  'mc','short',$v2m${"concepts":["Norge","Danmark","Sverige","ekspansionsretninger","geografisk logik"],"misconception_type":"overgeneralization","cognitive_skill":"comprehension","difficulty_type":"recognition","insight_type":"concept_clarification","challenge_role":"entry_level","domain":"vikings"}$v2m$::jsonb,
  'mc_single',1,'auto',true,'vikings',8,1
);

-- ─── BAND 2 (4 questions) ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v3q${"question":"Hvilke typer kilder bruger historikere til at studere vikingetiden og hvad er den vigtigste udfordring ved dem?","options":["Sagaerne, runesten, arkæologiske fund og fremmede skriftlige beretninger — udfordringen er at kilderne er fragmentariske, partiske eller nedskrevet længe efter de beskrevne begivenheder","Vikingerne efterlod detaljerede historiske krøniker der giver et præcist og komplet billede af vikingesamfundet","Den eneste troværdige kilde er arkæologiske fund da alle skriftlige kilder er demonstreret falske","Sagaerne er skrevet af vikingerne selv under vikingetiden og er derfor de mest direkte og troværdige kilder vi har"],"correct":"Sagaerne, runesten, arkæologiske fund og fremmede skriftlige beretninger — udfordringen er at kilderne er fragmentariske, partiske eller nedskrevet længe efter de beskrevne begivenheder","accepted_answers":["Sagaerne, runesten, arkæologiske fund og fremmede skriftlige beretninger — udfordringen er at kilderne er fragmentariske, partiske eller nedskrevet længe efter de beskrevne begivenheder"],"review_text":"Kildeunderlaget for vikingetiden er broget. Islandske sagaer er skrevet 150-300 år efter de begivenheder de beskriver og blander fakta og fiktion. Runestene er samtidige men korte og formulerede som mindesmærker ikke historieskrivning. Arabiske, frankiske og angelsaksiske skriftlige beretninger er samtidige men skrevet af vikingernes ofre eller handelspartnere og dermed partiske. Arkæologiske fund (skibe, redskaber, bopladser) er objektive men stumme om motiver og beslutninger. Videnskabeligt historiearbejde kræver kritisk krydsning af alle kildetype."}$v3q$::jsonb,
  'mc','short',$v3m${"concepts":["sagaer","runesten","arkaeologi","kildekritik","fragmentarisk"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"concept_clarification","challenge_role":"reinforcement","domain":"vikings"}$v3m$::jsonb,
  'mc_single',2,'auto',true,'vikings',8,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v4q${"question":"Hvilken central rolle spillede langskibet i vikingernes ekspansion?","options":["Langskibet kombinerede lavt dybgangde der muliggjorde sejlads op i floder og landing på strande med høj sødygtighed der muliggjorde oceankrydsninger til Island og Nordamerika","Langskibet blev udelukkende brugt til krigstogter — vikingerne brugte helt andre skibstyper til handel","Langskibet var for skrøbeligt til oceansejlads og blev kun brugt langs kyster og i rolige fjorde","Langskibet var vikingernes vigtigste opfindelse men for lavt til at bære last så handel var umulig med det"],"correct":"Langskibet kombinerede lavt dybgangde der muliggjorde sejlads op i floder og landing på strande med høj sødygtighed der muliggjorde oceankrydsninger til Island og Nordamerika","accepted_answers":["Langskibet kombinerede lavt dybgangde der muliggjorde sejlads op i floder og landing på strande med høj sødygtighed der muliggjorde oceankrydsninger til Island og Nordamerika"],"review_text":"Langskibet var en teknologisk revolution inden for sejlads. Med kun 50-90 cm dybgangde kunne det sejle op i de europæiske floder — Seine, Thames, Rhinen og russiske vandveje — langt fra havet til overraskelsesangreb langt inde på kontinentet. Symmetrisk for og agter betød det kunne sejle begge veje uden at vende. Klinkbyggeriet (overlappende planker) gav fleksibilitet i bølger. Knorren (handelsskibet) var bredere og dybere til last. Begge skibstyper supplerede hinanden i vikingernes maritime system."}$v4q$::jsonb,
  'mc','short',$v4m${"concepts":["langskib","dybgangde","floder","oceansejlads","teknologi"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"concept_clarification","challenge_role":"reinforcement","domain":"vikings"}$v4m$::jsonb,
  'mc_single',2,'auto',true,'vikings',8,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v5q${"question":"Hvad var Valhalla i den norrøne religion og hvilken funktion havde forestillingen om det for vikingernes krigerkultur?","options":["Odins kongsgård i Asgård hvortil faldne krigere hentedes af valkyrierne — forestillingen ophøjede krigerisk mod og adfærd ved at love et hæderfuldt efterliv til dem der faldt i kamp","Helheimen — det underjordiske rige hvortil alle døde kom uanset hvordan de levede og døde","En historisk borg i Sverige som vikingerne brugte som kongesæde og religiøst centrum for blotsoffre","En forestilling kun udbredt på Island der spillede ingen rolle for vikingerne i Danmark og Norge"],"correct":"Odins kongsgård i Asgård hvortil faldne krigere hentedes af valkyrierne — forestillingen ophøjede krigerisk mod og adfærd ved at love et hæderfuldt efterliv til dem der faldt i kamp","accepted_answers":["Odins kongsgård i Asgård hvortil faldne krigere hentedes af valkyrierne — forestillingen ophøjede krigerisk mod og adfærd ved at love et hæderfuldt efterliv til dem der faldt i kamp"],"review_text":"I norrøn kosmologi var Valhalla den store sal i Asgård hvor halvdelen af krigsofferdøde (einherjar) kom efter at være udvalgt af Odins valkyrier. Her trænede de til Ragnarok, den endelige kamp. Kontrasten var Hel — det grå rige for dem der døde af sygdom eller alderdom. Denne forestilling om en hierarki af efterliv efter dødsomstændighed — ikke efter moralsk opførsel som i kristen teologi — understøttede en krigerkultur hvor kampdød var hæderfuld. Forestillingen er primært rekonstrueret fra islandske tekster fra 1200-tallet og er muligvis mere islandsk end pan-skandinavisk."}$v5q$::jsonb,
  'mc','short',$v5m${"concepts":["Valhalla","Odin","valkyrier","norroen religion","krigerkultur","einherjar"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"concept_clarification","challenge_role":"reinforcement","domain":"vikings"}$v5m$::jsonb,
  'mc_single',2,'auto',true,'vikings',8,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v6q${"question":"Hvad kendetegnede den sociale hierarki i vikingesamfundet?","options":["Tre hovedelag: jarler (adel og høvdinge), karle (frie bønder, håndværkere og handelsmænd) og thraller (slaver) — trældom var udbredt og trællen var et vigtigt resultat af vikingernes fangsttagning under togter","Et fuldstændig ligeligt samfund uden nogen social hierarki hvor alle skandinaver havde de samme rettigheder og pligter","Et feudalt system som i resten af middelalderens Europa med vasaller, lensherrer og livegne bønder","To lag: konger og almue — der var ingen mellemgruppe af frie bønder eller adel i vikingesamfundet"],"correct":"Tre hovedelag: jarler (adel og høvdinge), karle (frie bønder, håndværkere og handelsmænd) og thraller (slaver) — trældom var udbredt og trællen var et vigtigt resultat af vikingernes fangsttagning under togter","accepted_answers":["Tre hovedelag: jarler (adel og høvdinge), karle (frie bønder, håndværkere og handelsmænd) og thraller (slaver) — trældom var udbredt og trællen var et vigtigt resultat af vikingernes fangsttagning under togter"],"review_text":"Vikingesamfundets tre lag er rekonstrueret primært fra den islandske Rigsthulakvad og arkæologiske fund. Jarlerne var de mægtige høvdinge med mange thegner. Karlerne var den brede frie middelklasse af bønder der ejede jord, bar våben og deltog i tinget. Thrallerne var slaver taget under togter — primært fra de britiske øer og Irland. Trællehandel var en væsentlig del af vikingernes økonomi; arabiske handelspartnere betalte sølv for skandinaviske slaver. Tingen (det lokale råd) gav frie karle en demokratisk stemme der ikke fandtes i Vesteuropas feudale samfund."}$v6q$::jsonb,
  'mc','short',$v6m${"concepts":["jarl","karl","thrall","social hierarki","traeldom","tinget"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"vikings"}$v6m$::jsonb,
  'mc_single',2,'auto',true,'vikings',8,2
);

-- ─── BAND 3 (6 questions) ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v7q${"question":"Hvorfor er begrebet viking problematisk som historisk kategori og hvad er det mere præcist en betegnelse for?","options":["De fleste skandinaver var bønder og handelsmænd — viking betegner sandsynligvis dem der deltog i togter (af norrønt vikingr) og var altså en aktivitet ikke en identitet der dækkede hele befolkningen","Viking er en præcis betegnelse der dækker alle skandinaver i perioden 793-1066 da hele befolkningen deltog aktivt i plyndretogter","Viking er et moderne ord opfundet af romantiske forfattere i 1800-tallet der ingen historisk rod overhovedet har","Viking betegner specifikt den kristne del af den skandinaviske befolkning der modstod de hedenske traditioner"],"correct":"De fleste skandinaver var bønder og handelsmænd — viking betegner sandsynligvis dem der deltog i togter (af norrønt vikingr) og var altså en aktivitet ikke en identitet der dækkede hele befolkningen","accepted_answers":["De fleste skandinaver var bønder og handelsmænd — viking betegner sandsynligvis dem der deltog i togter (af norrønt vikingr) og var altså en aktivitet ikke en identitet der dækkede hele befolkningen"],"review_text":"Det norrøne ord vikingr optræder i kilderne som betegnelse for en person der er gået på togt — ikke som en national eller etnisk identitet. At kalde hele den skandinaviske befolkning i 793-1066 for vikinger svarer til at kalde alle nutidens danskere for soldater fordi nogle tjener i hæren. Langt de fleste skandinaver levede som bønder, fiskere og håndværkere og deltog aldrig i togter. Brugen af viking som samlet identitetsbetegnelse er primært en konstruktion fra 1800-tallets nationalromantik der søgte heroiske forfædre. Det er et godt eksempel på at periodernes navne afspejler eftertidens selvbillede mere end de historiske aktørers selvforståelse."}$v7q$::jsonb,
  'mc','short',$v7m${"concepts":["viking som kategori","vikingr","aktivitet vs identitet","nationalromantik","kildekritik"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"challenge","domain":"vikings"}$v7m$::jsonb,
  'mc_single',3,'auto',true,'vikings',8,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v8q${"question":"Hvordan bidrog svenske vikinger til at forbinde øst og vest i middelalderen via handelsnetværk?","options":["Svenske vikinger sejlede øst via russiske floder til Konstantinopel og Bagdad og oprettede handelsposter som Novgorod og Kiev der skabte en rute der forbandt Nordeuropas pelse og slaver med det islamiske sølvmarked og Byzans","Vikingernes handel var begrænset til Nordvesteuropa og de havde ingen kontakt med det islamiske verden eller Byzans","Svenske vikinger erobrede Konstantinopel og oprettede et skandinavisk imperium i hele Østeuropa","Vikingernes østlige handelsnetværk var ubetydelig sammenlignet med arabernes og romernes handelsveje"],"correct":"Svenske vikinger sejlede øst via russiske floder til Konstantinopel og Bagdad og oprettede handelsposter som Novgorod og Kiev der skabte en rute der forbandt Nordeuropas pelse og slaver med det islamiske sølvmarked og Byzans","accepted_answers":["Svenske vikinger sejlede øst via russiske floder til Konstantinopel og Bagdad og oprettede handelsposter som Novgorod og Kiev der skabte en rute der forbandt Nordeuropas pelse og slaver med det islamiske sølvmarked og Byzans"],"review_text":"Svenske vikinger — i kilderne kaldet væringer eller rus — sejlede ad Dnepr og Volga-ruterne til det Kaspiske Hav og Sortehavet. De oprettede handelsposter som Staraja Ladoga, Novgorod og Kiev og handlede med arabiske sølvmønter (dirhemer) fundet i tusindvis i skandinaviske arkæologiske fund. Fra nord bragte de pelse, voks, rav, og slaver. Fra syd og øst bragte de sølv, silke og krydderier. Disse rus-vikinger lagde grunden til det tidlige russiske fyrstendømme Kievan Rus. Det er et eksempel på at vikingetiden var langt mere handelsdrevet end det populære billede tilsiger."}$v8q$::jsonb,
  'mc','short',$v8m${"concepts":["vaeringe","Rus-ruten","Kievan Rus","Novgorod","Kiev","osterhandel"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"challenge","domain":"vikings"}$v8m$::jsonb,
  'mc_single',3,'auto',true,'vikings',8,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v9q${"question":"Hvad kendetegnede kristningsprocessen i Skandinavien og hvad var dens vigtigste konsekvenser?","options":["Kristningen var gradvis (ca. 960-1100) drevet af missionærer, politisk pres og kongers strategiske valg — konsekvenserne var kirkebyggeri, skriftlig latinkultur, integration i det europæiske netværk og gradvis afvikling af norrøn religion","Skandinavien blev kristent på en enkelt dag i år 1000 da alle nordiske konger underskrev en traktat i Rom","Kristningen var tvungen og alle skandinaver modstod aktivt og blev kun kristne under direkte militær trussel","Kristningen ændrede kun privat religiøs praksis og havde ingen politiske eller kulturelle konsekvenser for samfundsstrukturen"],"correct":"Kristningen var gradvis (ca. 960-1100) drevet af missionærer, politisk pres og kongers strategiske valg — konsekvenserne var kirkebyggeri, skriftlig latinkultur, integration i det europæiske netværk og gradvis afvikling af norrøn religion","accepted_answers":["Kristningen var gradvis (ca. 960-1100) drevet af missionærer, politisk pres og kongers strategiske valg — konsekvenserne var kirkebyggeri, skriftlig latinkultur, integration i det europæiske netværk og gradvis afvikling af norrøn religion"],"review_text":"Harald Blåtand erklærede sig selv kristen ca. 960 og rejste Jellingsten II som erklærer ham som den der kristnede danskerne. Men kristning var en langvarig process ikke en enkelt begivenhed. Kongernes motiver var delvist politiske: kristen kongeideologi legitimerede centralmagt, og en kristen konge var en mere acceptable handelspartner for det kristne Europa. Konsekvenserne var dybe: kirker og klostre opbyggede en latinsk skriftkultur, kirkens retslige normer overtog tingsystemets lokale lov, og offerskik, kremering og norrøne grave erstattedes med kristne begravelser. Norrøn religion overlevede som folkemindekultur men ikke som institutionel praksis."}$v9q$::jsonb,
  'mc','short',$v9m${"concepts":["kristning","Harald Blåtand","Jellingsten","latinkultur","politisk legitimitet"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"challenge","domain":"vikings"}$v9m$::jsonb,
  'mc_single',3,'auto',true,'vikings',8,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v10q${"question":"Hvad kendetegnede kvinders retsstilling i vikingesamfundet sammenlignet med kvinder i det samtidige Vesteuropa?","options":["Vikingetidens kvinder havde relativt betydelige rettigheder i en middelalderlig sammenhæng — de kunne eje ejendom, kræve skilsmisse og drive handel — men var stadig underordnet mænd og kilderne er begrænsede","Vikingetidens kvinder var fuldstændigt ligestillede med mænd og havde nøjagtigt de samme juridiske og politiske rettigheder","Vikingetidens kvinder var mere undertrykte end samtidige europæiske kvinder og havde ingen juridiske rettigheder overhovedet","Kvinder spillede ingen rolle i vikingesamfundet og omtales slet ikke i de historiske eller arkæologiske kilder"],"correct":"Vikingetidens kvinder havde relativt betydelige rettigheder i en middelalderlig sammenhæng — de kunne eje ejendom, kræve skilsmisse og drive handel — men var stadig underordnet mænd og kilderne er begrænsede","accepted_answers":["Vikingetidens kvinder havde relativt betydelige rettigheder i en middelalderlig sammenhæng — de kunne eje ejendom, kræve skilsmisse og drive handel — men var stadig underordnet mænd og kilderne er begrænsede"],"review_text":"Juridiske bestemmelser fra islandske love (Grágás) og sagabeskrivelser antyder at vikingetidens kvinder kunne eje ejendom selvstændigt, arve, indgå og opløse ægteskab, og have husstandsmyndighed (husfrueautoritet). Det var mere end samtidige frankiske og angelsaksiske kvinder i mange tilfælde. Arkæologiske fund af velhavende kvindegrave (fx Osebergskibet med to kvinder) bekræfter at højststående kvinder havde reel status. Men kilderne er primært fra det islandske miljø og fra eliten — hverdagskvindens retsstilling var sandsynligvis mere begrænset. Nuancen er vigtig: relativt mere rettigheder er ikke det samme som ligestilling."}$v10q$::jsonb,
  'mc','short',$v10m${"concepts":["kvinder","retsstilling","Gragas","Osebergskib","middelalderlig sammenligning"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"reframing","challenge_role":"challenge","domain":"vikings"}$v10m$::jsonb,
  'mc_single',3,'auto',true,'vikings',8,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v11q${"question":"Hvorfor er distinktionen mellem vikingen som raider og vikingen som settler vigtig for en nuanceret historisk forståelse?","options":["De samme skandinaver der plyndrede et sted i én generation kunne bosætte sig fredeligt i en anden — raiding og bosætning var ikke to typer vikinger men aktiviteter betinget af muligheder: Danelaw og Normandiet var bosætninger Island et nybygningssamfund","Raidere og settlere var to fuldstændigt adskilte grupper — plyndrerne vendte altid hjem mens settlerne aldrig plyndrede","Distinktionen er irrelevant fordi alle vikingetogter endte med permanent bosætning i de plyndrede områder","Vikingerne bosatte sig aldrig permanent uden for Skandinavien — de vendte altid hjem til Skandinavien efter plyndretogterne"],"correct":"De samme skandinaver der plyndrede et sted i én generation kunne bosætte sig fredeligt i en anden — raiding og bosætning var ikke to typer vikinger men aktiviteter betinget af muligheder: Danelaw og Normandiet var bosætninger Island et nybygningssamfund","accepted_answers":["De samme skandinaver der plyndrede et sted i én generation kunne bosætte sig fredeligt i en anden — raiding og bosætning var ikke to typer vikinger men aktiviteter betinget af muligheder: Danelaw og Normandiet var bosætninger Island et nybygningssamfund"],"review_text":"Danelaw i det nordøstlige England og Normandiet i Frankrig er eksempler på at skandinaver der i første generation plyndrede regionerne i næste generation bosatte sig, integrerede sig med lokalbefolkningerne, og til sidst adopterede lokal sprog og kultur. Island og Færøerne var modsat jomfrueligt land besat fredeligt uden forudgående plyndring. Vinland i Nordamerika var et bosættelsesforsøg der mislykkedes på grund af konflikter med lokalbefolkning. Billedet af vikingen som udelukkende plyndrer er en forenkling der overser den demografiske bevægelse og kulturelle integration der var en mindst ligeså stor del af vikingetidens historiske arv."}$v11q$::jsonb,
  'mc','short',$v11m${"concepts":["raiding","bosatning","Danelaw","Normandiet","Island","integration"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"challenge","domain":"vikings"}$v11m$::jsonb,
  'mc_single',3,'auto',true,'vikings',8,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v12q${"question":"Hvad er runestenenes historiske værdi som kilde til vikingetiden og hvad er deres vigtigste begrænsninger?","options":["Runestene er samtidige primærkilder der giver direkte information om sociale relationer og geografiske ruter — men de er fragmentariske, geografisk skævt fordelt, skrevet af og for eliten, og fortæller sjældent om årsager eller kontekst","Runestene er ubrugelige som historiske kilder fordi runeskrift kun brugt til magiske ritualer ikke faktuel kommunikation","Runestene er de eneste fuldstændig troværdige kilder til vikingetiden da de er samtidige og ikke filtreret gennem eftertidens fortolkning","Runestene er middelalderlige forfalskninger skabt af romantiske forfattere i 1800-tallet for at glorificere den nordiske fortid"],"correct":"Runestene er samtidige primærkilder der giver direkte information om sociale relationer og geografiske ruter — men de er fragmentariske, geografisk skævt fordelt, skrevet af og for eliten, og fortæller sjældent om årsager eller kontekst","accepted_answers":["Runestene er samtidige primærkilder der giver direkte information om sociale relationer og geografiske ruter — men de er fragmentariske, geografisk skævt fordelt, skrevet af og for eliten, og fortæller sjældent om årsager eller kontekst"],"review_text":"Over 3.000 runestene er fundet primært i Sverige, Danmark og Norge. De er enestående som samtidige skriftlige primærkilder — men deres indhold er begrænset. De fleste er mindestene rejst af familier for afdøde slægtninge og fortæller hvem der rejste stenen, hvem der er død, og undertiden hvor. Byzantium-stenene fra Sverige nævner mænd der døde i Grækland og bekræfter vikingernes østlige ruter. Men de er formuleret stereotypt, fortæller ikke om historiske begivenheder, motiver eller samfundsstrukturer, og er geografisk koncentreret i Sverige. Runestene er nyttige brikker — men de er ikke et komplet historisk vidnesbyrd."}$v12q$::jsonb,
  'mc','short',$v12m${"concepts":["runesten","primaeRkilde","kildekritik","elitekilde","geografisk skaevhed"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"vikings"}$v12m$::jsonb,
  'mc_single',3,'auto',true,'vikings',8,3
);

-- ─── BAND 4 (1 question — brings G8 B4 from 4 to 5) ──────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v13q${"question":"Hvordan bidrog vikingetiden til dannelsen af tidlige stater i Europa?","options":["Vikingernes bosætninger og konsolidering skabte direkte nye statsdannelser: normannerne stiftede hertugdømmet Normandiet og erobrede England i 1066 og Sicilien; svenske vikinger grundlagde Kievan Rus; og i Skandinavien skabte presset udefra en konsolidering til tre riger","Vikingerne forhindrede europæisk statsdannelse ved konstant at destabilisere eksisterende kongedømmer og lod aldrig stabile stater opstå","Vikingetiden bidrog ikke til europæisk statsdannelse da vikingerne altid trak sig tilbage til Skandinavien efter togterne","Den eneste statsformation vikingerne bidrog til var Rusland — i Vesteuropa ødelagde de udelukkende eksisterende strukturer"],"correct":"Vikingernes bosætninger og konsolidering skabte direkte nye statsdannelser: normannerne stiftede hertugdømmet Normandiet og erobrede England i 1066 og Sicilien; svenske vikinger grundlagde Kievan Rus; og i Skandinavien skabte presset udefra en konsolidering til tre riger","accepted_answers":["Vikingernes bosætninger og konsolidering skabte direkte nye statsdannelser: normannerne stiftede hertugdømmet Normandiet og erobrede England i 1066 og Sicilien; svenske vikinger grundlagde Kievan Rus; og i Skandinavien skabte presset udefra en konsolidering til tre riger"],"review_text":"Vikingetidens statsformende konsekvenser er markante. Normandiet: skandinaviske bosættere under Rollo fik hertugdømmet i 911 og deres efterkommer Vilhelm Erobreren ændrede Englands historie permanent i 1066. Normannerne erobrede siden Sicilien og grundlagde et multietnisk kongedømme i Middelhavet. Kievan Rus: svenske rus-vikinger oprettede de tidlige fyrstendømmer der lagde grunden til Rusland, Ukraine og Hviderusland. I Skandinavien selv skabte vikingetogternes organisering af krigere og ressourcer en centraliseringsproces der konsoliderede de tre kongedømmer Danmark, Norge og Sverige. Vold og statsdannelse er historisk tæt forbundne."}$v13q$::jsonb,
  'mc','short',$v13m${"concepts":["statsdannelse","Normandiet","Kievan Rus","normannerne","Danmark","centralmagT"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"analytical_challenge","domain":"vikings"}$v13m$::jsonb,
  'mc_single',4,'auto',true,'vikings',8,4
);

-- ─── BAND 5 (3 questions) ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v14q${"question":"I hvilken grad er det populære billede af vikingerne med hornede hjelme og ren barbari et historisk konstrueret myte?","options":["I høj grad: hornede hjelme er aldrig fundet fra vikingetiden og stammer fra romantikkens operaer; barbarbildedet er skabt af vikingernes ofres ensidige beretninger og 1800-tallets nationalromantik; arkæologien viser et samfund med kompleks handel, retsorden og kunst","Det populære billede er fuldstændig historisk korrekt og bekræftes ensartet af alle arkæologiske fund fra vikingetiden","Billedet er overdrevet men er et resultat af fejlfortolkninger i akademisk forskning fra 1900-tallet ikke af romantikken","Det er umuligt at vurdere det populære vikinge-billede da vi ikke har tilstrækkelige historiske kilder til perioden"],"correct":"I høj grad: hornede hjelme er aldrig fundet fra vikingetiden og stammer fra romantikkens operaer; barbarbildedet er skabt af vikingernes ofres ensidige beretninger og 1800-tallets nationalromantik; arkæologien viser et samfund med kompleks handel, retsorden og kunst","accepted_answers":["I høj grad: hornede hjelme er aldrig fundet fra vikingetiden og stammer fra romantikkens operaer; barbarbildedet er skabt af vikingernes ofres ensidige beretninger og 1800-tallets nationalromantik; arkæologien viser et samfund med kompleks handel, retsorden og kunst"],"review_text":"De hornede hjelme stammer fra Wagners Nibelung-operaer (1870erne) og romantiske illustratorer som Lorenz Frølich. Det eneste bevarede vikingehjelmfragment fra Gjermundbu er rundt uden horn. Barbarbildedet dominerer fordi de vigtigste skriftlige samtidskilder er skrevet af klostrene — vikingernes ofre — der naturligvis beskrev plyndringen ikke den daglige handel. 1800-tallets nationalromantik i Skandinavien, Tyskland og England genopfandt vikingerne som heroiske forfædre tilpasset nationalistiske behov. Arkæologien viser et anderledes billede: raffineret guldsmedekunst, velfungerende handelsbyer (Hedeby, Ribe), skriftlig retslig tradition, og internationale handelsnetværk. Myter om fortiden fortæller os mere om dem der skabte myterne end om fortiden selv."}$v14q$::jsonb,
  'mc','short',$v14m${"concepts":["hornede hjelme","myte","nationalromantik","kildekritik","arkaeologisk billede","historieskrivning"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"vikings"}$v14m$::jsonb,
  'mc_single',5,'auto',true,'vikings',8,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v15q${"question":"Hvad afslører vikingetidens kombination af vold og kulturel udveksling om drivkræfterne bag historisk forandring?","options":["At vold og kulturel udveksling ofte er to sider af den samme historiske dynamik — vikingerne terroriserede klostre og oprettede handelsnetværk, blandede kulturer og adopterede lokale skikke; forandring sker sjældent gennem ren konstruktion eller ren destruktion men i samspillet","At vold aldrig fører til kulturel udveksling da vold ødelægger de kulturer den rører ved fuldstændigt","At vikingernes kulturelle udveksling var fuldstændig adskilt fra deres vold med to specialiserede grupper: handelsvikinger og krigssvikinger","At vikingetidens kulturelle udveksling var rent ensidig: vikingerne adopterede fremmede kulturer men bidrog ikke selv med noget til de kulturer de mødte"],"correct":"At vold og kulturel udveksling ofte er to sider af den samme historiske dynamik — vikingerne terroriserede klostre og oprettede handelsnetværk, blandede kulturer og adopterede lokale skikke; forandring sker sjældent gennem ren konstruktion eller ren destruktion men i samspillet","accepted_answers":["At vold og kulturel udveksling ofte er to sider af den samme historiske dynamik — vikingerne terroriserede klostre og oprettede handelsnetværk, blandede kulturer og adopterede lokale skikke; forandring sker sjældent gennem ren konstruktion eller ren destruktion men i samspillet"],"review_text":"Vikingetiden er et historiografisk interessant tilfælde fordi den tvinger os til at holde to tanker i hovedet på én gang. De samme aktører (skandinaviske mænd fra samme samfund) plyndrede irske klostre, grundlagde Dublin som handelsby, og adopterede irsk keltisk kunst i skandinavisk metalarbejde. Normannerne plyndrede Frankrig, bosatte sig i Normandiet, og skabte en frankisk-skandinavisk ridderkrigerkulturs syntese. Rus-vikingerne trængte ind i slaviske samfund og skabte Kievan Rus med blandet slavisk-skandinavisk kultur. Historisk forandring er sjældent en ryddetabel — det er en kompleks proces af ødelæggelse, adoption, blanding og transformation. Det er ubehageligt men vigtigt at anerkende at vold kan være historisk produktiv."}$v15q$::jsonb,
  'mc','short',$v15m${"concepts":["vold og kulturudveksling","historisk forandring","hybridisering","Normandiet","Rus","kompleksitet"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"vikings"}$v15m$::jsonb,
  'mc_single',5,'auto',true,'vikings',8,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $v16q${"question":"Var vikingetiden primært en skandinavisk historie eller en europæisk og global historie — og hvad siger perspektivvalget om historieskrivningens natur?","options":["Begge perspektiver er legitime men belyser forskelligt: som skandinavisk historie handler den om statsdannelse og kristning; som europæisk og global handler den om handelsnetværk og kulturblanding fra Nordamerika til Centralasien; perspektivvalget bestemmer hvad der er centralt og hvad der er perifert","Vikingetiden var udelukkende en skandinavisk historie da dens konsekvenser for resten af verden var ubetydelige","Vikingetiden var udelukkende en europæisk historie — Skandinavien var kun udgangspunktet og ændrede sig ikke under perioden","Det er irrelevant om man vælger skandinavisk eller globalt perspektiv da begge perspektiver giver nøjagtigt det samme historiske billede"],"correct":"Begge perspektiver er legitime men belyser forskelligt: som skandinavisk historie handler den om statsdannelse og kristning; som europæisk og global handler den om handelsnetværk og kulturblanding fra Nordamerika til Centralasien; perspektivvalget bestemmer hvad der er centralt og hvad der er perifert","accepted_answers":["Begge perspektiver er legitime men belyser forskelligt: som skandinavisk historie handler den om statsdannelse og kristning; som europæisk og global handler den om handelsnetværk og kulturblanding fra Nordamerika til Centralasien; perspektivvalget bestemmer hvad der er centralt og hvad der er perifert"],"review_text":"Valget af perspektiv er ikke neutralt i historieskrivning — det skaber narrativet. Et skandinavisk perspektiv placerer Harald Blåtand, Jelling-monumenterne og kristningen centralt og fortæller historien om Skandinaviens integration i det europæiske civilisationsfællesskab. Et globalt perspektiv placerer handelsruterne centralt: Vinland i vest, Bagdad i øst, konstantinopolitansk guldsmedekunst i nordiske grave, arabiske mønter i svenske skatte. De to fortællinger er ikke i modstrid — de er komplementære billeder af den samme virkelighed set fra forskellige vinkler. Erkendelsen af at historieskrivning altid er perspektivbaseret er en af historiedisciplinens vigtigste metodiske indsigter: der er ikke én sand fortælling men mange valide men delvise fortællinger."}$v16q$::jsonb,
  'mc','short',$v16m${"concepts":["perspektivvalg","skandinavisk vs globalt","historieskrivning","narrativ","metodisk indsigt"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"vikings"}$v16m$::jsonb,
  'mc_single',5,'auto',true,'vikings',8,5
);
