-- Section 84 — World War 2 — Grade 8 (25 questions)
-- B1x6, B2x7, B3x7, B4x5. Domain: world_war_2.

-- ─── GRADE 8 · BAND 1 ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvordan kom Hitler til magten i Germany?","options":["Han blev demokratisk valgt som kansler i 1933 og udnyttede derefter en krise til at omdanne Germany til et diktatur","Han gennemfoerte et militaerkup og tog magten med magt","Han arvede magten fra den tidligere kansler","Han blev valgt af militaeret til at lede Germany"],"correct":"Han blev demokratisk valgt som kansler i 1933 og udnyttede derefter en krise til at omdanne Germany til et diktatur","accepted_answers":["Han blev demokratisk valgt som kansler i 1933 og udnyttede derefter en krise til at omdanne Germany til et diktatur"],"review_text":"Hitler kom til magten ad demokratisk vej i januar 1933 da han blev udnaevnt til kansler. Derefter brugte han Rigsdagsbranden til at faa undtagelsesbefoejelser og Enablingsloven til at goere sig til diktator. Det var en gradvis overtagelse ikke et pludseligt kup."}'::jsonb,
  'mc','short','{"concepts":["Hitler","magtovertagelse","demokratisk","kansler","diktatur"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_2"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_2',8,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var kernen i den nazistiske ideologi?","options":["Racistisk nationalisme der satte den ariske race over alle andre med antisemitisme som centralt element","Et okonomisk system baseret paa fri handel og kapitalisme","En demokratisk bevaegelse der ville give folket mere indflydelse","En religioes bevaegelse baseret paa protestantisk kristendom"],"correct":"Racistisk nationalisme der satte den ariske race over alle andre med antisemitisme som centralt element","accepted_answers":["Racistisk nationalisme der satte den ariske race over alle andre med antisemitisme som centralt element"],"review_text":"Nazismen byggede paa racetenkning. Den ariske race sattes over alle andre. Joder, sigojnere og handicappede blev betragtet som mindrevaerdige. Antisemitisme var ikke en sidebemaekning men kernelementet i ideologien."}'::jsonb,
  'mc','short','{"concepts":["nazisme","raceideologi","antisemitisme","arisk","ideologi"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_2"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_2',8,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvornaar og med hvad startede Anden Verdenskrig i Europa?","options":["1. september 1939 da Germany invaderede Polen og England og Frankrig erklaerede Germany krig","1. september 1938 da Germany annekterede Oestrig","7. december 1941 da Japan angreb Pearl Harbor","10. maj 1940 da Germany invaderede Frankrig"],"correct":"1. september 1939 da Germany invaderede Polen og England og Frankrig erklaerede Germany krig","accepted_answers":["1. september 1939 da Germany invaderede Polen og England og Frankrig erklaerede Germany krig"],"review_text":"Den 1. september 1939 invaderede Germany Polen. To dage senere erklaerede England og Frankrig Germany krig. Det var den officielle start paa Anden Verdenskrig i Europa."}'::jsonb,
  'mc','short','{"concepts":["krigens udbrud","Polen","1939","England","Frankrig"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_2"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_2',8,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvornaar besatte Germany Danmark og hvad skete der?","options":["9. april 1940 invaderede Germany Danmark og den danske regering valgte at samarbeje for at beskytte befolkningen","9. april 1940 invaderede Germany Danmark og den danske haer kaeampede i to uger","1. maj 1941 invaderede Germany Danmark som reaktion paa dansk modstand","Danmark var aldrig besat af Germany under Anden Verdenskrig"],"correct":"9. april 1940 invaderede Germany Danmark og den danske regering valgte at samarbeje for at beskytte befolkningen","accepted_answers":["9. april 1940 invaderede Germany Danmark og den danske regering valgte at samarbeje for at beskytte befolkningen"],"review_text":"Den 9. april 1940 invaderede Germany Danmark. Den danske haer kaeampede kun i faa timer. Regeringen kapitulerede for at undgaa blodbad og beholde mest mulig selvstyreret. Det var starten paa et kompliceret besaettelsesforhold."}'::jsonb,
  'mc','short','{"concepts":["dansk besaettelse","9. april 1940","samarbejdspolitik","kapitulation"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_2"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_2',8,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var Holocaust?","options":["Det systematiske folkedrab paa ca. 6 millioner joder og millioner af andre grupper gennemfoert af Nazi-Germany","Et massedrab paa franske civile under den tyske besaettelse","En serie koncentrationslejre i Rusland under Stalins styre","Betegnelse for de allieredes bombardementer af tyske byer"],"correct":"Det systematiske folkedrab paa ca. 6 millioner joder og millioner af andre grupper gennemfoert af Nazi-Germany","accepted_answers":["Det systematiske folkedrab paa ca. 6 millioner joder og millioner af andre grupper gennemfoert af Nazi-Germany"],"review_text":"Holocaust var den planlagte og systematiske udrottelse af Europas joder. Ca. 6 millioner joder wurde myrdede. Dertil kom sigojnere, handicappede, homoseksuelle og politiske modstandere. Det er den storste planlagte massedrab i historien."}'::jsonb,
  'mc','short','{"concepts":["Holocaust","folkedrab","joder","systematisk","Nazi-Germany"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_2"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_2',8,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad endte Anden Verdenskrig i Europa?","options":["Germanys ubetingede kapitulation den 8. maj 1945 da de allierede had besat det meste af Germany","En fredsaftale forhandlet af alle parter i Geneve i april 1945","Hitlers aftale om vaabenstilstand i marts 1945","Den sovjetiske overtagelse af alle europaeiske lande i 1945"],"correct":"Germanys ubetingede kapitulation den 8. maj 1945 da de allierede had besat det meste af Germany","accepted_answers":["Germanys ubetingede kapitulation den 8. maj 1945 da de allierede had besat det meste af Germany"],"review_text":"Den 8. maj 1945 kapitulerede Germany ubetinget. Det er fejret som Victory in Europe Day. I Asien fortsatte krigen mod Japan indtil den japanske kapitulation i august 1945 efter atombomberne over Hiroshima og Nagasaki."}'::jsonb,
  'mc','short','{"concepts":["krigens afslutning","8. maj 1945","kapitulation","V-E Day"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_2"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_2',8,1
);

-- ─── GRADE 8 · BAND 2 ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var forbindelsen mellem Versailles-traktaten og Hitlers opkomst?","options":["Versailles ydmygede Germany og kraevede enorme erstatninger som skabte okonomisk nod og national vrede som Hitler udnyttede","Versailles gav Hitler direkte magt som kansler","Versailles forbod nazistpartiet som reaktion styrkede det","Der er ingen forbindels de to begivenheder var uafhaengige"],"correct":"Versailles ydmygede Germany og kraevede enorme erstatninger som skabte okonomisk nod og national vrede som Hitler udnyttede","accepted_answers":["Versailles ydmygede Germany og kraevede enorme erstatninger som skabte okonomisk nod og national vrede som Hitler udnyttede"],"review_text":"Versailles paaloede Germany enorme gaeldsbyrder og eneansvar for krigen. Den Store Depression forstaearkede den okonomiske nod. Hitler lovede at gengaelde ydmygelsen og hive Germany ud af krisen. Versailles saaede froe som Hitler hoestede."}'::jsonb,
  'mc','short','{"concepts":["Versailles","Hitler","okonomisk nod","national vrede","WWI-WWII"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_2"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_2',8,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var Den Store Depressions rolle i Hitlers vej til magten?","options":["Den massive arbejdsloeshed og okonomiske desperation fik millioner til at soege radikale loesninger og NSDAP voksede eksplosivt","Den Store Depression kom efter Hitler kom til magten","Den Store Depression paavirket kun USA og had intet at goere med Germany","Depressionen styrkede de demokratiske partier fordi folk ville have stabilitet"],"correct":"Den massive arbejdsloeshed og okonomiske desperation fik millioner til at soege radikale loesninger og NSDAP voksede eksplosivt","accepted_answers":["Den massive arbejdsloeshed og okonomiske desperation fik millioner til at soege radikale loesninger og NSDAP voksede eksplosivt"],"review_text":"I 1928 fik NSDAP 2,6% af stemmerne. I 1932 fik de 37%. Den Store Depression skete i mellemtiden. Desperation naerer ekstremisme. Naar folk mister job, opsparing og haab soeger mange radikale svar."}'::jsonb,
  'mc','short','{"concepts":["Store Depression","NSDAP","arbejdsloeshed","radikalisering","valgresultater"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_2"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_2',8,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var de konkrete teknikker i Nazi-propagandaen?","options":["Gentagelse af simple budskaber, fjendebilleder af joder og kommunister, kontrol med alle medier og massemobilisering via fester og symboler","Objektiv og faktabaseret kommunikation om Germanys udfordringer","Propaganda der kun appellerede til veluddannede borgere","Propaganda naesten udelukkende via aviser"],"correct":"Gentagelse af simple budskaber, fjendebilleder af joder og kommunister, kontrol med alle medier og massemobilisering via fester og symboler","accepted_answers":["Gentagelse af simple budskaber, fjendebilleder af joder og kommunister, kontrol med alle medier og massemobilisering via fester og symboler"],"review_text":"Goebbels vidste at simple gentagne budskaber virker bedre end komplekse argumenter. Joderne og kommunisterne var fjenderne. Radio, film og aviser var statslige. Nurnberg-rallies skabte en religioes stemning om Hitler. Propaganda var systematisk og altgennemtraengende."}'::jsonb,
  'mc','short','{"concepts":["propaganda","Goebbels","medier","fjendebilleder","massemobilisering"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_2"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_2',8,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betod samarbejdspolitikken for Danmark under besaettelsen?","options":["Den danske regering samarbejdede med besaettelsesmagten for at bevare selvstyreret og beskytte befolkningen under vanskelige moralske kompromiser","Danmark samarbejdede fuldt ud med Germany og stoettede nazi-politikken aktivt","Danmark nagtede al samarbeje og kaeampede aktiv modstand fra dag eet","Samarbejdspolitikken betod at danske joder blev deporterede med regeringens samtykke"],"correct":"Den danske regering samarbejdede med besaettelsesmagten for at bevare selvstyreret og beskytte befolkningen under vanskelige moralske kompromiser","accepted_answers":["Den danske regering samarbejdede med besaettelsesmagten for at bevare selvstyreret og beskytte befolkningen under vanskelige moralske kompromiser"],"review_text":"Samarbejdspolitikken betod at Danmark beholdt sin regering og grundlov fra 1940 til august 1943. Det beskyttede den danske befolkning relativt godt. Men det var ogsaa en kilde til dyb moralsk konflikt: hvornaar er pragmatisk samarbeje lig med aktiv kompromisering?"}'::jsonb,
  'mc','short','{"concepts":["samarbejdspolitik","dansk besaettelse","selvstyreret","moralsk konflikt"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_2"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_2',8,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad forklarer at nogle mennesker valgte at samarbeje med besaettelsesmagten?","options":["Kombination af frygt, okonomisk interesse, pragmatisme og i nogle tilfaelde ideologisk sympati med nazismen","Alle der samarbejdede var nazister der ideologisk stoettede Germany","Samarbeje var det moralsk rigtige da man ikke kunne goere noget","Ingen samarbejdede frivilligt alle var tvungne"],"correct":"Kombination af frygt, okonomisk interesse, pragmatisme og i nogle tilfaelde ideologisk sympati med nazismen","accepted_answers":["Kombination af frygt, okonomisk interesse, pragmatisme og i nogle tilfaelde ideologisk sympati med nazismen"],"review_text":"Kollaboration var ikke sort-hvid. Nogen samarbejdede af frygt for at miste job eller liv. Nogen saa okonomisk gevinst. Nogen troede det var den bedste maade at beskytte lokalsamfundet. Og nogen delte faktisk nazistiske synspunkter. Motiverne var mange og komplekse."}'::jsonb,
  'mc','short','{"concepts":["kollaboration","frygt","pragmatisme","ideologi","kompleksitet"],"misconception_type":"overgeneralization","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_2"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_2',8,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var den danske modstandsbevaeaegelse?","options":["Civile og militaere netvaerk der saboterede tyske anlaeg, hjalp joder med at flygte til Sverige og fremstillede illegale aviser","Den danske haer der kaeampede Germany i hele besaettelsestiden","En gruppe politikere der nagtede at deltage i Folketiget under besaettelsen","En bevaeaegelse der kun eksisterede i Kobenhavn"],"correct":"Civile og militaere netvaerk der saboterede tyske anlaeg, hjalp joder med at flygte til Sverige og fremstillede illegale aviser","accepted_answers":["Civile og militaere netvaerk der saboterede tyske anlaeg, hjalp joder med at flygte til Sverige og fremstillede illegale aviser"],"review_text":"Modstandsbevaeaegelsen voksede gradvist. Fra illegale aviser til sabotage af jernbaner og fabrikker. Den storste bedrift var i oktober 1943 da modstandsfolk og fiskere hjalp naesten alle danske joder over til Sverige og reddede ca. 7000 liv."}'::jsonb,
  'mc','short','{"concepts":["modstand","sabotage","joderedning","illegale aviser","Danmark"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_2"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_2',8,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvordan oplevede civile Anden Verdenskrig i besatte lande?","options":["Via rationering, frygt for arrestation, sorg over tabte familiemedlemmer og daglige valg om samarbeje eller modstand","Civile i besatte lande var fuldstaendigt beskyttede og maerkede ikke krigen direkte","Kun civile naer frontlinjen oplevede krigen resten levede normalt","Civile profiterede okonomisk fordi de solgte varer til besaettelsesmagten"],"correct":"Via rationering, frygt for arrestation, sorg over tabte familiemedlemmer og daglige valg om samarbeje eller modstand","accepted_answers":["Via rationering, frygt for arrestation, sorg over tabte familiemedlemmer og daglige valg om samarbeje eller modstand"],"review_text":"For civile i besatte lande var krigen allestedsnærværende. Rationering betod madmangel. Gestapo og angiveri skabte konstant frygt. Mange familier mistede slaegtinge til krigen eller deportation. Den daglige moralske kalkule var vanskelig."}'::jsonb,
  'mc','short','{"concepts":["civile","hverdagsliv","rationering","frygt","besaettelse"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"perspective_shift","challenge_role":"reinforcement","domain":"world_war_2"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_2',8,2
);

-- ─── GRADE 8 · BAND 3 ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved forestillingen om at demokratier aldrig kan bryde samman?","options":["Weimar-republikken var et demokrati der broed samman under okonomisk krise og systematisk underminering og viser at demokrati kraever aktiv opbakning for at overleve","Forestillingen er korrekt ingen demokratier er nogensinde kollapset","Kun fattige lande kan faa demokratiet til at bryde samman","Demokratiet kollapsede i Germany fordi Germany aldrig var et rigtigt demokrati"],"correct":"Weimar-republikken var et demokrati der broed samman under okonomisk krise og systematisk underminering og viser at demokrati kraever aktiv opbakning for at overleve","accepted_answers":["Weimar-republikken var et demokrati der broed samman under okonomisk krise og systematisk underminering og viser at demokrati kraever aktiv opbakning for at overleve"],"review_text":"Weimar-republikken fra 1919-1933 var en demokratisk forfatning. Germany had frie valg. Men under okonomisk krise og Hitlers systematiske underminering broed demokratiet samman. Det viser at demokratiet aldrig er urokkeligt."}'::jsonb,
  'mc','short','{"concepts":["demokrati","sammenbrud","Weimar","okonomisk krise","misconception-demokrati-urokkeligt"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_2',8,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved forestillingen om at Hitlers magtovertagelse skete pludseligt?","options":["Hitlers vej til magten var en gradvis proces over aaervis der involverede valgkampe, koalitionsforhandlinger og bevidst underminering af demokratiet","Forestillingen er korrekt Hitler tog magten i et pludseligt kup","Det er forkert fordi Hitler aldrig fik demokratisk valgt magt","Det er forkert fordi processen kun tog to maaneder"],"correct":"Hitlers vej til magten var en gradvis proces over aaervis der involverede valgkampe, koalitionsforhandlinger og bevidst underminering af demokratiet","accepted_answers":["Hitlers vej til magten var en gradvis proces over aaervis der involverede valgkampe, koalitionsforhandlinger og bevidst underminering af demokratiet"],"review_text":"Hitler kaeampede ved adskillige demokratiske valg. NSDAP voksede fra marginalparti til stoerste parti. Hitler blev demokratisk udnaevnt til kansler. Derefter underminerede han stap for stap demokratiets institutioner. Det tog aar ikke dage."}'::jsonb,
  'mc','short','{"concepts":["Hitler","gradvis proces","valgkamp","demokratisk underminering","misconception-pludselig"],"misconception_type":"temporal_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_2',8,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved forestillingen om at Nazi-propaganda kun virkede paa ukritiske og uintelligente mennesker?","options":["Propaganda virker paa alle under de rette betingelser og mange veluddannede og intelligente tyskere troede paa og stoettede nazismens budskaber","Forestillingen er korrekt kun ueducerede folk faldt for propagandaen","Det er forkert fordi ingen faktisk troede paa propagandaen de var bare bange","Det er forkert fordi Goebbels propaganda var for primitiv til at virke"],"correct":"Propaganda virker paa alle under de rette betingelser og mange veluddannede og intelligente tyskere troede paa og stoettede nazismens budskaber","accepted_answers":["Propaganda virker paa alle under de rette betingelser og mange veluddannede og intelligente tyskere troede paa og stoettede nazismens budskaber"],"review_text":"Professorer, laeger, jurister og ingeniorer var med i NSDAP. Propaganda virker paa alle under de rette betingelser: okonomisk krise, national ydmygelse og angst. At tro man selv er immun mod propaganda er den stoerste fare."}'::jsonb,
  'mc','short','{"concepts":["propaganda","intelligens","NSDAP","betingelser","misconception-propaganda-kun-dumme"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_2',8,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved forestillingen om at Holocaust skete pludseligt?","options":["Holocaust eskalerede gradvist over aar fra diskrimination og Nuremberg-lovene til gettoisering og endelig industrialiseret massedrab fra 1941","Forestillingen er korrekt Holocaust startede med massedrab fra begyndelsen af Hitler-styret","Det er forkert fordi Holocaust var planlagt fra 1933 i alle detaljer","Det er forkert fordi Holocaust kun vaerede i faa maaneder"],"correct":"Holocaust eskalerede gradvist over aar fra diskrimination og Nuremberg-lovene til gettoisering og endelig industrialiseret massedrab fra 1941","accepted_answers":["Holocaust eskalerede gradvist over aar fra diskrimination og Nuremberg-lovene til gettoisering og endelig industrialiseret massedrab fra 1941"],"review_text":"1933: bojkot. 1935: Nuremberg-love fratog joder rettigheder. 1938: Kristallnacht. 1941: Wannsee-konferencen og Endlosung. Det var en trappetraedning. Hvert trin normaliserede det naeste og fjernede en sparebrems mod det foelgende."}'::jsonb,
  'mc','short','{"concepts":["Holocaust","eskalation","Nuremberg","Wannsee","misconception-pludselig"],"misconception_type":"temporal_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_2',8,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var de storste konsekvenser af Anden Verdenskrig for Europa?","options":["Ca. 60 millioner dode, Europas byer i ruiner, opdeling i Vest og Ost og grundlaeggende af FN og den europaeiske samarbejedsstruktur","Krigen endte hurtigt og konsekvenserne for Europa var begransede","Europe kom styrkede ud af krigen alene takket vaere USA","Den eneste konsekvens var Germanys deling og Berlinmuren"],"correct":"Ca. 60 millioner dode, Europas byer i ruiner, opdeling i Vest og Ost og grundlaeggende af FN og den europaeiske samarbejedsstruktur","accepted_answers":["Ca. 60 millioner dode, Europas byer i ruiner, opdeling i Vest og Ost og grundlaeggende af FN og den europaeiske samarbejedsstruktur"],"review_text":"Anden Verdenskrig kostede ca. 60 millioner liv. Hele byer var bombet til grunde. Millioner var fordrevet. Den Kolde Krig opdelede Europa i to lejre. Men krigen foerte ogsaa til FN, NATO og fundamentet for det europaeiske samarbeje."}'::jsonb,
  'mc','short','{"concepts":["krigens konsekvenser","tab","FN","Kolde Krig","europaeisk samarbeje"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_2',8,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er forkert ved forestillingen om at modstand mod besaettelsen var en nem og heroisk handling?","options":["Modstand betod at risikere sit og sin families liv og Gestapos brutale metoder betod at mange modstandsfolk endte i koncentrationslejre eller med doedsdom","Forestillingen er korrekt modstand var nem og heroisk for alle der proevede","Det er forkert fordi besaettelsesmagten tolererede beskeden modstand","Det er forkert fordi modstand kun var farlig i Osteuropa"],"correct":"Modstand betod at risikere sit og sin families liv og Gestapos brutale metoder betod at mange modstandsfolk endte i koncentrationslejre eller med doedsdom","accepted_answers":["Modstand betod at risikere sit og sin families liv og Gestapos brutale metoder betod at mange modstandsfolk endte i koncentrationslejre eller med doedsdom"],"review_text":"I Danmark modte modstandsfolk Gestapo, angiveri og deportation. Mange endte i tyske koncentrationslejre. Adskillige danskere blev henrettet. Modstand var ikke et heroisk eventyr men en hverdagsbeslutning med livsfarlige konsekvenser."}'::jsonb,
  'mc','short','{"concepts":["modstand","fare","Gestapo","koncentrationslejre","misconception-modstand-nem"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_2',8,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad var forbindelsen mellem Anden Verdenskrig og den Kolde Krig?","options":["Sejrherrernes uenighed om Europas fremtid og Sovjets ekspansion i Osteuropa skaabte direkte den bipolare verdensorden der definerede den Kolde Krig","Der var ingen forbindels de to begivenheder var fuldstaendigt uafhaengige","Den Kolde Krig startede fordi USA og Sovjet besluttede at dele verden","Den Kolde Krig var en konsekvens af Versailles-traktaten"],"correct":"Sejrherrernes uenighed om Europas fremtid og Sovjets ekspansion i Osteuropa skaabte direkte den bipolare verdensorden der definerede den Kolde Krig","accepted_answers":["Sejrherrernes uenighed om Europas fremtid og Sovjets ekspansion i Osteuropa skaabte direkte den bipolare verdensorden der definerede den Kolde Krig"],"review_text":"Under Anden Verdenskrig samarbejede USA og Sovjet mod Germany. Men allerede i slutfasen byggede begge sider mistillid op. Sovjet onsekede sikkerhedsstaater i Osteuropa. USA ville stoppe kommunismens spredning. Det var kilden til den Kolde Krig."}'::jsonb,
  'mc','short','{"concepts":["Kolde Krig","Sovjet","USA","Osteuropa","WWII-forbindels"],"misconception_type":"temporal_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_2',8,3
);

-- ─── GRADE 8 · BAND 4 ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad viser det at danskere under besaettelsen traf vidt forskellige valg om samarbeje og modstand?","options":["At moralske valg under ekstreme betingelser afhaenger af mange faktorer og at det er svaeert at doeme folk der levede under frygt og tvang","At alle der samarbejdede var moralsk ansvarlige og fortjente straf","At alle der ikke aktivt modstod var kujonere","At moralske valg er simple enten stoetter man frihed eller fascisme"],"correct":"At moralske valg under ekstreme betingelser afhaenger af mange faktorer og at det er svaeert at doeme folk der levede under frygt og tvang","accepted_answers":["At moralske valg under ekstreme betingelser afhaenger af mange faktorer og at det er svaeert at doeme folk der levede under frygt og tvang"],"review_text":"Under besaettelsen var der ingen enkle valg. Var det samarbeje at saelge groentsager til tyske soldater? At fortsaette sit arbejde? Linjen mellem at overleve og at svigte var ikke klar. At forstaa fortiden kraever at man forsoeger at se det fra de menneskers perspektiv."}'::jsonb,
  'mc','short','{"concepts":["moralske valg","besaettelse","kompleksitet","perspektiv","doem"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_2',8,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad forklarer at millioner af ordinaere tyskere stoettede og deltog i nazistyret?","options":["Kombination af okonomisk fortvivlelse, national ydmygelse, propaganda der skabte en samlende fjende og gradvis normalisering af det ekstraordinaere","Alle tyskere var medfodte antisemitter og nazister","De fleste tysker var bange og ingen stoettede Hitler frivilligt","Kun de lavest uddannede tyskere stoettede Hitler"],"correct":"Kombination af okonomisk fortvivlelse, national ydmygelse, propaganda der skabte en samlende fjende og gradvis normalisering af det ekstraordinaere","accepted_answers":["Kombination af okonomisk fortvivlelse, national ydmygelse, propaganda der skabte en samlende fjende og gradvis normalisering af det ekstraordinaere"],"review_text":"Den menneskelige evne til at deltage i ondskab under de rette betingelser er et af Anden Verdenskrigs mest ubehagelige laerdommer. Okonomisk desperation, propaganda og social pres normaliserede gradvist det ekstraordinaere. Ingen nation er immune."}'::jsonb,
  'mc','short','{"concepts":["ordinaere tyskere","normalisering","propaganda","forklaring","menneskelig natur"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_2',8,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er borgers ansvar naer et demokrati begynder at erodere?","options":["At handle tidligt naar tegn paa autokrati opstaar fordi det er svaerere at modstaa et fuldt etableret diktatur end et fremspirende eet","At afvente officielle myndigheders dom om situationen","At forlade landet og vente paa at situationen loser sig","At fokusere paa sit eget liv og lade politikere loese politiske problemer"],"correct":"At handle tidligt naar tegn paa autokrati opstaar fordi det er svaerere at modstaa et fuldt etableret diktatur end et fremspirende eet","accepted_answers":["At handle tidligt naar tegn paa autokrati opstaar fordi det er svaerere at modstaa et fuldt etableret diktatur end et fremspirende eet"],"review_text":"Historien viser at diktaturer sjaeldent opstaar fuldformt. De vokser gradvist. Hvert lille trin normaliserer det naeste. Borgernes modstand er vigtigst i de tidlige faser. Naar kontrollen er total er individuel modstand ekstremt farlig."}'::jsonb,
  'mc','short','{"concepts":["demokratisk ansvar","borgere","tidlig modstand","erosion","diktaturer"],"misconception_type":"temporal_confusion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_2',8,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Var befrielsen i 1945 en entydig glaede for alle i Europa?","options":["Nej: millioner var fordrevne og hjemloese, Holocaust-overlevende bar uudslettelige traumer og Osteuropa skiftede fra tysk til sovjetisk besaettelse","Ja befrielsen betod at krig og undertrykkelse sluttede for alle i Europa","Befrielsen gjaldt kun for vesteuropaes befolkninger","Ja men det tog kun faa maaneder at genoprette fuld normalitet"],"correct":"Nej: millioner var fordrevne og hjemloese, Holocaust-overlevende bar uudslettelige traumer og Osteuropa skiftede fra tysk til sovjetisk besaettelse","accepted_answers":["Nej: millioner var fordrevne og hjemloese, Holocaust-overlevende bar uudslettelige traumer og Osteuropa skiftede fra tysk til sovjetisk besaettelse"],"review_text":"Befrielsen i Vest betod frihed fra nazistisk besaettelse. Men for Holocaust-overlevende var det en retur til et Europa der had myrdet deres familier. For Osteuropa betod det Soviet-satellitstatus. For millioner af flygtninge betod det aarers usikkerhed."}'::jsonb,
  'mc','short','{"concepts":["befrielse","kompleksitet","Holocaust-overlevende","Osteuropa","Sovjet"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_2',8,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er Anden Verdenskrigs vigtigste lektie til nutidens demokratier?","options":["At demokratier er skroebelige og kraever aktiv borgermessig beskyttelse og at propaganda, okonomisk krise og fjendebilleder er de klassiske vaaben mod dem","At militaer styrke alene kan beskytte demokratier mod trusler","At demokratiet er den naturlige og uundgaaelige styreform som ingen trussel kan vaelte","At kun diktaturer kan haandtere store kriser effektivt"],"correct":"At demokratier er skroebelige og kraever aktiv borgermessig beskyttelse og at propaganda, okonomisk krise og fjendebilleder er de klassiske vaaben mod dem","accepted_answers":["At demokratier er skroebelige og kraever aktiv borgermessig beskyttelse og at propaganda, okonomisk krise og fjendebilleder er de klassiske vaaben mod dem"],"review_text":"Weimar-demokratiets sammenbrud er advarslen. Demokratiet beskytter sig ikke selv. Det kraever borgere der vaerner om det, institutioner der modstaer pres og en kultur der afviser fjendebilleder og scapegoating. Det er altid relevant."}'::jsonb,
  'mc','short','{"concepts":["demokratiets lektie","skroebelig","borgeres ansvar","fjendebilleder","WWII-relevans-idag"],"misconception_type":"temporal_confusion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_2',8,4
);;
