-- Engelsk batch 2, 3. klasse bånd 3-4: 166 nye MC-spørgsmål (learning_objective='english', bånd 1-4).
-- Del af 1000 nye engelskspørgsmål til 3.-5. klasse. Samme indholds- og metadata-mønster som
-- 20261001000000_english_grade3_5; metadata afledes her af kategorinøglen k:
-- o=ordforråd, h=hverdagsudtryk, g=grammatik, l=læseforståelse. difficulty = bånd.
-- Bånd 1-2: reinforcement/conceptual_bridge. Bånd 3-4: challenge/reframing. All is_active=true.
-- Må KUN anvendes via apply_migration med særskilt ejer-autorisation (D-110).

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band)
SELECT
  jsonb_build_object('question', e->>'q', 'options', e->'o', 'correct', e->>'a',
                     'accepted_answers', jsonb_build_array(e->>'a'), 'review_text', e->>'r'),
  'mc', 'short',
  jsonb_build_object('concepts', jsonb_build_array(m.concept), 'cognitive_skill', m.skill,
                     'difficulty_type', m.dtype, 'misconception_type', m.mis,
                     'challenge_role', CASE WHEN (e->>'b')::int >= 3 THEN 'challenge' ELSE 'reinforcement' END,
                     'insight_type', CASE WHEN (e->>'b')::int >= 3 THEN 'reframing' ELSE 'conceptual_bridge' END,
                     'domain', 'english'),
  'mc_single', (e->>'b')::int, 'auto', true, 'english', (e->>'g')::int, (e->>'b')::int
FROM jsonb_array_elements($$[
{"g":3,"b":3,"k":"o","q":"Hvilket ord passer IKKE ind? cat – dog – horse – chair","o":["cat","dog","chair","horse"],"a":"chair","r":"Cat, dog og horse er dyr. 'Chair' er en stol, så den passer ikke ind."},
{"g":3,"b":3,"k":"o","q":"Hvilket ord passer IKKE ind? one – six – blue – ten","o":["one","blue","six","ten"],"a":"blue","r":"One, six og ten er tal. 'Blue' er en farve."},
{"g":3,"b":3,"k":"o","q":"Hvilket ord passer IKKE ind? mum – dad – sister – table","o":["table","mum","dad","sister"],"a":"table","r":"Mum, dad og sister er familie. 'Table' er et bord."},
{"g":3,"b":3,"k":"o","q":"Hvilket ord passer IKKE ind? milk – juice – water – shoe","o":["milk","juice","water","shoe"],"a":"shoe","r":"Milk, juice og water kan man drikke. En sko (shoe) kan man ikke drikke!"},
{"g":3,"b":3,"k":"o","q":"Hvilket ord passer IKKE ind? head – arm – leg – bread","o":["head","arm","bread","leg"],"a":"bread","r":"Head, arm og leg er kropsdele. 'Bread' er brød."},
{"g":3,"b":3,"k":"o","q":"Hvilket ord passer IKKE ind? Monday – Friday – Sunday – summer","o":["Monday","summer","Friday","Sunday"],"a":"summer","r":"Monday, Friday og Sunday er ugedage. 'Summer' er en årstid."},
{"g":3,"b":3,"k":"o","q":"Hvad er det modsatte af 'big'?","o":["small","tall","long","fat"],"a":"small","r":"Det modsatte af 'big' (stor) er 'small' (lille)."},
{"g":3,"b":3,"k":"o","q":"Hvad er det modsatte af 'happy'?","o":["funny","nice","good","sad"],"a":"sad","r":"Det modsatte af 'happy' (glad) er 'sad' (ked af det)."},
{"g":3,"b":3,"k":"o","q":"Hvad er det modsatte af 'old' (om en ting)?","o":["young","small","new","good"],"a":"new","r":"En gammel ting er 'old', en ny ting er 'new'. Om mennesker er det modsatte 'young'."},
{"g":3,"b":3,"k":"o","q":"Hvad er det modsatte af 'fast'?","o":["quick","slow","short","low"],"a":"slow","r":"Det modsatte af 'fast' (hurtig) er 'slow' (langsom)."},
{"g":3,"b":3,"k":"o","q":"Hvad er det modsatte af 'up'?","o":["down","out","on","off"],"a":"down","r":"'Up' betyder op, og 'down' betyder ned."},
{"g":3,"b":3,"k":"o","q":"Hvad er det modsatte af 'yes'?","o":["not","now","new","no"],"a":"no","r":"'Yes' betyder ja, og 'no' betyder nej."},
{"g":3,"b":3,"k":"o","q":"Hvad er det modsatte af 'day'?","o":["morning","week","night","sun"],"a":"night","r":"'Day' er dag, og 'night' er nat."},
{"g":3,"b":3,"k":"o","q":"Hvad er det modsatte af 'open'?","o":["over","closed","empty","out"],"a":"closed","r":"'Open' betyder åben, og 'closed' betyder lukket."},
{"g":3,"b":3,"k":"o","q":"Hvad hedder 'sommer' på engelsk?","o":["summer","sun","Sunday","spring"],"a":"summer","r":"Sommer = summer. 'Spring' er forår."},
{"g":3,"b":3,"k":"o","q":"Hvad betyder 'spring' som årstid?","o":["sommer","efterår","vinter","forår"],"a":"forår","r":"Årstiden 'spring' er forår. Ordet kan også betyde at springe."},
{"g":3,"b":3,"k":"o","q":"Hvad hedder 'marts' på engelsk?","o":["May","Monday","March","month"],"a":"March","r":"Marts = March. 'Month' betyder måned."},
{"g":3,"b":3,"k":"o","q":"Hvad betyder 'December'?","o":["november","december","oktober","januar"],"a":"december","r":"'December' er december — årets sidste måned."},
{"g":3,"b":3,"k":"o","q":"Hvilken måned kommer efter 'June'?","o":["July","May","August","January"],"a":"July","r":"June = juni og July = juli. Pas på — de ligner hinanden!"},
{"g":3,"b":3,"k":"o","q":"Hvad betyder 'week'?","o":["vej","weekend","vinge","uge"],"a":"uge","r":"'Week' betyder uge. En uge har syv dage (seven days)."},
{"g":3,"b":3,"k":"o","q":"Hvad betyder 'today'?","o":["i morgen","i går","i dag","i aften"],"a":"i dag","r":"'Today' betyder i dag. I morgen = tomorrow, i går = yesterday."},
{"g":3,"b":3,"k":"o","q":"Hvad betyder 'sunny'?","o":["blæsende","solrigt","regnfuldt","tåget"],"a":"solrigt","r":"'Sunny' kommer af 'sun' (sol). Blæsende = windy."},
{"g":3,"b":3,"k":"o","q":"Hvad betyder 'windy'?","o":["blæsende","vinter","regnfuldt","vindue"],"a":"blæsende","r":"'Windy' kommer af 'wind' (vind) og betyder blæsende."},
{"g":3,"b":3,"k":"o","q":"Hvad betyder 'cloud'?","o":["klo","klokke","kulde","sky"],"a":"sky","r":"'Cloud' betyder en sky. 'Cloudy' betyder overskyet."},
{"g":3,"b":3,"k":"o","q":"Hvad betyder 'evening'?","o":["morgen","middag","aften","nat"],"a":"aften","r":"'Evening' betyder aften. 'Good evening' = god aften."},
{"g":3,"b":3,"k":"o","q":"Hvad hedder 'lærer' og 'elev' på engelsk?","o":["teacher og parent","teacher og pupil","doctor og pupil","teacher og player"],"a":"teacher og pupil","r":"Lærer = teacher, elev = pupil eller student."},
{"g":3,"b":3,"k":"o","q":"Hvad betyder 'classroom'?","o":["klasseværelse","skolegård","gymnastiksal","bibliotek"],"a":"klasseværelse","r":"'Class' + 'room' = klasse + værelse = klasseværelse."},
{"g":3,"b":3,"k":"o","q":"Hvad betyder 'rubber' (eller 'eraser') i skolen?","o":["lineal","saks","lim","viskelæder"],"a":"viskelæder","r":"Et viskelæder hedder 'rubber' i England og 'eraser' i USA."},
{"g":3,"b":3,"k":"o","q":"Hvad hedder 'saks' på engelsk?","o":["sizes","sisters","scissors","scarf"],"a":"scissors","r":"Saks = scissors. Ordet er altid i flertal på engelsk."},
{"g":3,"b":3,"k":"o","q":"Hvad betyder 'shark'?","o":["hval","haj","skarv","skildpadde"],"a":"haj","r":"'Shark' betyder haj. Hval hedder 'whale'."},
{"g":3,"b":3,"k":"o","q":"Hvad betyder 'tiger'?","o":["tiger","løve","leopard","ulv"],"a":"tiger","r":"'Tiger' er det samme på engelsk og dansk."},
{"g":3,"b":3,"k":"o","q":"Hvad hedder 'ulv' på engelsk?","o":["fox","owl","bear","wolf"],"a":"wolf","r":"Ulv = wolf. Ræv = fox, ugle = owl."},
{"g":3,"b":3,"k":"o","q":"Hvad betyder 'owl'?","o":["ulv","ål","ugle","and"],"a":"ugle","r":"'Owl' betyder ugle. Ugler er vågne om natten."},
{"g":3,"b":3,"k":"o","q":"Hvad betyder 'kitten'?","o":["kylling","killing","kat","hvalp"],"a":"killing","r":"'Kitten' er en killing — en lille kat. En hvalp hedder 'puppy'."},
{"g":3,"b":3,"k":"o","q":"Hvad betyder 'hungry'?","o":["sulten","vred","træt","tørstig"],"a":"sulten","r":"'Hungry' betyder sulten. Tørstig hedder 'thirsty'."},
{"g":3,"b":3,"k":"o","q":"Hvad betyder 'thirsty'?","o":["træt","sulten","syg","tørstig"],"a":"tørstig","r":"'Thirsty' betyder tørstig. Så skal man have noget at drikke."},
{"g":3,"b":3,"k":"o","q":"Hvad betyder 'angry'?","o":["bange","glad","vred","sulten"],"a":"vred","r":"'Angry' betyder vred eller sur. Bange hedder 'scared'."},
{"g":3,"b":3,"k":"o","q":"Hvad betyder 'scared'?","o":["sur","bange","træt","glad"],"a":"bange","r":"'Scared' betyder bange. 'I am scared of spiders' = jeg er bange for edderkopper."},
{"g":3,"b":3,"k":"o","q":"Hvad betyder 'beautiful'?","o":["smuk","stor","bred","bitter"],"a":"smuk","r":"'Beautiful' betyder smuk eller meget flot."},
{"g":3,"b":3,"k":"h","q":"Hvad betyder 'What colour is it?'","o":["Hvad koster den?","Hvor er den?","Hvor stor er den?","Hvilken farve er den?"],"a":"Hvilken farve er den?","r":"'Colour' betyder farve. Svar f.eks.: 'It is green.'"},
{"g":3,"b":3,"k":"h","q":"Hvad betyder 'How many?'","o":["Hvor meget koster?","Hvor gammel?","Hvor mange?","Hvordan?"],"a":"Hvor mange?","r":"'How many' spørger om antal: 'How many dogs?' = hvor mange hunde?"},
{"g":3,"b":3,"k":"h","q":"Hvad svarer man på 'Do you like pizza?', hvis man godt kan lide pizza?","o":["Yes, I am.","Yes, I do.","Yes, I like.","Yes, it do."],"a":"Yes, I do.","r":"Svaret gentager 'do': 'Yes, I do' eller 'No, I don't'."},
{"g":3,"b":3,"k":"h","q":"Hvad betyder 'Can I go to the toilet?'","o":["Må jeg gå på toilettet?","Hvor er toilettet?","Toilettet er ude af drift","Jeg har været på toilettet"],"a":"Må jeg gå på toilettet?","r":"'Can I …?' bruges, når man spørger om lov."},
{"g":3,"b":3,"k":"h","q":"Hvad betyder 'I'm sorry, I'm late'?","o":["Undskyld, jeg er træt","Undskyld, jeg går nu","Undskyld, jeg glemte det","Undskyld, jeg kommer for sent"],"a":"Undskyld, jeg kommer for sent","r":"'Late' betyder for sent. Man siger undskyld, når man kommer for sent."},
{"g":3,"b":3,"k":"h","q":"Hvad betyder 'Be careful!'?","o":["Skynd dig!","Vær stille!","Pas på!","Vær glad!"],"a":"Pas på!","r":"'Careful' betyder forsigtig. 'Be careful!' = pas på!"},
{"g":3,"b":3,"k":"h","q":"Hvad betyder 'Hurry up!'?","o":["Ti stille!","Skynd dig!","Kom op!","Vent her!"],"a":"Skynd dig!","r":"'Hurry up' betyder skynd dig."},
{"g":3,"b":3,"k":"h","q":"Hvad betyder 'What's this?'","o":["Hvad er det her?","Hvem er det?","Hvor er det?","Hvorfor er det?"],"a":"Hvad er det her?","r":"'What' betyder hvad, og 'this' betyder dette/det her."},
{"g":3,"b":3,"k":"h","q":"Hvad betyder 'My favourite animal is a horse'?","o":["Jeg har en hest","Jeg kan ikke lide heste","Min hest er meget gammel","Mit yndlingsdyr er en hest"],"a":"Mit yndlingsdyr er en hest","r":"'Favourite' betyder yndlings-."},
{"g":3,"b":3,"k":"h","q":"Hvordan siger man 'Jeg har ondt i hovedet'?","o":["I have a head.","My head is happy.","I have a headache.","I am a head."],"a":"I have a headache.","r":"'Headache' betyder hovedpine — 'head' (hoved) + 'ache' (smerte)."},
{"g":3,"b":3,"k":"g","q":"Hvilket ord mangler? 'He ___ to school every day.'","o":["walk","walks","walking","to walk"],"a":"walks","r":"Med 'he', 'she' og 'it' får verbet -s i nutid: he walks."},
{"g":3,"b":3,"k":"g","q":"Hvilket ord mangler? 'My sister ___ pizza.'","o":["likes","like","liking","are like"],"a":"likes","r":"'My sister' er 'she', så verbet får -s: she likes."},
{"g":3,"b":3,"k":"g","q":"Hvilket ord mangler? 'The ball is ___ the box.' (inde i kassen)","o":["on","under","behind","in"],"a":"in","r":"'In' betyder i/inde i. 'On' betyder på."},
{"g":3,"b":3,"k":"g","q":"Hvilket ord mangler? 'The cup is ___ the table.' (oven på bordet)","o":["in","under","on","between"],"a":"on","r":"'On' betyder på: on the table = på bordet."},
{"g":3,"b":3,"k":"g","q":"Hvilket ord mangler? 'The cat is ___ the bed.' (nedenunder)","o":["on","under","in","next"],"a":"under","r":"'Under' betyder under: under the bed = under sengen."},
{"g":3,"b":3,"k":"g","q":"Hvad er flertal af 'baby'?","o":["babies","babys","babyes","baby"],"a":"babies","r":"Når et ord ender på konsonant + y, skifter y til -ies: babies."},
{"g":3,"b":3,"k":"g","q":"Hvad er flertal af 'bus'?","o":["buss","busies","bus","buses"],"a":"buses","r":"Efter -s tilføjer man -es: one bus, two buses."},
{"g":3,"b":3,"k":"g","q":"Hvad er flertal af 'man'?","o":["mans","mens","men","manes"],"a":"men","r":"'Man' er uregelmæssig: one man, two men."},
{"g":3,"b":3,"k":"g","q":"Hvad er flertal af 'foot'?","o":["foots","feet","feets","footes"],"a":"feet","r":"'Foot' er uregelmæssig: one foot, two feet."},
{"g":3,"b":3,"k":"g","q":"Hvilket ord mangler? 'I ___ like spiders.' (jeg kan ikke lide)","o":["don't","doesn't","not","am not"],"a":"don't","r":"Med 'I' bruger man 'don't': I don't like spiders."},
{"g":3,"b":3,"k":"g","q":"Hvilket ord mangler? '___ you like football?'","o":["Does","Are","Is","Do"],"a":"Do","r":"Spørgsmål med 'you' starter med 'Do': Do you like football?"},
{"g":3,"b":3,"k":"g","q":"Hvilket ord mangler? 'This is ___ bag.' (hendes taske)","o":["his","she","her","him"],"a":"her","r":"'Her' betyder hendes: her bag = hendes taske."},
{"g":3,"b":3,"k":"g","q":"Hvilket ord mangler? 'We ___ two cats.'","o":["has","have","is","are"],"a":"have","r":"Med 'we' bruger man 'have': we have = vi har."},
{"g":3,"b":3,"k":"g","q":"Hvilket ord mangler? 'Where ___ my shoes?'","o":["are","is","am","be"],"a":"are","r":"'Shoes' er flertal, så man bruger 'are': Where are my shoes?"},
{"g":3,"b":3,"k":"g","q":"Hvilket ord betyder 'os'?","o":["we","our","they","us"],"a":"us","r":"'Us' betyder os: 'Come with us' = kom med os. 'We' betyder vi."},
{"g":3,"b":3,"k":"g","q":"Hvilket ord betyder 'vores'?","o":["us","we","our","your"],"a":"our","r":"'Our' betyder vores: our house = vores hus."},
{"g":3,"b":3,"k":"l","q":"Læs: 'Tim is eight. His brother is ten.' Hvem er ældst?","o":["Tim","Tims bror","De er lige gamle","Det står der ikke"],"a":"Tims bror","r":"Broren er ti (ten), og Tim er otte (eight). Broren er ældst."},
{"g":3,"b":3,"k":"l","q":"Læs: 'It is raining. Mia takes her umbrella.' Hvad tager Mia med?","o":["en paraply","en hue","en bold","en is"],"a":"en paraply","r":"'Umbrella' betyder paraply — godt at have, når det regner (raining)."},
{"g":3,"b":3,"k":"l","q":"Læs: 'Nora gets a cake and ten candles.' Hvad fejrer Nora sikkert?","o":["jul","påske","nytår","sin fødselsdag"],"a":"sin fødselsdag","r":"Kage og ti lys (candles) — Nora har sikkert fødselsdag og bliver ti."},
{"g":3,"b":3,"k":"l","q":"Læs: 'Oscar is in bed. He has a cold and can't go to school.' Hvorfor er Oscar hjemme?","o":["Det er weekend","Han er træt","Han er forkølet","Skolen er lukket"],"a":"Han er forkølet","r":"'He has a cold' betyder han er forkølet."},
{"g":3,"b":3,"k":"l","q":"Læs: 'Ella has a pet. It can fly and it sings.' Hvilket dyr har Ella sikkert?","o":["en kat","en fugl","en fisk","en hund"],"a":"en fugl","r":"Dyret kan flyve (fly) og synge (sings) — det er sikkert en fugl."},
{"g":3,"b":3,"k":"l","q":"Læs: 'Ben's T-shirt is wet. He played in the rain.' Hvorfor er T-shirten våd?","o":["Han legede i regnen","Han svømmede","Han vaskede den","Han spildte saft"],"a":"Han legede i regnen","r":"'Wet' betyder våd. Han legede i regnen (rain)."},
{"g":3,"b":3,"k":"l","q":"Læs: 'The shop is closed on Sunday.' Hvornår er butikken lukket?","o":["lørdag","mandag","hver dag","søndag"],"a":"søndag","r":"'Closed' betyder lukket, og 'Sunday' er søndag."},
{"g":3,"b":3,"k":"l","q":"Læs: 'Lisa has a red pen, a blue pen and a green pencil.' Hvor mange kuglepenne har Lisa?","o":["tre","en","to","fire"],"a":"to","r":"Hun har to kuglepenne (pens). Den grønne er en blyant (pencil)."},
{"g":3,"b":3,"k":"l","q":"Læs: 'Ali is hungry, so he eats an apple.' Hvorfor spiser Ali et æble?","o":["Han er tørstig","Han er sulten","Han er træt","Han er syg"],"a":"Han er sulten","r":"'So' betyder så/derfor. Ali er sulten (hungry)."},
{"g":3,"b":3,"k":"l","q":"Læs: 'In winter it is cold and there is snow.' Hvad er der om vinteren?","o":["sne","sol","blomster","blade"],"a":"sne","r":"'Snow' betyder sne. Om vinteren (winter) er det koldt."},
{"g":3,"b":3,"k":"l","q":"Læs: 'Jack has two dogs. Each dog has four legs.' Hvor mange ben har hundene til sammen?","o":["fire","seks","to","otte"],"a":"otte","r":"To hunde med fire ben hver: 2 x 4 = 8 (eight)."},
{"g":3,"b":3,"k":"l","q":"Læs: 'Sofie can't find her shoes. They are under the bed.' Hvor er skoene?","o":["i skabet","på bordet","under sengen","i haven"],"a":"under sengen","r":"'Under the bed' betyder under sengen."},
{"g":3,"b":3,"k":"l","q":"Læs: 'Today is hot and sunny. Let's go to the beach!' Hvor vil de hen?","o":["skolen","stranden","skoven","biografen"],"a":"stranden","r":"'Beach' betyder strand. Det passer godt til varmt og solrigt vejr."},
{"g":3,"b":3,"k":"l","q":"Læs: 'I get up at 7. I go to bed at 8.' Hvornår går personen i seng?","o":["kl. 8","kl. 7","kl. 9","kl. 10"],"a":"kl. 8","r":"'Go to bed' betyder gå i seng. Det sker kl. 8 (eight)."},
{"g":3,"b":3,"k":"l","q":"Læs: 'Freja is not tall. She is short.' Hvordan er Freja?","o":["høj","tyk","hurtig","lav"],"a":"lav","r":"'Short' betyder lav (eller kort). 'Tall' betyder høj."},
{"g":3,"b":3,"k":"l","q":"Læs: 'The bird is in the tree. The cat is under the tree.' Hvem er oppe i træet?","o":["katten","begge","fuglen","ingen"],"a":"fuglen","r":"'In the tree' = oppe i træet. Det er fuglen (the bird)."},
{"g":3,"b":3,"k":"l","q":"Læs: 'My dad is a doctor. He works at a hospital.' Hvor arbejder far?","o":["på en skole","på et hospital","i en butik","på en gård"],"a":"på et hospital","r":"'Doctor' er læge, og 'hospital' er hospital."},
{"g":3,"b":3,"k":"l","q":"Læs: 'Peter has got five apples. He gives two to Anna.' Hvor mange æbler har Peter nu?","o":["tre","to","fem","syv"],"a":"tre","r":"Fem minus to giver tre (three). 'Gives' betyder giver."},
{"g":3,"b":4,"k":"g","q":"Hvilket ord mangler? 'Look! The baby ___ sleeping.'","o":["are","am","be","is"],"a":"is","r":"'The baby' er 'it' eller 'she/he', så det hedder 'is sleeping' = sover lige nu."},
{"g":3,"b":4,"k":"g","q":"Hvilket ord mangler? 'They ___ playing football now.'","o":["is","am","are","does"],"a":"are","r":"Med 'they' bruger man 'are': they are playing = de spiller lige nu."},
{"g":3,"b":4,"k":"g","q":"Hvilken sætning betyder 'Jeg spiser lige nu'?","o":["I eat now am.","I am eating now.","I eating now.","I is eating now."],"a":"I am eating now.","r":"Noget, der sker lige nu: am/is/are + verbum med -ing. I am eating."},
{"g":3,"b":4,"k":"g","q":"Hvilket ord mangler? 'Yesterday I ___ at home.'","o":["was","am","is","were"],"a":"was","r":"'Yesterday' (i går) betyder datid. 'Am' bliver til 'was': I was at home."},
{"g":3,"b":4,"k":"g","q":"Hvilket ord mangler? 'We ___ at the zoo last Sunday.'","o":["was","are","is","were"],"a":"were","r":"Datid af 'are' er 'were': we were = vi var."},
{"g":3,"b":4,"k":"g","q":"Hvilket ord mangler? 'She ___ ill yesterday.'","o":["were","is","was","be"],"a":"was","r":"'Yesterday' viser datid. Med 'she' hedder det 'was'."},
{"g":3,"b":4,"k":"g","q":"Hvilket ord mangler? 'I ___ my room yesterday.' (gjorde rent)","o":["clean","cleaned","cleans","cleaning"],"a":"cleaned","r":"Mange verber får -ed i datid: clean → cleaned."},
{"g":3,"b":4,"k":"g","q":"Hvad er datid af 'play'?","o":["played","plaid","playd","plays"],"a":"played","r":"'Play' får -ed: play → played. 'I played football' = jeg spillede fodbold."},
{"g":3,"b":4,"k":"g","q":"Hvad er datid af 'jump'?","o":["jumpt","jumps","jumping","jumped"],"a":"jumped","r":"'Jump' får -ed i datid: jumped = hoppede."},
{"g":3,"b":4,"k":"g","q":"Hvilket ord mangler? 'There ___ a cat in the garden.'","o":["are","am","is","be"],"a":"is","r":"Én kat: 'There is a cat' = der er en kat."},
{"g":3,"b":4,"k":"g","q":"Hvilket ord mangler? 'There ___ five birds in the tree.'","o":["is","are","am","has"],"a":"are","r":"Flere fugle (five birds): 'There are' = der er."},
{"g":3,"b":4,"k":"g","q":"Hvilket ord mangler? 'I have ___ orange.'","o":["an","a","two","three"],"a":"an","r":"Før en vokallyd (a, e, i, o, u) bruger man 'an': an orange."},
{"g":3,"b":4,"k":"g","q":"Hvilket ord mangler? 'She has ___ dog.'","o":["an","two","three","a"],"a":"a","r":"'Dog' starter med en konsonant, så man bruger 'a': a dog."},
{"g":3,"b":4,"k":"g","q":"Hvilket ord mangler? 'I ___ got a new bike.'","o":["has","am","have","is"],"a":"have","r":"'I have got' betyder jeg har (fået). Med 'he/she' hedder det 'has got'."},
{"g":3,"b":4,"k":"g","q":"Hvad betyder 'first'?","o":["sidst","først eller første","anden","tredje"],"a":"først eller første","r":"'First' betyder første. Second = anden, third = tredje."},
{"g":3,"b":4,"k":"g","q":"Hvilket ord mangler? 'Who ___ that boy?'","o":["is","are","am","do"],"a":"is","r":"'Who is that boy?' = hvem er den dreng?"},
{"g":3,"b":4,"k":"g","q":"Hvilket ord mangler? 'He ___ like fish.' (han kan ikke lide)","o":["don't","isn't","not","doesn't"],"a":"doesn't","r":"Med 'he/she/it' bruger man 'doesn't': He doesn't like fish."},
{"g":3,"b":4,"k":"g","q":"Hvilket ord mangler? '___ she play the piano?'","o":["Do","Is","Does","Are"],"a":"Does","r":"Spørgsmål med 'she' starter med 'Does': Does she play the piano?"},
{"g":3,"b":4,"k":"g","q":"Hvilket ord mangler? 'Tom is ___ than Ben.' (højere)","o":["tall","taller","tallest","more tall"],"a":"taller","r":"Når man sammenligner to ting, sætter man -er på korte ord: taller = højere."},
{"g":3,"b":4,"k":"g","q":"Hvad er flertal af 'mouse'?","o":["mice","mouses","mousees","mices"],"a":"mice","r":"'Mouse' er uregelmæssig: one mouse, two mice."},
{"g":3,"b":4,"k":"g","q":"Hvad er flertal af 'tooth'?","o":["tooths","toothes","teeths","teeth"],"a":"teeth","r":"'Tooth' er uregelmæssig: one tooth, many teeth."},
{"g":3,"b":4,"k":"g","q":"Hvilket ord mangler? 'Can you help ___?' (mig)","o":["I","my","me","mine"],"a":"me","r":"'Me' betyder mig: help me = hjælp mig. 'I' bruges kun som 'jeg'."},
{"g":3,"b":4,"k":"g","q":"Hvilket ord mangler? 'This is my friend. ___ name is Ella.'","o":["She","Her","His","Hers"],"a":"Her","r":"Ella er en pige, så det er 'her name' = hendes navn."},
{"g":3,"b":4,"k":"o","q":"Hvilket ord passer IKKE ind? spring – summer – winter – Tuesday","o":["Tuesday","spring","summer","winter"],"a":"Tuesday","r":"Spring, summer og winter er årstider. 'Tuesday' er en ugedag."},
{"g":3,"b":4,"k":"o","q":"Hvilket ord passer IKKE ind? bed – sofa – chair – carrot","o":["bed","sofa","chair","carrot"],"a":"carrot","r":"Bed, sofa og chair er møbler. En 'carrot' er en gulerod."},
{"g":3,"b":4,"k":"o","q":"Hvilket ord passer IKKE ind? run – jump – swim – green","o":["run","jump","green","swim"],"a":"green","r":"Run, jump og swim er ting, man gør. 'Green' er en farve."},
{"g":3,"b":4,"k":"o","q":"Hvilket ord passer IKKE ind? January – March – May – Monday","o":["January","Monday","March","May"],"a":"Monday","r":"Januar, marts og maj er måneder. 'Monday' er en ugedag."},
{"g":3,"b":4,"k":"o","q":"Hvad betyder 'second' i 'the second day'?","o":["anden","sekund","første","sidste"],"a":"anden","r":"'Second' betyder anden: the second day = den anden dag. Det kan også betyde sekund."},
{"g":3,"b":4,"k":"o","q":"Hvad betyder 'o'clock' i 'It's five o'clock'?","o":["halv","kvart over","minutter","klokken (hel time)"],"a":"klokken (hel time)","r":"'O'clock' bruges ved hele timer: five o'clock = klokken fem."},
{"g":3,"b":4,"k":"o","q":"Hvad betyder 'quarter past two'?","o":["kvart i to","halv to","kvart over to","klokken to"],"a":"kvart over to","r":"'Quarter' er et kvarter, og 'past' betyder over: kvart over to."},
{"g":3,"b":4,"k":"o","q":"Hvad betyder 'Wednesday' og 'weekend'?","o":["onsdag og uge","onsdag og weekend","torsdag og weekend","tirsdag og hverdag"],"a":"onsdag og weekend","r":"'Wednesday' er onsdag, og 'weekend' er lørdag og søndag."},
{"g":3,"b":4,"k":"o","q":"Hvad hedder 'jordbær' på engelsk?","o":["strawberry","blueberry","raspberry","cherry"],"a":"strawberry","r":"Jordbær = strawberry. Blåbær = blueberry, hindbær = raspberry."},
{"g":3,"b":4,"k":"o","q":"Hvad betyder 'vegetables'?","o":["frugt","kød","slik","grøntsager"],"a":"grøntsager","r":"'Vegetables' betyder grøntsager, f.eks. gulerødder og kartofler."},
{"g":3,"b":4,"k":"o","q":"Hvad betyder 'sweets'?","o":["sokker","svamp","slik","sved"],"a":"slik","r":"'Sweets' betyder slik (britisk). Amerikanere siger 'candy'."},
{"g":3,"b":4,"k":"o","q":"Hvad betyder 'farmer'?","o":["far","landmand","maler","fisker"],"a":"landmand","r":"'Farmer' er landmand. 'Farm' betyder bondegård."},
{"g":3,"b":4,"k":"o","q":"Hvad betyder 'police officer'?","o":["politibetjent","brandmand","postbud","læge"],"a":"politibetjent","r":"'Police officer' er politibetjent. Brandmand = firefighter."},
{"g":3,"b":4,"k":"o","q":"Hvad betyder 'firefighter'?","o":["politibetjent","fisker","kok","brandmand"],"a":"brandmand","r":"'Fire' er ild, og en 'firefighter' kæmper mod ild — en brandmand."},
{"g":3,"b":4,"k":"o","q":"Hvad betyder 'shop'?","o":["skib","sko","butik","skov"],"a":"butik","r":"'Shop' betyder butik. 'Go shopping' = gå på indkøb."},
{"g":3,"b":4,"k":"o","q":"Hvad betyder 'forest'?","o":["fest","skov","fort","forår"],"a":"skov","r":"'Forest' betyder skov. Fest hedder 'party'."},
{"g":3,"b":4,"k":"o","q":"Hvad betyder 'beach'?","o":["strand","bænk","bøg","bæk"],"a":"strand","r":"'Beach' betyder strand. Bænk hedder 'bench'."},
{"g":3,"b":4,"k":"o","q":"Hvad betyder 'sea'?","o":["sø","se","sæl","hav"],"a":"hav","r":"'Sea' betyder hav. En sø hedder 'lake'. 'See' (med to e'er) betyder at se."},
{"g":3,"b":4,"k":"o","q":"Hvad betyder 'clever'?","o":["kold","klodset","klog","glad"],"a":"klog","r":"'Clever' betyder klog eller dygtig."},
{"g":3,"b":4,"k":"o","q":"Hvad betyder 'quiet'?","o":["hurtig","stille","kvik","vild"],"a":"stille","r":"'Quiet' betyder stille. 'Be quiet!' = vær stille!"},
{"g":3,"b":4,"k":"o","q":"Hvad betyder 'noisy'?","o":["larmende","næsvis","nysgerrig","stille"],"a":"larmende","r":"'Noisy' betyder larmende. 'Noise' betyder larm."},
{"g":3,"b":4,"k":"o","q":"Hvad betyder 'dirty'?","o":["tørstig","tyk","ren","beskidt"],"a":"beskidt","r":"'Dirty' betyder beskidt. Det modsatte er 'clean' — ren."},
{"g":3,"b":4,"k":"o","q":"Hvad betyder 'heavy'?","o":["himmel","høj","tung","let"],"a":"tung","r":"'Heavy' betyder tung. Det modsatte er 'light' — let."},
{"g":3,"b":4,"k":"o","q":"Hvad betyder 'empty'?","o":["fuld","tom","tyk","lang"],"a":"tom","r":"'Empty' betyder tom. Det modsatte er 'full' — fuld."},
{"g":3,"b":4,"k":"h","q":"Hvad betyder 'What's the weather like?'","o":["Hvordan er vejret?","Hvad laver du?","Kan du lide vejret?","Hvornår regner det?"],"a":"Hvordan er vejret?","r":"'Weather' betyder vejr. Svar f.eks.: 'It's sunny.'"},
{"g":3,"b":4,"k":"h","q":"Hvad betyder 'What time is it?' og hvad kan man svare?","o":["Hvad er dato? – It's Monday.","Hvor gammel er du? – I'm three.","Hvor er du? – I'm at home.","Hvad er klokken? – It's three o'clock."],"a":"Hvad er klokken? – It's three o'clock.","r":"'Time' betyder tid. Svaret giver klokkeslættet."},
{"g":3,"b":4,"k":"h","q":"Hvad betyder 'Can you say that again, please?'","o":["Kan du tale højere?","Kan du hjælpe mig?","Kan du sige det igen?","Kan du komme igen?"],"a":"Kan du sige det igen?","r":"'Again' betyder igen. Brug sætningen, når du ikke hørte, hvad der blev sagt."},
{"g":3,"b":4,"k":"h","q":"Hvad betyder 'I've got a question'?","o":["Jeg har et svar","Jeg har et spørgsmål","Jeg har fået en gave","Jeg har en idé"],"a":"Jeg har et spørgsmål","r":"'Question' betyder spørgsmål. 'Answer' betyder svar."},
{"g":3,"b":4,"k":"h","q":"Hvad betyder 'It's my turn!'?","o":["Det er min tur!","Det er mit hus!","Det er min fejl!","Det er min bold!"],"a":"Det er min tur!","r":"'Turn' betyder tur i et spil: 'It's your turn' = det er din tur."},
{"g":3,"b":4,"k":"h","q":"Hvad betyder 'Don't worry!'?","o":["Lad være!","Skynd dig!","Hold op!","Bare rolig!"],"a":"Bare rolig!","r":"'Worry' betyder bekymre sig. 'Don't worry' = bare rolig, du skal ikke bekymre dig."},
{"g":3,"b":4,"k":"h","q":"Hvad betyder 'Good luck!'?","o":["Godt gået!","God tur!","Held og lykke!","God bedring!"],"a":"Held og lykke!","r":"'Luck' betyder held. 'Good luck!' = held og lykke!"},
{"g":3,"b":4,"k":"h","q":"Hvad betyder 'Get well soon!'?","o":["Kom snart!","God bedring!","Kom godt hjem!","Hav det sjovt!"],"a":"God bedring!","r":"'Get well' betyder blive rask. Man siger det til en, der er syg."},
{"g":3,"b":4,"k":"h","q":"Hvad siger man, når man vil låne et viskelæder?","o":["Can I borrow your rubber, please?","Give me rubber now.","You have rubber?","I am rubber, please."],"a":"Can I borrow your rubber, please?","r":"'Can I borrow …, please?' = må jeg låne …? Det er høfligt."},
{"g":3,"b":4,"k":"h","q":"Hvad betyder 'See you later!'?","o":["Se dig for!","Kom tilbage!","Vent lidt!","Vi ses senere!"],"a":"Vi ses senere!","r":"'Later' betyder senere. 'See you later' = vi ses senere."},
{"g":3,"b":4,"k":"l","q":"Læs: 'Mum is cooking in the kitchen. Dad is reading in the living room.' Hvad laver far?","o":["Han laver mad","Han sover","Han læser","Han ser fjernsyn"],"a":"Han læser","r":"'Reading' betyder læser. Det er mor, der laver mad (cooking)."},
{"g":3,"b":4,"k":"l","q":"Læs: 'Yesterday was Sunday.' Hvilken dag er det i dag?","o":["lørdag","mandag","søndag","tirsdag"],"a":"mandag","r":"I går (yesterday) var søndag, så i dag er mandag (Monday)."},
{"g":3,"b":4,"k":"l","q":"Læs: 'Lucas has got a dog, two cats and a fish.' Hvor mange kæledyr har Lucas?","o":["fire","tre","to","fem"],"a":"fire","r":"En hund + to katte + en fisk = fire kæledyr."},
{"g":3,"b":4,"k":"l","q":"Læs: 'The red car is fast. The blue car is faster.' Hvilken bil er hurtigst?","o":["den røde","de er lige hurtige","det står der ikke","den blå"],"a":"den blå","r":"'Faster' betyder hurtigere. Den blå bil er hurtigere end den røde."},
{"g":3,"b":4,"k":"l","q":"Læs: 'Ida wears a coat, a scarf and gloves.' Hvilken årstid er det sikkert?","o":["sommer","forår","vinter","det kan man ikke vide"],"a":"vinter","r":"Frakke, halstørklæde og vanter (gloves) bruger man, når det er koldt — om vinteren."},
{"g":3,"b":4,"k":"l","q":"Læs: 'I can't play today. I have a lot of homework.' Hvorfor kan personen ikke lege?","o":["Personen er syg","Personen har mange lektier","Personen skal til fødselsdag","Personen er sur"],"a":"Personen har mange lektier","r":"'Homework' betyder lektier. 'A lot of' betyder mange."},
{"g":3,"b":4,"k":"l","q":"Læs: 'Noah was at the zoo. He saw lions, monkeys and a giraffe.' Hvor var Noah?","o":["i zoologisk have","i skoven","på stranden","i skolen"],"a":"i zoologisk have","r":"'Zoo' er en zoologisk have. Der så han løver, aber og en giraf."},
{"g":3,"b":4,"k":"l","q":"Læs: 'Clara is eating a sandwich and drinking milk. It is 12 o'clock.' Hvilket måltid spiser Clara sikkert?","o":["morgenmad","aftensmad","kage","frokost"],"a":"frokost","r":"Klokken 12 (twelve o'clock) spiser man frokost (lunch)."},
{"g":3,"b":4,"k":"l","q":"Læs: 'The museum opens at ten. Now it's nine.' Kan man komme ind nu?","o":["Ja, det er åbent","Nej, det er lukket hele dagen","Nej, det åbner om en time","Ja, men kun i en time"],"a":"Nej, det åbner om en time","r":"Museet åbner kl. 10 (opens at ten), og klokken er 9. Man må vente en time."},
{"g":3,"b":4,"k":"l","q":"Læs: 'Mark's bag is heavy. There are six books in it.' Hvorfor er tasken tung?","o":["Den er våd","Der er seks bøger i den","Den er ny","Der er sten i den"],"a":"Der er seks bøger i den","r":"'Heavy' betyder tung. Der er seks bøger (six books) i tasken."},
{"g":3,"b":4,"k":"l","q":"Læs: 'Sara loves animals. She wants to be a vet.' Hvad vil Sara være?","o":["dyrlæge","lærer","politibetjent","kok"],"a":"dyrlæge","r":"En 'vet' er en dyrlæge. Det passer godt, for Sara elsker dyr (animals)."},
{"g":3,"b":4,"k":"l","q":"Læs: 'The glass is empty. Can I have some more juice?' Hvad vil personen?","o":["vaske glasset","have et nyt glas","have vand","have mere juice"],"a":"have mere juice","r":"'Empty' betyder tom. Personen vil have mere juice (more juice)."},
{"g":3,"b":4,"k":"l","q":"Læs: 'William is the youngest in his family.' Hvad betyder det?","o":["William er den ældste","William er den højeste","William er den yngste","William er den sjoveste"],"a":"William er den yngste","r":"'Young' betyder ung, og 'youngest' betyder yngst."},
{"g":3,"b":4,"k":"l","q":"Læs: 'Mia's birthday is on the first of May.' Hvornår har Mia fødselsdag?","o":["1. marts","1. maj","3. maj","1. juni"],"a":"1. maj","r":"'The first of May' = den første maj."},
{"g":3,"b":4,"k":"l","q":"Læs: 'Kim opens the window because it is hot.' Hvorfor åbner Kim vinduet?","o":["Det er varmt","Det er koldt","Det larmer","Det regner"],"a":"Det er varmt","r":"'Because' betyder fordi. Det er varmt (hot)."},
{"g":3,"b":4,"k":"l","q":"Læs: 'The library is next to the school.' Hvor ligger biblioteket?","o":["inde i skolen","bag skolen","langt fra skolen","ved siden af skolen"],"a":"ved siden af skolen","r":"'Next to' betyder ved siden af."},
{"g":3,"b":4,"k":"l","q":"Læs: 'Jonas has a sister. She is two years older than him. Jonas is eight.' Hvor gammel er søsteren?","o":["seks år","otte år","ti år","tolv år"],"a":"ti år","r":"Søsteren er to år ældre (two years older). 8 + 2 = 10."},
{"g":3,"b":4,"k":"l","q":"Læs: 'We are going to the beach. Don't forget your swimsuit!' Hvad må man ikke glemme?","o":["paraply","badetøj","madpakke","hue"],"a":"badetøj","r":"'Swimsuit' betyder badedragt/badetøj. 'Don't forget' = glem ikke."},
{"g":3,"b":4,"k":"l","q":"Læs: 'The dog is barking. Someone is at the door.' Hvorfor gør hunden?","o":["Der er nogen ved døren","Den er sulten","Den vil ud og gå","Den er bange for katten"],"a":"Der er nogen ved døren","r":"'Barking' betyder gør. Der står nogen ved døren (at the door)."},
{"g":3,"b":4,"k":"l","q":"Læs: 'Emil has a cold, so he stays in bed and drinks hot tea.' Hvad drikker Emil?","o":["kold mælk","varm kakao","juice","varm te"],"a":"varm te","r":"'Hot tea' betyder varm te. 'Has a cold' betyder er forkølet."},
{"g":3,"b":4,"k":"l","q":"Læs: 'In the morning Ava brushes her teeth. Then she has breakfast.' Hvad gør Ava først?","o":["spiser morgenmad","går i skole","børster tænder","tager tøj på"],"a":"børster tænder","r":"Først børster hun tænder (brushes her teeth). 'Then' betyder derefter."},
{"g":3,"b":4,"k":"l","q":"Læs: 'There are 20 pupils in my class. 11 are girls.' Hvor mange drenge er der?","o":["11","9","20","10"],"a":"9","r":"20 elever minus 11 piger giver 9 drenge."},
{"g":3,"b":4,"k":"g","q":"Hvilket ord mangler? 'My friends ___ at school yesterday.'","o":["were","was","are","is"],"a":"were","r":"'My friends' er flertal, og 'yesterday' viser datid: they were = de var."},
{"g":3,"b":4,"k":"o","q":"Hvad betyder 'third'?","o":["tredive","tre","træ","tredje"],"a":"tredje","r":"'Third' betyder tredje. First, second, third = første, anden, tredje."},
{"g":3,"b":4,"k":"h","q":"Hvad betyder 'Excuse me, where is the toilet?'","o":["Undskyld, må jeg gå på toilettet?","Toilettet er derovre","Undskyld, hvor er toilettet?","Jeg skal ikke på toilettet"],"a":"Undskyld, hvor er toilettet?","r":"'Excuse me' bruger man for at få nogens opmærksomhed. 'Where' = hvor."},
{"g":3,"b":4,"k":"l","q":"Læs: 'Tom's cat is grey and white. It has a long tail.' Hvad har katten?","o":["lange ører","en lang hale","en kort hale","sorte poter"],"a":"en lang hale","r":"'Tail' betyder hale, og 'long' betyder lang."}
]$$::jsonb) AS e
JOIN (VALUES
  ('o', 'ordforråd', 'recall', 'factual', 'surface_association'),
  ('h', 'hverdagsudtryk', 'comprehension', 'conceptual', 'surface_association'),
  ('g', 'grammatik', 'application', 'applied', 'overgeneralization'),
  ('l', 'læseforståelse', 'analysis', 'inferential', 'surface_association')
) AS m(k, concept, skill, dtype, mis) ON m.k = e->>'k';
