-- Engelsk batch 2, 3. klasse bånd 1-2: 167 nye MC-spørgsmål (learning_objective='english', bånd 1-4).
-- Del af 1000 nye engelskspørgsmål til 3.-5. klasse. Samme indholds- og metadata-mønster som
-- 20261001000000_english_grade3_5; metadata afledes her af kategorinøglen k:
-- o=ordforråd, h=hverdagsudtryk, g=grammatik, l=læseforståelse. difficulty = bånd.
-- Bånd 1-2: reinforcement/conceptual_bridge. Bånd 3-4: challenge/reframing. All is_active=true.
-- Må KUN anvendes via apply_migration med særskilt ejer-autorisation (D-110).

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band)
SELECT
  jsonb_build_object('question', e->>'q', 'options', e->'o', 'correct', e->>'a',
                     'accepted_answers', jsonb_build_array(e->>'a'), 'review_text', e->>'r'),
  'mc', 'short',
  jsonb_build_object('concepts', jsonb_build_array(m.concept), 'cognitive_skill', m.skill,
                     'difficulty_type', m.dtype, 'misconception_type', m.mis,
                     'challenge_role', CASE WHEN (e->>'b')::int >= 3 THEN 'challenge' ELSE 'reinforcement' END,
                     'insight_type', CASE WHEN (e->>'b')::int >= 3 THEN 'reframing' ELSE 'conceptual_bridge' END,
                     'domain', 'english'),
  'mc_single', (e->>'b')::int, 'auto', true, 'english', (e->>'g')::int, (e->>'b')::int
FROM jsonb_array_elements($$[
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'bird'?","o":["fugl","fisk","bjørn","bi"],"a":"fugl","r":"'Bird' betyder fugl. Fisk hedder 'fish' på engelsk."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder 'hest' på engelsk?","o":["house","hose","mouse","horse"],"a":"horse","r":"Hest hedder 'horse'. Pas på: 'house' er et hus."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'fish'?","o":["frø","fugl","fisk","får"],"a":"fisk","r":"'Fish' betyder fisk. Frø hedder 'frog'."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder 'ko' på engelsk?","o":["cat","cow","cup","cake"],"a":"cow","r":"Ko hedder 'cow'. 'Cup' er en kop, og 'cake' er en kage."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'pig'?","o":["gris","pige","hund","ged"],"a":"gris","r":"'Pig' betyder gris — ikke pige! Pige hedder 'girl'."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder dyret 'and' på engelsk?","o":["dog","cow","pig","duck"],"a":"duck","r":"Dyret and hedder 'duck'. En and siger 'quack'."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'mouse'?","o":["mund","mos","mus","måge"],"a":"mus","r":"'Mouse' betyder mus. Mund hedder 'mouth'."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder 'kanin' på engelsk?","o":["robot","rabbit","rainbow","river"],"a":"rabbit","r":"Kanin hedder 'rabbit'. 'Rainbow' er en regnbue."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'sheep'?","o":["får","skib","ske","sko"],"a":"får","r":"'Sheep' er et får. 'Ship' (skib) lyder næsten ens, men er noget helt andet."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'blue'?","o":["brun","sort","hvid","blå"],"a":"blå","r":"'Blue' betyder blå. Brun hedder 'brown'."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder 'gul' på engelsk?","o":["orange","purple","yellow","pink"],"a":"yellow","r":"Gul hedder 'yellow'. 'Purple' er lilla."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'black'?","o":["hvid","sort","grå","brun"],"a":"sort","r":"'Black' betyder sort. Hvid hedder 'white'."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder 'hvid' på engelsk?","o":["white","grey","brown","pink"],"a":"white","r":"Hvid hedder 'white'. Grå hedder 'grey'."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'pink'?","o":["lilla","orange","grå","lyserød"],"a":"lyserød","r":"'Pink' betyder lyserød. Lilla hedder 'purple'."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder 'brun' på engelsk?","o":["blue","green","brown","purple"],"a":"brown","r":"Brun hedder 'brown'. Det ligner det danske ord en lille smule."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder tallet 1 på engelsk?","o":["two","one","nine","ten"],"a":"one","r":"1 hedder 'one'. 2 = two, 9 = nine, 10 = ten."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder tallet 2 på engelsk?","o":["two","ten","twelve","three"],"a":"two","r":"2 hedder 'two'. Man udtaler det 'tu'."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder tallet 5 på engelsk?","o":["four","fine","nine","five"],"a":"five","r":"5 hedder 'five'. 'Four' er 4, og 'fine' betyder fin."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder tallet 4 på engelsk?","o":["five","fourteen","four","six"],"a":"four","r":"4 hedder 'four'. 'Fourteen' er 14."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder tallet 10 på engelsk?","o":["two","ten","eight","seven"],"a":"ten","r":"10 hedder 'ten'."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder tallet 6 på engelsk?","o":["six","seven","nine","eight"],"a":"six","r":"6 hedder 'six'. 7 = seven, 8 = eight."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'seven'?","o":["seks","otte","ni","syv"],"a":"syv","r":"'Seven' er tallet 7 — syv."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'eight'?","o":["syv","tre","otte","fire"],"a":"otte","r":"'Eight' er tallet 8 — otte. Man udtaler det 'eit'."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder tallet 9 på engelsk?","o":["one","nine","five","eight"],"a":"nine","r":"9 hedder 'nine'."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'sister'?","o":["søster","bror","mormor","tante"],"a":"søster","r":"'Sister' betyder søster. Bror hedder 'brother'."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder 'bror' på engelsk?","o":["mother","father","sister","brother"],"a":"brother","r":"Bror hedder 'brother'. 'Mother' er mor, og 'father' er far."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'boy'?","o":["pige","mand","dreng","bog"],"a":"dreng","r":"'Boy' betyder dreng. Pige hedder 'girl'."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder 'pige' på engelsk?","o":["boy","girl","pig","goal"],"a":"girl","r":"Pige hedder 'girl'. 'Pig' er en gris!"},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'hand'?","o":["hånd","hoved","hund","hals"],"a":"hånd","r":"'Hand' betyder hånd. Det ligner det danske ord."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder 'fod' på engelsk?","o":["food","hand","nose","foot"],"a":"foot","r":"Fod hedder 'foot'. 'Food' betyder mad."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'eye'?","o":["øre","æg","øje","ærme"],"a":"øje","r":"'Eye' betyder øje. Øre = ear, æg = egg."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder 'næse' på engelsk?","o":["nest","nose","mouth","neck"],"a":"nose","r":"Næse hedder 'nose'. 'Neck' er halsen."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'mouth'?","o":["mund","mus","måne","mave"],"a":"mund","r":"'Mouth' betyder mund. Mus hedder 'mouse'."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder 'øre' på engelsk?","o":["eye","arm","egg","ear"],"a":"ear","r":"Øre hedder 'ear'. 'Eye' er et øje."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'banana'?","o":["ananas","appelsin","banan","pære"],"a":"banan","r":"'Banana' betyder banan. Ananas hedder 'pineapple'."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder 'brød' på engelsk?","o":["bed","bread","red","butter"],"a":"bread","r":"Brød hedder 'bread'. 'Bed' er en seng, og 'butter' er smør."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'milk'?","o":["mælk","mel","vand","juice"],"a":"mælk","r":"'Milk' betyder mælk. Vand hedder 'water'."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder 'vand' på engelsk?","o":["wind","winter","milk","water"],"a":"water","r":"Vand hedder 'water'. 'Wind' er vind."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'cake'?","o":["kat","ko","kage","kop"],"a":"kage","r":"'Cake' betyder kage. Kop hedder 'cup'."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder 'æg' på engelsk?","o":["eye","egg","ear","leg"],"a":"egg","r":"Æg hedder 'egg'. 'Leg' er et ben."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'cheese'?","o":["ost","kirsebær","smør","kylling"],"a":"ost","r":"'Cheese' betyder ost. Man siger 'cheese', når man bliver fotograferet."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder 'bil' på engelsk?","o":["cat","cup","bike","car"],"a":"car","r":"Bil hedder 'car'. 'Bike' er en cykel."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'ball'?","o":["bål","ballon","bold","bil"],"a":"bold","r":"'Ball' betyder bold. Ballon hedder 'balloon'."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder 'bog' på engelsk?","o":["boot","book","ball","box"],"a":"book","r":"Bog hedder 'book'. 'Boot' er en støvle, og 'box' er en kasse."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'bike'?","o":["cykel","bil","bus","båd"],"a":"cykel","r":"'Bike' betyder cykel. Bil hedder 'car'."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder 'båd' på engelsk?","o":["bus","car","train","boat"],"a":"boat","r":"Båd hedder 'boat'. 'Train' er et tog."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'tree'?","o":["tre","tag","træ","tog"],"a":"træ","r":"'Tree' betyder træ. Tallet tre hedder 'three' — de lyder næsten ens."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder 'blomst' på engelsk?","o":["floor","flower","tree","grass"],"a":"flower","r":"Blomst hedder 'flower'. 'Floor' er et gulv, og 'grass' er græs."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'moon'?","o":["måne","morgen","mund","mor"],"a":"måne","r":"'Moon' betyder måne. Mandag hedder 'Monday' — månens dag."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder 'stjerne' på engelsk?","o":["sun","moon","sky","star"],"a":"star","r":"Stjerne hedder 'star'. 'Sky' er himlen."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'rain'?","o":["sne","sol","regn","vind"],"a":"regn","r":"'Rain' betyder regn. Sne hedder 'snow'."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder 'sne' på engelsk?","o":["snake","snow","sun","rain"],"a":"snow","r":"Sne hedder 'snow'. 'Snake' er en slange."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'door'?","o":["dør","gulv","vindue","tag"],"a":"dør","r":"'Door' betyder dør. Vindue hedder 'window'."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder 'seng' på engelsk?","o":["bad","bread","bag","bed"],"a":"bed","r":"Seng hedder 'bed'. 'Bag' er en taske."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'chair'?","o":["bord","sofa","stol","lampe"],"a":"stol","r":"'Chair' betyder stol. Bord hedder 'table'."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder 'blyant' på engelsk?","o":["pen","pencil","paper","ruler"],"a":"pencil","r":"Blyant hedder 'pencil'. 'Pen' er en kuglepen, og 'ruler' er en lineal."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'bag'?","o":["taske","bog","bad","bamse"],"a":"taske","r":"'Bag' betyder taske. En skoletaske hedder 'school bag'."},
{"g":3,"b":1,"k":"h","q":"Hvad siger man på engelsk, når man går hjem fra en ven?","o":["Hello!","Good morning!","Thank you!","Goodbye!"],"a":"Goodbye!","r":"'Goodbye' eller 'Bye' siger man, når man går. 'Hello' siger man, når man kommer."},
{"g":3,"b":1,"k":"h","q":"Hvad betyder 'yes'?","o":["nej","måske","ja","hej"],"a":"ja","r":"'Yes' betyder ja. Nej hedder 'no'."},
{"g":3,"b":1,"k":"h","q":"Hvad betyder 'no'?","o":["ja","nej","nu","ny"],"a":"nej","r":"'No' betyder nej. Ja hedder 'yes'."},
{"g":3,"b":1,"k":"h","q":"Hvad betyder 'please', når man beder om noget?","o":["vær så venlig","tak","undskyld","farvel"],"a":"vær så venlig","r":"'Please' gør en bøn høflig: 'Water, please' = vand, tak / vær så venlig."},
{"g":3,"b":1,"k":"h","q":"Hvad siger man på engelsk, hvis man kommer til at skubbe til nogen?","o":["Hello!","Yes!","Good night!","Sorry!"],"a":"Sorry!","r":"'Sorry' betyder undskyld. Det siger man, når man har gjort noget forkert."},
{"g":3,"b":1,"k":"h","q":"Hvad betyder 'Good night'?","o":["Godmorgen","Goddag","Godnat","Godt nytår"],"a":"Godnat","r":"'Night' betyder nat, så 'Good night' er godnat."},
{"g":3,"b":1,"k":"h","q":"Hvad betyder 'Hi'?","o":["Hvad","Hej","Hvem","Høj"],"a":"Hej","r":"'Hi' er en kort måde at sige hej på — ligesom 'Hello'."},
{"g":3,"b":1,"k":"h","q":"Hvad betyder 'Happy birthday!'?","o":["Tillykke med fødselsdagen!","Glædelig jul!","Godt nytår!","God weekend!"],"a":"Tillykke med fødselsdagen!","r":"'Birthday' er fødselsdag, og 'happy birthday' er tillykke med fødselsdagen."},
{"g":3,"b":1,"k":"h","q":"Hvad betyder 'Merry Christmas!'?","o":["Godt nytår!","God påske!","Tillykke!","Glædelig jul!"],"a":"Glædelig jul!","r":"'Christmas' er jul. 'Merry Christmas' = glædelig jul."},
{"g":3,"b":1,"k":"h","q":"Hvad betyder 'I am nine years old'?","o":["Jeg har ni venner","Jeg bor i nummer ni","Jeg er ni år gammel","Jeg går i 9. klasse"],"a":"Jeg er ni år gammel","r":"'Years old' fortæller alder: 'I am nine years old' = jeg er ni år gammel."},
{"g":3,"b":1,"k":"g","q":"Hvilket ord mangler? 'I ___ a girl.'","o":["is","am","are","have"],"a":"am","r":"Med 'I' (jeg) bruger man 'am': I am = jeg er."},
{"g":3,"b":1,"k":"g","q":"Hvad er flertal af 'dog' (flere hunde)?","o":["dogs","doges","dog","doggs"],"a":"dogs","r":"Man sætter bare -s på: one dog, two dogs."},
{"g":3,"b":1,"k":"g","q":"Hvilket ord mangler? 'It ___ a cat.'","o":["am","are","have","is"],"a":"is","r":"Med 'it' (den/det) bruger man 'is': It is a cat = det er en kat."},
{"g":3,"b":1,"k":"g","q":"Hvad er flertal af 'car' (flere biler)?","o":["cares","carz","cars","car"],"a":"cars","r":"Man sætter -s på: one car, three cars."},
{"g":3,"b":1,"k":"l","q":"Læs: 'I have a big dog.' Hvordan er hunden?","o":["lille","stor","sort","glad"],"a":"stor","r":"'Big' betyder stor. Personen har en stor hund."},
{"g":3,"b":1,"k":"l","q":"Læs: 'The cat is black.' Hvilken farve har katten?","o":["sort","hvid","rød","brun"],"a":"sort","r":"'Black' betyder sort. Katten er sort."},
{"g":3,"b":1,"k":"l","q":"Læs: 'My name is Ali. I am eight.' Hvor gammel er Ali?","o":["7 år","9 år","10 år","8 år"],"a":"8 år","r":"'Eight' er 8. Ali er otte år."},
{"g":3,"b":1,"k":"l","q":"Læs: 'I like apples.' Hvad kan personen lide?","o":["bananer","appelsiner","æbler","pærer"],"a":"æbler","r":"'Apples' betyder æbler. 'I like' = jeg kan lide."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder 'en sko' på engelsk?","o":["a sock","a shoe","a shirt","a hat"],"a":"a shoe","r":"En sko hedder 'a shoe'. 'Sock' er en sok, og 'shirt' er en skjorte."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'hat'?","o":["hat","hår","hånd","hus"],"a":"hat","r":"'Hat' betyder hat — det er det samme ord som på dansk."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder 'jakke' på engelsk?","o":["shirt","sock","dress","jacket"],"a":"jacket","r":"Jakke hedder 'jacket'. 'Dress' er en kjole."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'teddy bear'?","o":["dukke","robot","bamse","bold"],"a":"bamse","r":"En 'teddy bear' er en bamse. Dukke hedder 'doll'."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder 'dukke' på engelsk?","o":["ball","doll","dog","duck"],"a":"doll","r":"Dukke hedder 'doll'. 'Duck' er en and."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'new'?","o":["ny","gammel","nu","næste"],"a":"ny","r":"'New' betyder ny. Det modsatte er 'old' — gammel."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'sad'?","o":["glad","sur","træt","ked af det"],"a":"ked af det","r":"'Sad' betyder ked af det. Glad hedder 'happy'."},
{"g":3,"b":1,"k":"o","q":"Hvad hedder 'løve' på engelsk?","o":["line","love","lion","tiger"],"a":"lion","r":"Løve hedder 'lion'. 'Love' betyder kærlighed."},
{"g":3,"b":1,"k":"o","q":"Hvad betyder 'elephant'?","o":["løve","elefant","giraf","abe"],"a":"elefant","r":"'Elephant' betyder elefant. Abe hedder 'monkey'."},
{"g":3,"b":2,"k":"o","q":"Hvad hedder 'tirsdag' på engelsk?","o":["Thursday","Tuesday","Monday","Saturday"],"a":"Tuesday","r":"Tirsdag = Tuesday. Torsdag = Thursday — de to forveksles tit."},
{"g":3,"b":2,"k":"o","q":"Hvad hedder 'fredag' på engelsk?","o":["Friday","Saturday","Sunday","Thursday"],"a":"Friday","r":"Fredag = Friday. Ugedage skrives altid med stort på engelsk."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'Saturday'?","o":["søndag","fredag","torsdag","lørdag"],"a":"lørdag","r":"'Saturday' er lørdag. Søndag hedder 'Sunday'."},
{"g":3,"b":2,"k":"o","q":"Hvad hedder 'torsdag' på engelsk?","o":["Tuesday","Friday","Thursday","Wednesday"],"a":"Thursday","r":"Torsdag = Thursday. Det starter med 'th', ligesom 'Thor' — Thors dag."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'Sunday'?","o":["lørdag","søndag","mandag","fredag"],"a":"søndag","r":"'Sunday' er søndag — solens dag (sun = sol)."},
{"g":3,"b":2,"k":"o","q":"Hvad hedder tallet 11 på engelsk?","o":["eleven","twelve","seven","one"],"a":"eleven","r":"11 hedder 'eleven'. 12 hedder 'twelve'."},
{"g":3,"b":2,"k":"o","q":"Hvad hedder tallet 13 på engelsk?","o":["thirty","three","twenty","thirteen"],"a":"thirteen","r":"13 = thirteen. 30 = thirty — lyt efter slutningen '-teen'."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'fifteen'?","o":["50","5","15","14"],"a":"15","r":"'Fifteen' er 15. Tal fra 13 til 19 ender på '-teen'."},
{"g":3,"b":2,"k":"o","q":"Hvad hedder tallet 18 på engelsk?","o":["eighty","eighteen","eight","nineteen"],"a":"eighteen","r":"18 = eighteen. 80 = eighty."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'sixteen'?","o":["16","60","6","17"],"a":"16","r":"'Sixteen' er 16. 60 hedder 'sixty'."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'grandma'?","o":["mor","tante","søster","bedstemor"],"a":"bedstemor","r":"'Grandma' er bedstemor. Bedstefar hedder 'grandpa'."},
{"g":3,"b":2,"k":"o","q":"Hvad hedder 'bedstefar' på engelsk?","o":["grandma","uncle","grandpa","dad"],"a":"grandpa","r":"Bedstefar = grandpa. 'Uncle' er onkel."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'family'?","o":["venner","familie","klasse","nabo"],"a":"familie","r":"'Family' betyder familie."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'friend'?","o":["ven","fjende","fremmed","familie"],"a":"ven","r":"'Friend' betyder ven. 'Best friend' er bedste ven."},
{"g":3,"b":2,"k":"o","q":"Hvad hedder 'arm' på engelsk?","o":["ear","leg","hand","arm"],"a":"arm","r":"Arm hedder 'arm' — det samme ord som på dansk."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'leg'?","o":["læbe","leg","ben","lår"],"a":"ben","r":"'Leg' betyder ben — ikke at lege! At lege hedder 'play'."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'hair'?","o":["hare","hår","hjerte","hals"],"a":"hår","r":"'Hair' betyder hår. Hjerte hedder 'heart'."},
{"g":3,"b":2,"k":"o","q":"Hvad hedder 'tand' på engelsk?","o":["tooth","toe","tongue","teeth"],"a":"tooth","r":"En tand = a tooth. Flere tænder = teeth."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'fridge'?","o":["komfur","ovn","vask","køleskab"],"a":"køleskab","r":"'Fridge' er et køleskab. Komfur hedder 'cooker' eller 'stove'."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'bathroom'?","o":["soveværelse","stue","badeværelse","køkken"],"a":"badeværelse","r":"'Bathroom' er badeværelset. 'Bath' betyder bad."},
{"g":3,"b":2,"k":"o","q":"Hvad hedder 'soveværelse' på engelsk?","o":["bathroom","bedroom","living room","garden"],"a":"bedroom","r":"Soveværelse = bedroom (bed = seng). Stue = living room."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'garden'?","o":["have","garage","gård","gardin"],"a":"have","r":"'Garden' betyder have. Gardin hedder 'curtain'."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'window'?","o":["vind","væg","dør","vindue"],"a":"vindue","r":"'Window' betyder vindue. Væg hedder 'wall'."},
{"g":3,"b":2,"k":"o","q":"Hvad hedder 'gulerod' på engelsk?","o":["cabbage","potato","carrot","corn"],"a":"carrot","r":"Gulerod = carrot. Kartoffel = potato."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'potato'?","o":["tomat","kartoffel","pære","løg"],"a":"kartoffel","r":"'Potato' betyder kartoffel. 'Chips' laves af kartofler."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'chicken'?","o":["kylling","kirke","ko","køkken"],"a":"kylling","r":"'Chicken' betyder kylling eller høne."},
{"g":3,"b":2,"k":"o","q":"Hvad hedder 'appelsin' på engelsk?","o":["apple","lemon","grape","orange"],"a":"orange","r":"Appelsin = orange. Samme ord som farven orange."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'juice'?","o":["suppe","sukker","saft eller juice","salt"],"a":"saft eller juice","r":"'Juice' er juice eller saft — f.eks. 'orange juice'."},
{"g":3,"b":2,"k":"o","q":"Hvad hedder 'suppe' på engelsk?","o":["soap","soup","salt","sugar"],"a":"soup","r":"Suppe = soup. Pas på: 'soap' er sæbe!"},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'breakfast'?","o":["morgenmad","frokost","aftensmad","mellemmåltid"],"a":"morgenmad","r":"'Breakfast' er morgenmad. Frokost = lunch, aftensmad = dinner."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'lunch'?","o":["morgenmad","aftensmad","kage","frokost"],"a":"frokost","r":"'Lunch' er frokost. Madpakke hedder 'packed lunch'."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'run'?","o":["ryste","rulle","løbe","ride"],"a":"løbe","r":"'Run' betyder løbe. 'I run fast' = jeg løber hurtigt."},
{"g":3,"b":2,"k":"o","q":"Hvad hedder 'hoppe' på engelsk?","o":["run","jump","swim","sit"],"a":"jump","r":"Hoppe = jump. Svømme = swim."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'swim'?","o":["svømme","svinge","synge","sove"],"a":"svømme","r":"'Swim' betyder svømme. Synge hedder 'sing'."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'sleep'?","o":["slippe","slå","sidde","sove"],"a":"sove","r":"'Sleep' betyder sove. 'Go to sleep' = gå i seng og sove."},
{"g":3,"b":2,"k":"o","q":"Hvad hedder 'synge' på engelsk?","o":["sit","sink","sing","swing"],"a":"sing","r":"Synge = sing. 'Sit' betyder sidde."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'eat'?","o":["drikke","spise","lege","læse"],"a":"spise","r":"'Eat' betyder spise. Drikke hedder 'drink'."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'read'?","o":["læse","ride","rød","regne"],"a":"læse","r":"'Read' betyder læse. 'I read a book' = jeg læser en bog."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'play'?","o":["plante","betale","pleje","lege eller spille"],"a":"lege eller spille","r":"'Play' betyder lege eller spille: 'play football' = spille fodbold."},
{"g":3,"b":2,"k":"o","q":"Hvad hedder 'abe' på engelsk?","o":["money","donkey","monkey","mouse"],"a":"monkey","r":"Abe = monkey. 'Money' er penge, og 'donkey' er et æsel."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'bear'?","o":["bær","bjørn","øl","bi"],"a":"bjørn","r":"'Bear' betyder bjørn. Bær hedder 'berry'."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'frog'?","o":["frø","fisk","fugl","frugt"],"a":"frø","r":"'Frog' betyder frø. Frugt hedder 'fruit'."},
{"g":3,"b":2,"k":"o","q":"Hvad hedder 'slange' på engelsk?","o":["snail","snow","shark","snake"],"a":"snake","r":"Slange = snake. 'Snail' er en snegl, 'shark' er en haj."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'small'?","o":["stor","smal","lille","sød"],"a":"lille","r":"'Small' betyder lille. Det modsatte er 'big'."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'fast'?","o":["fast","hurtig","langsom","fed"],"a":"hurtig","r":"'Fast' betyder hurtig på engelsk. Langsom hedder 'slow'."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'old'?","o":["gammel","ny","ung","kold"],"a":"gammel","r":"'Old' betyder gammel. Ung hedder 'young'."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'funny'?","o":["fin","sur","fræk","sjov"],"a":"sjov","r":"'Funny' betyder sjov. 'A funny joke' = en sjov vits."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'sock'?","o":["sko","sæk","sok","sukker"],"a":"sok","r":"'Sock' betyder sok. Sko hedder 'shoe'."},
{"g":3,"b":2,"k":"o","q":"Hvad hedder 'kjole' på engelsk?","o":["dish","dress","desk","door"],"a":"dress","r":"Kjole = dress. 'Desk' er et skrivebord."},
{"g":3,"b":2,"k":"o","q":"Hvad betyder 'trousers'?","o":["bukser","trøje","sko","strømper"],"a":"bukser","r":"'Trousers' betyder bukser (på amerikansk: 'pants')."},
{"g":3,"b":2,"k":"h","q":"Hvad betyder 'How are you?'","o":["Hvor er du?","Hvem er du?","Hvor gammel er du?","Hvordan har du det?"],"a":"Hvordan har du det?","r":"'How are you?' spørger, hvordan man har det. Man kan svare: 'I'm fine, thank you.'"},
{"g":3,"b":2,"k":"h","q":"Hvad betyder 'Nice to meet you'?","o":["Vi ses i morgen","Hvad hedder du?","Rart at møde dig","Godt gået"],"a":"Rart at møde dig","r":"Man siger 'Nice to meet you', når man møder en ny person."},
{"g":3,"b":2,"k":"h","q":"Hvad betyder 'Where do you live?'","o":["Hvad laver du?","Hvor bor du?","Hvornår kommer du?","Hvem bor du med?"],"a":"Hvor bor du?","r":"'Where' = hvor, 'live' = bor. Svar: 'I live in Denmark.'"},
{"g":3,"b":2,"k":"h","q":"Hvad betyder 'I live in Denmark'?","o":["Jeg bor i Danmark","Jeg elsker Danmark","Jeg rejser til Danmark","Jeg kommer fra Norge"],"a":"Jeg bor i Danmark","r":"'Live' betyder bo. 'I live in Denmark' = jeg bor i Danmark."},
{"g":3,"b":2,"k":"h","q":"Hvad betyder 'Well done!'?","o":["Godt nytår!","Skynd dig!","Pas på!","Godt gået!"],"a":"Godt gået!","r":"'Well done' siger man, når nogen har klaret noget godt."},
{"g":3,"b":2,"k":"h","q":"Hvad betyder 'Come here!'?","o":["Gå væk!","Sid ned!","Kom her!","Vent lidt!"],"a":"Kom her!","r":"'Come' betyder kom, og 'here' betyder her."},
{"g":3,"b":2,"k":"h","q":"Hvad betyder 'Sit down, please'?","o":["Rejs dig op, tak","Sæt dig ned, tak","Gå ud, tak","Ti stille, tak"],"a":"Sæt dig ned, tak","r":"'Sit down' betyder sæt dig ned. Rejs dig = 'stand up'."},
{"g":3,"b":2,"k":"h","q":"Hvad siger læreren, når man skal række hånden op?","o":["Put your hand up.","Put your hat on.","Give me your hand.","Wash your hands."],"a":"Put your hand up.","r":"'Put your hand up' = ræk hånden op. 'Hand' er hånd."},
{"g":3,"b":2,"k":"h","q":"Hvad betyder 'I don't know'?","o":["Jeg kan ikke lide det","Jeg vil ikke","Jeg har det ikke","Jeg ved det ikke"],"a":"Jeg ved det ikke","r":"'Know' betyder vide. 'I don't know' = jeg ved det ikke."},
{"g":3,"b":2,"k":"h","q":"Hvad betyder 'Let's play!'?","o":["Lad være!","Lad os spise!","Lad os lege!","Lad os gå hjem!"],"a":"Lad os lege!","r":"'Let's' betyder 'lad os', og 'play' betyder lege."},
{"g":3,"b":2,"k":"h","q":"Hvad svarer man høfligt på 'Thank you!'?","o":["Goodbye!","You're welcome!","I'm sorry!","Me too!"],"a":"You're welcome!","r":"'You're welcome' betyder 'selv tak' eller 'det var så lidt'."},
{"g":3,"b":2,"k":"h","q":"Hvad betyder 'Help!'?","o":["Hjælp!","Hej!","Stop!","Hurra!"],"a":"Hjælp!","r":"'Help' betyder hjælp. 'Can you help me?' = kan du hjælpe mig?"},
{"g":3,"b":2,"k":"g","q":"Hvilket ord mangler? 'You ___ my friend.'","o":["am","is","be","are"],"a":"are","r":"Med 'you' (du) bruger man 'are': You are my friend = du er min ven."},
{"g":3,"b":2,"k":"g","q":"Hvilket ord mangler? 'She ___ a cat.'","o":["have","is","has","are"],"a":"has","r":"Med 'he', 'she' og 'it' bruger man 'has': She has a cat = hun har en kat."},
{"g":3,"b":2,"k":"g","q":"Hvilket ord mangler? 'We ___ happy.'","o":["is","are","am","has"],"a":"are","r":"Med 'we' (vi) bruger man 'are': We are happy = vi er glade."},
{"g":3,"b":2,"k":"g","q":"Hvad er flertal af 'book' (flere bøger)?","o":["books","bookes","book","bookies"],"a":"books","r":"Man sætter -s på: one book, two books."},
{"g":3,"b":2,"k":"g","q":"Hvad er flertal af 'box' (flere kasser)?","o":["boxs","box","boxies","boxes"],"a":"boxes","r":"Efter x tilføjer man -es: one box, two boxes."},
{"g":3,"b":2,"k":"g","q":"Hvad betyder 'he'?","o":["hun","det","han","vi"],"a":"han","r":"'He' betyder han. Hun hedder 'she'."},
{"g":3,"b":2,"k":"g","q":"Hvad betyder 'they'?","o":["vi","de","du","den"],"a":"de","r":"'They' betyder de. 'They are my friends' = de er mine venner."},
{"g":3,"b":2,"k":"g","q":"Hvilket ord mangler? 'I ___ swim.' (jeg kan svømme)","o":["can","am","has","is"],"a":"can","r":"'Can' betyder kan: I can swim = jeg kan svømme."},
{"g":3,"b":2,"k":"g","q":"Hvilket ord betyder 'min'?","o":["me","I","you","my"],"a":"my","r":"'My' betyder min eller mit: my dog = min hund."},
{"g":3,"b":2,"k":"g","q":"Hvilket ord mangler? 'This is ___ dog.' (hans hund)","o":["her","he","his","him"],"a":"his","r":"'His' betyder hans: his dog = hans hund. 'Her' betyder hendes."},
{"g":3,"b":2,"k":"g","q":"Hvilket ord mangler? 'He ___ ten years old.'","o":["are","is","am","have"],"a":"is","r":"Med 'he' bruger man 'is'. På engelsk ER man sin alder: He is ten."},
{"g":3,"b":2,"k":"l","q":"Læs: 'Sam has a blue bike and a red ball.' Hvilken farve har cyklen?","o":["blå","rød","grøn","gul"],"a":"blå","r":"'A blue bike' = en blå cykel. Bolden er rød."},
{"g":3,"b":2,"k":"l","q":"Læs: 'Lily is sad. She lost her doll.' Hvorfor er Lily ked af det?","o":["Hun er syg","Hun er sulten","Hun har fået en dukke","Hun har mistet sin dukke"],"a":"Hun har mistet sin dukke","r":"'Lost' betyder mistede. Lily mistede sin dukke (doll)."},
{"g":3,"b":2,"k":"l","q":"Læs: 'I have three sisters and one brother.' Hvor mange søskende har personen?","o":["tre","en","fire","to"],"a":"fire","r":"Tre søstre + en bror = fire søskende."},
{"g":3,"b":2,"k":"l","q":"Læs: 'My cat sleeps on my bed.' Hvor sover katten?","o":["i haven","på sengen","på stolen","i køkkenet"],"a":"på sengen","r":"'On my bed' betyder på min seng."},
{"g":3,"b":2,"k":"l","q":"Læs: 'Today is Monday. Tomorrow is ___.' Hvilken dag mangler?","o":["Tuesday","Sunday","Friday","Wednesday"],"a":"Tuesday","r":"Efter mandag (Monday) kommer tirsdag (Tuesday)."},
{"g":3,"b":2,"k":"l","q":"Læs: 'Max likes milk, but he doesn't like juice.' Hvad kan Max IKKE lide?","o":["mælk","is","vand","juice"],"a":"juice","r":"'Doesn't like' betyder 'kan ikke lide'. Max kan ikke lide juice."},
{"g":3,"b":2,"k":"l","q":"Læs: 'It is cold. Put on your hat!' Hvorfor skal man tage hue på?","o":["Det regner","Det er varmt","Det er koldt","Det er mørkt"],"a":"Det er koldt","r":"'Cold' betyder koldt. Derfor skal man have hue (hat) på."},
{"g":3,"b":2,"k":"l","q":"Læs: 'The dog is under the table.' Hvor er hunden?","o":["på bordet","under bordet","ved døren","i sengen"],"a":"under bordet","r":"'Under' betyder under, og 'table' er bord."},
{"g":3,"b":2,"k":"l","q":"Læs: 'Emma can run, but she can't swim.' Hvad kan Emma IKKE?","o":["svømme","løbe","læse","synge"],"a":"svømme","r":"'Can't' betyder 'kan ikke'. Emma kan ikke svømme (swim)."},
{"g":3,"b":2,"k":"l","q":"Læs: 'I am hungry. Can I have a sandwich?' Hvad vil personen have?","o":["et glas vand","en bog","en bold","en sandwich"],"a":"en sandwich","r":"'Hungry' er sulten, og personen beder om en sandwich."}
]$$::jsonb) AS e
JOIN (VALUES
  ('o', 'ordforråd', 'recall', 'factual', 'surface_association'),
  ('h', 'hverdagsudtryk', 'comprehension', 'conceptual', 'surface_association'),
  ('g', 'grammatik', 'application', 'applied', 'overgeneralization'),
  ('l', 'læseforståelse', 'analysis', 'inferential', 'surface_association')
) AS m(k, concept, skill, dtype, mis) ON m.k = e->>'k';
