-- Section 147C — World War 2 Grade 7 Capacity Expansion
-- world_war_2, target_grade=7, is_active=true
-- Distribution: B1(2) + B2(4) + B3(6) + B4(5) + B5(3) = 20 questions
-- Topics: Blitzkrieg, Pearl Harbor, Nuremberg Laws, Operation Barbarossa,
--         collaboration vs resistance, Japan's role, Wannsee Conference,
--         Warsaw Ghetto Uprising, atomic bombs (factual), women on home front,
--         August 1943 breakdown consequences, Stalingrad turning point,
--         Churchill's leadership, ordinary perpetrators (Browning/Arendt),
--         Germany's division 1949, international bystanders/refugee refusal,
--         civilians in WW2 vs WW1, atomic bombs (ethical debate),
--         Milgram/obedience and Holocaust, democracy's fragility lesson
-- Before: B1=6 B2=7 B3=7 B4=5 B5=0 → 25 active
-- After:  B1=8 B2=11 B3=13 B4=10 B5=3 → 47 active
-- Uses unique dollar-quoting throughout.

-- ─── BAND 1 (2 questions) ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c1q${"question":"Hvad var Blitzkrieg og hvordan brugte Tyskland det i begyndelsen af 2. Verdenskrig?","options":["En lynhurtig angrebsstrategi der kombinerede tanks, fly og infanteri for at overrumple fjenden inden de kunne organisere forsvar — brugt mod Polen (1939) og Frankrig (1940)","En defensiv strategi som Tyskland brugte til at beskytte sine egne grænser mod angreb fra vest","En strategi der udelukkende baserede sig på bombefly uden brug af landstyrker","En diplomatisk strategi der brugte trusler om krig frem for faktisk kamp"],"correct":"En lynhurtig angrebsstrategi der kombinerede tanks, fly og infanteri for at overrumple fjenden inden de kunne organisere forsvar — brugt mod Polen (1939) og Frankrig (1940)","accepted_answers":["En lynhurtig angrebsstrategi der kombinerede tanks, fly og infanteri for at overrumple fjenden inden de kunne organisere forsvar — brugt mod Polen (1939) og Frankrig (1940)"],"review_text":"Blitzkrieg betyder lynkrig på tysk. Strategien kombinerede pansrede køretøjer, motoriseret infanteri og kampfly i hurtige gennembrud der omringede og isolerede fjenden. Polen faldt på tre uger i september 1939. Frankrig, som havde klargjort sig mod en gentagelse af 1. Verdenskrigs skyttegravskrig, kolossede på seks uger i maj-juni 1940. Blitzkrieg var revolutionerende fordi den brød med den statiske frontkrigsførelse og viste at mobilitet og koordination kunne besejre numerisk overlegne styrker."}$c1q$::jsonb,
  'mc','short',$c1m${"concepts":["Blitzkrieg","lynkrig","tanks","Polen","Frankrig","strategi"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"recognition","insight_type":"concept_clarification","challenge_role":"entry_level","domain":"world_war_2"}$c1m$::jsonb,
  'mc_single',1,'auto',true,'world_war_2',7,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c2q${"question":"Hvad skete der ved Pearl Harbor den 7. december 1941 og hvad var konsekvensen?","options":["Japan angreb overraskende den amerikanske flådebase på Hawaii — det fik USA til at erklære krig mod Japan og dermed officielt at træde ind i 2. Verdenskrig","USA angreb den japanske flåde for at forhindre Japan i at angribe Kina","Angrebet på Pearl Harbor var en fejltagelse fra Japans side som ikke fik nogen krigsmæssig konsekvens","Den tyske flåde angreb Pearl Harbor for at trække USA ind på Tysklands side i krigen"],"correct":"Japan angreb overraskende den amerikanske flådebase på Hawaii — det fik USA til at erklære krig mod Japan og dermed officielt at træde ind i 2. Verdenskrig","accepted_answers":["Japan angreb overraskende den amerikanske flådebase på Hawaii — det fik USA til at erklære krig mod Japan og dermed officielt at træde ind i 2. Verdenskrig"],"review_text":"Den 7. december 1941 angreb japanske bombefly overraskende den amerikanske flådebase på Hawaii. 2.403 amerikanere omkom, 19 krigsskibe blev sænket eller beskadiget. Dagen efter erklærede USA krig mod Japan, og dage senere erklærede Tyskland og Italien krig mod USA. Det var vendepunktet der forvandlede en europæisk krig til en egentlig verdenskrig med USA's enorme industrielle og militære ressourcer på de Allieredes side. Roosevelt kaldte det en dato der ville leve i vanære."}$c2q$::jsonb,
  'mc','short',$c2m${"concepts":["Pearl Harbor","Japan","USA","krigserklaering","Stillehavet","1941"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"recognition","insight_type":"concept_clarification","challenge_role":"entry_level","domain":"world_war_2"}$c2m$::jsonb,
  'mc_single',1,'auto',true,'world_war_2',7,1
);

-- ─── BAND 2 (4 questions) ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c3q${"question":"Hvad var de såkaldte Nürnberg-love fra 1935 og hvad betød de for jøder i Tyskland?","options":["Racistiske love der fratog tyske jøder deres statsborgerskab og forbød ægteskab og forhold mellem jøder og ikke-jøder — et centralt juridisk skridt i nazisternes systematiske udelukkelse af jøderne","Love der bestemte at alle jøder i Europa skulle deporteres til Palæstina med det samme","Love der forbød jøder at udøve handel men tillod dem alle øvrige rettigheder som borgere","Internationale love vedtaget af Folkeforbundet der forsøgte at beskytte jødiske mindretal i Europa"],"correct":"Racistiske love der fratog tyske jøder deres statsborgerskab og forbød ægteskab og forhold mellem jøder og ikke-jøder — et centralt juridisk skridt i nazisternes systematiske udelukkelse af jøderne","accepted_answers":["Racistiske love der fratog tyske jøder deres statsborgerskab og forbød ægteskab og forhold mellem jøder og ikke-jøder — et centralt juridisk skridt i nazisternes systematiske udelukkelse af jøderne"],"review_text":"Nürnberg-lovene fra september 1935 var et afgørende vendepunkt i nazisternes jødeforfølgelse. Den ene lov fratog jøder tysk statsborgerskab — de blev statsborgere af anden klasse. Den anden forbød ægteskab og seksuelle forhold mellem jøder og ikke-jøder. Lovene var ikke spontane — de var en del af en systematisk strategi for at isolere og udelukke jøder fra det tyske samfund. De kom fire år inden massemordene begyndte og viser at Holocaust ikke var improviseret men et gradvist eskalerende forfølgelsesprogram."}$c3q$::jsonb,
  'mc','short',$c3m${"concepts":["Nürnberg-love","statsborgerskab","racisme","juridisk udelukkelse","jødeforfølgelse","1935"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"concept_clarification","challenge_role":"reinforcement","domain":"world_war_2"}$c3m$::jsonb,
  'mc_single',2,'auto',true,'world_war_2',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c4q${"question":"Hvad var Operation Barbarossa (1941) og hvorfor er den en af krigens vigtigste begivenheder?","options":["Tysklands invasion af Sovjetunionen i juni 1941 — den åbnede Østfronten der blev krigens blodigste kampzone og kostede anslået 27 millioner sovjetiske liv samt brød den tysk-sovjetiske ikke-angrebspagt","Det britiske modangreb der befriede Vesteuropa fra den tyske besættelse og åbnede en ny front","Den japanske invasion af Kina som udvidede krigen fra Europa til Asien og Stillehavet","Alliancen mellem Sovjet og USA om fælles angreb på Japan i Stillehavet"],"correct":"Tysklands invasion af Sovjetunionen i juni 1941 — den åbnede Østfronten der blev krigens blodigste kampzone og kostede anslået 27 millioner sovjetiske liv samt brød den tysk-sovjetiske ikke-angrebspagt","accepted_answers":["Tysklands invasion af Sovjetunionen i juni 1941 — den åbnede Østfronten der blev krigens blodigste kampzone og kostede anslået 27 millioner sovjetiske liv samt brød den tysk-sovjetiske ikke-angrebspagt"],"review_text":"I august 1939 underskrev Hitler og Stalin en ikke-angrebspagt — til omverdenens overraskelse. Den 22. juni 1941 brød Hitler pagten og sendte tre millioner tyske soldater ind i Sovjet i historiens hidtil største militære operation. I begyndelsen gik det hurtigt — men Sovjet var enormt og kæmpede med desperat beslutsomhed. Østfronten udviklede sig til en blodig udmattelseskrig. Stalingrad (1942-43), Kursk (1943) og til sidst Berlin (1945) — Østfronten kostede Sovjet anslået 27 millioner liv og var den krig der i høj grad knuste Nazityskland."}$c4q$::jsonb,
  'mc','short',$c4m${"concepts":["Operation Barbarossa","Østfronten","Sovjet","ikke-angrebspagt","1941","masseofre"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"concept_clarification","challenge_role":"reinforcement","domain":"world_war_2"}$c4m$::jsonb,
  'mc_single',2,'auto',true,'world_war_2',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c5q${"question":"Hvad kendetegnede forholdet mellem samarbejde og modstand i de tyskkontrollerede lande under 2. Verdenskrig?","options":["I de fleste besatte lande tilpassede flertallet sig hverdagen mens et mindretal enten samarbejdede aktivt med nazisterne eller aktivt modstod dem — forholdet varierede fra land til land afhængig af situation og politisk kultur","I alle besatte lande rejste befolkningerne sig øjeblikkeligt i aktiv væbnet modstand mod nazisterne","I alle besatte lande samarbejdede befolkningerne fuldt ud med nazisterne fordi de sympatiserede med deres ideologi","Samarbejde og modstand forekom kun i Danmark — alle andre besatte lande var fuldt neutrale"],"correct":"I de fleste besatte lande tilpassede flertallet sig hverdagen mens et mindretal enten samarbejdede aktivt med nazisterne eller aktivt modstod dem — forholdet varierede fra land til land afhængig af situation og politisk kultur","accepted_answers":["I de fleste besatte lande tilpassede flertallet sig hverdagen mens et mindretal enten samarbejdede aktivt med nazisterne eller aktivt modstod dem — forholdet varierede fra land til land afhængig af situation og politisk kultur"],"review_text":"Besatte landes befolkninger var sjældent entydigt enten modstandere eller samarbejdspartnere. I Frankrig var der aktiv kollaboration (Vichy-regeringen) men også stærk modstandsbevægelse (Résistance). I Norge var Quisling-regeringen kollaborationistisk mens store dele af befolkningen modstod. I Nederlandene deporteredes 75% af de jødiske borgere — delvist med lokale myndigheders medvirken. I Danmark reddede befolkningen størstedelen af de jødiske borgere. De fleste steder var den store midtergruppe tilpassede mennesker der forsøgte at overleve hverdagen — hverken helte eller forrædere."}$c5q$::jsonb,
  'mc','short',$c5m${"concepts":["samarbejde","modstand","besatte lande","kollaboration","Résistance","hverdagen"],"misconception_type":"overgeneralization","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_2"}$c5m$::jsonb,
  'mc_single',2,'auto',true,'world_war_2',7,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c6q${"question":"Hvilken rolle spillede Japan i 2. Verdenskrig og hvad var dets vigtigste mål?","options":["Japan kæmpede på Aksemagternes side og forsøgte at opbygge et koloniimperium i Asien og Stillehavet — det invaderede Kina, store dele af Sydøstasien og angreb USA ved Pearl Harbor","Japan kæmpede på de Allieredes side og bidrog til befrielsen af Europa fra nazistisk besættelse","Japan var neutral i 2. Verdenskrig og deltog udelukkende som humanitær hjælpeorganisation","Japan kæmpede kun i Europa og spillede ingen rolle i Stillehavet eller Asien"],"correct":"Japan kæmpede på Aksemagternes side og forsøgte at opbygge et koloniimperium i Asien og Stillehavet — det invaderede Kina, store dele af Sydøstasien og angreb USA ved Pearl Harbor","accepted_answers":["Japan kæmpede på Aksemagternes side og forsøgte at opbygge et koloniimperium i Asien og Stillehavet — det invaderede Kina, store dele af Sydøstasien og angreb USA ved Pearl Harbor"],"review_text":"2. Verdenskrig var ikke kun en europæisk krig. Japan var en af de tre Aksemagter (sammen med Tyskland og Italien) og havde ambitioner om at opbygge et Stor-Østasiatisk Velstandssfære — et japansk-domineret imperium i Asien. Japan havde allerede invaderet Kina i 1937. Angrebet på Pearl Harbor (1941) udløste Stillehavskrigen mod USA. Japan erobrede Filippinerne, Indonesien, Burma, Malaya og mange Stillehavsøer. Krigen i Asien og Stillehavet kostede anslået 20 millioner asiatiske civile livet."}$c6q$::jsonb,
  'mc','short',$c6m${"concepts":["Japan","Aksemagter","Stillehavskrigen","Pearl Harbor","koloniimperium","Asien"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"concept_clarification","challenge_role":"reinforcement","domain":"world_war_2"}$c6m$::jsonb,
  'mc_single',2,'auto',true,'world_war_2',7,2
);

-- ─── BAND 3 (6 questions) ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c7q${"question":"Hvad var Wannsee-konferencen i januar 1942 og hvad viser den om Holocaust?","options":["En hemmelig konference i Berlin hvor naziledere koordinerede den systematiske udryddelse af alle europæiske jøder — den viser at Holocaust krævede bureaukratisk planlægning og bred embedsmandsdeltagelse ikke kun SS-fanatikere","Et fredsforhandlingsmøde hvor Hitler og de allierede ledere diskuterede en mulig våbenhvile","En international konference i 1942 hvor de allierede planlagde invasionen af Normandiet","Et møde i Berlin hvor tyske generaler planlagde det militære angreb på Sovjetunionen"],"correct":"En hemmelig konference i Berlin hvor naziledere koordinerede den systematiske udryddelse af alle europæiske jøder — den viser at Holocaust krævede bureaukratisk planlægning og bred embedsmandsdeltagelse ikke kun SS-fanatikere","accepted_answers":["En hemmelig konference i Berlin hvor naziledere koordinerede den systematiske udryddelse af alle europæiske jøder — den viser at Holocaust krævede bureaukratisk planlægning og bred embedsmandsdeltagelse ikke kun SS-fanatikere"],"review_text":"Den 20. januar 1942 mødtes 15 højtplacerede nazister og embedsmænd i en villa ved Wannsee-søen nær Berlin. Formålet var at koordinere den systematiske udryddelse af alle 11 millioner europæiske jøder — det der kaldtes Endlösung, den endelige løsning. Mødet varede ca. 90 minutter. Protokollen fra mødet overlevede krigen. Den er chokerende i sin bureaukratiske, nøgterne tone: massemord planlagt som et administrativt problem. Wannsee viser at Holocaust ikke var improviseret galskab men systematisk planlægning med bred embedsmandsdeltagelse."}$c7q$::jsonb,
  'mc','short',$c7m${"concepts":["Wannsee","Endlösung","koordinering","bureaukrati","planlægning","embedsmænd"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"challenge","domain":"world_war_2"}$c7m$::jsonb,
  'mc_single',3,'auto',true,'world_war_2',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c8q${"question":"Hvad var Warszawagetto-oprøret (april-maj 1943) og hvad viser det om jøders reaktion på naziforfølgelsen?","options":["Jødiske modstandskæmpere i den lukkede ghetto i Warszawa rejste sig i bevæbnet oprør mod deportation til udryddelseslejre — det varede næsten en måned og viser at jøder aktivt modstod nazisterne selvom modstanden til sidst blev slået ned","Et polsk militærisk oprør der lykkedes med at befri Warszawa fra den tyske besættelse i 1943","Et oprør der beviste at jøderne var pacifistiske og aldrig forsøgte at modstå deportationerne","Et opgør mellem kommunistiske og nationalistiske polske grupper om kontrollen over Warszawa"],"correct":"Jødiske modstandskæmpere i den lukkede ghetto i Warszawa rejste sig i bevæbnet oprør mod deportation til udryddelseslejre — det varede næsten en måned og viser at jøder aktivt modstod nazisterne selvom modstanden til sidst blev slået ned","accepted_answers":["Jødiske modstandskæmpere i den lukkede ghetto i Warszawa rejste sig i bevæbnet oprør mod deportation til udryddelseslejre — det varede næsten en måned og viser at jøder aktivt modstod nazisterne selvom modstanden til sidst blev slået ned"],"review_text":"I april 1943 besluttede de tyske myndigheder at deportere ghettoen resterende 60.000 jøder til Treblinka-udryddelseslejren. En lille gruppe modstandskæmpere med hjemmelavede og smuglede våben valgte at kæmpe. De tyske tropper forventede at rydde ghettoen på tre dage — det tog næsten fire uger. Oprøret er et vigtigt historisk eksempel: det modviser myten om at jøder gik passivt i udryddelse. Det skete under ekstreme odds — omringet, underbevaebnet, ingen udefra kom til undsætning. Til sidst brændte tyserne ghettoen systematisk ned."}$c8q$::jsonb,
  'mc','short',$c8m${"concepts":["Warszawa-ghetto","oprør","modstand","deportation","Treblinka","aktiv modstand"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"challenge","domain":"world_war_2"}$c8m$::jsonb,
  'mc_single',3,'auto',true,'world_war_2',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c9q${"question":"Hvad var konsekvenserne af USA's atombombeangreb på Hiroshima og Nagasaki i august 1945?","options":["Angrebene dræbte anslået 130.000-226.000 mennesker og fik Japan til at overgive sig den 15. august 1945 — det afsluttede 2. Verdenskrig men åbnede en ny æra med atomvåben som global magtfaktor","Angrebene mislykkedes militært og Japan overgav sig først måneder senere efter en konventionel landinvasion","Angrebene dræbte udelukkende japanske soldater og efterlod den civile befolkning uskadet","USA brugte atombomber i Europa for at tvinge Nazityskland til at kapitulere i 1945"],"correct":"Angrebene dræbte anslået 130.000-226.000 mennesker og fik Japan til at overgive sig den 15. august 1945 — det afsluttede 2. Verdenskrig men åbnede en ny æra med atomvåben som global magtfaktor","accepted_answers":["Angrebene dræbte anslået 130.000-226.000 mennesker og fik Japan til at overgive sig den 15. august 1945 — det afsluttede 2. Verdenskrig men åbnede en ny æra med atomvåben som global magtfaktor"],"review_text":"Den 6. august 1945 kastede USA en atombombe over Hiroshima — en enkelt bombe der lagde en hel by øde. Den 9. august faldt en anden over Nagasaki. Titusinder døde øjeblikkeligt; mange tusinde mere døde i månederne og årene efter af strålingsskader. Den 15. august erklærede den japanske kejser Hirohito landets overgivelse. Det var første og hidtil eneste gang atomvåben er brugt i krig. Angrebene afsluttede verdenskrigens blodigste kapitel men markerede begyndelsen på den atomare tidsalder og Den Kolde Krig."}$c9q$::jsonb,
  'mc','short',$c9m${"concepts":["Hiroshima","Nagasaki","atombombe","Japan","overgivelse","atomalder"],"misconception_type":"factual_error","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"concept_clarification","challenge_role":"challenge","domain":"world_war_2"}$c9m$::jsonb,
  'mc_single',3,'auto',true,'world_war_2',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c10q${"question":"Hvilken rolle spillede kvinder på hjemmefronten i lande som Storbritannien og USA under 2. Verdenskrig?","options":["Kvinder overtog i store tal fabriksarbejde og krigsindustrien mens mænd var ved fronten — det ændrede samfundets syn på kvinders evner og bidrog til efterkrigstidens krav om ligestilling","Kvinder spillede ingen rolle under 2. Verdenskrig da de udelukkende opholdt sig i hjemmet","Kvinder kæmpede som soldater på alle fronter ligesom mænd i alle de allierede nationer","Kvinder blev sendt ud af arbejdsmarkedet under krigen for at frigøre pladser til hjemvendte veteraner"],"correct":"Kvinder overtog i store tal fabriksarbejde og krigsindustrien mens mænd var ved fronten — det ændrede samfundets syn på kvinders evner og bidrog til efterkrigstidens krav om ligestilling","accepted_answers":["Kvinder overtog i store tal fabriksarbejde og krigsindustrien mens mænd var ved fronten — det ændrede samfundets syn på kvinders evner og bidrog til efterkrigstidens krav om ligestilling"],"review_text":"Da millioner af mænd blev indkaldt til fronten, opstod et akut arbejdskraftbehov i industri og service. Kvinder rykkede ind i fly- og ammunitionsfabrikker, som ingeniører, som sygeplejersker og i militærets støttefunktioner. I USA blev Rosie the Riveter et ikonisk billede på kvinders krigsindsats. I Storbritannien tjente over 640.000 kvinder i hjælpemilitære enheder. Erfaringen med at kvinder kunne klare teknisk og fysisk krævende arbejde underminerede mange forudfattede meninger og gav næring til efterkrigstidens feministiske bevægelse og krav om ligeløn."}$c10q$::jsonb,
  'mc','short',$c10m${"concepts":["kvinder","hjemmefront","fabriksarbejde","ligestilling","Rosie the Riveter","efterkrigstid"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"challenge","domain":"world_war_2"}$c10m$::jsonb,
  'mc_single',3,'auto',true,'world_war_2',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c11q${"question":"Hvad var de vigtigste konsekvenser da den danske samarbejdspolitik brød sammen i august 1943?","options":["Besaettelsesmagten overtog fuld kontrol og internerede den danske haer og flaade — og den tyske plan om at deportere de danske joder tre uger senere udlosdte den redningsaktion der forte 7.000 joder i sikkerhed i Sverige","Danmark erklærede krig mod Tyskland og sendte tropper til Vestfronten","Samarbejdspolitikken fortsatte uaendret frem til befrielsen i maj 1945","Den danske befolkning rejste sig i masseoprør og slog de tyske besaettelsesstyrker tilbage"],"correct":"Besaettelsesmagten overtog fuld kontrol og internerede den danske haer og flaade — og den tyske plan om at deportere de danske joder tre uger senere udlosdte den redningsaktion der forte 7.000 joder i sikkerhed i Sverige","accepted_answers":["Besaettelsesmagten overtog fuld kontrol og internerede den danske haer og flaade — og den tyske plan om at deportere de danske joder tre uger senere udlosdte den redningsaktion der forte 7.000 joder i sikkerhed i Sverige"],"review_text":"I august 1943 eskalerede modstandsbevæegelsen og strejker. Det tyske militær erklærede undtagelsestilstand, internerede den danske hær, søsatte og sænkede den danske flåde for at forhindre den i at flygte. Den danske regering gik af. I den nye situation besluttede nazisterne at deportere de ca. 7.000 danske jøder. Men lækagen af planen kombineret med et usædvanligt stærkt folkeligt engagement — fiskere, læger, naboer — fik størstedelen over Øresund til Sverige inden razzia-natten den 1.-2. oktober 1943. Augustoprøret og jøderedningen hænger tæt sammen."}$c11q$::jsonb,
  'mc','short',$c11m${"concepts":["augustoprøret","samarbejdspolitik","jøderedning","besaettelse","undtagelsestilstand","1943"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"challenge","domain":"world_war_2"}$c11m$::jsonb,
  'mc_single',3,'auto',true,'world_war_2',7,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c12q${"question":"Hvorfor betragtes slaget ved Stalingrad (1942-43) som et afgørende vendepunkt i 2. Verdenskrig?","options":["Det første store tyske militære nederlag: den tyske 6. Armé på over 300.000 mand kapitulerede — det viste at Wehrmacht kunne besejres og markerede overgangen fra tysk offensiv til defensiv på Østfronten","Det var det slag hvor USA for første gang kæmpede på land mod tyske tropper i Europa","Det var det slag der befriede Frankrig fra den tyske besættelse og åbnede en anden front mod vest","Stalingrad var kun et mindre slag og havde ingen afgørende militær betydning for krigens forløb"],"correct":"Det første store tyske militære nederlag: den tyske 6. Armé på over 300.000 mand kapitulerede — det viste at Wehrmacht kunne besejres og markerede overgangen fra tysk offensiv til defensiv på Østfronten","accepted_answers":["Det første store tyske militære nederlag: den tyske 6. Armé på over 300.000 mand kapitulerede — det viste at Wehrmacht kunne besejres og markerede overgangen fra tysk offensiv til defensiv på Østfronten"],"review_text":"Stalingrad (august 1942 — februar 1943) var en af historiens blodigste slag. Hitler beordrede den 6. Armé til at holde Stalingrad for enhver pris — det var ikke kun et strategisk mål men symbolsk (en by opkaldt efter Stalin). Sovjet indkredsede og afskar armeen. General von Paulus kapitulerede i februar 1943 med ca. 91.000 overlevende soldater. Det var et chok for det tyske folk der aldrig tidligere havde fået en storrformation til at kapitulere. Fra Stalingrad pressede Sovjet gradvist de tyske styrker tilbage mod Berlin. Krigen var ikke vundet — men det tyske momentum var knust."}$c12q$::jsonb,
  'mc','short',$c12m${"concepts":["Stalingrad","vendepunkt","Østfronten","6. Armé","kapitulation","offensiv til defensiv"],"misconception_type":"false_equivalence","cognitive_skill":"analysis","difficulty_type":"causal","insight_type":"perspective_shift","challenge_role":"challenge","domain":"world_war_2"}$c12m$::jsonb,
  'mc_single',3,'auto',true,'world_war_2',7,3
);

-- ─── BAND 4 (5 questions) ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c13q${"question":"Hvad var Winston Churchills historiske betydning som Storbritanniens leder i 2. Verdenskrig?","options":["Churchill holdt fast i britisk modstand i 1940 da presset for at søge forhandlingsfred med Hitler var størst — hans lederevner og retorik cementerede den politiske og folkelige vilje til at kæmpe og forhindrede et britisk forligsfredssøgning","Churchill koordinerede den britiske atombombeudvikling som var afgørende for krigens afslutning","Churchill var ubetydelig for krigens resultat — USA vandt krigen med britisk neutral opbakning","Churchill beordrede personligt D-dag og var ansvarlig for den militære planlægning af Normandiet-landgangen"],"correct":"Churchill holdt fast i britisk modstand i 1940 da presset for at søge forhandlingsfred med Hitler var størst — hans lederevner og retorik cementerede den politiske og folkelige vilje til at kæmpe og forhindrede et britisk forligsfredssøgning","accepted_answers":["Churchill holdt fast i britisk modstand i 1940 da presset for at søge forhandlingsfred med Hitler var størst — hans lederevner og retorik cementerede den politiske og folkelige vilje til at kæmpe og forhindrede et britisk forligsfredssøgning"],"review_text":"Da Frankrig faldt i juni 1940 var Churchill britisk premierminister siden to måneder. Indflydelsesrige stemmer i det britiske kabinet — herunder udenrigsminister Lord Halifax — pressede på for forhandlingsfred med Hitler. Churchill afviste kategorisk. I tre berømte taler sommeren 1940 sagde han bl.a. at briterne ville kæmpe på strandene og aldrig overgive sig. Om hans valg var rigtigt fra et rent rationelt perspektiv er historisk omdiskuteret — men det forhindrede et forlig der sandsynligvis ville have frigivet tyske ressourcer til at slå Sovjet og befæste Europa. Enkeltpersoners valg kan have historisk afgørende konsekvenser."}$c13q$::jsonb,
  'mc','short',$c13m${"concepts":["Churchill","britisk modstand","forhandlingsfred","retorik","lederskab","1940"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"analytical_challenge","domain":"world_war_2"}$c13m$::jsonb,
  'mc_single',4,'auto',true,'world_war_2',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c14q${"question":"Hvad viser historisk forskning om de mennesker der udøvede Holocaust — hvem var gerningsmændene?","options":["Forskning som Christopher Brownings om Reservepolitibataljon 101 viser at mange gerningsmænd var ordinaere mennesker uden fanatisk ideologi — konformitetspres og lydighed over for autoritet var vigtigere motivationer end medfodt ondskab","Forskning viser entydigt at alle Holocaust-gerningsmaend var ideologisk overbevist om nazismens retfaerdighed","Forskning viser at Holocaust kun var mulig fordi alle gerningsmaend var psykisk syge og ikke normale mennesker","Historikere er enige om at kun en lille SS-elite var ansvarlig — den brede befolkning vidste intet og bidrog slet ikke"],"correct":"Forskning som Christopher Brownings om Reservepolitibataljon 101 viser at mange gerningsmænd var ordinaere mennesker uden fanatisk ideologi — konformitetspres og lydighed over for autoritet var vigtigere motivationer end medfodt ondskab","accepted_answers":["Forskning som Christopher Brownings om Reservepolitibataljon 101 viser at mange gerningsmænd var ordinaere mennesker uden fanatisk ideologi — konformitetspres og lydighed over for autoritet var vigtigere motivationer end medfodt ondskab"],"review_text":"I sin bog Ordinary Men (1992) analyserede Christopher Browning Reservepolitibataljon 101 — middelaldrende tyske mænd der ikke var SS-fanatikere. De fik valget om at deltage i masseudskydninger eller melde sig fra. Meget få meldte fra. Browning argumenterer at frygten for at skille sig ud, gruppepres og gradvis dehumanisering af ofrene var mere forklarende end ideologisk had. Hannah Arendt formulerede lignende pointer med begrebet det ondes banalitet i sin analyse af Adolf Eichmann. Det er en ubehagelig lektie: moralske katastrofer kræver ikke monstre — de kræver systemer der normaliserer ondskab."}$c14q$::jsonb,
  'mc','short',$c14m${"concepts":["ordinaere gerningsmaend","Browning","Arendt","det ondes banalitet","konformitet","lydighed"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"analytical_challenge","domain":"world_war_2"}$c14m$::jsonb,
  'mc_single',4,'auto',true,'world_war_2',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c15q${"question":"Hvad var den direkte årsag til at Tyskland blev delt i Vest- og Østtyskland efter 2. Verdenskrig?","options":["De fire sejrende magter delte Tyskland i besættelseszoner — den voksende spænding mellem vest og øst betød at de vestlige zoner fusionerede til Vesttyskland (BRD) og den sovjetiske zone blev til Østtyskland (DDR) i 1949","Det var en frivillig tysk beslutning at dele landet for at undgå fremtidige krige","FN besluttede at dele Tyskland som kollektiv straf for Holocaust og krigen","USA og Sovjet delte Tyskland fysisk i 1945 med en permanent mur fra dag ét"],"correct":"De fire sejrende magter delte Tyskland i besættelseszoner — den voksende spænding mellem vest og øst betød at de vestlige zoner fusionerede til Vesttyskland (BRD) og den sovjetiske zone blev til Østtyskland (DDR) i 1949","accepted_answers":["De fire sejrende magter delte Tyskland i besættelseszoner — den voksende spænding mellem vest og øst betød at de vestlige zoner fusionerede til Vesttyskland (BRD) og den sovjetiske zone blev til Østtyskland (DDR) i 1949"],"review_text":"Efter Tysklands kapitulation i maj 1945 delte USA, Storbritannien, Frankrig og Sovjet landet i fire besættelseszoner. Berlin blev ligeledes delt. Oprindeligt var hensigten midlertidig — men den voksende ideologiske og politiske kløft mellem Vest og Øst (Den Kolde Krig) betød at de vestlige zoner fusionerede til Forbundsrepublikken Tyskland (BRD) i maj 1949, og den sovjetiske zone blev til Den Tyske Demokratiske Republik (DDR) i oktober 1949. Tyskland forblev delt i 40 år til Berlinmurens fald i 1989 og den formelle genforening i 1990."}$c15q$::jsonb,
  'mc','short',$c15m${"concepts":["Tysklands deling","besættelseszoner","BRD","DDR","1949","Den Kolde Krig"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"causal","insight_type":"concept_clarification","challenge_role":"analytical_challenge","domain":"world_war_2"}$c15m$::jsonb,
  'mc_single',4,'auto',true,'world_war_2',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c16q${"question":"Hvad viser den internationale reaktion på nazisternes jødeforfølgelse i 1930'erne om tilskueres ansvar?","options":["Mange lande vidste om forfølgelserne men lukkede grænserne for jødiske flygtninge og reagerede ikke militært — det viser at passivitet ikke er neutral men kan muliggøre forfølgelse","Alle vestlige lande åbnede straks deres grænser for jødiske flygtninge da forfølgelserne begyndte","Ingen lande vidste noget om forfølgelserne af jøder før befrielsen af lejrene i 1945","FN fordømte nazisternes forfølgelse af jøder officielt i 1937 og krævede at det stoppede"],"correct":"Mange lande vidste om forfølgelserne men lukkede grænserne for jødiske flygtninge og reagerede ikke militært — det viser at passivitet ikke er neutral men kan muliggøre forfølgelse","accepted_answers":["Mange lande vidste om forfølgelserne men lukkede grænserne for jødiske flygtninge og reagerede ikke militært — det viser at passivitet ikke er neutral men kan muliggøre forfølgelse"],"review_text":"I 1938 mødtes 32 nationer i Évian i Frankrig for at diskutere den jødiske flygtningekrise. Næsten alle lukkede dørene — inklusive USA og Storbritannien der var bange for at importere fattigdom og antisemitisk modstand hjemme. Det tyske regime noterede tilfreds at Vesten talte om humanitære hensyn men i praksis nægtede at tage imod jøderne. Denne internationale passivitet i 1930'erne er ikke den direkte årsag til Holocaust — men den fjernede en mulig flugtvej. At tilskuere — individer, institutioner og nationer — har et ansvar for at reagere på forfølgelse er en central etisk lektie fra 2. Verdenskrig."}$c16q$::jsonb,
  'mc','short',$c16m${"concepts":["tilskueres ansvar","flygtninge","Évian","passivitet","international reaktion","bystanders"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"analytical_challenge","domain":"world_war_2"}$c16m$::jsonb,
  'mc_single',4,'auto',true,'world_war_2',7,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c17q${"question":"Hvad kendetegnede behandlingen af civile i 2. Verdenskrig sammenlignet med 1. Verdenskrig?","options":["2. Verdenskrig var i langt højere grad en krig mod civile — strategiske bombninger af byer, udryddelseslejre og systematisk folkemord betød at et flertal af de ca. 70-85 millioner ofre var civile ikke soldater","2. Verdenskrig havde proportionelt færre civile ofre end 1. Verdenskrig fordi bombardementsteknikken var mere præcis","2. Verdenskrig var en rent militær konflikt — civile befolkninger var beskyttet og ikke involveret i kamphandlingerne","Behandlingen af civile var identisk i 1. og 2. Verdenskrig da begge krige fulgte de samme folkeretslige regler"],"correct":"2. Verdenskrig var i langt højere grad en krig mod civile — strategiske bombninger af byer, udryddelseslejre og systematisk folkemord betød at et flertal af de ca. 70-85 millioner ofre var civile ikke soldater","accepted_answers":["2. Verdenskrig var i langt højere grad en krig mod civile — strategiske bombninger af byer, udryddelseslejre og systematisk folkemord betød at et flertal af de ca. 70-85 millioner ofre var civile ikke soldater"],"review_text":"1. Verdenskrig var primært en krig mellem soldater i skyttegrave — civile ofre var massive men overvejende indirekte (sult, sygdom). 2. Verdenskrig brød med dette: bomber over London, Dresden, Tokyo og Hiroshima dræbte bevidst civile. Holocaust udryddede seks millioner civile jøder systematisk. Japanske massedrab i Kina (Nanjing-massakren). Tyske destruktioner af byer i Sovjet og Polen. Af de anslået 70-85 millioner krigsofre var 40-55% civile. Det ændrede fundamentalt den internationale folkeretslige forståelse af hvad krig er og hvem der er legitimt mål."}$c17q$::jsonb,
  'mc','short',$c17m${"concepts":["civile ofre","total krig","bombninger","Holocaust","folkemord","folkeretten"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"analytical_challenge","domain":"world_war_2"}$c17m$::jsonb,
  'mc_single',4,'auto',true,'world_war_2',7,4
);

-- ─── BAND 5 (3 questions) ─────────────────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c18q${"question":"Var USA's brug af atombomber mod Hiroshima og Nagasaki moralsk forsvarlig — og hvad siger den historiske debat?","options":["En vedvarende etisk og historisk debat: forsvarerne argumenterer at bomberne forkortede krigen og reddede millioner af liv ved at undgå en blodig landinvasion — kritikerne svarer at Japan allerede var tæt på overgivelse og at massedrabet på civile aldrig kan retfærdiggøres","Der er historisk og etisk konsensus om at atombomberne var fuldstændig moralsk forsvarlige og retfærdige","Der er historisk og etisk konsensus om at atombomberne var en krigsforbrydelse og USA er officielt blevet domfældt for det","Debatten er rent teknisk og handler kun om militær effektivitet — etik er irrelevant i krig"],"correct":"En vedvarende etisk og historisk debat: forsvarerne argumenterer at bomberne forkortede krigen og reddede millioner af liv ved at undgå en blodig landinvasion — kritikerne svarer at Japan allerede var tæt på overgivelse og at massedrabet på civile aldrig kan retfærdiggøres","accepted_answers":["En vedvarende etisk og historisk debat: forsvarerne argumenterer at bomberne forkortede krigen og reddede millioner af liv ved at undgå en blodig landinvasion — kritikerne svarer at Japan allerede var tæt på overgivelse og at massedrabet på civile aldrig kan retfærdiggøres"],"review_text":"Debatten om atombomberne er en af moderne histories mest vedvarende etiske diskussioner. Forsvarerne (traditionelle historikere): en landinvasion af Japan kunne have kostet en million amerikanske og millioner af japanske liv — bomberne afkortede krigen og reddede liv netto. Kritikerne (revisionister fra 1960'erne): japanske signaler om overgivelsesvilje var allerede tydelige; bomberne var primært geopolitisk signalering over for Sovjet; og massedrab på civile kan aldrig retfærdiggøres uanset strategisk mål. En tredje position: begge faktorer var reelle — den moralske vurdering afhænger af hvilke konsekvenser man tillægger størst vægt. Debatten er ikke afsluttet."}$c18q$::jsonb,
  'mc','short',$c18m${"concepts":["atombomber","etisk debat","Hiroshima","landinvasion","civile ofre","historikerdebat"],"misconception_type":"overgeneralization","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}$c18m$::jsonb,
  'mc_single',5,'auto',true,'world_war_2',7,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c19q${"question":"Hvad fortæller Milgrams lydighedseksperiment (1961) om de psykologiske mekanismer bag Holocaust?","options":["Eksperimentet viste at ordinaere mennesker er villige til at paafore andre alvorlig skade naar en autoritetsfigur beordrer dem til det — det understøtter Hannah Arendts tese om det ondes banalitet og viser at Holocaust ikke kraevede monstre men systemer der normaliserede lydighed","Eksperimentet beviste at alle mennesker er naturligt onde og bevidst oensker at skade andre","Eksperimentet er videnskabeligt ugyldigt og bruges aldrig i serioes historisk forskning om Holocaust","Eksperimentet viser at Holocaust kun var mulig fordi tyskerne genetisk er mere lydige end andre folk"],"correct":"Eksperimentet viste at ordinaere mennesker er villige til at paafore andre alvorlig skade naar en autoritetsfigur beordrer dem til det — det understøtter Hannah Arendts tese om det ondes banalitet og viser at Holocaust ikke kraevede monstre men systemer der normaliserede lydighed","accepted_answers":["Eksperimentet viste at ordinaere mennesker er villige til at paafore andre alvorlig skade naar en autoritetsfigur beordrer dem til det — det understøtter Hannah Arendts tese om det ondes banalitet og viser at Holocaust ikke kraevede monstre men systemer der normaliserede lydighed"],"review_text":"Stanley Milgram udforte sit beroemte lydigheds-eksperiment i 1961 i kolvandet paa Eichmann-retssagen. Forsøgspersoner (ordinaere amerikanere) blev bedt om at give elektrisk stoede til en skuespiller i et andet rum naar en forsøgsleder sagde at de skulle forsaette. 65 procent gave de stoerkeste stoede paa troeds af hoere raab om smerter. Milgram fortolkede resultatet som lydighed over for autoritet under et system der frigjorde individet fra ansvar. Hannah Arendt havde to aar forinden moentet begrebet det ondes banalitet om Adolf Eichmann — en bureaukrat der organiserede Holocaust ikke af had men af pedantisk embedslydig. Begge perspektiver understreger at moralsk ondskab ikke kraever moralske monstre."}$c19q$::jsonb,
  'mc','short',$c19m${"concepts":["Milgram","lydighed","autoritet","Arendt","det ondes banalitet","psykologi og Holocaust"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}$c19m$::jsonb,
  'mc_single',5,'auto',true,'world_war_2',7,5
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  $c20q${"question":"Hvad er den vigtigste historiske lektie fra 2. Verdenskrig for forståelsen af demokratiets skrøbelighed?","options":["At demokratier kan demokratisk vaelge en leder der afvikler demokratiet — Hitlers magtovertagelse var ikke et coup men et produkt af valgsystemets sammenbrud under ekstrem okonomisk krise og social stress der forpligter nutidige demokratier til aktiv forfatningsbeskyttelse","Demokratier er naturligt selvopretholdte og kan aldrig kollapse indefra — 2. Verdenskrig er et unikt historisk undtagelsestilfaelde","Lektien fra 2. Verdenskrig er udelukkende militaer: demokratier skal have staerke haere for at forhindre invasion","Demokratiet var ikke under pres i 2. Verdenskrig — Hitler kom til magten via militaerkup ikke demokratiske valg"],"correct":"At demokratier kan demokratisk vaelge en leder der afvikler demokratiet — Hitlers magtovertagelse var ikke et coup men et produkt af valgsystemets sammenbrud under ekstrem okonomisk krise og social stress der forpligter nutidige demokratier til aktiv forfatningsbeskyttelse","accepted_answers":["At demokratier kan demokratisk vaelge en leder der afvikler demokratiet — Hitlers magtovertagelse var ikke et coup men et produkt af valgsystemets sammenbrud under ekstrem okonomisk krise og social stress der forpligter nutidige demokratier til aktiv forfatningsbeskyttelse"],"review_text":"Weimarrepublikkens kollaps er demokratihistoriens mest studerede fallit. Den tyske forfatning af 1919 var progressiv — men den indeholdt noedudstykkene der tillod suspensionen af borgernes rettigheder under undtagelsestilstand (§ 48). Hyperinflation i 1923, verdenskrisen fra 1929 og politisk fragmentering skabte kaos og fortvivlelse som Hitler og NSDAP udnyttede. I januar 1933 blev Hitler udnaevnt til kansler af den aeldgamle Hindenburg — ad legal vej, ikke ved statskup. Den tyske demokratiske institution valgte sin egen baeddelmand. Det er den dybeste lektie: demokrati er ikke en selvfoelge men kraever aktiv vedligeholdelse, forfatningsbeskyttelse og borgere der forsvarer dets principper ogsaa under krisetider."}$c20q$::jsonb,
  'mc','short',$c20m${"concepts":["demokratiets skrøbelighed","Weimarrepublikken","Hitler","forfatningsbeskyttelse","valgsystemets sammenbrud","borgerpligt"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_2"}$c20m$::jsonb,
  'mc_single',5,'auto',true,'world_war_2',7,5
);
