-- Section 82 — World War 1 — Grade 8 (25 questions)

-- ─── GRADE 8 · BAND 1 (6 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betoekner forkortelsen MAIN som beskriver aarsagerne til Forste Verdenskrig?","options":["Militarisme, Alliancer, Imperialisme og Nationalisme","Moerke, Angreb, Invasion og Neutralitet","Magt, Agression, Interesser og Naboer","Mobilisering, Anneksion, Information og Normer"],"correct":"Militarisme, Alliancer, Imperialisme og Nationalisme","accepted_answers":["Militarisme, Alliancer, Imperialisme og Nationalisme"],"review_text":"Historikere bruger MAIN som huskeregel. Militarisme: rustningskaapplobet. Alliancer: automatiske forpligtelser. Imperialisme: kolonirivalisering. Nationalisme: stolthed og fjendskab. Ingen enkelt aarsag men alle fire samlet."}'::jsonb,
  'mc','short','{"concepts":["MAIN","militarisme","alliancer","imperialisme","nationalisme"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_1',8,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvilke lande udgoerde Triple Entente og Triple Alliance foer Forste Verdenskrig?","options":["Triple Entente: Frankrig, Rusland og England. Triple Alliance: Germany, Oestrig-Ungarn og Italien","Triple Entente: Germany, Oestrig-Ungarn og Tyrkiet. Triple Alliance: Frankrig, Rusland og England","Begge alliancer bestod af de samme fem lande","Triple Entente: USA, England og Frankrig. Triple Alliance: Germany og Oestrig"],"correct":"Triple Entente: Frankrig, Rusland og England. Triple Alliance: Germany, Oestrig-Ungarn og Italien","accepted_answers":["Triple Entente: Frankrig, Rusland og England. Triple Alliance: Germany, Oestrig-Ungarn og Italien"],"review_text":"Europa var delt i to lejer. Triple Entente vandt. Men ved krigens start skiftede Italien side og England og Frankrig fik USA med i 1917. Alliancerne var ikke faste men de skabte automatiske forpligtelser."}'::jsonb,
  'mc','short','{"concepts":["Triple Entente","Triple Alliance","alliancer","krigsdeltagere"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_1',8,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvornaar og hvor udkaempedes Forste Verdenskrig?","options":["1914-1918 primaert i Europa men ogsaa i Mellemøesten, Afrika og Asien","1910-1918 kun i Europa","1914-1920 kun paa Vestfronten","1916-1918 primaert i Rusland og Tyrkiet"],"correct":"1914-1918 primaert i Europa men ogsaa i Mellemøesten, Afrika og Asien","accepted_answers":["1914-1918 primaert i Europa men ogsaa i Mellemøesten, Afrika og Asien"],"review_text":"Krigen varede fra august 1914 til november 1918. Vestfronten i Frankrig og Belgien var den mest beromte. Men der var ogsaa Oestfronten mod Rusland, krig i Mellemoeesten og soeslag i Atlanterhavet."}'::jsonb,
  'mc','short','{"concepts":["krig 1914-1918","fronter","Vestfronten","global konflikt"],"misconception_type":"scope_confusion","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_1',8,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad indeholdt Versailles-traktaten fra 1919?","options":["Germany fik skylden for krigen, maatte betale store erstatninger og afgive territorier","Alle lande fik ens betingelser og delte krigsomkostningerne ligeligt","Traktaten garanterede Germany beskyttelse mod fremtidige angreb","Traktaten skabte et forenet Europa med faelles graenser"],"correct":"Germany fik skylden for krigen, maatte betale store erstatninger og afgive territorier","accepted_answers":["Germany fik skylden for krigen, maatte betale store erstatninger og afgive territorier"],"review_text":"Paragraf 231 var krigsscyldsklausulen. Germany fik skylden for hele krigen. Det skulle betale massive erstatninger og afstaa territorier herunder Alsace-Lorraine. Germany mistede ogsaa sine kolonier og store dele af sin haer."}'::jsonb,
  'mc','short','{"concepts":["Versailles","krigsscyldsklausul","erstatninger","territorier","1919"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_1',8,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvilke nye vaabentyper blev indfoert i Forste Verdenskrig?","options":["Tanks, fly, undervandsbaade og kemiske vaaaben som giftgas","Nukleare bomber og ballistiske missiler","Lasservaaben og droner","Maskingevaeret var den eneste nye teknologi"],"correct":"Tanks, fly, undervandsbaade og kemiske vaaaben som giftgas","accepted_answers":["Tanks, fly, undervandsbaade og kemiske vaaaben som giftgas"],"review_text":"Tanks broede igennem skyttegravslinjer. Fly patruljerede og bombede. Undervandsbaade angreb forsyningsskibe. Giftgas var den mest frygtede nyhed. Alle disse teknologier var nye og aendrede krigsforlobet."}'::jsonb,
  'mc','short','{"concepts":["tanks","fly","undervandsbaade","giftgas","ny teknologi"],"misconception_type":"false_equivalence","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_1',8,1
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betod begrebet total krig under Forste Verdenskrig?","options":["At hele samfundet var mobiliseret til krig herunder fabrikker, kvinder, okonomi og propaganda","At krigen foregik 24 timer i dognet uden pauser","At alle militaere ressourcer blev brugt paa een gang","At krigen spredte sig til alle verdensdele"],"correct":"At hele samfundet var mobiliseret til krig herunder fabrikker, kvinder, okonomi og propaganda","accepted_answers":["At hele samfundet var mobiliseret til krig herunder fabrikker, kvinder, okonomi og propaganda"],"review_text":"Total krig betod at skellet mellem civil og militaer sloev. Fabrikker producerede vaaaben. Kvinder arbejdede i industrien. Okonomier blev omstillet til krigsproduktion. Staten kontrollerede madvarer og information."}'::jsonb,
  'mc','short','{"concepts":["total krig","mobilisering","hjemmefront","stat","civil-militaer"],"misconception_type":"scope_confusion","cognitive_skill":"recall","difficulty_type":"factual","insight_type":"conceptual_bridge","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',1,'auto',true,'world_war_1',8,1
);

-- ─── GRADE 8 · BAND 2 (7 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvordan skabte europaeisk imperialisme konkrete spaendinger foer Forste Verdenskrig?","options":["Rivalisering om kolonier i Afrika og Asien skabte gensidig frygt og konkurrence der goerede krig mere sandsynlig","Imperialisme skabte fred fordi lande var for optagede af kolonier til at kaempe","Kun Frankrig og England rivaliserede om kolonier resten var neutrale","Imperialisme var ikke relateret til krigen"],"correct":"Rivalisering om kolonier i Afrika og Asien skabte gensidig frygt og konkurrence der goerede krig mere sandsynlig","accepted_answers":["Rivalisering om kolonier i Afrika og Asien skabte gensidig frygt og konkurrence der goerede krig mere sandsynlig"],"review_text":"Marokko-kriserne i 1905 og 1911 bragte Frankrig og Germany naer ved krig. Konkurrence om Afrika og Asien forstaerkede militarismen. Imperialisme bidrog til atmosfaeren af rivalisering og mistillid."}'::jsonb,
  'mc','short','{"concepts":["imperialisme","kolonier","rivalisering","Marokko-kriserne","spaendinger"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_1',8,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvorfor gik Vestfronten i staa i en blodig doedvande?","options":["Defensiv teknologi som maskingevaerer og artilleri var langt staerkere end angrebsteknologi saa ingen side kunne bryde igennem","Soldaterne paa begge sider naegtede at angribe","Vejrliget umuliggjorde fremrykning","Alliancerne naegtede at sende nok soldater"],"correct":"Defensiv teknologi som maskingevaerer og artilleri var langt staerkere end angrebsteknologi saa ingen side kunne bryde igennem","accepted_answers":["Defensiv teknologi som maskingevaerer og artilleri var langt staerkere end angrebsteknologi saa ingen side kunne bryde igennem"],"review_text":"Et enkelt maskingevaer kunne holde et helt kompagni tilbage. Artilleri forvandlede slagmarken til mudder. Angreb paa befoestede stillinger kostede enormt mange liv for minimale gevinster. Krigen gik i staa i naesten fire aar."}'::jsonb,
  'mc','short','{"concepts":["Vestfronten","doedvande","defensiv teknologi","angreb","maskingevaer"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_1',8,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvilke konkrete teknikker brugte krigstidens propaganda?","options":["Plakater der fremstillede fjenden som monster, censurerede aviser og film der heroiserede egne soldater","Propaganda var baseret paa faktuelle nyheder","Propaganda brugte kun radio der ikke fandtes foer 1920","Propaganda var frivillig og ingen tvang borgere til at se den"],"correct":"Plakater der fremstillede fjenden som monster, censurerede aviser og film der heroiserede egne soldater","accepted_answers":["Plakater der fremstillede fjenden som monster, censurerede aviser og film der heroiserede egne soldater"],"review_text":"Propagandaplakater fremstillede tyske soldater som barbariske mordere. Aviser var censurerede. Film viste heroiske soldater. Maal: faa maeand til at melde sig, faa kvinder til at stoette krigen og fastholde civil moral."}'::jsonb,
  'mc','short','{"concepts":["plakater","censur","film","fjendebillede","propaganda-teknikker"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_1',8,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betod det at Forste Verdenskrig var en total krig for hjemmefronten?","options":["Staten kontrollerede okonomien, rationerede mad og mobiliserede kvinder til industriarbejde","Civile bag fronten var fuldt beskyttede","Kun civile naer fronten var paavirket","Den civile okonomi voksede og alle levede bedre"],"correct":"Staten kontrollerede okonomien, rationerede mad og mobiliserede kvinder til industriarbejde","accepted_answers":["Staten kontrollerede okonomien, rationerede mad og mobiliserede kvinder til industriarbejde"],"review_text":"Hjemmefronten var en del af krigen. Mad blev rationeret. Fabrikkerne producerede vaaaben. Kvinder overtog jobs. Staten censurerede pressen. Hjemmefronten var ikke bagland men en aktiv del af krigsindsatsen."}'::jsonb,
  'mc','short','{"concepts":["hjemmefront","total krig","rationering","kvinder","statskontrol"],"misconception_type":"scope_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_1',8,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad fik USA til at gaa ind i Forste Verdenskrig i 1917?","options":["Tysk ubadskrig mod neutrale skibe og Zimmermann-telegrammet der tilbod Mexico amerikansk territorium","USA var allierede med England fra starten","Germany angreb amerikansk territorium direkte","Frankrig var ved at tabe og USA ville redde sine allierede"],"correct":"Tysk ubadskrig mod neutrale skibe og Zimmermann-telegrammet der tilbod Mexico amerikansk territorium","accepted_answers":["Tysk ubadskrig mod neutrale skibe og Zimmermann-telegrammet der tilbod Mexico amerikansk territorium"],"review_text":"USA var neutral fra start. Men Germanys ubadskrig sank civile skibe herunder amerikanske. Zimmermann-telegrammet var et hemmeligt forsoeg paa at overtale Mexico til at angribe USA. Begge dele fik USA med i krigen."}'::jsonb,
  'mc','short','{"concepts":["USA","ubadskrig","Zimmermann-telegram","neutralitet","1917"],"misconception_type":"causal_inversion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_1',8,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad skete der med de store europaeiske imperier som foelge af Forste Verdenskrig?","options":["Det Osmanniske, Oestrig-Ungarnske, Russiske og Tyske kejserrige broede alle samman","Alle imperier overlevede krigen og fortsatte til 1945","Kun Germany mistede sit imperium de andre overlevede","Imperierene forstaearkedes fordi de vandt nye kolonier"],"correct":"Det Osmanniske, Oestrig-Ungarnske, Russiske og Tyske kejserrige broede alle samman","accepted_answers":["Det Osmanniske, Oestrig-Ungarnske, Russiske og Tyske kejserrige broede alle samman"],"review_text":"Krigen udraderede fire store imperier. Det Russiske Kejserrige faldt i revolutionen 1917. Oestrig-Ungarn oplostes i mange nye stater. Det Tyske Kejserrige endte. Det Osmanniske Rige oplostes. Europas kort var radikalt forandret."}'::jsonb,
  'mc','short','{"concepts":["imperierenes fald","Rusland","Oestrig-Ungarn","Germany","Osmannerriget","konsekvenser"],"misconception_type":"temporal_confusion","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"reframing","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_1',8,2
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad forklarer at soldaterne fortsatte med at adlyde ordrer selvom de vidste et angreb ville koste mange liv?","options":["Kombination af disciplin, kammeratskab, frygt for doedsstraffen og tro paa at kampen tjente et hoejere formaal","Soldaterne vidste ikke at de ville doe","Soldaterne naegtede faktisk tit og der var konstante mytinier","Soldaterne var paavirket af stoffer og vidste ikke hvad de goerde"],"correct":"Kombination af disciplin, kammeratskab, frygt for doedsstraffen og tro paa at kampen tjente et hoejere formaal","accepted_answers":["Kombination af disciplin, kammeratskab, frygt for doedsstraffen og tro paa at kampen tjente et hoejere formaal"],"review_text":"At naegte en ordre i krig betod doedsstraffen. Kammeratskab betod at man ikke ville svigte dem ved siden af sig. Propaganda overbeviste mange om at de kaeempede for noget vigtigt. Alt dette holdt massedesertioner i skak."}'::jsonb,
  'mc','short','{"concepts":["lydighed","kammeratskab","doedsstraffen","propaganda","disciplin"],"misconception_type":"false_equivalence","cognitive_skill":"comprehension","difficulty_type":"conceptual","insight_type":"perspective_shift","challenge_role":"reinforcement","domain":"world_war_1"}'::jsonb,
  'mc_single',2,'auto',true,'world_war_1',8,2
);

-- ─── GRADE 8 · BAND 3 (7 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er problemet med Versailles-traktatens konklusion om at Germany var eneansvarlig for krigen?","options":["Det var en politisk ydmygelse der ignorerede at alle store magter bidrog til de spaendinger der eksploderede i 1914","Der er intet problem Germany var faktisk eneansvarlig","Problemet er at Rusland og Frankrig burde have delt ansvaret","Problemet er kun at formuleringen var for mild"],"correct":"Det var en politisk ydmygelse der ignorerede at alle store magter bidrog til de spaendinger der eksploderede i 1914","accepted_answers":["Det var en politisk ydmygelse der ignorerede at alle store magter bidrog til de spaendinger der eksploderede i 1914"],"review_text":"Krigsscyldsklausulen var politisk ikke historisk. Sejrherrerne ville have Germany til at betale. Men England, Frankrig, Rusland og Oestrig-Ungarn bidrog alle til optrapningen. Det er konsensus blandt historikere i dag."}'::jsonb,
  'mc','short','{"concepts":["krigsansvar","Versailles","politisk beslutning","delt ansvar","historisk konsensus"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_1',8,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad forklarer at Forste Verdenskrig varede fire aar naer alle forventede den sluttede foer julen 1914?","options":["Defensiv teknologi skaabte en blodig doedvande og ingen side kunne opnaa det afgoorende gennembrud","Lederne paa begge sider oenskede bevidst at forlange krigen","Ingen af parterne oenskede fred","Vaabenstillstand var ulovlig under international ret"],"correct":"Defensiv teknologi skaabte en blodig doedvande og ingen side kunne opnaa det afgoorende gennembrud","accepted_answers":["Defensiv teknologi skaabte en blodig doedvande og ingen side kunne opnaa det afgoorende gennembrud"],"review_text":"Alle troede krigen ville vaere kort. Schlieffen-planen haabede paa seks uger. Men maskingevaerer og artilleri fastlaaeste fronterne. Ingen teknologi var god nok til at bryde igennem. Fire aars gensidigt blodbad folgede."}'::jsonb,
  'mc','short','{"concepts":["varighed","doedvande","Schlieffen","teknologi","forventninger"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_1',8,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er den direkte forbindels mellem Versailles-traktaten og Anden Verdenskrigs udbrud?","options":["Traktatens haardhed skabte okonomisk nod og national ydmygelse i Germany der gav Hitler og NSDAP den opbakning de behoevede","Der er ingen forbindels de to traktater var fuldstaendig separate","Traktaten forhindrede faktisk Anden Verdenskrig i 20 aar","Forbindelsen er kun at begge krige begyndte i Europa"],"correct":"Traktatens haardhed skabte okonomisk nod og national ydmygelse i Germany der gav Hitler og NSDAP den opbakning de behoevede","accepted_answers":["Traktatens haardhed skabte okonomisk nod og national ydmygelse i Germany der gav Hitler og NSDAP den opbakning de behoevede"],"review_text":"Den tyske okonomis kollaps under kravet om krigsudgifter og den nationale ydmygelse ved at acceptere eneansvar var giftige betingelser. Da Den Store Depression ramte i 1929 udnyttede Hitler bevidst hadet mod Versailles."}'::jsonb,
  'mc','short','{"concepts":["Versailles","Hitler","NSDAP","Den Store Depression","WWI-WWII forbindels"],"misconception_type":"temporal_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_1',8,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betod Forste Verdenskrig for de koloniserede folk i Afrika og Asien?","options":["De blev tvunget til at kaempe og doe i andres krig og fik ikke de friheder de var lovet som beloening bagefter","Koloniserede folk var fuldt frivillige og begejstrede deltagere","Koloniserede folk kaeampede ikke i krigen","Koloniserede folk fik fuld selvstaendighed straks efter krigen"],"correct":"De blev tvunget til at kaempe og doe i andres krig og fik ikke de friheder de var lovet som beloening bagefter","accepted_answers":["De blev tvunget til at kaempe og doe i andres krig og fik ikke de friheder de var lovet som beloening bagefter"],"review_text":"Over en million soldater fra franske og britiske kolonier kaeampede i krigen. Mange var tvangsindrullerede. De fik loefter om politiske reformer. Men efter krigen geninfoerte kolonimagterne det gamle system. Det saaede froe til befrielsesbevaegelserne der folgete."}'::jsonb,
  'mc','short','{"concepts":["kolonier","kolonifolk","tvang","loefter","befrielsesbevaegelser"],"misconception_type":"scope_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"perspective_shift","challenge_role":"challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_1',8,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad skete der med statens magt over borgerne under Forste Verdenskrig?","options":["Staten fik enorm magt via censur, rationering, tvangsindkaldelse og kontrol med okonomien","Statens magt mindsksdes fordi krigen var for kaotisk til at kontrollere","Staten mistede kontrol og borgerne styrede sig selv","Statens magt over borgerne aendrede sig ikke"],"correct":"Staten fik enorm magt via censur, rationering, tvangsindkaldelse og kontrol med okonomien","accepted_answers":["Staten fik enorm magt via censur, rationering, tvangsindkaldelse og kontrol med okonomien"],"review_text":"Total krig kraevede total kontrol. Staten bestemte hvad aviser maatte skrive. Den rationerede mad. Fabrikker omstillede sig til krigsproduktion. Tvangsindkaldelse sendte maeand til fronten mod deres vilje. Staten voksede dramatisk under krigen."}'::jsonb,
  'mc','short','{"concepts":["statsmagt","censur","tvangsindkaldelse","rationering","total krig"],"misconception_type":"causal_inversion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_1',8,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Paa hvilken maade var nationalisme en dobbeltaegget klinge i perioden foer Forste Verdenskrig?","options":["Den styrkede indenrigsk sammenhold men skabte fjendskab og rivalisering der goerede kompromis svaerere","Nationalisme var rent positiv og bidrog ikke til krigen","Nationalisme var rent negativ og ingen saa noget godt i den","Nationalisme opstod som konsekvens af krigen ikke foer den"],"correct":"Den styrkede indenrigsk sammenhold men skabte fjendskab og rivalisering der goerede kompromis svaerere","accepted_answers":["Den styrkede indenrigsk sammenhold men skabte fjendskab og rivalisering der goerede kompromis svaerere"],"review_text":"Nationalisme sammensvejsede borgerne og goerede dem villige til at kaempe for landets skyld. Men det betod ogsaa at man saa fjenden som grundlaeggende anderledes og mindrevaerdig. Det goerede fredelige loesninger svaerere."}'::jsonb,
  'mc','short','{"concepts":["nationalisme","sammenhold","fjendskab","dobbelttydig","kompromis"],"misconception_type":"overgeneralization","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_1',8,3
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad betod Forste Verdenskrig for den europaeiske verdensorden der had eksisteret siden 1815?","options":["Den udraderede den gamle orden: fire kejserriger faldt, nye nationer opstod og USA og Sovjet begyndte at erstatte Europa som verdens center","Den bevarede den gamle orden men med Germany som ny dominerende magt","Den styrkede den gamle orden fordi England og Frankrig sejrede","Den europaeiske orden aendrede sig ikke foerend Anden Verdenskrig"],"correct":"Den udraderede den gamle orden: fire kejserriger faldt, nye nationer opstod og USA og Sovjet begyndte at erstatte Europa som verdens center","accepted_answers":["Den udraderede den gamle orden: fire kejserriger faldt, nye nationer opstod og USA og Sovjet begyndte at erstatte Europa som verdens center"],"review_text":"Den europaeiske orden fra 1815 rasede i suel. Kejserriger forsvandt. Graenser blev omtegnet. Wilson introducerede folkenes selvbestemmelsesprincip. Europa var ikke laengere alene om at bestemme verdens skaebne."}'::jsonb,
  'mc','short','{"concepts":["verdensorden","kejserriger","nye nationer","USA","Sovjet","Europa"],"misconception_type":"temporal_confusion","cognitive_skill":"analysis","difficulty_type":"analytical","insight_type":"reframing","challenge_role":"challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',3,'auto',true,'world_war_1',8,3
);

-- ─── GRADE 8 · BAND 4 (5 questions) ─────────────────────────────────────────

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Var Forste Verdenskrig uundgaaelig?","options":["Det debatteres stadig. Strukturelle spaendinger var enorme men konkrete politiske beslutninger i juli 1914 kunne have stoppet krigen","Ja krigen var fuldstaendig uundgaaelig givet de strukturelle betingelser","Nej krigen var et tilfaeldigt uheld som nemt kunne vaere undgaaet","Krigen var uundgaaelig fordi Germany planlagde den systematisk i aartier"],"correct":"Det debatteres stadig. Strukturelle spaendinger var enorme men konkrete politiske beslutninger i juli 1914 kunne have stoppet krigen","accepted_answers":["Det debatteres stadig. Strukturelle spaendinger var enorme men konkrete politiske beslutninger i juli 1914 kunne have stoppet krigen"],"review_text":"Strukturalisterne siger spaendingerne var saa store at noget maatte eksplodere. Andre peeger paa at lederne i de afgoorende julidage 1914 aktivt valgte eskalering frem for kompromis. Sandsynligvis bidrog begge: strukturerne skaabte betingelserne men mennesker traf beslutningerne."}'::jsonb,
  'mc','short','{"concepts":["uundgaaelighed","strukturer","beslutninger","julidagene","historisk debat"],"misconception_type":"causal_inversion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_1',8,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Var Versailles-traktaten en retfaerdig fred eller en opskrift paa ny krig?","options":["Begge dele paa en gang: forstaaeelig fra sejrherrernes perspektiv men saa haard at den saaede froe til den naeste krig","Den var fuldt retfaerdig og ingen historiker kritiserer den","Den var katastrofalt uretfaerdig og ingen vidste bedre","Den var saa mild at det var grunden til at Hitler kom til magten"],"correct":"Begge dele paa en gang: forstaaeelig fra sejrherrernes perspektiv men saa haard at den saaede froe til den naeste krig","accepted_answers":["Begge dele paa en gang: forstaaeelig fra sejrherrernes perspektiv men saa haard at den saaede froe til den naeste krig"],"review_text":"Fra fransk perspektiv var haardhed forstaaeelig: Frankrig var haerget. Men okonomisten Keynes forudsagde i 1919 at traktatens betingelser ville skabe en ny krig inden 20 aar. Han fik desvaerre ret i 1939."}'::jsonb,
  'mc','short','{"concepts":["Versailles","retfaerdig fred","Keynes","konsekvenser","perspektiver"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_1',8,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad viser brugen af propaganda i England, Frankrig og USA om forholdet mellem demokrati og statsstyret manipulation?","options":["At demokratier er villige til at manipulere borgerne i eksistentielle kriser og at medierne aktivt samarbejdede med staten","At demokratier aldrig bruger propaganda det goer kun diktaturer","At demokratiernes propaganda var fuldt etisk modsat diktaturers","At borgerne gennemskuede al propaganda og den var ineffektiv"],"correct":"At demokratier er villige til at manipulere borgerne i eksistentielle kriser og at medierne aktivt samarbejdede med staten","accepted_answers":["At demokratier er villige til at manipulere borgerne i eksistentielle kriser og at medierne aktivt samarbejdede med staten"],"review_text":"England oprettede et dedikeret Propagandaministerium. USA brugte Committee on Public Information. Aviser og film formidlede krigens noedvendighed. Borgerne i disse demokratier var udsat for statsstyret informationskrig der var meget effektiv."}'::jsonb,
  'mc','short','{"concepts":["propaganda","demokrati","statsstyret","manipulation","misconception-propaganda-kun-diktaturer"],"misconception_type":"scope_confusion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_1',8,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad fortaeller kloeften mellem krigstidens propaganda og soldaternes egne dagboeger om information og magt?","options":["At dem der styrer informationen kan forme virkelighed for store befolkningsgrupper og at censur aktivt holdt sandheden fra offentligheden","At soldaterne faktisk var enige med propagandaen","At propaganda aldrig virker fordi folk gennemskuer det","At informationskontrol kun var mulig foer aviser eksisterede"],"correct":"At dem der styrer informationen kan forme virkelighed for store befolkningsgrupper og at censur aktivt holdt sandheden fra offentligheden","accepted_answers":["At dem der styrer informationen kan forme virkelighed for store befolkningsgrupper og at censur aktivt holdt sandheden fra offentligheden"],"review_text":"Mens propaganda fremstillede heroisk krig levede soldaterne i mudder og gas. Breve hjem var censurerede. Det er et tidligt og magtfuldt eksempel paa at kontrol over information er kontrol over virkelighed."}'::jsonb,
  'mc','short','{"concepts":["informationskontrol","censur","magt","virkelighed","dagboeger"],"misconception_type":"false_equivalence","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_1',8,4
);

INSERT INTO public.questions (content, answer_format, answer_type, metadata, type, difficulty, question_type, is_active, learning_objective, target_grade, difficulty_band) VALUES (
  '{"question":"Hvad er Forste Verdenskrigs vigtigste arv til verden i dag?","options":["At verdenskrig er mulig og at nationalisme, rivalisering og svage internationale institutioner kan bringe civilisationer til ruinens rand","At teknologisk overlegenhed altid afgoer en krig","At demokratier aldrig goer krig mod hinanden","At Europas dominans over verden er permanent og urokkeaelig"],"correct":"At verdenskrig er mulig og at nationalisme, rivalisering og svage internationale institutioner kan bringe civilisationer til ruinens rand","accepted_answers":["At verdenskrig er mulig og at nationalisme, rivalisering og svage internationale institutioner kan bringe civilisationer til ruinens rand"],"review_text":"Forste Verdenskrig draebte 20 millioner. Den udraderede fire imperier. Den saaede froe til den naeste krig. Dens lektie: den internationale orden er skroebelig og krig er aldrig det korte sejrstogt man lover. Det var baggrunden for FN og det europaeiske integrationsprojekt."}'::jsonb,
  'mc','short','{"concepts":["arv","FN","europaeisk integration","lektie","international orden"],"misconception_type":"temporal_confusion","cognitive_skill":"evaluation","difficulty_type":"applied","insight_type":"perspective_shift","challenge_role":"deep_challenge","domain":"world_war_1"}'::jsonb,
  'mc_single',4,'auto',true,'world_war_1',8,4
);;
